### ISSUE TITLE
Controller does not remove nodes from target groups when exclude balancer labels are added

### ISSUE THREAD

**Issue by rabbitfang** [kubernetes-sigs/aws-load-balancer-controller#1043]
When a node has the `alpha.service-controller.kubernetes.io/exclude-balancer=true` label, the ALB controller will [count the node as invalid](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/b5873f485133dcaa4978adb38edb82b2d306ae2f/internal/ingress/annotations/class/main.go#L49) and will exclude the node from being added to target groups. However, [node updates do not trigger reconciliation](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/b5873f485133dcaa4978adb38edb82b2d306ae2f/internal/ingress/controller/handlers/node.go#L43) (probably because Node objects are updated very frequently). This means that adding the label does not immediately cause the node to be removed from target groups. Instead, it happens when something else triggers reconciliation, like a new node being added or the controller being restarted.

Being able to add and remove this label is important because it allows us to preemptively remove a node from target groups when we know it is being terminated, especially when it occurs on short notice (e.g. for spot instance terminations). This prevents the target groups from sending traffic to a node that is being terminated, which might result in failed connections.

**Steps to reproduce:**
(Tested on ALB controller `v1.1.2`)
1. Setup a plain k8s node and the ALB controller with some ingress resource. Ensure the node is present in the target group(s) created by the ALB controller.
2. Set the `alpha.service-controller.kubernetes.io/exclude-balancer` label to `"true"` on the node.
3. Observe that the node is not removed from the target groups.
4. Trigger reconciliation on the controller by adding or removing a different node or restarting the controller.
5. Observe that the node is removed from the target groups.

Separate from this issue, but still relevant to the handling of the label: the K8S Service controller only checks label presence when determining if a node should be excluded from load balancers, whereas the ALB controller only excludes from the LBs if the label value is `true` (case-insensitive). Additionally, the `alpha.service-controller.kubernetes.io/exclude-balancer` is deprecated (to be removed in 1.18) with the replacement being `node.kubernetes.io/exclude-from-external-load-balancers` (introduced in 1.16), so both labels should be checked.

**Comment by rabbitfang** [comment]
As far as I can tell, this issue is still valid.

/remove-lifecycle rotten

**Comment by M00nF1sh** [comment]
Hi all,

I believe this issue is already addressed in >=v2.0.0. we have node event watchers will react to this label changes. 
Feel free to create a new ticket if this issue exists in v2.
