### ISSUE TITLE
Multiple listeners with custom attributes per ALB

### ISSUE THREAD

**Issue by Pacobart** [kubernetes-sigs/aws-load-balancer-controller#1062]
I have the need to create an ALB with the following structure:

if port = 80, backend service=A, path = /*
if port = 8080, backend service=B, path = /*
if port = 8081, backend service = C, path = /*
if port = 8082, backend service = D, path = /*

I've found I can use the annotation `alb.ingress.kubernetes.io/listen-ports` to configure multiple listeners but each listener gets the entire config. Here's what my ingress looks like:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-dvlp
  namespace: app-dvlp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-1, subnet-2
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8000}, {"HTTP": 8001}, {"HTTP": 9000}, {"HTTP": 9100}, {"HTTP": 9200}, {"HTTP": 9201}]'
  labels:
    app: smilecdr-mgmt
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app-listener
              servicePort: 8000
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app-listener
              servicePort: 8001
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app-mgmt
              servicePort: 9000
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app-mgmt
              servicePort: 9100
    - http:
        paths:
          - path: /*
            backend:
              serviceName:  app-smart
              servicePort: 9200
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app-smart
              servicePort: 9201

I need this to all exist under one ALB. Has anyone done this?

**Comment by ertenmehmet** [comment]
I have learned this issue by the hard way, trying, failing and searching through the net for more than a day.. But as they have explained in their EKS training; with an unfortunate quote "An Ingress does not expose arbitrary ports or protocols. Exposing services other than HTTP and HTTPS to the internet typically uses a service of type NodePort or LoadBalancer."

**Comment by techdragon** [comment]
The NGINX ingress has this kind of customisation options. So I don't see why the ALB couldn't be enhanced to support it via Ingress when the underlying ALB seems more than "smart enough" to handle this sort of traffic routing. Its a matter of how to expose this functionality through ingress "despite itself" so to speak. Nginx do it via a config map annotation to sort of bypass the limits of ingress.

**Comment by techdragon** [comment]
Not stale

**Comment by M00nF1sh** [comment]
@techdragon @Pacobart 
The new released v2.0.0 have a feature called IngressGroup to allow you achieve the desired behavior, please check it out 😄 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/ingress/annotations/#ingressgroup

resolving this issue.
