### ISSUE TITLE
provide of gzip

### ISSUE THREAD

**Issue by alexanderaucobo** [kubernetes-sigs/aws-load-balancer-controller#1132]
It will be really nice when the alb ingress controller can provide gzip compression.

**Comment by M00nF1sh** [comment]
This can a feature request to ALB team

**Comment by mivanovaxway** [comment]
/reopen
Is there a way to get gzip working with ALB?

**Comment by kishorj** [comment]
We will keep track of this in the AWS ALB feature list. Closing this.

**Comment by Shellmode** [comment]
Is there any update?

**Comment by tom10271** [comment]
All we need from this LB controller is to setup LB, target group and listener rules in AWS, the compression part can be handled by any modern web servers including nginx, caddy etc. I mean we need to the power of handling AWS side from this K8s ingress controller + nginx ingress controller for example for compression.
