### ISSUE TITLE
Allow security group autodiscovery

### ISSUE THREAD

**Issue by jorjao81** [kubernetes-sigs/aws-load-balancer-controller#1135]
Annotating each ingress with the security group is repetitive, error prone and could easily cause issues if the security group id changes for some reason. I.E, it exposes incidental complexity to the user.

Creating one security group per ALB is not scalable: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/ingress/annotation.md#security-groups

We would like to have a way of specifying the default security group per k8s cluster, so that users of the ingress don"t have to worry about and we don't run into AWS service limits. Looking at the existing design of the ingress controller, it seems like auto-discovery, in the style of the subnet autodiscovery (https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/controller/config.md#subnet-auto-discovery) is the way to go.

We are prepared to contribute this feature. Would something like that be accepted?

### Basic algorithm
- If the controller finds the `alb.ingress.kubernetes.io/security-groups`annotation, it uses it.
- If it doesn't, it first looks for existing security groups matching specific tags (i.e, security group gets auto-discovered). See below for details.
- If no security groups are found by auto-discovery, fall back to creating security groups.

### Auto discovery

Follow the example of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/controller/config.md#subnet-auto-discovery

* `kubernetes.io/cluster/${cluster-name}` must be set to owned or shared
* `kubernetes.io/role/internal-elb` must be set to 1 or `` for internal LoadBalancers
* `kubernetes.io/role/elb` must be set to 1 or `` for internet-facing LoadBalancers

**Comment by dudicoco** [comment]
@jorjao81 I am looking for the same feature as well. Are you working on a PR?
https://github.com/zalando-incubator/kube-ingress-aws-controller already has this implemented.

We are using one SG for the entire cluster which allows incoming traffic from the nodes and from our internal VPN, and an optional second SG per ingress with custom rules for incoming traffic.
It would be great if we can load these security groups dynamically using discovery with tags.

**Comment by jorjao81** [comment]
@dudicoco no I'm not; we have found a workaround that was enough for us:

there is a relatively new, undocumented feature: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1019

With this, the ALB controller creates an additional Rule in an Existing Security Group in the node, creating a new one only for the ALB.
By default, security groups can only have 60 rules, which would be cutting it a bit short, but we can increase the limit to 200 (https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html) which is enough for our current purposes. 

Eventually one could also move to IP targeting with different SGs per Instance/ENI, which would allow us to move beyond 200 ALBs per cluster (and enable ingresses for Fargate pods).

That doesn't completely eliminate the usefullness of the proposed feature, but doesn't make it a high priority. Considering I didn't get a single comment regarding the potential of merging such a feature, I dropped it.

**Comment by jorjao81** [comment]
I might still be interested in contributing this; but only if it has a realistic potential of being merged.

**Comment by dudicoco** [comment]
@jorjao81 doesn't this feature also creates a security group?

**Comment by jorjao81** [comment]
True, it creates it on the ALB, but creates only one per ENI on the nodes. Our issue was more with scalability (number of SG attached to an ENI) than anything else, so this solves it.

**Comment by M00nF1sh** [comment]
I don't think we should support this feature since it's different from subnets(subnets are tagged by default across almost all k8s on AWS offering).

also, as noted in comments, the securityGroup rules management for worker node have changed, so the original usage for this feature is unnecessary.

Another usage for this feature is to supply external-managed securityGroups for all ingresses, and we'll support this via IngressClass's parameters instead of auto-discovery.

closing this
