### ISSUE TITLE
Expose ALB Reconcile Status

### ISSUE THREAD

**Issue by eytan-avisror** [kubernetes-sigs/aws-load-balancer-controller#1169]
Some of us using aws-alb-ingress-controller, are using it to run/build a Kubernetes platform and allow tenants to provision ALBs for ingress access to their service/s.

In this case it may be very difficult to provide visibility to cluster tenants to the status of their ALB's reconcile, and this can potentially lead to downtime.

Example:
- User has an ALB which is receiving traffic in production with 100 targets in TargetGroup.
- User makes a change to something trivial, like ALB logging bucket destination, which is invalid.
- From this point forward, reconciles for that ALB will fail, and new targets will not be registered.
- Cluster gets upgraded and nodes get rotated, all targets eventually go away and new one don't get registered.

(another point to think about, is why an invalid bucket affects/blocks target registration ? this makes no sense)

This means downtime.

The person making the change has no way to know that reconcile is failing on his ALB unless he goes and inspects the logs of alb controller, this is not always an option.

Also, as a cluster tenant, controller logs is not a very friendly way to get this information.

Even for a cluster operator / controller, looking at logs to get this information is not an option.

It will be awesome if we can somehow expose this status, for example - add a status field to ingress object (success/error), but I believe since ingress is a Kubernetes primitive, it might not be possible to modify it's status? is this the case?

Is there another way we can expose the reconcile status to other cluster components / tenants outside of logs/events?

Suggestions / thoughts appreciated.

**Comment by M00nF1sh** [comment]
Hi,
The easiest solution for this is write an event to Ingress for successfully reconcile/failure. I can take this in next release(v1.1.6)

**Comment by M00nF1sh** [comment]
`another point to think about, is why an invalid bucket affects/blocks target registration ? this makes no sense`. 
Agree, that's why i used a separate controller for endpoints updates in V2. (https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v2/pkg/controller/endpointbinding/controller.go).
I'll speed effort to get V2 code reviewed and release beta version than changing v1 for this feature at this point :D

**Comment by eytan-avisror** [comment]
awesome! so this will update target groups independently of any non-blocking reconcile failures?

**Comment by M00nF1sh** [comment]
@eytan-avisror Yes. But other reconcile failures like rule conflicts will only prevents new target group creation/deletion. While existing targetGroups will be updated independently.
