### ISSUE TITLE
Prometheus support

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/aws-load-balancer-controller#1212]
It would be great to have metrics per alb group where we see how many targets are registered and if there is any rule failure...

Right now an iam error like this can cause the whole system to fail:
```
hop-zed"],"leavingMembers":[]}
{"level":"error","ts":1585751311.2310958,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"alb-ingress-controller","request":"/spryker","error":"AccessDeniedException: 
```
with an corresponding metric we could monitor such problems... An external monitor (url check) would not help because some old targets might be still up and running.

**Comment by clayvan** [comment]
@runningman84 Just to make sure I'm fully understanding the situation, there is 0 support for prometheus today?

As someone considering using ALB Ingress controller, am I correct to understand that there is no supported way to "monitor" or alert on controller reconciliation failures?

I could potentially alert based on logs in Splunk or something, but that's not very elegant.

**Comment by runningman84** [comment]
That's unfortunately correct, right now there is 0 support for prometheus...

You could run a custom container whiches parses the logs and publishes them as metrics....

**Comment by jutley** [comment]
It looks like there are Prometheus metrics, but they do not expose any data on a per-ingress or per-service level. Furthermore, there is not any data in the ingress itself that indicates that there may be an issue.

In the previous alb-ingress-controller, there was a metric called `aws_alb_ingress_controller_errors{ingress="<namespace>/<name>"}`, and we could use this to help notify teams that their ingress was misconfigured.

With the current metrics, we can only alert that _something_ is failing to reconcile, and we are required to parse logs to understand the specific issue.

This is a pretty major usability issue.

**Comment by kishorj** [comment]
Add new metrics for ingress group usage like number of ingress groups and provisioned ALB in the cluster and count of errors encountered per group.

**Comment by tooptoop4** [comment]
i can see prometheus metrics like:
```
aws_api_call_retries_bucket{operation="CreateTargetGroup",service="Elastic Load Balancing v2",le="0"} 11
```
but not at targetgroup level

**Comment by RamazanKara** [comment]
+1

**Comment by sanjeevpandey19** [comment]
+1

**Comment by dudicoco** [comment]
> It looks like there are Prometheus metrics, but they do not expose any data on a per-ingress or per-service level. Furthermore, there is not any data in the ingress itself that indicates that there may be an issue.
> 
> In the previous alb-ingress-controller, there was a metric called `aws_alb_ingress_controller_errors{ingress="<namespace>/<name>"}`, and we could use this to help notify teams that their ingress was misconfigured.
> 
> With the current metrics, we can only alert when _something_ is failing to reconcile, and we are required to parse logs to understand the specific issue.
> 
> This is a pretty major usability issue.

@kishorj @M00nF1sh any plans on fixing this regression? The current metric `controller_runtime_reconcile_errors_total` does not provide the same information that the previous `aws_alb_ingress_controller_errors` metric did.
