### ISSUE TITLE
Controller health check failed: [ec2.DescribeTagsWithContext]: WebIdentityErr: failed to retrieve credentials caused by: InvalidIdentityToken: No OpenIDConnect provider found

### ISSUE THREAD

**Issue by ARogovsky** [kubernetes-sigs/aws-load-balancer-controller#1226]
Hi

I unable use ingress controller by error:

```
	status code: 400, request id: xxx
E0416 12:40:46.016106       1 healthcheck.go:38] Controller health check failed: [ec2.DescribeTagsWithContext]: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.eu-west-1.amazonaws.com/id/xxxx
```

My args is:
```
                  + container {
                      + args                     = [
                          + "--ingress-class=alb",
                          + "--aws-region=eu-west-1",
                          + "--aws-max-retries=10",
```

**Comment by nthienan** [comment]
Facing same issue. Does anyone know why and how to fix it?

**Comment by wadkar** [comment]
If you have just created the EKS Cluster using `eksctl` or using the AWS Console, make sure to follow the steps [documented here](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html) to enable the EKS' OIDC Provider in your IAM Provider list, e.g. `eksctl utils associate-iam-oidc-provider --cluster "${CLUSTER_NAME}" --approve`

Please note should you decide to use the AWS Console for this one time setup for a newly created EKS Cluster, you should _ideally_ verify the EKS OIDC Identity Provider by manually [obtaining the root CA thumbprint for the EKS OIDC Identity Provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html).

It appears that the [`eksctl …` command does this for you automatically](https://github.com/weaveworks/eksctl/blob/fb3699aa913a5c514b8479a762802ad2ff739884/pkg/iam/oidc/api.go#L139).

**Comment by matias-devoto** [comment]
Thanks i have already solved the problem adding the oidc

**Comment by M00nF1sh** [comment]
closing this as it's iam for service accounts setup
