### ISSUE TITLE
docs: update to expose that IPv6 Inbound CIDRs are supported

### ISSUE THREAD

**Issue by ghostsquad** [kubernetes-sigs/aws-load-balancer-controller#1251]
as related to #991 

The only example in the current documentation is this:

```
alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/24
```

**Comment by ghostsquad** [comment]
I'd be happy to submit a PR if that makes sense to update the docs here:

https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#inbound-cidrs

**Comment by ghostsquad** [comment]
looks like this may also need updating:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/ingress/annotation.md

**Comment by ghostsquad** [comment]
additionally, the docs don't specify the format to provide a list of CIDRs

**Comment by kishorj** [comment]
The new v2 documentation has v6 examples as well. 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#inbound-cidrs
