### ISSUE TITLE
how does `delete.protection=true` work for you?

### ISSUE THREAD

**Issue by ryanoolala** [kubernetes-sigs/aws-load-balancer-controller#1254]
So i understand that we can turn on delete protection on aws console by adding the annotation to the ingress
`alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true`

However to my understanding, this is used for preventing deletion on AWS console, and this does not prevent any deletion on kubernetes API for the ingress itself. Thus as a kubernetes controlled resource, shouldn't the delete protection be on the ingress itself?

I understand this could go beyond the responsibilities of this application, but I'm wondering how the community is handling the protection of the ingress resource. 

Is RBAC the only way to prevent accidental deletion?

**Comment by kitsirota** [comment]
+1 

I am very concerned about accidental deletion also, specifically in the context of having to update all the relevant DNS records and propagation delays leading to extended downtime.  

Ideally, ALB delete operations should fail/noop if delete protection is enabled.

**Comment by zickzackv** [comment]
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DeleteLoadBalancer.html

The current version of the api docs state that you can *not* delete an LoadBalancer when the deletion_protection is set. 
If this controller does not delete first the protection and then deletes the LB, the LB will not be automatically deleted.

**Comment by korenyoni** [comment]
Confirming that as of `v2.2.0` when the annotation `alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true` is present, `alb-controller` outputs the following error:

```
{"level":"error","ts":1625699111.244138,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"[REDACTED]","namespace":"[REDACTED]","error":"OperationNotPermitted: Load balancer '[REDACTED]' cannot be deleted because deletion protection is enabled\n\tstatus code: 400, request id: [REDACTED]"}
```

**Comment by kishorj** [comment]
@korenyoni, There is an open issue to handle the delete protection in v2 - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1900. Please direct any comments/feedback to the v2 issue.

**Comment by korenyoni** [comment]
I've opened #2119 in light of this.
