### ISSUE TITLE
FeatureGate for WAFv2 should be disabled in AWS China regions

### ISSUE THREAD

**Issue by walkley** [kubernetes-sigs/aws-load-balancer-controller#1256]
With default parameters to launch alb-ingress-controller 1.1.7 in AWS China regions, it raised exception as following:
```
VAFv2  webACL,  kubebuilder/controller "msg"="Reconciler error" "error"="failed get WAFv2 webACL for load balancer arn:aws-cn:elasticloadbalancing:cn-northwest-1:188642756190:loadbalancer/app/546056ac-default-albingres-d740/2b728c5dc04c0991: RequestError: send request failed\ncaused by: Post https://wafv2.cn-northwest-1.amazonaws.com.cn/: dial tcp: lookup wafv2.cn-northwest-1.amazonaws.com.cn on 10.100.0.10:53: no such host"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"alb-ingress"},  
```

This is because WAFv2 is not available in AWS China regions, workaround is set parameters --feature-gates=waf=false,wafv2=false, however I'd expect it should be work without additional settings.

**Comment by jansony1** [comment]
Still exist in v1.1.8

**Comment by DevOpserzhao** [comment]
SubscriptionRequiredException: The AWS Access Key Id needs a subscription for the service\n\tstatus code: 400,

Still exist in v1.1.8, Add the following parameters to deployment spec.args:
- --enable-shield=false
- --enable-waf=false
- --enable-wafv2=false

**Comment by walkley** [comment]
Thanks @DevOpserzhao for the reminder.

@M00nF1sh do we have any solution to disable waf/shield features in the controller for China regions without setting additional parameters? otherwise we have to update the doc and guide to reminder users again and again...
