### ISSUE TITLE
Roadmap of helm chart for aws-alb-ingress-controller

### ISSUE THREAD

**Issue by zxkane** [kubernetes-sigs/aws-load-balancer-controller#1271]
Currently there is an [incubator chart](https://github.com/helm/charts/tree/master/incubator/aws-alb-ingress-controller) for `aws-alb-ingress-controller` contributed by community. However the project [helm/charts](https://github.com/helm/charts#deprecation-timeline) already ran into maintenance mode. Is there any road map to publish the AWS maintained helm chart of `aws-alb-ingress-controller`?

There are some EKS charts already maintained by project [aws/eks-charts](https://github.com/aws/eks-charts), it would be nice to have a chart of `aws-alb-ingress-controller` in same umbrella as well.

**Comment by Skaronator** [comment]
not stale

**Comment by kishorj** [comment]
Helm chart will be available for v2 release
https://github.com/aws/eks-charts/tree/master/stable/aws-loadbalancer-controller

**Comment by M00nF1sh** [comment]
closing this as we have released the helm chart in our eks-charts repo
