### ISSUE TITLE
alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300 works unstable

### ISSUE THREAD

**Issue by lmgnid** [kubernetes-sigs/aws-load-balancer-controller#1282]
Hello, I am using "docker.io/amazon/aws-alb-ingress-controller:v1.1.5" and used this annotation for multi ingresses:
"alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300"
But not all ingresses updated, in one EKS cluster, maybe the 1st ingerss/alb doesn't work, but in another EKS cluster, maybe the 3rd ingress/alb doesn't work and no rules.
Any ideas?
PS: No errors in ALB controllers  and can see all ALB ingresses  update logs.

**Comment by lmgnid** [comment]
For example in logs, I can see both these 2  updated, but actually the 2nd one is NOT updated in the real ALB:
alb-ingress-controller-87d6f564b-2c525:alb-ingress-controller I0602 18:43:36.622301       1 attributes.go:144] dev/ingress-alb-others: Modifying ELBV2 attributes to [{    Key: "idle_timeout.timeout_seconds",    Value: "300"  }].                                                                                                                                                                                                                             
alb-ingress-controller-87d6f564b-2c525:alb-ingress-controller I0602 18:53:20.774503       1 attributes.go:144] dev/ingress-alb-admin: Modifying ELBV2 attributes to [{    Key: "idle_timeout.timeout_seconds",    Value: "300"  }].

**Comment by M00nF1sh** [comment]
hi, v2.0.0 should have solved this issue.
there is a race in v1's annotation parsing and ingress reconcile
