### ISSUE TITLE
alb ingress controller not able to read the IAM role 

### ISSUE THREAD

**Issue by prvn040890** [kubernetes-sigs/aws-load-balancer-controller#1293]
Hi all,

I am trying to create a kubernetes cluster by terraform and kubeadm i am able to install kubernetes with one master and three worker nodes but when i am trying to use alb-ingress-controller i am continuously grtting errors eventhough i have followed all the required docs but still my al-ingress-controlled not creating the ALB please fin dthe below  files for your ref, Can anyone please help me with this issue

alb-controller-yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      containers:
        - name: alb-ingress-controller
          args:
            # - --watch-namespace=your-k8s-namespace
            - --ingress-class=alb
            - --cluster-name=kubernetes
            # - --aws-vpc-id=vpc-0e4eab02c9a73d895
            - --aws-region=us-east-1
            - --aws-api-debug
            # - --aws-max-retries=10
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.6
      serviceAccountName: alb-ingress-controller

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: webapp.gl-project1.com
spec:
    rules:
    - host: webapp.gl-project1.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: webapp-service
              servicePort: 80

i am getting the below error

ubuntu@ip-195-10-3-154:~/kubernetes-yaml/ingress$ kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o "alb-ingress[a-zA-Z0-9-]+")
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    v1.1.6
  Build:      git-95ee2ac8
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller.git
-------------------------------------------------------------------------------

W0611 03:10:00.577212       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0611 03:10:00.633184       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null}}}
I0611 03:10:00.633544       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I0611 03:10:00.633619       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"=
I0611 03:10:00.633868       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I0611 03:10:00.633940       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"=
I0611 03:10:00.634135       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null}}}
I0611 03:10:00.634417       1 controller.go:121] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "controller"="alb-ingress-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}}
I0611 03:10:00.634735       1 leaderelection.go:205] attempting to acquire leader lease  kube-system/ingress-controller-leader-alb...
I0611 03:10:00.641604       1 leaderelection.go:214] successfully acquired lease kube-system/ingress-controller-leader-alb
I0611 03:10:00.641799       1 recorder.go:53] kubebuilder/manager/events "level"=1 "msg"="Normal"  "message"="alb-ingress-controller-7f4fd86f48-jnl2j_09818916-ab91-11ea-aebe-46d7738304f3 became leader" "object"={"kind":"ConfigMap","namespace":"kube-system","name":"ingress-controller-leader-alb","uid":"53bd79f9-ddf8-4f7f-a72d-a55f996b0041","apiVersion":"v1","resourceVersion":"4152"} "reason"="LeaderElection"
I0611 03:10:00.742151       1 controller.go:134] kubebuilder/controller "level"=0 "msg"="Starting Controller"  "controller"="alb-ingress-controller"
I0611 03:10:00.842357       1 controller.go:154] kubebuilder/controller "level"=0 "msg"="Starting workers"  "controller"="alb-ingress-controller" "worker count"=1
E0611 03:10:01.085977       1 request_pagination.go:107] Failed request: ec2/DescribeSubnets, Payload: {  Filters: [{      Name: "tag:kubernetes.io/cluster/kubernetes",      Values: ["owned","shared"]    },{      Name: "tag:kubernetes.io/role/elb",      Values: ["","1"]    }]}, Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0611 03:10:01.086128       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"webapp-ingress"}
E0611 03:10:02.218942       1 request_pagination.go:107] Failed request: ec2/DescribeSubnets, Payload: {  Filters: [{      Name: "tag:kubernetes.io/cluster/kubernetes",      Values: ["owned","shared"]    },{      Name: "tag:kubernetes.io/role/elb",      Values: ["","1"]    }]}, Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0611 03:10:02.219017       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"webapp-ingress"}
E0611 03:10:03.336704       1 request_pagination.go:107] Failed request: ec2/DescribeSubnets, Payload: {  Filters: [{      Name: "tag:kubernetes.io/cluster/kubernetes",      Values: ["owned","shared"]    },{      Name: "tag:kubernetes.io/role/elb",      Values: ["","1"]    }]}, Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0611 03:10:03.337024       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"webapp-ingress"}
E0611 03:10:04.442990       1 request_pagination.go:107] Failed request: ec2/DescribeSubnets, Payload: {  Filters: [{      Name: "tag:kubernetes.io/cluster/kubernetes",      Values: ["owned","shared"]    },{      Name: "tag:kubernetes.io/role/elb",      Values: ["","1"]    }]}, Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0611 03:10:04.443097       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"webapp-ingress"}
E0611 03:10:05.595595       1 request_pagination.go:107] Failed request: ec2/DescribeSubnets, Payload: {  Filters: [{      Name: "tag:kubernetes.io/cluster/kubernetes",      Values: ["owned","shared"]    },{      Name: "tag:kubernetes.io/role/elb",      Values: ["","1"]    }]}, Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0611 03:10:05.595678       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"webapp-ingress"}
E0611 03:10:06.754148       1 request_pagination.go:107] Failed request: ec2/DescribeSubnets, Payload: {  Filters: [{      Name: "tag:kubernetes.io/cluster/kubernetes",      Values: ["owned","shared"]    },{      Name: "tag:kubernetes.io/role/elb",      Values: ["","1"]    }]}, Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0611 03:10:06.754218       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"webapp-ingress"}

**Comment by M00nF1sh** [comment]
Hi,
ALB Ingress controller needs proper IAM permission to act on-behalf of you.
Do you correctly grant IAM permission to the controller pod? 

You can rule out this issue by create a normal linux pod, and install aws cli there, and run `aws sts get-caller-identity`. You should make the above command work first via your aws credential vending solution you are using.
