### ISSUE TITLE
Cross account Cognito user pool problem

### ISSUE THREAD

**Issue by MyDigitalLife** [kubernetes-sigs/aws-load-balancer-controller#1294]
We are having some issues setting up Cognito user pool and our ingress. We have a setup where we have a dedicated AWS account for our EKS cluster but can't do anything else in this account. We have a linked account that we use for database, queue's, etc. We wan't to use Cognito as describe in the documentation here: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/cognito/setup/

When we configured this we are getting this error in the ingress pods:
```
error: InvalidLoadBalancerAction: 'arn:aws:cognito-idp:eu-west-1:{account-id}:userpool/eu-west-1_{pool-id}' is not a valid user pool ARN
	status code: 400, request id: ef8d8b2c-41dd-413f-b95f-d00fa67d8e94
```
It should be possible to use cognito cross account as its described in these two cases, but that's without EKS: 
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-cross-account-cognito-authorizer.html
https://aws.amazon.com/premiumsupport/knowledge-center/cognito-user-pool-cross-account-alb/

Is this something that should already work and I might be configuring incorrectly? Or is this a feature that will need to be created?

We did already check and everything is in the same region so its not the same problem as in #1057

**Comment by newtoworld999** [comment]
Hi 
Try using like this for cross account userpool(just like any other OIDC provider), i am not getting that error any more but when iam deploying the ingress object  the ALB is getting created and rules are getting created except the authentication part is not getting configured not sure where the issue is
The below ingress code worked for me for cross account cognito( like i said not getting error related to usepool any more in controller logs)

Create a secret with base64 encoded in eks with the client id and client secret that you created in the cognito user pool and provide the secret name as well - in my case its cognitoclientsecret is the file i created

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/auth-idp-oidc: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"Issuer":"cognito","AuthorizationEndpoint":"https://<user-pool-domainname>.auth.us-east-1.amazoncognito.com/oauth2/authorize","TokenEndpoint":"https://<user-pool-domain-name>.auth.us-east-1.amazoncognito.com/oauth2/token","UserInfoEndpoint":"https://<user-pool-domain-name>.auth.us-east-1.amazoncognito.com/oauth2/userInfo","SecretName":"cognitoclientsecret"}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxxxxx:certificate/bae36e74-d7f1-4b68-9bda-69c15f0 
  labels:
    app: demoapp
spec:
  rules:
  - host: xxxxxxx
    http:
      paths:
      - path:
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        backend:
          serviceName: nginx-service
          servicePort: 80
  - host: xxxxxxxx
    http:
      paths:
      - path: /helloworld
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        backend:
          serviceName: helloworldapp-service
          servicePort: 80
  - host: xxxxxxx
    http:
      paths:
      - path: /oauth2/idpresponse
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        backend:
          serviceName: helloworldapp-service
          servicePort: 80

Let me know if you are able to get the authentication config also applued to ALB when you deploy this ingress object or not

**Comment by xposix** [comment]
This is the only way I manage to get rid of those error messages 

My issue was that I was specifying both `auth-idp-cognito` and `auth-idp-oidc` config and alb.ingress.kubernetes.io/auth-type was set to `cognito` while it needs to be `oidc`

```
---
apiVersion: v1
kind: Secret
metadata:
  namespace: my-app
  name: cognitoclientcredentials
data:
  clientID: <<base64 of your plain text clientId>>
  clientSecret: <<base64 of your plain text clientSecret>>
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: my-app
  name: ingress-my-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{
      "Type": "redirect",
      "RedirectConfig": { 
        "Protocol": "HTTPS",
        "Port": "443",
        "StatusCode": "HTTP_301"
      }
    }'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:12345678900:certificate/62d0dacb-47e8-4e71-9683-75cbbf80aacb

    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: deny
    alb.ingress.kubernetes.io/auth-idp-oidc: '{
      "Issuer":"https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_c4UWtGS2A",
      "AuthorizationEndpoint":"https://mycompany-dev.auth.eu-west-1.amazoncognito.com/oauth2/authorize",
      "TokenEndpoint":"https://mycompany-dev.auth.eu-west-1.amazoncognito.com/oauth2/token",
      "UserInfoEndpoint":"https://mycompany-dev.auth.eu-west-1.amazoncognito.com/oauth2/userInfo",
      "SecretName":"cognitoclientcredentials"
    }'

spec:
  rules:
    - host: "my-app.dev.mycompany.net"
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: service-my-app
              servicePort: 80
```
