### ISSUE TITLE
Updating to networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by hiraken-w** [kubernetes-sigs/aws-load-balancer-controller#1296]
The ingress api group/version "extensions/v1beta1" is already deprecated.
And I understand that v1.18 or later cannot be used.

[kubernetes/CHANGELOG-1.14.md at master · kubernetes/kubernetes · GitHub]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md

> Ingress resources are now available via networking.k8s.io/v1beta1. Ingress resources in extensions/v1beta1 are deprecated and will no longer be served in v1.18. Existing persisted data is available via the new API group/version (#74057, @liggitt)

Updating to networking.k8s.io/v1beta1 is required.

[#1034](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1034) is closed.
So I created new Issue.

**Comment by liggitt** [comment]
The progress of Ingress to v1 was delayed, so `extensions/v1beta1` Ingress has not yet been removed.

Ingress v1 is on target to graduate in v1.19, and the deprecated version in extensions/v1beta1 to no longer be served in v1.22

**Comment by M00nF1sh** [comment]
Thanks for the notification. I think we'll need to implement client-side conversion support both version :D

**Comment by M00nF1sh** [comment]
resolving this as our new v2.0.0 have been out and using networking.k8s.io API :D
