### ISSUE TITLE
ALB ingress controller after deployment the pod fails due to back-off restarting failed the container

### ISSUE THREAD

**Issue by anusha-maheshwarappa-ip** [kubernetes-sigs/aws-load-balancer-controller#1306]
Hey, I have been working with ALB ingress controller nearly 4 months now and this is the first time i have been facing this issue, the ingress was perfectly working but then after i updated it to the latest version it has stopped and i am unable to resolve this can you please help me with the issue, here is details of the issue:

Initially i was using ALB ingress controller version v1.1.5 until lately and I updated it to V1.1.8 and after that the ingress controller pod is failing, i have clearly mentioned the namespace, which VPC ID to use, region and the cluster name also i have properly configured the RBAC, once i deploy these and i check the logs i get this error : I used this command
-  **kubectl logs alb-ingress-controller-7c974d9b8c-hgdfc -n kube-system**

-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    v1.1.8
  Build:      git-95ee2ac8
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller.git
-------------------------------------------------------------------------------

W0629 11:49:42.457832       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E0629 11:50:12.458509       1 manager.go:173] kubebuilder/manager "msg"="Failed to get API Group-Resources" "error"="Get https://10.100.0.1:443/api?timeout=32s: dial tcp 10.100.0.1:443: i/o timeout"  
F0629 11:50:12.458538       1 main.go:84] Get https://10.100.0.1:443/api?timeout=32s: dial tcp 10.100.0.1:443: i/o timeout

and then **kubectl get pods -n kube-system** get the pods i get this 

NAME                                      READY   STATUS             RESTARTS   AGE
alb-ingress-controller-7c974d9b8c-hgdfc   0/1     CrashLoopBackOff   797        3d2h

when i describe the pod and its deployment i get this details :

**kubectl describe pod alb-ingress-controller-7c974d9b8c-hgdfc -n kube-system**

Name:           alb-ingress-controller-7c974d9b8c-hgdfc
Namespace:      kube-system
Priority:       0
Node:           ip-xxx-xxx-xxx-x.xx-xx-x.compute.internal/xxx.xxx.xxx.x
Start Time:     Fri, 26 Jun 2020 09:34:14 +0000
Labels:         app.kubernetes.io/name=alb-ingress-controller
                pod-template-hash=7c974d9b8c
Annotations:    kubernetes.io/psp: eks.privileged
Status:         Running
IP:             xxx.xxx.xxx.x
IPs:            <none>
Controlled By:  ReplicaSet/alb-ingress-controller-7c974d9b8c
Containers:
  alb-ingress-controller:
    Container ID:  docker://e85647gbc3034cf87xxxxxxxxxxxxxe4906e0ddc9xxxxxxx1dae
    Image:         docker.io/amazon/aws-alb-ingress-controller:v1.1.8
    Image ID:      docker-pullable://amazon/aws-alb-ingress-controller@shaxxxxxxxxxxxxxxxxxxxxxx
    Port:          <none>
    Host Port:     <none>
    Args:
      --watch-namespace=xxxx
      --ingress-class=alb
      --cluster-name=xxxxx
      --aws-vpc-id=vpc-xxxx
      --aws-region=xxxx
      --aws-api-debug
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 29 Jun 2020 11:55:13 +0000
      Finished:     Mon, 29 Jun 2020 11:55:43 +0000
    Ready:          False
    Restart Count:  798
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from alb-ingress-controller-token-xxxxx(ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  alb-ingress-controller-token-xxxx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alb-ingress-controller-token-xxxx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                       From                                                     Message
  ----     ------   ----                      ----                                                     -------
  Warning  BackOff  2m16s (x18666 over 3d2h)  kubelet, ip-xxx-xxx-xxx-x.x-x-x.compute.internal  Back-off restarting failed container

also i created this cluster using EKSCTL config and here is my versions:

eksctl version--->
0.22.0

kubectl version --short  ---->
Client Version: v1.18.4
Server Version: v1.15.11-eks-xxxxx

kubectl get node -o custom-columns=NAME:.metadata.name,VERSION:.status.nodeInfo.kubeletVersion --->
NAME                                               VERSION
ip-xxx-xxx-xxx-x.x-x-x.compute.internal   v1.13.8-eks-xxxxx
ip-xxx-xxx-xxx-x.x-x-x.compute.internal   v1.13.8-eks-xxxxx

Also to mention i rolled back to the version 1.1.6 and even 1.1.4 and deployed but still i get the same error, can some one help me with this

Thanks in advance

**Comment by jayanthvn** [comment]
Hi @anusha-maheshwarappa-ip

Can you please check the kubelet logs and also if kube-proxy is running? Please do check security group/subnet ACL settings.

Thanks.

**Comment by anusha-maheshwarappa-ip** [comment]
Hey @jayanthvn 

I checked the kube-proxy seems that is also not working and that is strange has that was also working fine, security group and the ACL seems fine, what exactly should i look in the kubelet logs has there is lot of information but when i checked the events this is what is happening
**kubectl get events for -n kube-system** 
2m53s       Warning   BackOff     pod/alb-ingress-controller-7c974d9b8c-hgdfc   Back-off restarting failed container
4m2s        Normal    Killing     pod/coredns-74f78cdfd6-gzv7t                  Killing container with id docker://coredns:Need to kill Pod
5m23s       Warning   Unhealthy   pod/coredns-74f78cdfd6-n4t3w                Liveness probe failed: Get http://xxx.xxx.xxx.xxx:xxxx/health: dial tcp xxx.xxx.xxx.xxx:xxxx: connect: connection refused
59s         Warning   BackOff     pod/coredns-74f78cdfd6-n4t3w                  Back-off restarting failed container
68s         Warning   Unhealthy   pod/coredns-74f78cdf9d-vq7ew4                  Liveness probe failed: Get http://xxx.xxx.xxx.xxx:xxxx/health: dial tcp xxx.xxx.xxx.xxx:xxxx: connect: connection refused
5m59s       Warning   BackOff     pod/coredns-74f78cdf9d-vq74a                  Back-off restarting failed container

**Comment by jayanthvn** [comment]
Hi @anusha-maheshwarappa-ip,

Can you please provide the kube-proxy and kubelet logs once you triggered the upgrade? Even i will try locally and update.

Thanks.

**Comment by jayanthvn** [comment]
Hi @anusha-maheshwarappa-ip ,

I tried locally upgrading the ALB ingress controller and issue is not seen. Kindly share the kube-proxy logs.

Thanks.

**Comment by sveerabathini** [comment]
Hi @anusha-maheshwarappa-ip , first let me know what type of nodes that your running on the cluster. If you have mixed one like windows and linux, then mention the nodeselector as Linux in you deployment file for alb ingress controller.

**Comment by anusha-maheshwarappa-ip** [comment]
> Hi @anusha-maheshwarappa-ip ,
> 
> I tried locally upgrading the ALB ingress controller and issue is not seen. Kindly share the kube-proxy logs.
> 
> Thanks.

Hey .. here is the kube-proxy logs

I0502 09:41:30.354468       8 flags.go:33] FLAG: --alsologtostderr="false"
I0502 09:41:30.354516       8 flags.go:33] FLAG: --bind-address="0.0.0.0"
I0502 09:41:30.354522       8 flags.go:33] FLAG: --cleanup="false"
I0502 09:41:30.354528       8 flags.go:33] FLAG: --cleanup-iptables="false"
I0502 09:41:30.354532       8 flags.go:33] FLAG: --cleanup-ipvs="true"
I0502 09:41:30.354536       8 flags.go:33] FLAG: --cluster-cidr=""
I0502 09:41:30.354540       8 flags.go:33] FLAG: --config="/var/lib/kube-proxy-config/config"
I0502 09:41:30.354546       8 flags.go:33] FLAG: --config-sync-period="15m0s"
I0502 09:41:30.354552       8 flags.go:33] FLAG: --conntrack-max="0"
I0502 09:41:30.354558       8 flags.go:33] FLAG: --conntrack-max-per-core="32768"
I0502 09:41:30.354566       8 flags.go:33] FLAG: --conntrack-min="131072"
I0502 09:41:30.354571       8 flags.go:33] FLAG: --conntrack-tcp-timeout-close-wait="1h0m0s"
I0502 09:41:30.354577       8 flags.go:33] FLAG: --conntrack-tcp-timeout-established="24h0m0s"
I0502 09:41:30.354582       8 flags.go:33] FLAG: --feature-gates=""
I0502 09:41:30.354591       8 flags.go:33] FLAG: --healthz-bind-address="0.0.0.0:10256"
I0502 09:41:30.354595       8 flags.go:33] FLAG: --healthz-port="10256"
I0502 09:41:30.354599       8 flags.go:33] FLAG: --help="false"
I0502 09:41:30.354603       8 flags.go:33] FLAG: --hostname-override=""
I0502 09:41:30.354607       8 flags.go:33] FLAG: --iptables-masquerade-bit="14"
I0502 09:41:30.354611       8 flags.go:33] FLAG: --iptables-min-sync-period="0s"
I0502 09:41:30.354615       8 flags.go:33] FLAG: --iptables-sync-period="30s"
I0502 09:41:30.354619       8 flags.go:33] FLAG: --ipvs-exclude-cidrs="[]"
I0502 09:41:30.354630       8 flags.go:33] FLAG: --ipvs-min-sync-period="0s"
I0502 09:41:30.354634       8 flags.go:33] FLAG: --ipvs-scheduler=""
I0502 09:41:30.354638       8 flags.go:33] FLAG: --ipvs-strict-arp="false"
I0502 09:41:30.354643       8 flags.go:33] FLAG: --ipvs-sync-period="30s"
I0502 09:41:30.354646       8 flags.go:33] FLAG: --kube-api-burst="10"
I0502 09:41:30.354650       8 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0502 09:41:30.354655       8 flags.go:33] FLAG: --kube-api-qps="5"
I0502 09:41:30.354660       8 flags.go:33] FLAG: --kubeconfig=""
I0502 09:41:30.354664       8 flags.go:33] FLAG: --log-backtrace-at=":0"
I0502 09:41:30.354670       8 flags.go:33] FLAG: --log-dir=""
I0502 09:41:30.354674       8 flags.go:33] FLAG: --log-file=""
I0502 09:41:30.354678       8 flags.go:33] FLAG: --log-flush-frequency="5s"
I0502 09:41:30.354682       8 flags.go:33] FLAG: --logtostderr="true"
I0502 09:41:30.354686       8 flags.go:33] FLAG: --masquerade-all="false"
I0502 09:41:30.354691       8 flags.go:33] FLAG: --master=""
I0502 09:41:30.354696       8 flags.go:33] FLAG: --metrics-bind-address=“xxx.x.x.x:xxxxx”
I0502 09:41:30.354701       8 flags.go:33] FLAG: --metrics-port=“xxxx”
I0502 09:41:30.354707       8 flags.go:33] FLAG: --nodeport-addresses="[]"
I0502 09:41:30.354714       8 flags.go:33] FLAG: --oom-score-adj="-999"
I0502 09:41:30.354719       8 flags.go:33] FLAG: --profiling="false"
I0502 09:41:30.354724       8 flags.go:33] FLAG: --proxy-mode=""
I0502 09:41:30.354730       8 flags.go:33] FLAG: --proxy-port-range=""
I0502 09:41:30.354736       8 flags.go:33] FLAG: --resource-container="/kube-proxy"
I0502 09:41:30.354741       8 flags.go:33] FLAG: --skip-headers="false"
I0502 09:41:30.354745       8 flags.go:33] FLAG: --stderrthreshold="2"
I0502 09:41:30.354750       8 flags.go:33] FLAG: --udp-timeout="250ms"
I0502 09:41:30.354755       8 flags.go:33] FLAG: --v="2"
I0502 09:41:30.354762       8 flags.go:33] FLAG: --version="false"
I0502 09:41:30.354770       8 flags.go:33] FLAG: --vmodule=""
I0502 09:41:30.354775       8 flags.go:33] FLAG: --write-config-to=""
I0502 09:41:30.355701       8 feature_gate.go:206] feature gates: &{map[]}
I0502 09:41:30.862860       8 server_others.go:148] Using iptables Proxier.
W0502 09:41:30.863071       8 proxier.go:319] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0502 09:41:30.863210       8 server_others.go:178] Tearing down inactive rules.
I0502 09:41:31.175776       8 iptables.go:200] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
I0502 09:41:31.175808       8 server.go:484] Version: v1.13.8
I0502 09:41:31.180163       8 server.go:510] Running in resource-only container "/kube-proxy"
I0502 09:41:31.180948       8 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0502 09:41:31.181074       8 conntrack.go:52] Setting nf_conntrack_max to 131072
I0502 09:41:31.181326       8 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0502 09:41:31.181377       8 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0502 09:41:31.181489       8 config.go:202] Starting service config controller
I0502 09:41:31.181498       8 controller_utils.go:1027] Waiting for caches to sync for service config controller
I0502 09:41:31.181524       8 config.go:102] Starting endpoints config controller
I0502 09:41:31.181538       8 controller_utils.go:1027] Waiting for caches to sync for endpoints config controller
I0502 09:41:31.281603       8 controller_utils.go:1034] Caches are synced for service config controller
I0502 09:41:31.281607       8 controller_utils.go:1034] Caches are synced for endpoints config controller
W0512 23:44:39.156319       8 reflector.go:256] k8s.io/client-go/informers/factory.go:132: watch of *v1.Service ended with: too old resource version: 18762316 (25459801)
E0513 00:03:40.717955       8 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=8135, ErrCode=NO_ERROR, debug=""
E0513 00:03:40.717988       8 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=8135, ErrCode=NO_ERROR, debug=""
W0513 00:03:40.744191       8 reflector.go:256] k8s.io/client-go/informers/factory.go:132: watch of *v1.Service ended with: too old resource version: 25459801 (25462620)
W0513 02:42:25.540346       8 reflector.go:256] k8s.io/client-go/informers/factory.go:132: watch of *v1.Service ended with: too old resource version: 25462620 (25490982)
I0623 09:14:53.774071       8 proxier.go:656] Stale udp service kube-system/kube-dns:dns -> xx.xx.xx.x
E0623 12:32:20.555959       8 reflector.go:237] k8s.io/client-go/informers/factory.go:132: Failed to watch *v1.Endpoints: Get https://143eb521f0b325465rf6678gfr.yl4.xx-xxxx-x.eks.amazonaws.com/api/v1/endpoints?resourceVersion=35985678&timeout=9m36s&timeoutSeconds=576&watch=true: dial tcp x.xxx.xxx.xx:443: i/o timeout
W0626 09:14:12.483755       8 reflector.go:256] k8s.io/client-go/informers/factory.go:132: watch of *v1.Service ended with: too old resource version: 25490982 (36589739)
I0626 09:16:48.087082       8 proxier.go:656] Stale udp service kube-system/kube-dns:dns -> xx.xxx.x.xx
I0626 09:20:18.013019       8 proxier.go:656] Stale udp service kube-system/kube-dns:dns -> xx.xxx.x.xx
I0626 09:25:17.760949       8 proxier.go:656] Stale udp service kube-system/kube-dns:dns -> xx.xxx.x.xx
I0626 09:26:10.571580       8 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0626 09:26:10.571649       8 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF

**Comment by anusha-maheshwarappa-ip** [comment]
> Hi @anusha-maheshwarappa-ip , first let me know what type of nodes that your running on the cluster. If you have mixed one like windows and linux, then mention the nodeselector as Linux in you deployment file for alb ingress controller.
> 
> By default the deployment files doesnt have the node selector init.
> More over in your case you have only windows or a combination of the both you need to mention the nodeselector. Else cluster will pick up the one which is available

Hey, I have only one type of nodes that is linux , also has you mentioned we need to specify the nodeselector in ALB deployment files is it?

**Comment by anusha-maheshwarappa-ip** [comment]
> Hi @anusha-maheshwarappa-ip ,
> 
> I tried locally upgrading the ALB ingress controller and issue is not seen. Kindly share the kube-proxy logs.
> 
> Thanks.

Also I have a different in version like this 

eksctl version--->
0.22.0

kubectl version --short ---->
Client Version: v1.18.4
Server Version: v1.15.11-eks-xxxxx

kubectl get node -o custom-columns=NAME:.metadata.name,VERSION:.status.nodeInfo.kubeletVersion --->
NAME VERSION
ip-xxx-xxx-xxx-x.x-x-x.compute.internal v1.13.8-eks-xxxxx
ip-xxx-xxx-xxx-x.x-x-x.compute.internal v1.13.8-eks-xxxxx

will the version skew matter ?

**Comment by M00nF1sh** [comment]
seems this is connectivity to apiserver instead of the controller itself.
Is this issue still exists? if so, please create a support ticket to EKS team.

resolving this
