### ISSUE TITLE
Need option to just create target-group without an alb/listener record based on annotation

### ISSUE THREAD

**Issue by krish512** [kubernetes-sigs/aws-load-balancer-controller#1308]
Target groups are good to manage health as well as alarms etc for services. Even though we are using services internally and not consuming them from load balancer, its actually good to have their target group so we can see number of pods behind a service.

It may need us to support a service in ClusterIP. I am recommending that if we annotate a ClusterIP service as

```
alb.ingress.kubernetes.io/target-type: ip
kubernetes.io/ingress.class: alb
```

This should be able to create a target group without doing any ALB related stuff.

Thanks

Refer to https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/995

**Comment by M00nF1sh** [comment]
Hi, we plan to add a new CRD API called endpointBinding, which allow u to bind endpoints of a service to an external targetGroup.
However, there is no plan for a CRD API for targetGroup only(or the mentioned annotation here, since a service can bind to multiple targetGroups).
So u'll need to create targetGroup via aws API/cloudFormation, and use endpointBinding CRD to bind targets, did it solve your use case?

**Comment by krish512** [comment]
This is perfect, can you please point out once this is released?

**Comment by toricls** [comment]
@M00nF1sh That would be great! It could allow us to decouple ALB-related resources from a Kubernetes cluster. So, in my understanding, this is a different stuff from the `IngressGroup` CRD discussed in #688, correct?

**Comment by M00nF1sh** [comment]
Hi guys,
the new v2.0.0 release already have the TargetGroupBinding API support 😄 

closing this.

**Comment by rgg1993** [comment]
Hi there! I've got a question after reading this. 

I have an alb and target groups already configured in my aws account. 
Ive the pods deployed with service type NodePort 
I have the aws controller with the correct permissions needed 

But still, the target groups dont get the ip address updated when the pod is restarted, does any one have an idea on why? 

'''
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-tgb
  namespace: my-ns
spec:
  serviceRef:
    name: the-service-running
    port:  the-service-port
  targetGroupARN: the-tragetgroup-ARN 
  targetType: ip
'''
