### ISSUE TITLE
Support for AWS Firewall Manager via Centralized Tag Management

### ISSUE THREAD

**Issue by haneychad** [kubernetes-sigs/aws-load-balancer-controller#1316]
According to the following Issue the ALB Ingress Controller can exclude WAF from being controlled which is great:  https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/966

But AWS Firewall Manager WAF deployments are managed via Tags on ALBs.  We'd like the ability for the ALB Ingress Controller to exclude a specific Tag from management so that the specific Tag in question can be managed across thousands of AWS accounts by a separate centralized Tagging solution.

**Comment by M00nF1sh** [comment]
hi,
how would you like the UX to be. a command line flag like
`--waf-external-manage-tags=my-tag1=my-value,my-tag2`

**Comment by haneychad** [comment]
We use a single Tag key with various values to manage our AWS Firewall Manager deployments, your UX proposal seems to work as long as the following means that any value for my-tag1 is excluded from ALB Ingress Controller management...

--waf-external-manage-tags=my-tag1

@M00nF1sh can you confirm if that's the case?

If that's not the case and we need to define the possible values for the key, then may need something like...

--waf-external-manage-tags=my-tag1=my-value1,my-value2,my-value3,my-value4

**Comment by M00nF1sh** [comment]
yes. it's the case, any tag matching will be excluded.
to support multiple values, maybe make '--waf-external-manage-tags' to be specified multiple times. so
```
- --waf-external-manage-tags=my-tag1=my-value1,my-value2
- --waf-external-manage-tags=my-tag2
```
so, if it's my-tag1 and value is in [my-value1,my-value2] or it's my-tag2, exclude management.

**Comment by haneychad** [comment]
Excellent that would work perfectly..!

What's the next step to make the magic happen?

**Comment by M00nF1sh** [comment]
Hi, we'll implement this in our ALBV2 version. (Q3)

**Comment by haneychad** [comment]
It's now Q4 and we're still waiting for the ALBv2 GA release.  If an updated ETA can be provided that would be great.

**Comment by kishorj** [comment]
v2 is already available, we renamed it to aws-load-balancer-controller from aws-alb-ingress-controller.

**Comment by haneychad** [comment]
@M00nF1sh Can you confirm if this feature was released as part of ALBv2 controller?

**Comment by M00nF1sh** [comment]
@haneychad 
Sorry for the inconvenience. This feature is not released yet. I'll communicate internally and update here when will it be released.

**Comment by M00nF1sh** [comment]
@haneychad 
This is already supported by v2.2.0 with `--external-managed-tags"`

closing this issue
