### ISSUE TITLE
Questions about subnet usability & helm chart

### ISSUE THREAD

**Issue by maushah** [kubernetes-sigs/aws-load-balancer-controller#1317]
Less of an issue - more of a question that I cannot find answers to:

- We hit an issue with our subnets running out of IP addresses, this issue https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/1233/files appears to be able to mark subnets as not usable if they are out of IP addresses. We added 3 new subnets to the subnet annotation on the alb ingress which had 250 IPs free but the ingress controller kept using the older subnets with not enough IPs. Does the above not fix it where if a subnet has no free IPs it will NOT be used anymore but other subnets will be?

We were on v1.1.2 and then upgraded to v1.1.8 but still the same issue.

- On the helm chart from https://github.com/helm/charts/tree/master/incubator/aws-alb-ingress-controller - how do we set log levels to be debug - we hit some issues where the ingress controller was not cleaning up right but were not able to debug what was going on. If there is a different place for these issues let me know

**Comment by maushah** [comment]
Ignore the helm chart question - we figured it out using verbosity flags

**Comment by maushah** [comment]
We worked around the subnet question - had to remove the old subnets and add the new ones to the ingress, once that was done and the pods restarted - the ingress used the new subnets. Would be nice if the ingress controller could mark subnets as unusable. 

Another question we are trying to find out is how to scale the ingress controllers if we have 200+ ALBs managed by 1 controller in 1 region - adding more replicas would help?

**Comment by M00nF1sh** [comment]
Hi, you don't need to scale out the controller. It should be able to handle 200+ ingress with a single controller pod.

Also, if you do facing some performance issue, you can either 
1. leverage the 'watch-namespace' flag "https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/alb-ingress-controller.yaml#L28" to setup multiple controllers each watch different namespace
2. leverage the 'ingress-class' flag 'https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/alb-ingress-controller.yaml#L33 to setup multiple controllers each watch different ingress class

**Comment by maushah** [comment]
@M00nF1sh thanks for your reply, and also for all the support on the site. 

Our setup is a bit odd - we have 260 odd ALBs in the same namespace as its a multi instance type service - so using namespace watching will not help. Also the class from what I see would be the same as its all ALBs - unless am wrong.

We did open a support ticket with AWS and they mentioned going to the beta for v2 as a possible option to fix the reconcile issues. We do use WAF as well so cannot turn that off. 

The current behavior we see is that updating the ALB either with new pods as old pods have failed or a restart occurred OR with new annotations or rules takes anywhere between 30-45 minutes and we are not 100% sure what gets priority - changes or target deregistration OR reconcilation. Looking here https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/how-it-works/ does not provide any clues, neither do the logs (cant make it too verbose as we have a ton of ALBs). Let us know if you have any other thoughts as well.
