### ISSUE TITLE
Update documentation for security groups to reflect changes in #1019

### ISSUE THREAD

**Issue by mbarrien** [kubernetes-sigs/aws-load-balancer-controller#1318]
The documentation at https://github.com/kubernetes-sigs/aws-alb-ingress-controller/commits/master/docs/guide/ingress/annotation.md doesn't appear to be up to date to reflect the changes made in #1019 where the ingress controller will reuse the existing security group (or a security group with the proper tag). It still makes it look like that you will run into the per-ENI security group limit, rather than the per-SG rule count limit.

This is reflected in open issues such as https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1181 or https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1203 where the questions still seem to assume the old behavior.

**Comment by M00nF1sh** [comment]
/kind documentation
We'll update the docs to reflect the change :D

**Comment by M00nF1sh** [comment]
the documentation have been updated in our latest v2.0.0 docs.

resolving .
