### ISSUE TITLE
Incidental misconfiguration should not prevent target groups from being updated

### ISSUE THREAD

**Issue by edlee2121** [kubernetes-sigs/aws-load-balancer-controller#1319]
Currently, misconfiguration of attributes such as:
* WAF rule
* s3-access-log bucket
* ACM Cert ARN
* security group

Will prevent the target group from being updated. This means that specifying a non-existent s3-access-log bucket, for example, will eventually result in routing failure as old nodes are terminated but the target group cannot be updated with new nodes.

**Comment by M00nF1sh** [comment]
Hi, we are already working on a fix for such issue.(we'll separate targetGroup updating functionality out), so misconfiguration will just prevent new targetGroup been updated.

**Comment by larsrnielsen** [comment]
Is it the same issue I not-knowingly face?

EKS cluster
3 node groups, one for each AZ used
ArgoCD application with Ingress deployed -> ALB Ingress Controller creates an ALB.
The ALB is linked to a Target Group. The Target Group points to the IP address of the Node where the ArgoCD server Pod object is deployed.  

If the Pod is destroyed the Deployment creates a new Pod - using another Node - but the Target Group is not updated to point to the 'new' Node's IP. This generates a Bad Gateway 502 error. 

How can I debug this scenario? E.g., how to know if I have done something wrong with the Security Group?

Lars

**Comment by M00nF1sh** [comment]
@edlee2121 The issue have been addressed in latest >=v2.0.0 releases.
resolving this.

@larsrnielsen have you try out our latest v2.0.1 release? your issue doesn't seem like this one unless your ingress have misconfigurations
