### ISSUE TITLE
Setting up ALB controller for Kubespray kubernetes cluster on AWS Instance

### ISSUE THREAD

**Issue by amitcmore** [kubernetes-sigs/aws-load-balancer-controller#1320]
Hello, 

I have configured the kubernetes cluster using kubespray on AWS EC2 instance. its not an EKS cluster. 
I want to use AWS ALB controller for same, could you please help me how i can setup the same for my kubernetes cluster. It will be really helpful if you help me with setp by step process.

**Comment by M00nF1sh** [comment]
Hi, the setup steps is same. You just need to follow https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/setup/ 
only notice two thing:
1. make sure your worker node have proper iam permission. https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/iam-policy.json
2. make sure the cluster-name in the controller-yaml is set correctly: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/alb-ingress-controller.yaml#L39
