### ISSUE TITLE
Ingress configuration issues

### ISSUE THREAD

**Issue by talonx** [kubernetes-sigs/aws-load-balancer-controller#1322]
I have an EKS cluster setup using the web console (not eksctl). While attempting to deploy an ALB ingress, this is what the logs show

```
E0716 08:57:23.896186       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: c477ded6-8830-4c23-a8b5-297ba9a8bbf6"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"***removed***"}
```

This is after following the instructions at https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

My trust relationship looks like

```
Key: oidc.eks.us-east-1.amazonaws.com/id/18063776DCE360175FBD0C9F68DAFF71:sub
Value:  system:serviceaccount:kube-system:alb-ingress-controller 
```

I looked at #1153 and #1171, but they were of no help - everything mentioned there is done.

**Comment by M00nF1sh** [comment]
Hi, this is an issue about iam-for-service-accounts feature.
You can follow below steps to test whether your trust relation is setup correctly:
1. create a normal pod in kube-system that also using alb-ingress-controller serviceaccount.
2. kubectl exec into the pod, and get the mounted token(you can find token path in pod spec)
3. manually assume the role  for pod with ```
aws sts assume-role-with-web-identity \
 --role-arn $AWS_ROLE_ARN \
 --role-session-name anyname \
 --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE \
 --duration-seconds 1000
```

**Comment by M00nF1sh** [comment]
resolving this.

**Comment by Vishal2696** [comment]
> Hi, this is an issue about iam-for-service-accounts feature.
> You can follow below steps to test whether your trust relation is setup correctly:
> 
> 1. create a normal pod in kube-system that also using alb-ingress-controller serviceaccount.
> 2. kubectl exec into the pod, and get the mounted token(you can find token path in pod spec)
> 3. manually assume the role  for pod with ```
>    aws sts assume-role-with-web-identity 
>     --role-arn $AWS_ROLE_ARN 
>     --role-session-name anyname 
>     --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE 
>     --duration-seconds 1000

@M00nF1sh  Is this the permanent solution for this? or is this for testing purpose? How to correctly resolve this error?
