### ISSUE TITLE
support for ARM

### ISSUE THREAD

**Issue by alittlec** [kubernetes-sigs/aws-load-balancer-controller#1329]
Hi,

Now there are M6G instances, and EKS for ARM available - will an ARM64v8 build be available?

**Comment by kishorj** [comment]
ARM support is available in v1.1.9. This is the first multi-arch image with support for 
* linux/amd64
* linux/arm64
For further details, please refer to https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.1.9

**Comment by mikechiang2003** [comment]
We need features (group.name) from 1.2.0. just wondering when 1.2.0 build for arm64 will be released?

**Comment by kishorj** [comment]
ARM support and Ingress group support is available in the the new v2.0.0 release.
