### ISSUE TITLE
[Question] Naming ELB 

### ISSUE THREAD

**Issue by davorceman** [kubernetes-sigs/aws-load-balancer-controller#1331]
Hello, is it possible to set LB name via annotations, or somehow...?
I tried with adding Name tag, but no success, my ELBs are always created with name similar to this
5048fede-default-vault-c063

Or at least... how to know in advance, with what name will be created? Because I'm using terraform for deploying helm charts and AWS resources, and I need to reference other resources to this LB

**Comment by M00nF1sh** [comment]
/kind feature
Hi, it's currently not possible to set the name.
The name is generated here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/alb/generator/name.go#L23

**Comment by davorceman** [comment]
Thx for the response.
It would be nice to have that feature.
Usually AWS resourcess are named with the Tag "Name".
Maybe this naming feature can be overridden if Name tag exist in annotations.

Then in terraform with data resource we can reference all other resources, like CloudFront is.

**Comment by ffjia** [comment]
> Thx for the response.
> 
> It would be nice to have that feature.
> 
> Usually AWS resourcess are named with the Tag "Name".
> Maybe this naming function can be overridden if Name tag exist in annotations.

It seemed not work for ALB. The Name did not get updated, after I added the `Name` tag for it.

**Comment by kishorj** [comment]
Feature request https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1483
