### ISSUE TITLE
Reason for "8 free IP Addresses for ALB" requirement?

### ISSUE THREAD

**Issue by NeckBeardPrince** [kubernetes-sigs/aws-load-balancer-controller#1333]
I checked the docs and I can't find anything on this requirement.

**Comment by M00nF1sh** [comment]
Hi,
It's specified here: 
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html
> To ensure that your load balancer can scale properly, verify that each Availability Zone subnet for your load balancer has a CIDR block with at least a /27 bitmask (for example, 10.0.0.0/27) and has at least 8 free IP addresses.

**Comment by NeckBeardPrince** [comment]
@M00nF1sh Wow I guess I'm just the unlucky sucker that was given a very small public subnet to work with.
I bet this doesn't impact 99% of people or orgs.

**Comment by M00nF1sh** [comment]
I'm really sorry for the trouble u are facing. But there isn't much we can do from the controller side.

I *guess* the 8 free IP address requirement come from ALB itself's implementation, otherwise it will add downtimes when they  upgrade their nodes.

**Comment by NeckBeardPrince** [comment]
@M00nF1sh Oddly it seems you can continue to create ALB or other resources below 8 free ip addresses. I assume there is no way, right now to set a --feature-gate to disable the limit?

**Comment by M00nF1sh** [comment]
@NeckBeardPrince 
The new aws-load-balancer-controller removed the limit :D

**Comment by sarbajitdutta** [comment]
@M00nF1sh I don't think so. I upgraded from alb ingress controller v1.x to ALB load balancer controller v2.0.0 and it still requires 8 free IPs in each subnet.

```
{"level":"error","ts":1606329481.2930484,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"reciter-ing","namespace":"reciter","error":"InvalidSubnet: Not enough IP space available in subnet-xxxxxxxxxxxxxx. ELB requires at least 8 free IP addresses in each subnet.\n\tstatus code: 400, request id: 2a37780c-f411-xxxxx-xxxxx-xxxxxxxxx"}
```
