### ISSUE TITLE
Creating LoadBalancer service on Fargate should auto-create ALB Ingress Controller and Ingress

### ISSUE THREAD

**Issue by vgribok** [kubernetes-sigs/aws-load-balancer-controller#1337]
Problem: exposing a service running on Fargate to the Internet is a [chore seemingly requiring creating an ALB Ingress Controller with parameters that are all known](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) (cluster, VPC, region), plus creating similarly boilerplate-like [Ingress per service](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/2048/2048-ingress.yaml).

Proposed Solution: when the first LoadBlancer service with pods on Fargate is created on a cluster, auto-create Ingress controller with sensible defaults, followed by auto-creation of an Ingress/ALB per each LoadBalancer service running on Fargate.

**Comment by kishorj** [comment]
Work is in progress to support NLB for Fargate pods. Please refer to https://github.com/aws/containers-roadmap/issues/617 and https://github.com/aws/containers-roadmap/issues/981 for further details.

**Comment by M00nF1sh** [comment]
We'll provide a managed addon for this controller 😄 

closing this for now.
