### ISSUE TITLE
how to whitelist ip address

### ISSUE THREAD

**Issue by gauravachatrath** [kubernetes-sigs/aws-load-balancer-controller#1341]
Hi Team,

We need to whitelist ip some domain. We can whitelist the ip but the ip of server keep on changing so is there a way to whitelist the domain ?

**Comment by M00nF1sh** [comment]
hi, we cannot whitelist a domain. The best approach should be whitelist a CIDR that your server are in.

Or if your server is running in aws, you can create a in-vpc ALB Ingress controller. (and use mechanism such as vpc peering for cross-vpc communication)

**Comment by gauravachatrath** [comment]
the cidr keep on changing too so we can't use cidr

**Comment by M00nF1sh** [comment]
@gauravachatrath 
The controller didn't have a way to know the the IP addresses behind your DNS domain. 
I think for such use case, you might need to build a custom controller that modifies Ingress's CIDR annotations.

We cannot support this in side this controller as it's not a general use case.
