### ISSUE TITLE
alb.ingress.kubernetes.io/auth-scope is not escaped in Location header

### ISSUE THREAD

**Issue by jswidler** [kubernetes-sigs/aws-load-balancer-controller#1344]
According to the documentation here: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#auth-scope, a valid auth scope could be defined as 'email openid'.  However, this produces redirect links of the following form, with the space:

```
Location: https://xxx.amazoncognito.com/oauth2/authorize?client_id=xxx&redirect_uri=xxxresponse_type=code&scope=openid email&state=xxx
```

Note that the space between `openid` and `email` is preserved and not encoded to `%20`

While this works with modern browsers because they refuse to send the space, it is not the correct form for the redirect, and so, for instance, the Go http.Client we used trying to follow that redirect link cannot find the page there.

**Comment by jswidler** [comment]
For now, I fixed this problem on the other side with code like this:

```
		http.Client{
 			...
			CheckRedirect: func(req *http.Request, via []*http.Request) error {
				req.URL.RawQuery = strings.ReplaceAll(req.URL.RawQuery, " ", "%20")
				return nil
			},
		}
```

I don't think this should have been necessary.

**Comment by jswidler** [comment]
I looked through the code, my current though is that this is poor behavior on the AWS side and not this controller, but I wouldn't mind a second opinion. 

I did find the scope is fed into the aws sdk in a AuthenticateCognitoActionConfig struct, which documents the Scope field 

> The set of user claims to be requested from the IdP. The default is openid.
> To verify which scope values your IdP supports and how to separate multiple values, see the documentation for your IdP.

Space separated into this struct seems to be the goal.

**Comment by M00nF1sh** [comment]
Hi, i forwarded this to the PM of ELB

**Comment by jswidler** [comment]
Thanks.  I also contacted AWS - the confirmed the bug and said they forwarded it to the team, but could not provide ETA on a fix and I think they closed the ticket.  I'm not sure whether to leave this open or wait until there is a fix (in case others find this useful in the meantime), so I will leave it open for the maintainers to decide.  If I notice it is fixed I can follow up here.

**Comment by M00nF1sh** [comment]
@jswidler 
I'll close this and track this in a centralized ALB issue: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1344
