### ISSUE TITLE
Error using cognito in one account and ALB in another account

### ISSUE THREAD

**Issue by newtoworld999** [kubernetes-sigs/aws-load-balancer-controller#1375]
Hi
I am trying to use ALB ingress controller to authenticate a sample application deployed in eks to be authenticated with cognito.
I have ALB & eks cluster deployed in Account A and my cognito user pool is in Account B
Here is my ingress object configuration
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:us-east-1:<acctB-no>:userpool/us-east-1_YaWExlqBp", "UserPoolClientId":xxxxx", "UserPoolDomain":"abc"}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:<acctA-no>:certificate/bae36e74-d7f1-4b68-9bda-69c15f0c65
  labels:
    app: demoapp
spec:
  rules:
  - host: xxx.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
  - host: xxx.com
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-service
          servicePort: 80
  - host: xxx.com
    http:
      paths:
      - path: /helloworld
        backend:
          serviceName: helloworldapp-service
          servicePort: 80
  - host: xxx.com
    http:
      paths:
      - path: /oauth2/idpresponse
        backend:
          serviceName: helloworldapp-service
          servicePort: 80

In the ALB ingress controller iam getting below error

I0827 16:35:47.181034       1 listener.go:110] default/ingress: creating listener 443
E0827 16:35:47.201218       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to create listener due to InvalidLoadBalancerAction: 'arn:aws:cognito-idp:us-east-1:acctB-no:userpool/us-east-1_xxxx' is not a valid user pool ARN\n\tstatus code: 400, request id: 182736bd-6e2d-401e-95d9-e1ac26774ea4"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"ingress"}
I0827 16:35:48.782316       1 listener.go:110] default/ingress: creating listener 443
E0827 16:35:48.795454       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to create listener due to InvalidLoadBalancerAction: 'arn:aws:cognito-idp:us-east-1:acctB-no:userpool/us-east-1_xxxx' is not a valid user pool ARN\n\tstatus code: 400, request id: e84586f0-c5ef-4291-8b0f-3c6f1892bba5"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"ingress"}
I0827 16:35:51.667967       1 listener.go:110] default/ingress: creating listener 443
E0827 16:35:51.684123       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to create listener due to InvalidLoadBalancerAction: 'arn:aws:cognito-idp:us-east-1:acctB-no:userpool/us-east-1_xxxx' is not a valid user pool ARN\n\tstatus code: 400, request id: d155496d-88e6-413e-a21b-cf2491cfd642"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"ingress"}
I0827 16:35:57.158168       1 listener.go:110] default/ingress: creating listener 443
E0827 16:35:57.174416       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to create listener due to InvalidLoadBalancerAction: 'arn:aws:cognito-idp:us-east-1:acctB-no:userpool/us-east-1_xxxx' is not a valid user pool ARN\n\tstatus code: 400, request id: 8be78f47-1d75-4bdf-aa7e-3ed206a63ca8"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"ingress"}

**Comment by newtoworld999** [comment]
We cannot use the Cognito user pool which is created in another account and ALB in one account? Both ALB and cognito are in the same region

**Comment by M00nF1sh** [comment]
Hi, our oncalls will try to reproduce and cut ticket to ALB team to query whether such behavior is desired.

**Comment by antonyfray** [comment]
Is this still being investigated? I'd be curious to know if the team intends for this to be possible

**Comment by juozasget** [comment]
Hi @M00nF1sh, what is the conclusion on this issue?

We would like to use a single Cognito pool for multiple ALB's in multiple AWS accounts.
