### ISSUE TITLE
Run controller as non-root user

### ISSUE THREAD

**Issue by rafaelpereyra** [kubernetes-sigs/aws-load-balancer-controller#1381]
Best practices published for Amazon EKS recommend not running containers as root [user](https://aws.github.io/aws-eks-best-practices/pods/#do-not-run-processes-in-containers-as-root) and restrict containers that can run as [privileged](https://aws.github.io/aws-eks-best-practices/pods/#restrict-the-containers-that-can-run-as-privileged).

aws-alb-ingress-controller doesn't specify an user in the Dockerfile and is not straight forward how to run as non-root. As comparison, external-dns project provides instructions for this [here](https://github.com/kubernetes-sigs/external-dns/blob/83f52f6e7d7bd78cbd3ca916d578ee3ecf008233/docs/tutorials/security-context.md).

**Comment by kishorj** [comment]
A `securityContext` can be specified in the aws-alb-ingress-controller pod spec to run as a non-root user. I tested using this config - 
```
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
```

We will check if there are any corner cases and add documentation for this.

**Comment by M00nF1sh** [comment]
@rafaelpereyra 
Our new v2.0.0 release is running as a non-root user now 😄
