### ISSUE TITLE
Cognito configuration not updated

### ISSUE THREAD

**Issue by newtoworld999** [kubernetes-sigs/aws-load-balancer-controller#1382]
Hi
created the ingress object like below nd deployed the alb ingress controller, listners are created but the cognito configuration is not created with the alb ingress controller and ingress object
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:us-east-1:<acctB-no>:userpool/us-east-1_YaWExlqBp", "UserPoolClientId":xxxxx", "UserPoolDomain":"abc"}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:<acctA-no>:certificate/bae36e74-d7f1-4b68-9bda-69c15f0c65
  labels:
    app: demoapp
spec:
  rules:
  - host: xxx.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
  - host: xxx.com
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-service
          servicePort: 80
  - host: xxx.com
    http:
      paths:
      - path: /helloworld
        backend:
          serviceName: helloworldapp-service
          servicePort: 80
  - host: xxx.com
    http:
      paths:
      - path: /oauth2/idpresponse
        backend:
          serviceName: helloworldapp-service
          servicePort: 80

      app.kubernetes.io/name: alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      containers:
        - name: alb-ingress-controller
          args:
            - --ingress-class=alb
           - --cluster-name=pocekscluster
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.8

**Comment by kishorj** [comment]
Are there any errors in the alb-ingress-controller? If possible, please share it with us.

**Comment by newtoworld999** [comment]
I havent received any errors in the ingress controller, but ALB also didnt update with Cognito configuration for authentication.

**Comment by M00nF1sh** [comment]
@newtoworld999 
I believe this issue is resolved in our v2.0.0 release. there were race conditions in old controller that cause annotations not been picked up.

Feel free to reopen if this issue exists in v2.0.0 as well.
