### ISSUE TITLE
Add deployment documentation

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/aws-load-balancer-controller#1391]
Currently there is only documentation how to use the helm chart or an example manifest, but there should be documentation about different things (and added to the example manifest, if appropriate) 

- Is a port being exposed? If yes, which API endpoints are available?
- Is there a readiness / liveness endpoint? Can we use a readinessProbe / livenessProbe?
- Can the controller run with more than 1 replica? I've seen something about leader election in the logs. If yes, does it have to be a odd number of replicas? Does it make sense to run more than one replica?
- The helm chart adds a terminationGracePeriodSeconds of 60. Is there a specific reason for a higher number (default is 30)?
- Resource memory requests / limits should be added in the example manifest

- Command line arguments should be documented. Some are in the example manifest, but according to https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/cmd/options.go there is more going on.

**Comment by dudicoco** [comment]
I believe that leader election is something that is not documented anywhere.

Can anyone shed some light on the leader election mechanism? Does it indeed require an odd number of pods? How does it maintain state with the associated configmap? 
@M00nF1sh

**Comment by M00nF1sh** [comment]
@dudicoco 
It does leadership election by keep updating a configmap with current leader and lease time.
U don't need odd number of pods. (two pods will work too).

**Comment by kishorj** [comment]
We already provide installation guide https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/
and configuration guide https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/configurations/

Closing this issue for now. If there is anything missing in the installation or configuration guides, feel free to open a new issue or create a PR.

**Comment by mbyio** [comment]
@kishorj I don't think any of the things listed in this issue are documented on the pages you linked. Did you mean to link to some additional documentation? Otherwise, I think this issue should be reopened.

**Comment by kishorj** [comment]
@mbyio here are the items that I was referring to, 
- Command line arguments -https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/configurations/#controller-command-line-flags
- leader election is mentioned in the command line arguments
- helm chart configuration options - https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller#configuration
- liveness probe configurable for helm chart - refer to the helm chart configuration options
- resource limits can be configured during helm chart installation. The reference manifest lists out sample cpu/memory limitations, for example https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/8f1c32cfc548c0509bef5afbe7f2e2795a63d393/docs/install/v2_2_1_full.yaml#L814-L820
- I'm not certain where the terminationGracePeriodSeconds of 60 seconds come from, the values we use in the chart/reference manifest is 10 seconds. This value is configurable during chart installation.

Please let us know if there is anything missing, or you want to add to the documentation. Feel free to raise a PR as well.
