### ISSUE TITLE
EKS security group ingress rule from ALB seems odd

### ISSUE THREAD

**Issue by joneal** [kubernetes-sigs/aws-load-balancer-controller#1393]
When an EKS cluster is created, a security group for the cluster is also created.  This security group has one ingress rule:  accept all traffic on all ports but only from itself.  This security group is used to allow the EKS control plane and worker nodes to communicate.

When the ingress controller creates an ALB, a new ingress rule is injected into the cluster security group.  This rule allows all TCP traffic on all ports (0-65535) from the ALB.  This ingress rule permits traffic from clients via ALB to reach worker nodes.  However, it also permits application traffic from clients via ALB to reach the EKS control plane, theoretically.   This seems incorrect, from a security group/networking perspective.

It seems like an additional security group should be created that permits all TCP traffic on all ports from the ALB and this security group assigned to the worker node group.   The result is the worker nodes have two security groups, one for the cluster and one for ALB.  The EKS cluster should only have its cluster security group limiting K8S oriented traffic from the worker nodes.

**Comment by M00nF1sh** [comment]
@joneal 
We decided to not take that approach as ENIs have 5 SecurityGroup limit.
If we want to have finer controller on pod's securityGroup,  we can use the [securityGroup for pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) feature to assign dedicated securityGroup to pods, and using IP TargetType. The controller will modify the securityGroup you assigned to pods only.
