### ISSUE TITLE
How do I set response headers?

### ISSUE THREAD

**Issue by dsalaza4** [kubernetes-sigs/aws-load-balancer-controller#1397]
With Kubernetes ingress I was able to set headers by doing:

```
nginx.ingress.kubernetes.io/configuration-snippet: |
  more_set_headers "X-XSS-Protection: 1; mode=block";
```

Is there a way to set custom response headers with alb ingress controller?

**Comment by M00nF1sh** [comment]
closing this, and track in centralized ALB feature request: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571
