### ISSUE TITLE
Pods failing to be removed from Target Group after scale down

### ISSUE THREAD

**Issue by learoyklinginsmith** [kubernetes-sigs/aws-load-balancer-controller#1409]
We're currently running v1.18 of the controller and have been experiencing some interesting behavior. In these particular examples, we have both a private and public ingress for the same service. In the first example, a call is made to deregister the targets out of the private target group, then 16 seconds later the call is made to deregister the targets from the public target group:
![image](https://user-images.githubusercontent.com/15451763/92956586-5a58f200-f424-11ea-9d76-01c43c75accd.png)

In the second example, I don't see a call at all from the ingress controller to deregister targets out of the public target group:
![image](https://user-images.githubusercontent.com/15451763/92956743-a310ab00-f424-11ea-8f4f-1acf785230fe.png)

To ensure that it wasn't just a missing log, I confirmed that there also weren't corresponding API calls in cloud trail to deregister these same targets. Additionally, I've confirmed that the ingress controller pod isn't resource constrained, as well as searched through the logs looking for any sort of timeout errors trying to hit the API.

This issue is causing large spikes of 502s for us as traffic is being routed to the pods that have already shut down. Do you have any suggestions on what we can do to remediate this and ensure that the ingress controller is appropriately making calls to deregister the targets?

**Comment by M00nF1sh** [comment]
@learoyklinginsmith 
Please try out our new v2.0.0 release, it dramatically improved the AWS API usage, which should solve this problem.

closing this, feel free to reopen if such issue exists in our v2.0.0 release.
