### ISSUE TITLE
MalformedPolicyDocument iam-policy.json

### ISSUE THREAD

**Issue by davidcsi** [kubernetes-sigs/aws-load-balancer-controller#1415]
I just tried using

https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/iam-policy.json

like:

`$ aws iam create-policy   --policy-name ALBIngressControllerIAMPolicy   --policy-document https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/master/docs/examples/iam-policy.json`

and got:

An error occurred (MalformedPolicyDocument) when calling the CreatePolicy operation: Syntax errors in policy.

Thanks

**Comment by davidcsi** [comment]
Funny this, if i use the document to create the policy in AWS CONSOLE, it works fine.

**Comment by smuramshetty** [comment]
@davidcsi if you are still facing issue - this should work

aws iam create-policy --policy-name ALBIngressControllerIAMPolicy --policy-document file://"<localpath-to-policyjson>\iam-policy.json"

**Comment by davidcsi** [comment]
Thanks, I will try that.
Regards,

David Villasmil
email: david.villasmil.work@gmail.com
phone: +34669448337

**Comment by M00nF1sh** [comment]
@davidcsi 
Seems the AWSSDK behavior changed, you need to first download the policy as file, and use "file://` to create it.

```
curl -o iam_policy.json  https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json
aws iam create-policy --policy-name ALBIngressControllerIAMPolicy --policy-document file://iam_policy.json
```

closing this, feel free to reopen if we have any other issues

**Comment by yungyili** [comment]
> @davidcsi if you are still facing issue - this should work
> 
> aws iam create-policy --policy-name ALBIngressControllerIAMPolicy --policy-document file://"\iam-policy.json"

This solution works for me. Thank you so much!

**Comment by mbigras** [comment]
Also, to avoid persisting the iam-policy.json file, you can use [_Bash process substitution_](https://tldp.org/LDP/abs/html/process-sub.html) like the following shell session illustrates.

```bash
$ aws iam create-policy \
    --policy-name ALBIngressControllerIAMPolicy \
    --policy-document https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/iam-policy.json

An error occurred (MalformedPolicyDocument) when calling the CreatePolicy operation: Syntax errors in policy.
$ aws iam create-policy \
    --policy-name ALBIngressControllerIAMPolicy \
    --policy-document file://<(curl https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/iam-policy.json)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3546  100  3546    0     0  17271      0 --:--:-- --:--:-- --:--:-- 18091
{
    "Policy": {
        "PolicyName": "ALBIngressControllerIAMPolicy",
# ...
```
