### ISSUE TITLE
Traffic not get balanced between pods

### ISSUE THREAD

**Issue by siqusoft** [kubernetes-sigs/aws-load-balancer-controller#1418]
we are using alb ingress controller and we noticed traffic not get balanced between pods on load testing.

**Comment by siqusoft** [comment]
"error":"unknown targetGroup attributes: [load_balancing.algorithm.type]","errorVerbose":"unknown targetGroup attributes: [load_balancing.algorithm.type]

**Comment by M00nF1sh** [comment]
@siqusoft 
You should use our IP targetType. If you are using instance TargetType, the ALB will reuse the backend connections to nodes(kubeproxy), so it may not be evenly balanced.

closing this.  feel free to reopen if this issue still exists after using IP TargetType :D
