### ISSUE TITLE
Connection timed out for ingress

### ISSUE THREAD

**Issue by xiechen0692** [kubernetes-sigs/aws-load-balancer-controller#1424]
Hi, I am using aws eks to build my application. I follow the step and everything is fine:
https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html
1.apply deplyment
2.apply service
3.apply ingress
there is address for ingress.

> NAME           HOSTS                 ADDRESS                                                                                PORTS   AGE
> xxxx-ingress   xxxx-xxxx   internal-example-default-xxxxx-xxxxx-xxxxxxxxxxx.ap-northeast-1.elb.amazonaws.com   80      19m

When I try to use curl command to test the ingress, I get timeout problem.
I can not find the req sent to ingress when I check the logs: kubectl logs -n kube-system   deployment.apps/alb-ingress-controller
**Looks like ingress didn't get the request**. Can anyone help me to solve this problem? Thanks a lot!

**Comment by M00nF1sh** [comment]
Hi, seems you are using an internal loadbalancer. (the dns name have a "internal" prefix).
Internal loadbalancer can only be accessed from within your VPC. Did you do curl from within VPC(e.g. on a worker node).

If you want to create a internet-facing LoadBalancer, you need to specify `alb.ingress.kubernetes.io/scheme: internet-facing` on your Ingress objects.

**Comment by M00nF1sh** [comment]
@xiechen0692 
Is the issue still exists? feel free to reopen if it still exists :D
