### ISSUE TITLE
Health Check/Sanity Check

### ISSUE THREAD

**Issue by mothershipper** [kubernetes-sigs/aws-load-balancer-controller#1428]
We noticed today that our ALB ingress controller was reaped several times by the k8s health checker -- however, the logs suggested the controller was up and responding the in the reconcile loop. When we port-forwarded to the pod and tried to load the `/healthz` endpoint, we experienced the connection hanging / no result from the health check endpoint.

At a minimum, I think it might be worth setting an HTTP client timeout -- if unset, the [default aws config](https://github.com/aws/aws-sdk-go/blob/16cef773033e77d97f42fa5655c13bace6b9edc7/aws/defaults/defaults.go#L59) uses an http client [without a connection timeout](https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779).

Because the ALB controller leaves this unset, it uses the default client: 

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/aws/cloud.go#L82

Which leaves the health check endpoint susceptible to a hung connection:

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/aws/healthcheck.go#L16-L19

Setting a timeout would at a minimum let the controller respond to the health check, and give us logs sooner when an endpoint hangs. And maybe this also gives the sdk a chance to retry before k8s decides the pod is unhealthy. I'd be happy to open a PR if that sounds reasonable!

Somewhat of a tangent -- if the health check finds an AWS service (or the network) is unhealthy, should that actually cause the pods to be labeled unhealthy and get restarted?  I've got a mixed opinion. As the operator, I'd want to get notified, but at the same time, the restart behavior doesn't resolve the issue and is triggering an unrelated crashloop alert. 

Perhaps we could collect stats out of band, like the number of AWS API calls failing (or reconcile loops failing), and use those stats to determine the health/liveliness?

**Comment by M00nF1sh** [comment]
Hi @mothershipper 
Thanks for reporting this.

I agree that the current healthy check mechanism is not correct. we should only do such AWS service-api checks at controller startup if required. reboot the controller pod via healthCheck won't solve aws service unavailability issue. 
We'll fix this in our next up-coming v2.0.0 GA release.

**Comment by M00nF1sh** [comment]
@mothershipper 
In our v2.0.0 release, we simply used a ping handler to respond to healthz requests.
we shouldn't check aws services at healthz as restart the pod won't help in such case.

closing this.
