### ISSUE TITLE
ALB Ingress Controller Deletes Application Load Balancer

### ISSUE THREAD

**Issue by jamesgustard** [kubernetes-sigs/aws-load-balancer-controller#1435]
We are using the aws-alb-ingress-controller in an EKS fargate cluster. We recently  had an outage caused by the  aws-alb-ingress-controller  deleting the ALB and creating a new ALB, this caused DNS lookups from a NLB lambda on the ALB DNS name to fail, as the DNS name changed.
Is there a way to prevent the ALB Ingress Controller from deleting the ALB?
Under what circumstances would the ALB Ingress Controller delete the ALB?

**Comment by M00nF1sh** [comment]
Hi @jamesgustard,
We should only delete the ALB if you do either
* deletes the Ingress object (if you delete and recreate the Ingress, the ALB will be deleted and recreated as well)
* changed some key annotations like `alb.ingress.kubernetes.io/scheme` or `alb.ingress.kubernetes.io/ip-address-type`.  (such settings are immutable on ALB, so we have to delete & recreate if we have such changes)

**Comment by M00nF1sh** [comment]
@jamesgustard 

Is the issue still exists? feel free to reopen if it still exists :D
