### ISSUE TITLE
alb.ingress.kubernetes.io/tags annotation support on the service level

### ISSUE THREAD

**Issue by korobass** [kubernetes-sigs/aws-load-balancer-controller#1436]
Hi Guys,

In the beginning, I would like to thank you for all the functionality that this project provides.

I have one small request to have the possibility to use tags annotation on the service level. 
Our monitoring automation strongly relies on tags.  We're using single ALB/ingress for each namespace with multiple host-based rules to expose multiple micro-services that are running on Kubernetes. We would like to have the ability to set different tag values for each K8S-service/ALB-target-group to provide the necessary SLA. In other words, one service can be mature enough to assure monitoring, another may not be ready to be monitored, and by using a tag with the custom value on the target group level, we can potentially set this independently.

Thanks in advance for considering this feature.
Marek K.

**Comment by M00nF1sh** [comment]
@korobass 
Hi, we have an upcoming new release which solves this issue.
The tags on targetGroups will be a merge for tags on services and tags on ingresses. (where services takes priority).

The logic is if you specified `alb.ingress.kubernetes.io/tags` on service, the tags on service will be used. 
However, if you specified `alb.ingress.kubernetes.io/tags` on both Service / Ingress, these tags won't be merged at k/v level.
Is it the desired behavior?

**Comment by M00nF1sh** [comment]
@korobass 
This is already supported in our v2.0.0 release per behavior described above 😄 
closing this :D

**Comment by korobass** [comment]
Thx a lot. Hopefully, we'll be able to migrate to the newest version.
