### ISSUE TITLE
Ability to remove response 

### ISSUE THREAD

**Issue by ggwpp** [kubernetes-sigs/aws-load-balancer-controller#1454]
Is there any way to remove response header on alb ingress controller? 
In nginx ingress controller we can set up by `hide-headers` configmap. 

- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#hide-headers

**Comment by M00nF1sh** [comment]
close this issue and track in our centralized issue instead: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571
