### ISSUE TITLE
load-balancer-attributes fails when no prefix is provided

### ISSUE THREAD

**Issue by adamkgray** [kubernetes-sigs/aws-load-balancer-controller#1466]
Background:

In the docs it is specified that you can configure access logs in the following way:

```
alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-access-log-bucket,access_logs.s3.prefix=my-app
```

Expected behavior:

If you omit the `access_logs.s3.prefix` or just do `access_logs.s3.prefix=`, it should work and not use a prefix

Actual behavior:

If you omit the `access_logs.s3.prefix` or just do `access_logs.s3.prefix=`, it fails silently and does not enable access logs. The only workaround is to provide an empty string `""` as the prefix value. But this is a bug.

**Comment by kishorj** [comment]
What is your controller version?

**Comment by kishorj** [comment]
This issue has been fixed in the upcoming v2 release.

**Comment by adamkgray** [comment]
Whats the best way to include the changes in my cluster? I have deployed
using the template provided by aws. Can i just update a docker image tag in
that file to pull that latest version with the bug fix?

**Comment by adamkgray** [comment]
I have been getting errors this past week in the current version, saying that "" is invalid, and the load balancer s3 prefix must contain only a-zA-Z numbers and hyphens

**Comment by kishorj** [comment]
investigate this issue further.
