### ISSUE TITLE
[Feature Request] Add the option to specify a load balancer name

### ISSUE THREAD

**Issue by moosahmed** [kubernetes-sigs/aws-load-balancer-controller#1483]
Similar to Issue #360 

What is the annotation to specify the alb name?

**Comment by kishorj** [comment]
We do not support this feature yet. 
kind /feature

**Comment by M00nF1sh** [comment]
we'll add support for this after our first v2.0.0 release. Should be fairly easy to support it.

**Comment by moosahmed** [comment]
Thanks,

@M00nF1sh, no rush, just wondering when you are targeting v2.0.0 release?

**Comment by lexore** [comment]
Hello! I just want to say that version 2.0.0. is out and we can continue discuss this feature :-)

**Comment by M00nF1sh** [comment]
Hi, we'll add support to use existing LB and also this override LB name.

**Comment by vdahmane** [comment]
Hello, do you have ETA for this feature?

**Comment by LevonBecker** [comment]
How about now?  We're on v2.1.3... This feature is important to us for chargeback of stacks etc. Plus it makes easy to filter ALBs for a specific stack etc. 

Thanks in advance!

**Comment by kishorj** [comment]
/reopen
need to support for ingress as well

**Comment by pcolazurdo** [comment]
Will this feature allow to reuse existing NLBs? This is important to avoid having to recreate multiple Private Link configuration if for any reason the LoadBalancer has to be removed. Allowing the Controller to manage an existing NLB allows (which is connected to a Private Link) allow us to replace the service without having to ask the receiving end to recreate all the Private Endpoints setups

**Comment by kishorj** [comment]
@pcolazurdo, this feature is for specifying a custom load balancer name via annotation.

#1573 is the one for reusing existing LB.
