### ISSUE TITLE
Is AWS Global Accelerator supported?

### ISSUE THREAD

**Issue by solidaeon** [kubernetes-sigs/aws-load-balancer-controller#1488]
We're trying to have attach a static ip in our ALB.  AWS advised us to use AWS Global Accelerator.  Is this feature supported?

**Comment by M00nF1sh** [comment]
Hi, it's not supported by this controller for now.
You need to manually create GlobalAccelerator and configure the ALB provisioned by this controller as it's backend

**Comment by M00nF1sh** [comment]
we'll tracking globalLB support in roadmap: https://github.com/kubernetes-sigs/aws-load-balancer-controller/projects/5#card-48202903

closing this
