### ISSUE TITLE
Failed to build LoadBalancer configuration due to unable to fetch subnets.

### ISSUE THREAD

**Issue by smuramshetty** [kubernetes-sigs/aws-load-balancer-controller#1489]
kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller"

Am unable to get over this issue, any pointers please?

**Comment by smuramshetty** [comment]
I have the subnets tagged by `eksctl` 

article reference [awsdocs](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html)

**Comment by M00nF1sh** [comment]
`NoCredentialProviders: no valid providers in chain` you didn't setup aws permissions properly.

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by kishorj** [comment]
Feel free to reopen this if you still encounter issues with the permissions.
