### ISSUE TITLE
ALB ingress can't deploy on outpost 

### ISSUE THREAD

**Issue by brylex418** [kubernetes-sigs/aws-load-balancer-controller#1511]
ALB creation fails when using an outpost subnet. 

`
1015 23:21:32.485817       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet with at least 8 free IP Addresses for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/brylex': ['shared' or 'owned'] and 'kubernetes.io/role/elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[\"subnet-0dcffec1fcfc48382\"]'"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}
`
ALB creation detects my correctly tagged outpost subnet, however fails to proceed with ALB creation because check exists to qualify two subnets.
ALB on outpost only uses 1 subnet unlike the region which uses two.

**Comment by M00nF1sh** [comment]
i'll try to setup a outpost environment to resolve this post our initial v2.0.0 :D

**Comment by brylex418** [comment]
ping me internally if you need access to an outpost

**Comment by brylex418** [comment]
Closing
This is resolved with 2.0.1 release.
