### ISSUE TITLE
[Feature request] CRD based configuration via IngressClass parameters

### ISSUE THREAD

**Issue by RichiCoder1** [kubernetes-sigs/aws-load-balancer-controller#1515]
With the current setup of ALB, and short of creating a whole new CRD, a Service/Ingress with a lot of interesting rules applied to it is at significant risk of having a very noise and difficult to grok set of annotations. 

It would be great if some, if not all, of the available configuration for Service/Ingress could be specified in a ConfigMap or other resource.

**Comment by M00nF1sh** [comment]
@RichiCoder1 
It's already planed. We'll support setting these fields via the IngressClass API. 
Basically the IngressClass's parameter will become the configurations.

So you create single IngressClass hold these LB settings, and set Ingress.spec.ingressClassName.
Also, IngressClass will integrate nicely with our IngressGroup feature as well. like 
If groupName is specified as IngressClass parameter, then all Ingress belong to that class will share a single ALB.
If groupName isn't specified as IngressClass parameter, then all Ingress belong to that class continue to use standalone ALB.

Will it suit your need?
Also, what's your opinion on use configMap as configuration vs use a dedicated CRD for configuration?

BTW, we won't support IngressClass in the first v2.0.0 release, but will add support for it in later versions.

**Comment by RichiCoder1** [comment]
> It's already planed. We'll support setting these fields via the IngressClass API(available in kubernetes >=1.18)
Basically the IngressClass's parameter will become the configurations.

Interesting! That'd work too.

> Also, what's your opinion on use configMap as configuration vs use a dedicated CRD for configuration?

No strong opinion tbh, whatever makes the most sense for ya'll. A dedicated CRD a lot of sense, but in theory be more work to both manage and install.

**Comment by kishorj** [comment]
/kind feature
Post v 2.0 GA

**Comment by M00nF1sh** [comment]
we'll track the support for this in our roadmap: https://github.com/kubernetes-sigs/aws-load-balancer-controller/projects/5#card-48202777

closing this

**Comment by kishorj** [comment]
feature available in v2.2.0
