### ISSUE TITLE
kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile LB managed SecurityGroup:

### ISSUE THREAD

**Issue by sreejith421** [kubernetes-sigs/aws-load-balancer-controller#1519]
Im facing this issue very frequently . I f i update the ingress it will not reflecting and showing the below error log 

kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile LB managed SecurityGroup: failed to reconcile managed LoadBalancer securityGroup: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-west-2.amazonaws.com/\": dial tcp: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"

caused by: Post "https://sts.us-west-2.amazonaws.com/": dial tcp: i/o timeout
E1019 06:21:53.308913       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile LB managed SecurityGroup: failed to reconcile managed LoadBalancer securityGroup: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-west-2.amazonaws.com/\": dial tcp: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"dev","Name":"cus"}

E1019 06:28:00.095479       1 request_pagination.go:107] Failed request: ec2/DescribeSecurityGroups, Payload: {  Filters: [{      Name: "vpc-id",      Values: ["vpc-0332"]    },{      Name: "group-name",      Values: ["97-dev"]    }]}, Error: WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.us-west-2.amazonaws.com/": dial tcp: i/o timeout
E1019 06:28:00.095599       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile LB managed SecurityGroup: failed to reconcile managed LoadBalancer securityGroup: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-west-2.amazonaws.com/\": dial tcp: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"dev","Name":

Aws ingress controller Alb version : v1.1.9
Role using oidc with Required access 
Eks version: 1.15
ALB: Internal : ALB 
subnets: Private(Nat with egress enabled internet connectivity there)

**Comment by sreejith421** [comment]
Solved the issue by adding below dns entry in alb-ingress-controller deployment file and everything started working fine . anybody here faced the same issue ? is there any alternative better solution to fix this rather than using the google dns ?
dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4

**Comment by kishorj** [comment]
What does the default DNS configuration look like in your cluster? Also what is the DNS resolution path for the pods? Pod -> CoreDNS > Upstream DNS?

/kind need-investigation

**Comment by sreejith421** [comment]
Coredns Version: coredns:v1.6.6
before the issue dnspolicy of pod was ClusterFirst then changed to google dns. Verified coredns its all pointing to correct internal coredns ip and pod dns server also used the coredns server early .
