### ISSUE TITLE
Feature request: Shared NLB across multiple Services

### ISSUE THREAD

**Issue by khacminh** [kubernetes-sigs/aws-load-balancer-controller#1545]
- With NLB, I can add multiple listeners on multiple ports with multiple protocols, and multiple TLS certs
- The version 2 released with shared ALB between ingresses by IngressGroup and service with NLB IP mode. However, there is no way to share the same NLB between multiple services (or maybe I don't know, please correct me).

Therefore, I open this issue to request the feature to share the NLB between the services.

**Comment by M00nF1sh** [comment]
@khacminh 
I don't think we should do this as NLB is different than ALB(which can do L7 based routing).

A single Service closely maps to a single NLB.

**Comment by M00nF1sh** [comment]
closing this, but feel free to reopen if we have further thoughts or general use cases 😄

**Comment by khacminh** [comment]
@M00nF1sh 

with NLB, we can open multiple ports for multiple services. For example, we have 3 services that need to use the NLB to publish the connections to the internet:

- Service A running on port 1000
- Service B running on ports 1100 and 1101
- Service C running on port 1200

With the current approach of the controllers, 3 ALBs must be created. In this case, a workaround can be:
- Change the services to headless services
- Create a nginx deployment that listen on ports 1000, 1100, 1101, 1200, and route the traffic to the corresponding services
- Create a NLB nginx service

This workaround has some limits:
- only 1 TLS certs can be used
- only 1 protocol can be used

The point is, why the aws-load-balancer-controller have to limit down the ability of the ALB?

**Comment by tmetodie** [comment]
Hello, everyone! I totally agree with @khacminh as we can reuse the NLB by opening different ports per service and therefore have separate listeners per port. Would be really great if we can have this. Thanks in advance!

**Comment by zac-nixon** [comment]
With Gateway API support for NLB this is now possible. 
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.13.3
