### ISSUE TITLE
auth-idp-oidc annotation causing Throttling due to continuous updates

### ISSUE THREAD

**Issue by Mr-Howard-Roark** [kubernetes-sigs/aws-load-balancer-controller#1550]
We are using the `alb.ingress.kubernetes.io/auth-idp-oidc annotation`.  As part of it, a SecretName is included.  In the ALB Ingress Controller logs we noticed that any Ingresses that utilize this annotation are being continuously modified even though nothing changes.  It is severe to the point where our account is throttled for hitting the ec2 Load Balancer API so many times.  I mention the SecretName because maybe it is extrapolating its value over and over again to see if it changed?

Please let me know if you require other information to reproduce this yourself.  You should be able to reproduce it by just including these annotations:
`alb.ingress.kubernetes.io/auth-idp-oidc`
`alb.ingress.kubernetes.io/auth-type: oidc`
`alb.ingress.kubernetes.io/auth-scope: openid profile`
`alb.ingress.kubernetes.io/auth-session-timeout: "43200"`

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
Hi, I believe u are using the old controller version, which triggers the reconcile for every pod events. (and it always modifies OIDC since we don't know whether OIDCSecret is updated in aws or not).

Please try out our new v2.0.0 version, where only Ingress/Service/Secret change will trigger ingress reconciles.

**Comment by Mr-Howard-Roark** [comment]
Ok thanks for your response.  We are using v1.1.8 on Kubernetes version 1.16.  We will try using v2.0.0 and see if the throttling issue due to continuous modifications is mitigated.

**Comment by M00nF1sh** [comment]
sure :D i'll close this issue as v2.0.0 is designed to solve this and it's released. feel free to reopen if v2.0.0 didn't help.

**Comment by Mr-Howard-Roark** [comment]
@M00nF1sh is version 2.0.0 compatible with EKS 1.16?  I am seeing an error: "unable to create controller", "controller": "TargetGroupBinding","error":"no matches for kind \"TargetGroupBinding\" in version "\elbv2.k8s.aws.v1beta1\"

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
Yes, you should follow the migration guide. it's a completely new version which requires webhooks and CRDs.

**Comment by Mr-Howard-Roark** [comment]
@M00nF1sh  we are still running into the throttling issue after switching to the aws-load-balancer-controller.  Since we are part of Enterprise Support, we are interacting regarding the issue there and I sent a bunch of info last night for your reference.  Is it better to interact via that case or via this github issue?

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
either works, but we can guarantee timely response when using the support case. 
Do you change the Ingress/Service object frequently? under `aws-load-balancer-controller`, only Ingress/Service changes triggers these describe APIs calls. 
BTW, what's the AWS API you got throttled, and do you have the aws-api-requests-total metrics available?

**Comment by Mr-Howard-Roark** [comment]
@M00nF1sh I attached the aws-api-requests-total metrics to the case last night.  Let me know if you need to see anything else.

The ingress does change sometimes.  We've been using the ingress merge controller for close to two years now successfully.  So, it merges other ingresses into the ingress that the aws-load-balancer-controller manages.  But, it's not like teams are continuously adding webapps.  I would expect a new ingress to be added that is subsequently merged to be not even a daily occurrence.

The other point I guess that could be worth mentioning is our teams add app-specific ingress annotations to their services since those take precedence.  So, the main ingress has the core annotations we require, and then teams can add their own custom ones to their services.  Subsequently the one ingress managed by the aws-load-balancer-controller applies those custom annotations.

I don't want this to be overly wordy or sidetrack you -- I don't see why the Ingress Merge Controller would be the culprit for this since it's not like it's continuously merging changes into the primary Ingress that the aws-load-balancer-controller manages.  But, just in case it gives you any ideas I wanted to share it.

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
seems the ingress is keep reconciles. would you help add '--log-level=debug' so we can know what triggers it

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
Took me a long time to figure this out...(too many logs).
Your `system:serviceaccount:cattle-system:cattle` component is keep adding `field.cattle.io/publicEndpoints` annotation, while the IngressMerge component is keep removing that annotation.

Since there are annotation changes, it will endlessly trigger ingress reconcile.. 
I think you can fix the IngressMerge behavior, or switch to use our IngressGroup feature.

**Comment by Mr-Howard-Roark** [comment]
Wow thanks-- that is a really good catch!  That annotation is added by Rancher.  It looks like Rancher continuously modifies our ingresses with that annotation.  I am not sure why the Merge Ingress Controller would remove it and will need to try to understand that better.

Two questions:
- Do you know what `describe` api calls we should control via the `aws-api-throttle` config option to combat this in the meantime? ie- what specific `describe` api calls is the aws-load-balancer-controller making over and over again when it sees the ingress change?
- Does it make sense for you to add as a feature the ability to ignore specific annotations?  ie- if xyz annotation changes and nothing else changes, don't do a describe

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
1. I think you can limit the `DescribeTargetGroups` 😄 (that should be able to block other apis as well, since other reconcile depends on it).

2. yes, we indeed can do an optimization to check whether changed Ingress annotation key have our prefix. (should be a simple change, i can add it in later versions. PR welcome too 😄 )
   However, this issue ideally should be fixed since it's like change every ingress per second, and consumes control-plane resources.

**Comment by Mr-Howard-Roark** [comment]
Ok thanks for your help.  All of this is very interesting.  Especially what you mention regarding control-plane resources being consumed .  I will work on fixing it from here and close this issue.  Maybe I'll try to do the PR, but `Go` is one of my many weaknesses
