### ISSUE TITLE
[V2] Provided AWS iam policy have error

### ISSUE THREAD

**Issue by guan840912** [kubernetes-sigs/aws-load-balancer-controller#1552]
If use resource `"arn:aws:elasticloadbalancing:*:*:targetgroup/*" ` in iam policy , you will found some error like `Unrecognized resource types` .
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/005069dc18a6a2ce31f8c9315b4ae85df6b45372/docs/install/iam_policy.json#L142
![截圖 2020-10-25 上午9 13 37](https://user-images.githubusercontent.com/46012524/97097484-ddb86500-16ab-11eb-8ad5-472012ed3cdc.png)

see https://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticloadbalancingv2.html#elasticloadbalancingv2-targetgroup

change `"arn:aws:elasticloadbalancing:*:*:targetgroup/*" `  to `"arn:aws:elasticloadbalancing:*:*:targetgroup*" `
to fix error.
like 
![截圖 2020-10-25 上午10 24 34](https://user-images.githubusercontent.com/46012524/97097521-50c1db80-16ac-11eb-8b4a-589e52b35f00.png)
![截圖 2020-10-25 上午10 24 22](https://user-images.githubusercontent.com/46012524/97097522-528b9f00-16ac-11eb-9b91-9d83a38723dc.png)

I can create PR for this .😊

**Comment by M00nF1sh** [comment]
@guan840912 
Thanks for let us know.  
I assume the current IAM roles works as expected but just this UX issue right? (we tested these permissions works).
Needs to confirm with iam team whether it should be "/*" or "*" for this UX
