### ISSUE TITLE
Are internal LBs anti-pattern for internal k8s services?

### ISSUE THREAD

**Issue by adamkgray** [kubernetes-sigs/aws-load-balancer-controller#1562]
I am little confused about the best-practices/use case of aws LBs with k8s.

In a world without kubernetes i would place all my internal services behind internal load balancers. So when creating my cluster i did the same, and all services running on the cluster call eachother through an internal LB, deployed with this controller. But this increases latency drastically by 2-3 times. Not to mention that it is probably anti pattern, and not a cloud agnostic approach.

With that being said, is it safe to say that the best use case of the LB ingress controller is ONLY to expose services running on k8s to other services outside of k8s? Otherwise services should just communicate using k8s native methods?

I am interested to know if the project has an official stance on this. If it is anti pattern i feel there should be something in the documentation advising against it, and therefor clarifying the use case

**Comment by M00nF1sh** [comment]
@adamkgray 
In short, you don't need to use the internal LB if you don't rely on its functionality 😄 .
e.g. 
1. If you have an another in-vpc service(but out-of-k8s), and wants to talk to your service within k8s safely, you'll use these internal LBs.
2. You want to use internal ALB to do L7 load balancing/logging/monitoring/etc.

**Comment by adamkgray** [comment]
@M00nF1sh thanks!
I know it's sort of a silly question. Obviously, one should not use it if they don't need it XD

Out of interest, are there any resources which compare kubernetes's native ability to scale to handle things like high throughput, large requests, etc. to an AWS LB? Is that even a valid question? There is always other options like using istio internally for a service mesh, but I would be interested to know how k8s compares natively.

In any case, I consider my question sufficiently answered. Feel free to close the issue, thanks!

**Comment by M00nF1sh** [comment]
@adamkgray 
This isn't resources i'm aware of that compares the scalability of these solutions.  
You should be able to do load test to handle test it out.
For other in-cluster  solutions, the scalability should be bound to your machine count and size.


Feel free to reopen if you have further questions.
