### ISSUE TITLE
[v2] improve the log messages

### ISSUE THREAD

**Issue by postmaxin** [kubernetes-sigs/aws-load-balancer-controller#1565]
Seeing a lot of stuff like this;

```
{"level":"error","ts":1603747129.250157,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"rex-ingress-external","namespace":"","error":"cannot find at least two subnets from different Availability Zones, discovered subnetIDs: []"}
{"level":"error","ts":1603747155.3905587,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"rex-ingress-dev","namespace":"","error":"Service \"qualia-sync-cron-service\" not found"}
```

**Comment by M00nF1sh** [comment]
@postmaxin 
It's expected. I assume you are using `rex-ingress-external` and `rex-ingress-dev` as IngressGroups. these are encoded as a types.NamespacedName without namespace.

Do you need help on the actual error? 
1. the first one should be either u didn't tag the subnets correctly or u didn't set the '--cluster-name` flag to controller correctly
2. the second one is the service referenced by one Ingress in IngressGroup `rex-ingress-dev` is not found

**Comment by postmaxin** [comment]
So for #1, that totally makes sense, and I'm fine.

For #2 -- it was looking for the service *in a namespace*, correct? How do we tell what namespace it was looking in?

**Comment by M00nF1sh** [comment]
I agree we should improve the logs for #2. Before that, you can check all ingresses with group.name rex-ingress-dev :D.

**Comment by postmaxin** [comment]
Oh boy! :D 

```
$ kubectl get ing -A | grep rex-ingress-dev | wc -l
   158
```

Ok, I'll do that for now

**Comment by M00nF1sh** [comment]
@postmaxin 
We'll track the fix in v2.0.1: https://github.com/kubernetes-sigs/aws-load-balancer-controller/projects/3#card-48201295

closing this issue.

**Comment by weberc2-tempus** [comment]
> the first one should be either u didn't tag the subnets correctly or u didn't set the '--cluster-name` flag to controller correctly

How can we debug the `--cluster-name` flag setting?

**Comment by M00nF1sh** [comment]
@weberc2-tempus the `--cluster-name` setting is a flag to the controller, we currently didn't print it out in the logs. maybe in future versions, we can echo them.
