### ISSUE TITLE
[v2] Certificate ARN merge behaviour for groups broken by certificate discovery logic

### ISSUE THREAD

**Issue by itskingori** [kubernetes-sigs/aws-load-balancer-controller#1567]
**Short Version**

If someone is using groups ... and a member of the group has `certificate-arn` specified, I don't see why we should attempt to discover certificates for those members who **don't have** `certificate-arn` specified. To be fair, I'm fairly new to ALBs and it's likely there's something I'm missing.

**Long Version**

Based on the [docs on annotations](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/ingress/annotations/) it's expected that the merge behaviour on the `alb.ingress.kubernetes.io/certificate-arn` annotation is `Merge`. However, I think [certificate discovery](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/ingress/cert_discovery/) is overriding group logic. For more context, this is what I have:

1. More than one matching certificate in ACM.
2. An ingress resource (say `ingress-example-1`) that has `alb.ingress.kubernetes.io/certificate-arn` set explicitly and with `alb.ingress.kubernetes.io/group.name` set.
3. Another ingress resource (say `ingress-example-2`) where `alb.ingress.kubernetes.io/certificate-arn` **is not set** with but **with matching group name**.

I'd expect `ingress-example-2` to pick the certificate of `ingress-example-1` since it's value is empty but instead I get this error ...

```json
{
  "level": "error",
  "ts": 1603782857.9200053,
  "logger": "controller",
  "msg": "Reconciler error",
  "controller": "ingress",
  "name": "alb-external",
  "namespace": "",
  "error": "multiple certificate found for host: [REDACTED], certARNs: [arn:aws:acm:us-east-1:[REDACTED]:certificate/[REDACTED] arn:aws:acm:us-east-1:[REDACTED]:certificate/[REDACTED]]"
}
```

Seems this is where we have that logic and it doesn't seem like it accounts for groups ...

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/efe7e71d270e57a70d0c17587ee89237e055ee4d/pkg/ingress/cert_discovery.go#L67-L85

What I am trying to avoid is having to set `alb.ingress.kubernetes.io/certificate-arn` on all my ingress resources ... which is useful because it makes certificate rotation easy. Also when rotating certificates it's likely to recreate the certificate with one that matches the domain ... so we should expect someone to possibly have two matching certificates. Current error-out behaviour behaviour makes sense in the non-grouping context.

---

Related to https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1458 which introduced the certificate discovery issue cc: @M00nF1sh.

**Comment by M00nF1sh** [comment]
@itskingori 
This is the designed behavior. 
The intention is to make the each Ingress control their own listener & certificates and stay valid.

**Comment by itskingori** [comment]
> This is the designed behavior.

Alright, noted. I guess what I was trying to do is figure out how I can specify one certificate that would be the default using the group feature. Some more context before I close the issue, on this ...

> The intention is to make the each Ingress control their own listener & certificates and stay valid.

We have over 30 Ingress resources that we want to have in the same group so that all those services might be behind the same ALB. With a wildcard cert on ACM that covers all the domains of those certs, rotating the certificate becomes more involving since you have to update all the different ingress resources (in our case deploy those apps across on environments or write a kubectl patch script).

I'm moving from the official kubernetes `nginx-ingress` controller that used the classic-ELB and just getting a hang of how different ALBs are 😅 ... each listener seems to be like a classic-ELB in itself.

**Comment by zacblazic** [comment]
> This is the designed behavior.
> The intention is to make the each Ingress control their own listener & certificates and stay valid.

Would there be an issue if we allowed `ingress-example-2` with a to inherit the annotations from `ingress-example-1` where they both share a `alb.ingress.kubernetes.io/group.name`?

I don't see this behaviour impacting anything, at least with `alb.ingress.kubernetes.io/certificate-arn`. If there are annotations that absolutely cannot be inherited from an existing ingress with the same group you can force those to be specified. 

I'd be similar to how merging works I presume.

**Comment by M00nF1sh** [comment]
@zacblazic @itskingori 
It won't impact anything and will be correctly merged. e.g. If we cannot inferrer any tls certs from `ingress-example-2`, and `ingress-example-1` have configured a certs for the TLS ports, then it works as well. The controller only requires "some" TLS certificates specified per TLS port.
However, for this case, it's we encountered the error when inferrer TLS certs for an ingress within group. (we have to enable inferrer per Ingress as we want to make sure it have the correct TLS certs based on it's hostname). And for this case, it's multiple certs matched the host name and there is no explicit override via annotation specified.
