### ISSUE TITLE
Sharing an ALB between multiple clusters

### ISSUE THREAD

**Issue by victornoel** [kubernetes-sigs/aws-load-balancer-controller#1568]
Hi,

One question that I cannot answer while reading the documentation is if it is possible to have multiple EKS clusters, each with their instance of the aws-load-balancer-controller, but sharing an ALB.

The use case would be to allow for switching apps between clusters in a seamless way from the LB and DNS point of view.

**Comment by M00nF1sh** [comment]
@victornoel 
We cannot support sharing it across multiple cluster. Since the controller runs inside a single cluster, it doesn't have visibility into other clusters.

You should use the TargetGroupBinding CRD instead for cross-cluster use case.

**Comment by victornoel** [comment]
@M00nF1sh I will investigate a bit more, but it looks like this is exactly what I was looking for, thank you :)

I will close this issue then!
