### ISSUE TITLE
[Feature Request] TargetGroupBinding can't bind pod ip to another vpc's  targetgroup

### ISSUE THREAD

**Issue by yueliang9527** [kubernetes-sigs/aws-load-balancer-controller#1569]
**Short Version**
I create one  TargetGroupBinding resource , want to binding pod ip to a targetGroup (type is ip) which belong to another vpc, but aws-load-balancer-controller report error with **"ValidationError: The Availability Zone for IP address '192.168.11.189' must be 'all' for Application Load Balancer target groups, when not within the VPC"**.

Full error message: "{"level":"error","ts":1603805204.1610796,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"php-apache-1","namespace":"default","error":"ValidationError: The Availability Zone for IP address '192.168.11.189' must be 'all' for Application Load Balancer target groups, when not within the VPC\n\tstatus code: 400, request id"

**Long Version**

1. Create a targetgroup which belong to VPC A , Target type is ip.
1. Create a TargetGroupBinding, spec.targetType is also ip, spec.targetGroupARN is the targetgroup created in step one.
1. Get the error.

There have another similar bug reported but had been fixed :https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/783. So i think this error maybe triggered by a bug.

**Comment by 0xlen** [comment]
My understanding about this issue is due to it seems like the controller doesn't add the `AvailabilityZone` parameter when binding other target group not in the same VPC. Request might be looked like:

```
"eventName": "RegisterTargets",
"awsRegion": "us-west-2",
"userAgent": "elbv2.k8s.aws/v2.0.0-dirty aws-sdk-go/1.35.4 (go1.15; linux; amd64)",
"errorCode": "ValidationException",
"errorMessage": "The Availability Zone for IP address '10.1.1.1' must be 'all' for Application Load Balancer target groups, when not within the VPC",
"requestParameters": {
    "targets": [
        {
            "id": "10.1.1.1",
            "port": 1234
        }
    ],
   ...
}
``` 

In this case, the `all` should be included due to [1]:

> If the target type is ip and the IP address is in a subnet of the VPC for the target group, the Availability Zone is automatically detected and this parameter is optional. If the IP address is outside the VPC, this parameter is required.

> With an Application Load Balancer, if the target type is ip and the IP address is outside the VPC for the target group, the only supported value is all.

I did not see the controller's documentation mentioning this scenario(maybe I missed it), it might need to verify and see if this use case is in the scope.

[1] TargetDescription - Contents - https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetDescription.html#API_TargetDescription_Contents

**Comment by M00nF1sh** [comment]
Hi,
bind to another vpc's TargetGroups is not a supported use case for TargetGroupBinding.
Would you help share your use case so we can evaluate whether we should support it or not?

**Comment by yueliang9527** [comment]
@M00nF1sh Thanks for you reply.

We already have **mutiple EKS cluster** to run individual application of our operator platform, those EKS cluster **belong to    different VPCs**.
We want to control all of the ingress centralized, we want to leverage this targetgroupbinding feature to bind services which from different eks cluster to the union external ALB, this is the most simplest way.

If this way can't work, every EKS cluster will have owned ingress, and there must be another exteranl ALB work as Unified ingess, but those two  ALB must be connected by middle niginx, this is too complex.

**Comment by M00nF1sh** [comment]
@yueliang9527 
Is these VPCs connected by vpc peering? If not, the alb cannot route traffic to endpoints in another vpc

**Comment by yueliang9527** [comment]
@M00nF1sh Sure, they are connected by VPC peering.
But I think this problem is not related to VPC network connect, Becuase it was occured when I create K8S service, they have not start commnunication through VPC network.

As you mentioned at https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1569#issuecomment-717415397, It should be a feature needed to add.

**Comment by rich** [comment]
@M00nF1sh I just ran into this issue and it's a blocker for us. This is our use case.

We have an old monolithic application running in one VPC and new EKS/K8S based services running in another VPC. The VPCs are peered. I was planning on using a TargetGroupBinding to support splitting some traffic hitting an ALB between an endpoint in the old monolith and a new service running on EKS.

Seems like this would be a common approach for companies like mine that are working through a transition.

**Comment by rich** [comment]
@M00nF1sh Yes, ALB weighted load balancing was the plan. We would be managing all of the ALB pieces with Terraform and depending on the controller to keep the Terraform managed TargetGroup up to date with current targets.

**Comment by Igor96Poli** [comment]
Hi,
it should be great to have that features. I have a similar environment, with a VPC-A, which is public and a VPC-B that is private. On the VPC-A I have a ALB with IP target group, on VPC-B I have an EKS cluster and I spend my last week trying to register pods without success. 
Now I see why it happened!
I hope that feature will be taken into account soon as possible.

**Comment by andr3adc** [comment]
> Hi,
> it should be great to have that features. I have a similar environment, with a VPC-A, which is public and a VPC-B that is private. On the VPC-A I have a ALB with IP target group, on VPC-B I have an EKS cluster and I spend my last week trying to register pods without success.
> Now I see why it happened!
> I hope that feature will be taken into account soon as possible.

It would be great!

**Comment by stimmerman** [comment]
Hi,

Just wanted to add, that we have the same use-case. We currently have a central ingress vpc/egress vpc setup with AWS Network Firewall to centralise the security. The EKS cluster is in it's own VPC and would need to provision the ALB's that are in the Ingress VPC. If we can help with anything, like testing or writing more about the use-case please let me know!

**Comment by acjohnson** [comment]
I ran in to this as well today and need to be able to update a target group with IPs from a dedicated VPC for our EKS cluster.

**Comment by acjohnson** [comment]
This worked for me for the time being: https://github.com/acjohnson/aws-load-balancer-controller/commit/9b55e701a70f1f011b117defaf6b0cd7ea7e6ee0

**Comment by jdevine-avtx** [comment]
+1 running into this too. Any update on when it will be fixed in the man branch @M00nF1sh ?

**Comment by shoekstra** [comment]
Hi!

We recently ran into this (with @stimmerman) and I created PR to fix it. For those facing the issue and waiting for a fix to be merged you can do one of the following:

1. use the `shoekstra/aws-alb-ingress-controller:v2.1.2-patch` image I built based off [this commit](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1862/commits/e39d35401362e612217bf18b4d8c6c950e848b37)
2. if you'd prefer to build it yourself: checkout that commit and run `docker buildx build . --tag <image name/tag, e.g. "shoekstra/aws-alb-ingress-controller:v2.1.2-patch"> --push --platform linux/amd64`. I sometimes had issues building the image, if you have the same you can remove `GOPROXY=direct` from [line 10 in the `Dockerfile`](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/Dockerfile#L10) which seemed to fix it for me.

Hope that helps!

**Comment by cmd-werner** [comment]
+1 running into this too.

**Comment by swapnildahiphale** [comment]
Ran into this issue, the patched image based on https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1862/commits/e39d35401362e612217bf18b4d8c6c950e848b37 didn't work for Kubernetes 1.22
Here is new version I built:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/404c6db483b21baddccbae3ee0f17c0ae5844e2b
Docker image
`swapnildahiphale/aws-load-balancer-controller:2.4.7-patch`
Also here is docker image patched based on v2.5.1 for quick test
`swapnildahiphale/aws-load-balancer-controller:2.5.1-patch`

**Comment by acjohnson** [comment]
> Here is new version I built:

@swapnildahiphale  You shouldn't need to do that, this issue has been solved by https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1862 and merged upstream as of aws-load-balancer-controller `v2.3.1`

**Comment by swapnildahiphale** [comment]
In my use case I have 2 VPCs 
1. ALB VPC
2. EKS VPC

The upstream version worked only if I provide `vpcId` of ALB VPC while installation of aws-load-balancer-controller via helm.

However the issue that I ran into is if I create an kubernetes service with `Type: Loadbalancer` in EKS, it goes into pending state. Following are aws-load-balancer-controller in this case

![image](https://user-images.githubusercontent.com/13692814/234377780-6324c91a-1ade-45ca-822b-394597f2dbfa.png)
