### ISSUE TITLE
[Feature Request] Support Target Group Attributes for NLB IP Mode

### ISSUE THREAD

**Issue by arhea** [kubernetes-sigs/aws-load-balancer-controller#1570]
The Ingress configuration supports the `alb.ingress.kubernetes.io/target-group-attributes` annotation which enables configuring `stickiness.enabled`, `stickiness.type`,  `deregistration_delay.timeout_seconds`, `load_balancing.algorithm.type`, `slow_start.duration_seconds`, `stickiness.lb_cookie.duration_seconds`, and `proxy_protocol_v2.enabled`. 

Some of these features are also available on the NLB such as configuring `stickiness.enabled`, `stickiness.type`,  `deregistration_delay.timeout_seconds`, and `proxy_protocol_v2.enabled`. It would be helpful to have an `service.beta.kubernetes.io/target-group-attributes` annotation for configuring these options on NLB IP based services.

There is a workaround to statically create the NLB and Target Group outside of Kubernetes then use the `TargetGroupBinding` CRD to link the Kubernetes service to the Target Group.

Key use cases include:
- sticky sessions for things like WebSocket based connections to pods
- sticky sessions for in memory session state

**Comment by kishorj** [comment]
proxy_protocol_v2.enabled is already supported
For other attributes, we will add support for configuration via service annotations.
/kind feature

**Comment by M00nF1sh** [comment]
Hi, TargetGroupsAttributes support is already released in v2.1.0. closing this
