### ISSUE TITLE
[Feature Request ] Features for AWS ALB / NLB

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes-sigs/aws-load-balancer-controller#1571]
Track features that need support from AWS ALB / NLB service before we can support them in this controller 😄 
## ALB
- [ ] Manipulate HTTP Request
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1268
- [ ] Manipulate HTTP Response
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1454
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1397
- [ ] Server-side retry
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1447
- [ ] Fix OIDC scope
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1344
- [ ] ALB support GZIP compression
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1132 
- [ ] ALB support regex path
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1760
- [ ] ALB support HTTP healthcheck for GRPC backends
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1883
- [ ] ALB support for mutual TLS and passing client cert
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1973
- [ ] ALB support for rate limit
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2722
- [ ] 308 redirection
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2654
## NLB
- [ ] NLB support for SecurityGroups

**Comment by ffoysal** [comment]
any ETA on such a important feature?

**Comment by yuliyantsvetkov** [comment]
Any ETA here, guys ? Its the 21st century !

**Comment by M00nF1sh** [comment]
@ffoysal @yuliyantsvetkov the latest ETA i got from ELB team for request manipulation is Q2 2020.

**Comment by kcrawley-supernatural** [comment]
@M00nF1sh is there anywhere we can track the upstream issues on the AWS side for these features?

**Comment by hyerim-gn** [comment]
> @ffoysal @yuliyantsvetkov the latest ETA i got from ELB team for request manipulation is Q2 2022.

Are there any updates?

**Comment by anthonyliriano** [comment]
Is  the HTTP Request Header manipulation still being considered?

**Comment by neerajjain92** [comment]
Any update on this ?

**Comment by doctornkz** [comment]
Waiting Rate Limit feature for ALB, WAF too slow to help out with spike-loads.

**Comment by futurelm** [comment]
bro, it is Oct,  where is Q2 2022?

**Comment by dejwsz** [comment]
> bro, it is Oct, where is Q2 2022?

you know - they store so much data so relativistic time dilation appeared ;)

**Comment by or-navon** [comment]
Any progress with setting response headers?

**Comment by evyros** [comment]
Still waiting...

**Comment by nuwansa** [comment]
badly need this.....

**Comment by antonyfray** [comment]
![pulp-fiction-waiting](https://user-images.githubusercontent.com/15817659/202444014-b0e41381-fb31-461d-9542-e989a723757d.gif)

**Comment by johngmyers** [comment]
This is a tracking issue for features needed from an upstream project. Querying the status of those features here is less than productive. Such queries should be directed to the upstream project.

**Comment by antonyfray** [comment]
> This is a tracking issue for features needed from an upstream project. Querying the status of those features here is less than productive. Such queries should be directed to the upstream project.

Would you mind directing us to the upstream project in question please?

**Comment by johngmyers** [comment]
The upstream project would be AWS Elastic Load Balancing.

**Comment by edijsdrezovs** [comment]
> Is the HTTP Request Header manipulation still being considered?

Any ETA on this?

**Comment by DariusX** [comment]
As @johngmyers mentioned above, there really cannot be an ETA on this project, because this project uses features available on AWS ELB. If AWS ELB does not support a feature, then this project cannot do so either. 

I think the thing that folks who have experience with NGNIX style ingress do not realize that this is quite different. (I too had the same confusion when I first used this project.) With something like NGNIX, it is doing the routing of incoming requests. That is not how this project works. With this project, all the work of handling requests is being done by AWS ELB, not by the pod deployed by this project. The job of this project is to take the Ingress config as defined in EKS, and automatically spin up and configure AWS ELB.

So, when asking for a feature, the first question is: is this feature something that is in AWS ELB? In other words, is it possible to configure AWS ELB manually, to do whatever is being requested. If the answer is "yes", then this project can definitely create an automated way to configure that feature. But, if AWS ELB cannot be configured to do what's being requested, then this project can't do anything about it, because this project does not actually DO Ingress, it only CONFIGURES ingress using AWS ALB.

**Comment by acgs771126** [comment]
AWS NLB supported security group now, so when will aws-loadbalancer-controller can also support create NLB with sg by service? thanks.

**Comment by asychev** [comment]
@acgs771126 AWS NLB does not support SGs

**Comment by acgs771126** [comment]
Hi @asychev : 
You can login to your AWS web console and click the create NLB button, and then you will see the SecurityGroup block here.  
![image](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/43164653/5f7d6c99-644e-40f6-b9a8-9a3d757ac223)

**Comment by asychev** [comment]
@acgs771126 Checked two regions in US/EU, nothing like that available. Could you please provide link to the official documentation of this feature?

**Comment by asychev** [comment]
This is finally supported: https://aws.amazon.com/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/

**Comment by adrianmiron** [comment]
Any news on the set HTTP header feature ? It's a supported feature on the ALB side , so that shouldn't be the  blocker :)

Thanks!

**Comment by omidraha** [comment]
I have configured `aws load balancer controller` with Amazon `EKS`, and `Fluent bit` with `CloudWatch`.
How can I add HTTP headers like User Agent in the sent logs?

**Comment by omidraha** [comment]
I'm using AWS Load Balancer in EKS Kubernetes,
How can I enable mesh at https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/?
I added `"linkerd.io/inject": "enabled"` to the ingress controller, but it didn't make a difference.

**Comment by hughesadam87** [comment]
Vote - lost hours and hours to this, really makes AWS look bad

**Comment by stoltin** [comment]
AWS supports now Mutual TLS. Can this project implement that too?
https://aws.amazon.com/about-aws/whats-new/2023/11/application-load-balancer-authenticate-x509-certificate-based-identities/

**Comment by TemperingPick** [comment]
I noticed that ALB listener rules now support transforms, is this the required service enhancement?

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/rule-transforms.html

**Comment by adrianmiron** [comment]
I too would be interested in that feature
