### ISSUE TITLE
[Feature Request] expose LoadBalancer ARN via annotation

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes-sigs/aws-load-balancer-controller#1573]
We should expose LoadBalancer ARN via annotation to enable automation use case.

**Comment by seivan** [comment]
Yeah this is pretty important (for me) and would solve https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1116

Right now, there is no way to get access to the ALB after it has been created for further use, like getting its address and dealing with Route53.

**Comment by pcolazurdo** [comment]
This feature becomes important to avoid having to recreate multiple Private Link configuration if for any reason the LoadBalancer has to be removed. Allowing the Controller to manage an existing NLB allows (which, in this case, is connected to a Private Link) allow us to replace the service without having to ask the receiving end to recreate all the Private Endpoints setups

**Comment by kishorj** [comment]
Closing since there is a duplicate issue #2056.

**Comment by devkid** [comment]
@kishorj This is *not* a duplicate of #2056.

**Comment by kishorj** [comment]
@alfredkrohmer, thanks for pointing out.
/reopen

**Comment by ManuelMueller1st** [comment]
still required vor private link

**Comment by hitsub2** [comment]
we need this feature as the compliance requirement for internal usage.It will help us reduce the API Calls possible.

**Comment by hitsub2** [comment]
@M00nF1sh  could you help reopen this issue?

**Comment by hitsub2** [comment]
Any update on this?

**Comment by hitsub2** [comment]
@M00nF1sh Could you help reopen this issue?
