### ISSUE TITLE
[Feature Request] expose nodeSelector on targetGroupBindings, so users can optionally specify different nodes for different tgbs.

### ISSUE THREAD

**Issue by wlin-jin** [kubernetes-sigs/aws-load-balancer-controller#1575]
Do we have plans to develop this features?
  expose nodeSelector on targetGroupBindings, so users can optionally specify different nodes for different tgbs.
  https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/backend/endpoint_utils.go

**Comment by M00nF1sh** [comment]
@wlin-jin 
Yes, it's planed as it's a TODO 😄 
BTW, why would you prefer instance mode over IP mode?
