### ISSUE TITLE
[v2] Tag attempt fails while upgrading existing LB security group due to policy restriction

### ISSUE THREAD

**Issue by otterley** [kubernetes-sigs/aws-load-balancer-controller#1577]
After upgrading to the V2 controller, I saw the following errors in the controller log:

```
{"level":"info","ts":1603938504.0908365,"logger":"controllers.ingress","msg":"adding resource tags","resourceID":"sg-xxxxxxxxxxxx","change":{"elbv2.k8s.aws/cluster":"lab"}}
{"level":"error","ts":1603938504.1772304,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"stateful","namespace":"default","error":"UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: REDACTED\n\tstatus code: 403, request id: REDACTED"}
```

I've verified that I'm using the [policy document](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json) linked to from the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) located here. I validated that the correct IAM role was being used by the controller as well.

I decoded the authorization failure message and it appeared the `elbv2.k8s.aws/cluster` resource tag was not actually in the `ec2:CreateTags` API call context.

...

Later, I stumbled upon [this extra IAM policy](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy_v1_to_v2_additional.json) in the Git repository. I took a chance, and added it as an inline policy to the existing IAM role that I created with `eksctl` -- and everything worked fine. I never saw the error again.

So perhaps we have a documentation issue on our hands?

**Comment by kishorj** [comment]
The extra IAM policy is required if you were upgrading from AWS ALB ingress controller (v1) to v2. It is mentioned in the migration guide.

The EKS documentation did not provide the link to this migration guide. Our apologies for the confusion caused. We will fix the EKS documentation. Thanks for bringing it to our attention.

**Comment by evgpisarchik** [comment]
I resolved this issue by extending the Role "AWSLoadBalancerControllerIAMPolicy" from 
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
with adding permissions to add tags (and more) for whatever was mentioned in the errors I was getting.

At least this permissions were added:
ec2:CreateTags
elasticloadbalancing:AddTags
elasticloadbalancing:SetSecurityGroups
