### ISSUE TITLE
[v2] Error creating resource tag due to policy denial

### ISSUE THREAD

**Issue by otterley** [kubernetes-sigs/aws-load-balancer-controller#1578]
After upgrading to the V2 controller, I saw the following errors in the controller log:

```
{"level":"info","ts":1603938504.0908365,"logger":"controllers.ingress","msg":"adding resource tags","resourceID":"sg-xxxxxxxxxxxx","change":{"elbv2.k8s.aws/cluster":"lab"}}
{"level":"error","ts":1603938504.1772304,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"stateful","namespace":"default","error":"UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: REDACTED\n\tstatus code: 403, request id: REDACTED"}
```

I've verified that I'm using the [policy document](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json) linked to from the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) located here. I validated that the correct IAM role was being used by the controller as well.

I decoded the authorization failure message and it appeared the `elbv2.k8s.aws/cluster` resource tag was not actually in the `ec2:CreateTags` API call context.

...

Later, I stumbled upon [this extra IAM policy](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy_v1_to_v2_additional.json) in the Git repository. I took a chance, and added it as an inline policy to the existing IAM role that I created with `eksctl` -- and everything worked fine. I never saw the error again.

So perhaps we have a documentation issue on our hands?

**Comment by kishorj** [comment]
Thanks for bringing it to our attention, we will revise the docs.

**Comment by arms11** [comment]
Ran into the same this am. Working with our admin to resolve. Thanks for the information!
