### ISSUE TITLE
[v2] When creating IngressGroup load balancer, usual load balancers are created and work

### ISSUE THREAD

**Issue by arnikasky** [kubernetes-sigs/aws-load-balancer-controller#1583]
Hello!
Using:
region: us-east-1
external dns image version: bitnami/external-dns:0.7.1
 
Description:
When I create ingresses with annotations 'alb.ingress.kubernetes.io/group.name: test' and alb.ingress.kubernetes.io/group.order,  Load balancer k8s-test-xxxx шы is created, but when I run command "kubectl get ing", I see xxxx.us-east-1.elb.amazonaws.com associated with these ingresses in list.
What I am doing wrong?

Thank you for help!

**Comment by kishorj** [comment]
Could you share the ingress and service (the one referenced from the ingress) specs? Based on the lb name, it doesn't look like a ELBv2.

**Comment by arnikasky** [comment]
Hello @kishorj, sure!

I have these to ingress (on picture) with annotation alb.ingress.kubernetes.io/group.name: test':
[
<img width="1020" alt="Screenshot 2020-10-30 at 12 18 53" src="https://user-images.githubusercontent.com/8751017/97688422-29538000-1aab-11eb-9a72-6e17b28cdb05.png">
]

and I don't see using kubectl another ingress, but have it in AWS EC2 console:

k8s-test-83eb43558d-**********.us-east-1.elb.amazonaws.com

**Comment by kishorj** [comment]
do you have any other controllers handling the ingresses? Could you share the ingress manifest? Also if possible, please include the load balancer controller logs as well.

**Comment by M00nF1sh** [comment]
it looks to me you didn't uninstall the old aws-alb-ingress-controller

**Comment by arnikasky** [comment]
Hello @M00nF1sh and @kishorj, @M00nF1sh is right, I didn't update aws-alb-ingress-controller in other namespaces. I close this request, I'll open new issue, in case if updating another controllers don't help.
