### ISSUE TITLE
[v2] feature request: support ProtocolVersion on TargetGroups

### ISSUE THREAD

**Issue by backjo** [kubernetes-sigs/aws-load-balancer-controller#1586]
Support for gRPC and HTTP/2 between ALB and targets was just announced https://aws.amazon.com/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc 🎉 . 

It would be useful to have an annotation - perhaps `alb.ingress.kubernetes.io/backend-protocol-version` - that allows service /ingress objects to specify the backend version that they wish to use.

**Comment by M00nF1sh** [comment]
@backjo 
we are evaluating whether to use an annotation or leverage the appProtocol field in serviceSpec (available in k8s 1.18+). 
Do you have preferences?

**Comment by backjo** [comment]
@M00nF1sh I'm leaning towards annotation, so it would be useable on EKS today. We're running the latest 1.18 on EKS, and with appProtocol it wouldn't be useable until the January 1.19 release, since the `appProtocol` field is behind the `ServiceAppProtocol` feature gate in 1.18, and access to toggling feature gates is restricted.

**Comment by backjo** [comment]
That being said, I think appProtocol makes sense longer-term

**Comment by M00nF1sh** [comment]
@backjo 
This make sense to me 👍 
We have an internal securityReview process for all features we plan to launch before reinvent, i'll review the PR but hold the merge till the reinvent release.

**Comment by osterman** [comment]
Relates to #1590
