### ISSUE TITLE
Docs updates and confusion

### ISSUE THREAD

**Issue by rothgar** [kubernetes-sigs/aws-load-balancer-controller#1587]
There are some discrepencies in the docs at https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

We should update the official docs to specify which version of the ALB ingress they're for and add v2 ALB information.

Some changes like IAM permissions for the controller
```
"arn:aws:elasticloadbalancing:*:*:loadbalancer/*"
"arn:aws:elasticloadbalancing:*:*:targetgroup/*"
```
vs this in the v2 docs
```
"arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*"
"arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*"
```

If we update the official docs with a version that might be enough. We could also have the github pages show v1 and and v2 docs.

**Comment by M00nF1sh** [comment]
closing this, as we have multiple version github pages
