### ISSUE TITLE
Alb ingress annotation for reverse proxy to outside k8 service... 

### ISSUE THREAD

**Issue by gs-offcl** [kubernetes-sigs/aws-load-balancer-controller#1592]
Hi,

I am using alb ingress controller on eks cluster.  Currently I have a requirement to integrate outside k8 service via alb ingress with reverse proxy approach.

Below is nginx ingress annotation which does reverse proxy to external service( ( running outside k8s cluster)) with web socket connection and works. Are there any similar capabilities/annotations supported in alb ingress ?

ingress.yaml
...
nginx.org/server-snippets: |
location /somepath/ {
proxy_set_header Host $http_host;
proxy_pass https://ip:port/somepath/;
proxy_read_timeout 60m;
client_max_body_size 0;
#Enable websocket support
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}

Would really appreciate if any help/inputs provided.
Thanks.

**Comment by gs-offcl** [comment]
Any inputs on this?

**Comment by gs-offcl** [comment]
I would need this feature support badly. Any help or pointers would really appreciated.

**Comment by gs-offcl** [comment]
Found solution and issue has been resolved.  

Thanks.

**Comment by kishorj** [comment]
@gs-offcl could you provide a bit more details on the solution that you mentioned earlier?

**Comment by marceloboeira** [comment]
@gs-offcl what was the solution?

**Comment by krish512** [comment]
How can we achieve this?? Please share the solution here
