### ISSUE TITLE
Managing nodegroups with several Security Groups

### ISSUE THREAD

**Issue by allamand** [kubernetes-sigs/aws-load-balancer-controller#1594]
In my cluster, I have setup 2 security groups on my ASG.

this cause errors in the load-balancer-controller logs : 

```
 aws-load-balancer-controller {"level":"error","ts":1604056716.6213434,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"Targe ││ tGroupBinding","controller":"targetGroupBinding","name":"k8s-metrics-kubeopsv-24fdb1d6d0","namespace":"metrics","error":"expect exactly one securityGroup tagged with kubernet │
│ es.io/cluster/CassSpot for eni eni-027fad6da8078ca97, got: [sg-0735101ad3ec86cb1 sg-0bfcfd809667c1af3]"}
```

Why is there a limitation on the number of SecurityGroups ?

**Comment by M00nF1sh** [comment]
@allamand 
It's ok to have 2 security group, but for each ENI, only one of the security group should have the "kubernetes.io/cluster/cluster-name" tag. It's also a requirement for the in-tree cloudProvider code as well.
When a ENI have multiple SG, we need such information to decide which securityGroup to modify

**Comment by allamand** [comment]
Hi @M00nF1sh,

ok I see. In my case, I'm creating the nodesgroups using CDK, and didn't see how to add the correct security group in first place, so I added it to the ASG which seems not working with aws-load-balancer-controller. Do you have recommendation to fix this ?

```
const spotAsg = cluster.addAutoScalingGroupCapacity("Spot-" + AZs[az], {
        instanceType: new ec2.InstanceType(instanceType),
        minCapacity: 1,
        updateType: UpdateType.ROLLING_UPDATE,
        rollingUpdateConfiguration: {
          maxBatchSize: 1,
        },
        vpcSubnets: vpc.selectSubnets({
          subnetType: SubnetType.PRIVATE,
          availabilityZones: [vpc.availabilityZones[az]],
        }),
        maxCapacity: 10,
        spotPrice: "1.728",
        keyName: keyName,
        instanceMonitoring: Monitoring.DETAILED,
      });

      //Add Cluster Security Group to the Spot ASG
      spotAsg.addSecurityGroup(
        ec2.SecurityGroup.fromSecurityGroupId(this, "clusterSG" + AZs[az], cluster.clusterSecurityGroupId)
      );
```

**Comment by M00nF1sh** [comment]
@allamand 
what's the other security group added other than `cluster.clusterSecurityGroupI`?

**Comment by allamand** [comment]
@M00nF1sh  By default, the cluster.addAutoScalingGroupCapacity create for me a SecurityGroup (different from the clusterSecurityGroup) and It don't seem that I can control this with the actual cdk library

**Comment by guan840912** [comment]
@allamand I use this method to remove the SecurityGroup tag `kubernetes.io/cluster/${cluster.clusterName}` created by cluster.addAutoScalingGroupCapacity().
```ts
const asg = cluster.addAutoScalingGroupCapacity('nodes', {
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3A, ec2.InstanceSize.SMALL),
      maxCapacity: 3,
      minCapacity: 2,
      spotPrice: '0.0070',
    });
    const ASGSG = asg.node.findChild('InstanceSecurityGroup') as ec2.ISecurityGroup;
    // remove kubernetes.io/cluster/${cluster.clusterName} tag from InstanceSecurityGroup.
    Tags.of(ASGSG).remove(`kubernetes.io/cluster/${cluster.clusterName}`);
```

**Comment by Tanbouz** [comment]
I have a use case of using [Security Groups for pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) to allow a permissive inbound for ingress pods while keeping the nodes security group locked down.

The ingress pods ENIs have both the permissive pod security group attached (for external traffic) & the generic node security group (cluster local network) to allow ingress traffic to reach services hosted inside or reach CoreDNS for example.

I would prefer if the controller modifies the permissive pod security group instead of exposing nodes security group unnecessarily.

If a custom non default tag can be used to pick the Pod Security Group instead of the one tagged "kubernetes.io/cluster/cluster-name" tag it would help not having to keep explicitly defining an inbound rule to the nodes security group each time I add a new "ingress" pod security group (vs attaching two security groups).

**Comment by chary1112004** [comment]
> @M00nF1sh By default, the cluster.addAutoScalingGroupCapacity create for me a SecurityGroup (different from the clusterSecurityGroup) and It don't seem that I can control this with the actual cdk library

We have similar issues:
- 1 security group is created during created eks 
- 1 security group is created during cluster-autoscaler

expect exactly one securityGroup tagged with kubernetes.io/cluster/<cluster name> for eni eni-00ecd1b506ce989a0, got: [sg-0115455eb691defca sg-0726def54ced4f7cb] (clusterName: <cluster name>)

Action:
- When we remove tag in kubernetes.io/cluster/<cluster name> in first security group (1 security group is created during created eks) then after a while eks is automatically added it back. Refer to https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
- For security group is created by cluster-autoscaler then it is out of control.

Any solution for this case is appreaciate!

Thanks!
