### ISSUE TITLE
Keep old aws-alb-ingress-controller 1.x repository with docs, examples

### ISSUE THREAD

**Issue by Vadim-Zenin** [kubernetes-sigs/aws-load-balancer-controller#1595]
Please keep old aws-alb-ingress-controller 1.x repository with docs, examples.
It used by AWS documentation, deployment scripts.
It allows people migrate smoothly from 1 version to next.

**Comment by kishorj** [comment]
@Vadim-Zenin Thanks for the feedback. We are working on versioned documentation so that we can make the 1.x doc available for reference in the gh-pages.

**Comment by M00nF1sh** [comment]
@Vadim-Zenin 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/ is alive now, and our page supports multiple version. 

closing this
