### ISSUE TITLE
Pod Readiness Gate Is Not Backwards Compatible With ALB Ingress Controller V1

### ISSUE THREAD

**Issue by Mr-Howard-Roark** [kubernetes-sigs/aws-load-balancer-controller#1602]
The docs seem to imply that v2 of the ALB Ingress Controller is backwards compatible with V1.  However, that doesn't seem to be the case for Pod Readiness Gates.  The doc [here ](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/pod_readiness_gate/) suggests that we can continue to use V1 readiness-gate configuration by disabling readiness gate injection. 
```
## Upgrading from AWS ALB Ingress controller
If you have a pod spec with the AWS ALB ingress controller (aka v1) style readiness-gate configuration, the controller will automatically remove the legacy readiness gates config and add new ones during pod creation if the pod namespace is labelled correctly. Other than the namespace labeling, no further configuration is necessary.
The legacy readiness gates have the `target-health.alb.ingress.k8s.aws` prefix.
```

```
## Disabling the readiness gate inject
You can specify the controller flag `--enable-pod-readiness-gate-inject=false` during controller startup to disable the controller from modifying the pod spec.
```

However, based on testing, the AWS Load Balancer Controller doesn't seem to recognize the old configuration prefix -- Deployments sit at 0/1 forever because the Readiness Gate never passes.  We need to continue to use v1 because of this limitation you mention your doc:
```
!!!tip "create ingress or service before pod"
    To ensure all of your pods in a namespace get the readiness gate config, you need create your Ingress or Service and label the namespace before creating the pods
```

Our Helm charts are running into problems because they don't install the Ingress before everything else.  So, we can't use this new v2 version of the feature.

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
You need to **label** your pod namespace with `elbv2.k8s.aws/pod-readiness-gate-inject: enabled`.
Once it's labelled correctly, the v2 controller have a webhook which will automatically remove the old readinessGate format from your pod(so it's backwards compatible if setup correctly).

**Comment by Mr-Howard-Roark** [comment]
Ok that does seem to work, thanks for your response.  I can close this in a minute, but is this feature supposed to work with Helm charts?  ie- people have:
```
templates/
  ingress.yaml
  service.yaml
  deployment.yaml
```
And helm deploys the `ingress` last.  So the order of operations Developers will need to take is to run their usual `helm install` and then manually cycle the pods of their deployment so that a Target Group is created with their ips as targets.

As an aside, I do think that the feature is very cool.  I just have that last clarification question since most of our developers use helm charts.

**Comment by M00nF1sh** [comment]
@Mr-Howard-Roark 
You don't need to. The readinessGate is to protect rolling update case(it waits new pods to become ready before terminate old pods).
For new setup, it's totally fine to have pods without readinessGate.

**Comment by Mr-Howard-Roark** [comment]
Ok thanks that makes a lot of sense the more I think about it.  I did a bunch of tests and you are right-- our developers who use `helm` will be fine going forward now that we added this annotation to our namespaces.  Thanks as usual for your helpful responses.

**Comment by 64bit** [comment]
> 
> You don't need to. The readinessGate is to protect rolling update case(it waits new pods to become healthy before terminate old pods).
> For new setup, it's totally fine to have pods without readinessGate.(we also support you to specify the new format pod readiness gate manually in deployment spec if you still want them :D).

It would be amazing to have this in documentation https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/pod_readiness_gate/ 

I was worried that from get-go the first Pod needs readiness gate too. But finding this comment is a relief :)

**Comment by aboretum** [comment]
> (we also support you to specify the new format pod readiness gate manually in deployment spec if you still want them :D).

@M00nF1sh Can you advise on what readiness gate condition format would that be? (Upon looking at the generated pod readiness gate condition by the webhook, it appears to be referencing a specific ALB as the 
``` yaml
  readinessGates:
  - conditionType: target-health.elbv2.k8s.aws/k8s-myalb-31d2b7f0c5
```
)

I'm in an organization where the responsibility between setting namespace tag and pod spec are split to different teams, so I can't count on the namespace tag `elbv2.k8s.aws/pod-readiness-gate-inject: enabled` to always be there.

**Comment by wwftw** [comment]
> (we also support you to specify the new format pod readiness gate manually in deployment spec if you still want them :D).

@M00nF1sh Can you advise on what readiness gate condition format would that be? (Upon looking at the pod readinessgate template generated by the webhook, it looks like it references a specific ALB as the name contains a SHA
``` yaml
  readinessGates:
  - conditionType: target-health.elbv2.k8s.aws/k8s-myalb-31d2b7f0c5
```
)

I'm in an organization where the responsibility of setting namespaces tags and pod template spec fall into different teams. I can't always relying on the `elbv2.k8s.aws/pod-readiness-gate-inject: enabled` being there.
