### ISSUE TITLE
Terrible HA/FT test results for NLB/ALB in "ip mode" compare to "instance mode".

### ISSUE THREAD

**Issue by lmgnid** [kubernetes-sigs/aws-load-balancer-controller#1603]
Hello, I am testing the IP Mode for both NLB and ALB, compare to the instance mode, the only difference of the setting are:

`
alb.ingress.kubernetes.io/target-type: ip
--
  |   | alb.ingress.kubernetes.io/target-type: instance
`

Or
`
service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
--
  |   | service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
`

But the tested these IP mode NLB/ALB, they are terrible HA/FT results and service breaks (Test by delete the pod, or update the deployment):
- For NLB, 2-3 mins service break, compare to No break in instance mode for the same testing
- For ALB, 10s service break, compare to No break in instance mode for the same testing

Some other information:
EKS version: 1.18 eks.2
image: amazon/aws-alb-ingress-controller:v2.0.0

Any ideas? Thanks!

**Comment by M00nF1sh** [comment]
@lmgnid 
You need to enable podReadinessGate for IP mode: https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/pod_readiness_gate/

Also, you need to have prestop hook for both instance/ip mode if your app don't support graceful shutdown.
