### ISSUE TITLE
Terrible HA/FT test results for the ALB/NLB "Ip mode" compare to "instance mode"

### ISSUE THREAD

**Issue by lmgnid** [kubernetes-sigs/aws-load-balancer-controller#1604]
Hello, I am testing the IP Mode for both NLB and ALB, compare to the instance mode, the only difference of the setting are:

alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/target-type: instance

service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

But the tested these IP mode NLB/ALB, they are terrible HA/FT results and service breaks (Test by delete the pod, or update the deployment):
- For NLB, 2-3 mins service break, compare to No break in instance mode for the same testing
- For ALB, 10s service break, compare to No break in instance mode for the same testing

Some other information:
EKS version: 1.18 eks.2
image: amazon/aws-alb-ingress-controller:v2.0.0

Any ideas? Thanks!

**Comment by kishorj** [comment]
Have you tried pod readiness gate? 
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/controller/pod_readiness_gate.md

**Comment by lmgnid** [comment]
Yes, tried it, didn't see any differences.

**Comment by dza89** [comment]
I'm afraid that this is not a controller issue but and issue of the NLB itself.

**Comment by M00nF1sh** [comment]
@lmgnid
You need to enable podReadinessGate for IP mode: https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/pod_readiness_gate/

Also, you need to have prestop hook for both instance/ip mode if your app don't support graceful shutdown.

**Comment by kishorj** [comment]
Closing the issue for now. Feel free to reopen this if you have further concerns.

**Comment by infa-sanaik** [comment]
@imgnid Did you find any solution for this issue? We are also facing same issue.

**Comment by blhagadorn** [comment]
@infa-sanaik Do you have podReadinessGate and prestop hook configured? What are you seeing, exactly?

**Comment by lmgnid** [comment]
Really don't understand why this ticket is closed, @kishorj : Did you EVER really test it?
Just tested it again with the EKS1.20 and LB controller v2.1.2, still the same for at least NLB.
Also for @M00nF1sh's questions:
1: Yes as my comments above I tried with PodReadinessGate
2: Yes we DO have graceful shutdown, also we have NO issues in instance mode.

As my comments above, this issue is NLB cannot catch the health/unhealth pods on time in IP mode. Thus caused the service break. For example a healthy pods need ~3mins to be "healthy" in TG, even I only set as 2*10=20-30 seconds.

**Comment by blueice123** [comment]
Neither do I have any idea why this ticket was closed.
When a pod is replaced in the NLB IP target group, the connection is unconditionally disconnected.

There doesn't seem to be a way to gracefully disconnect.
This problem can be proven with a simple test.
EKS env: 1.21v
aws-load-balancer-controller: v2.2.4
 -> https://github.com/blueice123/grpc_server/blob/server-1/tcp_docker/tcp.yaml
