### ISSUE TITLE
Cert-manager issues with fargate

### ISSUE THREAD

**Issue by muhyousri** [kubernetes-sigs/aws-load-balancer-controller#1606]
Hello , 

We noticed some issues related to creating the cluster issuer on fargate when using the Yaml version , the issue is related to this cert-manager issue

https://github.com/jetstack/cert-manager/issues/3237

we tested the helm chart and I am aware that it's working on fargate as it's not using cert-manager and creating a self signed cert , we just need the documentation to reflect that it's the only way right now to deploy the controller on fargate pods to avoid confusion

I also suggest releasing a Yaml version without cert-manager dependency if that wasn't planned already 

Thanks

**Comment by fimbulvetr** [comment]
I agree that it would be nice to have this package without cert-manager. cert-manager is quite a significant dependency to introduce, seeing as it as an entirely new project in our cluster and weighs in at 2mb on the yaml. I currently have our aws-load-balancer-controller written as jsonnet (to better handle the arguments such as cluster-name) as well to use the fine-grained pod roles that are pre-allocated by cloudformation. I am ruling it "not possible" to convert cert-maanger to jsonnet as I just don't have that kind of time - which means that I now have two steps to deploy - `kubecfg` and `kubectl apply` - which just makes things that much more difficult.
It would be great if we could have this as an optional dependency, and even greater if you could have a [cdk8s](https://github.com/awslabs/cdk8s) version of this with and without cert-manager.

**Comment by kishorj** [comment]
/kind feature
To remove the cert-manage dpendency, we can provide the yaml sepc and script to generate the self-signed certs and secrets in future.

Also, check if helm template works for your use case. Helm will generate the self-signed cert, and secret resources.
