### ISSUE TITLE
nlb annotation `service.beta.kubernetes.io/aws-load-balancer-healthcheck-port` documented as string, must be int

### ISSUE THREAD

**Issue by chlunde** [kubernetes-sigs/aws-load-balancer-controller#1615]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blame/main/docs/guide/service/annotations.md#L31

says:
|Name                                                                               | Type              | Default       |
|-----------------------------------------------------------------------------------|-------------------|---------------|
|service.beta.kubernetes.io/aws-load-balancer-healthcheck-port                      | string            | traffic-port  |

Attempting to use a string here shows that only an integer is supported currently:

`failed to parse int64 annotation, service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: status-port: strconv.ParseInt: parsing "status-port": invalid syntax`

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/efe7e71d270e57a70d0c17587ee89237e055ee4d/pkg/service/nlb/builder.go#L263

Is the code wrong, or docs? :-)

**Comment by kishorj** [comment]
The only non-integer value supported currently is "traffic-port".

**Comment by kishorj** [comment]
I will update the documentation to correct this. The type is int, or "traffic-port" string value.
