### ISSUE TITLE
[v2] Controller deployment fails on Fargate

### ISSUE THREAD

**Issue by k3ypad** [kubernetes-sigs/aws-load-balancer-controller#1622]
Hi folks - tried installing the v2 following the[ AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) and received the error:
`{"level":"error","ts":1604540545.7699356,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}`

**Further details**
Using eksctl version 0.30.0
Cluster creation command: 
```
eksctl create cluster \
--name arbitrary-name \
--version 1.18 \
--region ap-southeast-2 \
--fargate
```
Note I've confirmed this creates a Fargate profile for the `kube-system` namespace.

Stepping through the docs:
1. `associate-iam-oidc-provider` succeeds as expected
2. curl succeeds
3. Policy creation succeeds
4. `eksctl create iamserviceaccount` succeeds - verified arn paramater is the same as was created in step 3.
5. N/A as new cluster
6. Helm install a-c succeed as expected
7. N/A as helm install succeeded
8. Deployment never becomes ready 

`kubectl logs -n kube-system   deployment.apps/aws-load-balancer-controller` :

```
{"level":"info","ts":1604540539.4608905,"msg":"version","GitVersion":"v2.0.0","GitCommit":"1028fa4f363a9a8e37b07ff6a093b7b422923512","BuildDate":"2020-10-21T22:17:18+0000"}
{"level":"error","ts":1604540545.7699356,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
```

**Comment by kishorj** [comment]
@k3ypad You need to manually specify the aws-region and aws-vpc-id flags to the controller. For helm installation, you can specify additional arguments `--set region=<AWS_REGION> --set vpcId=<AWS_VPC_ID>`.

**Comment by kishorj** [comment]
Closing this issue. Feel free to reopen this if the issue persists.

**Comment by sukrit007** [comment]
@kishorj  Thanks for the workaround.  Is it possible to get this added to the main document?   Took me a few hours to figure out why my NLB was not getting created.
