### ISSUE TITLE
http to https redirect

### ISSUE THREAD

**Issue by eugenetaranov** [kubernetes-sigs/aws-load-balancer-controller#1623]
Hello,

is it currently possible to redirect all http queries to https?

Thanks

**Comment by M00nF1sh** [comment]
@eugenetaranov 
Yes, it's possible: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/tasks/ssl_redirect/

**Comment by eugenetaranov** [comment]
thanks @M00nF1sh , it worked!
