### ISSUE TITLE
AWS Load Balancer Controller cannot be installed in a namespace with the readiness gate label

### ISSUE THREAD

**Issue by jmriebold** [kubernetes-sigs/aws-load-balancer-controller#1628]
Installing the AWS Load Balancer Controller in a namespace which has the `elbv2.k8s.aws/pod-readiness-gate-inject: enabled` NS label leads to a stuck deployment which cannot start a pod, with the following error:

```
Error creating: Internal error occurred: failed calling webhook "mpod.elbv2.k8s.aws": Post https://aws-load-balancer-controller-webhook-service.kube-system.svc:443/mutate-v1-pod?timeout=30s: no endpoints available for service "aws-load-balancer-controller-webhook-service"
```

I was able to get around this by temporarily removing the label, installing the chart, and restoring the label, however I'm curious if this behavior can be fixed, or if I'm simply doing something wrong on my end.

**Comment by kishorj** [comment]
You need to install the AWS Load Balancer Controller in a namespace without the `elbv2.k8s.aws/pod-readiness-gate-inject: enabled` label. For readiness gate, the mutating webhook gets invoked for during pod creation for each pod in the labelled namespaces, and without aws load balancer controller running, the pods will never be created successfully. This applies to the AWS load balancer controller pods as well if put in a labelled namespace.

The temporary workaround will not hold if the controller pod has to be recreated again.

**Comment by jmriebold** [comment]
Understood, thanks for the clarification.

**Comment by mda590** [comment]
@kishorj I wanted to follow-up on this. We are facing a similar issue as what @jmriebold mentioned. I understand what you are saying about putting the AWS Load Balancer Controller in a namespace without the `elbv2.k8s.aws/pod-readiness-gate-inject: enabled` label. However, we have all of our system components deployed into a namespace together (not kube-system, but org-system) and for some of those services that have web frontends behind an ALB. We would like to leverage the benefits of the ELB pod readiness gate for those pods.

It doesn't seem like we can add an exclusion for a specific pod for the mutating webhook to ignore - are there any recommendations for how to run in this manner, or is there no way to have only the AWS LBC pod ignored by the webhook? I'm thinking not, but wanted to see.

Thanks!
