### ISSUE TITLE
Ingres resources are not getting deleted even though the alb ingress controller deployment is deleted

### ISSUE THREAD

**Issue by git-kote** [kubernetes-sigs/aws-load-balancer-controller#1629]
There are two issues i faced while trying to use single load balancer feature

1. new ingress resource is failing to add ALB with new ingress group name (works only when the resource group name is changed to any existing ingress group name)
2. I started deleting all ingress resources from kuberentes but its struck. the aws alb ingress controller logs shows the repeated logs (deregistering targets) 
the deletion still continues though the alb ingress controller deployment is deleted
the deletion still continues though the ALB attached is deleted from aws console

and this error i am not able to understand why there is a conflict when i provided individual annotations for both subnets and security groups
{"level":"error","ts":1604857656.6127725,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ieie.com","namespace":"","error":"conflicting securityGroups: [sg-070cc1589434f5fa70bca sg-05cca8fbcii3o2d6ff04c7] | [subnet-057938d7384939be5cc5dd subnet-0439af3389f7i3045ae882]"}

please note that i am able to delete rest of the ingress resources except the ones i defined  alb.ingress.kubernetes.io/group.name: mygroup annotation

[ec2-user@ip-03 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", 
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", 

and i am using amazon/aws-alb-ingress-controller:v2.0.0 image

**Comment by kishorj** [comment]
The controller adds a finalizer to each of the processed ingress resources. If the controller deployment gets deleted before those ingress resources, the ingresses cannot be deleted later without manually removing the finalizer.

**Comment by git-kote** [comment]
Yes deleting finalizers deleted the ing resources. I will test again on our microservices. 
@kishorj  do you think this is same reason why its not able to add the ALB to new ing too ?

**Comment by kishorj** [comment]
@git-kote, deleting finalizer will remove the ingress resources, however, you'd need to cleanup the AWS LB resources manually. The recommended approach is to let the controller do the cleanup.

As for the reconciler error you mentioned, it looks like you've specified conflicting security group across multiple ingress resources that are part of the same ingress group. If you manually specify security groups via annotations, make sure the configuration match across all ingress resources in the same group. The error message also indicate `subnet-*` as the SG names. These look like subnet names.

Once you fix the configuration, controller should be able to correctly reconcile the ALB resources. If you still encounter issues, you can share the ingress manifests for the affected resources, we'll take a look.

**Comment by scardena** [comment]
@kishorj what do you mean "deleting finalizer will remove the ingress resources?"
how can I "delete a finalizer"? I am running into a similar problem in which I remove a helm deployment, and the ingress resource is not deleted, reason is:
`"error":"failed to delete securityGroup: timed out waiting for the condition"`
The reason is because the Cluster Security Group is still referencing the security group created for the load balancer by the old Ingress Controller. Deleting the reference from the Cluster Security Group allows the ALB controller to finally get rid of the ingress. is this a bug? how can I inspect the finalizers? because I run a describe in all ours ingresses objects (pre/post upgrade) and I can't find any.

**Comment by mikariekkinen** [comment]
@scardena, I have a similar problem, when deleting the namespace where the ingress is. This is my workaround at the moment:
`kubectl patch ingress <name-of-the-ingress> -n<your-namespace> -p '{"metadata":{"finalizers":[]}}' --type=merge`

**Comment by scardena** [comment]
@mikariekkinen won't that leave the ALB dangling? then you will need to remove it manually later. Although deleting a rule for sec groups is also a manual process. I wonder if this is a bug or not.

**Comment by mikariekkinen** [comment]
@scardena, To be honest, don't really know for sure. My problem comes when I want to delete a namespace, and the ingresses are not deleted. Then the namespace stays in "Terminating" state. I just run my first workaround with this script:

```
# Delete the namespace and wait for 15s for the deletion
kubectl delete namespace $NAMESPACE --grace-period=15 &

sleep 10

# Delete ingress finalizers (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1629)
ingresses=$(kubectl get ingress -n$NAMESPACE -o custom-columns=":metadata.name")

for i in $ingresses ; do
  kubectl patch ingress $i -n$NAMESPACE -p '{"metadata":{"finalizers":[]}}' --type=merge
done
```
And it did not leave anything on ALB. I.e the Loadbalancer was correctly cleaned. 
In my case, this one ALB is serving many namespaces (group is the same for all of them), and there is no danger of dangling ALB in that sense.

**Comment by kishorj** [comment]
@scardena, if the controller is running, you don't have the delete the finalizers, controller should cleanup all the resources on delete. If there are errors, you can share with us and we will help further identify the issue.

If you uninstall the controller before deleting the ingresses, then you will need to remove the finalizers to delete the resources.

@mikariekkinen, what error do you see in the logs when you delete the namespace?

**Comment by scardena** [comment]
@kishorj but that's the thing, the controller is not cleaning up properly. In my original comment, I state that we haven't uninstall the AWS LB controller, and we run into the error:
`"error":"failed to delete securityGroup: timed out waiting for the condition"`, from the lb controller logs when it's trying to delete the ingress object.
Refer to my original comment on what's the cause for this timeout condition, and the workaround we had to use.

**Comment by kishorj** [comment]
@scardena, I see your point. If you are upgrading from AWSALBIngressController (v1) to AWSLoadBalancerController(v2), and ingresses don't have the security-gruops annotation, you need to manually add `elbv2.k8s.aws/targetGroupBinding=shared` to the SG rule description as mentioned in the [migration guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/upgrade/migrate_v1_v2/). If this doesn't apply, let us know.

**Comment by scardena** [comment]
@kishorj yep, confirmed that adding that description actually gets of the ingress. Thanks

**Comment by mikariekkinen** [comment]
@kishorj, strangely enough, I cannot reproduce this anymore. I will try to reproduce this today again. But, when the issue was happening on friday, I have 5 namespaces, that are affected. These phantom namespaces introduce errors like this into logs:

`
{"level":"error","ts":1606108933.8226197,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"xxxx-platform","namespace":"","error":"namespaces \"pr-130\" not found"}
`

**Comment by M00nF1sh** [comment]
@mikariekkinen 
have you been able to reproduce the issue you saw? seems like some k8s bug. Is the Ingress still in these `phantom namespaces` while namespace is gone?

**Comment by mikariekkinen** [comment]
Yes. Now I was able to reproduce this. Waited for 5 minutes for the namespace deletion. I left the namespace as is and did not apply the workaround I mentioned above. So, the namespace stays now in terminating state.

Attached a log from ingress controller for this test. It started by creation of test namespace, followed by an installation of one service through helm, and finally deletion of namespace. I have marked those events in the log file:
[alb-problem-a.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/5600965/alb-problem-a.txt)

And yes, those ingresses are still visible in those "phantom" namespaces, here is one:
[alb-problem-b.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/5600995/alb-problem-b.txt)

**Comment by literalice** [comment]
In my environment, this error occurred.

```
2020-12-08T13:17:20.496291639Z {"level":"error","ts":1607433440.4961708,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress11","namespace":"dev1","error":"failed to delete securityGroup: timed out waiting for the condition"}
2020-12-08T13:17:21.224316174Z {"level":"info","ts":1607433441.2240896,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-xxx"}
...
```

* The SG that cannot  be deleted is associated to `eks-cluster-sg-xxx` 's inbound rule. It might prevent deleting the SG.
* I'd upgraded the Load Balancer Controller from ALB Ingress Controller (v1)

Thank you.

**Comment by diranged** [comment]
> In my environment, this error occurred.
> 
> ```
> 2020-12-08T13:17:20.496291639Z {"level":"error","ts":1607433440.4961708,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress11","namespace":"dev1","error":"failed to delete securityGroup: timed out waiting for the condition"}
> 2020-12-08T13:17:21.224316174Z {"level":"info","ts":1607433441.2240896,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-xxx"}
> ...
> ```
> 
> * The SG that cannot  be deleted is associated to `eks-cluster-sg-xxx` 's inbound rule. It might prevent deleting the SG.
> * I'd upgraded the Load Balancer Controller from ALB Ingress Controller (v1)
> 
> Thank you.

I am seeing the exact same issue with the AWS Load Balancer Controller v2.1.0.. would love to see this fixed ASAP.

**Comment by arnikasky** [comment]
Have the same issue as @diranged

**Comment by mikariekkinen** [comment]
> `{"level":"error","ts":1606108933.8226197,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"xxxx-platform","namespace":"","error":"namespaces \"pr-130\" not found"}`

For this particular problem of errors in controller log, looks like it is enough to just create those missing namespaces.

**Comment by git-kote** [comment]
after upgrading to newer version we are able to delete the ingress resources (and we realized that load balancers are not getting deleted as the security groups are not created by ingress instead we created manually)

**Comment by darren-steven** [comment]
We have noticed this inability to delete behavior as well. If you deploy a targetGroupBinding that is mis-configured, it cannot be deleted without removing the finalizer

**Comment by brettcave** [comment]
I was able to work around the hung ingress delete by rewriting the ingress json. 

1. If you have deleted the NS, you will need to recreate it: `kubectl create ns pr-130`
2. Get the JSON format output of the ing, and strip out finalizers, then post it back to the ingress endpoint (assuming you're running kube proxy to get direct access to the API). 

Here's a 1 liner: 
```
curl -H "Content-Type: application/json" -X PUT --data-binary "$(kubectl get ingress -n pr-130 whatever-platform -o json | jq '.metadata.finalizers = []')"  http://127.0.0.1:8001/apis/extensions/v1beta1/namespaces/pr-130/ingresses/whatever-platform
```

`pr-130` is a sample namespace from above thread, with `whatever-platform` as whatever the ingress name is.

**Comment by brettcave** [comment]
using `kubectl edit` to modify the ing and delete the finalizers should also work.

**Comment by kishorj** [comment]
@darren-steven, do you see any errors in the controller logs for the mis-configured targetGroupBinding? If you remove the finalizers manually, the controller doesn't get a chance to cleanup the underlying AWS resources.

**Comment by yi-yang-github** [comment]
Just add a few cents here as I ran into this problem and this is how I discovered the solution and fixed it:
Run this command to check the logs of the aws-load-balancer-controller:
```
kubectl logs -f  -n kube-system   deployment.apps/aws-load-balancer-controller
```
And I got something like
```
{"level":"error","ts":16203*******,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"dev-lb","namespace":"","error":"AccessDenied: User: arn:aws:sts::*********:assumed-role/eksctl-prod-nodegroup-prod-manage-NodeInstanceRole-********* is not authorized to perform: elasticloadbalancing:DescribeTargetGroups\n\tstatus code: 403, request id: ***********"}
```
Then I ran
```
aws iam attach-role-policy \
  --role-name eksctl-prod-nodegroup-prod-manage-NodeInstanceRole-******\
  --policy-arn arn:aws:iam::******:policy/AWSLoadBalancerControllerAdditionalIAMPolicy

aws iam attach-role-policy \
  --role-name eksctl-prod-nodegroup-prod-manage-NodeInstanceRole-******\
  --policy-arn arn:aws:iam::******:policy/AWSLoadBalancerControllerIAMPolicy
```
And the NodeGroup user now have access to the TargetGroups thus can add / delete loadbalancers.

The upgrade / migration guides mostly talking about creating a new service account and apply the 2 policies to that newly created service account, which did nothing to me. For me, the key is to apply the policies to the EXISTING NodeGroup service account.

**Comment by onagorodniuk** [comment]
> kubectl patch ingress <name-of-the-ingress> -n<your-namespace> -p '{"metadata":{"finalizers":[]}}' --type=merge

Thank you! It helped!

**Comment by johnny-fuse** [comment]
aws-load-balancer-controller requires a target group binding custom resource to be created.
I can't delete this crd, it keeps coming back no matter what I do...

Tried to edit it and delete the finalizers section as well, and still nothing. anyone?

**Comment by setevoy2** [comment]
Got a similar issue after upgrading from V1 to V2, but with new Ingresses, i.e. being created by using the V2 Controller.

1. created an Ingress
2. deleted it
3. its ALB was deleted (!), but its Namespace is still present in the _Terminating_ state

The error is:

> {"level":"info","ts":1625580538.1154413,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-093334fe379aeff03"}
> {"level":"error","ts":1625580371.9100788,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"test-ingress","namespace":"test-namespace","error":"failed to delete securityGroup: timed out waiting for the condition"}

The "_sg-093334fe379aeff03_" has references from WorkerNodes SGs, **but** they all has the "elbv2.k8s.aws/targetGroupBinding=shared" in the Description field, as it's mentioned in the docs.

Removing the `finalizers` from an Ingress will indeed delete its Ingress API object, but it lives the SecurityGroup and its references from WorkerNodes.

Using ALB Controller v2.2.1

**Comment by ismailyenigul** [comment]
I had the same issue.
`"error":"failed to delete securityGroup: timed out waiting for the condition"`

I migrated ALB ingress from v1 to v2 but I did not have `elbv2.k8s.aws/targetGroupBinding=shared` in the description of inbound rule  added to EKS worker node securityGroup.
The rule cannot be deleted because `elbv2.k8s.aws/targetGroupBinding=shared`  is missing in the rule description. 
ALB can't remove inbound rule and can't delete security group created by ingress controller.

I am using argocd. When I delete all resources in gitops repo, argocd tries to delete all resources including namespace. But can't delete ingress resource in the same namespace. 
For that reason, ingress resource and namespace stay in `Terminated` state.

As a result, instead of simply removing finalizers. Find the problem by checking logs that causes the issue.

Steps:
checked namespace status.
```
$ kubectl get namespaces myns -o json

 "lastTransitionTime": "2021-10-12T18:50:13Z",
                "message": "Some resources are remaining: ingresses.extensions has 1 resource instances, ingresses.networking.k8s.io has 1 resource instances",
                "reason": "SomeResourcesRemain",
                "status": "True",
                "type": "NamespaceContentRemaining"
```
Found the issue about ingress resource them checked ingress resource
```
kubectl get ingress -n  myns
NAME         CLASS    HOSTS                                                                          ADDRESS                                                            PORTS   AGE
my-ingress   <none>   myurl.
```
Checked ingress controller logs and got `"error":"failed to delete securityGroup: timed out waiting for the condition"`
Tried to delete manually security group but got error about sg association in worker security group.

**Comment by tan-i-ham** [comment]
I am not sure if it is the same problem
but maybe is similar question?
https://github.com/kubernetes/kubernetes/issues/95983

**Comment by kishorj** [comment]
The issue is highly likely due to upgrade from the previous 1.1.x version of the aws-alb-ingress-controller to the v2 version. While upgrade supports existing resources, there are additional IAM permissions needed, as well as the SG rules comments as mentioned in the upgrade guide https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/upgrade/migrate_v1_v2/

The controller fails to delete the security group since it is referred from the node SG ingress rule. The controller only those SG rules with the comment `elbv2.k8s.aws/targetGroupBinding=shared`.

The conflicting security group is due to different security groups configured in the ingress group members. In case of ingress group, either all ingresses have the same security groups configured via annotation, or empty.

I'm closing the issue for now, if problem persists with the latest version, feel free to reach out to us.

**Comment by dgurns** [comment]
In case anyone finds this later, here's my solution which makes it possible to fully delete the namespace:

```
kubectl patch ingress ph-ingress -n $KUBE_NAMESPACE -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl delete ingress ph-ingress -n $KUBE_NAMESPACE
kubectl delete namespace $KUBE_NAMESPACE
```

**Comment by ryanovas** [comment]
I think I see that a fix was applied to 2.5.2, but I don't see any clear instructions out there for how to upgrade versions? Could someone point me in the right direction?

**Comment by omidraha** [comment]
I have same issue with `Pulumi destroy`.

The `Load balancer` file:

```python
    kubernetes.helm.v3.Chart(
            "lb",
            kubernetes.helm.v3.ChartOpts(
                chart="aws-load-balancer-controller",
                fetch_opts=kubernetes.helm.v3.FetchOpts(
                    repo="https://aws.github.io/eks-charts"
                ),
                namespace=namespace.metadata["name"],
                values={
                    "logLevel": "debug",
                    "region": "us-west-2",
                    "replicaCount": "1",
                    "serviceAccount": {
                        "name": "aws-lb-controller-serviceaccount",
                        "create": False,
                    },
                    "vpcId": vpc.vpc_id,
                    "clusterName": cluster_name,
                    "podLabels": {
                        "app": "aws-lb-controller"
                    },
                    "autoDiscoverAwsRegion": "true",
                    "autoDiscoverAwsVpcID": "true",
                    "keepTLSSecret": True,
                },
            ),
            pulumi.ResourceOptions(
                provider=provider,
                parent=namespace
            )
        )
```
The `Ingress` file:

```python

    kubernetes.networking.v1.Ingress(
        "ingress",
        metadata=kubernetes.meta.v1.ObjectMetaArgs(
            name='ingress',
            namespace=namespace.metadata["name"],
            annotations={
                "kubernetes.io/ingress.class": "alb",
                "alb.ingress.kubernetes.io/target-type": "instance",
                "alb.ingress.kubernetes.io/scheme": "internet-facing",
                'external-dns.alpha.kubernetes.io/hostname': 'app1.idmelon.com,app2.idmelon.com',
                # 'alb.ingress.kubernetes.io/listen-ports': '[{"HTTPS":443}, {"HTTP":80}]',
            },
            labels={
                'app': 'ingress'
            },
        ),
        spec=kubernetes.networking.v1.IngressSpecArgs(
            rules=[
                kubernetes.networking.v1.IngressRuleArgs(
                    host='app1.example.com',
                    http=kubernetes.networking.v1.HTTPIngressRuleValueArgs(
                        paths=[
                            kubernetes.networking.v1.HTTPIngressPathArgs(
                                path="/",
                                path_type="Prefix",
                                backend=kubernetes.networking.v1.IngressBackendArgs(
                                    service=kubernetes.networking.v1.IngressServiceBackendArgs(
                                        name=service_app_01.metadata.name,
                                        port=kubernetes.networking.v1.ServiceBackendPortArgs(
                                            number=80,
                                        ),
                                    ),
                                ),
                            ),
                        ],
                    ),
                ),
                kubernetes.networking.v1.IngressRuleArgs(
                    host='app2.example.com',
                    http=kubernetes.networking.v1.HTTPIngressRuleValueArgs(
                        paths=[
                            kubernetes.networking.v1.HTTPIngressPathArgs(
                                path="/",
                                path_type="Prefix",
                                backend=kubernetes.networking.v1.IngressBackendArgs(
                                    service=kubernetes.networking.v1.IngressServiceBackendArgs(
                                        name=service_app_02.metadata.name,
                                        port=kubernetes.networking.v1.ServiceBackendPortArgs(
                                            number=80,
                                        ),
                                    ),
                                ),
                            ),
                        ],
                    ),
                )
            ],
        ),
        opts=pulumi.ResourceOptions(provider=provider)
    )
```
The `External dns` file:

```python

    external_dns = kubernetes.helm.v3.Chart(
        "external-dns",
        kubernetes.helm.v3.ChartOpts(
            chart="external-dns",
            fetch_opts=kubernetes.helm.v3.FetchOpts(
                repo="https://charts.bitnami.com/bitnami"
            ),
            namespace=namespace.metadata["name"],
            values={
                "logLevel": "debug",
                'provider': 'cloudflare',
                'sources': ['ingress'],
                'domainFilters': ['example.com'],
                "cloudflare": {
                    "apiToken": 'token',
                    "email": 'email',
                    'cloudflare-dns-records-per-page': '5000',
                    'proxied': False,
                },
                "replicaCount": "1",
                "region": "us-west-2",
            },
        ),
        pulumi.ResourceOptions(
            provider=provider,
            parent=namespace
        )
    )
    return external_dns
```

### Traceback

```bash

$ pulumi destroy

Destroying (dev):
     Type                                                            Name                               Status                  Info
     pulumi:pulumi:Stack                                             devops-dev                         **failed**              1 error
 -   └─ kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  targetgroupbindings.elbv2.k8s.aws  **deleting failed**     1 error


Diagnostics:
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (targetgroupbindings.elbv2.k8s.aws):
    error: 'targetgroupbindings.elbv2.k8s.aws' timed out waiting to be Ready

  pulumi:pulumi:Stack (devops-dev):
    error: update failed

Resources:

Duration: 5m2s

```

**Comment by anilsakr** [comment]
Edit Ingress object,
kubectl edit ingress -n <namespace> <ingressname>
and remove 
`finalizers:
  - ingress.k8s.aws/resources`
  
  Then it will be deleted

**Comment by blaargh** [comment]
I am facing the same issue in Pulumi's destroy as @omidraha. Would be nice if there was a fix for this.
