### ISSUE TITLE
Static IPs for NLB

### ISSUE THREAD

**Issue by amalagaura** [kubernetes-sigs/aws-load-balancer-controller#1630]
Is it possible to specify a static IP for the NLB via annotations? 

It seems the subnets are automatically being specified for the NLB but is it possible or feasible to specify static IPs like we can do if we create an NLB ourselves? 

We need to whitelist some target IPs and our subnet ranges are too large.

**Comment by kishorj** [comment]
For internet-facing load balancer, you can specify the EIP allocations via the annotation `service.beta.kubernetes.io/aws-load-balancer-eip-allocations`. For internal load-balancers, we don't have a similar annotation currently.

Subnets are currently auto-discovered. We will be adding support for manually specifying subnets via annotation -  #1576 

As for the whitelist you mentioned, is it specific to your application?

**Comment by amalagaura** [comment]
Yes sorry I didn't mention that it is for the private IP space.

The whitelist is specific to our environment. We need to pass on our load balancer IPs for another firewall and are trying to avoid sending the entire subnet to be whitelisted.

**Comment by kishorj** [comment]
/kind feature
For the ability to specify static IP for internal load balancers.
