### ISSUE TITLE
group order explained

### ISSUE THREAD

**Issue by dza89** [kubernetes-sigs/aws-load-balancer-controller#1638]
In my situation I have around 20 ingresses grouped under 1 ALB.

When I read the docs it says

_You may not have duplicate group order explicitly defined for Ingresses within IngressGroup._

So do I have to set a unique number of any ingress? 
From my point of view it would make more sense to have one leading ingress and the rest follows?
Tbh I don't want to set a unique number on each ingress.

I'm just trying to understand how the current setup was thought of so I understand how to use it.

**Comment by M00nF1sh** [comment]
@dza89 
Hi, you don't need to set the group.order unless you need to.
By default, the order is based on the literal order of your Ingress's qualified name, i.e. `namespace/name`
So if you organize your Ingress rules properly. e.g. each Ingress owns a hostname, then you don't need to use this `group.order`  annotation

**Comment by dza89** [comment]
Got it
