### ISSUE TITLE
Controller will recreate a new ALB while previous deleted

### ISSUE THREAD

**Issue by harvychen** [kubernetes-sigs/aws-load-balancer-controller#1640]
Hi,
We created one EKS ingress which type is class is the alb, but somebody removed the ALB by mistake, but it was found one new ALB created again, is this an expected behavior?

Thanks
HGC

**Comment by kishorj** [comment]
Controller will recreate the ALB during next reconcile in this case - usually when the ingress resource gets modified, or the controller gets restarted. The new ALB will have a different DNS name. We don't recommend modifying resources managed by the controller from the console, since the changes could potentially be overwritten by the controller during next reconcile.

**Comment by harvychen** [comment]
So if keep the ALB steady and no changes to the attributes, even the controller restart, the ALB DNS name will keep, if I am wrong, please correct me.

**Comment by M00nF1sh** [comment]
@harvychen 
Yes, the ALB DNS name won't change as long as u don't change the Ingress attributes/annotations.
Most of the changes won't result in DNS change too. (for NLB, the only change results in ALB recreation is you change from internet-facing to internal, or vice-versa)

**Comment by harvychen** [comment]
Thanks for your quick answer.
Wow, the annotations change will cause recreation, so it'll be better to use the external DNS.

**Comment by kishorj** [comment]
@harvychen To clarify, DNS name will change only if the load balancer scheme gets modified via the annotation (from internet-facing to internal or vice versa) or as in your previous case the ALB gets deleted from the AWS console and the controller recreates it.

**Comment by M00nF1sh** [comment]
closing this since the behavior is clarified.
@harvychen feel free to create a new issue if you have further questions :D
