### ISSUE TITLE
new nodeports not discovered

### ISSUE THREAD

**Issue by fabianpeterg** [kubernetes-sigs/aws-load-balancer-controller#1651]
if you delete (kubectl delete service myservice) and redeploy the same service (kubectl apply -f myservice.yaml) it gets new nodeports, however this is not reflected in the target group so ALB will still use the old nodeports and mark the service as unhealthy. 
this was not an issue with the previous ingress controller.

**Comment by M00nF1sh** [comment]
i think we can solve this by add a service event handler for tgb
