### ISSUE TITLE
NLB IPv6 support

### ISSUE THREAD

**Issue by bootc** [kubernetes-sigs/aws-load-balancer-controller#1655]
Now that this is a thing: https://aws.amazon.com/about-aws/whats-new/2020/11/network-load-balancer-supports-ipv6/

Please add support for configuring NLB services with IPv6, including support for static IPv6 addresses.

**Comment by keperry** [comment]
Hi, I was looking at implementing this.  Any objections?  Is anyone else already working on this that you know of?

**Comment by kishorj** [comment]
Awesome, thanks.

**Comment by M00nF1sh** [comment]
closing this since the PR is merged and will be release in v2.1.0 soon :D
