### ISSUE TITLE
SSL policy being added to non SSL listeners in NLB

### ISSUE THREAD

**Issue by sidprak** [kubernetes-sigs/aws-load-balancer-controller#1661]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/26ce16545b507c1a6350eb004c9f9c8e09b312a1/pkg/service/nlb/builder.go#L436

Example: LB with 2 listeners, one SSL and one with plain HTTP. If SSL policy is set, the controller tries to apply the SSL policy to both listeners and fails because SSL policies cannot be applied to non SSL listeners.

Log error:
```
{"level":"error","ts":1605634388.9671187,"logger":"controller","msg":"Reconciler error","controller":"service","name":"istio-ingressgateway","namespace":"istio-system","error":"ValidationError: An SSL policy cannot be specifed for TCP listeners\n\tstatus code: 400, request id: 5f31bd94-6ab2-4bd6-bb41-237875bdf579"}
```

**Comment by kishorj** [comment]
I have the fix in the PR #1632
