### ISSUE TITLE
You are not authorized / logging

### ISSUE THREAD

**Issue by arohner** [kubernetes-sigs/aws-load-balancer-controller#1664]
I'm trying to set up the aws-load-balancer-controller, version 2.0.1, on EKS. I'm using IAM roles for service accounts. 

I think I have everything set up properly, but I'm getting:

```{"level":"error","ts":1605641661.3973227,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"beta","namespace":"default","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: c9047522-f587-4fbc-ad9f-ed1903ab81a0"}```

I guess I have two problems: 1) it's not working but more importantly, from the logs, I have no clue what the deployment is trying to do when it fails. I _think_ that's an AWS request, but I can't tell for sure. I've looked at cloudtrail, and no obvious events stick out. It would be great if the controller told me what failed, so I can debug my permissions.

**Comment by M00nF1sh** [comment]
closing this in favor of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1668
