### ISSUE TITLE
why my ingress always redirects to 404 

### ISSUE THREAD

**Issue by rajeevchukkapalli** [kubernetes-sigs/aws-load-balancer-controller#1671]
Alb got created and all the targets are in healthy ... Plz let me know if need any more details.

**Comment by kishorj** [comment]
what does your ingress spec look like?

**Comment by rajeevchukkapalli** [comment]
This is how my ingress looks @kishorj 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-xxxxx, subnet-yyyyy
    kubernetes.io/ingress.class: alb
  name: ingress-dev
  namespace: exp-ets-dev
spec:
  rules:
  - host: hostname.com
    http:
      paths:
      - backend:
          serviceName: exp1
          servicePort: 80
        path: /a
      - backend:
          serviceName: exp2
          servicePort: 80
        path: /b
      - backend:
          serviceName: exp3
          servicePort: 80
        path: /c
      - backend:
          serviceName: exp4
          servicePort: 80
        path: /d
      - backend:
          serviceName: exp5
          servicePort: 80
        path: /e

**Comment by kishorj** [comment]
@rajeevchukkapalli, you have specified a host in the rule spec, so they apply for that particular host only. Other requests will get a 404. Could you verify whether your clients are setup to target the correct host? 

If using curl, you can verify as follows
```
curl -v  http://<ALB DNS NAME>/a -H "Host: hostname.com"
```

**Comment by M00nF1sh** [comment]
@rajeevchukkapalli 
Hi, do we still have this issue? @kishorj 's response is clear :D

**Comment by rajeevchukkapalli** [comment]
@kishorj @M00nF1sh  
It has been working when I change the path from /a to /a/* for all the paths
