### ISSUE TITLE
Failed to parse stringMap annotation with equal sign

### ISSUE THREAD

**Issue by sidprak** [kubernetes-sigs/aws-load-balancer-controller#1673]
We use AWS tags to store some base64 encoded JSON metadata. Looks like this no longer works in version 2 of the LB controller where as it used to work in version 1. Is there a different way to escape the equal signs?

```
{"level":"error","ts":1605798917.9130397,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"vproxy","namespace":"default","error":"failed to parse stringMap annotation, alb.ingress.kubernetes.io/tags: foo=Zm9vCg==,another=tag"}

# With escaping.
{"level":"error","ts":1605798989.6451142,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"vproxy","namespace":"default","error":"failed to parse stringMap annotation, alb.ingress.kubernetes.io/tags: foo=Zm9vCg\\=\\=,another=tag"}
```

**Comment by kishorj** [comment]
Thanks for bringing this to our attention. The current v2 doesn't allow escaping the equal sign, we will fix this. In v1, there was no error, but the value would get truncated at the first equal sign.

**Comment by sidprak** [comment]
Thank you!
