### ISSUE TITLE
Controller logging issues

### ISSUE THREAD

**Issue by mitchya1** [kubernetes-sigs/aws-load-balancer-controller#1682]
Hello!

We've come across two strange issues with the controller logs. We're running on EKS with Kubernetes 1.16. We've verified these issues with both 2.0.0 and 2.0.1.

- The controller constantly logs this error for ingress resources without the `kubernetes.io/ingress.class` and `alb.ingress.kubernetes.io/group.name` annotations:

`groupName must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character`

This is more of an annoyance than an issue but shouldn't the controller ignore ingresses that it doesn't control?

- The controller logs frequently show an empty namespace,

This ingress is running in the `test-alb-ingress-group` namespace:

`{"level":"error","ts":1606170654.6983924,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"test-alb-ingress-group-kong-alb-group","namespace":"","error":"groupName must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character"}`

This ingress is running in the `master` namespace:

`{"level":"error","ts":1606170590.703021,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"master-kong-alb-group","namespace":"","error":"groupName must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character"}`

**Comment by M00nF1sh** [comment]
@mitchya1 
The error message will show up during reconcile for **every Ingress** if **any Ingress** have a malformed groupName.

This have been addressed in https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1676, and will be release in v2.1.0 soon 😄

**Comment by mitchya1** [comment]
@M00nF1sh 

Gotcha, thanks for clarifying!

Looking forward to v2.1.0!
