### ISSUE TITLE
missing `--default-tags` flag on v2

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [kubernetes-sigs/aws-load-balancer-controller#1683]
On v1, it was possible to set default tags for the ALBs created via the controller:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/9776d298fddc1bb7fe9245510467d2507580ec96/docs/guide/controller/config.md#resource-tags

On v2, there is no equivalent option:

```
{"level":"info","ts":1606184040.4219582,"msg":"version","GitVersion":"v2.0.1","GitCommit":"b28cc08c5451da98383b345592c4d8cd57da2afb","BuildDate":"2020-11-11T18:19:04+0000"}
unknown flag: --default-tags
```

**Comment by jtnz** [comment]
This is an important feature for us from a billing perspective.
