### ISSUE TITLE
Target Group recreation during the v1 → v2 migration

### ISSUE THREAD

**Issue by blakestoddard** [kubernetes-sigs/aws-load-balancer-controller#1684]
I'm really just seeking clarity here because I can't seem to figure out where it is happening in the code. When you migrate from v1 to v2, the TargetGroup is said to be recreated because of the port change from 1 to the numbered port (if you're using one), but I'm not seeing the port as being checked [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/deploy/elbv2/target_group_synthesizer.go#L161), [the target_group_synthesizer tests don't show a recreate for port changes](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/deploy/elbv2/target_group_synthesizer_test.go#L556), and the general TG port doesn't seem to be something that you can change via `ModifyTargetGroup` or `ModifyTargetGroupAttributes` per the `sdk-for-go` docs.

Can you point me to where that is happening so I can understand the flow there?

**Comment by M00nF1sh** [comment]
@blakestoddard 
In v2.0.0, the targetGroups will be recreated. but in v2.0.1, we fixed the behavior. (will publish the updated docs :D)
