### ISSUE TITLE
Support services without selectors

### ISSUE THREAD

**Issue by barric1** [kubernetes-sigs/aws-load-balancer-controller#1687]
The kubernetes service in default namespace is not backed up by pods. It’s a service without selectors (https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors), and points to the control plane ENIs. The AWS Load Balancer Controller is not able to register the IP addresses of the kubernetes endpoints to a target group using TargetGroupBinding resource because it always looks for the backing pods and fails before the elasticloadbalancing:RegisterTargets call is being made. Services without selectors are used for providing common names across environments, for example, for ElasticsearchService and other downstream dependencies. The kubernetes service is just the easiest one to confirm the current behavior. The use case for TargetGroupBinding and services without selectors would be to provide debugging, and possibly break glass access, to services which are only exposed in the VPC through VPC Endpoint Services that are backed by NLBs. The logic to reject services without selectors are here:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/a0f42a47bc5d2ae2bd02c77a2783304e0261a70e/pkg/backend/endpoint_resolver.go#L74
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/a0f42a47bc5d2ae2bd02c77a2783304e0261a70e/pkg/backend/endpoint_resolver.go#L89 

epAddr.TargetRef will be nil for services without selectors. These should not be excluded from the endpoints slice.

**Comment by M00nF1sh** [comment]
@barric1 
Technically it can be supported. currently we require pods to be exists so we can inject pod readinessGate's condition into pods.
Do you have other use case other than expose the x-eni?

**Comment by barric1** [comment]
That’s currently our only use case. I can foresee using services without selectors also to create common service discovery names for downstream services that use VPC Endpoints (instead of x-ENIs), because they make life easier when promoting from dev environment to test and further to whatnot. Sometimes it necessary to provide access to these, for example, from admin VPCs.

**Comment by jkroepke** [comment]
I would also like expose my VPC connected OpenSearch Service through this. I could create a dedicated as workaround, but to save some money, I would like to re-use an existing one
