### ISSUE TITLE
AWS CloudFront Dynamic Whole Site Delivery

### ISSUE THREAD

**Issue by omninonsense** [kubernetes-sigs/aws-load-balancer-controller#1692]
Reopening #1014 since @fejta-bot closed the original issue.

Original issue description by @gravypod:

> Hello everyone. I'm deploying a service in AWS EKS and I've been making a lot of use of this ingress controller. I was wondering: does this controller had plans to support the CloudFront caching distribution of ALBs?

**Comment by omninonsense** [comment]
This would be really useful in a scenario where we have dynamic content (such as an API service) and a SPA website.

Right now, the best way that I am aware of (and which is what we do where I work) is to build the SPA into a docker image with nginx, and serve it. We use a multi-stage build so the container is quite lightweight (the vanilla nginx container with the static files). I'm not sure if there's a way to distribute these through CloudFront.

It would be really useful to be able to leverage CloudFront's CDN!

We tried to use terraform, but some changes to the ingress controller seem to re-create the ALB, and it's not straightforward (read, it's more contrived/arcane than just using the nginx pod) to resolve the new ALB instance and then connect everything,. 

Also—this might be special to our company, though—what makes things worse is that our "TerraformOps" is separated from our "KubernetesOps" in the sense that developers can manage the k8s resources, but the terraform stuff is managed by people who're more comfortable with infrastructure/devops, but they're also two separate skill sets (IMO). So, it would be really convenient to manage this somehow through The ALB IC controller.

**Comment by omninonsense** [comment]
I'll add that I'm not too familiar with the CloudFront API (just a cursory glance at the documentation) and if it has any AWS-specific concepts beyond those that are common to all CDNs. So, I'm not sure what the API for something like this might look like from Kubernetes' perspective.

Would it make sense to add annotations and do something similar to the "custom actions" thing, or would this have to be a [CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) if doesn't make sense to piggyback on the annotations? If requires a CDR, then I guess it makes sense to have a separate controller...

**Comment by gravypod** [comment]
It's very unfortunate. I've completely moved off of AWS since needing this. Hopefully it gets resolved as multiple people would like this feature.

**Comment by dudicoco** [comment]
I don't believe this is an issue.
All you need to do is create a CNAME/alias record for the load balancer using `external-dns`, for example `test.example.com`, and create a distribution with a custom origin which points to the domain name `test.example.com`.

**Comment by mschueler** [comment]
It would be great to have an annotation that creates a CloudFront distro in front of the LB -- and everything "just works".  This is the pattern that AWS is recommending/pushing as well.

**Comment by gravypod** [comment]
> It would be great to have an annotation that creates a CloudFront distro in front of the LB -- and everything "just works". This is the pattern that AWS is recommending/pushing as well.

This also allows us to spend *more* money with just a single line of yaml. It's very much a win/win. This would also be great to integrate with WAF too to prevent DDoS

**Comment by omninonsense** [comment]
Hi @dudicoco

> I don't believe this is an issue.
> All you need to do is create a CNAME/alias record for the load balancer using `external-dns`, for example `test.example.com`, and create a distribution with a custom origin which points to the domain name `test.example.com`.

Would you mind giving an example of this setup? I'm not sure if I'm missing something obvious here? Or if writing a small example would end up being not-so-small, could you at least expand your explanation a bit more, since I feel like I'm lacking some context or knowledge of glue pieces to put these things together.

Thanks!

**Comment by dudicoco** [comment]
@omninonsense in order to configure your cloudfront distribution to use k8s ingress as origin with dynamic content, do the following:
1. Configure a custom origin within the distribution, the domain name should be the load balancer CNAME - `my-lb.example.com`.
2. Configure a cache behaviour which forwards all headers, query strings and cookies to the origin - this will disable caching and work with dynamic content.
3. Create a CNAME record for your load balancer - `my-lb.example.com`.
