### ISSUE TITLE
aws-load-balancer-controller installed through helm shows ImagePullBackOff in us-east-1

### ISSUE THREAD

**Issue by ckeragala** [kubernetes-sigs/aws-load-balancer-controller#1694]
I have my EKS cluster created in us-east-1 region. I'm trying to configure aws-load-balancer-controller in my EKS cluster but cannot pull the image for aws-load-balancer-controller from 602401143452.dkr.ecr.us-west-2.amazonaws.com
`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.1`

I already have `AmazonEC2ContainerRegistryReadOnly` policy attached to my worker node's instance profile.

```
 Warning  Failed     22s                kubelet, ip-xx-xx-xxx-xxx.ec2.internal  Error: ImagePullBackOff
  Normal   Pulling    12s (x2 over 24s)  kubelet, ip-xx-xx-xxx-xxx.ec2.internal  Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.1"
  Warning  Failed     12s (x2 over 23s)  kubelet, ip-xx-xx-xxx-xxx.ec2.internal  Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.1": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon/aws-load-balancer-controller/manifests/v2.0.1: no basic auth credentials
  Warning  Failed     12s (x2 over 23s)  kubelet, ip-xx-xx-xxx-xxx.ec2.internal  Error: ErrImagePull
```

**Comment by bozoli** [comment]
Hey @ckeragala
I'm facing the same issue. How did you fix it?

**Comment by kishorj** [comment]
@bozoli, you can refer to the release notes for the ECR images for your region, For the recent relese, https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.1.3.

**Comment by cepefernando** [comment]
I had the same issue, was fixed by updating the Image to use my correct region, somehow It was trying to use the us-west-1 instead of us-east-1 image.
