### ISSUE TITLE
Documentation for Required OIDC Secret has a typo

### ISSUE THREAD

**Issue by timothymahoney** [kubernetes-sigs/aws-load-balancer-controller#1700]
The secret that you're instructed to create has a typo, which causes the ingress controller to throw an error

https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/ingress/annotations/#auth-idp-oidc

In the data section, instead of clientID for the key it should be clientId with a lowercase "d"

**Comment by M00nF1sh** [comment]
@timothymahoney 
Hi, we changed it to be clientID for AWSLoadBalancerController(v2.0.0+). and clientId also works to be backward-compatible.

If you are using AWSALBIngressController, only `clientId` works. Our doc version for AWSALBIngressController is https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/ingress/annotation/.
