### ISSUE TITLE
Allow Reuse Of NLB when using NLB-IP For A Service

### ISSUE THREAD

**Issue by toneill818** [kubernetes-sigs/aws-load-balancer-controller#1707]
If we have multiple services that serve TCP traffic, using NLB-IP mode currently creates a new NLB for each service. It would be nice to be able to name an NLB and add to it like the new ALB ingress does. This would save a lot of money giving the option to reuse an NLB.

**Comment by M00nF1sh** [comment]
@toneill818 
NLB is different from ALB. It's solely port based. And services supports multiple ports, which closing maps to a nlb.
You should use a service with multiple port instead 😄

**Comment by toneill818** [comment]
@M00nF1sh I understand that, my use case is I have two separate services in the EKS cluster. One listens on TCP port 6651 and a separate service listens on TCP port 8091. When I add the nlb-ip annotation to these services, I would like to be able to group them to the same NLB instead of two separate NLB's being created. Since they listen on different ports NLB should be able to handle this.

**Comment by M00nF1sh** [comment]
@toneill818 
would it be possible to merge that two service into a single one? since it models a multi-port service better?

with the existing IngressGroup features, we have security concerns like who can create Ingresses join a IngressGroup, which we plan to address by enforce a namespaceSelector on IngressClass.
we don't have similar solution to use for service's case for now.

**Comment by khacminh** [comment]
@M00nF1sh 

Similar with #1545

**Comment by M00nF1sh** [comment]
@khacminh 
Yeah, i remember that. wondering whether this use case could be supported with a single service.

**Comment by toneill818** [comment]
@M00nF1sh I might be able to rewrite combine the charts and create a single service.

**Comment by almson** [comment]
@M00nF1sh @kishorj You've mentioned that currently NLB closely maps to Service+ClusterIP, but I have a need for the NLB to closely map to the NodePort concept.

My use-case requires launching a TCP-based application for each client, and it is better to allocate a port for each service than to allocate a DNS domain (ie, allocate an NLB). Allocating a domain is slower, more expensive, and clutters up DNS records.
