### ISSUE TITLE
what's difference between ingress-Nginx and this ?

### ISSUE THREAD

**Issue by jackie-JD** [kubernetes-sigs/aws-load-balancer-controller#1708]
I have a question that what's the difference between ingress-Nginx(https://github.com/kubernetes/ingress-nginx) and this project ? 
Thank you

**Comment by M00nF1sh** [comment]
@jackie-JD 
nginx ingress is using in-cluster nginx instances to do load balancing. that controller configure the nginx instances to do load balancing.
Pros:
    * More features available. 
Cons:
    * You need to manage the scale/security of the nginx instances.

this project is do load balancing using AWS managed ALB.
Pros:
    * managed by AWS(scale/security).
    * tightly integrated with AWS ecosystem, e.g. WAF/ACM/etc).
Cons:
    * features limited.

**Comment by jackie-JD** [comment]
And which is better ?

**Comment by M00nF1sh** [comment]
@jackie-JD 
I'd recommend ALB if you can implement your functionality on top of ALB's existing features.

**Comment by kishorj** [comment]
@jackie-JD closing the issue. Feel free to reopen or create a new one if you have further questions.
