### ISSUE TITLE
Kustomize support

### ISSUE THREAD

**Issue by solarchad** [kubernetes-sigs/aws-load-balancer-controller#1711]
Would you be open to a PR which adds support for Kustomize? This way we can consume this controller via both Helm and Kustomize (as a base).

**Comment by kishorj** [comment]
@solarchad could you elaborate more on the kustomize support you are referring to? We do have kustomize base to generate the manifests.

**Comment by solarchad** [comment]
@kishorj sorry, I must have missed it! I see the `kustomization.yaml` files in `./config/`. Is there an example of how this should be referenced?

For example:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git@github.com:kubernetes-sigs/aws-load-balancer-controller?configg/default?ref=v2.1.0
```

**Comment by solarchad** [comment]
Looks like this will work for me, closing. Thanks!
