### ISSUE TITLE
Unable to Support HTTP health checks with nlb-ip type load balancer

### ISSUE THREAD

**Issue by mseverin** [kubernetes-sigs/aws-load-balancer-controller#1714]
When using the following annotations to configure an NLB:

service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true, stickiness.type=source_ip
service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: ‘/test’
service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: ‘HTTP’
service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"

you get the following error from the AWS Load Balancer Controller

{"level":"error","ts":1607377231.8265452,"logger":"controller","msg":"Reconciler error","controller":"service","name":"echo-server","namespace":"default","error":"Unsupported health check protocol ‘HTTP’"}

**Comment by M00nF1sh** [comment]
@msau42 i believe it should be `"HTTP"` or  `'HTTP'` or simply `HTTP`, instead of `‘HTTP’`. similar issue for `‘/test’`.
`‘` is not `'` :D

**Comment by mseverin** [comment]
That was a bad copy paste I guess, still having the issue:

    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true, stickiness.type=source_ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/test"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"

Error:
{"level":"error","ts":1607385851.5126667,"logger":"controller","msg":"Reconciler error","controller":"service","name":"echo-server","namespace":"custom-tg","error":"InvalidConfigurationRequest: Custom health check timeouts are not supported for health checks for target groups with the TCP protocol\n\tstatus code: 400, request id: 48f023cd-13bc-44ec-acb4-2588c76d073e"}

I believe it is the order of operations in what is built.  If the Target Group healthcheck protocol is not TCP, the Target group needs to be created first.

**Comment by kishorj** [comment]
Try adding these annotations for HTTPS -
```
service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
```

For HTTP, set the timeout to 6

Target group will get re-created if you modify the health check protocol.

What region is your cluster currently in?

**Comment by kishorj** [comment]
Could you also get the model for the load balancer from the controller logs?

**Comment by mseverin** [comment]
Tried adding the extra annotations, no change...

Model Built by the controller:
{"level":"info","ts":1607391430.3511727,"logger":"controllers.service","msg":"successfully built model","model":"{\"id\":\"custom-tg/echo-server\",\"resources\":{\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/custom-tg/echo-server:80/status/targetGroupARN\"}}]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-customtg-echoserv-6adbf805bf\",\"type\":\"network\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-0f95740a8b562ebc3\"},{\"subnetID\":\"subnet-02adb8ef9371b5edc\"}],\"loadBalancerAttributes\":[{\"key\":\"access_logs.s3.enabled\",\"value\":\"false\"},{\"key\":\"access_logs.s3.bucket\",\"value\":\"\"},{\"key\":\"access_logs.s3.prefix\",\"value\":\"\"},{\"key\":\"load_balancing.cross_zone.enabled\",\"value\":\"true\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"custom-tg/echo-server:80\":{\"spec\":{\"name\":\"k8s-customtg-echoserv-4de613ac6c\",\"targetType\":\"ip\",\"port\":8080,\"protocol\":\"TCP\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/test\",\"intervalSeconds\":30,\"timeoutSeconds\":10,\"healthyThresholdCount\":3,\"unhealthyThresholdCount\":3},\"targetGroupAttributes\":[{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"custom-tg/echo-server:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-customtg-echoserv-4de613ac6c\",\"namespace\":\"custom-tg\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/custom-tg/echo-server:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"echo-server\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"192.168.32.0/19\"}},{\"ipBlock\":{\"cidr\":\"192.168.0.0/19\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]}}}}}}}}"}

**Comment by kishorj** [comment]
@mseverin, in the model you provided above, the healthCheck protocol is HTTP, timeout is 10. For HTTP timeout needs to be 6. Please specify the following annotation -
```
service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "6"
```

Currently it is not possible to modify healthcheck timeout for NLB target groups. It has to be 6 for HTTP, 10 for TCP and HTTPS.

**Comment by mseverin** [comment]
Thanks for all the help, with the timeout 6, I was able to instantiate as expected

**Comment by chancez** [comment]
I'm also noticing that if you specify `externalTrafficPolicy: Local` with `nlb-ip` mode, it creates health checks on the traffic port instead of the healthCheckNodePort.

**Comment by kishorj** [comment]
@chancez, for IP mode, the node port and the healthCheckNodePort gets ignored since NLB can target traffic directly to the pods. You can override the health check configurations via annotations, however, you need to make sure it is the pods that have the ports open, not the nodes.
