### ISSUE TITLE
PodReadinessGates with Helm

### ISSUE THREAD

**Issue by AirbornePorcine** [kubernetes-sigs/aws-load-balancer-controller#1718]
So I understand that, with the current implementation of PodReadinessGate injection, the service needs to be created before the deployment in order for the admission controller to properly add the gates to your pods (as it relies on the service definition).

The problem we've found with this method is when deploying a new ingress/service/deployment via helm3, the service/ingress are often created before the deployment. This tends to result in the first one or more pods in the deployment having no readiness gate at all.

Is there some way that someone knows of to work around this? Controlling order of installation in Helm doesn't appear to be an option, and we can't split our chart up. This behaviour was very surprising migrating from 1.1.8 to 2.1.0, especially since our old readinessgate definitions just don't work at all.

**Comment by M00nF1sh** [comment]
Hi @AirbornePorcine 

It's expected behavior. The purpose of pod readinessGate is to protect pod rolling deployment when used as Target.
If during pod creation, there is no Ingress/Service(or it haven't been initialized), there is nothing to protect, so it's not needed.

Please note that pod readinessGates can only be added during pod creation.

**Comment by AirbornePorcine** [comment]
But what happens when the service is created a few moments later, and all but 1-2 pods in your deployment have the readinessgate, and then you try to do a deployment? Does the missing readinessgate on those pods that started before the service not increase the chances of an outage? Maybe I'm understanding wrong here.

**Comment by M00nF1sh** [comment]
@AirbornePorcine 
During a deployment after everything is correctly setup, new pods will get the readinessGate and block deployments correctly.

The existing pods(without readinessgate) didn't increase the chance of outage.

**Comment by AirbornePorcine** [comment]
Thanks @M00nF1sh for the clarification!
