### ISSUE TITLE
Does EKS1.17 support  aws-load-balancer-controller?

### ISSUE THREAD

**Issue by anemptyair** [kubernetes-sigs/aws-load-balancer-controller#1720]
I always get the error in aws-load-balancer-controller pod.
Already add tags for subnets via https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/subnet_discovery/

{"level":"error","ts":1607579134.4313915,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"hpbp-test-ingress-grpc","namespace":"istio-system","error":"couldn't auto-discover subnets: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}

**Comment by kishorj** [comment]
EKS 1.17 supports aws-load-balancer-controller. The error indicates that the IAM roles are not setup correctly in your case. The [installation guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/) provides the steps to setup the IAM permissions.

You can also refer to for further details https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

**Comment by anemptyair** [comment]
Thank u
