### ISSUE TITLE
Alb controller stops working if a valid ingress is pointed to ClusterIP service

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [kubernetes-sigs/aws-load-balancer-controller#1723]
Version: 2.1.0
Installed-by: helm

ALB controller works for me when i deploy a totally new app/ingress in the environment. However, it does not if I delete the same app and reinstalled it as-is.
Ing is stuck without a Load Balancer ARN and there is no new TargetGroupBinding created for the app when deployed second time.

Couple of more points:
1. While deleting the app, it got stuck due to finalizer on the ing. I manually deleted the finalizer and then ingress. it deleted the app and its namespace completely.

2. Model present Controller Pod Logs shows deleted resources TargetGroup and TargetGroupBindings even after creating the controller pod.

3. I am using ArgoCd for deployment

**Comment by abhinavkhanna-sf** [comment]
Found the issue. it is not related to app recreation. 
One more app was deployed in a different namespace on the same cluster using same LB with bad ingress/service resource values. 
It was blocking whole AWS LB Controller Model to do a reconcile. This was the error that blocked the global reconcile.
`
{"level":"error","ts":1607601360.880526,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"lb.group","namespace":"","error":"InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n"}
`

it may be a good idea just to block that ingress sync and continue with good values

**Comment by kishorj** [comment]
@abhinavkhanna-sf The backend service referred by your ingress in of type ClusterIP, this is the cause of the reconciler error. Your ALB is configured to use instance targets, so the service type should be NodePort.

**Comment by abhinavkhanna-sf** [comment]
Thanks @kishorj thats what i figured. However, the issue was broader. With this bad ingress/service deployed, it was taking down whole controller reconciliation. ALB Controller stops working if i I point an alb annotated ingress ClusterIP service

**Comment by kishorj** [comment]
@abhinavkhanna-sf did the controller recover once you modified the service type? Were there any other error messages in the log? did you modify the default concurrent reconciles?

**Comment by abhinavkhanna-sf** [comment]
@kishorj i did not notice any other  error. Controller recovered once the bad service was removed.  No other modifications done.

**Comment by kishorj** [comment]
@abhinavkhanna-sf, I'm closing the issue based on your last comment. If problem persists, feel free to reopen or file a new issue.
