### ISSUE TITLE
How does traffic flow into a pod?

### ISSUE THREAD

**Issue by nsubrahm-aws** [kubernetes-sigs/aws-load-balancer-controller#1732]
In my `Deployment`, I have used a `nodeSelector` such that the pod will be placed in an EC2 instance that is in a private subnet. This means, the EC2 instances - where the `Pod` gets scheduled - will not have a public IP address. My `Ingress` object uses `target-type` as `ip`. When the ALB is provisioned, I noticed that the AZs points to _public_ subnets only.  However, the registered target is the `Pod` IP address, where the `Pod` was scheduled in a EC2 instance in a private subnet.

1. So, how does the traffic flow from ALB into a public subnet and still reach the `Pod` IP address, where the `Pod` was scheduled in a EC2 instance in a private subnet.
2. Shouldn't the registered 'target' be `Service` DNS; typically, `servicename.cluster.local.svc`, etc. - so that `Service` can front-end the scaled out (or scaled in) pods?

**Comment by kishorj** [comment]
@nsubrahm-aws check if this document helps you https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/how-it-works/

In case of IP mode, ALB forwards the traffic directly to the pod, without going through the instance. The target group entries in this case should contain the IP address of your application pods. It is not clear to me what you mean by "Target group points to public subnets only".

**Comment by nsubrahm-aws** [comment]
> In case of IP mode, ALB forwards the traffic directly to the pod, without going through the instance. 
This is not clear; since the pod is running on an instance, what does it mean when you say _the traffic directly to the pod, without going through the instance. _ ?

Sorry, the Target Group should read AZs - I have edited the question.

I noticed that, the subnets of the AZs of the provisioned ALB are all public subnet. In my case, the pod is scheduled in a private subnet. So, my question is, how did the traffic come into the pod, scheduled on a private subnet, from the ALB whose AZs point to public subnets only?

**Comment by M00nF1sh** [comment]
@nsubrahm-aws 
1. When you creating a public ALB, the controller provisions the ALB with public subnets and ALB will create one ENI in each of the configured public subnet, let's call it ALB-ENI.
2. When you use aws-vpc-eni, each pod's IP is actually a secondary IP on ENI attached to your node(may not be the primary ENI).
3. When client traffic arrives at ALB, ALB will use these ALB-ENIs in your public subnet to send traffic to the ENI for your pod in private subnet.

**Comment by kishorj** [comment]
@nsubrahm-aws, do you still have further concerns on this matter? I'm closing this issue, feel free to reopen or file a new one if you still have questions/concerns.
