### ISSUE TITLE
docker pull unauthorized

### ISSUE THREAD

**Issue by v4mpir0ck** [kubernetes-sigs/aws-load-balancer-controller#1736]
Hi,
im getting problems pulling the image, right after deploying the operator with helm in the namespace kube-system, 
`  Normal   Pulling         46m (x4 over 48m)     kubelet            Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0"
  Warning  Failed          46m (x4 over 48m)     kubelet            Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0": rpc error: code = Unknown desc= Error reading manifest v2.1.0 in 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller: unauthorized: authentication required
  Warning  Failed          46m (x4 over 48m)     kubelet            Error: ErrImagePull
  Warning  Failed          13m (x150 over 48m)   kubelet            Error: ImagePullBackOff`

we are using the aws credentials passed though environment variables, could it be the problem?

thank you

**Comment by kishorj** [comment]
@v4mpir0ck Check if your node instance role grants ECR access permissions.

**Comment by M00nF1sh** [comment]
@v4mpir0ck 
Does this issue still exists? If so, please reopen or create a new issue.

**Comment by emmaroberts-nbs** [comment]
I get this issue when trying to deploy the helm chart in the eu-west-2 region.

My instance profile for the nodes have ecr readonly access, the following policy is attached to the role I'm using: AmazonEC2ContainerRegistryReadOnly
