### ISSUE TITLE
Can't be deployed

### ISSUE THREAD

**Issue by malcolm061990** [kubernetes-sigs/aws-load-balancer-controller#1737]
Hi. I am trying to deploy this LB using [official guide](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html)
My versions:
```sh
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

Deploying (previous steps from guide are completed):
```sh
# this output is from the second applying of this yaml to get output for this GitHub issue :)
$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager-legacy.yaml
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io configured
namespace/cert-manager unchanged
serviceaccount/cert-manager-cainjector unchanged
serviceaccount/cert-manager unchanged
serviceaccount/cert-manager-webhook unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-view unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-edit unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim unchanged
role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection unchanged
role.rbac.authorization.k8s.io/cert-manager:leaderelection unchanged
role.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving unchanged
rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection unchanged
rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection configured
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving configured
service/cert-manager unchanged
service/cert-manager-webhook unchanged
deployment.apps/cert-manager-cainjector unchanged
deployment.apps/cert-manager unchanged
deployment.apps/cert-manager-webhook unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured

# edited --cluster-name to my clustername and deploy
# commented kind: ServiceAccount in v2_1_0_full.yaml
$ kubectl apply -f v2_1_0_full.yaml
customresourcedefinition.apiextensions.k8s.io/targetgroupbindings.elbv2.k8s.aws configured
mutatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook configured
role.rbac.authorization.k8s.io/aws-load-balancer-controller-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/aws-load-balancer-controller-role configured
rolebinding.rbac.authorization.k8s.io/aws-load-balancer-controller-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/aws-load-balancer-controller-rolebinding unchanged
service/aws-load-balancer-webhook-service unchanged
deployment.apps/aws-load-balancer-controller unchanged
validatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook configured
unable to recognize "v2_1_0_full.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
unable to recognize "v2_1_0_full.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"

# the deployment isn't ready
kubectl get deployment -n kube-system aws-load-balancer-controller
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
aws-load-balancer-controller   0/1     1            0           36m

# describe pod
kubectl -n kube-system describe po aws-load-balancer-controller-7f458fd5d7-bhmsq
Name:           aws-load-balancer-controller-7f458fd5d7-bhmsq
Namespace:      kube-system
...
Events:
  Type     Reason       Age                   From                                 Message
  ----     ------       ----                  ----                                 -------
  Normal   Scheduled    36m                   default-scheduler                    Successfully assigned kube-system/aws-load-balancer-controller-7f458fd5d7-bhmsq to ip-10-20-6-49.ec2.internal
  Warning  FailedMount  6m22s (x23 over 36m)  kubelet, ip-10-20-6-49.ec2.internal  MountVolume.SetUp failed for volume "cert" : secret "aws-load-balancer-webhook-tls" not found
  Warning  FailedMount  61s (x16 over 34m)    kubelet, ip-10-20-6-49.ec2.internal  Unable to mount volumes for pod "aws-load-balancer-controller-7f458fd5d7-bhmsq_kube-system(1b23b20d-05ac-403f-af15-951e37f3822a)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"aws-load-balancer-controller-7f458fd5d7-bhmsq". list of unmounted volumes=[cert]. list of unattached volumes=[aws-iam-token cert aws-load-balancer-controller-token-dw4cl]
```

Some issues with CRDs "Certificate" and "Issuer"... Please, help.

**Comment by evagonz** [comment]
I ran into the same thing earlier, I think the formatting on [this page](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/deploy/installation.md) is a bit messed up.

Basically, I think you didn't install the cert-manager, as detailed

```
=== "Via YAML manifests" ### Install cert-manager - For Kubernetes 1.16+: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml - For Kubernetes <1.16: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager-legacy.yaml
```

specifically, the correct one for your version of kubernetes. Do that, and it'll take care of those specific errors.

**Comment by kishorj** [comment]
@malcolm061990 It looks like you already had some version of cert-manager installed when you applied the cert-manager manifest. You need to make sure the supported version is installed in your cluster.

The `unable to recognize "v2_1_0_full.yaml": no matches...` means that the cert-manager will not create a secret resource for the controller.

You can try installing the helm chart, it doesn't have a dependency on the cert manager.

**Comment by Larry-JJ** [comment]
Hi @kishorj, are we able to install AWS LB Controller without cert-manager via kubectl instead of helm? As we are using internal ALB which not requires a certificate, we would like to keep it lightweight.

**Comment by Larry-JJ** [comment]
Hi @kishorj, you mentioned helm chart doesn't have a dependency on the cert manager. may I know is there any guide to install AWS LB Controller without cert-manager via kubectl instead of helm? As we are using internal ALB which not requires a certificate, we would like to keep it lightweight.

**Comment by kishorj** [comment]
@Larry-JJ, the certificate is not for the ALB, but for the mutating and validating webhooks used by the controller. It is a one time configuration. Helm generates the certificate/secrets during chart installation.

If you want to use kubectl instead of helm, you will have to modify your manifests accordingly. Here are the tentative steps - 
1. Remove the certificate and Issuer resources from the manifest
2. Add a resource of kind Secret with the name`aws-load-balancer-webhook-tls`, kind `Secret`, type `kubernetes.io/tls
`
3. Modify the MutatingWebhookConfiguration and ValidatingWebhookConfiguration. Here you put in the actual value for caBundle. Replace the `Cg==` in the caBundle with the value of the `ca.crt` from the secret in step 2.

For step 2, I find it helpful to run the `helm template` command on the eks/aws-load-balancer-controller chart and copy the contents. If you use the manifests from this github repo, make sure the secret name is correct.

**Comment by Larry-JJ** [comment]
@kishorj Thanks very much, this makes me better understand how it works. I will try it soon.

**Comment by malcolm061990** [comment]
> I ran into the same thing earlier, I think the formatting on [this page](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/deploy/installation.md) is a bit messed up.
> 
> Basically, I think you didn't install the cert-manager, as detailed
> 
> ```
> === "Via YAML manifests" ### Install cert-manager - For Kubernetes 1.16+: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml - For Kubernetes <1.16: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager-legacy.yaml
> ```
> 
> specifically, the correct one for your version of kubernetes. Do that, and it'll take care of those specific errors.

I launched the command you mentioned and showed it in my first message:
```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager-legacy.yaml
```

> @malcolm061990 It looks like you already had some version of cert-manager installed when you applied the cert-manager manifest. You need to make sure the supported version is installed in your cluster.
> 
> The `unable to recognize "v2_1_0_full.yaml": no matches...` means that the cert-manager will not create a secret resource for the controller.
> 
> You can try installing the helm chart, it doesn't have a dependency on the cert manager.

I didn't have any cert-managers. Some months ago I installed cert-manager in cert-manager namespace (by default). But I deleted that namespace before installing the new one.

**Solution**:
I changed the apiVersion for "kind: Certificate" and "kind: Issuer" from cert-manager.io/v1alpha2 to cert-manager.io/v1 in v2_1_0_full.yaml, applied changed file and it works:
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
...
---
apiVersion: cert-manager.io/v1
kind: Issuer
...
```

Thank you, guys, for your support 👍 
And may be this changes must be done in https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/v2_1_0_full.yaml. If not, please, close this issue

**Comment by M00nF1sh** [comment]
@malcolm061990 

We'll add a YAML/scripts without cert-manager dependency. 

We don't intend to support multiple cert-manager versions and 1.15 will be deprecated soon, so closing this issue.
