### ISSUE TITLE
IP whitelisting aws-load-balancer-controller

### ISSUE THREAD

**Issue by sandeepnanda2** [kubernetes-sigs/aws-load-balancer-controller#1738]
This is my working ingress for my app, please suggest how can I allow my app to access from certain IPs or cidrs.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingressName"
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/group.name: internal-apps-dev
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:{ownerID}:certificate/certificateID-XXXX-XXXXX-XXXXX'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}, {"HTTP": 8080}, {"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  namespace: "myNamespace"
  labels:
    app: "MyApp"
spec:
  rules:
  - host: "uat-myapp.domain.com"
    http:
      paths:
      - path: 
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - path: 
        backend:
          serviceName: "servicemyapp"
          servicePort: 80

**Comment by kishorj** [comment]
@sandeepnanda2 you can use the annotation `alb.ingress.kubernetes.io/inbound-cidrs` to specify the CIDRS that are allowed to access the load balancer.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#inbound-cidrs

**Comment by M00nF1sh** [comment]
seems this issue is addressed per the doc.

**Comment by cloudlady911** [comment]
I have a question related to this.  I am using a shared ALB.  I have 175 apps using the same alb.  I would like to be able to whitelist certain CIDR's to certain apps. How can I use this setting?  For instance, AppA should be accessable from 123.345.23.45/24 and AppB should be accessible from 456.567.89.76/24
