### ISSUE TITLE
how to merge listener routing rules on same group.name ingress objects to get weighted routing

### ISSUE THREAD

**Issue by orong-pp** [kubernetes-sigs/aws-load-balancer-controller#1742]
I want to deploy microservices each with it's own ingress object, but using the same 
alb.ingress.kubernetes.io/group.name annotation, to have the ingress rules merge under the same ALB

this works fine as long as I'm using different a hostname or HTTP header value.
but when I want to have 2 ingress rules with weight forwarding rules, I want the merging process to put them together
under the same listener rule, but I get 2 different rules that in practice only the first rule get evaluated (since the hostname and header value are the same for both rules.

is there a way to hint to aws-load-balancer-controller to merge the 2 weight routing rules to the same listener rule (on an array of target groups) instead of creating 2 different rules

following is a minimal example with 1 namespace, 2 deployments, 2 services, 2 ingress that demonstrates the issue

note that there are 2 separate rules on the listener rules, instead of 1 rule with 2 weighted forwarding target groups

[ingress.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/5721669/ingress.txt)

**Comment by M00nF1sh** [comment]
@orong-pp 
You need to specify the weighted rule in a single Ingress. currently each Ingress rule will result in a ALB rule.

I can see this can be an issue where the weighted backend services are from different namespaces, is it the reason that you want to create two ingress instead of one?

**Comment by orong-pp** [comment]
@M00nF1sh 
thanks for the reply
the reason to make 2 ingress objects is - I want to achieve a microservices deployment behavior,
where each microservice has its own ingress object.
These microservices should implement a canary deployment. 

For example, The first one is the current version with weight 90 and the second is the new release with weight 10. When the second one is deployed, a single listener rule should be created that routes traffic to both microservices according to their weights

I hope I made my usecase clear.
I prefer to handle this with the helm / k8s charts and not on terraform since TF is not run as regularly as helm deployments.
I am looking for a solution in the direction service mesh, but hope to find a simpler solution with ALB ingress rules that will be easier to implement and require less adaptations to my running environment
