### ISSUE TITLE
Reuse of existing ALBs after version upgrade

### ISSUE THREAD

**Issue by mberkow** [kubernetes-sigs/aws-load-balancer-controller#1743]
Issue: After migration from alb-ingress-controller to aws-load-balancer-controller new ALBs are created instead of managing the existing ALBs

Expected behavior: When migration between versions existing ALBs would continue to be updated.

Observed behavior: A new ALB with a different name is created and updates to the ingress/service resources are only reflected in the new ALB.

Steps to reproduce:
1) deploy alb-ingress-controller v1.1.9
2) deploy test web application with deployment, service and ingress resources
3) follow migration steps for aws-load-balancer-controller
4) change port configuration for the test web application

**Comment by M00nF1sh** [comment]
@mberkow 
would you help share your service and ingress specs? it should be reused.
BTW, if possible, would you share the AWS tags on aws console for the old ALB and new ALB?

**Comment by mberkow** [comment]
@M00nF1sh 
Sorry for the delay in replying. Checking the AWS Tags I realized I had a mistake in one of the options and the tags did not match. Closing this.
