### ISSUE TITLE
nlb instance support

### ISSUE THREAD

**Issue by jurgenweber** [kubernetes-sigs/aws-load-balancer-controller#1744]
As per this; https://github.com/kubernetes/kubernetes/issues/57250#issuecomment-723390608

Apparently this project is taking over the NLB instance support, for those that need proxy-protocol v2 on + NLB and are not on k8s 1.20 (which is a [prerequisite for nlb-ip](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/service/nlb_ip_mode/)). We are on eks, so 1.18.

Any status update on this? Are you aware? :)

**Comment by kishorj** [comment]
@jurgenweber, It is in our roadmap, we are working on it.

**Comment by jurgenweber** [comment]
since you answered this question; https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1745 meaning I don't specifically need this but there are people out there going from those threads that are crying out for it. It was hard to find good information so hopefully this helps those whom are searching.

**Comment by indrekj** [comment]
Any idea when v2.2 will be released?

**Comment by hanjh0814** [comment]
Any updates with regards to this issue?

**Comment by kishorj** [comment]
@hanjh0814, v2.2 is already released. Please refer to the release notes at - https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0.
