### ISSUE TITLE
NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by v1nc3nt27** [kubernetes-sigs/aws-load-balancer-controller#1747]
Hey there,

I'm running a self managed (kubeadm) cluster on EC2 instances and running into some problems with installing the load balancer controller. I've created the [IAM policy manually](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller#setup-iam-manually) and added it to my worker node IAM role. The LB controller was installed with the helm chart. I first encountered the problem that the EC2Metadata couldn't be read so I added `vpcId` and `region` parameters and the controller came up fine. However, when deploying the game-2048 example from [here](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html), the controller gives me the following status:

`{"level":"error","ts":1609246673.333103,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}`

Hence, I've added the annotation `alb.ingress.kubernetes.io/subnets:` with my public subnets to the ingress controller. The error changes to:

`{"level":"error","ts":1609250899.5429265,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}`

It's obvious that the auto discovery of meta data is not working, but I don't see why and also I don't really understand what is missing. Is there anything I've overlooked?

Here is also the initial output of the controller logs:

> {"level":"info","ts":1609243280.836659,"msg":"version","GitVersion":"v2.1.0","GitCommit":"f95827224a66cae20a1af999d8ef1d46ec462547","BuildDate":"2020-12-01T19:27:50+0000"}
> {"level":"info","ts":1609243280.8867862,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
> {"level":"info","ts":1609243280.8893495,"logger":"setup","msg":"adding health check for controller"}
> {"level":"info","ts":1609243280.889599,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
> {"level":"info","ts":1609243280.8896723,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
> {"level":"info","ts":1609243280.8897293,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
> {"level":"info","ts":1609243280.8903737,"logger":"setup","msg":"starting podInfo repo"}
> {"level":"info","ts":1609243282.8905973,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
> I1229 12:01:22.890585       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/aws-load-balancer-controller-leader...
> I1229 12:01:22.913199       1 leaderelection.go:252] successfully acquired lease kube-system/aws-load-balancer-controller-leader
> {"level":"info","ts":1609243282.990953,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
> {"level":"info","ts":1609243282.9910135,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243282.9910777,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243282.9911292,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243282.991307,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0002e75e0"}
> {"level":"info","ts":1609243282.9913447,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc0002e7630"}
> {"level":"info","ts":1609243282.9913597,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243282.9913778,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243282.9914043,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243282.9917204,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
> {"level":"info","ts":1609243282.9918613,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
> {"level":"info","ts":1609243282.9919984,"logger":"controller","msg":"Starting EventSource","controller":"service","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243282.992043,"logger":"controller","msg":"Starting Controller","controller":"service"}
> {"level":"info","ts":1609243282.992421,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
> {"level":"info","ts":1609243283.0914352,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
> {"level":"info","ts":1609243283.0918407,"logger":"controller","msg":"Starting Controller","controller":"ingress"}
> {"level":"info","ts":1609243283.0920892,"logger":"controller","msg":"Starting workers","controller":"service","worker count":3}
> {"level":"info","ts":1609243283.191922,"logger":"controller","msg":"Starting Controller","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding"}
> {"level":"info","ts":1609243283.1919682,"logger":"controller","msg":"Starting workers","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","worker count":3}
> {"level":"info","ts":1609243283.1922286,"logger":"controller","msg":"Starting workers","controller":"ingress","worker count":3}

**Comment by M00nF1sh** [comment]
@v1nc3nt27 
Hi, the controller needs IAM permission to work on-behalf of you(e.g. create ALB).
Since you are using a self-managed cluster, this left you a few options:
1. grant IAM permission to node, and allow container to access EC2Metadata. 
2. use iam per pod solutions like kube2iam.
 
Seems access to EC2Metadata was blocked and you didn't use any other solutions to grant iam permission to the pod.
Did you intentionally blocked EC2Metadata? If not, please check below article:
1. https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/
2. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
In short, there are two IMDS(EC2Metadata version), where IMDSv2 by default can not be accessed from container. You might have disabled IMDSv1 and didn't set a proper hop-limit for IMDSv2.

**Comment by v1nc3nt27** [comment]
@M00nF1sh Thanks a lot for your suggestion. In fact, I've set IMDSv2-only and hop limit to 1. Does this mean I cannot use IMDSv2 at all?

Anyhow, I restored IMDSv1 on the worker instance and the error of the controller logs changed to 

`{"level":"error","ts":1609323024.1760008,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"echoserver","namespace":"echoserver","error":"RequestError: send request failed\ncaused by: Post \"https://ec2.eu-central-1.amazonaws.com/\": dial tcp: i/o timeout"}`

So this definitely helped with the previous error and metadata seems available now (so perhaps I can remove the subnet annotation in the ingress and the region/vpc info when setting up the controller). 
However, there is some connection error now and I don't really understand what the controller is doing at this point. The worker and master nodes are both in private subnets and communicate through an internet facing network load balancer. I've opened up [all ports required by kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports). Do I need to open an extra port for this communication?

Thanks!

**Comment by M00nF1sh** [comment]
hi, If you want to use imds-v2 only, you need to set the hop-limit to at least 2. so that containers can access IMDS.
As for the new issue, the controller need to access EC2 service(ec2.eu-central-1.amazonaws.com) to work on behalf of you, so i don't think there are any issue in the controller binary itself. 
Have you tried exec into the controller and verify you have access to ec2.eu-central-1.amazonaws.com? If not, it could be caused by it don't have connectivity to your coreDNS pods or you didn't setup privateLink/NatGateway/InternetGateway in your vpc(depends on your setup).

**Comment by v1nc3nt27** [comment]
@M00nF1sh Hi, so you were actually right, the pods had no internet access. As it turns out, my CNI (flannel) needs UDP Port 8472 to be open. After that, I didn't have to specify the subnets in the Ingress annotations anymore and AWS load balancer controller is running fine. I think all issues are solved then, thanks again!
