### ISSUE TITLE
Control loop does not reconcile NLB SSL Ports

### ISSUE THREAD

**Issue by colearendt** [kubernetes-sigs/aws-load-balancer-controller#1748]
I have an NLB defined via annotations:

```
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/id"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

Then I updated to:
```
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443,8443'
```

However, after leaving things this way for a while (a day), the ALB load balancer controller still has not set port 8443 to use the ssl certificate. I have confirmed that deleting and creating a new NLB from scratch will attach the SSL certificate to both ports.

Using `    Image:       602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0`

**Comment by kishorj** [comment]
@colearendt, do you see any errors in the controller logs? What does your service spec look like? Also, could you share the model generated for your service after the modification?

I tried using a similar configuration, but wasn't able to reproduce the issue.

**Comment by kishorj** [comment]
@colearendt, based on the annotation `service.beta.kubernetes.io/aws-load-balancer-type` value being `nlb`, the NLB gets reconciled by the k8s in-tree controller, not this external load balancer controller. The in-tree controller has limitations with modifying the listener protocol after service gets created. 

This controller does not have such limitations. The upcoming v2.2.0 will support instance mode NLB.

I'm closing the issue for now. Let us know if you have further concerns/questions.

**Comment by colearendt** [comment]
Oops. Sorry for missing the prior notification / request for more info! Still happy to provide that if it would be helpful. I don't completely follow the "in-tree controller" vs. "external load balancer controller." Is there a doc on how to ensure that I am using the aws-load-balancer-controller? Or to tell the difference between the two? I have to admit I haven't been enlightened by the docs, unfortunately

**Comment by colearendt** [comment]
Amazing clarification, thank you!! That's hilarious - I had deployed the aws-load-balancer-controller and then used the built-in 😄 Thanks so much for your help!
