### ISSUE TITLE
auto discovring webacl

### ISSUE THREAD

**Issue by naimiaziz** [kubernetes-sigs/aws-load-balancer-controller#1751]
Hello,

First of all I would like to thank you for you amazing work, I'm using AWS LoadBalancer Controller which  gladly respond to all my need except one:

there is a way to auto discover the WebAcl arn available in the region without mentioning it in the ingress annotation and thanks.

**Comment by M00nF1sh** [comment]
@naimiaziz 
technically we can support it by checking tags on waf rules, but it will become inefficient as we have to try check `waf` rules on every reconcile even for users not using waf. (unless we do things like `alb.ingress.kubernetes.io/wafv2-acl-arn: auto`)

Alternatively, we'll providing support for configuration via IngressClass's parameter soon, which allow you to define configurations via CRD per IngressClass. So you only need to define waf once, and configure all your Ingress to use same IngressClass(or configure a default IngressClass per cluster). **Will this suit your need as well without auto-discovery waf**?

**Comment by naimiaziz** [comment]
@M00nF1sh thank you for your response I've wanted to use `alb.ingress.kubernetes.io/wafv2-acl-arn: auto` but unfortunately I had this error :`InvalidParameter: 1 validation error(s) found.\n- minimum field size of 20, AssociateWebACLInput.WebACLArn.\n"}`

and for the feature that you will propose it doesn't suits my need because I want to automate the deployment full stack including aws-loadbalancer-controller once I did provision the infrastructure via Terraform

**Comment by M00nF1sh** [comment]
@naimiaziz 
The `alb.ingress.kubernetes.io/wafv2-acl-arn: auto` is not supported for now.
we'll discuss in roadmaps meeting whether this feature should be included.

In the meantime, what's the UX you expect for this feature? how should the controller know whether `WAF-XXX` should be attached to `LoadBalancer-YYY`

**Comment by hemanthkini** [comment]
> In the meantime, what's the UX you expect for this feature? how should the controller know whether WAF-XXX should be attached to LoadBalancer-YYY?

One option here (although slightly different from the OP's request) would be to specify the ACL ARN to the controller, and have the controller associate that ACL with all of the ALB instances it creates. Put differently, it would be ideal (at least for something I'm working on) if we could specify `alb.ingress.kubernetes.io/wafv2-acl-arn: <arn>` to the controller, and have that annotation be merged with the other annotations on our Ingress object.

**Comment by dudicoco** [comment]
@M00nF1sh I like the suggestion of `alb.ingress.kubernetes.io/wafv2-acl-arn: auto`, or alternatively, as a flag when starting up the controller.

I don't think the WAF arn should be hardcoded in any configuration (annotations/IngressClass/controller) because it's a unique ARN similar to a VPC/subnet ID, not something you want to hardcode but rather auto discover.

Are there any plans on implementing this?

Thanks
