### ISSUE TITLE
Is it required that healthcheck-interval-seconds should be bigger than healthcheck-timeout-seconds

### ISSUE THREAD

**Issue by jianghuiyou** [kubernetes-sigs/aws-load-balancer-controller#1754]
In my k8s usage, I use the conditionType of readinessGates in K8S deployment.yaml. If I set the healthcheck-interval-seconds equals to healthcheck-timeout-seconds, such as both are 5 seconds,  the pod can't startup successfully with `ReadinessGatesNotReady` Error, as the pic below shows. But if I set healthcheck-interval-seconds bigger, like healthcheck-interval-seconds  is 10 seconds,  healthcheck-timeout-seconds is 4 seconds, it'll be ok. Maybe this is a kinda stupid question, but why did this happen? And when the alb health check start to do this health check, right after pod readiness probe ready? 
![image](https://user-images.githubusercontent.com/6174908/103661874-3197d200-4faa-11eb-8856-d2a981c4ec6f.png)

**Comment by M00nF1sh** [comment]
@jianghuiyou 
`healthcheck-interval-seconds` and `healthcheck-timeout-seconds` can be set independently. 
However, for ALB, `healthcheck-interval-seconds` must be within [5-300], and `healthcheck-timeout-seconds`  must be within [2-120]. 
Did you set `healthcheck-interval-seconds` to a lower value than 5? otherwise, it should work.
Also, if there any errors from the controller's logs?

**Comment by jianghuiyou** [comment]
I met the issue when I set  both `healthcheck-interval-seconds` and `healthcheck-timeout-seconds` are 5 seconds~ Not lower than 5. And I only changed them to 10s and 4s, it worked, but it's really wierd~ 

I don't know the errors logs from the controller you said, could you give me some hint how to get them? But as a dev, I don't have the permission to our company's k8s cluster, only can use `kubectl` to do some read-only operations~ like `kubectl desc`

**Comment by jianghuiyou** [comment]
after asking devops in my company, I got this error message from alb-controller-logs `kubebuilder/controller "msg"="Reconciler error" "error"="failed to build SG association config: healthcheck timeout must be less than healthcheck interval. Timeout was: 5. Interval was 5"  "controller"="alb-ingress-controller" "request"={"Namespace":"service-name","Name":"service-name-perf-ingress"}`, which requires `healthcheck timeout must be less than healthcheck interval`. The root cause is clear now, it's a requirement from our company.  Thanks a lot~ You could close this issue anytime you want
