### ISSUE TITLE
--restrict-scheme and --restrict-scheme-namespace flags are missing from v2 versions

### ISSUE THREAD

**Issue by csgaiger-hiya** [kubernetes-sigs/aws-load-balancer-controller#1757]
As per this document: [https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/upgrade/migrate_v1_v2/](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/upgrade/migrate_v1_v2/)
the AWSLoadBalancerController(v2.0.1) is backwards-compatible with AWSALBIngressController(>=v1.1.3), but actually it is not exactly true, because the --restrict-scheme and --restrict-scheme-namespace flags are missing from v2 versions.

These flags gave us the possibility to control the provisioning ALBs with an internet-facing scheme using the alb-ingress-controller-internet-facing-ingresses configMap which can store a list of approved ingresses. [https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/controller/config/#limiting-external-namespaces](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/controller/config/#limiting-external-namespaces)

If you try to run the new versions with these flags they will crash with the `unknown flag: --restrict-scheme` message. 

Is it intentional or is there any new approach to solve this situation?

**Comment by M00nF1sh** [comment]
@csgaiger-hiya 
Hi, there is no equivalent functionality in v2 currently. we'll add support for it via IngressClass in future versions.

**Comment by csgaiger-hiya** [comment]
Thanks!

**Comment by kishorj** [comment]
We plan to support this in the upcoming release with the IngressClassParams feature. Targeted for Q1.

**Comment by kishorj** [comment]
PR  #1969

**Comment by kishorj** [comment]
Feature supported in v2.2.0 release.
