### ISSUE TITLE
migration from v1 to v2 doesn't register targets to TG

### ISSUE THREAD

**Issue by amitde69** [kubernetes-sigs/aws-load-balancer-controller#1758]
version: aws-alb-ingress-controller:v2.1.1

Hey,
I have been performing the migration steps documented here 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.0/guide/upgrade/migrate_v1_v2/

everything seems to work as expected except 1 thing, after the whole process is done, all the TGs are getting recreated and added to the ALB rules (as expected), but the Targets in the TargetGroups are being registered.

The behavior in the logs is as such :

This happens on a loop, while every loop it recreates the TGs again and isn't able to find them afterwards:
```
{
    "level": "info",
    "ts": 1610156555.6678073,
    "logger": "controllers.ingress",
    "msg": "creating targetGroupBinding",
    "stackID": "xxxxx/xxxxx",
    "resourceID": "xxxxx/xxxxx-xxxxxx:80"
}
....
{
    "level": "error",
    "ts": 1610156555.6807902,
    "logger": "controller",
    "msg": "Reconciler error",
    "controller": "ingress",
    "name": "xxxxx",
    "namespace": "xxxxx",
    "error": "targetgroupbindings.elbv2.k8s.aws \"k8s-xxxxx-xxxxxx-xxxxxxxx\" already exists"
}
....
{
    "level": "error",
    "ts": 1610156654.0800788,
    "logger": "controller",
    "msg": "Reconciler error",
    "reconcilerGroup": "elbv2.k8s.aws",
    "reconcilerKind": "TargetGroupBinding",
    "controller": "targetGroupBinding",
    "name": "k8s-xxxx-xxxxxx-a23b412ccf",
    "namespace": "xxxxx",
    "error": "TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-2:xxxxxxxx:targetgroup/k8s-xxxxxx-xxxxxxx-xxxxxxx/xxxxxxxxx' not found\n\tstatus code: 400, request id: xxxxxxx-xxxx-xxxxx-xxxxxx-xxxxxxxxxx"
}
```
 
All annotations are the same, same ingress resources nothing changed between v1 and v2.

Can anyone advise on why that would happen ? what situations could cause this to happen ?

**Comment by amitde69** [comment]
Seems like the problem was solved (Targets registered) when upgarding to version v2.1.1 although I am still getting these errors on a loop:
```
{
    "level": "error",
    "ts": 1610156654.0800788,
    "logger": "controller",
    "msg": "Reconciler error",
    "reconcilerGroup": "elbv2.k8s.aws",
    "reconcilerKind": "TargetGroupBinding",
    "controller": "targetGroupBinding",
    "name": "k8s-xxxx-xxxxxx-a23b412ccf",
    "namespace": "xxxxx",
    "error": "TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-2:xxxxxxxx:targetgroup/k8s-xxxxxx-xxxxxxx-xxxxxxx/xxxxxxxxx' not found\n\tstatus code: 400, request id: xxxxxxx-xxxx-xxxxx-xxxxxx-xxxxxxxxxx"
}
```

Is it expected ?

**Comment by M00nF1sh** [comment]
@amitde69 
would you help share your Ingress spec here.

**Comment by chandankashyap19** [comment]
Hey, Getting similar error in my case as well.
"level":"error","ts":1610614059.2585454,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"prometheus-server-lb-02","namespace":"kube-system","error":"the server could not find the requested resource (post targetgroupbindings.elbv2.k8s.aws)"}
Please suggest

**Comment by amitde69** [comment]
So after some playing, I figured out I messed up the TargetGroupBindings and they pointed to non-existing TargetGroups.
To resolve it I wiped all the TargetGroupBinding resources with the following command :
```
kubectl delete targetgroupbinding  --all --all-namespaces
```
