### ISSUE TITLE
ingress controller paths for different paths.

### ISSUE THREAD

**Issue by root1250** [kubernetes-sigs/aws-load-balancer-controller#1760]
Hi Team,

i have 2 apps one front end and one is backend and both uses a same host but different services i have regex rule which works with nginx but not with aws ingress controller. 

see my config.

# To route requests between API and UI
# you should have installed IngressController in your K8S cluster,
# see https://kubernetes.github.io/ingress-nginx/deploy/
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
#    alb.ingress.kubernetes.io/group.name: <my-group> #if we want to share ALB between apps
spec:
  rules:
    - host: HOST_TO_BE_CUSTOMIZED
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: frontend-ui-cluster-ip
              servicePort: 4200
          - path: /(v3?(.*))
            backend:
              serviceName: backend-api-cluster-ip
              servicePort: 8080
          - path: /(swagger?(.*))
            backend:
              serviceName: backend-api-cluster-ip
              servicePort: 8080

both front and back end services are up but the traffic is not redirecting the service it supposed to :( , help is needed.

**Comment by M00nF1sh** [comment]
@root1250
ALB Ingress controller currently only supports the "ImplementationSpecific" path type(which is the default).
We'll support "prefix" path in future versions, but we won't be able to support Regex before ALB itself supports it.

The supported path syntax can be viewed here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#path-conditions.

**Comment by kishorj** [comment]
This requires support from the ALB side. Adding to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571.

**Comment by kishorj** [comment]
Keeping track of the issue in AWS ALB feature list.
