### ISSUE TITLE
Needs additional permissions to provision ALB on AWS Outpost with customer IPs

### ISSUE THREAD

**Issue by arhea** [kubernetes-sigs/aws-load-balancer-controller#1761]
**Description:**
When running Amazon EKS in a VPC with an AWS Outpost, the AWS Load Balancer Controller needs two additional permissions to provision an ALB on the AWS Outpost when using customer provided IPs.

- `ec2:DescribeCoipPools`
- `ec2:GetCoipPools`

These will work in conjunction with the `alb.ingress.kubernetes.io/customer-owned-ipv4-pool` annotation.

**Comment by kishorj** [comment]
@arhea, thanks for letting us know. We will update the iam policy docs.
