### ISSUE TITLE
Installation procedure is convoluted and not very IaC friendly

### ISSUE THREAD

**Issue by fernando-villalba** [kubernetes-sigs/aws-load-balancer-controller#1763]
I don't know if it's just me, but I find the installation procedure described for this controller is all over the place and hard to work with. Let me explain...

In [here](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller) you have installation instructions for Helm, where you are asked to first install a CRD with Kustomize and then do a Helm install. I fail to see why this is not done in just one step, in either Helm or Kustomize.

Also the yaml installation requires you to install the cert manager but Helm doesn't, where is the consistency? 

I personally tend to favour kustomize over Helm, especially for IaC, it's just cleaner to work and easier to understand and what I particularly love is when I can track a remote Kustomize base and apply overlays where needed, this makes applying updates a lot easier. So I was very happy when I found that you are doing [kustomize](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/main/config/default) in this repo. However making it work out of the box and by referencing it remotely is a real hassle because you have overlays all over the place, and if you just try to run it as it is from your default configuration yaml here, it just doesn't work. The ingress complains of this error:

```
{"level":"error","ts":1610810328.0963387,"logger":"setup","msg":"problem running manager","error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
```
or that the secret does not exist.

I noticed that Helm is actually generating this secret resource and mounting it when it runs, but this is not something done by Kustomize.

Another thing is that I don't even know why I need the above if I don't want the ingress controller to manage certificate creation and renewal.  I am just using AWS managed certs for this. I may have known this if it was properly documented, but I can't find it anywhere either. 

Shouldn't the default Kustomize be a working configuration?

Anyway, I know I can probably spend my time dissecting this and making it work for myself, but I just find this whole process could be implemented a lot better from an operational point of view.

**Comment by M00nF1sh** [comment]
Hi @fernando-villalba,
1. we separated the CRD install from helm because helm [currently doesn't manage CRD updates](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/). And when we release new controller versions, the CRD might contain changes, so we always ask user to apply the CRD first. (when installing in a fresh cluster, helm install will work without apply the crd explicitly).
2. The controller needs the cert for it's webhook server(and the cert cannot be a ACM cert). In our helm chart, we support both `generating cert during helm install` or `rely on cert-manager`. However, for install via YAML, we cannot generating cert during install`, so we only support rely on cert-manager instead.
3. If you install via kustomize, you have install cert-manager as well, since it's what we used to generate the certificate.

BTW, we'll consider install/upgrade CRD and serving cert within the controller itself, so it can address this issue.

**Comment by fernando-villalba** [comment]
hi @M00nF1sh Yeah I saw that link about the CRDs after posting this and I figured all the rest myself by getting stump and looking at the code. I guess my point is that everything you said here, should be part of your documentation so it is clear, otherwise it's confusing. It's only a few extra lines and I think it would help a lot.

I was just going to suggest your solution for the cert generation. But I guess this would require granting the controller service account additional permissions to create secret resources? Or did you have something else in mind?

**Comment by fernando-villalba** [comment]
@M00nF1sh Jesus, I actually went through and clarified the documentation as best as I could and was excited to help but doing a pull request for this repo is more work than signing up for a bank account. I am being asked all kinds of legal requirements and to sign all these documents and give out my home address. As much as I want to help, this spooked me out of my desire to do so. I was happy to give me name and email address, but my home address and all that feels like a really excessive invasion of privacy. 

Here are the changes I was planning to submit:

https://github.com/fernando-villalba/aws-load-balancer-controller/commit/668af05a45bace8457e0acce55ad2eec81abbfa5#diff-8a0aad20650a13771cbf472ff7c0127a7cbcef25e47dd2b279a80b1db3dffee5

If anyone wants to incorporate them, I am happy to give my consent.

**Comment by jonathanjuursema** [comment]
@fernando-villalba would you be willing to share the steps you've taken to deploy to deploy the ALBCv2 without the cert manager? We're facing a similar issue (deploying via IaC, and trying to minimize what we run in our cluster, so if we can work without cert-manager we'd like to).

**Comment by jonathanjuursema** [comment]
Figured it out. For anyone interested in running ALBCv2 without cert-manager:

Create a secret like so (this is what cert-manager does under the hood, when creating the Certificate resource):
```
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: aws-load-balancer-webhook-tls
  namespace: kube-system
data:
  ca.crt: LS0tLS1CRU <Base64 Encoded PEM file> SUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRU <Base64 Encoded PEM file> SUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRU <Base64 Encoded PEM file> SUZJQ0FURS0tLS0tCg==
```
The ca.crt and tls.crt are the same (self-signed) certificate. The certificate needs to have the following properties:
- CN: aws-load-balancer-serving-cert
- SAN: aws-load-balancer-webhook-service.kube-system.svc
- SAN: aws-load-balancer-webhook-service.kube-system.svc.cluster.local

Update both WebhookConfigurations to remove the `cert-manager.io/inject-ca-from` annotation, and update the caBundle in that same resource with the same value as `ca.crt` above (the Base64 encoded PEM file).

Remove the Issuer and the Certificate resources.

Figure out a way to generate and insert the self-signed certificate in your IaC, that works for your set-up (we have a way to store encrypted values in our IaC, that are only decrypted temporarily on apply). Hope this helps someone.

**Comment by lifeofmoo** [comment]
This is still an issue (for me anyway). We also do not use cert-manager so to be able to upgrade the controller from 2.1.3 to 2.3.1 I also had to use my previously generated self signed certs like above but also had to add the caBundle spec back into the install file and place it under each of the clientConfig objects (4 places in the file).

i.e

``   clientConfig:
    caBundle:  XXXXXX
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
