### ISSUE TITLE
Race condition between pod readiness gate injection and ingress model update?

### ISSUE THREAD

**Issue by foriequal0** [kubernetes-sigs/aws-load-balancer-controller#1764]
I've once tried to update both ingress and deployment at once.
But then new pod's readiness gate stuck at this state for few minutes.
```
Readiness Gates:
  Type                                                           Status
  target-health.elbv2.k8s.aws/old-target-group-id                <none>
```

This is a brief timeline of logs of the `aws-load-balancer-controller`. This happened in < 3 seconds.
```
< left are logs with old-target-group-id
          > right are logs with new-target-group-id
successfully built model (new pod has created around this log's timestamp)
successfully deployed model
          successfully built model
          creating targetGroup
          created targetGroup
          modifying listener rule
          modified listener rule
          creating targetGroupBinding
          created targetGroupBinding
deleting targetGroupBinding
deRegistering targets (old pod)
deRegistered targets (old pod)
          registering targets (old pod)
Reconciler error with "TargetGroupBinding.elbv2.k8s.aws \"old-target-group-id\" not found"
deleted targetGroupBinding
          registered targets (old pod)
deleting targetGroup
deleted targetGroup
          successfully deployed model
```

I also wonder why the events are in this order for the old pod:
```
creating targetGroup
modifying listener rule
creating targetGroupBinding
deRegistering targets
registering targets
```
not in this order:
```
creating targetGroup
creating targetGroupBinding
registering targets
modifying listener rule
deRegistering targets
```
Wouldn't modifying the listener to forward traffic to the target group that targets are registered later introduce downtime?

**Comment by M00nF1sh** [comment]
@foriequal0 
The controller currently doesn't support zero downtime when u modify the Ingress/Service in such way that result in TargetGroup changes(e.g. changed the backend service).  The Targets won't be health-checked before added to LoadBalancer. However, we indeed can do optimizations like modify the rule once new targets are registered(but not health-checked) to reduce the downtime in such case.

For the pod readinessGate issue, i think it's indeed a race condition under such case. the webhook is based on current available TargetGroupBinding in cluster.  I think we can solve it by:
1. delete old TargetGroupBinding first.
2. mark podCondition with associated TargetGroupBinding's readinessGate as healthy when delete a TargetGroupBinding.

/kind bug

**Comment by Project0** [comment]
/remove-lifecycle stale

I just ran into a similar issue with the same root cause. When deleting a ingress and updating the deployment at the same time it ends up in the same situation, the readiness gate is attached to the new pods, but the targetgroup is eventually gone and can never become healthy.

Please note i have two ingress controller attached (a ALB for internal and one for external)
```
  - lastProbeTime: null
    lastTransitionTime: "2021-12-21T13:59:44Z"
    message: Target registration is in progress
    reason: Elb.RegistrationInProgress
    status: "False"
    type: target-health.elbv2.k8s.aws/k8s-test-408ff770ff
  - lastProbeTime: null
    lastTransitionTime: "2021-12-21T13:59:36Z"
    message: corresponding condition of pod readiness gate "target-health.elbv2.k8s.aws/k8s-test-8abc38e6f1"
      does not exist., the status of pod readiness gate "target-health.elbv2.k8s.aws/k8s-test-408ff770ff"
      is not "True", but False
```
