### ISSUE TITLE
SSL Passthrough

### ISSUE THREAD

**Issue by leo-viridis** [kubernetes-sigs/aws-load-balancer-controller#1766]
Hi,

Is it possible to do SSL passthrough  and skip terminating TLS on the load balancer but do it in the service instead?

I've seen only two issues mentioning that, referring to GRPC. I am interested in having HTTPS on the service. I wasn't able to find anything in the documentation.

Thanks.

**Comment by M00nF1sh** [comment]
@leo-viridis 
Yes it's possible, if you are using NLB, i believe a tcp service will work.

**Comment by leo-viridis** [comment]
@M00nF1sh 
Thanks. Is this documented somewhere?

**Comment by leo-viridis** [comment]
I managed to setup NLB-IP using the following as annotations:
```
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```
And ports are mapped as:

```
ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
```

And that seems to setup everything properly. Services are properly added to NLB, health check passes OK too. However, my intention is to get SSL passthrough to an nginx sidecar pod that serves valid SSL on port 443. For some reason NLB doesn't really pass the traffic to pods. I have added CNAME for NLB in Route53 so that I have a proper domain that is covered by the SSL cert. Yet, doing `curl` throws an error:

```
 curl -kv https://my-domain.com/path
 curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by leo-viridis** [comment]
Update: this now works as expected. For anyone running into the same problem in the future, make sure that the app behind NLB supports Proxy Protocol v2. If that's not the case then drop:

`service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"`

Or enable Proxy Protocol in your backend.
