### ISSUE TITLE
Ingress Group is failing to propagate certificate arn changes (Enterprise Impact)

### ISSUE THREAD

**Issue by BoucheeMalcolm** [kubernetes-sigs/aws-load-balancer-controller#1776]
Hello Everyone,

I'm submitting this using my personal GitHub account, but it's impacting my enterprise's EKS Platform management.

Our current design for ingress file management is to have one primary ingress file with most of the shared annotations, while limiting any dependent ingress file to just these annotations:

kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/group.name: groupname
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'

After changing the certificate.arn annotation the primary ingress file if I change, all of the dependent ingress files now throw this error: error":"ingress: different-namespace/dependent-ingressname: multiple certificate found for host: sharedhostname, certARNs [previousarn currentarn]

What I expect to happen is to have a new cert added to the ALB and for all listener rules to be moved to the new port 443 listener with the updated cert. That error appears to be stopping this from occurring.

In the short term, my fix will be to inform everyone to remove {"HTTPS": 443} from their dependent listen-port and then re-add so any aws load balancer controller data referring to the previous arn is hopefully removed from the EKS cluster.

Thanks,
Malcolm

**Comment by M00nF1sh** [comment]
@BoucheeMalcolm 
The TLS cert is determined per Ingresses. The idea is like this.
1. You have IngressA with host `hostA.example.com`, IngressB with host `hostB.example.com`
2. It make more sense if you specify the certs for `hostA.example.com` on IngressA, and certs for `hostB.example.com` on IngressB.

So in your case, on the secondary Ingresses, it cannot find the TLS certificate for `sharedhostname` via annotation, so it attempted to do auto-discovery and find multiple matching certificate(where the controller view it as a conflict).

The workaround for now should be add the certificate ARN annotation to secondary Ingresses as well.

BTW, there are multiple potential fixes to this issue, which one fits your cause?
1. do the certificate resolve on entire IngressGroup. (i.e. if you specified at least one cert on one of the Ingress, we'll proceed the reconcile process). 
2. make the automated certificate-discovery to find the best matching certificate. e.g. prefer `*.example.com` over `*.com` (not sure whether it's your case which have multiple certificate for `sharedhostname` in your account).

**Comment by BoucheeMalcolm** [comment]
Thank you for the prompt response.

I may not have expressed it well but Solution 1 was the expected behavior. If I set a certificate on one member of a particular ingress group, it should be shared across all members except for when a different cert is specified in the certificate.arn annotation.  In that case, that unique member will reconcile with its own certificate.

Does certificate discovery search ACM or does it search for all certificate arns the controller is currently using? My expectation was that once I changed the only explicit certificate declaration in all of the Ingresses, it would assume that I want the old certificate forgotten by the system and replaced with the new certificate.

The reason I avoided having people enter the certificate arn in each ingress file is because I wanted to maintain the certificate arn in one place. I wanted to keep a non-functional task such as TLS encryption to be as simple as possible.

**Comment by vmvazque** [comment]
/remove-lifecycle rotten

We have a very similar design. We have a primary ingress file with the shared annotations (certificate arns, group name, security groups) and then have the micro-service ingress files limited to attaching itself to the group and adding their path. We know these micro-services should be using the same certificate as the primary ingress, so adding the certificate-arn or certificate discovery (which isn't working for me but that's another issue) shouldn't be needed. 

If we want to update the certificate on the load-balancer, our process would be to update the arn in the primary ingress file and have all the micro-services use that new certificate. Essentially we'd like a way for our micro-services to use the certificate already defined for the ingress group, either by turning off auto-discovery or having auto-discover only look at the certificates already assigned to the group.
