### ISSUE TITLE
Support for cross-cluster load balancer

### ISSUE THREAD

**Issue by hintofbasil** [kubernetes-sigs/aws-load-balancer-controller#1777]
We are trying to add pods from two clusters to a single target group.  In one cluster we create a service with `service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip` to create an NLB, in the other we create a TargetGroupBinding to add pods to the target group of the created NLB.

When a controller in either cluster reconciles it removes the pods from the other cluster and adds its own.

It is technically possible for the controller in one cluster to not remove the targets added by a controller in a second cluster?

Would this be possible if we were using `type: instance` instead of ip addresses?  Our tests show the same behaviour for both currently but maybe one is possible and the other not?

Happy to contribute a PR if there is a way to get this functionality.

**Comment by kishorj** [comment]
@hintofbasil, Are you looking for both the controllers to modify the same target group?

Assuming your clusters are on the same VPC, if you have different target groups, then you can create the NLB and target groups externally and create appropriate targetgroupbindings in each of the clusters to reconcile the individual target groups.

**Comment by hintofbasil** [comment]
Hi Kishorj,

Yes, we need both controller to modify the same target group.
NLBs only support one listener per port, and each listener only supports a single target group.  So to have an NLB load balancer traffic between two clusters using the same port we need to add pods form both clusters to the same NLB.

This is all happening in the same VPC.

**Comment by Smirl** [comment]
Hi @M00nF1sh, @kishorj 

I work with @hintofbasil and we spoke with our TAM/SA the other week and they suggested that the fixes outlined in #1452 would also fix this.

We are happy to talk in a zoom/chime call or over slack if that is quicker than github.

**Comment by sftim** [comment]
BTW, https://kubernetes-sigs.github.io/service-apis/ is now a 404 page.
