### ISSUE TITLE
Using Webproxy to connect internet

### ISSUE THREAD

**Issue by fhopeman** [kubernetes-sigs/aws-load-balancer-controller#1779]
Hi there,

I want to use a webproxy to connect to the internet. In AWS there is no VPC Endpoint for AWS WAF V2. The alb ingress controller is calling this url and I see timeouts to that service api url.

Is it possible to configure a webproxy for the alb ingress controller?

Best regards
Fabian

**Comment by kishorj** [comment]
If you are not using WAF V2, you can disable the waf v2 feature by --enable-wafv2=false controller flag. If you indeed require WAF V2, you should be able to configure HTTP proxy for the controller via the HTTP_PROXY environment variable. Let us know if you run into issues.

**Comment by fhopeman** [comment]
Thanks a lot! We've set the enable-wafv2 flag to false and it works.
