### ISSUE TITLE
Feasibility of running v1 and v2 in parallel

### ISSUE THREAD

**Issue by patstrom** [kubernetes-sigs/aws-load-balancer-controller#1781]
Hello!

I am wondering about the feasibility of running v1 and v2 in parallel when upgrading. The idea is to use a different ingress class for the controller running v2 and then re-create all the existing ingresses for that class to make sure everything is working correctly before actually committing to it (and updating DNS and whatnot).

Is there anything I need to think about if I were to do this? Can they peacefully co-exist or will annotations and/or tags cause some conflicts somewhere?

Cheers

**Comment by kishorj** [comment]
The v2 controller is backwards compatible with the ALB/target groups configured by v1. You should be able to uninstall v1 and then install v2 controller without incurring a downtime. Are there specific concerns you have with this recommendation?

You should also be able to run v1 and v2 controllers on the same cluster as long as you specify distinct values to the ingress-class controller flag.

**Comment by patstrom** [comment]
My concerns are mainly about the stakes of this. If something goes wrong with the ingress controller more or less everything becomes unavailable. That's why running both in parallel feels like a good option.

The idea is also to use the new controller and ingress API added in Kubernetes 1.18 and the current controller has run since version 1, which is why I am a little hesitant to just go for it.

From my understanding the v2 controller also requires the certificate manager (which the v1 does not) which adds another point of failure during the upgrade.

I guess I just don't want the stress of dealing with everything in the timeframe where the v1 controller is gone but before the v2 one is up.

But everything should be fine if I just specify different `--ingress-class` values? Like naming the v2 one `--ingress-class=albv2` (where the current one is `--ingress-class=alb`)?

**Comment by patstrom** [comment]
I solved this by running v2 in parallel to v1 but with different ingress classes! Everything worked very well and I didn't even need to shut down external DNS, I just deleted the old ingress and everything was updated accordingly.

Thank you for the help!
