### ISSUE TITLE
ReadinessGates are removed even for ingress that do not have a targetgroupbinding before the migration to v2.

### ISSUE THREAD

**Issue by cw-sakamoto** [kubernetes-sigs/aws-load-balancer-controller#1782]
In our environment we are running multiple ingress classes with each aws-alb-ingress-controller to increase parallelism.

When I tried to installing v2 with `ingress-class:alb`, readinessGates that have not yet been migrated to v2 removed from the pod.

I think this is due to this [process,](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.1.1/pkg/inject/pod_readiness_gate.go#L102), since this method checks only prefix, the readinessGates is deleted before I actually change it to the ingressclass for v2.

Is it possible to add a condition other than checking the prefix (e.g. whether there is a targetgroupbinding or not)?

**Comment by kishorj** [comment]
@cw-sakamoto, thanks for reporting the issue.

In your case, do you have the same pods being targeted by ingresses from v1 and v2 controllers?

**Comment by cw-sakamoto** [comment]
@kishorj 

>In your case, do you have the same pods being targeted by ingresses from v1 and v2 controllers?
No, pods are targeted by v1, so aAdding and deleting to the AWS targetgroup is done by the ingress controller of v1.

Only `readinessGates` is managed bu v2 with mutation webhook, and ingress is v1, so its `readinessGates` is set to null by v2.

**Comment by M00nF1sh** [comment]
@cw-sakamoto 
I think we can introduce a flag to see whether automatically remove v1 readinessGates. (which default to true)
Will it suit your use case? 

 BTW, V2 only supports a single controller per cluster(it's scalable enough, so no need to run multiple controllers)

**Comment by cw-sakamoto** [comment]
@M00nF1sh 
Thank you for your comments.

I would like to have v1 and v2 coexist in one cluster, since our team prepares for the migration to v2, but the dev side has the decision to switch from v1 to v2.

**Comment by M00nF1sh** [comment]
@cw-sakamoto 
Thanks for the response :D 
In such case, i think the controller-level flag(e.g. `--remove-legacy-readiness-gate=true`) should be able to help here. Would you mind doing a PR to add it?

**Comment by cw-sakamoto** [comment]
@M00nF1sh 

Good idea!  Thanks.
It's no problem, because dev team will remove v1 `readiness-gate`  in manifests when migrating to v2.

**Comment by cw-sakamoto** [comment]
I modified it so that it could be handled without the `--remove-legacy-readiness-gate` option.
