### ISSUE TITLE
Dynamically allocating groups for 100+ rules?

### ISSUE THREAD

**Issue by mitom** [kubernetes-sigs/aws-load-balancer-controller#1784]
ALBs have a service limit of maximum of 100 rules per ALB. This is very likely not an issue in most environments. In my usecase, there are development environments which may have ingresses associated with them but in reality see barely any traffic. Keeping the ingresses is important so developers can work in production like environments. I'd like to reduce the number of load balancers as much as possible, however even with the new grouping this would be a problem (there are hundreds of dev environments). 

I'm curious if you have any thoughts or suggestions on somehow dynamically partitioning groups to minimise the number of load balancers (or otherwise overcome this problem)? E.g. if adding a rule fails due to reaching the maximum of 100 rules for the load balancer, create a 2nd ALB for the same group so putting 101 ingress rules into 1 group would result in 2 ALBs for the same group. Evidently from an automation perspective that becomes a bit of a chore when you delete a few ingresses from earlier which puts it below 100 and it migrates things to a single alb which likely causes a bit of a blip. Not to mention, this'd need to be implemented in the project.

Any suggestions would be welcome.

Thanks!

**Comment by M00nF1sh** [comment]
Hi @mitom 
I have thought about add things like `group.name: auto` to support such functionality. 
However, we don't have a good design to capture all use case/scenarios in a clean way. There are restrictions on how we can break the rules:
1.  rules for same Ingress shouldn't be break into different ALBs.
2. rules for hostname shouldn't be break into different ALBs.
However, there are a lot of sharp edges when handling such restrictions:
1. a single Ingress may have more than 100 rules.
2. user may add more rules to an existing ingress. (which may cause ALB exceed 100 rules, and we'll have a move some Ingress into another ALB, which may not be wanted).

I think if we have a good design to handle all these case, it indeed would be convenient for users with such use case.

**Comment by mitom** [comment]
Hi @M00nF1sh sorry for the slow response.

I've tried to come up with an idea of how could this work but I don't think I have a good design suggestion.

To your points:

1. I don't think this is in itself a huge problem. (combining with point 3) Having 100 rules in 1 ingress could potentially be a hard limit here. If it's 100+ rules for the same host, there is just no way to achieve it due to the limit in the ALB (i am unsure if this can be raised on the AWS side). Having 100 rules for multiple hostnames (combining with point 2) is a problem anyway since we couldn't set 2 endpoints in k8s for the 1 ingress object so other tools external-dns wouldn't be able to work. However, this can be very easily overcome in userland by just splitting out the ingress objects to 1/hostname. It's not a huge amount of work and it's a pretty realistic caveat to have IMO.
2. As above, I think this is a hard limit that the ALB controller can't really overcome because of how ALBs work. Regardless of whether it's the same host, or multiple hosts - we could make it happen solely on the ALB level, but it'd not fit with how other tools work in the ecosystem so it'd likely cause more issues than solutions (1 ingress -> 1 hostname -> 2 ALBs = very difficult DNS, if not impossible, 1 ingress -> 2 hostnames -> 2 ALBs = no way to advertise to k8s which hosts go to which ALB, but easy to solve just by using 2 ingress objects). The issue this causes (and it may have been your point and I just didn't immediately get it) is if we have 100+ ingress objects with 1 rule each assigned to the same group causing 2 dynamic ALBs, if we add a 2nd rule to one of them, we have no place to put it.
3. Once again as above, seems like a hard limit, if it's hostnames, they need to be split, if it's not, we can't do it anyhow already can we?
4. I agree with this being an issue, however based on the above I'd conclude that creating 1 ingress object and expecting multiple ALBs is not possible, so maybe this is an area that couldn't be supported. Nevertheless, the problem transcends the 1 ingress multiple ALBs scenario as below.
5. This is what I'd like to add - based on the above, I don't think we can reasonably say 1 ingress object could dynamically split rules into multiple ALBs. However, maybe we can scope this explicitly as multiple ingress objects specifying the same group could cause multiple ALBs. Point 4 applies here, what if we delete an ingress that was scheduled on ALB1, would 1 rule from ALB2 migrate to ALB1, and 3->2 and so on for however manny there are?

I had only 2 ideas design wise which may provide some sort of workaround:
1. Provide a user configurable way to how the placing logic works. This is far from automated, but I am unsure if there is a reasonable way to dynamically guess this. This could be on multiple levels, the way I imagine it:
  a. We create a new CRD for an ALB resource (I'm not sure if this is the best path, the only point is to provide a single source of truth for configuring an ALB to avoid 2 ingress resources specifying the same group, but different expectations for how an ALB should be set up. There may already be a solution to this in the project and I just don't know since theoretically this could already happen?)
  b. We create an `expectedRulesPerIngress` setting that controls how to space the ingresses. I.e. set if set to 5, it'd allow 20 ingresses onto an ALB, leaving room for 5 rules each. (it could also be `maxIngressPerAlb` to say "set to 20 to only ever allow 20 ingresses onto single ALB" ). This would be an option for users to pad their setup according to their needs. E.g. if you know for a fact you'd really only ever use 1 rule/ingress but also wanted a bit of headroom, you could set the max to be 90 ingress/ALB giving you the option to add 10 more rules to any of the 90 ingresses.
2. To avoid ingresses migrating between ALBs, we could annotate the ALBs in a tag with what ingresses are scheduled on them. I.e. just 1 tag with a comma delimited list of `namespace/ingress-name` (max tag value length may be an issue here, not sure what that is). If an ingress is already scheduled on an ALB, leave it alone even if there is a free slot for it somewhere else. We could make an option whether migrating ingresses should be allowed or not to toggle this. (e.g. for my usecase it's development environments, a blip of outage because some ingresses got deleted and a bunch got moved is not a big deal and optimising for the smallest number of ALBs is good, in production you'd probably disable this).

That being said, all of the above seems like a kinda hacky way to shuffle these things together. It may be less effort to just run both the ALB controller and some generic software IC which has no limits on these and simply use them in the different usecases.

After writing all this out, I think personally I'd not bother with the workflow I described and just live with both.

**Comment by FlorinAsavoaie** [comment]
So actually I think the group: auto is a very good idea and it can be fairly simple to define a scenario:

Define `AlbIngressGroup` as an actual resource and it should support a parameter called `ingressSelector`.

What do you think about this?

**Comment by jcogilvie** [comment]
/reopen

I would very much like to see some variant of this feature where a large group can be split across multiple ALBs.  

For instance, I have groups `internal` and `external`.  I have more than 100 external routes, which will be sourced from many different Ingresses, and can be safely split between LBs with no ill effect.
