### ISSUE TITLE
Question about target group ready time.

### ISSUE THREAD

**Issue by MarvinCai** [kubernetes-sigs/aws-load-balancer-controller#1786]
Hi there,
We notice it takes about 4 ~ 5min from creating a Service of type LoadBalancer till we can actually hit the endpoint successfully.
We've tested with our deployment and service and with sample ngnix deployment and service provided here: https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html.
And we've tried both `service.beta.kubernetes.io/aws-load-balancer-type: nlb` and `service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip`
Is it normal that it take about 4 ~ 5 min to provision LB, add listener and register targets with target group after a LoadBalancer Service is created with AWS LB Controller installed?
If yes is there anything we can do or config we can tweak to make the process faster?

**Comment by M00nF1sh** [comment]
@MarvinCai 
Hi, it's due to new targets will take 4~5mins to be ready when registered into a NLB's targetGroup.
NLB team have a roadmap Item to optimize this delay this year.

**Comment by M00nF1sh** [comment]
closing this, but feel free to create a new issue if there are further questions :D
