### ISSUE TITLE
[v2] Support for --alb-name-perfix

### ISSUE THREAD

**Issue by kpulgam** [kubernetes-sigs/aws-load-balancer-controller#1788]
We use --alb-name-perfix in our current v1 alb ingress controller implementation , which helps us craft our IAM policy for controller to make it resource bound based on the prefix.
I see there was similar discussion in  https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1302 to see if --alb-name-perfix is also supported in v2 ( this will help us along with tag based conditions in locking IAM even further )
I did not notice this flag mentioned anywhere in the documentation - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/deploy/configurations.md

Can anyone please advise if it still is supported.
Thanks!

**Comment by M00nF1sh** [comment]
@ketan-sdeuser 
The v2 Controller doesn't support the `--alb-name-perfix` flag. we now used a fixed name pattern for ALB/NLBs: `k8s-<namespacedName>-<hash>`. The fixed name pattern allows us to have fine-grain control to stay within ELB's naming limits.

What's your use case to use this `--alb-name-perfix` flag? will a new feature to allow you specify the whole ALB name(instead of a prefix) for Ingress be sufficient?

**Comment by alexmnyc** [comment]
When trying to fit into existing infrastructure moulds at Enterprises, IAM policies are already crafted around specific resource naming conventions. We need the ability to customize it. For example, a team name "aum" must have all ALB resources named starting with aum prefix. It is important to have this level of customization for Enterprise integrations with the existing IAM paradigms

**Comment by LiorLieberman** [comment]
Any updates regarding this feature?, we just move to work with the new version and we need the as well need the prefix option that was in the old controller

**Comment by rdubya16** [comment]
@M00nF1sh Is this not mentioned anywhere in the migration guide? We use this feature to lockdown IAM permissions when using multiple kubernetes clusters. We expected this feature to still work from it not being mentioned anywhere. What is now the best way to grant limited access to alb resources when running multiple kubernetes clusters in the same account?

**Comment by kishorj** [comment]
@rdubya16, the v2 controller adds a resource tag with the key `elbv2.k8s.aws/cluster` with the current clusterName as the value. You could also configure controller instance to add additional tags. Would it not be possible to lockdown the IAM permission per controller based on the specific tag values?
