### ISSUE TITLE
Disable pod readiness gate for a specific ingress?

### ISSUE THREAD

**Issue by dudicoco** [kubernetes-sigs/aws-load-balancer-controller#1789]
Hi,

Is it possible to have the webhook skip injecting a pod with the readiness gate configuration, according to an annotation perhaps?

Thanks

**Comment by M00nF1sh** [comment]
@dudicoco 
Currently we only support to enable/disable readiness gate per namespace(via labels). so you need to create your pods in a separate namespace if different readinessGate configuration is needed.

BTW, it's technically feasible to disable readinessGate per Ingress(e.g. by have a field like enableReadinessGate in the generated TargetGroupBinding for the Ingress).  What's your use to disable readinessGate on specific Ingress?

**Comment by dudicoco** [comment]
Thanks @M00nF1sh.

My use case is for internal facing critical components. 
For example, I don't want prometheus to be dependent on the readiness gate, I would rather have some 5xx in the internal facing UI (ingress) than the possibility of the prometheus pods not being ready within the cluster.

**Comment by M00nF1sh** [comment]
@dudicoco 
could these internal facing critical components running in a separate namespace which didn't enable readiness gate? (or they have to leave in same namespace with other components that requires readinessGate)

**Comment by dudicoco** [comment]
@M00nF1sh I was able to do this by adding `objectSelector` to the mutating webhook configuration:
```
  objectSelector:
    matchLabels:
      elbv2.k8s.aws/pod-readiness-gate-inject: enabled
```

**Comment by M00nF1sh** [comment]
@dudicoco 
That's actually a brilliant solution 👍 
We should add objectSelector to our pod webhook to un-select the controller pod itself. and add documentation to podReadinessGate feature page about this solution.

/kind documentation
