### ISSUE TITLE
Does this controller work on vanilla k8s?

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/aws-load-balancer-controller#1792]
Hi, I have a question.

Can I use this controller on my own k8s cluster in AWS other than EKS nodes?

**Comment by kishorj** [comment]
It works, here are a couple of things to be aware of
- IAM for service account doesn't work, so you will have to attach the IAM permissions to the worker node IAM roles
- you will have to tag your subnets appropriately for auto-discovery to work 

If you run into other issues, please share it with us as well.

**Comment by M00nF1sh** [comment]
closing this issue as it can work on vanilla k8s. (e.g. kops)

In addition to the tips @kishorj  posted,  If aws-vpc-cni is not been used, you have to manage the worker node securityGroups yourself. (e.g. via the alb.ingress.kubernetes.io/security-groups annotation for ALB/Ingress). Note: it's possible to use `aws-vpc-cni ` even on vanilla k8s(kops supports it).
