### ISSUE TITLE
Metrics are broken in v2

### ISSUE THREAD

**Issue by dudicoco** [kubernetes-sigs/aws-load-balancer-controller#1797]
Hi,

The following metrics are missing from the v2 release:
aws_alb_ingress_controller_errors
aws_alb_ingress_controller_aws_api_errors
aws_alb_ingress_controller_aws_api_retries

Is there a reason why these metrics were removed?

Thanks

**Comment by dudicoco** [comment]
Looks like these metrics were renamed to `aws_api_..`.

It would be nice if the metrics could be documented.

**Comment by M00nF1sh** [comment]
@dudicoco 
Thanks for raising this issue.  we'll provide documentation for these metrics.

**Comment by M00nF1sh** [comment]
For now, you can refer the description in this PR for metrics usage: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/167
