### ISSUE TITLE
getting error when using image 2.1.1

### ISSUE THREAD

**Issue by gauravachatrath** [kubernetes-sigs/aws-load-balancer-controller#1799]
Hi,

I am getting this below error when i use image 2.1.1. in alb-ingress. Any help i can get on how to use the image or what am i missing ?

{"level":"info","ts":1612527706.0665936,"msg":"version","GitVersion":"v2.0.0-dirty","GitCommit":"1028fa4f363a9a8e37b07ff6a093b7b422923512","BuildDate":"2020-10-23T01:34:38+0000"}
{"level":"info","ts":1612527709.2469158,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"error","ts":1612527709.2641134,"logger":"setup","msg":"unable to create controller","controller":"TargetGroupBinding","error":"no matches for kind \"TargetGroupBinding\" in version \"elbv2.k8s.aws/v1beta1\""}

**Comment by kishorj** [comment]
@gauravachatrath The logs indicate that you are running version 2.0.0, not 2.1.1. How did you install the controller? Also, the CRDs appear to be missing. You can find the installation instructions in the live docs [[link]](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/).

**Comment by gauravachatrath** [comment]
Hi,

i followed the steps as said but now i am getting this error

unable to recognize "v2_1_0_full.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
unable to recognize "v2_1_0_full.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"

Any suggestion what values are needed or anything i need to change ?

**Comment by kishorj** [comment]
@gauravachatrath, did you install the cert-manager appropriate to your kubernetes version? 
```
Install cert-manager

For Kubernetes 1.16+:

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml

For Kubernetes <1.16:

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager-legacy.yaml
```

You can install the helm chart, it doesn't require cert-manager to be installed.

**Comment by gauravachatrath** [comment]
Thank you issue solved.

**Comment by lpossamai** [comment]
I'm also getting this error. Following the steps mentioned here did not solve it.

```
{"level":"info","ts":1615883498.9090755,"msg":"version","GitVersion":"v2.1.3-8-gccc707cf-dirty","GitCommit":"ccc707cf083e0869dec623d0270fa8831633f652","BuildDate":"2021-03-05T21:17:11+0000"}
{"level":"info","ts":1615883498.9370675,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"error","ts":1615883498.958169,"logger":"setup","msg":"unable to create controller","controller":"TargetGroupBinding","error":"no matches for kind \"TargetGroupBinding\" in version \"elbv2.k8s.aws/v1beta1\""}
```

I'm using version `v2.2.0`. Kubernetes version `1.19`.

Steps I did to try to solve this issue:
1. Ran: `kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml`
2. Installed CRDs [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/).

What am I missing?
