### ISSUE TITLE
Pod Readiness Gates Not Working

### ISSUE THREAD

**Issue by akash0710** [kubernetes-sigs/aws-load-balancer-controller#1808]
Hi,
I have a deployment with a service attached via labels. I have created a target group binding and controller is able to add the pods to the target group.

Now i am trying to enable readiness gates. I added the required label(`elbv2.k8s.aws/pod-readiness-gate-inject=enabled`) to the namespace.

Things which i tried:

- restarted all the pods
- fresh new deployment using kubectl apply
- restart the controller pods.

the Readiness gates are not getting added to the pod spec and neither the status are being updated.

What am i doing wrong here?

**Comment by M00nF1sh** [comment]
@akash0710 
not sure what's wrong here from the giving information. in the past, similar issue were reported but the user added the required label as annotations instead of labels. Note: it need to be label on the namespace where your pods runs, instead of the namespace of this controller(kube-system).

Would you help paste the output of `kubectl get namespace <your-ns-name> -o yaml` and `kubectl get mutatingwebhookconfiguration/aws-load-balancer-webhook -o yaml`

**Comment by akash0710** [comment]
`kubectl label namespace <ns>  elbv2.k8s.aws/pod-readiness-gate-inject=enabled`
 This is what is ran to enable label.
I will need sometime to get the config. I have 3 applications running in separate namespaces having a controller of their own in that namespace. Is this a wrong way to set it up?
Also it seems the MutatingWebhookConfiguration has got created only once for only one of the namespaces.

**Comment by akash0710** [comment]
Mutating Webhook Configuration
<details>
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2021-01-20T12:46:37Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: <ns>
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.0.1
    helm.sh/chart: aws-load-balancer-controller-1.0.7
  name: aws-load-balancer-webhook
  resourceVersion: "91807372"
  selfLink: /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/aws-load-balancer-webhook
  uid: e9394b04-8f3c-4d6e-ab53-f0c455904cb7
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: <bundle>
    service:
      name: aws-load-balancer-webhook-service
      namespace: <ns>
      path: /mutate-v1-pod
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mpod.elbv2.k8s.aws
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/pod-readiness-gate-inject
      operator: In
      values:
      - enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: <bundle>
    service:
      name: aws-load-balancer-webhook-service
      namespace: <ns>
      path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mtargetgroupbinding.elbv2.k8s.aws
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
</details>

From what i believe is happening here is it updates the webhook to the namespace where the loadbalancer controller was last run. And as i have controller running in different namespaces, the last one created should be the only one working.

What do you recommend in this case?

**Comment by akash0710** [comment]
Update:
This seems to be working, since i was running controllers in individual namespaces, i had passed watchNamespace param which restricts the scope to a single namespace.

Is the setup to run only 1 ALB controller in kube-system namespace by design?
Reason for this question:

- I am only working with different target group binding in different namespaces so the setup doesnt cause any issues in terms or registration or deregisteration.
- For pod-readiness i will have to enable watch all namespaces.
- What happens if i have multiple ALB ingress in multiple namespaces, how to handle ingressClass?

**Comment by M00nF1sh** [comment]
@akash0710 
You should only run a single controller deployment for v2.0.0+. The controller view itself as the sole owner of worker node securityGroup rules (rules with `elbv2.k8s.aws/targetGroupBinding=shared` description). There will be conflicts if multiple controller is running. (technically it's possible to allow multiple controller by provide a flag to override the `shared` keyword for each controller, but we don't support it currently)
With the introduction of IngressClass and scalability improvement, there shouldn't be need to run multiple deployment of controller.

**Comment by akash0710** [comment]
Thanks this helps closing this issue.
