### ISSUE TITLE
[Question] ELB security group

### ISSUE THREAD

**Issue by s4mur4i** [kubernetes-sigs/aws-load-balancer-controller#1809]
We are currently using alb-ingress-controller 1.1.6
We were currently investigating to add inbound CIDRs to the ELB. But according to annotations there is no option for this:
We have following annotatations currently:
```
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 1.2.0.0/16
    service.beta.kubernetes.io/aws-load-balancer-type: elb
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "env=dev,app=argocd"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: elb-logs
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: argocd/dev
```
`service.beta.kubernetes.io/aws-load-balancer-internal` should be boolean, so setting there cirdr ranges doesn't help.
In ALB docs I see possibility for defining CIDR range: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.0/guide/ingress/annotations/
but for ELB these don't work.
Is there a way to change inbound CIDR's on ELB?
Thank you

**Comment by kishorj** [comment]
@s4mur4i It is apparent that you wanted to create a Classic Load Balancer (based on the annotation). Let us know if it is otherwise.

In this case, you can specify the source ranges via the service annotation, for example
```
metadata:
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8, 1.2.3.0/24
```
or the service spec
```
kind: Service
apiVersion: v1
metadata:
  ...
spec:
  loadBalancerSourceRanges: 
  - "10.0.0.0/8"
  - "1.2.3.0/24"
  ports:
   ...
```

The default source range is 0.0.0.0/0.

**Comment by M00nF1sh** [comment]
adding to @kishorj 's suggestion, prefer to use `spec.loadBalancerSourceRanges` than annotation. 😄

**Comment by s4mur4i** [comment]
Thank you, it solved my problem!
