### ISSUE TITLE
Upgrading from v1.2.0-alpha.1 to V2 

### ISSUE THREAD

**Issue by siqusoft** [kubernetes-sigs/aws-load-balancer-controller#1811]
Hi @M00nF1sh 
we are currently using the beta feature of v1.2.0 in kuberentes 1.16 version of eks cluster and currently have about ~ 100 services with single load balancer.  i wanted to upgrade to the v2 version  with out any impact  since  tier one applications are hosted on the cluster.  wanted to see if we can simply upgrade the image and update the i am role to add the additional  required roles per v2 requirements.  Can you please guide us on  how to perform the upgrade as safe as possible we have multiple clusters across several environments with similar configuration.

**Comment by kishorj** [comment]
@siqusoft, you should be able to upgrade from v1 to the latest version of v2 (v2.1.2) without incurring downtime. You'd need to uninstall the v1 version completely, the ingress resources can stay as is, then install v2 following the upgrade instructions [[link]](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/upgrade/migrate_v1_v2/).
