### ISSUE TITLE
Documentation Request: A guide on setting up ALBC on an unmanaged cluster.

### ISSUE THREAD

**Issue by nicroto** [kubernetes-sigs/aws-load-balancer-controller#1819]
Hey folks,

The information I find about setting up the ALBC on a non-EKS cluster (in my specific case I still use AWS, but manage my cluster with kops) is only in the form of very short pointers of closed issues (where people are asking "Can I use it in a vanilla k8s cluster?" or similar), here in the repo.

Would it be possible to make a short guide?

**Comment by kishorj** [comment]
/kind documentation
Similar Issue #1792

We will mention it in the installation guide.
@nicroto feel free to raise a PR to update the installation guide.

**Comment by nicroto** [comment]
@kishorj Thanks. I would submit a PR, but unfortunately I am one of those people in need of the docs. :D (opting for haproxy ingress controller until I can test this out)
