### ISSUE TITLE
How to apply this in my AWS EKS cluster?

### ISSUE THREAD

**Issue by ZillaG** [kubernetes-sigs/aws-load-balancer-controller#1822]
The README.md file doesn't tell me how to apply this in my AWS EKS cluster. How do I do it? Or should I expect it to already "be there" if I create an AWS EKS cluster?

**Comment by M00nF1sh** [comment]
Hi, the installation guide can be found here: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/

**Comment by M00nF1sh** [comment]
it's not installed by default in EKS

**Comment by kishorj** [comment]
@ZillaG, closing the issue. Feel free to reopen or file a new one if you still have issues.
