### ISSUE TITLE
Reference to created ALB via infrastructure code. 

### ISSUE THREAD

**Issue by seivan** [kubernetes-sigs/aws-load-balancer-controller#1824]
It seems like a lot of tickets could be resolved if there was an easy way to refer to the ALB via whatever infrastructure tools being used to deploy the rest of the stack, e.g Terraform.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1116
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1086
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/846
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/870
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1774
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1074
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1331
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1483
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/360

This is a pretty big deal as it's currently not possible via massive hacks to deal with this. 
Most of these tickets mention stuff like names, ARN and approaches, I just want to point out that the method itself is irrelevant, as long as there is a way to refer to it. 

What is important, is having a way to get access to a specific ALB to set up further infrastructure at the final stages of a CI once most of the other stuff have been deployed. 

This could be anything from dealing Route53 to setting up Cloudwatch metrics and other aspects that needs to know details about the ALB being set up. 
There is currently a disconnect between how the rest of the system is set up (RDS, S3, etc) and the ALB which makes it tricky and bothersome. 

This could be anything from some changes in the code base to something simple as additional documentation with how to best deal with this in practice, maybe there's already a way, but I haven't managed to find it. 

Neither Terraform and Pulimi have a good way of dealing with this setup and I am not sure if there is anything that can be changed on those parts.

**Comment by M00nF1sh** [comment]
@seivan 
What is the feature request here? is it to use a externally-provisioned ALB or expose the managed ALB ARN(by the controller) to the Ingress object?

**Comment by seivan** [comment]
@M00nF1sh The feature request would be some way to identify said ALB once created.

Maybe the annotations on the `Service` or `Ingress` would be updated with the `ARN` and allow a `kubectl jsonpath` to traverse and extract it.

**Comment by seivan** [comment]
Closing this in favour of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1573 that would pretty much support all those issues, but it's not the best solution as it requires some logic on whatever infrastructure as code to "wait" until the load balancer is set up and then execute kubectl functions to fetch the jsonpath - but it's a good start!
