### ISSUE TITLE
Is there no way to `Preserve client IP addresses` when use `nlb-ip` mode?

### ISSUE THREAD

**Issue by junojuno90** [kubernetes-sigs/aws-load-balancer-controller#1825]
Dear, alb-controller developers.

We changed `service.beta.kubernetes.io/aws-load-balancer-type` annotation located on `Service` template recently from `nlb` to `nlb-ip`.
And after that, `x-forwarded-for` client ip was changed as internal ip `10.x.x.x`.
So we eanbled `Preserve client IP addresses` option on `Target Group` options manually.
But when after that changes, all request seems not reached to target group's POD. 

Is there other way to preserve client ip?

Thanks. Best regards.

**Comment by kishorj** [comment]
You can specify the preserve client IP configuration via the following annotation
```
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
```

For more details on the annotation, you can check the live docs [[link](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/#target-group-attributes)].

**Comment by junojuno90** [comment]
> You can specify the preserve client IP configuration via the following annotation
> 
> ```
> service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
> ```
> 
> You'd need use controller v2.1.0 or later for this feature.
> 
> For more details on the annotation, you can check the live docs [[link](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/#target-group-attributes)].

Thanks. I'll check :>

**Comment by buptliuwei** [comment]
> > You can specify the preserve client IP configuration via the following annotation
> > ```
> > service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You'd need use controller v2.1.0 or later for this feature.
> > For more details on the annotation, you can check the live docs [[link](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/#target-group-attributes)].
> 
> Thanks. I'll check :>

have you tried successfully, i add this annotation to my service, Preserve client IP addresses is enabled, but all request seems not reached to target group's
