### ISSUE TITLE
What annotations are supported when creating ALB & TargetGroupBinding manually? 

### ISSUE THREAD

**Issue by seivan** [kubernetes-sigs/aws-load-balancer-controller#1827]
Are the options defined here available? 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/

Or just the ones under `service.beta.kubernetes.io/aws-load-balancer-target-group-attributes`

Like could I define something like
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-path` ? 
And have it apply? 

What I am really interested in, is creating the ALB outside, and letting K8 create the attached targetGroups and Listeners via annotations.

**Comment by M00nF1sh** [comment]
@seivan 
Currently we don't support to use a ALB created outside for a Ingress. so no annotations were available.(support for external-provisioned ALB with Ingress is on our roadmap).

What you can achieve currently is to create ALB and TargetGroup and ListenerRules all from outside. and create the TargetGroupBinding resource in k8s for the TargetGroups created.

**Comment by seivan** [comment]
@M00nF1sh Just to be clear, if I am using `TargetGroupBindings` to wire things up, I can't annotate my Service with `service.beta.kubernetes.io/aws-load-balancer-healthcheck-path`? 
Why is that the case, it seems like it shouldn't make a difference, whatever the annotations do to configure the TargetGroups on AWS, should work here as well?

**Comment by M00nF1sh** [comment]
@seivan 
You can annotation your services with such annotation, but that annotation won't be used to configure targets(since seems you created the targetGroups outside of this controller).

currently, the solo purpose of TargetGroupBindings is to only register/deregister targets(and optionally manage securityGroup rules), instead of configure the targetGroup attributes.

**Comment by M00nF1sh** [comment]
closing this.
Feel free to reopen a new issue if you have further questions 😄
