### ISSUE TITLE
After moving our service to ALBv2 getting server unavailable

### ISSUE THREAD

**Issue by nandeeshb09** [kubernetes-sigs/aws-load-balancer-controller#1833]
Hi Team,

One of our service were in CLB and if we try to move to ALBv2 getting server is unavailable.

From frontend to backend traffic is not routing even though health checks are passing.

alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn
    alb.ingress.kubernetes.io/group.name: test
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb-controller-test
  creationTimestamp: "2019-08-09T11:30:13Z"
  finalizers:
  - group.ingress.k8s.aws/test
  generation: 9
  labels:
    app.kubernetes.io/name: appname
    helm.sh/chart: appname
  name: appname
  namespace: test
spec:
  rules:
  - host: hotsname
    http:
      paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        path: /*
      - backend:
          serviceName: service-name
          servicePort: http
        path: /*
This is the frontend configuration and please help here , the traffic is not getting in the backend.

**Comment by M00nF1sh** [comment]
@nandeeshb09 
Is the targets healthy in targetGroups created? (you can check them in aws console).
also, how do you access your service? since you used `scheme: internal` and specified a hostname in IngressRules, you have to access the LB from within your VPC and access it using the hostname(e.g. configure a cname to point hostname to the ALB's DNS).

**Comment by nandeeshb09** [comment]
Is the targets healthy in targetGroups created? Yes...target groups are healthy.
how do you access your service? since you used scheme: internal -- we have set VPN and using vpn will access url.
cname is pointed to the ALB's DNS has configured already.

**Comment by nandeeshb09** [comment]
@M00nF1sh And giving the 200 code in the developer mode and response is in the html mode instead JSON mode, and UI is not loading and not routing the traffic to the  backend pod.

**Comment by M00nF1sh** [comment]
@nandeeshb09 
Given you are migrating from CLB to ALB, do you aware of ALB's behaviors? I'm wondering where is the "server unavailable" came from, is it from ALB or from your backend application?

e.g. ALB currently didn't do any path rewrites, so if you access your app with `www.example.com/home/path`, then your backend pods must be able to handle http traffic with PATH "/home/path".

**Comment by nandeeshb09** [comment]
@M00nF1sh ,

Given you are migrating from CLB to ALB, do you aware of ALB's behaviors? I'm wondering where is the "server unavailable" came from, is it from ALB or from your backend application? --- Yes this is from backend server...

Yes , pods will handle the https traffic with those paths, but the problem is UI not able to connect to backend.

**Comment by M00nF1sh** [comment]
@nandeeshb09 
Didd your UI access the ALB correctly? e.g. you specified `host: hotsname` in your Ingress rules, which means the rules only applies for `hotsname`, so you need to access the ALB via the `hotsname` (e.g. by DNS cname).

Also, is the ALB/TargetGroups/SecurityGroups setup correctly in your AWS console?
