### ISSUE TITLE
Troubles configuring clientSecret for OIDC auth

### ISSUE THREAD

**Issue by Topher-the-Geek** [kubernetes-sigs/aws-load-balancer-controller#1838]
I have a lot of things working with this controller, and I'm delighted. Now I'm trying to configure the load balancer to use my Dex instance as an IDP, and I'm having troubles.

I've setup a secret with my `clientID` and `clientSecret`. I've setup the annotation `alb.ingress.kubernetes.io/auth-idp-oidc` on my ingress. I can verify in the EC2 Web UI that the rule is created on the load balancer as expected---expect of course I cannot see the `clientID` or `clientSecret` there. I can visit my web app, and I'm directed through the OAuth flow as expected. However, after granting access on the Dex screen and being redirected with a code to my web app, I'm getting "561 Authentication Error". In the Dex log I can see:

```
invalid client_secret on token request for client: k9U8PSgWpweFtGZ8Vtm9
```

This message nicely tells me that the load balancer has passed correct `clientID` through with the token request. But it seems that it's not passing the correct `clientSecret`. I can verify that the secret I've handed to the controller has the correct `clientSecret`. Also, in the EC2 Web UI, I can delete the authentication rule in the load balancer that the controller created, and I can manually add one that does work. So I'm suspecting that the controller didn't create the rule with the right secret. Unfortunately, everything wants to redacted the secret, so I cannot verify what secret the controller did use to create the rule.

Any advice on debugging? There's a whole lot of config to get this far, so I've tried to give you just the details that I think are relevant, but let me know if there's any other info that might help.

**Comment by Topher-the-Geek** [comment]
I couple additional helpful details. I'm running EKS with 1.18, and I installed the load balancer controller using the helm chart 1.1.5.

**Comment by kishorj** [comment]
@Topher-the-Geek, what does your ingress spec look like? Could you share the redacted version?

**Comment by Topher-the-Geek** [comment]
@kishorj Thank you for your reply. I got creative and intercepted the token request to see what in fact was being passed through to Dex for client_secret. That lead me right to the problem. I'm going to save you some steps.

[Here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/9776d298fddc1bb7fe9245510467d2507580ec96/internal/ingress/auth/auth.go#L167-L168)
```
clientId := strings.TrimRightFunc(string(k8sSecret.Data["clientId"]), unicode.IsSpace)
clientSecret := string(k8sSecret.Data["clientSecret"])
```

clientId is being trimmed, but clientSecret is not. I got a `\n` included at the end of the base64 encoding of clientSecret. I never noticed because I encoded it the same way as I encoded the clientId, and that was being handled correctly despite that it also included `\n` at the end. These `\n` were not visible to me when I looked at them through the Kubernetes dashboard.

Probably should trim both in the controller. In the meantime, I can handle this by just not adding the `\n` in the first place.

**Comment by M00nF1sh** [comment]
@Topher-the-Geek 
Thanks for the troubleshooting. We didn't do the same thing to clientSecret because we are not sure whether there will be cases whether clientSecret can end with whitespace or not..
should check whether there is RFC for such thing.

**Comment by M00nF1sh** [comment]
/kind documentation
Also, no matter what the behavior will be, we indeed should document it clearly.

**Comment by ismith** [comment]
I have also been bitten by this - it's a rather opaque issue to debug, since:
- clientSecret is (understandably) not visible in the AWS console or `aws elbv2 describe-rules`
- the oidc idp just responds 561
- trailing newlines are subtle - `... | base64 -d` _looks_ right ...

And easy to fall into; my workflow for creating the secret.yml was `echo ... | base 64 | xsel -ib`; what I wanted was `echo -n`, but that's easy to forget.

If trimming trailing whitespace like with clientID in #1216 isn't possible because a clientSecret _could_ end in whitespace, perhaps a note in the docs re: being careful to check for whitespace, and perhaps a mention of `echo -n` (as a likely tool in the process) would reduce this pain?
