### ISSUE TITLE
Example (doc) for 1 Ingress - > Multiple Services in different namespaces

### ISSUE THREAD

**Issue by ficofer** [kubernetes-sigs/aws-load-balancer-controller#1840]
Sorry team I got confused on ing-controller.

**Comment by kishorj** [comment]
@ficofer, I saw your earlier query in my email. This project is for the ingress controller for AWS ALB.

As for your query, the ingress has to be in the same namespace as your service. You can group multiple ingresses together via ingress group feature. If you create an ingress group, the controller will provision a signle ALB for the group and reconcile rules from all of the ingresses.
