### ISSUE TITLE
Use target IP instead of POD IP while configuring Target as IP method in NLB

### ISSUE THREAD

**Issue by jeffingn** [kubernetes-sigs/aws-load-balancer-controller#1842]
Hello,

Currently we have an option to use NLB with Target as IP using  AWS Load Balancer Controller as per the link [1]. But it uses POD IP instead of actual instance IP. 

We would like to configure it using TargetIP instead of POD IP. 

Customer use case:

1. Pods are more destructive than Instance IP - ie internal scheduling of K8s, deployments etc..

2. We run our services on spot instances

Reference
[1] https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html

**Comment by kishorj** [comment]
@jeffingn would instance targets not work for your use case? This controller will support instance mode in the upcoming v2.2.0 release. Support for instance targets is already there in the k8s in-tree controller.

**Comment by M00nF1sh** [comment]
closing this as the instance mode support PR is merged, we'll release it in v2.2.0.

**Comment by jeffingn** [comment]
Hello,

The target as instance do not work in this sceenario. The use case would require accessing the load balancer from the backend target . But Internal load balancers do not support hairpinning or loopback. Please refer the below link and check the topic "Connections time out for requests from a target to its load balancer"

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html
