### ISSUE TITLE
Set custom headers

### ISSUE THREAD

**Issue by jesstracy** [kubernetes-sigs/aws-load-balancer-controller#1848]
Hi, Looking through the documentation I'm trying to find a way to set a custom header before the request is sent to the backend, like can be done in the k8s nginx ingress controller here: https://kubernetes.github.io/ingress-nginx/examples/customization/custom-headers/#custom-headers
(I want to set the header `X-Request-Start: "t=${msec}"`)

Is that something that is already possible, or would you be open to possibly adding it in the future?
Thank you!

**Comment by M00nF1sh** [comment]
@jesstracy 
Sorry, that feature is not available currently since ALB itself doesn't support it yet.
Once ALB supports requests modification, we'll support it in this controller.

**Comment by jesstracy** [comment]
ah, got it. Thanks for getting back to me!
