### ISSUE TITLE
Multiple tagged subnets in AZ not working correctly when creating AWS ELB

### ISSUE THREAD

**Issue by tru-cstavares** [kubernetes-sigs/aws-load-balancer-controller#1853]
Our network setup has 4 subnets (in each AZ) as follows:

    1 subnet is public (1 AZ-a, 1 AZ-b, 1 AZ-c)
    1 subnet is private (1 AZ-a, 1 AZ-b, 1 AZ-c)
    1 subnet is private (1 AZ-a, 1 AZ-b, 1 AZ-c)
    1 subnet is private (1 AZ-a, 1 AZ-b, 1 AZ-c)

We use public subnet to create public ELBs. It happens that we run out of IPs on our public subnet, so the solution was to add additional CIDR block to our VPC. With this new setup we now have 2 public subnet per AZ (2 AZ-a, 2 AZ-b, 2 AZ-c). So the current status is:

    1 subnet is public (2 AZ-a, 2 AZ-b, 2 AZ-c)
    1 subnet is private (1 AZ-a, 1 AZ-b, 1 AZ-c)
    1 subnet is private (1 AZ-a, 1 AZ-b, 1 AZ-c)
    1 subnet is private (1 AZ-a, 1 AZ-b, 1 AZ-c)

With this new additional subnet we have now more IPs to instanciate new ELBs however, when we create a new service of type loadbalancer on EKS the creation fails since it still tries to use the previous subnet that have not enought IPs instead of using the new subnet. Both subnets in AZ are correctly tagged.

From your [documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/subnet_discovery/) it says that:

> In case of multiple tagged subnets in an Availability Zone, the controller will choose the first one in lexicographical order by the Subnet IDs.

in case of not enough IPs on first Subnet ID can controller try the other Subnet ID of same availablity zone?

BR

**Comment by kishorj** [comment]
@tru-cstavares, you could try specifying the subnets via annotation. 

For NLB, 
```
service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxx, subnet-yyy
```
The limitation for NLB is that you will have to specify the annotation during service creation, and not edit it later.

For ALB,
```
alb.ingress.kubernetes.io/subnets: subnet-xxx, subnet-yyy
```

**Comment by M00nF1sh** [comment]
auto-discovery is designed for simple use case where a set fixed subnet is always used as ELB subnets.
For cases like this, you have to specify the subnets. 
Also, in future releases, we might allow you to specify subnets in IngressClasses(for ALB) to avoid specify it on every Ingress.

**Comment by kishorj** [comment]
@tru-cstavares, I'm closing the issue. If you have further questions/concerns, feel free to reopen or create a new issue.
