### ISSUE TITLE
Can't access a game-2048 page with an ALB.

### ISSUE THREAD

**Issue by strada501** [kubernetes-sigs/aws-load-balancer-controller#1854]
I tried install an aws load balancer controller on my kops cluster(k8s v1.17.8) on my AWS account.
After installing an aws load balancer controller and sample game-2048 applications, but I can't reach game-2048 page.
I found the following errors in the logs of an aws-load-balancer-controller pod:

> {"level":"info","ts":1614850332.2526042,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-game2048-ingress2-93916313ab\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":80,\"toPort\":80,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-service-2048:80/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-game2048-ingress2-53ee75e893\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-01920f4a736f2e527\"},{\"subnetID\":\"subnet-03d97464b8669166e\"},{\"subnetID\":\"subnet-0843444d3f0d643c1\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\":{\"name\":\"k8s-game2048-service2-aef078f8c4\",\"targetType\":\"ip\",\"port\":80,\"protocol\":\"HTTP\",\"protocolVersion\":\"HTTP1\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-game2048-service2-aef078f8c4\",\"namespace\":\"game-2048\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-service-2048:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"service-2048\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}}}],\"ports\":[{\"protocol\":\"TCP\"}]}]}}}}}}}}"}
{"level":"info","ts":1614850333.0976968,"logger":"controllers.ingress","msg":"creating securityGroup","resourceID":"ManagedLBSecurityGroup"}
{"level":"info","ts":1614850333.354935,"logger":"controllers.ingress","msg":"created securityGroup","resourceID":"ManagedLBSecurityGroup","securityGroupID":"sg-09d279b8e57761add"}
{"level":"info","ts":1614850333.6097672,"msg":"authorizing securityGroup ingress","securityGroupID":"sg-09d279b8e57761add","permission":[{"FromPort":80,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"0.0.0.0/0","Description":""}],"Ipv6Ranges":null,"PrefixListIds":null,"ToPort":80,"UserIdGroupPairs":null}]}
{"level":"info","ts":1614850333.7492418,"msg":"authorized securityGroup ingress","securityGroupID":"sg-09d279b8e57761add"}
{"level":"info","ts":1614850335.188659,"logger":"controllers.ingress","msg":"creating targetGroup","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80"}
{"level":"info","ts":1614850335.6278405,"logger":"controllers.ingress","msg":"created targetGroup","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80","arn":"arn:aws:elasticloadbalancing:ap-northeast-1:111416579228:targetgroup/k8s-game2048-service2-aef078f8c4/7b9106835b223f4e"}
{"level":"info","ts":1614850335.9732656,"logger":"controllers.ingress","msg":"creating loadBalancer","stackID":"game-2048/ingress-2048","resourceID":"LoadBalancer"}
{"level":"info","ts":1614850336.6914213,"logger":"controllers.ingress","msg":"created loadBalancer","stackID":"game-2048/ingress-2048","resourceID":"LoadBalancer","arn":"arn:aws:elasticloadbalancing:ap-northeast-1:111416579228:loadbalancer/app/k8s-game2048-ingress2-53ee75e893/960bc41f2bfc4031"}
{"level":"info","ts":1614850336.73407,"logger":"controllers.ingress","msg":"creating listener","stackID":"game-2048/ingress-2048","resourceID":"80"}
{"level":"info","ts":1614850336.773712,"logger":"controllers.ingress","msg":"created listener","stackID":"game-2048/ingress-2048","resourceID":"80","arn":"arn:aws:elasticloadbalancing:ap-northeast-1:111416579228:listener/app/k8s-game2048-ingress2-53ee75e893/960bc41f2bfc4031/b4ea24dfd834f49a"}
{"level":"error","ts":1614850336.786887,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"ListenerNotFound: One or more listeners not found\n\tstatus code: 400, request id: 3e903227-68e8-4c3e-a220-a41a4874afce"}
{"level":"info","ts":1614850336.8902185,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-game2048-ingress2-93916313ab\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":80,\"toPort\":80,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-service-2048:80/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-game2048-ingress2-53ee75e893\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-01920f4a736f2e527\"},{\"subnetID\":\"subnet-03d97464b8669166e\"},{\"subnetID\":\"subnet-0843444d3f0d643c1\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\":{\"name\":\"k8s-game2048-service2-aef078f8c4\",\"targetType\":\"ip\",\"port\":80,\"protocol\":\"HTTP\",\"protocolVersion\":\"HTTP1\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-game2048-service2-aef078f8c4\",\"namespace\":\"game-2048\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-service-2048:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"service-2048\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}}}],\"ports\":[{\"protocol\":\"TCP\"}]}]}}}}}}}}"}
{"level":"info","ts":1614850339.221392,"logger":"controllers.ingress","msg":"creating listener rule","stackID":"game-2048/ingress-2048","resourceID":"80:1"}
{"level":"info","ts":1614850339.2807434,"logger":"controllers.ingress","msg":"created listener rule","stackID":"game-2048/ingress-2048","resourceID":"80:1","arn":"arn:aws:elasticloadbalancing:ap-northeast-1:111416579228:listener-rule/app/k8s-game2048-ingress2-53ee75e893/960bc41f2bfc4031/b4ea24dfd834f49a/98a9d85ccb38c257"}
{"level":"info","ts":1614850339.2808273,"logger":"controllers.ingress","msg":"creating targetGroupBinding","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80"}
{"level":"info","ts":1614850339.303399,"logger":"controllers.ingress","msg":"created targetGroupBinding","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80","targetGroupBinding":{"namespace":"game-2048","name":"k8s-game2048-service2-aef078f8c4"}}
{"level":"info","ts":1614850339.4140997,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"game-2048/ingress-2048"}
{"level":"error","ts":1614850339.4994721,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb]"}
{"level":"error","ts":1614850339.5612583,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb]"}
{"level":"error","ts":1614850339.6142538,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb]"}
{"level":"error","ts":1614850340.576101,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb]"}
{"level":"error","ts":1614850340.6856365,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb]"}
{"level":"error","ts":1614850340.8291376,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb]"}
{"level":"error","ts":1614850341.6333058,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}
{"level":"error","ts":1614850342.017205,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}
{"level":"error","ts":1614850342.3393767,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-qhf46 game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}
{"level":"error","ts":1614850342.7220871,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-qhf46 game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}
{"level":"error","ts":1614850345.3440433,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-qhf46 game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}
{"level":"error","ts":1614850350.5447164,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-qhf46 game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}
{"level":"error","ts":1614850360.9993918,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-qhf46 game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}
{"level":"error","ts":1614850381.5511308,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-aef078f8c4","namespace":"game-2048","error":"cannot resolve pod ENI for pods: [game-2048/deployment-2048-6c98cf98cd-857jq game-2048/deployment-2048-6c98cf98cd-qhf46 game-2048/deployment-2048-6c98cf98cd-7zfl2 game-2048/deployment-2048-6c98cf98cd-w2dwb game-2048/deployment-2048-6c98cf98cd-7wnwp]"}

but I can't resolve this errors.
Please show me how to resolve this issue.

I did the following instructions:
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

**Comment by M00nF1sh** [comment]
@strada501 
the example uses `alb.ingress.kubernetes.io/target-type: ip`, which relies on `amazon-vpc-cni-k8s`. (you can also create a kops cluster with this CNI too, but by default kops uses kubenet as cni).

you can remove that annotation, or use `alb.ingress.kubernetes.io/target-type: instance` instead.

**Comment by eibay** [comment]
I am not sure if this issue I am having right now below is related to this. @M00nF1sh I tried setting it to "instance" but it didn't work..

`{"level":"error","ts":1615031885.1953833,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: WebIdentityErr: failed to retrieve credentials\ncaused by: ValidationError: Request ARN is invalid\n\tstatus code: 400, request id: 3dca6dc3-be06-420a-b785-7b9974f9eccf"}
{"level":"error","ts":1615032253.9167805,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: WebIdentityErr: failed to retrieve credentials\ncaused by: ValidationError: Request ARN is invalid\n\tstatus code: 400, request id: cee7c6bc-42a3-4937-b93f-5ca454896615"}`

**Comment by strada501** [comment]
@M00nF1sh Thank you for your reply.
I can resolve my issue.
After I remove `alb.ingress.kubernetes.io/target-type: ip` , I can access game-2048 top page!!!
