### ISSUE TITLE
downtime when using readiness gates?

### ISSUE THREAD

**Issue by mfmbarros** [kubernetes-sigs/aws-load-balancer-controller#1858]
Hi,

My setup:
    EKS: 1.18 
     AWS LB Controller: 2.1.2
   
I recently configured AWS LB controller in my EKS in order to enable NLB-IP mode in my services and noticed the following:
 when rolling out my deployment, I see new pods being scheduled in cluster and consequently, a new set of pods entered in registering phase in NLB target group. When everything is healthy, the older pods are being deregistered (draining) and pods are terminating. However, in this phase  I noticed that some requests to my service are failling with connection timeout. The following request eventually went well but immediately a new request failed again with timeout and this erratic behaviour lasts for ~1m.
      
Could it be some lb controller misconfiguration?

I'm passing the following annotations in my service:

Annotations:     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
                          service.beta.kubernetes.io/aws-load-balancer-eip-allocations:
                            eipalloc-02462d6260e81282d,eipalloc-033d952b51b2f933a,eipalloc-048355233ec5bf8d0
                          service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: 2
                          service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: 10
                          service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: 2
                          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0fff8e90c77b94e6a,subnet-08aa7308ba0e0ac7f,subnet-08dce046feef77a4b
                          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes:
                            deregistration_delay.timeout_seconds=30,deregistration_delay.connection_termination.enabled=true
                          service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
   

Thanks

**Comment by kishorj** [comment]
@mfmbarros, you will have to add a preStop hook to ensure that your application pods don't get killed before the de-registration is complete, also modify terminationGracePeriodSeconds as appropriate. Try 4 to 5 mins of delay to ensure the target pod gets completely deregistered in the worst case.

**Comment by mfmbarros** [comment]
Thanks. I've just tested and it works with no downtime. However, I'm wondering,  let's say my 2 replicas' deployment is being served by a NLB-IP and the EC2 where one of those replicas is running goes down suddently or become unresponsive. At same point, NLB will start to drain/unregister my faulty pod and assuming it takes about 4/5 minutes, some requests to my service will fail during that amount of time, am I right?

**Comment by kishorj** [comment]
@mfmbarros, readiness gates doesn't help in case the pod goes down suddenly, or becomes unresponsive. In this case the NLB health probes fail, and the target is marked unhealthy. Targets are unregistered only when the pod gets deleted.

**Comment by kishorj** [comment]
@mfmbarros, I'm closing the issue for now. Feel free to reopen or create a new one if you have further questions/concerns.

**Comment by vladiceanu** [comment]
Hello @kishorj ,
I'm facing a similar issue: while the pod is in "deregistrating" state and the pod follows its SHUTDOWN procedure (SIGTERM -> Readiness close -> connections close -> etc.), some requests are still sent to it for approximately 20 seconds and timing out. 

>  Try 4 to 5 mins of delay to ensure the target pod gets completely deregistered in the worst case.

4 - 5 minutes sounds a lot to me, especially when we have 20 pods deployments. What is the deregistration time based on? Can we influence it in any way?
