### ISSUE TITLE
Unrecognized resource types in iam_policy.json

### ISSUE THREAD

**Issue by ctison** [kubernetes-sigs/aws-load-balancer-controller#1861]
When creating an IAM policy for the Kubernetes AWS load balancer controller as specified in step 3 of the [Installation Guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/), AWS IAM displays the following message in the console (after creation):
```
Unrecognized resource types: arn:aws:elasticloadbalancing:*:*:targetgroup/*/*
```

![image](https://user-images.githubusercontent.com/17789536/110203138-a7b29b00-7e6c-11eb-967b-3cbad82ef5e0.png)

IAM policy v2.1.3: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.1.3/docs/install/iam_policy.json

**Comment by kishorj** [comment]
@ctison, this is a UX issue, we've verified the permissions work. The ELB service in IAM policies refer to the classic load balancer which doesn't support targetgroup resources. The ELB v2 service in IAM policy is the one for NLB/ALB and it should have no errors.

**Comment by kishorj** [comment]
@ctison, we are closing the issue. If you have further questions/concerns, feel free to reopen or create a new issue.
