### ISSUE TITLE
Use target IP instead of POD IP while configuring Target as IP method in NLB - (workaround target as instance is not a viable solution also)

### ISSUE THREAD

**Issue by jeffingn** [kubernetes-sigs/aws-load-balancer-controller#1864]
Hello,

I am unable to reopen the issue #1842 (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1842). Hence creating a new issue. 

Currently we have an option to use NLB with Target as IP using AWS Load Balancer Controller as per the link [1]. But it uses POD IP instead of actual instance IP.

We would like to configure it using TargetIP instead of POD IP.

Customer use case:

Pods are more destructive than Instance IP - ie internal scheduling of K8s, deployments etc..

We run our services on spot instances

Also, The target as instance do not work in this sceenario. The use case would require accessing the load balancer from the backend target . But Internal load balancers do not support hairpinning or loopback. Please refer the below link and check the topic "Connections time out for requests from a target to its load balancer"

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html

Reference
[1] https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html

**Comment by M00nF1sh** [comment]
@jeffingn 
Do you mean use instance mode(use nodePort) but register instance IP instead of instanceID to bypass hairpinning issue?
it's not supported currently. we'll sync with ELB team whether they will provide features to disable perserveSourceIP when using instanceID. 

/kind feature

**Comment by kishorj** [comment]
@jeffingn 
NLB now supports disabling preserve client IP for instance targets as well with the exception of some instance types - for more details you can refer to the AWS documentation https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html

When preserve client IP is disabled, the hairpinning issue is no longer there for internal load balancer. Could you confirm whether this satisfies your use case? 

Instance mode will be supported in the upcoming v2.2.0 release.

**Comment by kishorj** [comment]
@jeffingn, I'm closing the issue for now. If you have further questions/concerns, feel free to reopen or create a new issue.
