### ISSUE TITLE
Support ElasticIPs

### ISSUE THREAD

**Issue by BenSlabbert** [kubernetes-sigs/aws-load-balancer-controller#1867]
Hello,

From what I can see there is no support to attach Elastic IPs to the created load balancer.

Am I mistaken or will this require a feature request?

Thanks in advance.

**Comment by kishorj** [comment]
@BenSlabbert, you can specify the EIPs via the annotation `service.beta.kubernetes.io/aws-load-balancer-eip-allocations`. The number of EIP allocations must match the number of subnets.

**Comment by BenSlabbert** [comment]
thank you @kishorj I found it in the documentation [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/#annotations)
