### ISSUE TITLE
bug report: adding ssl cert annotation to existing service of type load balancer

### ISSUE THREAD

**Issue by geoffcline** [kubernetes-sigs/aws-load-balancer-controller#1870]
**What happened:**
1. existing service with type load balancer on port 80
2. add "service.beta.kubernetes.io/aws-load-balancer-ssl-cert" annotation to the service
3. updating configuration of AWS NLB fails
4. I got this error in the console:

```
Error syncing load balancer: failed to ensure load balancer: error creating load balancer listener: "DuplicateListener: A listener already exists on this port for this load balancer 'arn:aws:elasticloadbalancing:us-east-2:<account_no>:loadbalancer/net/a40e9128b3cc445f598a9fe17571cd51/3e22e2d5abb8f7e9'\n\tstatus code: 400, request id: 2d69d4bd-fcf4-4a5f-baeb-6d80baf89c44"
```

**workaround:**
- deleting the AWS NLB in the console triggers a new NLB to be created with the proper SSL/TLS configuration. 

**what I expect to happen:**
- the LB controller adds a new listener to the NLB with the SSL cert.

**Comment by geoffcline** [comment]
any insights @M00nF1sh ? :)

**Comment by kishorj** [comment]
@geoffcline, what does your service annotation look like? Especially `service.beta.kubernetes.io/aws-load-balancer-type`. If the annotation value is not `nlb-ip`, then the load balancer is reconciled by the kubernetes in-tree controller, not this controller.

**Comment by kishorj** [comment]
@geoffcline, for nlb-ip, you will have to create a new service with `service.beta.kubernetes.io/aws-load-balancer-type` set to `nlb-ip` - note that we don't recommend modifying this annotation after creating the service. You can refer to the live docs for the prerequisites [[link](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/nlb_ip_mode/#prerequisites)].

**Comment by kishorj** [comment]
@geoffcline, I'm closing this issue. If you have further questions/concerns, feel free to reopen or create a new issue.

**Comment by fgendc** [comment]
Hello, having the same issue with the same DuplicateListener error.

Got an existing LoadBalancer, type is nlb, with both HTTP and HTTPS listeners but when adding annotation "service.beta.kubernetes.io/aws-load-balancer-ssl-cert" it fails to either remove HTTPS listener or change it to TLS.
