### ISSUE TITLE
Use existing load balancer

### ISSUE THREAD

**Issue by stephan-hartmann** [kubernetes-sigs/aws-load-balancer-controller#1872]
Is it possible to use an existing load balancer (NLB) instead of creating a new one when deploying a service?
Background: I'm building my infrastructure stack with Pulumi. When I tear down my stack, the NLB that has been created by the aws load balancer controller won't get deleted and I have to delete it manually.
To address this issue, I would like to create the load balancer (NLB) with Pulumi and then hand it over to the service (or ingress in case of ALB) e.g. via an annotation.
Another reason is that I also need to have a reference to the load balancer for other resource (i.e. service endpoint).

Thanks,
Stephan

**Comment by kishorj** [comment]
@stephan-hartmann, here is a potential solution if you want to manage NLB outside of k8s -
- Create NLB and add the listeners and target groups externally
- Create a k8s service of type ClusterIP or NodePort (without any of the aws annotations). For instance targets, you must use NodePort service
- Create targetgroup bindings for your externally managed target groups, and refer to the service created in the above steps to associate with the backend pods

**Comment by kishorj** [comment]
@stephan-hartmann also consider deleting the service before deleting the cluster. This will ensure load balancer resource get cleaned up properly.

**Comment by rifelpet** [comment]
I have a similar feature request but for a different reason:

I have an existing NLB that I'd like aws-load-balancer-controller to "inherit". Ideally I could just add all of the expected tags to the NLB that align with the annotations of a service I create, and aws-load-balancer-controller will treat the NLB the same as if it had created the NLB all along, just ignoring the differing load balancer name.

I could see this workflow being supported as a result of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1483 but there hasn't been an update on that recently. @kishorj any idea when that might get implemented?

**Comment by stephan-hartmann** [comment]
Thank you so much @kishorj, I think this is exactly what I was looking for :)

**Comment by kishorj** [comment]
@rifelpet, there are two outstanding feature requests
1. #1483 - For the ability to specify a custom load balancer name via annotation instead the controller auto generating it
   This is fairly straightforward and we will implement in the upcoming releases (PRs are welcome :D)
1. #1573 - Ability to specify load balancer ARN via annotation
   It is in our long term roadmap, but have some security concerns to iron out. You can provide further comments in the discussion.

I'm closing this issue. If there are further questions/concerns feel free to reach out to us.

**Comment by kishorj** [comment]
@stephan-hartmann, 
- what is your target type? instance or ip?
- If instance type, what is the externalTrafficPolicy on the underlying nodeport service?
- would your health check port be different from traffic port?

You can specify the sg rules in the targetgroupbinding spec. Here is an example - 

```
spec:
  networking:
    ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
      - port: 31249
        protocol: TCP
    - from:
      - ipBlock:
          cidr: 192.168.32.0/19
      - ipBlock:
          cidr: 192.168.0.0/19
      - ipBlock:
          cidr: 192.168.64.0/19
      ports:
      - port: 32424
        protocol: TCP
```

In the above example, there are rules to allow port 31249 from everywhere for traffic, and 32424 from the load balancer subnet CIDRS for health check.

**Comment by stephan-hartmann** [comment]
@kishorj thanks for your valuable support, I really appreciate it!
This works in principal but first let me answer your questions:
- what is your target type? instance or ip?
instance
- If instance type, what is the externalTrafficPolicy on the underlying nodeport service?
Cluster
- would your health check port be different from traffic port?
no

The only problem I have is to know the nodePort. Is the a way that the lb controller can find out the port from the nodeport service?
I set up my infrastructure and the k8s resources with Pulumi so the only solution I see is to define a nodePort explicitly, but that carries the risk of collisions.
