### ISSUE TITLE
Delete operation is attempted on the security group provided in alb.ingress.kubernetes.io/security-groups annotation

### ISSUE THREAD

**Issue by kamatvishal** [kubernetes-sigs/aws-load-balancer-controller#1876]
I have an EKS cluster and I am using aws-load-balancer-controller:v2.1.1. I am using the below aws alb ingress

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-alb-ingress
  namespace: myns
  labels: 
    app: myns-alb-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Team=myteam
    alb.ingress.kubernetes.io/group.name: my-apps
    alb.ingress.kubernetes.io/certificate-arn: arn:xxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```
Also there is a security group "sg-xxxxc91467c97bbb" with the description "[k8s] Managed SecurityGroup for LoadBalancer".

I have a bunch of IP addresses added in this Security Group as inbound rules. Now whenever I add any host rules (path/ backend service ) and apply this ingress, all the inbound rules of this security group gets deleted and 0.0.0.0/0 gets added automatically.

**Issue # 1: How do I prevent the inbound rules of this security group from being wiped**

I tried few things to overcome this. Tried adding this annotation

`alb.ingress.kubernetes.io/security-groups: sg-xxxxc91467c97bbb`

and this helps retaining the inbound rules. However I see the below in the aws load balancer controller now

```
kubectl logs -n kube-system   deployment.apps/aws-load-balancer-controller
{"level":"info","ts":1615287229.3065767,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-xxxxc91467c97bbb"}
```

and in the kubectl describe ingress output, I see events like

```
Events:
  Type     Reason             Age                    From     Message
  ----     ------             ----                   ----     -------
  Warning  FailedDeployModel  5m2s (x9 over 20m)  ingress  Failed deploy model due to failed to delete securityGroup: timed out waiting for the condition
```

**Issue # 2: If I provide the security group in the annotations, the inbound rules are retained but something tries to delete the security group itself which I don't want.**

Any suggestions on how to overcome the two issues?

**Comment by M00nF1sh** [comment]
@kamatvishal
This is expected(and designed behavior). 
when `alb.ingress.kubernetes.io/security-groups` annotation not specified, the controller will provision and **manage** a SG for LoadBalanacer,  and automatically modify worker node SG rules to allow access from this managed LB securityGroup. By manage, it means the controller fully owns all rules in that securityGroup.  You can control the CIDRs to allow access via [`alb.ingress.kubernetes.io/inbound-cidrs`](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#inbound-cidrs) annotation

when `alb.ingress.kubernetes.io/security-groups` specified, users should use a SG created by you(instead of a SG created by the controller), and users are responsible for updating worker SG rules.

**Comment by kamatvishal** [comment]
Thanks @M00nF1sh for the response. So does it mean

1. If `alb.ingress.kubernetes.io/security-groups` is provided with a SG that is created by me, the default SG that was created for the LB  ([k8s] Managed SecurityGroup for LoadBalancer) will be deleted?
2. If I don't provide `alb.ingress.kubernetes.io/security-groups` annotation but manually attach a newly created SG by me to the LB, the controller would delete this newly added SG from the LB and only keep the default SG ([k8s] Managed SecurityGroup for LoadBalancer)?

Also while using `alb.ingress.kubernetes.io/inbound-cidrs` annotation, I don't see a provision to provide the description for each CIDR. Is there any other way of providing the description?

**Comment by M00nF1sh** [comment]
@kamatvishal 
Your two assumptions is correct.
Yes, we don't provide a way to set description for the rules managed by the controller.

**Comment by kamatvishal** [comment]
Thanks @M00nF1sh appreciate your response. Closing this as it is not an issue.
