### ISSUE TITLE
Ingress is stuck while deleting. Cause AWS-LoadBalancer-Controller is not able to delete the ALB Security group it has created.

### ISSUE THREAD

**Issue by kakarotbyte** [kubernetes-sigs/aws-load-balancer-controller#1879]
Issue:
-
- Launching ingress will create resources without any problem.  Deleting Ingress is getting stuck. 

 -  logs have the following events 
 - while creation.:  
    -   created securityGroup                        - Will create SG for ALB
    -   authorized securityGroup ingress     - Will add rules to the ALB SG
    -   created targetGroup                           - Will create targetGroup  to be assigned to Loadbalancer.
    -    created loadBalancer                         - Will create a LoadBalancer.
    -    created listener                                   - the port on which loadbalancer will be listening on.
    -  created listener rule                            - Rules to forward to the targets (target groups in our case)
    -  created targetGroupBinding              - Will create a custom resource which maintains target groups and assignment/removal of ELB SG rule from worker node security group inbound rule.
    - authorized securityGroup ingress     - adding ELB SG as an inbound rule to the worker node’s SG
    - registered targets                                 - All the concerned targets are registered.
 
- while Deleting:
      - deleting loadBalancer
       - deleted loadBalancer
       - deleting targetGroupBinding
       - deRegistering targets
       #####This step is missing in logs######  - revoking securityGroup ingress 
       - deleted targetGroupBinding
       - deleting targetGroup
       - deleted targetGroup
       - deleting securityGroup
        ###  Waits and times out. ###

**Creating Ingress:** 

    {"level":"info","ts":1615573916.5910168,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-game2048-ingress2-d569118d1d\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":80,\"toPort\":80,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-2-deployment-2048:80/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-game2048-ingress2-5f73974abf\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-02401487562661d6b\"},{\"subnetID\":\"subnet-0a5a8517ddd407386\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"game-2048/ingress-2048-2-deployment-2048:80\":{\"spec\":{\"name\":\"k8s-game2048-deployme-eaaffd25f8\",\"targetType\":\"instance\",\"port\":30040,\"protocol\":\"HTTP\",\"protocolVersion\":\"HTTP1\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"game-2048/ingress-2048-2-deployment-2048:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-game2048-deployme-eaaffd25f8\",\"namespace\":\"game-2048\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-2-deployment-2048:80/status/targetGroupARN\"},\"targetType\":\"instance\",\"serviceRef\":{\"name\":\"deployment-2048\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}}}],\"ports\":[{\"protocol\":\"TCP\"}]}]}}}}}}}}"}
    {"level":"info","ts":1615573916.7312713,"logger":"controllers.ingress","msg":"creating securityGroup","resourceID":"ManagedLBSecurityGroup"}
    {"level":"info","ts":1615573916.9273224,"logger":"controllers.ingress","msg":"created securityGroup","resourceID":"ManagedLBSecurityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"info","ts":1615573917.0983446,"msg":"authorizing securityGroup ingress","securityGroupID":"sg-0f586c967c97088d7","permission":[{"FromPort":80,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"0.0.0.0/0","Description":""}],"Ipv6Ranges":null,"PrefixListIds":null,"ToPort":80,"UserIdGroupPairs":null}]}
    {"level":"info","ts":1615573917.2171466,"msg":"authorized securityGroup ingress","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"info","ts":1615573917.4708657,"logger":"controllers.ingress","msg":"creating targetGroup","stackID":"game-2048/ingress-2048-2","resourceID":"game-2048/ingress-2048-2-deployment-2048:80"}
    {"level":"info","ts":1615573917.7708743,"logger":"controllers.ingress","msg":"created targetGroup","stackID":"game-2048/ingress-2048-2","resourceID":"game-2048/ingress-2048-2-deployment-2048:80","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:targetgroup/k8s-game2048-deployme-eaaffd25f8/1c4f73a63fdd2ac1"}
    {"level":"info","ts":1615573917.8701153,"logger":"controllers.ingress","msg":"creating loadBalancer","stackID":"game-2048/ingress-2048-2","resourceID":"LoadBalancer"}
    {"level":"info","ts":1615573918.4064794,"logger":"controllers.ingress","msg":"created loadBalancer","stackID":"game-2048/ingress-2048-2","resourceID":"LoadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:loadbalancer/app/k8s-game2048-ingress2-5f73974abf/69aa89deda96779a"}
    {"level":"info","ts":1615573918.432617,"logger":"controllers.ingress","msg":"creating listener","stackID":"game-2048/ingress-2048-2","resourceID":"80"}
    {"level":"info","ts":1615573918.4699438,"logger":"controllers.ingress","msg":"created listener","stackID":"game-2048/ingress-2048-2","resourceID":"80","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:listener/app/k8s-game2048-ingress2-5f73974abf/69aa89deda96779a/b00458f3f1ec4509"}
    {"level":"info","ts":1615573918.48435,"logger":"controllers.ingress","msg":"creating listener rule","stackID":"game-2048/ingress-2048-2","resourceID":"80:1"}
    {"level":"info","ts":1615573918.528814,"logger":"controllers.ingress","msg":"created listener rule","stackID":"game-2048/ingress-2048-2","resourceID":"80:1","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:listener-rule/app/k8s-game2048-ingress2-5f73974abf/69aa89deda96779a/b00458f3f1ec4509/469c0a2fc0ed7383"}
    {"level":"info","ts":1615573918.528914,"logger":"controllers.ingress","msg":"creating targetGroupBinding","stackID":"game-2048/ingress-2048-2","resourceID":"game-2048/ingress-2048-2-deployment-2048:80"}
    {"level":"info","ts":1615573918.5499268,"logger":"controllers.ingress","msg":"created targetGroupBinding","stackID":"game-2048/ingress-2048-2","resourceID":"game-2048/ingress-2048-2-deployment-2048:80","targetGroupBinding":{"namespace":"game-2048","name":"k8s-game2048-deployme-eaaffd25f8"}}
    {"level":"info","ts":1615573918.5760646,"msg":"authorizing securityGroup ingress","securityGroupID":"sg-031fbe94175d7e066","permission":[{"FromPort":0,"IpProtocol":"tcp","IpRanges":null,"Ipv6Ranges":null,"PrefixListIds":null,"ToPort":65535,"UserIdGroupPairs":[{"Description":"elbv2.k8s.aws/targetGroupBinding=shared","GroupId":"sg-0f586c967c97088d7","GroupName":null,"PeeringStatus":null,"UserId":null,"VpcId":null,"VpcPeeringConnectionId":null}]}]}
    {"level":"info","ts":1615573918.7534945,"msg":"authorized securityGroup ingress","securityGroupID":"sg-031fbe94175d7e066"}
    {"level":"info","ts":1615573918.753537,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:targetgroup/k8s-game2048-deployme-eaaffd25f8/1c4f73a63fdd2ac1","targets":[{"AvailabilityZone":null,"Id":"i-03c3704088426fd5e","Port":30040},{"AvailabilityZone":null,"Id":"i-04c99dd8ae6ea7dcf","Port":30040},{"AvailabilityZone":null,"Id":"i-05a259495b04177d1","Port":30040},{"AvailabilityZone":null,"Id":"i-0d88a603160eba565","Port":30040},{"AvailabilityZone":null,"Id":"i-0e4087821bd51b262","Port":30040}]}
    {"level":"info","ts":1615573918.971722,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:targetgroup/k8s-game2048-deployme-eaaffd25f8/1c4f73a63fdd2ac1"}
    {"level":"info","ts":1615573921.26484,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"game-2048/ingress-2048-2"}
    
    
**Deleting ingress:**

    {"level":"info","ts":1615573933.624165,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615573934.403732,"logger":"controllers.ingress","msg":"deleting loadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:loadbalancer/app/k8s-game2048-ingress2-5f73974abf/69aa89deda96779a"}
    {"level":"info","ts":1615573934.4640892,"logger":"controllers.ingress","msg":"deleted loadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:loadbalancer/app/k8s-game2048-ingress2-5f73974abf/69aa89deda96779a"}
    {"level":"info","ts":1615573934.4642053,"logger":"controllers.ingress","msg":"deleting targetGroupBinding","targetGroupBinding":{"namespace":"game-2048","name":"k8s-game2048-deployme-eaaffd25f8"}}
    {"level":"info","ts":1615573934.502075,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:targetgroup/k8s-game2048-deployme-eaaffd25f8/1c4f73a63fdd2ac1","targets":[{"AvailabilityZone":null,"Id":"i-03c3704088426fd5e","Port":30040},{"AvailabilityZone":null,"Id":"i-0d88a603160eba565","Port":30040},{"AvailabilityZone":null,"Id":"i-0e4087821bd51b262","Port":30040},{"AvailabilityZone":null,"Id":"i-05a259495b04177d1","Port":30040},{"AvailabilityZone":null,"Id":"i-04c99dd8ae6ea7dcf","Port":30040}]}
    {"level":"info","ts":1615573934.5375626,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:targetgroup/k8s-game2048-deployme-eaaffd25f8/1c4f73a63fdd2ac1"}
    {"level":"info","ts":1615573934.674162,"logger":"controllers.ingress","msg":"deleted targetGroupBinding","targetGroupBinding":{"namespace":"game-2048","name":"k8s-game2048-deployme-eaaffd25f8"}}
    {"level":"info","ts":1615573934.6741986,"logger":"controllers.ingress","msg":"deleting targetGroup","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:targetgroup/k8s-game2048-deployme-eaaffd25f8/1c4f73a63fdd2ac1"}
    {"level":"info","ts":1615573936.7798157,"logger":"controllers.ingress","msg":"deleted targetGroup","arn":"arn:aws:elasticloadbalancing:us-east-1:991242130495:targetgroup/k8s-game2048-deployme-eaaffd25f8/1c4f73a63fdd2ac1"}
    {"level":"info","ts":1615573936.7798467,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574057.601004,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574057.60624,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574058.4520416,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574143.4115403,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-99d7d1ed30","namespace":"game-2048","error":"Service \"service-2048\" not found"}
    {"level":"error","ts":1615574145.7253807,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"ingress: game-2048/ingress-2048: Service \"service-2048\" not found"}
    {"level":"error","ts":1615574179.2232325,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574179.233499,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574180.1235468,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574300.8319676,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574300.8522952,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574301.4767795,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574422.1812649,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574422.221527,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574422.9222147,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574543.7580657,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574543.8383646,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574544.567872,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574665.3016562,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574665.4619308,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574666.2247941,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574786.9304166,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574787.250984,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574787.8373125,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615574798.7718012,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-99d7d1ed30","namespace":"game-2048","error":"Service \"service-2048\" not found"}
    {"level":"error","ts":1615574801.302523,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"ingress: game-2048/ingress-2048: Service \"service-2048\" not found"}
    {"level":"error","ts":1615574908.7046163,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615574909.3448658,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615574910.1083722,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615575030.8196366,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615575032.099989,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615575032.7105463,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615575153.4098299,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615575155.9700658,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615575156.7179873,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615575277.4268694,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615575282.5473304,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615575283.1888723,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615575404.092654,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615575414.3329256,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615575415.0070148,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615575535.8077579,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615575556.2880208,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615575556.9507792,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615575677.649595,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615575718.609941,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615575719.3012247,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615575798.7721074,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-99d7d1ed30","namespace":"game-2048","error":"Service \"service-2048\" not found"}
    {"level":"error","ts":1615575801.4968414,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"ingress: game-2048/ingress-2048: Service \"service-2048\" not found"}
    {"level":"error","ts":1615575840.1898646,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615575922.1101327,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615575922.756585,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615576043.4803133,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    {"level":"info","ts":1615576207.3206213,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048-2\",\"resources\":{}}"}
    {"level":"info","ts":1615576207.9951148,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0f586c967c97088d7"}
    {"level":"error","ts":1615576311.7751284,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-99d7d1ed30","namespace":"game-2048","error":"Service \"service-2048\" not found"}
    {"level":"error","ts":1615576328.7744353,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048-2","namespace":"game-2048","error":"failed to delete securityGroup: timed out waiting for the condition"}
    error: read tcp 10.95.181.248:58279->52.1.202.169:443: read: operation timed out
   
   
   
**Replication steps:**
   - create service(svc-1) and ingress(ing-1) referencing it.
    - delete svc-1(but keep the ingress ing-1)
    - **restart the controller**. Issue only occurs when we restart the controller.
    - create new service(svc-2) and new ingress(ing-2)
    - delete ing-2
    - Ing-2 will be stuck in delete state.   
   - Fix will be to either deleting the ingress 1 or adding the removed service 1 to reconcile everything back. 
 
 **Cause of the issue:**
 
- Targetgroupbinding resource tries to reconcile service 1 before it goes and delete the ALB SG rule attached to the Worker node. 
        {"level":"error","ts":1615574143.4115403,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-game2048-service2-99d7d1ed30","namespace":"game-2048","error":"Service \"service-2048\" not found"}

Ask:   
- Controller should handle the deleted service as no targets behind loadbalancer while reconciling.

**Comment by M00nF1sh** [comment]
This is an known issue and will be fixed in v2.2.0.

**Comment by cmsmith7** [comment]
@M00nF1sh that is great news, thank you.

**Comment by M00nF1sh** [comment]
reopen this for visibility, will close once we release v2.2.0

**Comment by cmsmith7** [comment]
Hi M00nF1sh .. do you have a release date for v2.2.0? thanks again.

**Comment by kishorj** [comment]
closing the issue since v2.2.0 is out - https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0

**Comment by sergeevo** [comment]
Hi @M00nF1sh, @kishorj  - It looks like we're facing the same issue with the latest version. The Ingress resource deletion gets stuck on the security group deletion. Here is the controller log:
> {"level":"info","ts":1623228692.0993183,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-*"}
{"level":"error","ts":1623228812.7212946,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"my-ingress","namespace":"my-namespace","error":"failed to delete securityGroup: timed out waiting for the condition"}

And the corresponding CloudTrail event error:
> "errorCode": "Client.DependencyViolation",
"errorMessage": "resource sg-* has a dependent object",

What additional information could help to identify the root cause?

**Comment by kishorj** [comment]
@sergeevo, what is the version of your controller? If it is v2.2.0, please open a new issue.

**Comment by bartmanus** [comment]
I am hitting this issue after upgrade from controller v1.1.3 to v2.4.2.

It took a lot of research but I finally discovered it is due to a missing ingress rule description in the EKS worker node's security group. This exact case has a Backwards Compatibility [chapter](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.4.2/docs/deploy/upgrade/migrate_v1_v2.md#backwards-compatibility) in the migration guide.

**Comment by geocomm-shenningsgard** [comment]
I'm also hitting this issue after clean install on a new 1.28 EKS cluster with aws-load-balancer-controller v2.6.2 - can we re-open this?

Note - as far as I can see, the Load Balancer, Target Groups, and Security Group have all successfully been deleted, but this is preventing the Ingress resource from being deleted.

```{"level":"error","ts":"2024-01-25T13:55:56Z","msg":"Reconciler error","controller":"ingress","object":{"name":"my-cool-group-name"},"namespace":"","name":"my-cool-group-name","reconcileID":"57cb27b3-7f99-47f8-b829-9dbc4c9c90f9","error":"failed to delete securityGroup: timed out waiting for the condition"}
{"level":"info","ts":"2024-01-25T14:12:36Z","logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"my-cool-group-name\",\"resources\":{}}"}
{"level":"info","ts":"2024-01-25T14:12:37Z","logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"my-cool-group-name"}
{"level":"error","ts":"2024-01-25T14:14:37Z","msg":"Reconciler error","controller":"ingress","object":{"name":"my-cool-group-name"},"namespace":"","name":"my-cool-group-name","reconcileID":"78046cae-c848-46a9-8990-f2cfd81c3f83","error":"failed to delete securityGroup: timed out waiting for the condition"}
{"level":"info","ts":"2024-01-25T14:31:17Z","logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"my-cool-group-name\",\"resources\":{}}"}
{"level":"info","ts":"2024-01-25T14:31:18Z","logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"my-cool-group-name"}
{"level":"error","ts":"2024-01-25T14:33:19Z","msg":"Reconciler error","controller":"ingress","object":{"name":"my-cool-group-name"},"namespace":"","name":"my-cool-group-name","reconcileID":"a97ada5a-1539-4f7f-a76d-af58fa1f9ff0","error":"failed to delete securityGroup: timed out waiting for the condition"}```
