### ISSUE TITLE
How to configure using the private cluster

### ISSUE THREAD

**Issue by mohanrao** [kubernetes-sigs/aws-load-balancer-controller#1882]
Hi,

I have a private cluster with vpc configured in us-west-1 with ecr private endpoint configured. 

When i use the default ingress controller deployed it is using the image us-west-2.  Ingress pods are not starting. 

Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned kube-system/aws-load-balancer-controller-5b46b74769-2798g to ip-10-192-2-219.us-west-1.compute.internal
  Normal   Pulling    10m (x4 over 18m)     kubelet            Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.3"
  Warning  Failed     7m49s (x4 over 16m)   kubelet            Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.3": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     7m49s (x4 over 16m)   kubelet            Error: ErrImagePull
  Normal   BackOff    7m12s (x8 over 16m)   kubelet            Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.3"
  Warning  Failed     3m22s (x15 over 16m)  kubelet            Error: ImagePullBackOff

Is there any way to change the image to be pulled from us-west-1 ?

**Comment by mohanrao** [comment]
I went ahead and edited the image name of the deployment with kubectl edit. and the deployment is success

**Comment by kishorj** [comment]
@mohanrao, we post the ECR images to all supported regions. You can find the ECR repo URLs from the release notes - For 2.1.3, https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.1.3.

**Comment by mohanrao** [comment]
yes @kishorj  but how do we configure it as part of helm install to use from a certain region ?  We want to automate this for more clusters

**Comment by kishorj** [comment]
You can specify the repository as part of helm install/upgrade command. For example 
```
 helm upgrade -i <other options> --set image.repository=602401143452.dkr.ecr.us-west-1.amazonaws.com/amazon/aws-load-balancer-controller
```

**Comment by mohanrao** [comment]
Thank you!
