### ISSUE TITLE
Support http status code when the ALB backend protocol version is set to gRPC

### ISSUE THREAD

**Issue by Sushma10037017** [kubernetes-sigs/aws-load-balancer-controller#1883]
Hi,
We use AWS application load balancer to expose the ambassador API gateway(v1.2.2) deployed in our Kubernetes cluster(v1.7), through which we want to support gRPC calls.
AWS ALB supports gRPC as the backend protocol version but looks like it expects the health checks to return the gRPC status code.

If the service does not expose a gRPC healthcheck endpoint, is there any option to use HTTP endpoints and status codes for health check? Any recommendations around this are appreciated.

AWS load balancer controller version used : v2.1.0
Thanks!.

**Comment by M00nF1sh** [comment]
@Sushma10037017 
seems currently there isn't a way to achieve it. There isn't a healthcheck protocol version available. 
we'll forward this feature request to ALB team.

**Comment by Sushma10037017** [comment]
@M00nF1sh Thanks!

**Comment by M00nF1sh** [comment]
@Sushma10037017 already forward the feature request to ALB's PM. 
closing this issue and track it in the aggregated ALB/NLB feature request issue instead: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571
