### ISSUE TITLE
EKS IAM role as service does not work as expected, the node is also requiring permission

### ISSUE THREAD

**Issue by jayeshnazre** [kubernetes-sigs/aws-load-balancer-controller#1885]
I have followed all the steps mentioned in the link below
[https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/ ](url)

**Environment details**
1. EKS
2. Kubernetes v1.18
3. eksctl to create EKS cluster (v 0.40.0)
4. Used helm chart to deploy the aws load balancer controller, helm client version: "v3.5.1"

**Expected behavior** - No IAM permission should be needed to be applied to the EKS worker node role as outlined in the step 4 of the link [https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/](url) 

**Issue description:**
When I created an Ingress resource, I saw error logs in my aws load balancer controller pod stating the following:

_"Failed deploy model due to UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ........"_

**What I did to make it work:**
I looked at AWS CloudTrail and decoded the encoded log message from my aws load balancer controller pod and found out that the worker nodes of EKS needed some access rights, I did not check to see what exact rights were needed but instead applied the IAM policy in the step 2 of the link [https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/](url)  to my worker nodes IAM role. As soon as I did that it started working and a ALB was provisioned. But this defeats the whole purpose of removing access from worker nodes and assigning them to the pods via IAM role as a service approach.
Is this not a bug?  Am I missing something

**Comment by kishorj** [comment]
@jayeshnazre, with IRSA setup, you don't need to configure additional IAM policies in the worker nodes. Couple of things to make sure 
- The service account gets created via `eksctl create iamserviceaccount` command before the load balancer pods
- helm install/upgrade command has `--set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller`
- if there was an existent service account with the same name before `eksctl create iamserviceaccount was run` - https://github.com/weaveworks/eksctl/issues/2665. The workaround for this issue is to run `eksctl delete iamserviceaccount` and `eksctl create iamserviceaccount` again.
- aws-iam-token is mounted in the lb controller pod

**Comment by jayeshnazre** [comment]
@ kishorj thanks for responding 
I have done/checked all the things you mentioned in your four bullet points and based on what I can tell it should work but it does not work until I assign the IAM policy to worker node role as well.  
Take a look at the following link - [https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1171](url), the issue explained there is not the same but in the discussion one person @ahrtr   commented that when you add the policy to nodes it works. Any pointers as this should work based on what is described in link - [https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/](url)

**Comment by jayeshnazre** [comment]
@kishorj Below are the simple steps I used

**Step1:** 
eksctl create cluster -f eksctlconfig1.yml
eksctlconfig1.yml file contents: 
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: myeksctlcluster1
  region: "us-east-1"
  version: "1.18"
managedNodeGroups:
- name: myeksctlng1
  desiredCapacity: 2
  minSize: 1
  maxSize: 2
  instanceType: t3.medium
  ssh:
    allow: true
    publicKeyPath: mykey.pub
availabilityZones: ['us-east-1a', 'us-east-1b']

 
**Step2:** 
eksctl utils associate-iam-oidc-provider \
    --region us-east-1 \
    --cluster myeksctlcluster1 \
    --approve

**Step3** (download the iam-policy.json from [https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.2/docs/install/iam_policy.json](url) ): 

aws iam create-policy \
    --policy-name AWSLoadBalancerControllerIAMPolicy \
    --policy-document file://iam-policy.json

**Step4:**	
	
eksctl create iamserviceaccount \
--cluster=myeksctlcluster1 \
--namespace=kube-system \
--name=aws-load-balancer-controller \
--attach-policy-arn=arn:aws:iam::XXXX:policy/AWSLoadBalancerControllerIAMPolicy \
--override-existing-serviceaccounts \
--approve

**Step5:**
helm repo add eks https://aws.github.io/eks-charts

**Step6:**
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"


**Step7:**
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
-n kube-system --set serviceAccount.create=false --set clusterName=myeksctlcluster1 \
--set enableShield=false --set enableWaf=false --set enableWafv2=false --set logLevel=debug

Any pointers to troubleshoot?

**Comment by kishorj** [comment]
- check if your serviceaccount has the annotation 
```
eks.amazonaws.com/role-arn: arn:aws:iam::xxxx:role/eksctl-<cluster>-addon-iamserviceaccount-kube-Role1-xxxx
```
- controller pod should have the aws-iam-token volume
```
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
```
- and the mount
```
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
```

**Comment by jayeshnazre** [comment]
@kishorj Thanks once again for responding. I started a fresh EKS cluster with the steps I mentioned above. 

**For serviceaccount has the annotation:** 
I have checked and it looks good (see below)
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXX:role/eksctl-myeksctlcluster1-addon-iamserviceacco-Role1-17VN35J6Y9RVK
  creationTimestamp: "2021-03-16T20:10:37Z"
.........

**For controller pod should have the aws-iam-token volume:**
I think you are correct I do not see those mounts in the controller pod, however I am not creating the controller pod the helm chart as mentioned in Step7 (in my above section is) , so what is causing this not to work the way its stated in the link (step 3 - Add Controller to Cluster) [https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/](url)

    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4hj9p (ro)
Volumes:
  cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aws-load-balancer-tls
    Optional:    false
  default-token-4hj9p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4hj9p
    Optional:    false

**NOTE: I also just for fun deleted the pod so it is auto-launched but still do not see the volume mounts. Any pointers as the steps are exactly how its defined in the official documentation?**

**Comment by jayeshnazre** [comment]
@kishorj Any pointers, why the the EKS control plane (admission plugins) when the helm chart creates the AWS load balancer controller is not mounting the aws-iam-token volume in the controller POD?

**Comment by M00nF1sh** [comment]
@jayeshnazre 
we'll need your cluster arn to troubleshot. It's related to the IAM-For-SA setup. I cannot spot any error from your steps above.
would you help share your cluster-arn to us?

**Comment by jayeshnazre** [comment]
@M00nF1sh 
I can share it but because I use my personal aws account I typically delete the EKS to save money. Are you not able to do the steps what I did at your end and recreate the problem? 
I am literally doing the same steps mentioned above (nothing fancy :) ) and it is giving me the error as the mounts are missing in the controller pod.  

Is there a way we can time this so when I am doing it you are aware that I am doing it and that way you can check the logs and then I can purge it. Let me know if that works for you? If "yes" - mention some date and time when you want to do it and I can fire up the cluster and email you once its done. Let me know what works best for you. I am on EST zone.

**Comment by M00nF1sh** [comment]
@jayeshnazre 
you can find me by @M00nF1sh  in Kubernetes slack, and we can discuss there for a slot.

**Comment by M00nF1sh** [comment]
You need to update your helm command to have `--set serviceAccount.name=aws-load-balancer-controller`. 
We have it in our docs: https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

Wondering where did you get the command without it, let us know and we’ll update the docs accordingly 😄

**Comment by jayeshnazre** [comment]
@kishorj  and @M00nF1sh  - guys you nailed it. A simple flag like "--set serviceAccount.name=aws-load-balancer-controller"  missing in the documentation [https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/](url) and I was looking all over the place 👍  🥇
