### ISSUE TITLE
Issue with resource tags in documentation

### ISSUE THREAD

**Issue by georgew5656** [kubernetes-sigs/aws-load-balancer-controller#1886]
**Context**
Hi, according to the live documentation (https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#resource-tags), all resources created by the aws lb controller should have the following tags.
ingress.k8s.aws/cluster: ${clusterName}
ingress.k8s.aws/stack: ${stackID}
ingress.k8s.aws/resource: ${resourceID}

I'm seeing:
- ingress.k8s.aws/resource
- ingress.k8s.aws/stack

But instead of the ingress.k8s.aws/cluster tag i am seeing elbv2.k8s.aws/cluster where I expect it. 
The policy document https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2_ga/docs/install/iam_policy.json also seems to suggest that the elbv2 version is the correct one.

**Changes**
Clarify the default resource tags section of the documentation.

**Comment by M00nF1sh** [comment]
thanks for pointing this out. The tags indeed should be `elbv2.k8s.aws/cluster`. (we did the change for cluster tag but missed to update the docs).

PRs are welcome too if you are interested to make this change :D
