### ISSUE TITLE
Fail to create target group when cluster contains nodes from different AWS regions

### ISSUE THREAD

**Issue by PeterMaco** [kubernetes-sigs/aws-load-balancer-controller#1891]
Hi
I have a cluster that contains worker nodes from 2 AWS regions (EU and US). I have 2 ALBs, one in each region. Each ALB is configured to watch its own ingress class (to route different URLs to different regions directly and avoid EU-US roundtrips).

Each controller correctly creates ALB it correct region, creates target groups but it fails when adding targets to target groups. It is because it wants to add ALL nodes to each ALB, but ALB can have targets only from its own region.

{"level":"error","ts":1616052464.657866,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-cockpitu-900387c783","namespace":"dev","error":"InvalidInstanceID.NotFound: The instance ID 'i-01acd9e08dca925bc' does not exist\n\tstatus code: 400, request id: 96d71a64-f843-4374-9e18-67d34f385441"}

The problem is that EC2 i-01acd9e08dca925bc is from a different region.

I suppose that you should filter out nodes that are not from the same region as ALB you are creating.

**Comment by M00nF1sh** [comment]
@PeterMaco 
This is actually the first time i heard about this use case(having node is different region join a single cluster)
How is the nodes in different region talking to apiserver?

**Comment by PeterMaco** [comment]
We have nodes from 2 regions in one k8s cluster. VPCs are connected with VPC Peering, then it acts like a single network, there absolutely no problem with it. Some services we run with region affinity (e.g. services are for customer which is only in one region). The only problem is that external connection (via DNS name) will hit server in any region, because DNS entry contains IPs of all public nodes.
I don't think ALB controller can run only in single deployment. I tried 2 deployments and it works if you configure it correctly. Each instance is configured with its own ingress class (one class for one region) and controllers use node affinity to ensure there is one controller per region (and it will create ALB in the same region because you take it from EC2 metadata). With this setup we can control which DNS names are routed to which ALB (region). The only issue is that controller will not add targets to target group, because you include also nodes from other regions. Filtering by VPC would solve it. You have EC2 ID from k8s Node, so you can get some info about the EC2 via AWS Api, I believe also VPC. Then you can filter these nodes using VPC and add only nodes that have the same VPC as ALB you are creating.
