### ISSUE TITLE
delete.protection does not reconcile the resource

### ISSUE THREAD

**Issue by mridu23** [kubernetes-sigs/aws-load-balancer-controller#1900]
We recently migrated from ALB ingress controller (v1) to Load Balancer controller(v2) and noticed the following behaviour:

As per the expected behaviour, when load balancer deletion protection annotation is used with the ingress, the controller does not directly goes ahead and deletes the resources until the load balancer deletion protection is turned off.
 alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true

With v1 - if ingress with load balancer deletion protection tag set to true was deleted, and later updated to set this tag value to false, the controller reconciled the resource and honoured the changes made

However, with v2 - if ingress with load balancer protection tag set to true is deleted, and later the ingress resource is updated, the controller does not reconcile the resource. It is required to change the protection tag to false before the ingress deletion., otherwise the resource just hangs.

**Comment by M00nF1sh** [comment]
@mridu23 
Hi, there is a behavior change from v1 to v2 regards the `alb.ingress.kubernetes.io/load-balancer-attributes` annotation. There is an PR to update the docs about this: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1869/files

In v1, we defined default values for these attributes, so remove the attribute from annotation means revert the attribute to the default value defined by the controller. (for deletion protection, the default value is disabled, so remove it clears deletion_protection).

in v2, we didn't define any default values for these attributes. remove the attribute from annotation means "keep the attribute value as what it is in AWS). you need to explicitly set deletion_protection to false in annotation to disable it.

We did this change to gain two benefit:
1. support future new attributes without controller changes. (we don't have default values for these new attributes, and we don't want to remove these future new attributes when they are not specified in annotations).

2. align with AWS API. (the ELBv2 API only allows to modify attributes with a set of attributes to update, and un-specified attributes are left as it is).

**Comment by kishorj** [comment]
@mridu23 
If you delete an ingress with the deletion_protection attribute enabled, controller will not be able to delete the underlying AWS resources. To recover from this situation, you can manually disable the deletion_protection attribute from the AWS console for the affected load balancer. We will call this out in our docs.

/kind documentation

**Comment by mridu23** [comment]
@M00nF1sh @kishorj 
Thanks for addressing my query. I completely understand the reason for change and the expected behavior.

My concern is more around the resource reconciliation.

I understand that ideally - if this annotation is used - its value should be set to false before ingress resource is deleted. ( To eventually delete the actual Load Balancer)

However, lets say that the annotation value in ingress resource is still true, and someone forgot to update it and went with ingress resource deletion.
In this case, the controller logs error saying 'Deletion protection enabled - cannot delete LB ' + it does not delete the ingress resource either - Which is excellent !

But after this when we update the annotation value in the ingress resource to false -
- with Load Balancer Controller :: it does **not** reconcile that ingress resource. It keeps looping the same error log - and everything has to be deleted manually. Controller never takes the updated value into account.
- with ALB Ingress controller :: It acknowledges the updated value, and proceeds with deletion of LB, as expected.

@kishorj 
When you say " To recover from this situation, you can manually disable the deletion_protection attribute from the AWS console for the affected load balancer. "
Is this the only suggested option ? If the value is later updated at the ingress resource, would that not be considered at all ?

**Comment by M00nF1sh** [comment]
@mridu23 
we need to chat with our PM on the expected behavior for such case. 
1. should we always delete the LoadBalancer no matter whether deletion_protection attribute is set on Ingress?
2. should we allow delete LoadBalancer once the `deletion_protection: disabled` is added back to a Ingress in deletion state?

To help us make a decision, would you mind share your use case for add such `deletion_protection: enabled` attribute on Ingresses?

**Comment by mridu23** [comment]
@M00nF1sh 
In our environment, dns mapping and certificates are issued per Load balancer basis.
If because of any configuration - load balancer is deleted and recreated - which results in a new Load balancer DNS name - we need to get the dns mapping and certificate mapping done again. To avoid this, we use deletion_protection: enabled attribute on Ingresses, which ensures that load balancer is not deleted accidentally.

**Comment by M00nF1sh** [comment]
@mridu23 
is the purpose only to protect the LoadBalancer deletion from outside of Kubernetes?(e.g. from AWS console)?
If you don't put the deletion_protection: disabled back on Ingress and you delete the Ingress directly, do you expect the LoadBalancer to be deleted for your case?

**Comment by korenyoni** [comment]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1254#issuecomment-875993654

@kishorj as you implied when adding the `kind/documentation` label, I think this should definitely be documented. I might make a PR to add this.

**Comment by korenyoni** [comment]
@kishorj I've opened up a documentation PR: #2119

**Comment by kishorj** [comment]
@korenyoni, thanks.
Long term fix would be to force delete the lb resources once the delete.protection is set to false via annotation. We will keep this issue open to track the fix.
