### ISSUE TITLE
Support for waf.fail_open.enabled loadbalancer option

### ISSUE THREAD

**Issue by rdubya16** [kubernetes-sigs/aws-load-balancer-controller#1903]
Tried configuring the waf fail open option and it appears that its not supported. Could we get support added for this or am I missing something? I also dug into the codebase and I dont see any mention of it there.

Option is listed in the aws documentation:
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html

```
alb.ingress.kubernetes.io/load-balancer-attributes: waf.fail_open.enabled=true

E0324 12:40:54.580273       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile attributes of arn:aws:elasticloadbalancing:us-east-1:861551072145:loadbalancer/app/sandbox-default-albingress-d740/47b6e07c931dc70f due to failed parsing attributes; the load balancer attribute waf.fail_open.enabled is not valid"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"alb-ingress"}
```

**Comment by kishorj** [comment]
@rdubya16, this error mesasge is from v1 version of the controller which doesn't support this attribute. You will have to upgrade to the latest v2.1.3 release. You can find the upgrade instructions in the live doc - https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/upgrade/migrate_v1_v2/

**Comment by rdubya16** [comment]
Thanks!
