### ISSUE TITLE
Failed to create ALB without subnet Tags

### ISSUE THREAD

**Issue by adriantaut** [kubernetes-sigs/aws-load-balancer-controller#1905]
**Describe the bug**
According to AWS Documentation, starting with k8s version `1.19` https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-subnet-tagging the VPC subnets are not automatically tagged anymore with `kubernetes.io/cluster/<cluster-name>: shared`. 

Also, according with https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html the above tag is not anymore mandatory starting with `AWS Load Balancer Controller >= v2.1.2`.

However, we observed the Controller fails to create the ALBs in specific circumstances that I will describe below. The error is the following: 

```
{"level":"error","ts":1617132819.9878466,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"basic-ingress","namespace":"default","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}
```

**Steps to reproduce**

Deploy a private only EKS Cluster with k8s version 1.19. The AWS Load Balancer Controller is installed with Helm and it has the `v2.1.3` version. The VPC Subnets are tagged accordingly with the `kubernetes.io/role/internal-elb: 1` and `kubernetes.io/role/elb: 1`, but NONE of the VPC subnets have the `kubernetes.io/cluster/<cluster-name>: shared`. The below two scenarios are behaving differently:

1. Deploying the EKS Cluster in a VPC with private-only subnets
* deploying an `LoadBalancer` k8s resource successfully creates an NLB
* deploying an `Ingress` k8s resource successfully creates an ALB

2. Deploying the EKS Cluster in a VPC with both public and private subnets, although the cluster is instructed to make use of the private subnets only
* deploying an `LoadBalancer` k8s resource successfully creates an NLB
* deploying an `Ingress` k8s resource FAILS to create the ALB with the `couldn't auto-discover subnets` error. Once I add the above tag to the private subnets, it gets back to life and creates the ALB.

**Expected outcome**

Taking into account the `v2.1.3` of the Controller and the fact that the missing tag should not be mandatory anymore, I would expect having the ALB in scenario 2 being created.

Now that AWS does not automatically add the tag starting with k8s version 1.19, the easy workaround would be to tag ourselves the VPC subnets, unfortunately we are using AWS CDK for deploying our infrastructure. This has a known intended limitation that prevents user adding tags to already created subnets during the EKS Cluster Deployment.

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: 1.1.6
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version? yes

**Comment by kishorj** [comment]
@adriantaut, for Service of type `LoadBalancer`, internet-facing NLB gets provisioned by default. For `Ingress`, internal ALB gets provisioned by default. Could you verify your observations `1.` and `2.` above using the same LB scheme in both cases. 

Also, could you verify that your subnets don't have tags for some other clusters. If a subnet contains cluster tags for some other clusters, that subnet will get ignored by the atuo-discovery.
