### ISSUE TITLE
Add NLB support for BYOIP PublicIpv4Pool parameter

### ISSUE THREAD

**Issue by zenvdeluca** [kubernetes-sigs/aws-load-balancer-controller#1906]
AWS customers that make usage of [AWS BYOIP feature](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-byoip.html), when provisioning public network load balancers (NLBs), it requires a two-step process where:

1: provision Elastic IPs referencing an existing BYOIP ipv4 pool
```public-ipv4-pool (string)

The ID of an address pool that you own. Use this parameter to let Amazon EC2 select an address from the address pool. To specify a specific address from the address pool, use the Address parameter instead.
``` 

2: Provision an NLB referencing the EIPs created on Step 1

We need the functionality of passing our ipv4pools as an annotation, such as:

```
service.beta.kubernetes.io/aws-load-balancer-public-ipv4-pool: ipv4pool-ec2-0f123678912345678
service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```

that would result in provisioning the Network Load Balancer with public IPv4 from our BYOIP pools

**Comment by M00nF1sh** [comment]
@zenvdeluca 
I don't think this is a feature currently supported by NLB.

**Comment by zenvdeluca** [comment]
The NLB supports the parameter AllocationId, which takes an existing Elastic IP ID as input

```
AllocationId
[Network Load Balancers] The allocation ID of the Elastic IP address for an internet-facing load balancer.
Type: String
Required: No
```

as I mentioned above, its a two-step process where first we need to create EIPs using the `PublicIpv4Pool` parameter, then I can create NLBs using the `AllocationId` parameter with the EIPs I just created.

ideally, I'd write an annotation including the BYOIP PublicIpv4Pool value and the controller will provision the required EIPs and Allocate the NLB with them.

Last resort, I can have EIPs pre-allocated and my annotation will include a list of EIP-Ids so the controller is only creating the NLB with the AllocationId parameters from the annotation

**Comment by kishorj** [comment]
@zenvdeluca, Currently, you can configure EIP allocations via the service annotation 
```
service.beta.kubernetes.io/aws-load-balancer-eip-allocations
```

We haven't tested it with BYOIP allocations though. If you have the IP resources could you help us test?

Note that if you use this annotation, you will have to specify during service creation and not edit it later.

**Comment by zenvdeluca** [comment]
Thanks for clarifying @kishorj  was unaware of the `service.beta.kubernetes.io/aws-load-balancer-eip-allocations` annotation. I'll definitely give it a try and eventually mark this as resolved.  See no reasons why wouldn't work with BYOIP EIPs, but worth giving a shot before I mark it as closed.
