### ISSUE TITLE
Container stuck when kubelet try to kill it

### ISSUE THREAD

**Issue by jlpettersson** [kubernetes-sigs/aws-load-balancer-controller#1907]
The `aws-load-balancer-controller:v2.1.3` seem to may end up in a state where it cannot be killed by the kubelet.
Also `kubectl delete aws-load-balancer-controller-<pod>` does not terminate.

When doing "describe" on the Pod, I see events: "Reason: Killing", "Age: x32 over 48m", "From: kubelet".

This is preventing e.g. nodes in a Managed Node Group on EKS to be upgraded automatically.

/kind bug

**Comment by M00nF1sh** [comment]
@jlpettersson 
Would you mind share the logs from kubelet on why the killing failed? wondering whether it's some bug from kubelet itself. (e.g. on a older docker/containderd version, there was a race condition caused PID reuse that will cause pod kill fail forever)
