### ISSUE TITLE
ALB not created in EKS due to client Id not found in K8 secrets

### ISSUE THREAD

**Issue by hmojicag** [kubernetes-sigs/aws-load-balancer-controller#1908]
We changed clientID for clientId and it worked.

Please check again your documentation on how to setup the secret for the OIDC here:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blame/main/docs/guide/ingress/annotations.md#L473

**Comment by M00nF1sh** [comment]
@hmojicag 
what controller version are you using? both `clientID` and `clientId` should work(while we prefer `clientID`) on AWSLoadBalancerController v2.0.0+.

only `clientId` works if you are using AWSALBIngressController v1. 

we have different documentation version:
for V1: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/ingress/annotation/#auth-idp-oidc
for V2: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/#auth-idp-oidc

**Comment by hmojicag** [comment]
Well, that explains it then, we are using v1.
Thank you!!
