### ISSUE TITLE
[v2] iam_policy for AWS GovCloud regions

### ISSUE THREAD

**Issue by 1riggs** [kubernetes-sigs/aws-load-balancer-controller#1910]
Similar to #1557 when creating the IAM policy for the AWS load balancer controller with AWS GovCloud regions:

```
curl -o iam_policy.json  https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json
aws iam create-policy --policy-name ALBIngressControllerIAMPolicy --policy-document file://iam_policy.json
```
Results in the partition error:
```
An error occurred (MalformedPolicyDocument) when calling the CreatePolicy operation: Partition "aws" is not valid for resource "arn:aws:ec2:*:*:security-group/*".
```
The fix is to replace as with aws-us-gov in the arn stuff in this file. Would be nice to have this file available much like iam_policy_ch.json

[Reference for the arn names in GovCloud (US) regions](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html)

**Comment by kishorj** [comment]
@1riggs if you have the file with changes already, we'd very much appreciate if you can create a PR - so it is useful for other users as well.

**Comment by 1riggs** [comment]
PR which contains the new file: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1911

**Comment by 1riggs** [comment]
PR here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1912 

The bot says I haven't signed the CLA but I have. I am using a different username there (shevek24) but did commit using the email address I used to sign with.
