### ISSUE TITLE
i have deployed k8s cluster using kubespray and i have deployed traefik using helm charts, how traefik behind aws elb will work? what else i need to deploy?

### ISSUE THREAD

**Issue by arunk4m** [kubernetes-sigs/aws-load-balancer-controller#1917]

**Comment by M00nF1sh** [comment]
@arunk4m 
Hi, i'm clear how traefik works.Is your task to expose traefik with CLB/NLB?

**Comment by M00nF1sh** [comment]
@arunk4m 
closing this issue. Feel free to reopen a new one if you have more details to share 😄

**Comment by arunk4m** [comment]
@M00nF1sh I am using CLB
