### ISSUE TITLE
Specifying Load Balancer Attributes while installing the Controller

### ISSUE THREAD

**Issue by shubham391** [kubernetes-sigs/aws-load-balancer-controller#1918]
Hello

I'm creating an EKS Cluster which will have multiple services hosted on it. All the services will be exposed by the Load Balancer created using the controller. There are certain configurations which are service specific, and those configurations can be set in the Ingress definition of the service. However, there are some configurations which apply to all the services and should be set at the Load Balancer level. For e.g. Enabling Delete Protection, Enabling Access Logs, etc.

I understand that the MergeBehaviour of Load Balancer Attributes is Exclusive, and these should be specified on a single Ingress. My question is that is there a way to not define these attributes at an Ingress level at all but rather specify them when we install the Controller? Reason being that I want to keep the configurations which are not service specific separate from the service code. Since there are multiple services, it's not easy to define and maintain the one service whose Ingress definition will have the LB attributes.

**Comment by M00nF1sh** [comment]
/kind feature
I think this is a valid feature. currently we only support specifying tags at controller level, but there isn't really blockers to allow more attributes to be specified in the controller.

what's the desired semantic for your case if a user specified the attribute(with different value) at both Service/Ingress and controller level?

**Comment by shubham391** [comment]
@M00nF1sh In my case, I'd expect the attributes set at Controller level to be applied. Primarily because these attributes are global config of a Load Balancer (as opposed to service specific listeners/routing rules). Since the relationship between Controller/LB and Service/Ingress is 1-to-many, there can be many conflicting attributes defined at Service/Ingress level. So if the attributes present at Controller level always get first preference, it will eliminate any confusion that may arise when attributes are set in multiple places.

If these attributes are set at Controller as well as Ingress, I'd actually prefer that the Ingress installation itself fail. Just so we can fail-fast and fix the conflict, instead of realising later on that the config that got applied (via Ingress) is not what's actually active in LB. But I'm not sure if that's feasible and/or in line with the design principles of Kubernetes world (I'm quite new to it) 😄

**Comment by M00nF1sh** [comment]
Also, We'll support a new feature called IngressClassParams which allows you to define settings for a set of Ingresses, will it suit your requirement as well? (if you are only interested in ALB instead of NLB :D)

https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1849. Initially we'll only support scheme and ipAddressType, but we plan to extend to other load-balancer specific settings as well in future releases.

**Comment by shubham391** [comment]
@M00nF1sh I think IngressClassParams will satisfy the requirement once all the LB specific settings are supported.

Is this something that I will have to install separately in the cluster? Or will installing the controller along with some IngressClassParams configs (like these https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml) be enough (controller internally creating IngressClass and IngressClassParams in the cluster)? If it is the latter that would be great.

**Comment by M00nF1sh** [comment]
@shubham391 
The IngressClassParams is a CRD you need to install (as part of controller install or upgrade)

And then you need to create IngressClassParams per IngressClass explicitly (which can be used by a set of Ingresses).

**Comment by shubham391** [comment]
@M00nF1sh Thank you for supporting this in the new release (v2.2). Do you have a roadmap which includes addition of other load balancer settings?
