### ISSUE TITLE
Support for target group node labels either from ingress or node group labels

### ISSUE THREAD

**Issue by tirumerla** [kubernetes-sigs/aws-load-balancer-controller#1925]
Hello,

I am running into a problem that all nodes in multiple eks node groups are getting attached to the target group. I'm creating loadbalancer via ingress annotations using aws-load-balancer-controller. 

I came across several discussions on this topic:
-  Add label `node.kubernetes.io/exclude-from-external-load-balancers=true` to the node group. 
    1. Ran into when creating node group/adding labels via terraform.
      `InvalidParameterException: Label cannot contain reserved prefixes [kubernetes.io/, k8s.io/, eks.amazonaws.com/]`

    2. This ^^ makes sense to me but not sure what's the best approach to fix this. This will only work with `eksctl`?
- I see this PR #1874 which is merged. I tried adding this annotation but it doesn't seem to work. Guess it only works in "latest" k8s version ( `~1.20` ).

This how my flow looks like - r53 ( created via external-dns ) --> ALB ( created via aws-loadbalancer-controller & ingress annotations, `target-type: instance` ) --> traefik ( node port )  

controller version - `v2.1.3`
controller helm chart - `v1.1.5`
k8s version - `1.18`

Any help would be appreciated on how to fix this.

Thanks

**Comment by M00nF1sh** [comment]
@tirumerla 
I think it's terraform's issue for `Label cannot contain reserved prefixes`. which you may open ​an issue there.

PR1874 is merged but not release yet, it will be available in future release v2.2.0.

**Comment by tirumerla** [comment]
Thanks @M00nF1sh. I also tried adding the label by manually editing the node group. Guess this needs to be passed to EKS bootstrap script as a feature gate in the launch template user data script? not sure.

![Screen Shot 2021-04-13 at 1 03 14 PM](https://user-images.githubusercontent.com/57160285/114613811-aa1cc780-9c58-11eb-9b69-f3d51e8d504f.png)

Also I'm assuming I can use [kubernetes/kubernetes#90943](https://github.com/kubernetes/kubernetes/pull/90943) without any issue if i can bump my k8s version to `1.19`

**Comment by M00nF1sh** [comment]
@tirumerla 
personally I believe this label should be supported by our MNG. i'll forward this to our devs for MNG.

**Comment by kishorj** [comment]
@tirumerla, we just released v2.2.0 with support for target node labels. Note that the controller runs on k8s v1.16 and later.

I'm closing the issue for now. Feel free to reopen or create a new one if your concerns have not been addressed.

**Comment by tirumerla** [comment]
Thanks for all your help @M00nF1sh @kishorj
