### ISSUE TITLE
Name and IPs for NLB are not set

### ISSUE THREAD

**Issue by herbertgoto** [kubernetes-sigs/aws-load-balancer-controller#1930]
I am using v2.1.2 of the controller and try to set a name for the NLB as well as private IPs, however, the NLB gets random IPs and Name. 

This is my spec:

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-name: "test"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-03e7e4d30698abcad,subnet-0829cba6d398d1fca,subnet-07d55f6b0b1f1ca0e"
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "192.168.128.10,192.168.96.10,192.168.160.10"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  name: nlb-adl
  namespace: nginx-test
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

**Comment by kishorj** [comment]
@herbertgoto, the name and private IPv4 features are not supported in v2.1.2 release. These features will be included in the upcoming v2.2.0 release.

**Comment by herbertgoto** [comment]
ty @kishorj Any ETA?

**Comment by kishorj** [comment]
@herbertgoto, It's pending internal security review and pentests and we will release v2.2.0 soon after the review is complete.

**Comment by kishorj** [comment]
@herbertgoto we just released v2.2.0.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0

Closing this issue.
