### ISSUE TITLE
aws-load-balancer-controller cant create pod

### ISSUE THREAD

**Issue by kimilpyoung** [kubernetes-sigs/aws-load-balancer-controller#1931]
Hi 
I used EKS, k8s ver is 1.1.8
I applied "deploy" through the guide below
https://aws.amazon.com/ko/premiumsupport/knowledge-center/eks-alb-ingress-controller-fargate/

![스크린샷 2021-04-16 오후 4 31 05](https://user-images.githubusercontent.com/17869347/114988303-24f01780-9ed1-11eb-8e53-3c7bf152c8fc.png)

![스크린샷 2021-04-16 오후 4 32 30](https://user-images.githubusercontent.com/17869347/114988560-6bde0d00-9ed1-11eb-89dd-328ccf0175e8.png)

But It didn't create pod
Just status is pending

Can you tell where is wrong with that?
I tried command "kubectl logs deployment.apps/aws-load-balancer-controller -namespace=kube-system" for show logs
But timed out...

**Comment by M00nF1sh** [comment]
@kimilpyoung 
Hi, would you describe the replicaset of aws-load-balancer-controller, which should say why the pod isn't created

**Comment by kimilpyoung** [comment]
Oh Sorry,
When I describre replicaset i show message cant create pod because no serviceaccount 
So I re added service account, now It ok

Thx!
