### ISSUE TITLE
removing resource tags - UnauthorizedOperation: You are not authorized to perform this operation

### ISSUE THREAD

**Issue by newb1e** [kubernetes-sigs/aws-load-balancer-controller#1939]
I'm having an issue where it seems that the iam_policy from v2.3.1 does not allow to remove tags, thus I'm unable to remove ingress objects from my cluster once created.
I have installed aws-alb-ingress-controller:v2.1.3.
I'm using the [policy](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.3/docs/install/iam_policy.json) from the aws [userguide](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html).
Deleting the condition: 
```
           "Condition": {
                "Null": {
                    "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
                }
            }
```
from : 
```
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:DeleteSecurityGroup"
            ],
            "Resource": "*",
            "Condition": {
                "Null": {
                    "aws:ResourceTag/elbv2.k8s.aws/cluster": "false"
                }
            }
        },
```        
Seems to resolve the issue but the policy then allows the action on all resources. 
Please advice.

**Comment by M00nF1sh** [comment]
@newb1e 
Are you migrating from V1 to V2? If the resource is created via v2, it should always have "elbv2.k8s.aws/cluster" tag.
If you are migrating, you need to follow our upgrade guide(https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/upgrade/migrate_v1_v2/), there are other manual actions needed as well in the doc.(e.g. an additional iam policy is needed: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/install/iam_policy_v1_to_v2_additional.json)

**Comment by newb1e** [comment]
Hi @M00nF1sh , 
I'm installing everything from scratch. Followed the aws user guide. The security group gets created with the tag you specified by the controller but I'm still getting the error.
I'm deploying the alb controller through ArgoCD though I don't think it has anything to do with it.

**Comment by M00nF1sh** [comment]
@newb1e 
we didn't saw problem like this in the past.
do you have other automation system that could remove that tags from the auto-created security groups?
If not, we'll need to check the audit logs to figure out the exact cause.

**Comment by newb1e** [comment]
@M00nF1sh  No, nothing is removing the tag. 
I've tried to locate events in the cluster audit (if I understood correctly) but could not locate any event regarding the securitygroup deletion there.

**Comment by newb1e** [comment]
I have put the condition back on the IAM policy and the problem does not reproduces. I speculate that an app we use to tag resources messed up the tagging for the resource (even though the tag was on the SG).

**Comment by M00nF1sh** [comment]
@newb1e what's the log of app you are using?
