### ISSUE TITLE
Created security group for load balancer is not allowed to worker's security group automatically.

### ISSUE THREAD

**Issue by sechunOH** [kubernetes-sigs/aws-load-balancer-controller#1945]
Hello, I'm using aws-load-balancer-controller with helm chart with terraform. (https://github.com/aws/eks-charts)

Referrencing document for annotations(https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/ingress/annotations/#security-groups), this statement is shown.
```
When this annotation is not present, the controller will automatically create one security groups: 
the security group will be attached to the LoadBalancer and allow access from inbound-cidrs to the listen-ports. 
Also, the securityGroups for Node/Pod will be modified to allow inbound traffic from this securityGroup.
```
"the securityGroups for Node/Pod" means only for "Managed Node groups"?
I created eks with self-managed workers with ASG. The security groups for the workers will not be modified to allow newly, automatically created security group for Load balancer.

In this situation, I have to manually manage this security group rules. But when deleting ingress, automatically created security group for load balancer will not be able to be deleted because of manually managed security group rules.

Briefly, is it possible for eks worker security groups to be modified to allow security group for Load balancer automatically?
If possible, is it also possible for eks worker security groups to be modified not to allow security gorup for LB when deleting ingress?

need someone to talk with please.

**Comment by kishorj** [comment]
@sechunOH, do you see any errors in the logs/ingress events?
If your instance has a single security group, it gets modified. In case of multiple SGs, the SG tagged with the kubernetes cluster gets modified. The tag key is of the form kubernetes.io/cluster/<cluster_name>, where <cluster_name> is the name of your cluster. There can be only one SG with the cluster tag on your instance/ENIs.

**Comment by sechunOH** [comment]
@kishorj 
Oops, sorry and thank you for your reply.
It certainly did not work I think, but now it works well.
Logs are below
```
{"level":"info","ts":1619056939.419753,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0a78cf39ea9f86404"}
{"level":"error","ts":1619057060.0754342,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"aws-ingress","namespace":"default","error":"failed to delete securityGroup: timed out waiting for the condition"}
{"level":"info","ts":1619057060.08068,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"default/aws-ingress\",\"resources\":{}}"}
{"level":"info","ts":1619057061.2016888,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0a78cf39ea9f86404"}
{"level":"error","ts":1619057181.7923179,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"aws-ingress","namespace":"default","error":"failed to delete securityGroup: timed out waiting for the condition"}
{"level":"info","ts":1619057181.802573,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"default/aws-ingress\",\"resources\":{}}"}
{"level":"info","ts":1619057182.9204807,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0a78cf39ea9f86404"}
{"level":"error","ts":1619057303.5672474,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"aws-ingress","namespace":"default","error":"failed to delete securityGroup: timed out waiting for the condition"}
{"level":"info","ts":1619057303.587516,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"default/aws-ingress\",\"resources\":{}}"}
```
Obviously, it did not work. So I manually added rules to workers security group to allow lb's traffic. (Specific port with NodePort - 31551).

I have one another question. Is it a right behavior that automatically added ingress rule (for workers security group) include all TCP port (0-65536/TCP)? 
For more secure options, should we make security group for LB first, then manage ingress rules for workers security with it, finally pass the security group to ingress using annotation "alb.ingress.kubernetes.io/security-groups", right?

**Comment by M00nF1sh** [comment]
If you used `alb.ingress.kubernetes.io/security-groups` annotation, then **you need to modify** the worker node SGs to allow traffic from the SG you specified via annotation.

If not, an SG will be automatically created, and we also automatically manage the worker node SGs rule to allow traffic from our auto created SG.

Note, you should only specify security groups created by you in `alb.ingress.kubernetes.io/security-groups` annotation.

**Comment by sechunOH** [comment]
@M00nF1sh 
thankyou for reply. if security group for ingress were created automatically, is it right that rule added to worker nodes SG allows all TCP traffic(0-65535) from the auto created SG? not specific ports related with services configured in k8s Ingress definition? (if the sevice Nodeport set to 30500, then SG ingress rule added to worker nodes does not allows only that port, but all tcp port.)

**Comment by M00nF1sh** [comment]
@sechunOH 
Yes, we did that to save rule on your worker node's SG (since you might use multiple services at different port number).
And since that auto-created SG is only used by the ALB itself, it's should be considered safe as that rule basically means trust any traffic come from ALB.

**Comment by sechunOH** [comment]
@M00nF1sh 
Thank you for your explanation.
I understand it is for common uses.
For more secure, i will use that annotation.

GLTY.!
