### ISSUE TITLE
Access logs prefix does not unset if you remove the prefix from the annotation

### ISSUE THREAD

**Issue by serain** [kubernetes-sigs/aws-load-balancer-controller#1946]
**Problem**
If you configure an S3 object prefix for access logs using `access_logs.s3.prefix` and later remove the `access_logs.s3.prefix` from the `load-balancer-attributes` annotation, the controller will not unset the prefix on the LB.

**Expected behaviour**
The controller should ensure the access logs prefix is empty if `access_logs.s3.prefix` is not present in the `load-balancer-attributes` annotation.

**Steps to reproduce**
* Deploy an Ingress with access logs enabled and set the access logs prefix with the `access_logs.s3.prefix` attribute, for example:
```
...
  annotations:
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-bucket,access_logs.s3.prefix=my-prefix
...
```
* Remove the prefix from the annotation and apply:
```
...
  annotations:
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-bucket
...
```
* Observe that the ALB still has an access logs prefix configured

**Version**
Tested on version 2.1.1 of the controller.

If this is considered undesirable behaviour I'm happy to submit a fix.

**Comment by kishorj** [comment]
@serain, In v2 version, if an attribute is not specified in the annotation, the controller will not modify that particular attribute on the ALB. This allows us to support modifications that are made outside of the controller.
