### ISSUE TITLE
2.1.4 release date?

### ISSUE THREAD

**Issue by alexmnyc** [kubernetes-sigs/aws-load-balancer-controller#1949]
hi, I just wanted to check on the 2.1.4 release date to pick up alb.ingress.kubernetes.io/load-balancer-name annotation. It is blocking us from moving forward within our strict enterprise IAM policies. I saw cadence of releases went down after 2.1.3. Is there a specific reason why 2.1.4 could not be cut to include that change?

Reference https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1880

**Comment by alexmnyc** [comment]
Thank you

**Comment by kishorj** [comment]
@alexmnyc we just released v2.2.0 
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0

I'm closing this ticket.

**Comment by alexmnyc** [comment]
Thank you!
