### ISSUE TITLE
Ship ALB access logs from S3 to Cloudwatch Logs

### ISSUE THREAD

**Issue by justmy2centx** [kubernetes-sigs/aws-load-balancer-controller#1950]
Controller Version: aws-alb-ingress-controller:v1.1.9

We have added the annotations to enable the access logs and its working fine. However we need the logs to be viewable from Cloudwatch Logs so we can create metrics and alarms based on log lines.

I created a lambda function and followed this [blog](https://blog.atj.me/2017/10/ship-access-logs-to-cloudwatch/ ) , it sent the access log to cloudwatch lgos however its in compressed gz format so its basically unreadable. 

Is there an option to forward this alb access logs to cloudwatch logs? or how can i make those log files from s3 uncompressed. 

Thanks!

**Comment by M00nF1sh** [comment]
@justmy2centx 
Hi, ALB currently don't support ship to cloudwatch logs directly. (only s3 is supported).
You'll need to use lambda to do it as in your blog, and decompress when upload

**Comment by M00nF1sh** [comment]
closing this as it's not a feature supported by ALB thus we cannot support it directly.
