### ISSUE TITLE
Can not disable client IP preservation while using instance type mode with internal NLB

### ISSUE THREAD

**Issue by focaaby** [kubernetes-sigs/aws-load-balancer-controller#1953]
Here are the steps that I can reproduce `aws-load-balancer-controller` do not update the attributes `preserve_client_ip.enabled=false`.

1. Apply a service with the attribute and internal NLB.

```
$ cat ./nginx-nlb-service.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "demo-nginx"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "demo-nginx-deployment"
  namespace: "demo-nginx"
spec:
  selector:
    matchLabels:
      app: "demo-nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: "demo-nginx"
        role: "backend"
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: "demo-nginx"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "service-demo-nginx"
  namespace: "demo-nginx"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=false"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: "demo-nginx"
```

```
$ kubectl apply -f nginx-nlb-service.yaml
namespace/demo-nginx created
deployment.apps/demo-nginx-deployment created
service/service-demo-nginx created
ec2-user@ip-172-31-15-47:~/eks-lab-env$ kubectl -n demo-nginx get po,svc
NAME                                        READY   STATUS    RESTARTS   AGE
pod/demo-nginx-deployment-6d57bbd9f-9jf87   1/1     Running   0          17s
pod/demo-nginx-deployment-6d57bbd9f-jjnbf   1/1     Running   0          17s
pod/demo-nginx-deployment-6d57bbd9f-lb9xr   1/1     Running   0          17s

NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)        AGE
service/service-demo-nginx   LoadBalancer   10.100.197.180   a090d33943cef48ab8a0e2c741cbdbb8-eaee8a642aade8e7.elb.eu-west-1.amazonaws.com   80:32644/TCP   17s
```

2. Check the attributes for the targe group.

```
$ aws elbv2 describe-target-groups --load-balancer-arn=arn:aws:elasticloadbalancing:eu-west-1:561333300361:loadbalancer/net/a090d33943cef48ab8a0e2c741cbdbb8/eaee8a642aade8e7
{
    "TargetGroups": [
        {
            "TargetGroupArn": "arn:aws:elasticloadbalancing:eu-west-1:561333300361:targetgroup/k8s-demongin-serviced-7438ad793b/e9dfb82608b33a94",
            "TargetGroupName": "k8s-demongin-serviced-7438ad793b",
            "Protocol": "TCP",
            "Port": 32644,
            "VpcId": "vpc-0682db5962a841270",
            "HealthCheckProtocol": "TCP",
            "HealthCheckPort": "traffic-port",
            "HealthCheckEnabled": true,
            "HealthCheckIntervalSeconds": 30,
            "HealthCheckTimeoutSeconds": 10,
            "HealthyThresholdCount": 3,
            "UnhealthyThresholdCount": 3,
            "LoadBalancerArns": [
                "arn:aws:elasticloadbalancing:eu-west-1:561333300361:loadbalancer/net/a090d33943cef48ab8a0e2c741cbdbb8/eaee8a642aade8e7"
            ],
            "TargetType": "instance"
        }
    ]
}
```

I can view the `preserve_client_ip.enabled` is in `true` value.
```
$ aws elbv2  describe-target-group-attributes --target-group-arn arn:aws:elasticloadbalancing:eu-west-1:561333300361:targetgroup/k8s-demongin-serviced-7438ad793b/e9dfb82608b33a94
{
    "Attributes": [
        {
            "Key": "proxy_protocol_v2.enabled",
            "Value": "false"
        },
        {
            "Key": "preserve_client_ip.enabled",
            "Value": "true"
        },
        {
            "Key": "stickiness.enabled",
            "Value": "false"
        },
        {
            "Key": "deregistration_delay.timeout_seconds",
            "Value": "300"
        },
        {
            "Key": "stickiness.type",
            "Value": "source_ip"
        },
        {
            "Key": "deregistration_delay.connection_termination.enabled",
            "Value": "false"
        }
    ]
}
```

Also, I can view the annotations for Kubernetes service `service-nginx-demo` is applied the same value in previous step.
```
$ kubectl -n nginx-demo get service service-nginx-demo -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-internal":"true","service.beta.kubernetes.io/aws-load-balancer-target-group-attributes":"preserve_client_ip.enabled=false","service.beta.kubernetes.io/aws-load-balancer-type":"nlb"},"name":"service-nginx-demo","namespace":"nginx-demo"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx-demo"},"type":"LoadBalancer"}}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  creationTimestamp: "2021-04-24T20:55:09Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-04-24T21:36:56Z"
  finalizers:
  - service.k8s.aws/resources
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"service.k8s.aws/resources": {}
    manager: controller
    operation: Update
    time: "2021-04-24T21:07:10Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:service.beta.kubernetes.io/aws-load-balancer-internal: {}
          f:service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: {}
          f:service.beta.kubernetes.io/aws-load-balancer-type: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-24T21:23:19Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-24T21:23:20Z"
  name: service-nginx-demo
  namespace: nginx-demo
  resourceVersion: "7606256"
  selfLink: /api/v1/namespaces/nginx-demo/services/service-nginx-demo
  uid: 372bc3b2-0454-4b8a-b16d-dd5c1f744952
spec:
  clusterIP: 10.100.82.47
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32602
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-demo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by kishorj** [comment]
@ focaaby, instance mode is not supported by this controller yet. The service you create is reconciled by the kubernetes in-tree controller which does not support specifying the load balancer attributes in the annotation.

Service with the following annotation is reconciled by the in-tree controller -
```    
service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

**Comment by kishorj** [comment]
@focaaby, closing the issue for now. Feel free to reopen or create a new one if you have further queries.

**Comment by angeloskaltsikis** [comment]
Same problem here. Is this scheduled to be supported any time in the future?

**Comment by focaaby** [comment]
Hello @kishorj

I upgraded the `aws-load-balancer-controller` to v2.2.0 for NLB instance support, and used the same YAML configuration. However, the `preserve_client_ip.enabled=false` attribute was still not updated.

1. Upgrade the `aws-load-balancer-controller`, and check the image version is `v2.2.0`.
```
$ kubectl -n kube-system get deployments aws-load-balancer-controller -o yaml | grep "image:"
                f:image: {}
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.2.0
```

2. Apply a service with the attribute and internal NLB.

```
$ cat ./nginx-nlb-service.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "demo-nginx"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "demo-nginx-deployment"
  namespace: "demo-nginx"
spec:
  selector:
    matchLabels:
      app: "demo-nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: "demo-nginx"
        role: "backend"
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: "demo-nginx"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "service-demo-nginx"
  namespace: "demo-nginx"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=false"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: "demo-nginx"
```

```
$ kubectl apply -f nginx-nlb-service.yaml
namespace/demo-nginx created
deployment.apps/demo-nginx-deployment created
service/service-demo-nginx created
```

```
$ kubectl -n demo-nginx get po,svc
NAME                                        READY   STATUS    RESTARTS   AGE
pod/demo-nginx-deployment-6d57bbd9f-bh7kw   1/1     Running   0          8m53s
pod/demo-nginx-deployment-6d57bbd9f-j7slz   1/1     Running   0          8m53s
pod/demo-nginx-deployment-6d57bbd9f-m679x   1/1     Running   0          8m53s

NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)        AGE
service/service-demo-nginx   LoadBalancer   10.100.173.112   a78a4684b7c7f499e832dc23507b585e-9e0c372c039e23e6.elb.eu-west-1.amazonaws.com   80:31353/TCP   8m53s
```

3. Check the attributes for the targe group.

```
$ aws elbv2 describe-target-groups --load-balancer-arn=arn:aws:elasticloadbalancing:eu-west-1:561333300361:loadbalancer/net/a78a4684b7c7f499e832dc23507b585e/9e0c372c039e23e6
{
    "TargetGroups": [
        {
            "TargetGroupArn": "arn:aws:elasticloadbalancing:eu-west-1:561333300361:targetgroup/k8s-demongin-serviced-f88b59e0af/a8df6e504f8323f7",
            "TargetGroupName": "k8s-demongin-serviced-f88b59e0af",
            "Protocol": "TCP",
            "Port": 31353,
            "VpcId": "vpc-0682db5962a841270",
            "HealthCheckProtocol": "TCP",
            "HealthCheckPort": "traffic-port",
            "HealthCheckEnabled": true,
            "HealthCheckIntervalSeconds": 30,
            "HealthCheckTimeoutSeconds": 10,
            "HealthyThresholdCount": 3,
            "UnhealthyThresholdCount": 3,
            "LoadBalancerArns": [
                "arn:aws:elasticloadbalancing:eu-west-1:561333300361:loadbalancer/net/a78a4684b7c7f499e832dc23507b585e/9e0c372c039e23e6"
            ],
            "TargetType": "instance"
        }
    ]
}
```

The attribute `preserve_client_ip.enabled` is still in `true` value.


```
$ aws elbv2  describe-target-group-attributes --target-group-arn=arn:aws:elasticloadbalancing:eu-west-1:561333300361:targetgroup/k8s-demongin-serviced-f88b59e0af/a8df6e504f8323f7
{
    "Attributes": [
        {
            "Key": "proxy_protocol_v2.enabled",
            "Value": "false"
        },
        {
            "Key": "preserve_client_ip.enabled",
            "Value": "true"
        },
        {
            "Key": "stickiness.enabled",
            "Value": "false"
        },
        {
            "Key": "deregistration_delay.timeout_seconds",
            "Value": "300"
        },
        {
            "Key": "stickiness.type",
            "Value": "source_ip"
        },
        {
            "Key": "deregistration_delay.connection_termination.enabled",
            "Value": "false"
        }
    ]
}
```
## References

1. https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1744
2. https://github.com/kubernetes-sigs/aws-load-balancer-controller/projects/7

**Comment by kishorj** [comment]
@focaaby, your service is reconciled by the in-tree controller which does not support the client IP preservation settings. The annotations on your current service are - 
```
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=false"
```

You need to delete the service and create a new one with the following annotations instead - 

```
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=false"
```
Note: AWS LB controller creates internal load balancer by default.

**Comment by kyg9823** [comment]
Same problem here. Is this scheduled to be supported any time in the future?

**Comment by kishorj** [comment]
@kyg9823, if your service has the annotation, `service.beta.kubernetes.io/aws-load-balancer-type: nlb`, client IP preservation feature is not supported. Please refer to my earlier comments https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1953#issuecomment-844273695.

**Comment by boney9** [comment]
Hi @kishorj - when you say not supported, is that because of some technical limitations or is it just something that is not implemented yet? Is it possible to create an internal load balancer with this setting?

**Comment by kishorj** [comment]
@boney9, the limitation is on the kubernetes kube-controller-manager which doesn't support the client IP preservation feature. If you prefer to use the client IP preservation, you'd need to setup this controller and specify appropriate annotations.

**Comment by ta1meng** [comment]
I ran into a similar problem as the reporter. I had existing target groups and tried to update their "preserve client IP" value through annotation. It didn't work.

However, when the target groups were recreated, the annotation "preserve_client_ip.enabled=false" was respected.

I used Terraform to deploy my changes, and the Terraform state file looks like this:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/23320335/205186109-d038fc41-422a-4949-aa0a-6fa74be981ed.png">

As can be seen, I was configuring an "internal" "nlb" load balancer.

So @focaaby, if you recreate the load balancer in AWS, is "preserve_client_ip.enabled=false" respected?

**Comment by kishorj** [comment]
@ta1meng, the annotation `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"` causes the service to be reconciled by the KCM/CCM not this controller. KCM/CCM doesn't support target group attributes. For this controller, you need to specify the annotation `service.beta.kubernetes.io/aws-load-balancer-type as "external"` and `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type` as 'instance' or 'ip'.

**Comment by ta1meng** [comment]
@kishorj I made a mistake earlier. I thought our load balancer was recreated but it was not. So I am interpreting your explanation to cover the case of load balancer creation as well.

I'll look into changing the load balancer type as you described.

**Comment by ta1meng** [comment]
> @ta1meng, the annotation `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"` causes the service to be reconciled by the KCM/CCM not this controller. KCM/CCM doesn't support target group attributes. For this controller, you need to specify the annotation `service.beta.kubernetes.io/aws-load-balancer-type as "external"` and `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type` as 'instance' or 'ip'.

Hi @kishorj I have been trying the solution posted in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1953#issuecomment-844273695 but it has been challenging installing the `aws-load-balancer-controller`. It's also unclear what the impact will be when we switch load balancer types. We might succeed in changing the load balancer type but end up breaking the Pulsar EKS cluster that relies on the load balancer.

Reading your latest response, can I conclude that there is a bug in KCM/CCM?

Does CCM refer to the AWS Cloud Controller Manager?

Because our company pays for an AWS TAM, I'm asking him whether he can confirm the initial bug report as a bug in the AWS CCM. I do see a relevant ticket: https://github.com/kubernetes/cloud-provider-aws/issues/338

**Comment by kishorj** [comment]
@ta1meng, you're right CCM refers to the cloud controller manager, it is enabled in EKS 1.22 and later versions. Prior versions had the KCM (kube controller manager). The KCM/CCM contains legacy code, and never had support for specifying target group attributes for NLB - so it is not a KCM/CCM bug. As I mentioned earlier, if you specify `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"` annotation on the service, it gets reconciled by the KCM/CCM.

This controller (aws-load-balancer-controller) is an external controller you need to install on your k8s cluster. It is not installed by default. In addition you also need to specify the annotation `service.beta.kubernetes.io/aws-load-balancer-type as "external"` on your service resource. Since there are multiple controllers involved, we recommend you to create a new service resource instead of editing the `service.beta.kubernetes.io/aws-load-balancer-type` annotation.

If you encounter challenges with installing the aws-load-balancer-controller, feel free to reach out to us, or create a new issue in this repo.

The cloud-provider-aws issue 338 you referred is not exactly related to setting the target group `preserve_client_ip.enabled` attribute. The OP mentions CLB and the x-forwarded-for header which are not relevant for the NLB. OP also mentions trying various combinations of NLB, but to the lack of details on the NLB part, I'm not able to comment further.

In case of instance targets, your application may not see the original client IP address regardless of `preserve_client_ip.enabled` configuration. You might want to consider setting `externalTrafficPolicy: Local`, or setting the `proxy_protocol_v2.enabled=true` attribute on the target group.
