### ISSUE TITLE
"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403" when using custom docker image

### ISSUE THREAD

**Issue by piano-man** [kubernetes-sigs/aws-load-balancer-controller#1955]
So I set up my elb controller using the setps mentioned here: https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
Everything works as expected and when I deploy my service, the AWS NLB is created properly.

Now, I wanted the deployment to use the controller docker image which I put in a different registry(not the AWS registry). I created this image using the Dokcerfile in the repo and made no changes to the code whatsoever.
To make the deployment get this image, **I did an "edit deployment" and replaced the image path.**
The controller still comes up fine with the new image, but when I try to deploy the service now, I get the error: **"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403"** in the controller pod logs. The deployment is still using the same service account and has no other changes other than the image path.
I'm not sure how toggling the container image path is affecting the AWS level permissions.

Is there something I'm missing while building the docker image?
Any help would be appreciated.

**(NOTE: If I edit the deployment again and put the original image path _(602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.3)_ , everything goes back to working as expected)**

**Comment by OzySky** [comment]
How did you solve it?

**Comment by piano-man** [comment]
The iam policy needs to be updated. If you're building the latest docker image, make sure you also pick up the latest iam_policy.json from this repository.

**Comment by OzySky** [comment]
Yep figured that out. Thanks!

**Comment by Nurlan199206** [comment]
i have same issue, how u updated this policy json file? help pls

**Comment by Nurlan199206** [comment]
In my case i'm added these tags in subnets, now its works!

```
kubernetes.io/cluster/$CLUSTER_NAME            where $CLUSTER_NAME is the same CLUSTER_NAME that you pass to the controller in the --cluster-name option; the value must be set to owned or shared
kubernetes.io/role/internal-elb                should be set to 1 or an empty tag value for internal load balancers
kubernetes.io/role/elb                         should be set to 1 or an empty tag value for internet-facing load balancers
```
