### ISSUE TITLE
iam:CreateServiceLinkedRole what is it used for? Can i get by without it? Our IAM permissions are locked down

### ISSUE THREAD

**Issue by alexmnyc** [kubernetes-sigs/aws-load-balancer-controller#1961]

**Comment by kishorj** [comment]
This permission is required for ELB to create a [service linked role](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/elb-service-linked-roles.html) on your behalf.
 
For ELB, you can scope down the permission as follows -
```
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:AWSServiceName": "elasticloadbalancing.amazonaws.com"
                }
            }
        }
```

**Comment by kishorj** [comment]
@alexmnyc, I'm closing the issue for now. If you still have questions/concerns, feel free to reopen or create a new issue.
