### ISSUE TITLE
"error":"UnauthorizedOperation: You are not authorized to perform this operation

### ISSUE THREAD

**Issue by alexmnyc** [kubernetes-sigs/aws-load-balancer-controller#1962]
I am trying to scope IAM policy down to the least privileged and it the current logging is extremely unhelpful to try to indentify which operation failed. can we add contextual logging i.e. ?

Exception TriedToCreateTargetInstanceGroupExecption
Cause: "error":"UnauthorizedOperation: You are not authorized to perform this operation
/../////

**Comment by kishorj** [comment]
@alexmnyc what permissions did you remove/modify?

**Comment by alexmnyc** [comment]
I had conditional policy based on tags but it turns out that controller does not tag rules and listeners.  There is a deffect. I opened up a ticket and was told it will be tagged with 2.2.0
