### ISSUE TITLE
How to configure managed rules for AWS ALB

### ISSUE THREAD

**Issue by zacyang** [kubernetes-sigs/aws-load-balancer-controller#1972]
Hi ,
I'd like the ALB provisioned has some common rules configured. e.g https://docs.aws.amazon.com/config/latest/developerguide/alb-http-drop-invalid-header-enabled.html

However, it seems there's no way I can configure the ALB from this chart.

**Comment by M00nF1sh** [comment]
@zacyang 
Hi Yang, we'll support a new feature called IngressClassParams in v2.2.0(https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1849), which allow you to define common settings of ALB for a set of Ingresses.
However, initially(v2.2.0) we only support to specify `scheme`, `ipAddressType` and `tags`. In the future, we'll expand it to more attributes. Will it meet your need if we support specify loadbalancer attributes there?

**Comment by zacyang** [comment]
Thanks for your quick response. For common use case I think it has been covered by adding annotation on the deploy side e.g Ingress annotation
`alb.ingress.kubernetes.io/load-balancer-attributes`
tested the common feature like deletion_protection are supported. But tags are not.

I think it's very useful to support tags on your side. Thanks.

**Comment by elFarto** [comment]
@M00nF1sh It would be nice if we could apply any of the Ingress/Service annotations to IngressClassParam, and have them all merged together. I was hoping v2.2.0 would let me clean up my 30+ Ingress manifests to remove the ALB specific cruft from them, as it stands I'd be left with target-type and listen-ports (and healthcheck-path, but that's a harder one to fix).
