### ISSUE TITLE
Passing the client certificate to the backend for mutual auth

### ISSUE THREAD

**Issue by boxidilshan** [kubernetes-sigs/aws-load-balancer-controller#1973]
I am using EKS/Fargate for K8s deployment. There are few use cases which we need to provide mutual authentication. In my opinion mutual authentication is not supported in ALB rather in the AWS Gateway. Even though the Gateway support it there is a limitation that we cannot use individual cert per API. Hence I am looking at options to offload TLS in ALB and pass the certificate to backend for mutual authentication. Looking for a similar option like in Nginx controller [1].

Here is the annotation. 

nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream

Also I am aware that this can be directly done in the POD level with TLS termination if we use a NLB. However we enforces certain WAF rules from AWS which is not available to have in layer 4. Hence kindly looking for your input. Not sure such a feature is planned with ALB controller in the future.

[1] - https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-certificate-authentication

**Comment by kishorj** [comment]
@boxidilshan ALB currently doesn't support mTLS. Keeping track of this issue in the AWS ALB feature request list.

**Comment by boxidilshan** [comment]
Thank you @kishorj

**Comment by kishorj** [comment]
@ boxidilshan, I'm closing this ticket for now since we are keeping track of this issue in the ALB/NLB feature list. We will support mTLS once the ALB side support is available.
