### ISSUE TITLE
Missing reconcile on targetgroupbinding causing delayed registration

### ISSUE THREAD

**Issue by gaganapplatix** [kubernetes-sigs/aws-load-balancer-controller#1974]
We are seeing missed reconciles on targetgroupbinding when endpoint object is updated sometimes. This happened on 2.1.2 but I don't think there are changes related to this on 2.1.3
What we observed is that sometimes:
1) Pod gets removed from endpoint
2) Reconcile removes the target
3) Within 1 minute of above reconcile, new pod gets added to target to notready subset in the endpoint
4) 4 minutes from previous reconcile pod gets to containers ready
5) 10 minutes from previous reconcile a new reconcile on targetgroupbinding happens (no endpoint updates have happened)
6) Register the pod as target
7) This delays rollout of deployments

I saw the comment 
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/da8951f80521651e0a1ffe1361c011d6baad7706/pkg/backend/endpoint_resolver.go#L18

I was trying to understand whether the above is happening because the endpoint object changes are not observed or its because endpoint doesn't meet your criterea as the comment says?

**Comment by gaganapplatix** [comment]
I will try to reproduce with --v higher on the alb ingress controller so I can see the output for the endpoint events updates and if it queues the update for reconcile or not.

**Comment by julius88** [comment]
Could this be related my issue as described here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1960

At least your description sounds a bit similar problem.

**Comment by gaganapplatix** [comment]
Possibly. We do see the 10 minute mark is somehow magical. We regularly see that registration happens 10 minutes after last register/deregister event when things go slow (in our case the pod may be ready at the 5 minute mark).

**Comment by gaganapplatix** [comment]
This is happening regularly enough that is it causing us a lot of issues due to increased deployment times because of this.

**Comment by gaganapplatix** [comment]
I checked CloudTrail and There are no Register/DeRegister calls between the two reconciles on the account

**Comment by gaganapplatix** [comment]
One other thing of note is I see bunch of patch calls in kubernetes api server audit log for the pod/status readiness condition on the same targetgroup for 2 other pods repeatedly during the 10 minutes (the patch value is the same so not sure why it is doing repeated patches). Is it related to kubernetes client caching issues for pod objects of some sort in the aws load balancer controller?

**Comment by gaganapplatix** [comment]
Looks like you actively create patch with empty condition value here
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/da8951f80521651e0a1ffe1361c011d6baad7706/pkg/targetgroupbinding/resource_manager.go#L429
That probably explains repeated patches.

**Comment by gaganapplatix** [comment]
@M00nF1sh Do you have any insight on what may be happening here?

**Comment by M00nF1sh** [comment]
@gaganapplatix 
This should be happening due to https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/targetgroupbinding/resource_manager.go#L139

The currently logic did exponential back off retry to check whether pods in not ready subset becomes containerReady. (from 10 ms to 16minute by default).
For your case, since your pod only becomes containerReady after 4 minutes, it may cause the above backoff retry to 10minutes.

Do you think whether it's what happening to your case? If you are not sure, are you ok to run a patched controller with more logs to verify it?

BTW, if it's indeed this case, i think we can tune the exponential backoff behavior. we did this exponential backoff behavior to avoid blocking other TGB's reconcile with too many retries. However, since doing this check is purely in-memory(we are using informer), we indeed can optimize it here.

**Comment by gaganapplatix** [comment]
Where does the exponential backoff happen? Is it built into kubebuilder reconcile logic or when you explicitly ask for the delay, because currently I only see the 15 second default timing that is built in as the only mention of delay in some scenarios. When you just queue for reconcile, does the exponential logic happen in kubebuilder? But yeah configurable cap on the backoff may be useful to guarantee relatively slow pods specially if they are on bad boundaries of exponential backoff.

**Comment by M00nF1sh** [comment]
@gaganapplatix yes, we currently just used the default exponential backoff from kube-builder. but we can implement our own exponential mechanism for specific scenario.

or even do wait&watch in a separate go-routine and only enqueue an item to TGB  reconciler workers when certain precondition meets. But this seems unnecessary in most cases

**Comment by gaganapplatix** [comment]
Yeah, I mean thinking ideally what you want is an event when containersReady gets set to true so you can immediately do reconcile. But that would basically mean a watch on pod/status which is somewhat busy and then work to filter on containersReady being true. From what I understand I don't think it is kube-builder supports configurability for the exponential backoff so you may have to implement your own. Mostly looking for a max backoff so it doesn't become too big. When do you think this can be implemented? This is probably useful for a lot of people because we pretty much cannot remove readiness gates and some of our pods have slow containers which happen to be on the wrong side of exponential delay.

**Comment by gaganapplatix** [comment]
Hmm I do see this ticket which mentions some of these issues in kube-builder and that you can cap the delay
https://github.com/kubernetes-sigs/controller-runtime/issues/808
Looks like you can configure a cap. Can we expose that as configurable for now.
https://github.com/kubernetes-sigs/controller-runtime/issues/808#issuecomment-640323570

**Comment by M00nF1sh** [comment]
@gaganapplatix Yes, we can add configure ability for this in a patch version i  believe.

**Comment by eytan-avisror** [comment]
@M00nF1sh thanks for merging the PR, do you think we can get a release with this shortly?
