### ISSUE TITLE
Ingress in different AWS Account

### ISSUE THREAD

**Issue by matthiassb** [kubernetes-sigs/aws-load-balancer-controller#1975]
We currently have a central ingress/egress networking topology where the ingress VPCs live in separate account and connected back to the spoke VPC through a Transit Gateway.

Does ALB Ingress Controller support provisioning and managing an ALB in a separate account?

**Comment by M00nF1sh** [comment]
Currently we don't support this use case. the ALB and pods should be in a single VPC.

would you mind share your exact use case? In each account is your EKSCluster/Worker node running? 
Also, how would you assume this to be configured?(e.g. additional controller-flag to configure the role arn used to access another account)

**Comment by mihirk** [comment]
@M00nF1sh Hey sorry not the same use-case but similar. 
We have worker nodes running in 2 separate VPCs. 
One is an edge VPC which has connectivity to public internet and all the workloads running on workers on the edge VPC are the ones which are responsible for ingress/egress to the public internet, there is also a separate VPC where the masters and workers run, which do not have access to public internet. 

Currently if the workloads on the edge vpc request an NLB it is created in the main VPC instead.

It would be ideal if the controller is capable of handling the use-case of workers running across different VPCs and provision NLBs.
