### ISSUE TITLE
Support different values for additional tags for ingresses in the same ingress group

### ISSUE THREAD

**Issue by raids** [kubernetes-sigs/aws-load-balancer-controller#1986]
It'd be great to be able to apply additional tags on a per-ingress basis and not merge tags on the ingress group or fail to build because of conflicting tag values.

We want to be able to filter load balancer metrics by tag key _and_ value, such as `Environment=environment-A` and `Environment=environment-B`, but when specifying different tag values for the same key across ingresses in the same ingress group, the following error occurs.

```
Events:
  Type     Reason            Age                  From     Message
  ----     ------            ----                 ----     -------
  Warning  FailedBuildModel  9m44s (x3 over 11m)  ingress  Failed build model due to conflicting tag Environment: environment-A | environment-B
```

**Comment by aaj-synth** [comment]
Why was this issue ever closed? This is a valid problem!
