### ISSUE TITLE
Rewriting ingress to deprecated apiVersion.

### ISSUE THREAD

**Issue by rverma-nsl** [kubernetes-sigs/aws-load-balancer-controller#1987]
Facing issue with argo-rollout which is not able to modify the ingress since we are using a deprecated apiversion

**Comment by rverma-nsl** [comment]
@M00nF1sh  does the controller rewrite the ingress class with different apiversion ?

**Comment by mbevc1** [comment]
Probably examples in docs need updating as well :thinking:

**Comment by M00nF1sh** [comment]
@rverma-nsl the controller didn't automatically rewrites. but the Ingresses will be updated automatically to storage version if there is any writes to Ingress.

@mbevc1 Yes, we'll update the docs to use newer Ingress API soon.

**Comment by mbevc1** [comment]
Cheers :+1:

**Comment by M00nF1sh** [comment]
the examples have been updated to use networking.k8s.io/v1beta1: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1850

@mbevc1  feel free to submit PRs to improve the examples :D

closing this.

**Comment by mbevc1** [comment]
Cheers @M00nF1sh :+1:

**Comment by mbevc1** [comment]
Oh, I might actually do that as they are probably broken now - it wasn't just API change, but there is slightly different spec now as well, i.e.:
```
...
           backend:
              service:
                name: xxx
                port:
                  name: 666
```
and also path cannot have wildcards with latest v2.2.0 :smiley:
