### ISSUE TITLE
Feature Request: restrict ingress ports for node SG

### ISSUE THREAD

**Issue by flyguybravo** [kubernetes-sigs/aws-load-balancer-controller#1993]
I expose several nodeport services from a single ALB. Currently on deployment of the ingress object, when the Security Group of my nodes is modified by the controller it adds a new ingress rule for port range 0 - 65535 to permit traffic from the SG just created for the ALB. 

It would be very helpful to be able to specify via annotation a min/max value for this rule, or have it default to only those ports in Kubernetes default nodeport range (30000 - 32767).

**Comment by kishorj** [comment]
v2.3.1 release has the feature to restrict SG rules to the the port ranges required for ingress access. Closing the issue.
