### ISSUE TITLE
Prevent single ingress error causing whole reconciler error

### ISSUE THREAD

**Issue by thanhma** [kubernetes-sigs/aws-load-balancer-controller#1994]
My ingress has many rules, and if one of these rules has error, the whole ingress becomes not able to reconcile and affect other rules behaviors, i.e. update rule, add new rule

Is there a way to prevent this to happen?

I'm using v2.1.3 of ALB controller.

**Comment by kishorj** [comment]
PR #1967 supports tolerance non-existent service or action references and will be available in the v2.2.0 release. Does this help with your issues?

**Comment by thanhma** [comment]
@kishorj great, I think this would help.

Is v2.2.0 going to be released soon?

**Comment by kishorj** [comment]
@thanhma we just released v2.2.0.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0

closing the issue.

**Comment by thanhma** [comment]
@kishorj There's a case that an ingress that belongs to an Ingress Group, but having the certificate expired, the other ingresses within the group also cannot be reconciled. Do we have any fix or workaround for this?
