### ISSUE TITLE
Documentation without a version in the URL does not show version selection

### ISSUE THREAD

**Issue by pre** [kubernetes-sigs/aws-load-balancer-controller#1995]
The default documentation in the web, which is easily found by googling, does not display a dropdown for version selection.

The default version of the documentation lacks many options of the most recent version. 

I remembered I had earlier seen the "good documentation somewhere" but I really struggled to find where it was. It took me some time to find the right place. 

=> The version selector should be displayed in the default version of the documentation. It is really difficult to find the "v2.1 docs" unless one knows that they exist or has seen them earlier. 

Please see the attached image. 

<img width="1551" alt="2021-05-10 aws documentation mismatch" src="https://user-images.githubusercontent.com/63895/117664940-00731c80-b1ab-11eb-84e3-b6359cdfb409.png">

[1] Default docs without version selection dropdown: https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/service/annotations/

[2] Recent v2.1 docs with version selection dropdown: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/annotations/

**Comment by kishorj** [comment]
@pre, did you encounter any documentation that contained the old links? 
The live docs link https://kubernetes-sigs.github.io/aws-load-balancer-controller/ redirects to the latest version with the version selector.

/kind documentation

**Comment by pre** [comment]
<img width="860" alt="2021-05-11 at 10 43" src="https://user-images.githubusercontent.com/63895/117778195-0e29b000-b246-11eb-8664-b9abb877be22.png">

It seems I had just bad luck. Currently the first google search result points to the 2.1 documentation, but 75% (3 of 4) point to the docs of the old lb-controller and do not eg. describe service annotations for selecting a subnet.

**Comment by M00nF1sh** [comment]
the un-versioned docs is removed. google should automatically remove these results in  a few days 😄 

closing this
