### ISSUE TITLE
Feature Request: Reference a statically create NLB/ALB and dynamically update target group 

### ISSUE THREAD

**Issue by anthr76** [kubernetes-sigs/aws-load-balancer-controller#2001]
Hello

A great use case for the aws-load-balancer-controller would be to specify a NLB or ALB created in the AWS console that you can reference in the controller. This can be used in conjunction with a servicetype in Kubernetes to dynamically update the nodes your service is listening on as a target.

For example

A ingress controller service of load-balancer has annotations pointing to a existing NLB/ALB and the nodes where the ingress controller pods are running will be dynamically added as a target in the ALB/ NLB. This is useful for a few reasons.

* Deletion of the service ensures the ALB/NLB won't be deleted
    * This becomes useful when you need to manually point DNS at the ALB/NLB and are under conditions where it's not feasible to dynamically update DNS in a automated fashion.
 * Less dynamic TLS termination

**Comment by M00nF1sh** [comment]
@anthr76 
Hi, i believe we already support this use case via this CRD: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/targetgroupbinding/targetgroupbinding/

would you mind check whether it suits your need? 😄

**Comment by anthr76** [comment]
Hi @M00nF1sh thank you for the prompt reply. TargetGroupBinding looks like it's exactly what we need although it seems with that we would need to manually specify targetgroups. Which would require us to bind the ingresscontroller to static nodes since you'd need to manually point the IP addresses in the targetgroup upon NLB/ALB creation. Is that assumption correct?

**Comment by M00nF1sh** [comment]
@anthr76 
You don't need to bind the ingresscontroller to static nodes.

The TargetGroupBinding is a CRD that allows you to update an existing TargetGroup(which should be created by you out-side-of k8s) with a k8s service.
