### ISSUE TITLE
Error when upgrade v1.1.3 to v2.1.0

### ISSUE THREAD

**Issue by thiagolsfortunato** [kubernetes-sigs/aws-load-balancer-controller#2003]
On the documentation ["Migrate from v1 to V2"](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/upgrade/migrate_v1_v2/) is not described that have break changes on the Kubernetes v1.14 related to [OpenAPI v3](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) that was introduced after the Kubernetes 1.15 and used by new CRD `TargetGroupBinding` to [validate](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation) input data type: `x-kubernetes-int-or-string: true`

ErrorMessage: 
![image](https://user-images.githubusercontent.com/11510919/118156051-46202700-b3ef-11eb-8b90-1feaa1f01828.png)

It's possible to migrate from v1.1.3 to v2 with Kubernetes v1.14.x?

**Comment by M00nF1sh** [comment]
@thiagolsfortunato 
Hi,
v2.1.3 requires at least Kubernetes 1.15.
And our coming v2.2.0 will require at least Kubernetes 1.16.
We'll make these requirements clear in docs & release page.

**Comment by M00nF1sh** [comment]
closing this as the docs and releases have been updated to have this info 😄

**Comment by thiagolsfortunato** [comment]
@M00nF1sh could share this documentation?
The page ["Migrate from v1 to V2"](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/upgrade/migrate_v1_v2/) was removed

**Comment by kishorj** [comment]
This is the document
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/upgrade/migrate_v1_v2/

**Comment by thiagolsfortunato** [comment]
Please, also add the [Kubernetes version requirements](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/#kubernetes-version-requirements) on the documentation of version [2.1](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/installation/).
