### ISSUE TITLE
Ingress group cannot reconcile when reach ALB max number of rules

### ISSUE THREAD

**Issue by thanhma** [kubernetes-sigs/aws-load-balancer-controller#2011]
I have ingresses in different namespaces, which are in a same ingress-group.

When the number of ingresses increases, the number of rules per ALB reaches the limit (by default 100 rules per ALB, current hard limit is 200). And the ingress will fail to reconcile with the error: 

`failed to create listener rule: TooManyRules: The maximum number of rules on load balancer`

Can the ingress group detect the limit and create a new ALB in same ingress-group, with ALB name append with incremental number, i.e. `ingress-group-A-alb-2`?

**Comment by M00nF1sh** [comment]
@thanhma 
we currently didn't offer such feature. as it's complicated to implement it in a stable way. 
e.g. 
1. users might add rules into a different Ingress, which makes it exceed 100 rules. breaking it up might cause downtime.
2. the rules for same hostname should be in one ALB. however, it might be in different Ingress.

**Comment by M00nF1sh** [comment]
closing this one as we don't have a proper way to support this.

**Comment by thanhma** [comment]
@M00nF1sh  I see.

So I will need to handle it from Ingress creation and apply.

Thank you.
