### ISSUE TITLE
Target group not deleted

### ISSUE THREAD

**Issue by sechunOH** [kubernetes-sigs/aws-load-balancer-controller#2014]
Hello. I'm using alb controller and Ingress object(helm provider) in terraform.
Shortly, target groups are not deleted when I delete Ingress object, ALB controller in turn.

Ingress object has dependency with alb controller, so they are deleted in turn
but there may be something for ALB Controller to do before deleted. (includes deleting target group)
I just tested with no POD deployment, only with Ingress and Service with NodePort.
```
resource "helm_release" "ingress" {
  ...

  depends_on = [
    helm_release.alb_controller,
  ]

  ...
}
```

Please let me know how to delete alb controller gracefully.

**Comment by kishorj** [comment]
@sechunOH, before deleting the controller, you need to delete all of the ingresses managed by the controller. Do you see any errors in the controller logs when you delete the ingress?

**Comment by M00nF1sh** [comment]
@sechunOH 
If you are using ALBController v2.0.0+, it adds finalizers to Ingress and Service events, which are only cleaned up after all AWS resources for Ingress/Services is deleted.
Is it possible in terraform to wait Ingress/Service deletion before delete the controller itself?

**Comment by sechunOH** [comment]
@kishorj 
Thanks for reply. I destroyed Ingress with terraform helm provider. There was no error when I destroyed my Ingress only.
But I got some errors when I destroyed my Ingress and ALB Controller v2.0.0+.

My helm_release resource for installing Ingress has ALB Controller dependency like above my first comment.
So, I think they are deleted in turn like below message from terraform.
```
module.mymodule.helm_release.init_ingress: Destroying... [id=init-ingress]
module.mymodule.helm_release.init_ingress: Destruction complete after 0s
module.mymodule.helm_release.alb_controller: Destroying... [id=alb-ingress-controller]
module.mymodule.helm_release.alb_controller: Destruction complete after 2s
```

but, ALB Controller is deleted after some errors occured.
```
{"level":"info","ts":1621416856.4612236,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"default/init-ingress\",\"resources\":{}}"}
E0519 09:34:16.773618       1 leaderelection.go:320] error retrieving resource lock kube-system/aws-load-balancer-controller-leader: configmaps "aws-load-balancer-controller-leader" is forbidden: User "system:serviceaccount:kube-system:ingress-controller" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
{"level":"info","ts":1621416857.4546728,"logger":"controllers.ingress","msg":"deleting loadBalancer","arn":"arn:aws:elasticloadbalancing:ap-northeast-2:728318878052:loadbalancer/app/k8s-default-initingr-d8be78ac88/73b3c3c544830aa8"}
{"level":"info","ts":1621416857.5296233,"logger":"controllers.ingress","msg":"deleted loadBalancer","arn":"arn:aws:elasticloadbalancing:ap-northeast-2:728318878052:loadbalancer/app/k8s-default-initingr-d8be78ac88/73b3c3c544830aa8"}
{"level":"info","ts":1621416857.5297291,"logger":"controllers.ingress","msg":"deleting targetGroupBinding","targetGroupBinding":{"namespace":"default","name":"k8s-default-apigatew-c681418edc"}}
{"level":"error","ts":1621416857.5319998,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"init-ingress","namespace":"default","error":"targetgroupbindings.elbv2.k8s.aws \"k8s-default-apigatew-c681418edc\" is forbidden: User \"system:serviceaccount:kube-system:ingress-controller\" cannot delete resource \"targetgroupbindings\" in API group \"elbv2.k8s.aws\" in the namespace \"default\""}
{"level":"info","ts":1621416857.5371463,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"default/init-ingress\",\"resources\":{}}"}
{"level":"info","ts":1621416857.7404006,"logger":"controller","msg":"Stopping workers","controller":"ingress"}
{"level":"info","ts":1621416857.7404366,"logger":"controller","msg":"Stopping workers","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding"}
{"level":"info","ts":1621416857.740475,"logger":"controller","msg":"Stopping workers","controller":"service"}
{"level":"info","ts":1621416857.7405334,"logger":"controller-runtime.webhook","msg":"shutting down webhook server"}
{"level":"info","ts":1621416857.88343,"logger":"controllers.ingress","msg":"deleting targetGroupBinding","targetGroupBinding":{"namespace":"default","name":"k8s-default-apigatew-c681418edc"}}
{"level":"error","ts":1621416857.8854492,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"init-ingress","namespace":"default","error":"targetgroupbindings.elbv2.k8s.aws \"k8s-default-apigatew-c681418edc\" is forbidden: User \"system:serviceaccount:kube-system:ingress-controller\" cannot delete resource \"targetgroupbindings\" in API group \"elbv2.k8s.aws\" in the namespace \"default\""}
rpc error: code = Unknown desc = Error: No such container: 3d89b7a0ed6a547a7935db04dad4b006e9162ae5cbc6a09baf347faf4d79ff00%
```

@M00nF1sh 
Thanks too. 
You mean that I should delete not only Ingress but also services before deleting ALB Controller, right?
I will test it, but I think ALB controller and Ingresses are separate parts with k8s Services resource.
I guess ALB Controller lose some permissions according to above errors. What do you think about it?

**Comment by M00nF1sh** [comment]
@sechunOH 
1. `You mean that I should delete not only Ingress but also services before deleting ALB Controller, right?`, no, only Ingresses need to be deleted (If you are not using NLB with ALBCONTROLLER)
1. How do you delete the Ingress resource? the delete command merely mark the Ingress to be deleted, but it's only real deleted once the ALBController cleaned up all the resources. see https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/.

Is it possible in terraform to wait until all Ingress resources is real deleted? (i'm not familiar with terraform tbh)

**Comment by sechunOH** [comment]
@M00nF1sh 
I delete ingress resource with terraform helm provider. But I need more research of that how helm provider determine helm_release resource is deleted totaly. I think it may use terraform kubernetes provider.

You are saying that I should determine the deletion with not just kubernetes delete api response, but also finalizer on that Ingress resource (with get api?). right?

**Comment by M00nF1sh** [comment]
@sechunOH 
Yes. Similar how `kubectl delete ` works, by default it issues delete api first, and then poll(via get API) to wait for the resources actually deleted.

**Comment by sechunOH** [comment]
@M00nF1sh 
Okay. I will go along that way.
Maybe it cannot be handled with just terraform and helm provider..

Thanks a lot.
