### ISSUE TITLE
Question: is cert-manager a hard requirement?

### ISSUE THREAD

**Issue by syscll** [kubernetes-sigs/aws-load-balancer-controller#2015]
After reading through the docs, I cannot see any reference to _why_ cert-manager is needed by the AWS Load Balancer Controller. I understand it is used to provision SSL certs via Let's Encrypt, but if I plan to use ACM certs with my ALBs, do I really need to install it?

The problem being, cert-manager requires me to `kubectl apply` 26k+ lines of YAML into my cluster and for security reasons I don't want to blindly do this.

I noticed the `aws-load-balancer-controller` Deployment mounts a secret named `aws-load-balancer-webhook-tls`, which seems to be created by cert-manager. What is this used for? And can I pass my own self-signed cert here instead?

**Comment by jescarri** [comment]
It apears is used to provising the TLS certs for the webhooks, in theory you can provide your own certs just make sure the hostname of the certs match the service fqdn of the webhook.

**Comment by kishorj** [comment]
@syscll, the TLS certs are needed for the webhooks. We didn't hardcode the TLS key/cert with the manifests for security reasons. You don't need cert-manager if you manage the secret on your own. 

You could also install the controller via helm chart, there is no dependency on the cert manager.

**Comment by syscll** [comment]
@jescarri thanks for the info!

> @syscll, the TLS certs are needed for the webhooks. We didn't hardcode the TLS key/cert with the manifests for security reasons. You don't need cert-manager if you manage the secret on your own.

@kishorj this makes sense! So it's ok for this secret to contain a self-signed cert that I manage? If so, does the FQDN of the cert matter?

**Comment by jescarri** [comment]
@syscll It does matter, you will need to create the self signed cert with the following fqdns.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/config/certmanager/certificate.yaml#L18-L20
 
For example if the webhook svc name is foo and the namespace is bar:
foo.bar.svc
and SAN:
foo.bar.svc.cluster.local

**Comment by syscll** [comment]
Thanks, @jescarri! I was just looking at the v2.2.0 yaml and noticed the following DNS names:
```yaml
dnsNames:
- aws-load-balancer-webhook-service.kube-system.svc
- aws-load-balancer-webhook-service.kube-system.svc.cluster.local
```

I will not be changing the service name or namespace so I will create the cert using the above.

**Comment by syscll** [comment]
I managed to get this working using a local CA self-signed cert. Thanks!

I did this manually without the use of Helm. Is this something worth documenting, or is this an unofficial path?

**Comment by kishorj** [comment]
@syscll, if you share the steps, it is extremely helpful for other users in similar situation. 

You are welcome to submit a  docs PR with the steps.

**Comment by syscll** [comment]
Will work on some docs for this and submit a PR. Thanks again for the help!

**Comment by kuroneko25** [comment]
Did you get a chance to work on the docs? We are in a similar situation and would appreciate more details on the steps you took here.

**Comment by syscll** [comment]
> Did you get a chance to work on the docs? We are in a similar situation and would appreciate more details on the steps you took here.

I will try and PR some docs this week! Will comment here once it's done.
