### ISSUE TITLE
Issue with IAM policy for version 2.2.0

### ISSUE THREAD

**Issue by pmachado212** [kubernetes-sigs/aws-load-balancer-controller#2018]
Good Day

There are missing permissions in the below policy:

https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.0/docs/install/iam_policy.json 

When using this policy the Ingress creation fails with a lack of authorization, does the policy need to be edited?

I know that the issue is with policy permissions because when I attach the Full Admin policy and test...the ingress creates. It is difficult to troubleshoot which permissions need to be added as there is no further information in the logs.

**Comment by kishorj** [comment]
@pmachado212, what errors do you see in the controller logs?

**Comment by Leankit-Stuart-Will** [comment]
We're running into the same issue. Permissions error that can be resolved by attaching an admin policy to the role.

Controller logs show a constant stream of these errors:
`{"level":"error","ts":1621443417.9175518,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"instantcoffee","namespace":"ic","error":"couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 72de59ae-f804-4f81-b069-8b04114b67b0"}`

Unfortunately as @pmachado212 mentioned, the errors don't get into which IAM perms are missing or what operation it's getting stuck on.

**Comment by pmachado212** [comment]
@kishorj herewith the logs:

{"level":"info","ts":1621347235.181692,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1621347235.1817973,"logger":"controller","msg":"Starting Controller","controller":"ingress"}
{"level":"info","ts":1621347235.1818817,"logger":"controller","msg":"Starting workers","controller":"ingress","worker count":3}
{"level":"error","ts":1621353946.890053,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"skipper-prod-io","namespace":"qa","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 78f350e4-a161-4f26-bd67-df8051749a90"}
{"level":"error","ts":1621353946.950792,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"skipper-prod-io","namespace":"qa","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 52ba7300-4247-402b-aaa0-230db99b2b45"}
{"level":"error","ts":1621353947.2183053,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"skipper-prod-io","namespace":"qa","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 925a5657-4ebf-4f6f-808b-bd62651b55a0"}
{"level":"error","ts":1621353948.0860603,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"skipper-prod--io","namespace":"qa","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 59ccf646-30c0-4e77-b45a-382262c2f679"}
{"level":"error","ts":1621353948.307852,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"skipper-prod--io","namespace":"qa","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 1d816dc9-e508-4013-8368-c6c20001c01d"}

**Comment by pmachado212** [comment]
@Leankit-Stuart-Will add the following annotation to your ingress: alb.ingress.kubernetes.io/subnets: <subnet ids>, you can also tag your subnets as per: https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

**Comment by M00nF1sh** [comment]
@pmachado212 @Leankit-Stuart-Will 
would you help double check that you have `"ec2:DescribeAvailabilityZones"` in the iam policy you created? it's a new permission we included in https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.0/docs/install/iam_policy.json

**Comment by pmachado212** [comment]
@M00nF1sh I didn't have it, but I added it and will test tomorrow and let you know.

Thank you!

**Comment by Leankit-Stuart-Will** [comment]
@M00nF1sh We also don't have that perm in our policy. We're using eksctl to auto-generate those though, and it looks like this is an issue on their part that will hopefully get updated shortly.

Related Issue: https://github.com/weaveworks/eksctl/issues/3714
Specifically when using an eksctl config like so:
```iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
```

In the meantime, we'll just manually add that line to the policy as a workaround.

Thanks so much for the help!

**Comment by M00nF1sh** [comment]
@Leankit-Stuart-Will I created an PR to update EKSCTL with updated policy: https://github.com/weaveworks/eksctl/pull/3734

**Comment by M00nF1sh** [comment]
resolving this as the PR in eksctl is merged
