### ISSUE TITLE
Why ingress with the same group-name delete older?

### ISSUE THREAD

**Issue by b0nete** [kubernetes-sigs/aws-load-balancer-controller#2020]
Hi, i have a doubt.

Currently in my cluster i have 2 ALBs controllers, 
- alb-internal (for ingresses with internal scheme)
- alb-public (for ingresses with internet-facing scheme)

I tried to deploy the same application with differents domains; specifying differents schemes but using the same group.name. 
The problem with this is that it delete the older ALB. For example, if i deployed the firs ingress using this annotations, this create a public ALB.

```
annotations: |
        kubernetes.io/ingress.class: "alb-ingress-public-prd"
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/group.name: backend-api-public
```

But when deploy other ingress using these annotations for internal scheme, this delete public ALB and create new internal ALB, this behaviour is correct?
I see a problem here, because by error i use the same group name with different scheme this delete mi older ALB.

```
annotations: |
        kubernetes.io/ingress.class: "alb-ingress-internal-prd"
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/group.name: backend-api-internal
```

I hope responses, thank you!

**Comment by M00nF1sh** [comment]
@b0nete 
You shouldn't have two different deployment of ALB controller running. there should only be one deployment of ALB controller in your cluster. 
controller isn't aware of the existence of other controllers, so your alb-ingress-internal-prd will try to reconfigure the lb for "backend-api-internal" group from internet-facing to internal.

Please install a single deployment of the controller only. If you want to limit the scheme for different Ingresses, please use our https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/ingress_class/ feature instead.

**Comment by b0nete** [comment]
Thanks for fastly response!.
Im going to test this.

I noted the helm chart dont provide this option, i will create this resources manually and sure send a PR for add this feature.

**Comment by M00nF1sh** [comment]
closing this. feel free to create a new issue if you have further question :D
