### ISSUE TITLE
Reconciler error with colon in tag name

### ISSUE THREAD

**Issue by mhr3** [kubernetes-sigs/aws-load-balancer-controller#2021]
I've tried to use the recently added `alb.ingress.kubernetes.io/target-node-labels` annotation and set it to: `eks:nodegroup-name=core-ng-1`, but that doesn't seem to work, I see these errors in the logs:

```json
{
  "level":"error",
  "ts":1621446807.273297,
  "logger":"controller",
  "msg":"Reconciler error",
  "reconcilerGroup":"elbv2.k8s.aws",
  "reconcilerKind":"TargetGroupBinding",
  "controller":"targetGroupBinding",
  "name":"<redacted>",
  "namespace":"<redacted>",
  "error":"invalid label key \"eks:nodegroup-name\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')"}
```

Not sure if that's a limitation of the ALB controller or ALB itself?

**Comment by M00nF1sh** [comment]
@mhr3 
The `alb.ingress.kubernetes.io/target-node-labels` is used to filter nodes with specific labels.
`eks:nodegroup-name` cannot be used as Kubernetes label. the label key `must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')"`

It's Kubernetes restriction.

**Comment by mhr3** [comment]
Oh, for some reason I thought I need to set it to the AWS instance tag, and not just the k8s node label. Works fine with `eks.amazonaws.com/nodegroup=core-ng-1` thanks!

**Comment by M00nF1sh** [comment]
yes, it's the k8s node selector. we'll update the docs to note it's k8s label selector.
closing this :D
