### ISSUE TITLE
Feature Request: Allow annotation for NLB to set security group rules to be Managed Prefix Lists

### ISSUE THREAD

**Issue by than-tryf** [kubernetes-sigs/aws-load-balancer-controller#2030]
Hello,

We are using the aws-load-balancer-controller to manage NLBs. However we face an issue in case we need to define service.beta.kubernetes.io/load-balancer-source-ranges and the CIDRs we provide create security groups that exceed the 60 rules limit that aws enforces. For that reason we create Managed Prefix Lists on AWS and we provide them manually as rules to security groups. 

It would be useful if  there was an annotation that would allow values to be Managed Prefix Lists

**Comment by kishorj** [comment]
@than-tryf, as per the managed prefix lists documentation [[link](https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html#create-managed-prefix-list)], the prefix list does not help overcome sg quota for rules.  

```
You can't add a prefix list to a security group rule if the number of rules plus the max entries for the prefix list exceeds the quota for rules per security group for your account. 
```

Other than the quota issue, this is a good feature to have . 

/kind feature

**Comment by than-tryf** [comment]
@kishorj yes you are right about the quota limitations.

**Comment by than-tryf** [comment]
sorry, i closed this by mistake
