### ISSUE TITLE
Subnets annotation not working

### ISSUE THREAD

**Issue by matthewmrichter** [kubernetes-sigs/aws-load-balancer-controller#2031]
[The documentation implies](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#subnets) that by setting Ingres annotation `alb.ingress.kubernetes.io/subnets:` with a comma/space separated list of subnet ID's or subnet names, we can manually specify the subnets that a particular LB group uses for its load balancer. However, the tags on the subnets (`kubernetes.io/cluster/` and `kubernetes.io/role/elb=1`) seem to override this behavior and cause auto-discovery to be used, which is a problem in my case.

So, we have let's say I have "Subnets ABC" and "Subnets XYZ" in the same VPC, which are hosting legacy and new clusters I'm building with AWS LBC. These subnets have the `kubernetes.io/cluster/` and `kubernetes.io/role/elb=1` tags on them. I don't have much flexibility to use different subnets or change the tagging on these legacy subnets. Using Ingress annotations, I specify that I want an ALB to be created in "subnets ABC":

```
kubernetes.io/ingress.class: alb
alb.ingress.kubernetes.io/scheme: internet-facing
alb.ingress.kubernetes.io/subnets: subnet-aaaaaa, subnet-bbbbb, subnet-ccccc
alb.ingress.kubernetes.io/certificate-arn: {{ $.Values.stockAlbs.albCertificateArns }}
alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]' 
```

Unfortunately the AWS LBC is creating my load balances in subnets A, Y, Z via autodiscovery rather than the explicitly specified subnets. This is problematic due to the separate allowlisting rules for those two separate sets of subnets.

(I will also note this is a load balancer "model" - I am creating a "dummy" Ingress object in advance with the above annotations and downstream ingresses merge into a group with the model. )

So.. is there any way to force-disable Subnet Autodiscovery without removing tags from the subnets? Or a way to tell a cluster to use different tags for autodiscovery?

**Comment by mars64** [comment]
* What is the complete tag (including value) of `kubernetes.io/cluster/`? You may wish to review https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1905#issuecomment-810644265 
* What version of the controller are you using? What does the controller log regarding subnet selection?
* What cluster version? How are you creating clusters? [Note that eksctl automatic tagging changed in at least 1.19 ](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1905) and [AWS LBC tagging requirements changed in 2.1.2](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/subnet_discovery/#common-tag)

**Comment by matthewmrichter** [comment]
* Complete tag: `"kubernetes.io/cluster/infra-us-east-1-rp-eo-test"            = "shared"`
* Controller version: 2.2.0
* Cluster version: EKS 1.19

**Comment by kishorj** [comment]
@matthewmrichter, when you specify the `alb.ingress.kubernetes.io/subnets` annotation on an ingress, subnet auto-discovery is disabled for the ALB. Is it possible that you created an ingress with auto-discovery at first and when you specified the subnets annotation, controller encountered errors and did not update the ALB? You can check whether there are any errors in the controller logs.

Also check if the controller correctly generated the ALB model with the subnets you specified. You can find it in the controller log containing the following string
`
... "controllers.ingress","msg":"successfully built model","model ...
`

**Comment by matthewmrichter** [comment]
I got it to work. Here are the things I have done that have made this work:

* Introduce a 5 minute delay after deployment of AWS LBC and my model ingresses so the model can be successfully built before attempting to create more ingresses in the LB "group."
* Remove spaces from stringLists, eg use `subnet-aaaa,subnet-bbbb` instead of `subnet-aaaa, subnet-bbbb`. I also had to do this with the security groups annotation.

**Comment by mars64** [comment]
>     * Introduce a 5 minute delay after deployment of AWS LBC and my model ingresses so the model can be successfully built before attempting to create more ingresses in the LB "group."

Guessing there may be a bit of order-of-operation problem in your setup. At a high level, there are three things that need to happen in order: install the crds, install the lb controller, install the ingress with the annotations that trigger the controller. 
It may be that your installation method is happening out of order. Check events in the kube namespace, controller logs, etc. Or maybe the delay works fine for your case. 

>     * Remove spaces from stringLists, eg use `subnet-aaaa,subnet-bbbb` instead of `subnet-aaaa, subnet-bbbb`. I also had to do this with the security groups annotation. I don't know if this maybe constitutes a bug in the handling of annotations or at least a documentation fail.

I totally [agree that the `example` is totally confusing](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/ingress/annotation/#subnets):

```
alb.ingress.kubernetes.io/subnets: subnet-xxxx, mySubnet
```

This makes it looks like spaces should work.

However, check out: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/ingress/annotation/ 

```
* Annotation keys and values can only be strings. Advanced format are encoded as below:
  * stringList: s1,s2,s3
```

It would be great if the provided examples followed the rules too.

**Comment by kishorj** [comment]
controller trims the leading and trailing whitespaces for annotations of type stringList. 

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/dde29f02e011343a5d35f49cfe59c476063f2f4a/pkg/annotations/parser.go#L189

**Comment by mars64** [comment]
> controller trims the leading and trailing whitespaces for annotations of type stringList.

That's not the problem --  a list of strings in csv+space format, e.g. `subnet-1, subnet-2` is not a `stringList`. But the example makes it look like csv+space works. It doesn't.

**Comment by kishorj** [comment]
@mars64, for the `alb.ingress.kubernetes.io/subnets` annotation, any leading and trailing spaces for the individual subnets get trimmed. Both of the following examples are valid 
- alb.ingress.kubernetes.io/subnets:  subnet-xxx  ,   subnet-yyy   
- alb.ingress.kubernetes.io/subnets:  subnet-xxx ,subnet-yyy

**Comment by mars64** [comment]
> @mars64, for the `alb.ingress.kubernetes.io/subnets` annotation, any leading and trailing spaces for the individual subnets get trimmed. Both of the following examples are valid

Woah! Ok then OP has a different problem, thanks for correcting me, good to know.

**Comment by M00nF1sh** [comment]
@matthewmrichter You don't need to wait 5 minute after install the controller. 
but you do need to wait for the controller pod to be ready before creating Ingresses as we have webhook injecting Ingresses creation.

@mars64 @matthewmrichter did kishor's answer answers for your issues?

**Comment by mars64** [comment]
> @mars64 @matthewmrichter did kishor's answer answers for your issues?

Thanks for following up. Seems like @matthewmrichter has a different problem around annotations, but will let him pursue that issue.

**Comment by matthewmrichter** [comment]
I popped my ingresses into the helm chart deploying AWS LBC, so pretty good change that the dependency order is not being met. I will break the stock ingresses out to a separate chart that will deploy after, and report back.

**Comment by M00nF1sh** [comment]
@matthewmrichter 
Does this issue still persist? 
If so, feel free to create an new issue 😄
