### ISSUE TITLE
Using wildcards in path

### ISSUE THREAD

**Issue by project-administrator** [kubernetes-sigs/aws-load-balancer-controller#2041]
After upgrading to version 2.2.0 I'm seeing these errors:
```
{"level":"error","ts":1622459291.638713,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"myname","namespace":"","error":"ingress: default/my-ingress: prefix path shouldn't contain wildcards: /*"}
```

Is path `/*` not allowed anymore? But there are lots of mentions of paths having wildcards in the docs and examples. Should we just use the `path: /` instead of the `path: /*`? Or am I misunderstanding the issue?

**Comment by jdomag** [comment]
@project-administrator 
Did you solve it?

**Comment by project-administrator** [comment]
@jdomag Yes, I had to change all ingress resources to use the `Path: /` instead of `Path: /*`. I don't remember, but maybe I had to delete and re-create all ingress resources.
Actually, it's better to make the change while running the older version of the controller to avoid getting these errors.

**Comment by jdomag** [comment]
@project-administrator 
The problem is that when you use `Path: /` the new controller creates `/*` in ALB rule on AWS, once the old one creates `/` - so deleting `/*` first is not an option. 
I wish the migration docs mentions this, I would plan it much better ;)
