### ISSUE TITLE
random deRegistering / registering targets

### ISSUE THREAD

**Issue by flyguybravo** [kubernetes-sigs/aws-load-balancer-controller#2044]
The controller in our environment recently initiated "deRegistering" and "registering" target events for all targets on all ingress objects without being user initiated.  This caused our security monitoring to alert to unexpected alteration of our environment.  

I am not able to see any obvious reason for this modification by the controller.  Is there a way to discover why this series of events took place?

Here's an excerpt from the controller console log for a single service in one of our ingress objects:
``` json
{"level":"info","ts":1622339658.7193022,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a111111c1a/dddddddddddddddd","targets":[{"AvailabilityZone":null,"Id":"i-11111111111111111","Port":30233}]}
{"level":"info","ts":1622339658.7639265,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a180939c4a/dddddddddddddddd"}
{"level":"info","ts":1622339659.688296,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a180939c4a/dddddddddddddddd","targets":[{"AvailabilityZone":null,"Id":"i-22222222222222222","Port":30233}]}
{"level":"info","ts":1622339659.7143834,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a180939c4a/dddddddddddddddd"}

{"level":"info","ts":1622339660.4293568,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a180939c4a/dddddddddddddddd","targets":[{"AvailabilityZone":null,"Id":"i-22222222222222222","Port":30233}]}
{"level":"info","ts":1622339671.4926465,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a180939c4a/dddddddddddddddd"}
{"level":"info","ts":1622339672.1465905,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a180939c4a/dddddddddddddddd","targets":[{"AvailabilityZone":null,"Id":"i-11111111111111111","Port":30233}]}
{"level":"info","ts":1622339672.2857041,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:us-east-2:012345678965:targetgroup/our-service-a180939c4a/dddddddddddddddd"}
```

The nodeports and instances did not change -- the target was simply deRegistered then Registered again a few moments later. 

This environment has two ingress objects. The controller's console log shows these were last successfully deployed on May 7 and 9th. 

Using `aws-load-balancer-controller:v2.1.3`

**Comment by kishorj** [comment]
@flyguybravo, do you have audit logs enabled for your cluster? Could you correlate these to any changes to your node resources during the time? It is possible there have been some changes to the k8s resources, for example some third party component in the cluster modifies the tags/annotations on the node resources.

**Comment by flyguybravo** [comment]
@kishorj  - I worked with AWS support and was able to identify maintenance within RDS as the culprit which ultimately caused health checks to fail.  

Would it be possible for the controller to provide contextual information in the console log about events that trigger an action?  

For example, in the case of this event, _before_ outputting to the console logs indicating that deregister and re-register target actions are taking place, output a message to indicate that an action is being triggered as a result of a specific event -- such as 'N failed target health checks over X minutes' -- or similar.  Just enough information to help localize the search through CW logs.

This ended up being more time consuming to pin down than it should have because the CloudWatch logs for EKS are very noisy.

**Comment by M00nF1sh** [comment]
@flyguybravo 
If you enable debug log, you should see the events triggering reconcile, e.g. from https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/controllers/elbv2/eventhandlers/endpoints.go#L75

However, we don't have more context information from the controller's perspective. e.g. why a pod is been removed from the endpoints. doing that would couple this controller with specific endpointsController(embed in k8s)'s logic.
