### ISSUE TITLE
Periodical spikes (~30min) at TargetResponseTime metric

### ISSUE THREAD

**Issue by manideepl** [kubernetes-sigs/aws-load-balancer-controller#2045]
We have an ALB behind which there is an EKS cluster.
The metric shows spikes every half an hour, even though there's no scheduled/cron job running.
Could someone point where to look at? We exhausted all options - load balancer logs, app logs, cloud watch metrics for eps etc :(

**Comment by kishorj** [comment]
@manideepl, the target response time is not related to this controller as it only sets up the ALB and target group. It has something to do with your application or the data path. Would you be able to open a case with the EKS team with your cluster ARN and the detailed logs?

**Comment by manideepl** [comment]
Thank you, will try that! But would you please advise which logs exactly that would help us?

**Comment by manideepl** [comment]
![Screenshot 2021-06-22 at 8 21 20 PM](https://user-images.githubusercontent.com/52558700/122946952-6a303a00-d397-11eb-9eee-1a1ea245eed5.png)
Would you please help me understand this?

**Comment by kishorj** [comment]
@manideepl
SuccessfullyReconciled event means controller has reconciled the lb target groups based on the changes to your endpoints/nodes.

You will need to enable ALB access logs and share it on the AWS ticket.
