### ISSUE TITLE
HELM  POD is created before the Ingress or Service Causing pod to never be Ready

### ISSUE THREAD

**Issue by marcelobartsch** [kubernetes-sigs/aws-load-balancer-controller#2047]
with version 2.2.0 , when using HELM to deploy and create the Ingress and a Deployment, HELM  create the Deployment and POD before the Ingress is created[1] , causing the pod to never become ready, as the mutatingwebhook only works when the POD is created.

So everytime that helm is used to deploy, the ReadinessGates will fail as the ingress is not yet created when the pod is created and no ingress is configured. so it will do nothing. if you kill the pod 'mid-deploy' it will be recreated and the mutatingwebhook will do it's job as expected and the helm deploy will complete successfully 

how to reproduce:
Have a helm chart that define readinessGates in the deployment.

the one we use I can't share it here , and couldn't find any to test

[1] https://github.com/helm/helm/blob/release-3.0/pkg/releaseutil/kind_sorter.go

**Comment by M00nF1sh** [comment]
@marcelobartsch 
 for the initial deployment, the pods won't have ReadinessGates injected, so they should operate normal. When you say "causing the pod to never become ready", how is that actually caused?

our Ingress ReadinessGates is designed to protect deployments, so it's totally fine for the initial pods to not have ReadinessGates is injected

**Comment by marcelobartsch** [comment]
@M00nF1sh Hi, yeah remove the readinesGates from the templates in helm fix the issue, but is not the expected behavior, as in 2.1 this worked without problems, I will create a sammple helm chart to explain and be able to reproduce the issue , which I think will help better to explain it.

**Comment by M00nF1sh** [comment]
@marcelobartsch thanks, it would be good if you can share the reproduce helm template. 
There isn't changes related to readinesGate in v2.2 compared with v2.1

**Comment by marcelobartsch** [comment]
@M00nF1sh Hey , sorry I was kind busy with the upgrade of our EKS clusters, and to be honest after a lot of think on your comment we realize we are doing it wrong as having readiness gates on the initial deploy make no much sense, so we just remove that from our helm chart, and we were unable to reproduce the problem using just yaml files. so I will close this Issue unless we have enough data to reproduce it in a consistent way.

you can safely flag this as PEBCAK
