### ISSUE TITLE
Terrible HA/FT test results for the ALB/NLB "Ip mode" compare to "instance mode" 

### ISSUE THREAD

**Issue by lmgnid** [kubernetes-sigs/aws-load-balancer-controller#2048]
lmgnid commented on Nov 2, 2020 • 
Hello, I am testing the IP Mode for both NLB and ALB, compare to the instance mode, the only difference of the setting are:

alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/target-type: instance

service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

But the tested these IP mode NLB/ALB, they are terrible HA/FT results and service breaks (Test by delete the pod, or update the deployment):

For NLB, 2-3 mins service break, compare to No break in instance mode for the same testing
For ALB, 10s service break, compare to No break in instance mode for the same testing
Some other information:
EKS version: 1.18 eks.2
image: amazon/aws-alb-ingress-controller:v2.0.0

Any ideas? Thanks!

@kishorj
 
Collaborator
kishorj commented on Nov 2, 2020
Have you tried pod readiness gate?
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/controller/pod_readiness_gate.md

@lmgnid
 
Author
lmgnid commented on Nov 2, 2020 • 
Yes, tried it in NLB, didn't see any differences. Didn't even bother to test in ALB though.
For a new POD, the NLB need ~3 mins to mark it as health, even I only set 210 seconds. The readiness gate will delay the POD updates during deployment deployment and solve the health issue as it suppose to solve.
But the 2-4 mins service break is still there, it seems the issue is NLB cannot catch the unhealth/terminated pod, even I only set 210 seconds as well.
So In details:

Without readiness gate: I saw see a whole 2-3 mins break, as even no health POD in the NLB during some time, also the health POD can only be detected by NLB ~3 mins.
With readiness gate: I saw 1mins break, then recovered for couple of seconds then another 1 mins break, then recovered again, then ~40s service break again. I always saw health POD in the NLB though. Also I saw in my deployment with HPA min 2 had a much longer update time because of the readiness gate, which means it was working.
@dza89
 
dza89 commented on Nov 3, 2020
I'm afraid that this is not a controller issue but and issue of the NLB itself.

@M00nF1sh
 
Collaborator
M00nF1sh commented on Nov 3, 2020
@lmgnid
You need to enable podReadinessGate for IP mode: https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/pod_readiness_gate/

Also, you need to have prestop hook for both instance/ip mode if your app don't support graceful shutdown.

@kishorj
 
Collaborator
kishorj commented on Nov 11, 2020
Closing the issue for now. Feel free to reopen this if you have further concerns.

@M00nF1sh M00nF1sh closed this on Nov 11, 2020
@infa-sanaik
 
infa-sanaik commented on Jan 23
@imgnid Did you find any solution for this issue? We are also facing same issue.

@blhagadorn
 
blhagadorn commented on Jan 26
@infa-sanaik Do you have podReadinessGate and prestop hook configured? What are you seeing, exactly?

@lmgnid
 
Author
lmgnid commented now
Really don't understand why this ticket is closed, @kishorj : Did you EVER really test it?
Just tested it again with the EKS1.20 and LB controller v2.1.2, still the same for at least NLB.
Also for @M00nF1sh's questions:
1: Yes as my comments above I tried with PodReadinessGate
2: Yes we DO have graceful shutdown, also we have NO issues in instance mode.

As my comments above, I found NLB cannot catch the health pods on time in IP mode. . For example a healthy pods need ~3mins to be "healthy" in TG, even I only set as 2*10=20-30 seconds. Also I notice the even the unhealthy pod status will be synced to TG on time, but still service break so must be some issues in the "draining" in IP mode for POD. As we don't have this issue in "instance mode" if I deleted a pod.

**Comment by M00nF1sh** [comment]
@lmgnid 
Please check the repo: https://github.com/M00nF1sh/ReInvent2019CON310R, which presents an application to be able to perform deployment in zero downtime. check the commits message there for factors involved.

in short, podReadinessGate should be enabled, proper prestop sleep time should be added, protocol specific shutdown should be considered as well(e.g. if HTTP keep alive is enabled by default in HTTP 1.1, alb always reuses backend connection)
