### ISSUE TITLE
nlb-ip just created internal mode without annotation

### ISSUE THREAD

**Issue by ilpyoung** [kubernetes-sigs/aws-load-balancer-controller#2049]
hi I have something problem
`
apiVersion: v1
kind: Service
metadata:
  name: xcast-router
  namespace: xcast
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:~~:certificate/520a0ada-6~
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  labels:
    app: xcast-router
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3002
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3001
  selector:
    app: xcast-router
`

I used this yaml file, depoly service with alb-controller

But it's just created nlb internal mode
I dont uses annotaion internalmode

<img width="481" alt="스크린샷 2021-06-04 오전 11 57 39" src="https://user-images.githubusercontent.com/85208281/120739174-12d34280-c52c-11eb-9410-c55e588e81d7.png">

Please reply thx..

**Comment by kishorj** [comment]
@ilpyoung, starting v2.2.0 release, controller will create an internal NLB by default unless you explicitly specify the load balancer scheme as internet-facing.
```
service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
```
This is called out in the release notes for v2.2.0 [[link](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0)].

**Comment by ilpyoung** [comment]
> @ilpyoung, starting v2.2.0 release, controller will create an internal NLB by default unless you explicitly specify the load balancer scheme as internet-facing.
> 
> ```
> service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
> ```
> 
> This is called out in the release notes for v2.2.0 [[link](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0)].

Oh.. Couldn't read release notes
Thanks for help
