### ISSUE TITLE
Feature Request: Subnet discovery to be able to select subnet based on available address spaces

### ISSUE THREAD

**Issue by anthonysuterag** [kubernetes-sigs/aws-load-balancer-controller#2056]
We have public subnets that span across 3 AZs, and we use these subnets to host our internet facing LBs. 
Recently, we started to run out of address spaces, so we would like to extend those by adding new subnets, which means we currently have 6 public subnets (two in each availability zone). 

However, I figured out that subnet discovery will select subnet based on lexicographical order by the Subnet IDs (https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/networking/subnet_resolver.go#L148). I think it would be great to adjust this behavior to be able to select subnet based on available address spaces in case of multiple tagged subnets are available.

**Comment by shinji62** [comment]
I would like this to happen too, and happy to make a PR if required.

**Comment by fabasoad** [comment]
Would be great to have it 👍

**Comment by kishorj** [comment]
@anthonysuterag,
Controller already supports configuring custom subnets via annotation. 
`alb.ingress.kubernetes.io/subnets` for ALB
`service.beta.kubernetes.io/aws-load-balancer-subnets` for NLB

Would this not be helpful for your use case?

**Comment by anthonysuterag** [comment]
@kishorj Might be a workaround, but if it is possible, I would like to avoid assigning subnets statically to the Ingress, because in the long run, it would be difficult to maintain and also to keep track as we have a lot of ingresses. So, I would prefer to let subnet discovery to handle the subnets assigning process.

**Comment by M00nF1sh** [comment]
If we add a logic based on available IP addresses, we might need to restrict the subnet auto-discovery for new LB creation only. for existing LBs, we shouldn't invoke subnet auto-discovery as it might change subnets and cause downtime. 

we can do similar things as we currently did for service model builder here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/service/model_build_load_balancer.go#L118

**Comment by shinji62** [comment]
@M00nF1sh Sounds ok for me.
