### ISSUE TITLE
Add annotation to manage egress rules

### ISSUE THREAD

**Issue by lucaspanayiotou** [kubernetes-sigs/aws-load-balancer-controller#2058]
Currently there is an annotation to manage ingress:
alb.ingress.kubernetes.io/inbound-cidrs

To manage egress, you need to create a security group, and then attach this to the load balancer via annotations.

Why is there not an annotation to manage egress?
_alb.ingress.kubernetes.io/outbound-cidrs_

**Comment by kishorj** [comment]
@lucaspanayiotou, since the traffic is ingress from the clients to your application, the egress rules would have no effect.

**Comment by rafaip** [comment]
Is it possible to reopen this?

ALB needs to have outbound to target groups to be able to send the traffic, and by default it's outbound is 0.0.0.0/0. 
It should be possible to restrict the outbound rule for one specific target group

**Comment by jslouisyou** [comment]
Has there been any further review regarding this issue?

It would be better if we can fine-tune the default outbound configuration, which is currently configured as 0.0.0.0/0.
