### ISSUE TITLE
[2.2.0] couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation

### ISSUE THREAD

**Issue by scila1996** [kubernetes-sigs/aws-load-balancer-controller#2060]
Before, I was deploy AWS ALB Ingress follow this guide

https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

and it work with older version before 2.2.0. But when i upgrade or install AWS ALB on new EKS with version 2.2.0, I using helm to deploy and just replace version chart 1.1.6 (2.1.3) to 1.2.0 (2.2.0). And Ingress was not created, this is log from Controller

```
kubectl logs -n kube-system -l app.kubernetes.io/instance=aws-load-balancer-controller -f
```

> {"level":"error","ts":1623141886.8454742,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: aba7d89e-843b-4d18-93e7-a70c76d062e2"}
{"level":"error","ts":1623141927.8661003,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 5ab9af79-7e7d-4b92-819c-a2a83a5c6321"}
{"level":"error","ts":1623142009.8975346,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: fda4a313-43b2-4845-8e79-6682a673eb46"}
{"level":"error","ts":1623142173.8393497,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: a7e21a7b-9e00-4ba6-8476-464c3d04e375"}

What new changed in version 2.2.0 ? Can i mistake something wrong step ? I was changed helm to closer older version is 1.1.6 (2.1.3) and it work !

**Comment by usman-github** [comment]
For aws-load-balancer-controlle version 2.2.0 new IAM Permissions needed.

Check out release notes here :
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0

Sample IAM policy :
https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.0/docs/install/iam_policy.json

**Comment by eldadpuzach** [comment]
Means that You have resources created by ALB ingress controller v1.
Upon [required IAM permissions json](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json) add additional permissions from [iam_policy_v1_to_v2_additional.json](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy_v1_to_v2_additional.json):
![image](https://user-images.githubusercontent.com/37382556/121191438-a54d4c00-c874-11eb-93de-82630fb3a7ec.png)

**Comment by scila1996** [comment]
Thank ! it's worked 👍

**Comment by kwarunek** [comment]
It would be great if the controller could log an operation (IAM name) which failed  in a debug level . I know I can get it through cloudtrail, but nevertheless it would be helpful.
