### ISSUE TITLE
Dealing with Blue/Green Deployment/Argo Rollouts and Readiness Gates

### ISSUE THREAD

**Issue by gaganapplatix** [kubernetes-sigs/aws-load-balancer-controller#2061]
We have some requirements where we need to use argo-rollouts, but the situation would be the same with any sort of blue green implementation which swaps service object selectors.

The problem is lets say you have a stable replicaset which is pointed to by the stable service object which is pointed to by a stable TargetGroup (and a Listener for it) which is taking most of the traffic. Lets say these pods got the stable TargetGroup readiness gate.

Now, you create a new preview replicaset which is pointed to by preview service object which is pointed to by a preview TargetGroup (and a Listener for it) on the same ALB. You test out your preview service and it works and you want to swap to make it the stable one. So you swap the selector on the stable service object to point to the new replicaset pods. At this point the new pods still have the preview TG's readiness gates set and there is no way to verify they are registered in time for the stable TargetGroup because readiness gates are put in at the time of Pod Creation based on the TGs that point to them at that time through a Service object.

Kubernetes general preference for blue/green style deployment is to use swapping of service selector but this clearly doesn't play well with how readiness gates and target group work.

I think the way this could work is if there was a way to configure having readiness gates which can be for more than one target group and the readiness gate represents or between the two or if there was a way to update the readiness gate (which I don't think Pod Yaml allows) to the new path to the Pod.

Any ideas?

**Comment by jessesuen** [comment]
Related: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1764#issuecomment-775396332

> The controller currently doesn't support zero downtime when u modify the Ingress/Service in such way that result in TargetGroup changes(e.g. changed the backend service). The Targets won't be health-checked before added to LoadBalancer

**Comment by M00nF1sh** [comment]
@gaganapplatix @jessesuen 
The recommended way to implement blue/green deployment is using the weighted routing feature of ALB. 

Swapping the labels of Kubernetes is a simple way to do blue/green deployment for in-cluster services only. It don't suits LoadBalancer case for the reasons you outlined. (1. it take time for controller to register new pods, 2. podReadinessgate cannot be mutated on created pods)

**Comment by M00nF1sh** [comment]
closing this as service label swapping is not intended for 0 downtime deployment and cannot leverage the podReadinessgate feature.

feel free to create a new issue if you facing problems using the weighted routing feature. (you can also continue do the service label swapping as well without enable podReadinessgate on your namespace)
