### ISSUE TITLE
Cross namespace ALB

### ISSUE THREAD

**Issue by infakt-HNP** [kubernetes-sigs/aws-load-balancer-controller#2064]
Hello,

is it possible to create one ALB which will point to services in different namespaces? I've tried, but requires separate ALB per namespace.

Thank you.

**Comment by kishorj** [comment]
@infakt-HNP, did you try the ingress group feature and see if it helps with your use case? This feature allows you to group multiple ingress across namespaces to provision a single ALB.

**Comment by infakt-HNP** [comment]
Thank you, It works :)
May I ask where should I put ```--disable-ingress-class-annotation```? To annotations in ingress definition or via helm?

**Comment by kishorj** [comment]
This `--disable-ingress-class-annotation` flag has to be specified as controller container command line argument. You could edit the `aws-load-balancer-controller` deployment.

Helm chart doesn't support it yet. I will add support in the new chart version 1.2.2.

**Comment by infakt-HNP** [comment]
thank you
