### ISSUE TITLE
2048 example will not load on second tab, or new browser, or close and restart browser

### ISSUE THREAD

**Issue by tanvp112** [kubernetes-sigs/aws-load-balancer-controller#2073]
Hi,

I ran the [2048 example](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/examples/2048/2048_full_latest.yaml) and able to access the application running on EKS (worker node on private network) **initially**. But I noticed if I try to access the app with new tab in the browser (with the first and successful one), the page will fail to load. If I close the browser and try to access again immediately, the page is again fail to load (timeout).

Is this the 2048 app behavior or I should configure the service with additional LB annotation/attribute? Not much clue I can find on the annotation document due to my lack of knowledge to AWS LB, but I would like to learn more about this controller.

Appreciate if anyone can provide a pointer to such LB behavior? Thanks!

**Comment by M00nF1sh** [comment]
@tanvp112 
We haven't noticed the behavior before. Is it due to some issues in your network? Have you tried access the game from another network environment?

If it still don't work, would you help check whether the targets in your TargetGroups shows healthy in your AWS console.

**Comment by tanvp112** [comment]
I have AWS console opened and access it with no issues during the tests, Health status all green. Other common task like google browsing etc all work as normal. Have you tried the example with the steps as described? What sort of network issue would you suspect that could cause an issue on the LB end?
