### ISSUE TITLE
Unrecognized resource types after installing ALB Controller 2.2.0

### ISSUE THREAD

**Issue by BanutC** [kubernetes-sigs/aws-load-balancer-controller#2075]
A couple of days ago i performed an upgrade for ALB Controller from version 2.1.3 to version 2.2.0 using Helm.
The upgrade itself performed great, alb-controller pod doesn't show any errors and all components work fine.

But in AWS Console in IAM Policy created for ALB-Controller there are some Resources which appear as Unrecognized.
`arn:aws:elasticloadbalancing:*:*:listener/net/*/*/*`
 `arn:aws:elasticloadbalancing:*:*:listener-rule/app/*/*/*`
 `arn:aws:elasticloadbalancing:*:*:listener/app/*/*/*`
 `arn:aws:elasticloadbalancing:*:*:listener-rule/net/*/*/*`
 `arn:aws:elasticloadbalancing:*:*:targetgroup/*/*`

I'm asking if this is a normal behavior and ignore the warnings in AWS.

**Comment by kishorj** [comment]
@BanutC, this is a UX issue. The ELB service in IAM policies refer to the classic load balancer which doesn't support targetgroup/listener/listener-rule resources. The ELB v2 service in IAM policy is the one for NLB/ALB and will not show the unrecognized errors.

**Comment by pshen** [comment]
Hi, 

I just want to understand if it's really a UX issue.

Looking at the AWS doc https://docs.aws.amazon.com/service-authorization/latest/reference/list_elasticloadbalancingv2.html

The resource types look like below:
listener/net*
listener/app*
listener-rule/app*
listener-rule/net*
targetgroup*

Thanks,
Chenjun
