### ISSUE TITLE
Can I specify application loadbalancer name?

### ISSUE THREAD

**Issue by sechunOH** [kubernetes-sigs/aws-load-balancer-controller#2080]
Hello,
I'm using ALB with aws eks.

I should use static IP for ALB because of security reasons, so I'll use AWS global accelerator.
But in terraform, I cannot know the name or arn of ALB created with Ingress, so I cannot create global accelerator endpoint group with ALB using Terraform.
(it maybe like this pattern: k8s-\<namespacedName\>-\<hash\>)

Is there a way to specify ALB's name or to imply that hash?

**Comment by andor44** [comment]
Yes, the most recent version allows specifying the name (note, NOT the ARN) of the load balancer: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#load-balancer-name

**Comment by M00nF1sh** [comment]
@andor44 Thanks for the clarification 👍 
@sechunOH Did the load-balancer-name works for you? note(it must be a unique name across your entire AWS account, so you'll need to generate the name dynamically by yourself to make it unique in your Terraform)

Closing this, feel free to open a new one if you facing any new issues.

**Comment by sechunOH** [comment]
@andor44 @M00nF1sh
Thanks for the explanation.
Maybe I'm using ALB controller v2.1.x.
We should update the ALB controller version to use that specification.
