### ISSUE TITLE
Manifests for kubectl apply and Helm are very different

### ISSUE THREAD

**Issue by jlpettersson** [kubernetes-sigs/aws-load-balancer-controller#2083]
In the documentation, the Deployment-manifests for `kubectl apply` and Helm are very different.

Some major differences:
* Different number of replicas
* Different Affinity rules configured
* Different Labels

There are probably more differences.

This makes it hard to switch from Helm to `kubectl apply` or the other way. It is also hard to understand what configuration is recommended.

**Comment by M00nF1sh** [comment]
@jlpettersson 
Thanks for the feedback. The yaml version is pretty limited for us to implement features available via helm, and they are currently maintained separately.

We'll converge them to be a single source of truth. (e.g. using helm chart to render the YAML version and have different YAMLs for different settings).

we recently moved the helm-chart to be maintained in this controller(https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2088), and will work to close the discrepancy between helm&yamls
