### ISSUE TITLE
Are alb.ingress.kubernetes.io/ annotations whitespace agnostic?

### ISSUE THREAD

**Issue by trallnag** [kubernetes-sigs/aws-load-balancer-controller#2084]
Let's say I want to enable access logging to S3. Can I do the following?

```yaml
alb.ingress.kubernetes.io/load-balancer-attributes: >-
  access_logs.s3.enabled=true,
  access_logs.s3.bucket=mybucket,
  access_logs.s3.prefix=myenv
```

This gets rendered as a string with whitespaces:

``` 
access_logs.s3.enabled=true, access_logs.s3.bucket=mybucket, access_logs.s3.prefix=myenv
```

Does this work or are white spaces forbidden?

**Comment by M00nF1sh** [comment]
@trallnag Yes, This will work, white spaces is permitted around `,` but not permitted around `=`
