### ISSUE TITLE
Ingress Controller causing whole data plane to go down

### ISSUE THREAD

**Issue by Deepak1100** [kubernetes-sigs/aws-load-balancer-controller#2085]
So we had some issues with Node Authorizer and which caused all nodes to go into the NotReady state. and at that time alb-ingress-controller deregister all the pods from all the alb.
Which cause all service to give 503.
I don't think this is the right way. As it is taking the whole data plane down while all containers and nodes were fine.
Or at Atleast we should follow some kind of policy like PDB which can determine that at least that many pods should always be in LB.

**Comment by M00nF1sh** [comment]
@Deepak1100 
Do you have a good strategy to differentiate the case of node accidentally moved to NotReady state or nodes moved to NotReady on purpose manually?
also, node might entering NotReady one by one (if it's due to failed healthcheck)

**Comment by kishorj** [comment]
@Deepak1100, this is the designed behavior for the instance targets. I'm closing the issue. If you have a suggestion for new new strategy feel free to create a feature request.
