### ISSUE TITLE
Building.md is giving 404

### ISSUE THREAD

**Issue by Deepak1100** [kubernetes-sigs/aws-load-balancer-controller#2086]
its giving 404 https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/BUILDING.md

I wanted to build and test for [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2085) but there are no contribution docs.

**Comment by M00nF1sh** [comment]
@Deepak1100 
Thanks for your interest in contributing :D. We'll fix the `BUILDING.md` shortly.
For now you can checkout the main branch of this repo and execute
```
IMG=repo/name:v2.2.0-dev make docker-push
```
above command will build the image as `repo/name:v2.2.0-dev` and push to the repository(you need to setup your ECR/dockerHub credentials before run above command)

**Comment by fawadkhaliq** [comment]
@Deepak1100 added the devel docs here https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2101
