### ISSUE TITLE
Documentation links to old alb-ingress-controller

### ISSUE THREAD

**Issue by rothgar** [kubernetes-sigs/aws-load-balancer-controller#2091]
**Describe the bug**
Some links are still linking back to alb-ingress-controller pages which no longer exist. An example is the controller docs on this page https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/

It should be updated to https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/controller/setup/

**Comment by M00nF1sh** [comment]
thanks for reporting this. we'll fix the readme shortly

**Comment by M00nF1sh** [comment]
closing this as the docs have been updated :D
