### ISSUE TITLE
[Documentation] svc account creation

### ISSUE THREAD

**Issue by wild-endeavor** [kubernetes-sigs/aws-load-balancer-controller#2093]
On https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/

The last step 3. where it begins "Install the helm chart if using IAM roles..." shouldn't the note read `serviceAccount.create=true` instead of `serviceAccount.create=false`?

**Comment by kishorj** [comment]
@wild-endeavor, in this case,  the serviceaccount is created before helm install, `eksctl create iamserviceaccount ...`. So the `serviceAccount.create=false` is correct.

**Comment by wild-endeavor** [comment]
Oooh got it thanks, I missed that step.
