### ISSUE TITLE
Specify a source of ip address when provisioning load balancer controller

### ISSUE THREAD

**Issue by MaorPaz** [kubernetes-sigs/aws-load-balancer-controller#2095]
The main goal:

When provisioning a aws eks cluster, and installing the aws-load-balancer-controller, i would like to specify the source of accepted ip addresses within the security group of the auto generated security group

**Comment by kishorj** [comment]
@MaorPaz, you can specify a list of CIDRs that can access the load balancer. Please refer to the following documentation - 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#inbound-cidrs

**Comment by MaorPaz** [comment]
@kishorj Hi, thank you for the reply, I am talking about the aws eks load balancer controller himself, 
When deploying it via it's YAML file, 
Not on the ingress, 
By default, when deploying it, it's automatically assigned to a nodes and assigning to  theme a SG so the source of it becomes the load balancer, 
The security group of the load balancer, 
By default open to the world,
I would like to restrict it to one address

**Comment by kishorj** [comment]
@MaorPaz, what is the controller version you are using? The controller doesn't create security groups during controller startup.

**Comment by MaorPaz** [comment]
@kishorj He is creating SG and attaching theme to the instances,
The SG of the load-balancer is open to the world

This is the version: 
gitthub.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master

Implement it via helm,

This is the guide:
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html

**Comment by M00nF1sh** [comment]
@MaorPaz 
The controller creates a SG per Ingress(ALB) by default. And it's open to public if the ALB is public-facing.
And that SG's inbound permission can be adjusted via https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#inbound-cidrs on Ingresses.

Apart from above SG, there is no other created SG by this controller/helm chart.

**Comment by M00nF1sh** [comment]
@MaorPaz 
do above answers your questions?
If not, feel free to create a new issue 😄
