### ISSUE TITLE
ingressClass vs Annotations kubernetes.io/ingress.class

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/aws-load-balancer-controller#2097]
**Describe the bug**
Right now you cannot deploy a resource with ingressClass set to alb and annotation kubernetes.io/ingress.class set to alb at the same time.

Other ingress controllers like treafik do not complain here.

**Steps to reproduce**
deploy a resource with ingressClass set to alb and annotation kubernetes.io/ingress.class set to alb at the same time

**Expected outcome**
Just print a warning that annotation kubernetes.io/ingress.class is deprecated.

**Environment**

* AWS Load Balancer controller version: 2.2
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version?: 1.19

**Additional Context**:

**Comment by M00nF1sh** [comment]
@runningman84 
The validation is enforced by Kubernetes instead of our controller: https://github.com/kubernetes/kubernetes/blob/v1.19.0/pkg/apis/networking/validation/validation.go#L228

I don't think treafik will work with this case as well on 1.19 😃

**Comment by runningman84** [comment]
ok yes I have also seen errors in our traefik deployment now....
