### ISSUE TITLE
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+

### ISSUE THREAD

**Issue by logicminds** [kubernetes-sigs/aws-load-balancer-controller#2100]
**Describe the bug**
A deprecation notice is displayed when creating the 2048 game

`Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

**Steps to reproduce**
https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/

**Expected outcome**
No errors, The Dns of the game

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version? YES, 1.19?

**Additional Context**:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.9/docs/examples/2048/2048-namespace.yaml
namespace/2048-game created
(base) ➜  ~ git:(master) kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.9/docs/examples/2048/2048-deployment.yaml
deployment.apps/2048-deployment created
(base) ➜  ~ git:(master) kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.9/docs/examples/2048/2048-service.yaml
service/service-2048 created
(base) ➜  ~ git:(master) kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.9/docs/examples/2048/2048-ingress.yaml
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.extensions/2048-ingress created
(base) ➜  ~ git:(master) kubectl get ingress/2048-ingress -n 2048-game
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME           CLASS    HOSTS   ADDRESS   PORTS   AGE
2048-ingress   <none>   *                 80      30s
```

**Comment by fawadkhaliq** [comment]
@logicminds thanks for reporting this. This is a work in progress. The new CRDs will be available soon/before 1.22

**Comment by logicminds** [comment]
I did find other minor issues in that article.  Should I make separate issues?

**Comment by fawadkhaliq** [comment]
@logicminds that'd be great, thanks!

**Comment by kishorj** [comment]
There is already a feature request #2050, and support for `networking.k8s.io/v1` is in our roadmap. I'm closing this issue as a duplicate.
