### ISSUE TITLE
egrep is incorrect in blog article

### ISSUE THREAD

**Issue by logicminds** [kubernetes-sigs/aws-load-balancer-controller#2102]
**Describe the bug**
A bad egrep fails the command

**Steps to reproduce**
kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o alb-ingress[a-zA-Z0-9-]+)

Follow https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/
**Expected outcome**
The ingress controller instance is returned

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:
The command `kubectl get po -n kube-system | egrep -o "alb-ingress[a-zA-Z0-9-]+" | cut -f 1 -d\ ` seems to fix the issue

The full command ` kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -e "alb-ingress[a-zA-Z0-9-]+" | cut -f 1 -d\ )`

Although there is probably a better way to just capture the instance name instead of cutting the field out

**Comment by kishorj** [comment]
@logicminds, with the `egrep -o`, the additional cut isn't required. 
- What is the version of your `egrep` command? Does it support the `-o` option?
- What output do you get from the egrep command before passing to cut?

**Comment by logicminds** [comment]
Adding quotes around the egrep pattern seems  to fix the issue.

## Incorrect way
```
kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o alb-ingress[a-zA-Z0-9-]+)
zsh: no matches found: alb-ingress[a-zA-Z0-9-]+
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples
```

## Correct way
`kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o "alb-ingress[a-zA-Z0-9-]+")`command

## Egrep version
I am using OS X so I think egrep is compiled differently than the linux version.  There is no -o option but it still seems  to work.

```
usage: egrep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

egrep --version
egrep (BSD grep) 2.5.1-FreeBSD
```

**Comment by kishorj** [comment]
The quotes requirement is due to zsh. It works without the quotes on bash.

egrep on OS X does support the -o option, I have the same version of egrep as well. Here is the section from the man page - 

```
     -o, --only-matching
             Prints only the matching part of the lines.
```
