### ISSUE TITLE
cannot create policy outlined in blog article

### ISSUE THREAD

**Issue by logicminds** [kubernetes-sigs/aws-load-balancer-controller#2103]
**Describe the bug**
For some reason creating the policy from the CLI fails with a syntax error.

**Steps to reproduce**
https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/

```
aws iam create-policy \
    --policy-name ALBIngressControllerIAMPolicy \
    --policy-document https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/iam-policy.js
```

**Expected outcome**
A policy would be created

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

I was able to work around this issue by manually downloading the policy json file and creating the same policy through the AWS Iam web interface.

**Comment by kishorj** [comment]
@logicminds what error do you get? 
The URL you've specified in the description is truncated. The file extension should have been `.json`. Also, if the policy already exists, you'd get EntityAlreadyExists from the AWS.

**Comment by logicminds** [comment]
```
 aws iam create-policy \
    --policy-name ALBIngressControllerIAMPolicy \
    --policy-document https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/iam-policy.json

An error occurred (MalformedPolicyDocument) when calling the CreatePolicy operation: Syntax errors in policy.
```

**Comment by kishorj** [comment]
@logicminds, looks like you are using aws cli v2 which doesn't support http:// or https:// urls for parameters. For details, please refer to the breaking changes outlined in https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-paramfile

The workaround is to download the file locally, and pass the `--policy-document file://iam-policy.json` argument instead.

**Comment by kishorj** [comment]
@logicminds, I'm closing the issue. Feel free to reopen or file a new one if you have further concerns.

**Comment by andrewmclagan** [comment]
perhaps update the blog...?
