### ISSUE TITLE
auth-scope not updating

### ISSUE THREAD

**Issue by rmgpinto** [kubernetes-sigs/aws-load-balancer-controller#2112]
**Describe the bug**
Changing from `alb.ingress.kubernetes.io/auth-scope: "email openid"` to `alb.ingress.kubernetes.io/auth-scope: "openid"` doesn't remove the scope from the `x-amzn-oidc-data` header.

**Steps to reproduce**
Create an ingress with `alb.ingress.kubernetes.io/auth-scope: "email openid"` then change to `alb.ingress.kubernetes.io/auth-scope: "openid"` 

**Expected outcome**
The scope should be removed from the HTTP header.

**Environment**

* AWS Load Balancer controller version 2.2
* Kubernetes version 1.20
* Using EKS (yes/no), if so version? no

**Comment by M00nF1sh** [comment]
@rmgpinto 
Sorry for late reply.
We did validated that the controller correctly updated the auth-scope on ALB side.

Would you help check AWS console to see whether it's updated?
