### ISSUE TITLE
New Ingress does not get picked up from aws-load-balancer-controller

### ISSUE THREAD

**Issue by jchoi926** [kubernetes-sigs/aws-load-balancer-controller#2113]
**Describe the bug**
I have two existing ingresses each in their respective namespace. The aws-load-balancer-controller picked up both ingresses and provisioned all AWS alb's, target groups, etc as expected. 
I created an additional ingress in a namespace with an existing ingress mentioned above. The aws-load-balancer-controller does not process the new ingress and as a result no AWS resources are provisioned.

**Steps to reproduce**
Install aws-load-balancer-controller mentioned here(https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html)
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ci-ingress
  namespace: ci-team-b
  labels:
    app: ci-team-b
    environment: development
    tag: team-b-4.12.141-xxx
    pod: ingress
  annotations:
    kubernetes.io/ingress.class: ingress-alb
    alb.ingress.kubernetes.io/group.name: development
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: environment=dev
    alb.ingress.kubernetes.io/subnets: subnet-xxx,subnet-xxx,subnet-xxx
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/target-node-labels: nodegroup-type=dev
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true,routing.http.drop_invalid_header_fields.enabled=true,access_logs.s3.enabled=true,access_logs.s3.bucket=cirrus-west-alb-access,access_logs.s3.prefix=team-b/ci
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:xxx:certificate/xxx"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/ping.php"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
          path: /*
        - backend:
            serviceName: nginx-svc
            servicePort: 80
          path: /*`

All ingresses are very similar in structure.

**Expected outcome**
New ingress to be processed by the aws-load-balancer-controller and AWS resources provisioned.

**Environment**

* AWS Load Balancer controller version - v2.2.0
* Kubernetes version - 
* Using EKS (yes/no), if so version? - yes, v1.17

**Additional Context**:

**Comment by kishorj** [comment]
@jchoi926, the ingress class annotation is set to `ingress-alb`
```
 kubernetes.io/ingress.class: ingress-alb
```
Could you confirm if the LB controller is setup to correctly recognize `ingress-alb` class? This is the value of the `--ingress-class` controller flag and by default it is `alb`.

Also check if you have the `disable-ingress-class-annotation` flag set to true.

**Comment by jchoi926** [comment]
That was it, thanks for the eyes @kishorj!
