### ISSUE TITLE
Issue in iam-policy.json

### ISSUE THREAD

**Issue by DebojyotiGhosal** [kubernetes-sigs/aws-load-balancer-controller#2115]
In the post the iam-policy.json document giving error malformed policy. 

Policy Document: https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/iam-policy.json

**Comment by kishorj** [comment]
@DebojyotiGhosal what error do you get? 
Could you also provide further details on the following?
- controller version you are trying to deploy
- aws cli version. Note: If you use aws cli v2, it does not support http:// or https:// urls for parameter. You will have to download the file locally and pass the --policy-document file://iam-policy.json argument

**Comment by M00nF1sh** [comment]
@DebojyotiGhosal 
Did kishor's response provided the answer to you?

closing this, feel free to open a new issue if you have further concerns
