### ISSUE TITLE
"cannot resolve pod ENI for pods" error on migration from v1.1.8 to v2.2

### ISSUE THREAD

**Issue by anetanel** [kubernetes-sigs/aws-load-balancer-controller#2116]
I'm testing the migration process on a test cluster.
While on version 1.1.8 I was able to create an ALB with "target-type" ip, and had traffic flowing to the pods IPs without issues.
Once I upgraded to the new version, I started getting "cannot resolve pod ENI for pods" errors in the "aws-load-balancer-controller" pod.
Cluster Version is 1.16.9
As far as I understand, we are using "kubenet" plugin. Is "amazon-vpc-cni-k8s" mandatory now when using target-type: ip?
I'm attaching the pod debug log after restarting it, redacted from some dns address and private info :)

`{"level":"info","ts":1625578009.448428,"msg":"version","GitVersion":"v2.2.0","GitCommit":"68c417a7ea37ff153f053d9ffef1cc5c70d7e211","BuildDate":"2021-05-14T21:49:05+0000"}
{"level":"info","ts":1625578012.6509175,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1625578012.653971,"logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":1625578012.6540709,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1625578012.6541085,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1625578012.6541305,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1625578012.6541548,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1beta1-ingress"}
{"level":"info","ts":1625578012.6543317,"logger":"setup","msg":"starting podInfo repo"}
{"level":"info","ts":1625578014.6547494,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0706 13:26:54.654602       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/aws-load-balancer-controller-leader...
{"level":"info","ts":1625578014.755159,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1625578014.7557101,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1625578014.755842,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1625578014.7559412,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
I0706 13:27:11.513389       1 leaderelection.go:252] successfully acquired lease kube-system/aws-load-balancer-controller-leader
{"level":"debug","ts":1625578031.5135162,"logger":"controller-runtime.manager.events","msg":"Normal","object":{"kind":"ConfigMap","namespace":"kube-system","name":"aws-load-balancer-controller-leader","uid":"1ed9df03-62d4-4249-b257-b5ec9cfb8ee8","apiVersion":"v1","resourceVersion":"4681085"},"reason":"LeaderElection","message":"aws-load-balancer-controller-84fdbd5448-npr5f_4d198ade-300b-4bcd-9ba5-81fdbd486a86 became leader"}
{"level":"info","ts":1625578031.5136158,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.5136843,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.5137296,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.513929,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc000100370"}
{"level":"info","ts":1625578031.5139778,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc000100410"}
{"level":"info","ts":1625578031.5140142,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.5140467,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.5141094,"logger":"controller","msg":"Starting EventSource","controller":"ingress","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.5141773,"logger":"controller","msg":"Starting EventSource","controller":"service","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.514246,"logger":"controller","msg":"Starting Controller","controller":"service"}
{"level":"debug","ts":1625578031.5142436,"logger":"controllers.ingress.eventHandlers.ingress","msg":"enqueue ingressGroup for ingress event","ingress":"dev/verification-nginx-alb-ingress","ingressGroup":"dev/verification-nginx-alb-ingress"}
{"level":"debug","ts":1625578031.5143487,"logger":"controllers.ingress.eventHandlers.service","msg":"enqueue ingress for service event","service":{"namespace":"dev","name":"verification-nginx-svc"},"ingress":{"namespace":"dev","name":"verification-nginx-ingress"}}
{"level":"debug","ts":1625578031.5146735,"logger":"controllers.ingress.eventHandlers.service","msg":"enqueue ingress for service event","service":{"namespace":"dev","name":"verification-nginx-alb-svc"},"ingress":{"namespace":"dev","name":"verification-nginx-alb-ingress"}}
{"level":"debug","ts":1625578031.5147026,"logger":"controllers.ingress.eventHandlers.ingress","msg":"enqueue ingressGroup for ingress event","ingress":"dev/verification-nginx-alb-ingress","ingressGroup":"dev/verification-nginx-alb-ingress"}
{"level":"info","ts":1625578031.6142175,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1625578031.6145015,"logger":"controller","msg":"Starting Controller","controller":"ingress"}
{"level":"debug","ts":1625578031.6148717,"logger":"controllers.targetGroupBinding.eventHandlers.endpoints","msg":"enqueue targetGroupBinding for endpoints event","endpoints":{"namespace":"dev","name":"verification-nginx-alb-svc"},"targetGroupBinding":{"namespace":"dev","name":"k8s-dev-verifica-47a965a747"}}
{"level":"info","ts":1625578031.6150136,"logger":"controller","msg":"Starting workers","controller":"service","worker count":3}
{"level":"info","ts":1625578031.7147853,"logger":"controller","msg":"Starting workers","controller":"ingress","worker count":3}
{"level":"info","ts":1625578031.715485,"logger":"controller","msg":"Starting Controller","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding"}
{"level":"info","ts":1625578031.7156243,"logger":"controller","msg":"Starting workers","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","worker count":3}
{"level":"info","ts":1625578035.1972456,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"dev/verification-nginx-alb-ingress\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-dev-verifica-21704e3802\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"tags\":{\"App\":\"kubernetes\",\"Name\":\"nginx-alb-dev-alb\",\"Stack\":\"Dev\"},\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":443,\"toPort\":443,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]},{\"ipProtocol\":\"tcp\",\"fromPort\":443,\"toPort\":443,\"ipv6Ranges\":[{\"cidrIPv6\":\"::/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"443\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":443,\"protocol\":\"HTTPS\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}],\"certificates\":[{\"certificateARN\":\"arn:aws:iam::1234567:server-certificate/wildcard-nopenope-com-v9\"}],\"sslPolicy\":\"ELBSecurityPolicy-2016-08\",\"tags\":{\"App\":\"kubernetes\",\"Name\":\"nginx-alb-dev-alb\",\"Stack\":\"Dev\"}}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"443:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/443/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/dev/verification-nginx-alb-ingress-verification-nginx-alb-svc:80/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}],\"tags\":{\"App\":\"kubernetes\",\"Name\":\"nginx-alb-dev-alb\",\"Stack\":\"Dev\"}}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-dev-verifica-552aabb582\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"dualstack\",\"subnetMapping\":[{\"subnetID\":\"subnet-0e87f767\"},{\"subnetID\":\"subnet-4bfe4730\"},{\"subnetID\":\"subnet-8407c9c9\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}],\"loadBalancerAttributes\":[{\"key\":\"access_logs.s3.bucket\",\"value\":\"nopenope-logs-us-east-2\"},{\"key\":\"access_logs.s3.prefix\",\"value\":\"elb-traffic/dev/kube-nginx-alb-dev-oh-lbj.nopenope.com\"},{\"key\":\"deletion_protection.enabled\",\"value\":\"true\"},{\"key\":\"access_logs.s3.enabled\",\"value\":\"true\"},{\"key\":\"idle_timeout.timeout_seconds\",\"value\":\"60\"}],\"tags\":{\"App\":\"kubernetes\",\"Name\":\"nginx-alb-dev-alb\",\"Stack\":\"Dev\"}}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"dev/verification-nginx-alb-ingress-verification-nginx-alb-svc:80\":{\"spec\":{\"name\":\"k8s-dev-verifica-47a965a747\",\"targetType\":\"ip\",\"port\":80,\"protocol\":\"HTTP\",\"protocolVersion\":\"HTTP1\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":30,\"timeoutSeconds\":5,\"healthyThresholdCount\":5,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"30\"}],\"tags\":{\"App\":\"kubernetes\",\"Name\":\"nginx-alb-dev-alb\",\"Stack\":\"Dev\"}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"dev/verification-nginx-alb-ingress-verification-nginx-alb-svc:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-dev-verifica-47a965a747\",\"namespace\":\"dev\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/dev/verification-nginx-alb-ingress-verification-nginx-alb-svc:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"verification-nginx-alb-svc\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"}}}],\"ports\":[{\"protocol\":\"TCP\"}]}]}}}}}}}}"}
{"level":"error","ts":1625578035.2158282,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578035.2966735,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578035.372735,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"info","ts":1625578036.012844,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"dev/verification-nginx-alb-ingress"}
{"level":"debug","ts":1625578036.012936,"logger":"controller","msg":"Successfully Reconciled","controller":"ingress","name":"verification-nginx-alb-ingress","namespace":"dev"}
{"level":"debug","ts":1625578036.0131392,"logger":"controller-runtime.manager.events","msg":"Normal","object":{"kind":"Ingress","namespace":"dev","name":"verification-nginx-alb-ingress","uid":"d3d17834-b4c1-408a-a540-a192e37d6a04","apiVersion":"networking.k8s.io/v1beta1","resourceVersion":"4626189"},"reason":"SuccessfullyReconciled","message":"Successfully reconciled"}
{"level":"error","ts":1625578036.286149,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578036.3972342,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578036.5476003,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578037.3563988,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578037.7476687,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578038.4575317,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578039.7977567,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
{"level":"error","ts":1625578042.4328475,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-verifica-47a965a747","namespace":"dev","error":"cannot resolve pod ENI for pods: [dev/verification-nginx-deployment-65699c4d76-xtff2 dev/verification-nginx-deployment-86b4fdc986-hbb8k dev/verification-nginx-deployment-86b4fdc986-t6gb2]"}
`

**Comment by anetanel** [comment]
I found out that I had multiple subnets with appropriate annotations, and I think that the subnet discovery got confused.
Anyway, after removing old, unneeded subnets, those errors were gone, only to be replaced with a new kind of error:

> {"level":"info","ts":1625661491.2624648,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-east-2:000000000000:targetgroup/k8s-dev-testngin-f5eef3cff3/12ef6ae88df29a02","targets":[{"AvailabilityZone":null,"Id":"100.96.3.36","Port":80},{"AvailabilityZone":null,"Id":"100.96.3.37","Port":80}]}
{"level":"error","ts":1625661491.395464,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"k8s-dev-testngin-f5eef3cff3","namespace":"dev","error":"ValidationError: The Availability Zone for IP address '100.96.3.36' must be 'all' for Application Load Balancer target groups, when not within the VPC\n\tstatus code: 400, request id: 324c40cd-f199-4a3f-9297-ac3454724e05"}

**Comment by anetanel** [comment]
Using this image: "shoekstra/aws-alb-ingress-controller:latest-patch" instead of the official one, as suggested here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1862, seems to solve my issue.
Hopefully it will be merged soon, as we are somewhat reluctant to use a private build in production.

**Comment by M00nF1sh** [comment]
@anetanel 
Yes, the `amazon-vpc-cni-k8s` currently is mandatory for V2 when using targetType: IP. 

We'll evaluate #1862 . Note, with 1862, you'll need to manage the worker node SGs yourself, as the controller won't check which instance supports the pod IP.

**Comment by anetanel** [comment]
@M00nF1sh thanks. I think this needs to be mentioned in the migration docs.
Luckily we are already managing the SG via CloudFormation, so that wont be a problem.
One last question, why was the solution that worked in v1 (setting the Target `AvailabilityZone` to `All`) removed in v2?

**Comment by M00nF1sh** [comment]
@anetanel 
The support for other VPC CNI plugin is not considered during we plan for v2. since we cannot support the securityGroup management if the CNI plugin is not been used.

There is a open PR to add that back: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1862
which we plan to merge and release. But the caveat is this can be used only when the worker SG rules is managed by users.
