### ISSUE TITLE
SecurityGroups are not deleted after deleting an Ingress

### ISSUE THREAD

**Issue by setevoy2** [kubernetes-sigs/aws-load-balancer-controller#2117]
**Describe the bug**

We've updated the Controller from 1.14 to 2.2.1 and are faced with an issue when after creating and deleting an Ingress and an AWS LoadBalancer - its Namespace hangs in the Terminating state.
The Controller's logs reports:

> {"level":"info","ts":1625580538.1154413,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-093334fe379aeff03"}
> {"level":"error","ts":1625580371.9100788,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"test-ingress","namespace":"test-namespace","error":"failed to delete securityGroup: timed out waiting for the condition"}

The "_sg-093334fe379aeff03_" has references from WorkerNodes SGs, but they all have the "_elbv2.k8s.aws/targetGroupBinding=shared_" in the Description field, as it's mentioned in [the migration docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.0/guide/upgrade/migrate_v1_v2/).

Removing the `finalizers` from an Ingress as noted in comments in [the similar issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1629) will indeed delete its Ingress API object, but it leaves the SecurityGroup and its references from WorkerNodes.

A CloudTrail event expectedly says "_resource sg-093334fe379aeff03 has a dependent object_"

**Steps to reproduce**

1. create an Ingress
2. delete it
3. its ALB was deleted (!), but its Namespace is still present in the Terminating state

**Expected outcome**

All related AWS resources must be deleted.

**Environment**

* AWS Load Balancer controller version: 2.2.1
* Kubernetes version: AWS EKS 1.18
* Using EKS (yes/no), if so version? AWS EKS 1.18

**Comment by setevoy2** [comment]
Found a weird thing while watching CloudTrail logs.

So, we have a Test cluster, we have an old, Dev, cluster.
The issue happens on the Dev, and everything is working on the Test.

During an Ingress deletion - I can see the "`RevokeSecurityGroupIngress`" requests happened on the Test env to update WorkerNodew SG to drop the rule, but no such requests are made on the Dev cluster.

**Comment by M00nF1sh** [comment]
@setevoy2 
When migrate from v1 to v2, you'll need to follow the migration guide: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/upgrade/migrate_v1_v2

The above issue could happen if you didn't finish the steps of `If security-groups annotation isn't used, the SecurityGroup rule on worker node's SecurityGroup that allow LoadBalancer traffic should be manually adjusted post migration.`

**Comment by setevoy2** [comment]
Do you mean the "elbv2.k8s.aws/targetGroupBinding=shared", @M00nF1sh?
I've added a note about this in the first message:

> but they all have the "elbv2.k8s.aws/targetGroupBinding=shared" in the Description field, as it's mentioned in the migration docs.

**Comment by setevoy2** [comment]
So, let's try to reproduce the issue step-by-step.

1. create an Ingress, an associated ALB will be created:
```
$ kk -n test-namespace get ingress
NAME           CLASS    HOSTS   ADDRESS                                                                  PORTS   AGE
test-ingress   <none>   *       k8s-testname-testingr-***.us-east-2.elb.amazonaws.com   80      51s
```
2. WorkerNodes SecurityGroups are updated, and this reflected in EKS logs
![Screenshot_20210708_124943](https://user-images.githubusercontent.com/7965314/124901783-fe7edb80-dfea-11eb-9851-2f84838f34ad.png)
![Screenshot_20210708_124834](https://user-images.githubusercontent.com/7965314/124901686-e5762a80-dfea-11eb-9318-aedbb6b77785.png)
3. delete the Ingress: all Kubernetes resources are deleted excluding corresponded Namespace:
```
$ kk delete -f test-deployment.yaml 
namespace "test-namespace" deleted
deployment.apps "test-deployment" deleted
service "test-svc" deleted
ingress.extensions "test-ingress" deleted
```
And:
```
$ kk get ns test-namespace
NAME             STATUS        AGE
test-namespace   Terminating   9m56s
```
Also, no `RevokeSecurityGroupIngress` call has been made:
![Screenshot_20210708_125240](https://user-images.githubusercontent.com/7965314/124902306-79e08d00-dfeb-11eb-91e7-f4621a26d6bd.png)

CloudTrail reports only about my own calls when I cleaned SGs:
![Screenshot_20210708_125404](https://user-images.githubusercontent.com/7965314/124902477-a399b400-dfeb-11eb-9f83-70469ea759b1.png)

4. The Controller will try to remove it with the "_failed to delete securityGroup: timed out waiting for the condition_" error:
![Screenshot_20210708_125741](https://user-images.githubusercontent.com/7965314/124903058-3d616100-dfec-11eb-9b6c-f2bb6a7581d7.png)

And CloudTrail reports on the `Client.DependencyViolation` error for the calls:
![Screenshot_20210708_125943](https://user-images.githubusercontent.com/7965314/124903317-86b1b080-dfec-11eb-86ab-12eb9d70036d.png)

Any ideas? As I'm really stuck in there...

**Comment by M00nF1sh** [comment]
@setevoy2
Is there other error logs from the controller? 

Another possible cause is there is some error in other targetGroupBinding's reconciles.

The current logic is the controller keep tracks the networking requirement from all targetGroupBindings, and only delete a worker SG rules if it have captured the networking requirement from all targetGroupBinding at least once since its startup.

e.g. if a `TGB-x` is failed to reconcile at least once since the controller startup due to different reasons, the controller will not be able to GC any worker SG rules since it don't know whether that rule will be needed for TGB-x or not, and that could cause the issue.

We have done a partial fix for this issue in https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1888. You can find more details there.
For your case, it might be similar cases, and we can figure it out from the controller logs and fix accordingly.

**Comment by setevoy2** [comment]
@M00nF1sh Sure, there are logs from the Controller, just not sure what exactly I need to check there as there is a lot of information. Any suggestions? 

Regarding broken TargetGroupBinding - any way to check them?

And the fix for the issue in [#1888](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1888) was merged, so I guess it's added to the latest 2.2.1?

Anyway - many thanks for stepping in.
Meanwhile, will try to take a closer look at the Controller logs. Maybe, will see something about TargetGroupBindings.

**Comment by setevoy2** [comment]
@M00nF1sh Many thanks!
So, the point was the "broken TGBs's(TargetGroupBinding)".
I've found, that we had an old Ingress with incorrect Service configuration ("Service type must be nodePort or LoadBalancer" and so on).
After deleting this Ingress - everything works as expected (so far... :-) )

**Comment by setevoy2** [comment]
@M00nF1sh And now we've got the situation when no ALB are crated, no deleted. No revoke, delete, etc calls are made at all.
Nothing was changed on the ALB Controller side.
I think we'll have to roll back to the 1.14.

**Comment by setevoy2** [comment]
Found this in a Namespace events:

```
 0s    Warning   FailedBuildModel   Ingress   Failed build model due to couldn't auto-discover subnets: WebIdentityErr: failed to retrieve credentials
caused by: ExpiredTokenException: Token expired: current date/time 1627631226 must be before the expiration date/time1626886384
      status code: 400, request id: 90b95c70-fc7c-4974-ab0d-01c08bb18e58
```

**Comment by setevoy2** [comment]
Okay, closing it :-)
The issue was with the IAM ServiceAccount used for the Controller. 
Re-created it, and now it is working.
