### ISSUE TITLE
Running Controller in restricted environment without security group IAM permissions

### ISSUE THREAD

**Issue by ryphon** [kubernetes-sigs/aws-load-balancer-controller#2126]
**Is your feature request related to a problem?**
Currently, I'm in an environment where I cannot control the security groups. They're controlled from a higher level admin. In that, I'm unable to give the Load Balancer Controller access to the "AuthorizeSecurityGroupIngress" permission. 

**Describe the solution you'd like**
Is there a way I can just bypass that, and let it just assume the Security group is handled externally and that the ports are indeed open?

**Describe alternatives you've considered**
I've read through most of the documentation. At this point it seems like having some terraform or something next to my chart to control the load balancers is probably the only documented option.

**Comment by M00nF1sh** [comment]
@ryphon 
For ALB/Ingress, you can use [alb.ingress.kubernetes.io/security-groups](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#security-groups) annotation to specify the SecurityGroup on ALBs, and once it's specified, the controller won't touch the securityGroup on worker nodes, so no "AuthorizeSecurityGroupIngress" is needed.

For NLB/Service, we currently don't have a way to disable the worker node securityGroup rule management, worker is underway to support it.

**Comment by ryphon** [comment]
@M00nF1sh Ah perfect. Is that tracked in an issue or PR somewhere I can track? Would really like to keep an eye on that.

**Comment by M00nF1sh** [comment]
@ryphon you can track https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2118

**Comment by ryphon** [comment]
@M00nF1sh thank you. closing this issue!
