### ISSUE TITLE
Node group security group not updated with no access to instance metadata

### ISSUE THREAD

**Issue by v1ctorrhs** [kubernetes-sigs/aws-load-balancer-controller#2127]
**Describe the bug**

We have a scenario where the IMDS (instance metadata service) is not reachable from the pods (intentionally). `cluster-name`, `vpc`, `region`, and `ingress-class` are passed to the deployment and the deployment starts correctly.

An ingress and a service are created, so the ALB creates all the needed components - ALB, target groups, creates a dedicated _managed_ security group for the ALB itself with the listen ports, however it does not add a security group rule allowing traffic from the ALB to the node group security group. The Node group is tagged with `kubernetes.io/cluster/<cluster-name> : owned`. In other clusters where the instance metadata is enabled that works.

The IRSA role is attached and i've confirmed the pod has access to describe and to authorize rules in the security group.

Looking at [this](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html) documentation, I understand there should be just 1 security group with such a tag  so i get the impression that the alb controller should be able to filter and pick the correct one instead of taking it from the instance metadata.

**Steps to reproduce**

EKS 1.19, Node group with a launch template that specifies 

```
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }
```
ALB controller, version v2.1.3, helm chart v1.2.0

**Expected outcome**

ALB controller creates the ALB, target group, security group, and authorizes a new rule that allows `0-65535` port from the security group attached to the ALB in the node group security group rule.

**Environment**

AWS-EKS, us-east-1 region

* AWS Load Balancer controller version
v2.1.3

* Kubernetes version
1.19

* Using EKS (yes/no), if so version?
yes, 1.19

**Additional Context**:

**Comment by M00nF1sh** [comment]
@v1ctorrhs 
Is there any error messages from the controller? the code path that finds the nodeSG and authorize rules don't have dependency on IMDS.

I guess the role assigned via IRSA might missing some permissions and caused this

**Comment by v1ctorrhs** [comment]
Thank you for the quick response @M00nF1sh!

We don't see any errors in the logs.

The IRSA role (and policies) are automated, we use them in multiple other clusters and dont see any issues with them.
Anyway, [this](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.0/docs/install/iam_policy.json) is the policy we attach to the role.

Just to confirm it's not a permission issue I created a new pod using the following image, attached the same IRSA role, passed the following args and it authorizes a new rule successfully .

```
    spec:
      containers:
      - image: amazon/aws-cli:latest
        args:
          - ec2
          - authorize-security-group-ingress
          - --group-id
          - sg-<xxxxxxx>
          - --protocol
          - tcp
          - --port
          - '5555'
          - --cidr
          - 0.0.0.0/0
```

**Comment by v1ctorrhs** [comment]
my bad here, it seems like the ALB controller waits for the pods to start before authorizing the security group rules.
