### ISSUE TITLE
Fargate pod IPs in different VPC than Ingress do not get added to target group

### ISSUE THREAD

**Issue by gleyfer** [kubernetes-sigs/aws-load-balancer-controller#2135]
**Describe the bug**

I have deployed the load balancer controller with the --aws-vpc-id option and specified a different VPC than where the cluster is deployed.  A Fargate profile is used for the pod deployment, and when creating an ingress service with an ALB, the targets are not being populated in the target group for the alb.

**Steps to reproduce**
1. Deploy the aws load balancer controller using --aws-vpc-id option and specify different VPC from the cluster
2. Deploy an app/service using fargate profile
3. Deploy an ingress alb

**Expected outcome**

Expect ALB target groups to be populated with fargate IPs. Currently nothing is added/populated.

**Environment**

* AWS Load Balancer controller version: 2.2.1
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? eks.2

**Additional Context**:

Deployed alb controller via helm specifying vpc id:

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
  --set clusterName=dev-cluster \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  --set region=us-west-2 \
  --set vpcId=<centralized ingress vpc id here> \
  -n kube-system

controller deployed fine:

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
aws-load-balancer-controller   2/2     2            2           17m

Pods for the application are running:

NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE
default       dev-app-6b887bf459-kkn9k                       1/1     Running   0          15m
default       dev-app-6b887bf459-qh6dw                       1/1     Running   0          15m
kube-system   aws-load-balancer-controller-5bfdc49cb-knmng   1/1     Running   0          18m
kube-system   aws-load-balancer-controller-5bfdc49cb-tljdw   1/1     Running   0          18m
kube-system   coredns-867ff8777b-j2kfz                       1/1     Running   0          26h
kube-system   coredns-867ff8777b-jx746                       1/1     Running   0          26h

ingress definition:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-service
            port:
              number: 80

relevant ingress yaml:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/target-type":"ip","kubernetes.io/ingress.class":"alb"},"name":"dev-ingress","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"service":{"name":"dev-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    kubernetes.io/ingress.class: alb
  creationTimestamp: "2021-07-22T18:49:21Z"

ALB is created in AWS, target group is created, rule is created pointing to target group. However, target group itself is not populated with nodes.

If I create deploy the controller in the same VPC as the cluster and deploy the same ingress, it works and target is populated.

**Comment by M00nF1sh** [comment]
@gleyfer 
This will be supported by https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1862

We'll include it in future releases

**Comment by kishorj** [comment]
Closing this issue in lieu of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1569
