### ISSUE TITLE
Acquire Region from Env

### ISSUE THREAD

**Issue by nairb774** [kubernetes-sigs/aws-load-balancer-controller#2139]
**Is your feature request related to a problem?**

I'm trying to reduce the IMDS hop limit from 2 to 1, and this resulted in the aws-load-balancer-controller erroring out with `failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: EC2MetadataError: failed to make EC2Metadata request\n\tstatus code: 401, request id: \ncaused by:`. There are other ways to determine the region which don't require manual configuration.

**Describe the solution you'd like**
A description of what you want to happen.

It would seem that the controller should try picking this information up from the environment. The `AWS_REGION` env var is automatically set by the [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) tooling, and this would be a natural replacement for using the IMDS endpoints.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

I could set the flag, but it seems redundant when the controller already needs a role for manipulating various AWS objects, and thus the AWS_REGION env var is being set correctly.

**Comment by M00nF1sh** [comment]
/kind good-first-issue
/kind feature
@nairb774 I think this is a good feature request to add. BTW, after we implemented above, you'll still need the `--aws-vpc-id` to specify the vpc ID.

**Comment by Shreya027** [comment]
The issue  has been addressed in #2217, so closing the issue
