### ISSUE TITLE
Instance Target UDP NLB doesn't get traffic

### ISSUE THREAD

**Issue by jplouis** [kubernetes-sigs/aws-load-balancer-controller#2144]
**Describe the bug**

Trying to set up LoadBalancer service using UDP ports. When we set `externalTrafficPolicy:  local` health checks pass and it works. Would like to find a solution where we don't have to run `externalTrafficPolicy` set to local.  We can't currently use NLB-IP mode.

**Environment**
KOPs based K8s

* AWS Load Balancer controller version
2.2

* Kubernetes version
1.20

* Using EKS (yes/no), if so version?
no

**Additional Context**:

**Comment by kishorj** [comment]
The UDP target groups still require TCP/HTTP/HTTPS based health check. If you specify `externalTrafficPolicy: local`, then k8s configures a health check node port with HTTP protocol, which satisfies the target group requirement. When do not have the `externalTrafficPolicy: local` configuration. With IP targets, it is easier to setup a sidecar with TCP based health check for UDP protocol, but it might not be straightforward with instance targets. If you ware able to set up TCP port per instance for health check, you can specify via the custom port via the service annotation `service.beta.kubernetes.io/aws-load-balancer-healthcheck-port`.

For UDP protocol, NLB operates in  fail-open mode. If all of the targets fail health check, LB will forward traffic to the targets.

**Comment by jplouis** [comment]
I've gotten It to work when using IP targets in a test cluster, but unfortunately can't use IP targets in production cluster. I'm not sure how the `service.beta.kubernetes.io/aws-load-balancer-healthcheck-port`would work with instance targets. Seems like the health check port would have to be exposed on the service. Mixing UDP and TCP on the NLB service doesn't seem to be supported.
