### ISSUE TITLE
aws-alb-ingress-controller:v2.2.0   authorization failure message

### ISSUE THREAD

**Issue by DevOpserzhao** [kubernetes-sigs/aws-load-balancer-controller#2152]
**Describe the bug**

You are not authorized to perform this operation. Encoded authorization failure message

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**
cn-northwest-1

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?
 image: amazon/aws-alb-ingress-controller:v2.2.0

1.20

 eksctl version
0.40.0

**Additional Context**:

use  image: amazon/aws-alb-ingress-controller:v2.1.2  no problem

**Comment by kishorj** [comment]
@DevOpserzhao, v2.2.0 release requires new IAM permissions. Please refer to the [v2.2.0 release notes](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0) for further details.

**Comment by kishorj** [comment]
@DevOpserzhao, closing this issue. If you still encounter errors after applying the new IAM permissions, feel free to reopen or create a new issue.
