### ISSUE TITLE
externalManagedTags not working with TargetGroupBindings

### ISSUE THREAD

**Issue by willbennett-kaltura** [kubernetes-sigs/aws-load-balancer-controller#2154]
Trying to implement the functionality from https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1970

We've created an EC2 instance with the tag key "tgbhandsoff" with value "true" and another without it, and then added the following to our deployment.yaml:

        - name: aws-load-balancer-controller
          image: >-
            602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.2.1
          command:
            - /controller
          args:
            - '--cluster-name=example'
            - '--ingress-class=alb'
            - '--log-level=debug'
            - '--external-managed-tags=tgbhandsoff'

We've also tried wrapping "tgbhandsoff" in quotes, as well as using tgbhandsoff:true in the args.

We've also tried to set it in the values.yaml like so:

helm install aws-load-balancer-controller eks/aws-load-balancer-controller --set clusterName=example --set externalManagedTags="tgbhandsoff" -n kube-system

In all cases, these resources still get removed from our target group anyway. Is there something we're missing here?

To be clear, we're trying to be able to have some existing resources in our target group, and also have new kubernetes nodes added and removed without touching the existing resources.

**Comment by kishorj** [comment]
@willbennett-kaltura, the externalManagedTags option lets you specify resource tags that should not be modified by the controller. In your case, the controller will not modify the resource tag with the key 'tgbhandsoff' on the load balancer resources. 

As of v2.2.2, the controller assumes exclusive access over the managed target groups. There is a proposed PR https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1865 which lets you specify restrictions on the targets to manage based on the labels. We still have concerns around maintaining consistency with multiple controllers managing the same resources, so the PR is not merged  yet.

**Comment by kishorj** [comment]
@willbennett-kaltura, closing the issue since the externalManagedTags has a different purpose than the issue you described here. For your use case please continue to track the PR #1865 - we will revisit this PR post v2.3 release.
