### ISSUE TITLE
v1.1.8 (aws-alb-ingress-controller) to v2.2.2  (aws-load-balancer-controller) migration issues

### ISSUE THREAD

**Issue by B0go** [kubernetes-sigs/aws-load-balancer-controller#2162]
**Steps to reproduce**

I recently migrated one deployment of the `aws-alb-ingress-controller` v1.1.8 to `aws-load-balancer-controller` v2.2.2 and had some issues regarding the permissions needed to successfully manage resources previously created on 1.1.8. The main problem was that the [migration documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/upgrade/migrate_v1_v2/) mentions that it is required to update only the security group rules including the description "elbv2.k8s.aws/targetGroupBinding=shared" but after migrating to the new version I faced a lot of IAM permission errors because the resources created (ALB, SG, TG) on 1.1.8 missed the tags `elbv2.k8s.aws/cluster: mycluster.mydomain` and this tag is mentioned as a condition in the example required IAM Policy.

Is this expected behavior or we should evolve the migration docs to include this scenario? I don't know if this tags previously existed and something else erased them or they never existed at all, but it was hard to correlate the permission errors to the condition in the IAM Policy and I spent quite a good time figuring this out

**Expected outcome**
After adding the "elbv2.k8s.aws/targetGroupBinding=shared" description to the SG rules, updating the CRD and the version I expected the controller to successfully start and communicate with AWS to reconcile previously created resources

**Environment**

v1.1.8 (aws-alb-ingress-controller) and v2.2.2 (aws-load-balancer-controller)
Kubernetes: 1.17
EKS: no

**Comment by kishorj** [comment]
@B0go,
In case of migration from v1 to v2, you'd need to grant additional IAM permissions. This is documented in step 3 of the live doc upgrade steps [[link]](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/upgrade/migrate_v1_v2/#upgrade-steps).

If you still get errors after granting the additional IAM policies (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/install/iam_policy_v1_to_v2_additional.json), let us know.

**Comment by f3d3Cz** [comment]
I'm not sure if its related, but here it says that version `v2.0.1` is backwards-compatible with `v1.x`. It doesn't say `v2.2` is. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/upgrade/migrate_v1_v2/

However, I wanted to migrate to v2.0, but as soon as I deploy that, it tries to delete my previous ingresses. Not sure why that is?

**Comment by B0go** [comment]
> In case of migration from v1 to v2, you'd need to grant additional IAM permissions. This is documented in step 3 of the live doc upgrade steps [[link]](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/upgrade/migrate_v1_v2/#upgrade-steps).
> 
> If you still get errors after granting the additional IAM policies (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/install/iam_policy_v1_to_v2_additional.json), let us know.

Hmm I see, thanks for clarifying @kishorj! I believe I missed the point of adding this extra IAM policies because the referenced resources and actions already existed in the original configured policy, except that this time they are valid in case the needed tags are not in place (hence the errors I experienced)

Do you think it makes any sense to update the migration docs to avoid mistakes like that?

**Comment by B0go** [comment]
> I'm not sure if its related, but here it says that version v2.0.1 is backwards-compatible with v1.x. It doesn't say v2.2 is. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/upgrade/migrate_v1_v2/

Yeah, you observation makes sense but I did checked differences between 2.0.1 and 2.2 using the same process described in the previous comment, that's why I got errors! But thanks for contributing :)
