### ISSUE TITLE
When pods oom terminates abnormally, alb needs to wait for the health check to fail before stopping traffic forwarding. Can the corresponding target be marked as failed in the alb TargetGroup?

### ISSUE THREAD

**Issue by sishuiliunian** [kubernetes-sigs/aws-load-balancer-controller#2163]
**Describe the bug**
When pods oom terminates abnormally, alb needs to wait for the health check to fail before stopping traffic forwarding. Can the corresponding target be marked as failed in the alb TargetGroup?
**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by kishorj** [comment]
@sishuiliunian, have you enabled pod liveness/readiness in your case? If a pod is not ready, it will get de-registered from the target group.

**Comment by sishuiliunian** [comment]
Thanks for your reply, pod liveness/readiness are all configured. I think this is caused by the defect of state synchronization between aws-load-balancer-controller and alb.

**Comment by kishorj** [comment]
@sishuiliunian, could you verify if the fix for #1974 helps your case? Upgrade controller to v2.2.1 or later, and set the `targetgroupbinding-max-exponential-backoff-delay` controller flag.
