### ISSUE TITLE
Support for AWS Shield Advanced health-based detection

### ISSUE THREAD

**Issue by hhamalai** [kubernetes-sigs/aws-load-balancer-controller#2166]
AWS Shield Advanced supports so-called health-based detection, where a route53 health-check can be attached to a protected resource, and the outcome the health-check is used as an additional signal for an attack detection: https://aws.amazon.com/about-aws/whats-new/2020/02/aws-shield-advanced-now-supports-health-based-detection/

As LBs are created by the controller, the lifecycle of shield protections and these health-based detections should also be managed. Other solutions would require either extra solutions polling for resource change.

If this sounds like a reasonable request, I can try to contribute it. Currently, WAF and Shield functionalities are behind the feature flags, so what is the general feeling toward these functionalities or extending their functionality?

**Comment by kishorj** [comment]
/kind feature
@hhamalai, if you have the proposal, feel free to share it with us.
