### ISSUE TITLE
Support for custom AWS endpoints

### ISSUE THREAD

**Issue by papigers** [kubernetes-sigs/aws-load-balancer-controller#2176]
**Is your feature request related to a problem?**
Currently, there is no way for a user to customize any of the AWS endpoints used by this controller which makes it difficult to use the controller on non-standard regions.

**Describe the solution you'd like**
AWS allows customizing the endpoint for all/some of the services. I'm willing to submit a PR that uses an [endpoint resolver](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#hdr-Using_Custom_Endpoints) to customize every endpoint used.

**Describe alternatives you've considered**
I saw that the [EBS driver overrides all the endpoints](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L241), but that's just because it uses a single endpoint, so I thought it would be better to use a resolver for that :shrug:

**Comment by M00nF1sh** [comment]
@papigers 
Thanks for willing to help on this. I think use a custom endpoint resolver make sense. 
The source input should be from command line flags or environment variables

**Comment by papigers** [comment]
@M00nF1sh Great! I've created a PR for that, its waiting for review

**Comment by papigers** [comment]
Resolved by #2179
