### ISSUE TITLE
AWS Load Balancer Controller not setting the default certificate as specified in the documents

### ISSUE THREAD

**Issue by mseverin** [kubernetes-sigs/aws-load-balancer-controller#2177]
**Describe the bug**
When specifying a list of certificates using the annotation "alb.ingress.kubernetes.io/certificate-arn" the first ARN in a list is not alway placed as the default certificate.  It appears to be somewhat alphabetical, but a *.example.com certificate does not become the default over aechoserver.example.com

**Steps to reproduce**
1) Put a comma separated list of certificate ARNs in the annotation "alb.ingress.kubernetes.io/certificate-arn".
2) Compare the first one in the list with the default certificate of the created ALB

**Expected outcome**
A concise description of what you expected to happen.
As per the documentation, the first ARN in the list should be the default certificate

**Environment**

* AWS Load Balancer controller version - 2.1
* Kubernetes version - 1.18
* Using EKS (yes/no), if so version? - eks.6

**Additional Context**:

**Comment by kishorj** [comment]
@mseverin, this issue has been fixed in v2.2.0 release, please refer to the issue #1836 and PR #1863 for further details.

**Comment by mseverin** [comment]
thanks!
