### ISSUE TITLE
Allow configuration of per-target group attributes 

### ISSUE THREAD

**Issue by Tommyf** [kubernetes-sigs/aws-load-balancer-controller#2191]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

We have a service (Atlassian Bitbucket server) that listens on both http(s) and TCP (git-ssh). We are using nginx-ingress in front of AWS NLB for our request routing. The setup looks a little like this:

- The application (Bitbucket) has a K8s Service object configured to listen on ports 80 and 7999 (The default git-ssh port)
- The application has a K8s Ingress object that is only configured for the HTTP part, as Ingress objects do not currently support TCP.
  - This Ingress object uses the nginx-ingress controller and not the AWS ALB controller.
  - We are unable to use ALB for this as we have some URL rewriting requirements that are not supported.
- The nginx-ingress controller's Service object has annotations that AWS Load Balancer Controller uses to create the NLB
  - These annotations are where things like proxy protocol and health check attributes are defined
- The TCP configurations for nginx-ingress are defined in a config map.
- The Service object for the nginx-ingress controller has port definitions for ports 443 (TLS), 80 (TCP) and 7999(TCP).
- TLS is offloaded at the NLB. HTTP requests are forwarded by the nginx-ingress to port 443.
- Due to application design, we need to have proxy protocol v2 enabled in order to have the `x-forwarded-proto` header present. (nginx-ingress has no idea about https as it's offloaded by the NLB, so it cannot add the header)

Some of that above is not relevant directly, it just builds the picture. The most relevant part is this:

When we enable proxy protocol via annotations, it is applied to *all* Target Groups. This is fine when we are only exposing http(s) ports, but it breaks when we try to use TCP in the same multi-port service.

**Describe the solution you'd like**
A description of what you want to happen.

It would be ideal if there was a way to specify attributes on a per-target group basis for NLB.
Is it possible to have dynamic names in Annotations? Consider the following:

```
kind: Service
apiVersion: v1
metadata:
   annotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: *
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol-gitssh: 0
spec:
   ports:
      - name: http
         protocol: TCP
         port: 80
      - name: gitssh
         protocol: TCP
         port: 7999
 
```

In the above service, you have enabled proxy protocol as you would currently. This would effectively be the default for any listener/tg that is defined in the service.
You have also defined the same attribute for a specific port. So in this case, for the gitssh port, the controller could create a TG that does not have proxy protocol enabled.

Any ports that do not have an attribute defined specifically for that port, will just pick up whatever default has been defined or specified using existing annotations. This means this should not break any existing Service objects.

If it is not possible to have dynamic annotation names like this, maybe there is another way that the information can be passed in. Maybe using a ConfigMap and an annotation pointing to that?

This functionality would need to be added for all annotations that affect target groups.
Adding this functionality would greatly add to the flexibility of Service configurations using the AWS Load Balancer Controller.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

Alternatives considered:
* Disabling Proxy Protocol V2 completely. - Not an option as Bitbucket needs the c-forwarded-proto header present. Hard coding nginx-ingress to always inject the header would be hacky.
* Using a separate load balancer. This is the most likely alternative option for us. It's not ideal though:
  * Extra cost of Load Balancers, all for the sake of a minor Target Group configuration
  * Cannot use the same URL for both ports (Bitbucket repos can be cloned via https or ssh(7999) and it's nice to have them under the same URL). It's certainly an option, but it's not ideal for our migration scenario.
  * We could also have a second NLB for SSH and then another NLB in front to provide a consistent URL, but that is increasing cost and complexity needlessly.
* Create the NLB & TGs separately and use TargetGroupBindings.  This is also not ideal as we would be forfeiting the great integration between K8s and the NLB using the AWS Load Balancer Controller. This will be a shared cluster, so the more that can use native integrations, the better.

**Comment by jacktwilliams** [comment]
Agreed, for example I have UDP and TCP ports for the same service/NLB, and I'm using ingress-nginx-controller that doesn't handle proxy protocol for UDP, I don't think. So I would like to provision the target group for the UDP ports to not have proxy_protocol_v2.
