### ISSUE TITLE
Time format aws-load-balancer-controller

### ISSUE THREAD

**Issue by TraianSandu** [kubernetes-sigs/aws-load-balancer-controller#2193]
Hello!

We recently updated from old AWS ALB Ingress controller v1.1.9 to AWS Load Balancer Controller v.2.2.2. The upgrade went fine, but we noticed the time format inside logs changed : 
New alb-ingress version:

`alb-ingress-controller-6449c486fc-hthwl alb-ingress-controller {"level":"info","ts":1628859653.6314578,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"xxxx"}`

Old alb-ingress version:

`alb-ingress-controller-7c7b66bc4f-ll867 alb-ingress-controller I0813 12:29:08.517906 1 controller.go:236] kubebuilder/controller "level"=1 "msg"="Successfully Reconciled" "controller"="alb-ingress-controller" "request"={"Namespace":"xxxx","Name":"xxxx"}
`
Is there a way to change the way time is displayed inside ALB logs?

Thank you!

**Comment by Prasad1189** [comment]
/reopen

I get timeformat in epoch standard for alb pod logs, I wanted to have it in ISO 8601 standard

{"level":"info","ts":1719844438.041701,"msg":"version","GitVersion":"v2.4.1","GitCommit":"c4471defda10f8184173192b9f9df4e411ee5dac","BuildDate":"2022-03-16T16:10:01+0000"}
{"level":"info","ts":1719844609.6857922,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
