### ISSUE TITLE
Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet

### ISSUE THREAD

**Issue by DevOpserzhao** [kubernetes-sigs/aws-load-balancer-controller#2194]
**Describe the bug**
A concise description of what the bug is.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**
 ./eksctl version
0.61.0

image: amazon/aws-alb-ingress-controller:v2.1.1

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-eks-xxxxxx
  region: ap-southeast-1
  version: "1.21"
vpc:
  subnets:
    public:
      ap-southeast-1a: { id: subnet-02f1121d49d5de8ba }

 aws ec2 describe-subnets --subnet-ids subnet-02f1121d49d5de8ba
{
    "Subnets": [
        {
            "MapPublicIpOnLaunch": false, 
            "AvailabilityZoneId": "apse1-az1", 
            "Tags": [
                {
                    "Value": "shared", 
                    "Key": "k8s.io/cluster-autoscaler/eksctl-eks-xxxx"
                }, 
                {
                    "Value": "1", 
                    "Key": "kubernetes.io/role/elb"
                }, 
* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?
eks
**Additional Context**:

**Comment by kishorj** [comment]
@DevOpserzhao, I'm closing the issue for now. Feel free to reopen/create a new issue if the suggestion form @papigers  doesn't help your case.
