### ISSUE TITLE
Include `v2_2_4_full.yaml` manifest in v2.2.4 git tag

### ISSUE THREAD

**Issue by akhilles** [kubernetes-sigs/aws-load-balancer-controller#2201]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
v2.2.4 git tag should include the `v2_2_4_full.yaml` manifest. The [user guide](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) indicates that this should work:
```sh
curl -o v2_2_4_full.yaml https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.4/docs/install/v2_2_4_full.yaml
```
NOTE: I replaced `v2_2_0` with `v2_2_4` because it's the latest version. The user guide should probably be updated to use the latest version.

**Describe alternatives you've considered**
Include full manifest in GitHub release.

Current workaround is to use https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/v2_2_4_full.yaml which isn't ideal because it tracks `main` branch instead of a git tag.

**Comment by kishorj** [comment]
@akhilles, This is a current limitation, please refer to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2180. We are planning to include the installation yaml as part of release artifact in future releases. Until then, you can use the main branch for the installation yaml.

**Comment by akhilles** [comment]
Ah, didn't realize this was a duplicate. Including the yaml in the release would be perfect, thanks!
