### ISSUE TITLE
Kubectl logs returns tls: internal error

### ISSUE THREAD

**Issue by gsabatini2016** [kubernetes-sigs/aws-load-balancer-controller#2202]
When i exec "kubectl logs" or i want run "kubectl exec", i obtain the following error: 
![imagen](https://user-images.githubusercontent.com/48037187/131233225-9b49ae32-c269-4fe0-b98f-a693ced0f50c.png)
I Googled it but i cant found the solution... 
When i run "kubectl get csr" the result is this
![imagen](https://user-images.githubusercontent.com/48037187/131233283-328484f1-1206-40b4-9b89-279162bfc3e4.png)
Im running the cluster in AWS EKS Fargate Mode and was created with Terraform

**Comment by kishorj** [comment]
@gsabatini2016 could you provide more context on the issue and how it is related to the aws load balancer controller?

**Comment by gsabatini2016** [comment]
Yes, is related because, the error only happens when i try to run a kubectl logs on pods of the aws load balancer deployment. That deployment was created with Helm. It's weird because, i followed the documentation of AWS step by step but it never happened me before.

**Comment by kishorj** [comment]
@gsabatini2016, are the lb pods running in Fargate?

**Comment by gsabatini2016** [comment]
@kishorj  yes, all the cluster is running in Fargate.
![imagen](https://user-images.githubusercontent.com/48037187/131761774-00f05fa2-c527-4839-880c-214d3a1b56db.png)

**Comment by kishorj** [comment]
@gsabatini2016, how did you create the EKS Fargate profile/iam roles? Would you be able to create an AWS support case for this?

**Comment by gsabatini2016** [comment]
The fargate profiles has been created with Terraform just like the cluster. Yesterday i saw the same error in all the pods on the cluster so that let me think about the error comes from another thing.
`$ kubectl logs backend-678f969794
Error from server: Get "https://---/backend-678f969794-7h9t4/backend": remote error: tls: internal error
`

**Comment by kishorj** [comment]
@gsabatini2016, were you able to resolve your issues? do you have the AWS support case?

If you still have issues, you can share the terraform configuration snippet for the fargate profile, I can try to repro the issue on my setup.

**Comment by gsabatini2016** [comment]
Yes, i still have issues. I created a support case but i not get any answer from AWS for now. My company was elevated the issue to the representant of AWS on the company because this is blocking a deploy on a prod environment. I attached like a .log because GitHub dont support tf attached files.
[fargate.tf.log](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/7136838/fargate.tf.log)

**Comment by gsabatini2016** [comment]
Now i get the same error when i want deploy the load-balancer-controller 
![imagen](https://user-images.githubusercontent.com/48037187/132929314-8bc4c546-cdff-48e1-9a8c-c467bcd72186.png)

The webhook svc exists and match with the correspondient pod. 
![imagen](https://user-images.githubusercontent.com/48037187/132929579-77a44611-9bbe-4945-b03a-ca0e7ce04199.png)
The pod matched is running 
![imagen](https://user-images.githubusercontent.com/48037187/132929602-ae8f4be0-cba6-456a-ac7a-fd8c6790e7f6.png)

On Monday, i've a call with a official AWS supporter. I will post, the solution, here, if i could fix the error.

**Comment by gsabatini2016** [comment]
Well, the official AWS supports says he never saw this error before. He will elevates the issue to the EKS Engineers.

**Comment by kishorj** [comment]
@gsabatini2016, if your issue is still unresolved, could you share the AWS case id?

**Comment by gsabatini2016** [comment]
@kishorj yes, the support case's 8844464001 and keeps open. That seems like an error in how Terraform creates the fargate profile. I'nt get an answer from the EKS Engineers.
