### ISSUE TITLE
failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet with at least 8 free IP Addresses for ALB

### ISSUE THREAD

**Issue by kickthemooon** [kubernetes-sigs/aws-load-balancer-controller#2210]
**Describe the bug**
The aws-alb-ingress-controller is complaining with this error message:
```
failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet with at least 8 free IP Addresses for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/my-cluster-name': ['shared' or 'owned'] and 'kubernetes.io/role/elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[]'
```
But that is not true because, there are three subnets available, with thousands of free IP's, spread across all AZ's and with the appropriate tagging:
```
kubernetes.io/cluster/my-cluster-name shared
kubernetes.io/role/internal-elb 1
```

**Expected outcome**
Maybe more information. It seems that something else is wrong.

**Environment**

* AWS Load Balancer controller version
  v1.1.9
* Kubernetes version
   v1.15.12-eks-9fd540
* Using EKS (yes/no), if so version? 
   yes 1.15

**Comment by kickthemooon** [comment]
I added another tag to the subnets so now the tags:
```
kubernetes.io/cluster/my-cluster-name shared
kubernetes.io/role/internal-elb 1
kubernetes.io/role/elb
```
Now the aws-alb-ingress-controller is able to register the nodes in the target group.
But now im getting timeouts when trying to open anything running in that cluster.

**Comment by kishorj** [comment]
@kickthemooon, are you trying to create an `internet-facing` ALB? In that case, you'd need to ensure the subnets are publicly routable. Adding the `kubernetes.io/role/elb` tag is not sufficient.

**Comment by kickthemooon** [comment]
yes. the kubernetes.io/role/elb tag was missing on the public subnets.
