### ISSUE TITLE
[rabbitmq] Management UI not accessible through Ingress AWS ALB

### ISSUE THREAD

**Issue by richardsonmbr** [kubernetes-sigs/aws-load-balancer-controller#2211]
**[rabbitmq] Management UI not accessible through Ingress AWS ALB**
Using aws-load-balancer-controller version v2.2.0, I'm not able to access the rabbitmq page instead it's showing 404 error message
**Steps to reproduce**
**service config yaml** `

`
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-managment
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rabbitmq-client
      protocol: TCP
      port: 5672
      targetPort: 5672
  type: NodePort
`
**Ingress config**
`
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: instance
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/rabbitmq
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
`
**Expected outcome**
Able to access rabbitmq dashboard.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version? 1.19

**Additional Context**:

Earlier version of aws-load-balancer-controller I can able to use Wildcard path but Wildcard not supporting in version 2.2.0.
Following is not supporting
`
path: /api/v1/rabbitmq/*
            pathType: Prefix
`
If I do deploy with above Wildcard path It won't allow us to deploy instead it will throw error like Wildcard not supported.

Wildcard fix ref. https://github.com/bitnami/charts/issues/4346

**Comment by kishorj** [comment]
@richardsonmbr,
- is the ingress spec the same as the one you used with the prior version? 
- when you specify the path type as `ImplementationSpecific` and path with the wildcard, does the UI load for you?
- are there any other paths your browser is trying to access other than the `/api/v1/rabbitmq/*`?

**Comment by richardsonmbr** [comment]
@kishorj 
Here is the Answer for your ask,

* Is the ingress spec the same as the one you used with the prior version?
       Yes
* When you specify the path type as ImplementationSpecific and path with the wildcard, does the UI load for you?
       When I tried with ImplementationSpecific, I got the same issue 404
* Are there any other paths your browser is trying to access other than the /api/v1/rabbitmq/*?
      Yes, tried with some other paths but noting seems to be working.

**Comment by kishorj** [comment]
@richardsonmbr, it looks like the UI access would require additional path configuration in your ingress. Did you try adding rule for the "/" path?

**Comment by richardsonmbr** [comment]
@kishorj Yes If I put only "/" it's working as expected. 
But I have deployed lot of other micro services ex. /api/v1/abc, /api/v1/xyz
If I put "/" other url will not work
