### ISSUE TITLE
Using single ALB with target group results in multiple classic LBs per Ingress

### ISSUE THREAD

**Issue by anwarchk** [kubernetes-sigs/aws-load-balancer-controller#2213]
**Describe the bug**
I am using ALB Helm Char Version v2.2.1 on EKS 1.20.x. I followed the instructions from here https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/ to setup a single ALB that can route to multiple Ingresses within a cluster. I added the annotations:
```service:
      type: LoadBalancer
    ingress:
      enabled: true
      annotations:
        alb.ingress.kubernetes.io/group.name: platform-group
        alb.ingress.kubernetes.io/group.order: "3"
```
as per the documentation. Everything works as expected, except, for each ingress, ALB controller creates a classic LB. That is if I have 3 ingress / services, I end up with 1 ALB and 3 classic LBs. My understanding was that, in order to save cost and IP address usage, this would have just ended up in a single ALB.

**Steps to reproduce**

1. Create a Service Type of LB
2. Annotate your ingress with `alb.ingress.kubernetes.io/group.name: platform-group`
3. Deploy the app.

Repeat this for any number of services / Ingress

**Expected outcome**
One ALB created for all services / ingress.

**Environment**

* AWS Load Balancer controller version: v2.2.1
* Kubernetes version: v1.20.4-eks-6b7464
* Using EKS (yes/no), if so version? yes v1.20.4-eks-6b7464

**Additional Context**:

**Comment by kishorj** [comment]
@anwarchk, in this case, you will have to create a service of type `NodePort`, not `LoadBalancer` - I'm assuming you want to configure your ALB with instance targets.

If you create a service of type `LoadBalancer`, the kube-controller-manager provisions CLB (or NLB if specified via annotation), and this is the indended behavior.

**Comment by anwarchk** [comment]
Ok, so the `kube-controller-manager` provisiong the CLBs. The are some security concerns with using `NodePort` such as this : https://kyverno.io/policies/best-practices/restrict_node_port/restrict_node_port/ and hence we went with `LoadBalancer`.

**Comment by kishorj** [comment]
@anwarchk, k8s service of type `LoadBalancer` is built on top of `NodePort`. So the "security concerns" with `NodePort` will also apply to `LoadBalancer`.  You will have to ensure the security groups attached to your EC2 instances do not permit global access.

**Comment by kishorj** [comment]
You could use a `ClusterIP` service, if but you will have to use IP target type via the annotation
```
 alb.ingress.kubernetes.io/target-type: ip
```

**Comment by anwarchk** [comment]
Thanks. Thats a better way to do this.

**Comment by anwarchk** [comment]
Looks like this is expected behavior when using LoadBalancer type. Closing this.
