### ISSUE TITLE
ALB default action fwd to service/target group

### ISSUE THREAD

**Issue by benbyr** [kubernetes-sigs/aws-load-balancer-controller#2215]
Is there a way to change the default action (requests otherwise not routed) to forward to a certain service/target group?

The reason we need this is we have openresty setup to SSL our customers sites via CNAME, which then proxies back through to our ALB. We have Cloudfront set up for host matching protection, not needing the ALB to do the same.

Thanks,

![image](https://user-images.githubusercontent.com/1673175/132265782-76ad66d4-7051-47bf-a0fc-5f8f87ee56c8.png)

**Comment by kishorj** [comment]
@benbyr, you should be able to use `spec.backend` in case of v1beta1 or `spec.defaultBackend` in case of networking.k8s.io/v1. You can use the also use the actions annotation to specify arbitrary action instead of k8s service.

**Comment by benbyr** [comment]
@kishorj Thank you! I got it working with:

`  defaultBackend:
    service:
      name: service
      port:
        number: 80`
