### ISSUE TITLE
alb.ingress.kubernetes.io/inbound-cidrs VS. limits on “Rules per VPC security group” x “VPC security groups per elastic network interface” < 1000

### ISSUE THREAD

**Issue by brant4test** [kubernetes-sigs/aws-load-balancer-controller#2224]
We're using aws-load-balancer-controller v2.1, annotations alb.ingress.kubernetes.io/inbound-cidrs specifies the CIDRs that are allowed to access LoadBalancer.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/#inbound-cidrs

But from AWS limits "The number of rules multiplied by the number of security groups per network interface cannot exceed 1,000", which means “Rules per VPC security group” x “VPC security groups per elastic network interface” < 1000

The key issue is each IP CIDR will create a new "Inbound rule" in AWS security group, which counting as 1 additional Permission entry, taking out 1 quota from “Rules per VPC security group” limit above.

Because of that, we are seeing lots of Permission entries in one Security Group, have to increase the limit again and again. Any tips/suggestions? Thanks!

**Comment by kishorj** [comment]
These limits are from AWS, and controller will be subject to them as well. For now, the best we can recommend is to consolidate the rules into CIDRs if possible. If you can spread the rules across multiple security groups, you can specify the security groups manually via the annotation `alb.ingress.kubernetes.io/security-groups`. If you specify this annotation, you will have to manage the worker node security group rules yourself, however, in the upcoming v2.3.0 release, we will provide a mechanism to automatically manage the worker node security group rules in this case.
