### ISSUE TITLE
Question: Does the ALB Controller support path based routing ?

### ISSUE THREAD

**Issue by anwarchk** [kubernetes-sigs/aws-load-balancer-controller#2226]
I know host based routing is supported. If path based routing is supported, are there any examples ?

**Comment by anwarchk** [comment]
Looks like it does ? https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/annotations.md

**Comment by kishorj** [comment]
@anwarchk, you can specify path in the ingress spec or the annotation and the controller will satisfy the k8s resource by configure an AWS ALB. Is there any specific feature you are looking for?
