### ISSUE TITLE
GRPC without TLS or using self-signed cerificate

### ISSUE THREAD

**Issue by QuanTran91** [kubernetes-sigs/aws-load-balancer-controller#2228]
Hi all,

At the moment, I am unable to create alb using gRPC protocol without certificate arn.
I have 2 k8s services located in 2 EKS in 2 different VPC, I use VPC Peering to connect 2 VPC.
These 2 services are communicated via gRPC protocol, so I create an ingress for gRPC server.
Since it requires me to create put certificate ARN in annotation, I have to create private CA (Certificate Authority) then create a private certificate with domain *..ap-southeast-1.amazonaws.com and use that certificate.
However, the grpc client show error that this certificate is issued by unknown certificate authority.
So I think have to put CA and certificate into grpc client (via k8s manifest). I don't know if it work, I'm trying it.
But my question is:

Do AWS ALB Controller support grpc without tls? Since my connection is private and not exposed to the internet, I can use plain text grpc for these 2 services scommunication.
Or is there any workaround? 
THanks

**Environment**

* AWS Load Balancer controller version:  2.2.4
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes, 1.21

**Additional Context**:

**Comment by kishorj** [comment]
@QuanTran91, AWS ALB requires an HTTPS listener for gRPC support, this is not a limitation on the controller side. Were you not able to configure your grpc clients to accept self-signed certificates, or certs signed by your private CAs?

**Comment by kishorj** [comment]
@QuanTran91, I'm closing the issue. If you still face problems, feel free to reopen or create a new issue.
