### ISSUE TITLE
Can't get data from the metada  after switching to IMDSv2 in EKS

### ISSUE THREAD

**Issue by alexku7** [kubernetes-sigs/aws-load-balancer-controller#2231]
**Describe the bug**
A concise description of what the bug is.

**Steps to reproduce**
After switching to metada version 2 in EKS 1.21 , the AWS controller can't connecto to metada and get details required for proper functionality.

**Environment**
EKS 1.21

* AWS Load Balancer controller version
2.2.4

the example for error
{"level":"error","ts":1631737412.2021482,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect vpcID from EC2Metadata, specify --aws-vpc-id instead if EC2Metadata is unavailable: EC2MetadataError: failed to make EC2Metadata request\n\n\tstatus code: 401, request id: "}

**Comment by kishorj** [comment]
@alexku7, you need to manually specify the aws region and the vpc in case of IMDSv2. With the default configuration controller isn't able to contact IMDSv2 due to the hop limit being 1. If you modify the hop limit to be 2, metadata introspection will work as expected.

**Comment by alexku7** [comment]
Yep , You are right. Confirmed :)

Sorry for false alarm but may be need to document it somewhere :)

**Comment by kishorj** [comment]
@alexku7, no worries. Feel free to raise a doc PR with the information - a note/warning in the docs/deploy/installation.md or docs/deploy/configurations.md

**Comment by vincentvdk** [comment]
Just ran into this issue. Id have to set __both__ `region/vpc-id` and `hop limit` to make it work
