### ISSUE TITLE
Question: Can the controller support multiple VPC (internal/external) ?

### ISSUE THREAD

**Issue by christianlafleur** [kubernetes-sigs/aws-load-balancer-controller#2232]
Just figure it out if i can use the same controller (v2.2.0) on multiple VPC since no annotation seem to exist for that. Subnet work but fail with security group and target group later (vpc id mishmah). Im running on EKS private cluster.

**Comment by M00nF1sh** [comment]
@christianlafleur 
Hi, the controller works with a single vpc only. 
working with multiple vpc/accounts is also requested by multiple customers, and we are planning to design and support it.
Would you mind share your use case so that we can evaluate?
    e.g. your vpc setup/ traffic flow and expected alb/targetgroup/securitygroup setup by the controller.

**Comment by christianlafleur** [comment]
Hello, good to know you are panning this feature ! My usecase is simply to use spcific VPC for public ingress and another VPC for internal ones. Thanks

**Comment by PT-GD** [comment]
> Would you mind share your use case so that we can evaluate? e.g. your vpc setup/ traffic flow and expected alb/targetgroup/securitygroup setup by the controller.

I have a similar problem. In my case I cannot use VPC peering as proposed by others. Rather I am using a private transit gateway to communicate between the two VPCs. It seems that the controller creates the target group based on the VPC of the targets.

**Comment by PT-GD** [comment]
@M00nF1sh did this get put on the roadmap? perhaps time to reopen

**Comment by bpoweski** [comment]
this would be useful as it's idiomatic to use inspector VPCs and the lack of support create some challenges with that
