### ISSUE TITLE
Question: one NLB with multiple listeners fully managed from k8s/YAML - possible ?

### ISSUE THREAD

**Issue by przemolb** [kubernetes-sigs/aws-load-balancer-controller#2234]
When creating new NLB in AWS GUI we can add several listeners for _one_ NLB (cost savings !) and redirect traffic from different ports to different target groups.
When defining new k8s Service to create new NLB (using annotations like `service.beta.kubernetes.io/aws-load-balancer-*` ) is it possible to define multiple listeners at the k8s level ?
In general: is it possible to create new NLB with multiple listeners using just k8s YAMLs ?

**Comment by kishorj** [comment]
@przemolb, you can add multiple ports to the service spec which will translate to multiple listeners on the NLB.

**Comment by infakt-HNP** [comment]
It looks great. But how to use different selector for different NLB listeners?
My current config is:
`apiVersion: v1
kind: Service
metadata:
  name: nlb-testing
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

spec:
  type: LoadBalancer
  ports:
    - name: test1
      port: 85
      targetPort: 85
      protocol: TCP
    - name: test2
      port: 84
      targetPort: 84
      protocol: TCP
  selector:
    app: hello-world
`
And now it adds my application to two listeners. So I want to have the ability to define different selectors per port? How can I achive this?
Thank you

**Comment by kishorj** [comment]
You could use the targetgorupbinding. If you use tgb, you 'd need to create the NLB and its target groups manually. You can use targetgroupbinding to associate a NodePort (for instance targets) or ClusterIP (for IP targets) type services with the NLB target groups.

**Comment by przemolb** [comment]
@kishorj can we achieve this _only_ with targetgorupbinding ? If yes then it requiores manual operations (create NLB + target groups). My question was: "create new NLB with multiple listeners using just k8s YAMLs".
I am assuming at the moment it is not possible ?

**Comment by przemolb** [comment]
Is it this feature in any roadmap ?

**Comment by M00nF1sh** [comment]
we might be able to support this when we support [Gateway API](https://gateway-api.sigs.k8s.io/). the K8s Service API don't have such flexibility and we don't want to add something like serviceGroup.

**Comment by nfeltrin-dkb** [comment]
@M00nF1sh wouldn't it be possible to implement it in a similar way to what has been done for ALBs? In that case (if I read the [docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#group.name) correctly), using the same `alb.ingress.kubernetes.io/group.name` annotation causes multiple k8s ingresses to be created as rules in a single ALB. I would expect a similar annotation (say `service.beta.kubernetes.io/group.name`) to be available on services too... Or is that what you mean when you say you don't want to ass something like serviceGroup? 
Just trying to figure it out, it's honestly not a critique :)

**Comment by TheMatrix97** [comment]
I think this is a needed feature, in our case, ALB isn't a feasible option, as our services use simple TCP / TLS. It makes no sense having to deploy one nlb per service, is a waste of resources. Adding some kind of  `service.beta.kubernetes.io/group.name` would be perfect :)

**Comment by vumdao** [comment]
Anyone can change this issue to feature type instead of question?

**Comment by jslatterycnvrtr** [comment]
FYI, this is possible in ingress-nginx ingress controller. See [docs](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/#exposing-tcp-and-udp-services). I agree that it would be nice to see in AWS Load Balancer controller.

**Comment by revilwang** [comment]
One more use case is we need to expose services to other VPCs by using endpoint service, which NLB is required. But currently we can only create one NLB for each service, which is quite a waste. @jslatterycnvrtr

**Comment by tuomari** [comment]
I tried to create two services with name: `service.beta.kubernetes.io/aws-load-balancer-name`. It creates the  LB and target groups correctly, but when adding the second targetgroup, it clears the first targetgroup from the LB. 

I imagine that it would be fairly straightforward to keep track of the targetgroups created by the controller, and not remove them from the LB.

**Comment by ghostsquad** [comment]
> I tried to create two services with name: `service.beta.kubernetes.io/aws-load-balancer-name`. It creates the LB and target groups correctly, but when adding the second targetgroup, it clears the first targetgroup from the LB.
> 
> I imagine that it would be fairly straightforward to keep track of the targetgroups created by the controller, and not remove them from the LB.

This kind of behavior is pretty common with k8s resources. Controllers are trying to "reconcile" desired state and actual state. So, the usual pattern is loop through each object that represents desired states, and ensure actual state adheres to that. What you are seeing is exactly that:

1. service1 -> configures lb1
2. service2 -> configures lb1

and it will likely continue to bounce back and forth between states. It doesn't know what there's another service out there that is _also_ configuring it, and that these 2 states should be merged.

It does sound like that might be an interesting feature though. E.g.

```
service.beta.kubernetes.io/aws-load-balancer-merge-services: "foo,bar"
```

The questions I would have on behavior is:
1. What should be done if one of these services doesn't exist
2. Do all services in the group need to indicate their willingness to be merge with each other (is coordination required)
2a. If coordination is required, what happens if there's misalignment?

**Comment by boris-de-groot** [comment]
Are there any updating regarding this functionality? We would very much like to be able to provision a single NLB with listeners to multiple services

**Comment by Sinhyeok** [comment]
If you want to connect services that handle two different protocols under one domain, such as in the case below, the ability to bundle two service annotations to create a single NLB is essential.

```
https://gitlab.exmaple.com => 443 NLB => 443 http service => http pod
gitlab.example.com:22 => 22 NLB => 22 ssh service => ssh pod
```
