### ISSUE TITLE
Failed to calling webhook

### ISSUE THREAD

**Issue by gsabatini2016** [kubernetes-sigs/aws-load-balancer-controller#2237]
I've an EKS Cluster in AWS with Fargate and I've a weird error when i want create an Ingress resource. 

![imagen](https://user-images.githubusercontent.com/48037187/134039626-33878cb6-aa75-43b1-b303-3ebff5f11461.png)

The controller pods are all running, same for the cert-manager pods.
![imagen](https://user-images.githubusercontent.com/48037187/134040900-61a023d8-2819-4cac-bf6d-0928ece23d20.png)

**Environment**

* AWS Load Balancer controller version: v2.2.0
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes, 1.21

If anyone had the same error i'll apreciate if let me know how was fixed.

**Comment by gsabatini2016** [comment]
Update: I updated the load-balancer-controllers to the latest version and i've a new error:
![imagen](https://user-images.githubusercontent.com/48037187/134041163-44b5fa92-18ea-41c7-8b6c-c5268f3161ac.png)

**Comment by kishorj** [comment]
@gsabatini2016, it seems you installed using helm chart. Helm chart currently re-creates the TLS certificates/keys on every install. If you used helmfile, the re-creation of TLS cert/keys could cause issues in your setup. This is the eks-charts issue https://github.com/aws/eks-charts/issues/555, and the description has a diff that could potentially help.

**Comment by gsabatini2016** [comment]
@kishorj yes, the controller was installed using Helm but i tried the Kubernetes Manifest way like the documentation says because the helm way give me a lot of errors. Anyway i'll read the issue, maybe i find something who can help me. Thanks for you reply! Regards.

**Comment by gsabatini2016** [comment]
@kishorj Hi, i was doing some changes and now i get this error. Do you have any idea that could be happening?
![imagen](https://user-images.githubusercontent.com/48037187/134227814-8e7cb8f4-9823-411d-9e14-ca5c954658b6.png)

**Comment by kishorj** [comment]
@gsabatini2016, the cert manager is similar to a previous issue https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1563#issuecomment-846219688, please check if the workaround mentioned in the comments help your case.

**Comment by gsabatini2016** [comment]
Well, I could fix the error. Aparently Cert-Manager uses the same port than kubelet. I re-deployed the Cert-Manager with Helm with the "--set webhook.securePort" flag and works!. I found the solution on a comment on this issue <a href="https://github.com/jetstack/cert-manager/issues/3237">#3237</a> on the Cert-Manager repository.
