### ISSUE TITLE
SSL Redirect not supported in networking.k8s.io/v1 api version

### ISSUE THREAD

**Issue by ricky1265** [kubernetes-sigs/aws-load-balancer-controller#2242]
**Describe the bug**
A concise description of what the bug is.

**Steps to reproduce**
Use networking.k8s.io/v1 in the ingress resource yaml file instead of extensions/v1beta1
and use ssl redirect as in the port number we have to set as "use-annotation", which gives a validation error as integer is expected
**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
* 2.2.1
* Kubernetes version
* Using EKS (yes/no), if so version?
Yes
**Additional Context**:
annotations:
  alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              number: use-annotation    < --- this is not supported as it expects a integer here
        path: /*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: ui
            port:
              number: 5000
        path: /*

**Comment by kishorj** [comment]
@ricky1265, I'm closing the issue for now. If the problem persists, feel free to reopen or file a new issue.
