### ISSUE TITLE
Unable to create controller

### ISSUE THREAD

**Issue by Erokos** [kubernetes-sigs/aws-load-balancer-controller#2247]
When trying to deploy the AWS Load Balancer Controller, following the instructions for using the latest Helm chart in the Live Docs, the pods are kept in "CrashLoopBackOff" status. Their logs state:
```
{"level":"info","ts":1632479461.9025311,"msg":"version","GitVersion":"v2.2.4","GitCommit":"c269d1218dc5208f4ba39859d14a69944903c375","BuildDate":"2021-08-26T18:53:31+0000"}
{"level":"info","ts":1632479461.9975362,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"error","ts":1632479462.0090206,"logger":"setup","msg":"unable to create controller","controller":"Ingress","error":"the server could not find the requested resource"}
```

I'm trying to deploy it on a self-managed kubernetes cluster in AWS using EC2 instances. 
EBS volume type used: `gp3` (before I used `gp2`)
It's created using `kubeadm`, the latest `1.22.2` kubernetes version
For a pod networking solution, `Calico` is used.
The VPC subnets are tagged appropriately and it also doesn't work if I set the `hostNetwork` param to true. IAM policies are attached to the nodes. The command used to install:

`helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=my-cluster --set hostNetwork=true`

I've used the same instructions in July and had no problems. Any help would be appreciated.

/kind bug

Checking the cert-manager resources I see the issue is there:

```
kubectl get all -n cert-manager
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/cert-manager           ClusterIP   10.103.54.197   <none>        9402/TCP   67m
service/cert-manager-webhook   ClusterIP   10.102.4.240    <none>        443/TCP    67m
```

`crd`s are there:
```kubectl get crd | grep cert-manager
certificaterequests.cert-manager.io                   2021-09-24T09:50:42Z
certificates.cert-manager.io                          2021-09-24T09:50:42Z
challenges.acme.cert-manager.io                       2021-09-24T09:50:42Z
clusterissuers.cert-manager.io                        2021-09-24T09:50:42Z
issuers.cert-manager.io                               2021-09-24T09:50:43Z
orders.acme.cert-manager.io                           2021-09-24T09:50:43Z
```
Other than that, there are no pods or resources to get the logs from.

Also checking the kubelet status I see:

```
TLS handshake error from 192.168.178.195:33806: remote error: tls: bad certificate
```

```
Error syncing pod, skipping" err="failed to \"StartContainer\" for \"aws-load-balancer-controller\" with CrashLoopBackOff: \"bac>
Sep 24 11:48:20 dev-staging-on-demand-master-10-0-27-187 kubelet[1813]: I0924 11:48:20.427619    1813 log.go:184] http: TLS handshake error from 192.168.178.195:40360: remote error: tls: bad certificate
```

**Comment by kishorj** [comment]
@Erokos, do you see any events reported for the aws-load-balancer-controller pods? What do you see when you run `kubectl describe pod -n kube-system aws-load-balancer-controller-xxx-yyy` pods

**Comment by Erokos** [comment]
@kishorj sorry for the late reply, was away a bit. The only things that I could see are the things written above. Further testing with different ebs type etc. led me to the conclusion that it was somehow incompatible with the newest version of kubernetes which I believe you now confirmed. 
I switched to using the nginx ingress controller with an NLB and it serves our needs well. Can't say I like the idea of the AWS load ballancer controller being tied to EKS and its versions but I can understand it given the fact AWS promotes it as one of its main services.

**Comment by kishorj** [comment]
@Erokos, I'm closing this issue since there is already a feature request to support networking.k8s.io/v1
