### ISSUE TITLE
Controller does not see the subnet

### ISSUE THREAD

**Issue by maciekwisniewski** [kubernetes-sigs/aws-load-balancer-controller#2249]
Load Balancer Controller does not see the subnets, the automatic discovery did not work even though I tagged the subnets, so I tried setting the subnets using annotation and it just say:

{"level":"error","ts":1632501611.3785017,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"alb-ingress","namespace":"automatedtests","error":"InvalidSubnetID.NotFound: The subnet ID 'subnet-xxxxxxxx' does not exist\n\tstatus code: 400, request id: "}

How to find the issue?
To configure it I followed the steps from https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/
so I created the service account, installed it using helm and tagged subnets.

**Comment by kishorj** [comment]
@maciekwisniewski, could you verify the subnets you've specified are in the same VPC as the controller?

**Comment by maciekwisniewski** [comment]
Thank you for the answer @kishorj, the VPC is the same for those subnets and the EKS cluster. My cluster is using Fargate only, so when creating the cluster I provided it with 2 private subnets from the VPC. Now I am specifying 2 other, public subnets from that VPC. But could this be an issue? They are still in the same VPC and are tagged. My Kubernetes version is 1.20 and controller 2.2.4

**Comment by Shreya027** [comment]
Hi @maciekwisniewski could you please tell me the arguments you provided to the controller install using helm? For Fargate, we need to specify `--set region=<region>` and `--set  vpcId=<vpc-id>` while doing the alb controller install using helm.

**Comment by kishorj** [comment]
@maciekwisniewski, could you verify if the aws cli returns the subnets for your vpc?
For internal lb
```
aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} Name=tag:kubernetes.io/role/elb,Values=1
```
For internet facing lb
```
aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} Name=tag:kubernetes.io/role/internal-elb,Values=1
```
replace ${VPC_ID} with your VPC id

**Comment by kishorj** [comment]
@maciekwisniewski, I'm closing the issue. If you have further concerns, feel free to reopen or create a new one.
