### ISSUE TITLE
Add Flag to Enable ALB Access Logs

### ISSUE THREAD

**Issue by rsmets** [kubernetes-sigs/aws-load-balancer-controller#2250]
**Is your feature request related to a problem?**
There is seemingly no way to enable access logs on the ALB. 
Reference: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/configurations/

**Describe the solution you'd like**
A flag on the controller itself which one can set to enable access logs

**Describe alternatives you've considered**
The controller checks for an annotation ingress resources to enable ALB access logs.

**Comment by kishorj** [comment]
You could enable access logs via annotation on your ingress, for example
```
alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-access-log-bucket,access_logs.s3.prefix=my-app
```

For further details: 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#custom-attributes

**Comment by kishorj** [comment]
We are also adding support to specify lb attributes via ingress class params starting v2.3.0 release. For details - https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2190

**Comment by rsmets** [comment]
Thanks you very much for the info and the link directly in the docs. Missed that!

Closing.
