### ISSUE TITLE
Unable to use action to create type -authenticate-cognito- rule

### ISSUE THREAD

**Issue by blastik** [kubernetes-sigs/aws-load-balancer-controller#2257]
**Describe the bug**
When adding a `alb.ingress.kubernetes.io/actions` annotation of type `authenticate-cognito` to be used in the `paths` section I get the following error message:

`json: cannot unmarshal array into Go value of type ingress.Action`

**Steps to reproduce**

Applying the following ingress config does not work:

```
---
# Source: app/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customer-service
  namespace: david-test
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/team: core
    app.kubernetes.io/instance: customer-service
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: app-v2.2.0
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.redirect-to-https: >
      {"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/actions.authenticate-cognito-auth: >-
      [
        {
            "Type": "authenticate-cognito",
            "AuthenticateCognitoConfig": {
                "UserPoolArn": "arn:aws:cognito-idp:eu-west-1:123456789:userpool/eu-west-1_xxxxx",
                "UserPoolClientId": "xxxxxx",
                "UserPoolDomain": "customer-service-lab",
                "SessionCookieName": "AWSALBAuthSessionCookie",
                "SessionTimeout": "604800",
                "Scope": "openid",
                "OnUnauthenticatedRequest": "authenticate"
            },
            "Order": 1
        }, {
            "Type": "redirect",
            "ServiceName": "customer-service",
            "ServicePort": "http",
            "Order": 2
        }
      ]


spec:
  rules:
    - host: "customer-service.lab.example.com"
      http:
        paths:
          - path: /login
            backend:
              serviceName: authenticate-cognito-auth
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: redirect-to-https
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: customer-service
              servicePort: http
```

**Expected outcome**
ALB created with the corresponding rules per path.

**Environment**

* AWS Load Balancer controller version
2.2.0
* Kubernetes version 
1.18
* Using EKS (yes/no), if so version?
YES. eks.8

**Additional Context**:

What I want to achieve is **conditionally** add the cognito authentication actions to the selected paths only

---

Thank you! ❤️

**Comment by blastik** [comment]
BTW I've seen [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1465#issuecomment-752776455) issue related but i was wondering if I could use the actions instead of creating several services?

**Comment by blastik** [comment]
and perhaps because of https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/754 I'm mistaken and we cannot use an action ?

**Comment by kishorj** [comment]
@blastik, 
for cognito authentication, you'd want to use the annotation `alb.ingress.kubernetes.io/auth-idp-cognito` - For more details https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#authentication.

For the action annotation, you've specified an array instead of single struct as expected. This is different from the ELBv2 api where you can specify an array.

**Comment by blastik** [comment]
> @blastik, for cognito authentication, you'd want to use the annotation `alb.ingress.kubernetes.io/auth-idp-cognito` - For more details https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#authentication.
> 
> For the action annotation, you've specified an array instead of single struct as expected. This is different from the ELBv2 api where you can specify an array.

Thanks for your answer. I cannot use that annotation because I want **different cognito params per path**. I could use different services for that purpose but then I cannot use an `action` to forward the requests wherever I want.
Are you saying is still possible to use an action annotation for that purpose ? Could you put an example?

Long story sort. I believe the alternative number 2 in the comments of this PR https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/754 should have been chosen instead of the one we have now because we are limited on what we can do.
