### ISSUE TITLE
kubectl apply does not work after adding readinessGates

### ISSUE THREAD

**Issue by yahavb** [kubernetes-sigs/aws-load-balancer-controller#2259]
**Describe the bug**
I added readinessGates with `conditionType: target-health.alb.ingress.k8s.aws/` and run `kubectl apply` and I got a new replicaset with the new pods but left with pods from the old replicaset

**Steps to reproduce**
Configure ALB ingress
Deploy svc and ingress
Deploy a workload (e.g., nginx) 
Access the service via the ALB ingress

add readinessGates with conditionType `target-health.alb.ingress.k8s.aws/<ingress name>_<service name>_<service port name>` per https://kubernetes-sigs.github.io/aws-load-balancer-controller/v1.1/guide/ingress/pod-conditions/

Run `kubectl apply ` the workload (nginx) 

**Expected outcome**
Updated workload with readinessGates. Instead I got two replicaset that doubles my pods allocation and messes up cluster-autoscaler (many unnecessary pending jobs)  
**Environment**

* AWS Load Balancer controller version - aws-load-balancer-controller:v2.2.0
* Kubernetes version 1.19
* Using EKS (yes/no), if so version? Yes 1.19

**Additional Context**:

**Comment by kishorj** [comment]
@yahavb, the guide you mentioned is for the v1 version of the controller. Could you refer to the new guide 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/pod_readiness_gate/ instead?
