### ISSUE TITLE
Question: Do you have a reason that's not include new installation manifest in v2.2.4?

### ISSUE THREAD

**Issue by senpot** [kubernetes-sigs/aws-load-balancer-controller#2260]
I'd like to use an installation manifest in release v2.2.4 (v2_2_4_full.yaml).
And I can see an installation manifest in main but I can't see an installation manifest in v2.2.4.
Do you have a any reason that's not include new installation manifests in v2.2.4?
If possible can you include installation manifests?

**Comment by kishorj** [comment]
Please refer to the earlier reported issue on this matter - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2180

With the current process the installation yaml gets released only after the release tag is cut. For now, please use the main branch for the manifests.

**Comment by senpot** [comment]
@kishorj Thank you for the answer. I understood it.
