### ISSUE TITLE
Exact path shouldn't contain wildcards

### ISSUE THREAD

**Issue by Dgadavin** [kubernetes-sigs/aws-load-balancer-controller#2269]
**Describe the bug**
After updating ALB ingress controller to 2.2.4 I faced with warning

```
exact path shouldn't contain wildcards: /*
```
but without wildcard listener rule not work

**Steps to reproduce**
- update to the latest version
- have `pathType: Exact` and path `/*`

**Comment by kishorj** [comment]
@Dgadavin, wildcards are not supported for `Exact` or `Prefix` path types. If you need to use wildcard, you can specify `ImplementationSpecific` path type.

**Comment by Dgadavin** [comment]
Thanks a lot.
