### ISSUE TITLE
Adding group.name to existing Ingress creates a new ALB

### ISSUE THREAD

**Issue by Typraeurion** [kubernetes-sigs/aws-load-balancer-controller#2271]
**Describe the bug**
This morning I replaced the alb-ingress-controller (v1.1.4) in our dev cluster with aws-load-balancer-controller (v2.2.0).  Reading the “Migrate from v1 to v2” document I expected this would preserve our existing load balancer, which it did after the new controller was started.  But then I modified the Ingress configuration to add “alb.ingress.kubernetes.io/group.name” since I was planning to add another ingress in a different namespace.  After applying this configuration, the controller proceeded to provision a new load balancer instead of modifying the configuration of the existing load balancer.  There was also nothing in the documentation of the group.name annotation indicating that adding this would result in creating another load balancer.

**Steps to reproduce**
1. Install alb-ingress-controller v1.1.4
2. Create an Ingress resource with the annotation “kubernetes.io/ingress.class: alb” (among other alb annotations)
3. Upgrade to aws-load-balancer-controller v2.2.0 (following AWS’ documentation at https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html)
4. Modify the Ingress resource, adding the annotation “alb.ingress.kubernetes.io/group.name: dev-lb-group”

**Expected outcome**
The updated Ingress should use the existing ALB created by the old alb-ingress-controller

**Environment**

* AWS Load Balancer controller version: 2.2.0
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? No (using kubectl & AWS console)

**Additional Context**:
Looking at the tags on the ALB’s in AWS, I found the old ALB had the tag “ingress.k8s.aws/stack = <namespace>/<ingress-name>” while the new ALB has the tag “ingress.k8s.aws/stack = <group-name>”.  In addition, the old ALB has several tags which are not on the new ALB: “kubernetes.io/ingress-name”, “kubernetes.io/cluster/<cluster-name>”, “kubernetes.io/namespace”, and “ingress.k8s.aws/cluster”.  Is it possible any of these would cause the controller not to use the existing ALB?

**Comment by kishorj** [comment]
The v2 version of the lb controller uses tags to keep track of aws resources. Here are the tracking tags -
```
    elbv2.k8s.aws/cluster: ${clusterName}
    ingress.k8s.aws/stack: ${stackID}
    ingress.k8s.aws/resource: ${resourceID}
```
Also refer to the live docs - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#resource-tags

The stackID is based on the ingress group name, if an explicit group is not specified, then controller assigns an implicit group name to the ingress. If you modify the ingress group name, the controller will not be able to find existing lb resource so it provisions a new load balancer.

**Comment by Typraeurion** [comment]
Does this mean we can expect this behavior any time the group name is changed — i.e. it will provision a new LB while leaving the old LB running?  That definitely at least needs documenting, since it means the administrators will need to manually clean up the old resources.  Although my preference would be that the controller keeps track of what it had already created and just change its stack ID (assuming no other Ingress is in the same group.)

Along the same line, what would happen if I change the group name to “namespace/ingressname” to match the stack ID of the old ALB — would it update that ALB’s configuration, destroy it and create another new one, create a _third_ ALB, error out, or …?

**Comment by kishorj** [comment]
@Typraeurion, controller should automatically cleanup existing load balancer resources if you modify the group name. If the old lb still exists in your case, could you send us the ingress spec by running kubectl get ingress ingressname -n namespace -oyaml, we'd want to look at the finalizers, also share your controller logs.

The group name namespace/ingressname is not valid. 

You could modify the the ALB tags instead to match the new group name, but for safety you will have to stop the lb controller (0 replicas), modify the ALB tags, modify the ingress, then resume the controller. It is hacky, so we don't recommend.

**Comment by ajaydevtron** [comment]
> [@Typraeurion](https://github.com/Typraeurion), controller should automatically cleanup existing load balancer resources if you modify the group name. If the old lb still exists in your case, could you send us the ingress spec by running kubectl get ingress ingressname -n namespace -oyaml, we'd want to look at the finalizers, also share your controller logs.
> 
> The group name namespace/ingressname is not valid.
> 
> You could modify the the ALB tags instead to match the new group name, but for safety you will have to stop the lb controller (0 replicas), modify the ALB tags, modify the ingress, then resume the controller. It is hacky, so we don't recommend.

Hello @kishorj 

We have the same use case where we want to use an existing Load Balancer for a new Ingress by passing the stack name as the group name annotation.

However, when we add the annotation, we encounter the following validation error:

```
failed load groupID due to invalid ingress group: groupName must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
```

The issue is that the existing Load Balancer has the tag `ingress.k8s.aws/stack` with the value **namespace/ingressname**, which was generated when the LB was provisioned without explicitly setting the group name.

How can we reuse this existing Load Balancer in a new Ingress, given that its group name is based on `namespace/ingressname` (an implicit group) and does not pass the current validation rules?

**Comment by ajaydevtron** [comment]
@kishorj Could you please help here ?
