### ISSUE TITLE
Http-Header condition not working with ALB ingress v1.1.9 & v.1.1.4

### ISSUE THREAD

**Issue by Shikhakush** [kubernetes-sigs/aws-load-balancer-controller#2278]
**Describe the bug**
Hi, 

I'm trying to setup advanced header based routing condition through Ingress manifest but it's not working. you can find the configuration i'm pushing below:

--------------------------
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: example
  labels:
    app: example
  annotations:
    meta.helm.sh/release-name: example
    meta.helm.sh/release-namespace: intexamplel
    alb.ingress.kubernetes.io/scheme: internal
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:**:certificate/**
    alb.ingress.kubernetes.io/success-codes: 200,204
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck/ping
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/conditions.header: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "abc", "values":["example"]}}]
spec:
  tls:
  - hosts:
    - host.example.com
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: header
          servicePort: use-annotation
--------------------------
Also tried thsi annotation::    alb.ingress.kubernetes.io/routing.condition.header:header1=b,header2=d

Version::
ALB Ingress controller v1.1.9 running on EKS

Expectation::
I want a rule which would have two condition first would be path based i.e. /* and then header based having two headers, once both condition will meet then pass traffic to application.

Pls help me out.

**Comment by PieroMarraffa** [comment]
If you check the documentation at the link https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#conditions you'll notice that when you write alb.ingress.kubernetes.io/conditions.SERVICENAME you have to give your backend service a name and use it as the parameter I caps-locked.


in my case the final ingress.yaml was:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-name
  namespace: ns
  labels:
    app: app-name
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/subnets: subnet-1a,subnet-1b
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/conditions.service-name: >
    [{"field":"http-header","httpHeaderConfig":{"httpHeaderName":"_**HEADER-NAME**_","values":["**_HEADER-VALUE_**"]}}]
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /path-name
            pathType: Prefix
            backend:
              service:
                name: service-name
                port:
                  number: 80   


Important to use the ">" after the annotation or Kubernetes will give back the error "json: cannot unmarshal array into Go struct field ObjectMeta.metadata.annotations of type string"
