### ISSUE TITLE
[Feature Request] Is it possible to support NLB proxy protocol v2 for internal LBs?

### ISSUE THREAD

**Issue by d-shi** [kubernetes-sigs/aws-load-balancer-controller#2285]
**Is your feature request related to a problem?**
I searched the docs and issues and haven't seen this brought up before. I would like to use ingress-nginx for handling grpc traffic, which required it to be fronted by an NLB instead of an ELB. I would also like to have `force-ssl-redirect` enabled, which then requires proxy protocol v2 be set on the NLB target groups. Lastly, I would like for this NLB to be internal instead of internet-facing.

Currently this does not seem possible, as the latest version of the `aws-load-balancer-controller` only kicks in when the load balancer type is `nlb-ip` or `external`, both of which are external. However, it seems proxy protocol v2 can only be enabled if the load balancer type is one of those, and does not when the type is just `nlb`.

**Describe the solution you'd like**
Allow some combination of service annotations to allow the `aws-load-balancer-controller` to create an internal NLB and still enable proxy protocol v2 on the NLB target groups.

**Describe alternatives you've considered**
I've spent several hours reading various issues and SO answers to try to accomplish this, but there does not seem to be a way to do it without manual intervention.

**Comment by kishorj** [comment]
@d-shi, you can set proxy protocol v2  for both internal and internet-facing load balancers provisioned by the aws-load-balancer controller. The load balancer type `external` indicates the lb resources are managed by an external controller (for example the aws-load-balancer-controller) and not the kubernetes in-tree kube-controller-manager.

When you set the aws-load-balancer-type to `nlb`, the resource is handled by the in-tree controller, not this controller.
