### ISSUE TITLE
[Feature Request] Support different target group attributes per listener

### ISSUE THREAD

**Issue by d-shi** [kubernetes-sigs/aws-load-balancer-controller#2288]
**Is your feature request related to a problem?**
It is currently possible to create multiple listeners/target groups for a single NLB, but it does not seem possible to specify a different set of target group attributes for each of the target groups.

For example, I am currently trying to use nginx-ingress-controller to route many types of ingresses into the cluster. Most of them are HTTP/HTTPS, but one of them is GRPC, for which I have had to expose a TCP listener on the NLB. In order to do `force-ssl-redirect` on the HTTP endpoints, I need to enable proxy protocol v2, but this cannot be enabled on the GRPC endpoint.

From reading the docs, it doesn't seem like this is possible currently, but please let me know if it is.

**Describe the solution you'd like**
Be able to use an annotation on the NLB service such as `service.beta.kubernetes.io/aws-load-balancer-target-group-attributes`, but be able to specify the name of the port (and corresponding target group) for which to apply the attributes, and be able to set it multiple times (once per port).

**Describe alternatives you've considered**
I have to disable proxy protocol v2 for only the GRPC listener manually.

**Comment by kishorj** [comment]
@d-shi, for attributes other than the proxy protocol v2, the controller doesn't override the settings that you manually configure from the AWS console. Would it help your use case if similar support is available for proxy protocol v2 configuration?

**Comment by d-shi** [comment]
@kishorj I am configuring all of this via Terraform + Terraform Helm Provider, and would like to avoid any manual steps if possible. We need to run these Terraform modules quite frequently to set up new clusters, so any manual steps become very cumbersome. It's also not always the same person who sets up new clusters, so manual steps will often be forgotten, and then it becomes very confusing and difficult to troubleshoot.

**Comment by imduffy15** [comment]
+1 for this feature having a similar issue with self hosted gitlab, need proxy protocol for http/https traffic but not for ssh traffic.
