### ISSUE TITLE
Missing documentation for aws-load-balancer-backend-protocol and ...-ssl-ports

### ISSUE THREAD

**Issue by Nuru** [kubernetes-sigs/aws-load-balancer-controller#2296]
Although listed in the list of annotations, in Documentation version 2.2.4 there is no further documentation for the annotations
- `service.beta.kubernetes.io/aws-load-balancer-ssl-ports`
- `service.beta.kubernetes.io/aws-load-balancer-backend-protocol`

The correct settings for these annotations are not obvious. I still don't understand why `aws-load-balancer-backend-protocol` has both `https` and `ssl` as valid settings that do different things or what exactly the difference is.

**Comment by Nuru** [comment]
@kishorj wrote:
> 
> `service.beta.kubernetes.io/aws-load-balancer-backend-protocol` - If you specify `ssl` for this annotation, controller creates a TLS target group so that the connection between NLB and your application happens over TLS. You need to configure TLS listener for this. Other values for this annotation have no effect.

Thank you for explaining these 2 annotations. I am surprised about your statement "Other values for this annotation have no effect" for the `aws-load-balancer-backend-protocol` annotation. Since opening this ticket I have found [this unofficial documentation](https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/services-networking/service/) which says valid values for the annotation are `http`, `https`, `tcp`, and `ssl`, and explains them this way:

> HTTP and HTTPS will select layer 7 proxying: the ELB will terminate the connection with the user, parse headers and inject the X-Forwarded-For header with the user's IP address (pods will only see the IP address of the ELB at the other end of its connection) when forwarding requests.
>
> TCP and SSL will select layer 4 proxying: the ELB will forward traffic without modifying the headers.

Is this documentation wrong? Outdated? I suspect "ELB" refers to "classic" load balancers, but following the description, I would expect to need to use "https" with ALBs and "ssl" with NLBs.

**Comment by kishorj** [comment]
we updated the live docs, closing the issue.
