### ISSUE TITLE
Ingress not found error on deletion

### ISSUE THREAD

**Issue by sthristov** [kubernetes-sigs/aws-load-balancer-controller#2299]
**Describe the bug**

I have a cluster that is used for pull-request preview environments.
The setup is as follows:
- An Ingress in the `default` namespace that is used to persist the ALB with a group annotation that is shared with all preview ingresses.
- Each preview environment is deployed in an individual namespace with an Ingress that has the same group annotation as the above. Each preview Ingress has an individual host so the ALB can route the requests as needed.
- After the pull-request is closed the namespace is deleted.

This setup is working but I have noticed an error like the below:

```json
{
  "level":"error",
  "ts":1634304528.0231721,
  "logger":"controller",
  "msg":"Reconciler error",
  "controller":"ingress",
  "name":"redacted-group-name",
  "namespace":"",
  "error":"Ingress.networking.k8s.io \"redacted-ingress-name\" not found"
}
```

The first thing that I have noticed is that the namespace field is empty. I checked past issues and only one was similar that is related to group naming, but it's not what's wrong in my setup.

The second thing is the error itself. Initially I thought that since I remove the preview environments by directly deleting the namespace, perhaps the target group bindings might get deleted before the ingress and confuse the controller.
In order to test this theory I have split the removal process in two steps. One to delete the Ingress and another to delete the namespace, but I still get the error.

I have also checked the audit logs and I noticed something that might be related. Between the two removal steps I see that the ALB controller removes the target group bindings which is normal, but it also tries to `patch` the Ingress which I suspect is the cause of the error in the logs since it's already removed.

**Steps to reproduce**

The steps can be extracted from the description.

**Expected outcome**

There should be no errors

**Environment**

* AWS Load Balancer controller version: 2.2.0
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? eks.2

**Additional Context**:

N/A

**Comment by ketronkowski** [comment]
I am seeing the same error with v2.3.0 of the AWS Load Balancer controller.
```
{
  "level": "error",
  "ts": 1635618992.2329748,
  "logger": "controller-runtime.manager.controller.ingress",
  "msg": "Reconciler error",
  "name": "portal-ext",
  "namespace": "",
  "error": "Ingress.networking.k8s.io \"k8s-template-ext\" not found"
}
``` 
I am working with only one application in my k8s cluster. 
In my case, I do not have an ingress defined in default; it is defined in the namespace of the deployment.
