### ISSUE TITLE
K8s server version v1.22.2: groupcontroller failing

### ISSUE THREAD

**Issue by SidAceJog** [kubernetes-sigs/aws-load-balancer-controller#2300]
For the resource **networking.k8s.io**, the version **v1beta1** does not exist anylonger. 

As a result the ingress controller does not get created. And fails with a very generic error:

`{"level":"error","ts":1634560543.029553,"logger":"setup","msg":"unable to create controller","controller":"Ingress","error":"the server could not find the requested resource"}`

Error occurs in the file: group_controller.go 
function:  
`func (r *groupReconciler) SetupWithManager(ctx context.Context, mgr ctrl.Manager, clientSet *kubernetes.Clientset) error {`

**Comment by kishorj** [comment]
@SidAceJog, the controller doesn't support networking.k8s.io/v1 yet, there is an outstanding feature request #2050. I'm closing this issue as a duplicate.
