### ISSUE TITLE
Error: "couldn't auto-discover subnets: unable to discover at least one subnet"

### ISSUE THREAD

**Issue by serhiiromaniuk** [kubernetes-sigs/aws-load-balancer-controller#2316]
**Describe the bug**
ALB cannot discover subnets

**Steps to reproduce**
1. Deploy simple cluster within AWS via Terraform
2. Deploy ALB `v2.3.0 ` with 0 customiazations
3. Create iam-role and map it into serviceaccount via `eksctl create iamserviceaccount`
4. Deploy sample ingress

**Expected outcome**
200 response

**Environment**

* AWS Load Balancer controller version: `v2.3.0`
* Kubernetes version: `1.20`
* Using EKS: yes, `1.20`

**Additional Context**:
```yaml
  args:
    - '--cluster-name=< PROPER NAME >'
    - '--ingress-class=alb'
    - '--aws-region=eu-central-1'
```
```
kubernetes.io/cluster/${cluster-name}: shared
```

**Error Log**
```
{"level":"error","ts":1634915134.4170897,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"echoserver","namespace":"default","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}
{"level":"error","ts":1634915154.9974372,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"echoserver","namespace":"default","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}
{"level":"error","ts":1634915196.108869,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"echoserver","namespace":"default","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}
{"level":"error","ts":1634915278.212482,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"echoserver","namespace":"default","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}
```

Also that annotaion fixes the issue, but its no the proper way.
```yaml    
  alb.ingress.kubernetes.io/subnets: < ... >
```

**Comment by David-Tamrazov** [comment]
Posting this in case anyone else runs a similar setup - if you're deploying your clusters onto subnets shared from a different account, be sure that the subnets are tagged **_in the account you're deploying the clusters to_**, not the account that the subnets belong to/originated from. That is, if you have an AWS account with ID `11111111` that owns `subnet-abc444`, and I share it with AWS account ID `22222222`, then you have to make sure that the subnet copy of `subnet-abc444` in AWS account `22222222` is the one that has the tags. 

this tripped me up hard - the subnets aren't fully pass-by-reference so changes made in the origin account (at least for tags) don't automatically propagate over to the account the subnets are shared with. once I created the tags in the right account, this same error was resolved for me.
