### ISSUE TITLE
no endpoints available for service "aws-load-balancer-webhook-service"

### ISSUE THREAD

**Issue by aarajbhattarai** [kubernetes-sigs/aws-load-balancer-controller#2336]
**Describe the bug**
Error from server (InternalError): error when creating "ingress.yml": Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1beta1-ingress?timeout=10s": no endpoints available for service "aws-load-balancer-webhook-service"

**Steps to reproduce***
I deployed using the kubernetes manifest in AWS
kubectl apply -f ingress.yml -n=atkansproduction

**Expected outcome**
Successful Creation of Ingress

**Environment**

* AWS Load Balancer controller version: amazon/aws-alb-ingress-controller:v2.3.0
* Kubernetes  Client version: 1.21.5
* Kubernetes server version: v1.21.2-eks-0389ca
* EKS Version":0.66.0 

**Additional Context**:
kubectl describe deploy -n kube-system aws-load-balancer-controller

Name:                   aws-load-balancer-controller
Namespace:              kube-system
CreationTimestamp:      Mon, 01 Nov 2021 10:51:52 +0545
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=aws-load-balancer-controller
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=aws-load-balancer-controller
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=aws-load-balancer-controller
  Service Account:  aws-load-balancer-controller
  Containers:
   controller:
    Image:      amazon/aws-alb-ingress-controller:v2.3.0
    Port:       9443/TCP
    Host Port:  0/TCP
    Args:
      --cluster-name=aklang
      --ingress-class=alb
      --disable-restricted-sg-rules=true
    Limits:
      cpu:     200m
      memory:  500Mi
    Requests:
      cpu:        100m
      memory:     200Mi
    Liveness:     http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:               Secret (a volume populated by a Secret)
    SecretName:         aws-load-balancer-webhook-tls
    Optional:           false
  Priority Class Name:  system-cluster-critical
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   aws-load-balancer-controller-5f7cddb6d7 (1/1 replicas created)
Events:          <none>
----------------------------------------------
kubectl get deploy -n kube-system
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
aws-load-balancer-controller   1/1     1            1           2d
coredns                        2/2     2            2           4d4h

**Comment by oliviassss** [comment]
Seems similar to this issue: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2289

**Comment by kishorj** [comment]
closing as duplicate, since there is already a similar issue.

**Comment by ohookins** [comment]
Also seeing this issue on v2.3.1

**Comment by waheed-15** [comment]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2289   
this worked for me.
