### ISSUE TITLE
aws-load-balancer-private-ipv4-addresses annotation is ignored

### ISSUE THREAD

**Issue by julienperignon** [kubernetes-sigs/aws-load-balancer-controller#2337]
**Describe the bug**
Hey everyone
Creating a new service with the annotation `aws-load-balancer-private-ipv4-addresses: 10.20.0.120,10.20.1.120`  does not create an NLB with specified static IP addresses but assigns a dynamic IP from the subnet CIDR instead.

I don't see any error in the controller logs.

**Steps to reproduce**
```
          external-dns.alpha.kubernetes.io/hostname: [REDACTED]
          service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
          service.beta.kubernetes.io/aws-load-balancer-name: test-new-nlb
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
          service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: 10.20.0.120,10.20.1.120
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: [REDACTED]
          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0892c76f,subnet-d401479d
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
```
Subnets CIDRS : 
`subnet-0892c76f: 10.20.0.0/24`
`subnet-d401479d: 10.20.1.0/24`

This is the outcome i'm getting after creation : 
![image](https://user-images.githubusercontent.com/5164996/140192817-947f3392-84bb-4e44-b347-80d443613fcf.png)

**Expected outcome**
The created NLB in AWS should have both 10.20.0.120 and 10.20.1.120 ip addresses assigned

**Environment**

* AWS Load Balancer controller version: `v2.2.0`
* Kubernetes version: `1.21.5`
* Using EKS (yes/no), if so version? : `no`

Am I configuring anything incorrectly? 

Cheers

**Comment by julienperignon** [comment]
Maybe a pointer in the right direction, the annotation to specify the name of the NLB is also ignored (`service.beta.kubernetes.io/aws-load-balancer-name: test-new-nlb`)

If I switch to target IP via this annotation : `service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip` the NLB gets the name from the annotation and the correct static ip address. Am i missing something here ?

**Comment by M00nF1sh** [comment]
@julienperignon 
You missed the `service.beta.kubernetes.io/aws-load-balancer-type: external`.
`service.beta.kubernetes.io/aws-load-balancer-type` decides which controller is responsible and how to provision the LBs.

the possible values are:
* `service.beta.kubernetes.io/aws-load-balancer-type: nlb`:  The in-tree controller(built inside Kubernetes) will be used, and it provision NLB with instance targeting, however, most of these new annotations is not supported. 
* `service.beta.kubernetes.io/aws-load-balancer-type: external`: An external controller will be used to provision LBs. It can be any external controller(e.g. our aws-loadbalancer-controller or some custom made controller), and you need to specify one of the following annotation, to use aws-load-balancer-controller.
   * `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance`: aws-load-balancer-controller will provision a NLB with instance targeting
   * `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip`: aws-load-balancer-controller will provision a NLB with IP targeting
   * 
* `service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip`: This is deprecated. it's treated same as you specified both `service.beta.kubernetes.io/aws-load-balancer-type: external` and `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip`.

**Comment by julienperignon** [comment]
@M00nF1sh Thanks so much for those details. 
Indeed this was my issue and it worked properly once I set the `service.beta.kubernetes.io/aws-load-balancer-type: external` annotation.

Closing the issue
