### ISSUE TITLE
Security vulnerability of LB controller image

### ISSUE THREAD

**Issue by herbertgoto** [kubernetes-sigs/aws-load-balancer-controller#2343]
**Describe the bug**
When uploading the amazon/aws-alb-ingress-controller:v2.3.0 image to ECR, it reports the image has this high security vulnerability:

ca-certificates:2020.2.41-70.0.amzn2.0.1 - [ALAS2-2021-1710](https://alas.aws.amazon.com/AL2/ALAS-2021-1710.html)

**Steps to reproduce**
docker pull --platform=linux/amd64 amazon/aws-alb-ingress-controller:v2.3.0        
docker tag amazon/aws-alb-ingress-controller:v2.3.0 <AWS ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-alb-ingress-controller:v2.3.0
docker push <AWS ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-alb-ingress-controller:v2.3.0 

**Expected outcome**
No vulnerabilities :) 

**Environment**

* AWS Load Balancer controller version
amazon/aws-alb-ingress-controller:v2.3.0
* Kubernetes version
Not important
* Using EKS (yes/no), if so version?
Yes

**Additional Context**:

**Comment by oliviassss** [comment]
@herbertgoto We will fix it in the next patch release, thanks!

**Comment by kishorj** [comment]
addressed in v2.3.1 release.
