### ISSUE TITLE
Force this controller to manage "nlb" type or any way to use instance Target Groups

### ISSUE THREAD

**Issue by froblesmartin** [kubernetes-sigs/aws-load-balancer-controller#2350]
Hello! :smile: 

In my project, I need to use the annotation to always keep the same private IPs in my private/internal NLB. The problem is that I can not use "nlb-ip", and as the docs say (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#legacy-cloud-provider), a regular "nlb" will be managed by the legacy provider. 

**Describe the solution you'd like**
Is there any way to force the AWS Load Balancer Controller to manage the "nlb" type as well?

**Describe alternatives you've considered**
If not, is there any way to specify the private IPs to use in an "nlb" with the legacy provider? 

Thank you in advance!
Fran

**Comment by froblesmartin** [comment]
I have seen the annotation `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance`, which makes me think that even specifying `nlb-ip` type, the AWS Load Balancer Controller would configure the Target Group as instance, but sadly it does not. :(

**Comment by M00nF1sh** [comment]
@froblesmartin 
With newer controller version(e.g. v2.3.0), you can create a instance type NLB by this controller as well
You need to specify both annotation below:
* `service.beta.kubernetes.io/aws-load-balancer-type: external`
* `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance`

Note, we cannot make `service.beta.kubernetes.io/aws-load-balancer-type: nlb` work as the in-tree controller looks for the "nlb" type, we have to use `external` type above.

Also, `service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip` is deprecated, it's same as if you specified both annotation below:
* `service.beta.kubernetes.io/aws-load-balancer-type: external`
* `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip`

**Comment by froblesmartin** [comment]
Thanks a lot for your answer @M00nF1sh! I got it working now :smiley: 

I have opened this PR to try to clarify this a little bit in the docs, as seeing the type as `external` makes the impression that you can not get an `internal` NLB: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2356
