### ISSUE TITLE
ALB not working for Kubernetes Dashboard or Kibana

### ISSUE THREAD

**Issue by codenow99** [kubernetes-sigs/aws-load-balancer-controller#2351]
I am trying to create an ALB for **Kubernetes Dashboard** and **Kibana using opendistro-es** Helm chart that was previous running on Ingress nginx. They are working fine with Ingress Nginx. But I want to move them to ALB controller. 

They seem not to be working actually, the ALB are deployed but I am not able to navigate to applications. I have other multiple charts they are seem to be working fine with ALB controller, only difference among the other charts and these charts according to me seem to be is, other charts are running on port 80 or 8080 etc. whereas above mentioned charts seem to run on **443 port** that might somehow be an issue. Below is my Ingress and Service yaml files example.

**Ingress.yaml**

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: opendistro-es-kibana-ing
  labels:
    app: opendistro-es
    chart: "opendistro-es-1.11.0"
    release: "opendistro-es"
    heritage: "Helm"
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xxxxxxxxxx:xxxxxxxxx:certificate/xxxxxxxxxxxxxxxxxxxxx
    alb.ingress.kubernetes.io/group.name: example
    alb.ingress.kubernetes.io/inbound-cidrs: xxxxxxxxx/16,xxxxxxxxx/32
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-xxxxxxxxxxxxx, subnet-xxxxxxxxxxxx
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: "kibana.xxxxxxxx.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: opendistro-es-kibana-svc
              servicePort: 443
```

**Service.yaml**

  ```apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    labels:
      app: opendistro-es
      chart: "opendistro-es-1.11.0"
      release: "opendistro-es"
      heritage: "Helm"
      role: kibana
    name: opendistro-es-kibana-svc
  spec:
    ports:
    - name: kibana-svc
      port: 443
      targetPort: 5601
    selector:
      role: kibana
    type: NodePort
```
**Output of** `kubectl get ingress -A`

```
NAMESPACE    NAME                                CLASS    HOSTS                        ADDRESS                                    PORTS   AGE
example   opendistro-es-client-service        <none>   elasticsearch.xxxx.xxxx.xx   xxxxxx.xxxxx.load-balancer.amazonaws.com   80      32m
example   opendistro-es-kibana-ing            <none>   kibana.xxxx.xxxx.xx          xxxxx.xxxxx.load-balancer.amazonaws.com    80      32m
```

**Environment**

* AWS Load Balancer controller version v2.3
* Using EKS (yes/no), if so version? yes 1.21

FYI, Kubernetes Ingress yaml and Service yaml are similar.

**Comment by M00nF1sh** [comment]
@codenow99 
I'm not familiar with Kibana application, when you say it's not working properly, that's the response code/body returned when you access the ALB?
Also, i saw you used `path: /`, and by default the [PathType](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) is "ImplementationSpecific":
* with NginxIngressController, it matches all paths including path like `/someapp`.
* with ALBIngressController, it matches only `/` but not `/someapp`
If above is the error, then you can either change path to `/*`while keep pathType unspecified(ImplementationSpecific), or add a pathType to be `Prefix` per documentation about pathType above.

Note, as above rule, you need to access `kibana.xxxxxxxx.example.com` instead of the ALB's DNSName.

**Comment by M00nF1sh** [comment]
@codenow99 
Did above recommendation addresses your issue? If not, feel free to cut a new issue instead 😄
