### ISSUE TITLE
Supporting authenticated and unauthenticated paths for single ALB and shared ALB

### ISSUE THREAD

**Issue by blevine** [kubernetes-sigs/aws-load-balancer-controller#2352]
This is related to issue #2151. 

From the comments, it's unclear to me how to proceed to support the following scenarios:

1. Single ALB in which some paths are secured via OIDC and some are not.
Do I define 2 NodePort services using the same ports, one of which includes the `alb.ingress.kubernetes.io/auth-type` (and related annotations) and one that does not.  And then associate the different paths with either the unsecured or secured NodePort service?

2. Shared ALB using IngressGroup
If each application defines its ALB with secured and unsecured paths as described in 1, will this be merged correctly into the single shared ALB?

**Comment by M00nF1sh** [comment]
@blevine 
For #1, yes, you can define 2 nodePort services to achieve it. The auth annotation on service takes priority. 
For #2, yes as well. If both Ingress are within same group with [alb.ingress.kubernetes.io/group.name](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/#group.name) annotation

Both option can achieve your desired effect.

**Comment by blevine** [comment]
Thank you @M00nF1sh !  Closing.
