### ISSUE TITLE
AWS load balancer fails to start using the latest helm chart (2.3.0)

### ISSUE THREAD

**Issue by tah-mas** [kubernetes-sigs/aws-load-balancer-controller#2353]
**Describe the bug**
The aws-load-balancer-controller fails to start with the below error, using the latest chart (new install):

kubectl logs aws-load-balancer-controller-5c8d6f4467-w5nr6
{"level":"info","ts":1636564689.7425728,"msg":"version","GitVersion":"v2.0.0","GitCommit":"1028fa4f363a9a8e37b07ff6a093b7b422923512","BuildDate":"2020-10-21T22:17:18+0000"}
unknown flag: --disable-restricted-sg-rules

This is using:
Chart:  aws-load-balancer-controller-1.3.2 
App Version:   v2.3.0 

**Steps to reproduce**
Install aws-load-balancer-controller as per your instructions:
helm3 install aws-load-balancer-controller eks/aws-load-balancer-controller \
        -n kube-system \
        --set clusterName=service-k8-cluster \
        --set serviceAccount.create=false \
        --set serviceAccount.name=aws-load-balancer-controller \
        --set image.tag="${LBC_VERSION}" \
        --set region=${AWS_REGION} \
        --set vpcId=${VPC_ID} \
        --set replicaCount=1  

**Expected outcome**
I expect that the aws-load-balancer-controller deploys successfully and not get stuck in  a crash loop.

**Environment**

* AWS Load Balancer controller version
 aws-load-balancer-controller-1.3.2, App version 2.3.0
* Kubernetes version
1.21
* Using EKS (yes/no), if so version?
yes - eks.2
**Additional Context**:
I've deployed my eks with fargate so any pods in kube-system gets deployed on fargate.

**Comment by M00nF1sh** [comment]
@tah-mas 
Looks like you specified a custom image tag via `--set image.tag="${LBC_VERSION}"`. is LBC_VERSION set to some older version?

The `--disable-restricted-sg-rules` is a new field introduced in v2.3.0 only, and the latest helm chart sets it by default.

**Comment by tah-mas** [comment]
Thank you @M00nF1sh , removing the image.tag version worked. :-) I was following the instructions here: https://www.eksworkshop.com/beginner/180_fargate/prerequisites-for-alb/

**Comment by oliviassss** [comment]
@tah-mas You can follow our [live doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/installation/) in the future.
