### ISSUE TITLE
Non managed TargetGroupBindings get deleted

### ISSUE THREAD

**Issue by junzebao** [kubernetes-sigs/aws-load-balancer-controller#2357]
**Describe the bug**
We create a `TargetGroupBinding` ourselves to bind the pods to an existing ALB because we need to reuse the existing ALB, but the TGB gets deleted every night when we scale down the dev cluster. After digging into the code, I found out the non managed TGBs get deleted in the [TargetGroupBindingSynthesizer#PostSynthesize](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/deploy/elbv2/target_group_binding_synthesizer.go#L69).

**Steps to reproduce**
1. create your own TGB
2. delete the controller pod and then you'll see the new leader deletes the TGB

**Expected outcome**
non managed TGBs are not deleted; or at least we can annotate them to have the controller ignore them.

**Environment**

* AWS Load Balancer controller version: 2.2
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? yes; eks platform version eks.2

**Additional Context**:
I'm happy to provide a PR to fix it if this is not an expected behavior.

**Comment by M00nF1sh** [comment]
@junzebao 
Hi, what's the labels you supplied on your TargetGroupBinding?
It shouldn't conflicts with our `ingress.k8s.aws/stack` or `service.k8s.aws/stack`. See https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/c60d5e63485fe1c4dd726c5aa0fff8bb6459e073/pkg/deploy/tracking/provider.go#L25

**Comment by junzebao** [comment]
Hi @M00nF1sh, thanks for the quick reply! Indeed, it turns out I accidentally copy pasted the labels from a managed TGB. I just removed it and it works expected. Thanks!
