### ISSUE TITLE
Disable adding security group rules to worker node security group for nlb

### ISSUE THREAD

**Issue by RommelLayco** [kubernetes-sigs/aws-load-balancer-controller#2358]
**Is your feature request related to a problem?**
When creating an NLB. The controller adds inbound rules to the node security group or ENI security group.

<img width="839" alt="Screen Shot 2021-11-12 at 10 26 06 AM" src="https://user-images.githubusercontent.com/8358460/141371635-6505e677-3ee6-4feb-952b-e33615df2e32.png">

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/nlb/#security-group

When the service has  a lot of ports in its spec. This will cause us to reach the security group limit real quick, As it add a new inbound rule per port.

**Describe the solution you'd like**

We would like one of the following.

Option 1: An annotation to disable the controller for adding new inbound rules to the security group. Instead the admin would open the ports needed on the security groups.

Option 2: An annotation that allows us provide what ports should be open on the security group. Overriding the current logic that uses the port in the service spec.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by M00nF1sh** [comment]
/kind feature
i think option1 makes sense for now before NLB security group support. we'll make it into the v2.4.0 release if NLB SG is not ready by then

**Comment by alfredkrohmer** [comment]
This would help us a lot. We can't manage NLBs through the aws-load-balancer-controller right now due to this issue (our cloud governance doesn't allow us to modify security groups).

**Comment by bruno-andrad** [comment]
Hello everyone, everything good?
Has this problem already been resolved? I have the same problem. I need to prevent my service from creating new rules in the security group. But it does not work.
Besides installing aws-load-balancer-controller and adding the annotations, what else should I do?
