### ISSUE TITLE
MountVolume.SetUp failed for volume "cert" : secret "aws-load-balancer-webhook-tls" not found

### ISSUE THREAD

**Issue by DevOpserzhao** [kubernetes-sigs/aws-load-balancer-controller#2359]
**Describe the bug**
```
`  Warning  FailedMount  13m   kubelet            MountVolume.SetUp failed for volume "cert" : secret "aws-load-balancer-webhook-tls" not found
  Normal   Pulling      13m   kubelet            Pulling image "amazon/aws-alb-ingress-controller:v2.3.0"
  Normal   Pulled       13m   kubelet            Successfully pulled image "amazon/aws-alb-ingress-controller:v2.3.0" in 24.291651828s
  Normal   Created      13m   kubelet            Created container controller
  Normal   Started      13m   kubelet            Started container controller`
```

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
aws-alb-ingress-controller:v2.3.0
```
 Kubernetes version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Using EKS (yes/no), if so version?
```

eks

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
eksctl version   
0.67.0

```
**Additional Context**:

china cn-northwest-1

**Comment by M00nF1sh** [comment]
@DevOpserzhao 
Would you help post how you installed the controller?
seems the some step is incorrect during setup

**Comment by DevOpserzhao** [comment]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2359#issuecomment-969254093

**Comment by DevOpserzhao** [comment]
> @DevOpserzhao Would you help post how you installed the controller? seems the some step is incorrect during setup

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2359#issuecomment-969254093

**Comment by DevOpserzhao** [comment]
> @DevOpserzhao Would you help post how you installed the controller? seems the some step is incorrect during setup

[https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2359#issuecomment-969254093](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2359#issuecomment-969254093)

**Comment by DevOpserzhao** [comment]
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/installation/

**Comment by DevOpserzhao** [comment]
> @DevOpserzhao Would you help post how you installed the controller? seems the some step is incorrect during setup



install

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/installation/

**Comment by BKnights** [comment]
Same outcome following: https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/aws-load-balancer-controller.md

on eks with kubernetes 1.21

tried with cert manager 1.5.4 specified in the link. Same result with the current 1.6.1

**Comment by M00nF1sh** [comment]
@DevOpserzhao 

It looks like you were installing with the YAMLs instead of helm charts. Which requires a cert-manager installation in your cluster to generate the `aws-load-balancer-webhook-tls` secret: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/v2_2_4_full.yaml#L840
Would you help check cert-manager logs to see why the certificate is not issued.

@BKnights 
newer cert-manager version requires new `cert-manager.io/v1` for Kind Certificate, and we have updated to use  `cert-manager.io/v1` in our latest v2.3.0 installation YAMLs. If you are using the YAMLs for older controller version, it's still using "cert-manager.io/v1alpha2" which seems not supported.

**Comment by DevOpserzhao** [comment]
yes, i use installing ws-alb-ingress-controller2.3   with the YAML, I restarted the pod and no more errors were reported, I think it may be related to the configuration order of the yaml file, the certificate had not been applied when the pod was created

**Comment by DevOpserzhao** [comment]
> yes, i use installing ws-alb-ingress-controller2.3 with the YAML, I restarted the pod and no more errors were reported, I think it may be related to the configuration order of the yaml file, the certificate had not been applied when the pod was created

yes, i use installing ws-alb-ingress-controller2.3 with the YAML, I restarted the pod and no more errors were reported, I think it may be related to the configuration order of the yaml file, the certificate had not been applied when the pod was created

**Comment by BKnights** [comment]
I am installing via YAML.
The cert manager 1.6.1 works with ALB Controller 2.3 as long as I wait some time after applying the cert manager. 

When applied one after another as part of a script I consistently get the following as the last few lines of output

```
...
deployment.apps/aws-load-balancer-controller created
mutatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook created
Error from server (InternalError): error when creating "./config/alb_prepped.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
Error from server (InternalError): error when creating "./config/alb_prepped.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
```

**Comment by arundathi-nirmata** [comment]
I am installing using YAML, facing same issue! Even after waiting for some time after applying cert manager I get the error while applying controller YAML
```
Error from server (InternalError): error when creating "./config/alb_prepped.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
Error from server (InternalError): error when creating "./config/alb_prepped.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
```
The aws controller is stuck in ContainerCreating state when I describe pod 
```
  Warning  FailedMount  6m33s                 kubelet, ip-10-20-2-158.us-west-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[aws-iam-token cert aws-load-balancer-controller-token-pl2kp]: timed out waiting for the condition
  Warning  FailedMount  2m2s (x2 over 4m19s)  kubelet, ip-10-20-2-158.us-west-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cert aws-load-balancer-controller-token-pl2kp aws-iam-token]: timed out waiting for the condition
  Warning  FailedMount  22s (x12 over 8m36s)  kubelet, ip-10-20-2-158.us-west-1.compute.internal  MountVolume.SetUp failed for volume "cert" : secret "aws-load-balancer-webhook-tls" not found
```
Any solution?

**Comment by BKnights** [comment]
I have a shell script that runs after the cluster is set up. 

```
kubectl apply \
  --validate=false \
  -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml

kubectl wait \
  --request-timeout=300s \
  -n cert-manager \
  --for=condition=Available deployment/cert-manager-webhook 

#.. then prep https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.3.0/v2_3_0_full.yaml with cluster name and apply that
```

**Comment by kishorj** [comment]
@arundathi-nirmata, can you ensure that the cert-manager is installed and running first before applying the lb controller manifests?

**Comment by timharsch** [comment]
@kishorj Isn't that what his `kubectl wait` is doing?

I ran into the same error.  I also script the installation steps as I gather from following https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html,  though my script doesn't currently do a kubectl wait..  should it?  In my case i see:

output of kubectl describe pod/aws-load-balancer-controller...
```
Events:
  Type     Reason       Age                   From                                    Message
  ----     ------       ----                  ----                                    -------
  Warning  FailedMount  16m (x8 over 71m)     kubelet, ip-10-191-xx-109.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[kube-api-access-vhhq2 cert]: timed out waiting for the condition
  Warning  FailedMount  5m19s (x25 over 84m)  kubelet, ip-10-191-xx-109.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cert kube-api-access-xxxxx]: timed out waiting for the condition
  Warning  FailedMount  73s (x50 over 86m)    kubelet, ip-10-191-xx-109.ec2.internal  MountVolume.SetUp failed for volume "cert" : secret "aws-load-balancer-webhook-tls" not found
```

**Comment by timharsch** [comment]
I do see a number of errors in the logs of pod/cert-manager-cainjector...

```E1210 02:48:12.585831       1 sources.go:114] cert-manager/certificate/mutatingwebhookconfiguration/generic-inject-reconciler "msg"="unable to fetch associated certificate" "error"="Certificate.cert-manager.io \"aws-load-balancer-serving-cert\" not found" "certificate"={"Namespace":"kube-system","Name":"aws-load-balancer-serving-cert"} "resource_kind"="MutatingWebhookConfiguration" "resource_name"="aws-load-balancer-webhook" "resource_namespace"="" "resource_version"="v1" 
I1210 02:48:12.585888       1 controller.go:166] cert-manager/certificate/mutatingwebhookconfiguration/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="MutatingWebhookConfiguration" "resource_name"="aws-load-balancer-webhook" "resource_namespace"="" "resource_version"="v1" 
E1210 02:48:12.586000       1 sources.go:201] cert-manager/secret/validatingwebhookconfiguration/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="ValidatingWebhookConfiguration" "resource_name"="cert-manager-webhook" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.586078       1 controller.go:166] cert-manager/secret/validatingwebhookconfiguration/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="ValidatingWebhookConfiguration" "resource_name"="cert-manager-webhook" "resource_namespace"="" "resource_version"="v1" 
I1210 02:48:12.586246       1 controller.go:207] cert-manager/secret/mutatingwebhookconfiguration/controller/controller-for-secret-mutatingwebhookconfiguration "msg"="Starting workers"  "worker count"=1
E1210 02:48:12.586506       1 sources.go:201] cert-manager/secret/mutatingwebhookconfiguration/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="MutatingWebhookConfiguration" "resource_name"="cert-manager-webhook" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.586562       1 controller.go:166] cert-manager/secret/mutatingwebhookconfiguration/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="MutatingWebhookConfiguration" "resource_name"="cert-manager-webhook" "resource_namespace"="" "resource_version"="v1" 
I1210 02:48:12.586654       1 controller.go:207] cert-manager/secret/customresourcedefinition/controller/controller-for-secret-customresourcedefinition "msg"="Starting workers"  "worker count"=1
I1210 02:48:12.587138       1 controller.go:207] cert-manager/certificate/validatingwebhookconfiguration/controller/controller-for-certificate-validatingwebhookconfiguration "msg"="Starting workers"  "worker count"=1
E1210 02:48:12.587485       1 sources.go:114] cert-manager/certificate/validatingwebhookconfiguration/generic-inject-reconciler "msg"="unable to fetch associated certificate" "error"="Certificate.cert-manager.io \"aws-load-balancer-serving-cert\" not found" "certificate"={"Namespace":"kube-system","Name":"aws-load-balancer-serving-cert"} "resource_kind"="ValidatingWebhookConfiguration" "resource_name"="aws-load-balancer-webhook" "resource_namespace"="" "resource_version"="v1" 
I1210 02:48:12.587660       1 controller.go:166] cert-manager/certificate/validatingwebhookconfiguration/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="ValidatingWebhookConfiguration" "resource_name"="aws-load-balancer-webhook" "resource_namespace"="" "resource_version"="v1" 
I1210 02:48:12.587894       1 controller.go:207] cert-manager/certificate/customresourcedefinition/controller/controller-for-certificate-customresourcedefinition "msg"="Starting workers"  "worker count"=1
E1210 02:48:12.588798       1 sources.go:201] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="CustomResourceDefinition" "resource_name"="clusterissuers.cert-manager.io" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.588860       1 controller.go:166] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="CustomResourceDefinition" "resource_name"="clusterissuers.cert-manager.io" "resource_namespace"="" "resource_version"="v1" 
E1210 02:48:12.590756       1 sources.go:201] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="CustomResourceDefinition" "resource_name"="issuers.cert-manager.io" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.590830       1 controller.go:166] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="CustomResourceDefinition" "resource_name"="issuers.cert-manager.io" "resource_namespace"="" "resource_version"="v1" 
E1210 02:48:12.591196       1 sources.go:201] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="CustomResourceDefinition" "resource_name"="certificaterequests.cert-manager.io" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.591249       1 controller.go:166] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="CustomResourceDefinition" "resource_name"="certificaterequests.cert-manager.io" "resource_namespace"="" "resource_version"="v1" 
E1210 02:48:12.591727       1 sources.go:201] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="CustomResourceDefinition" "resource_name"="certificates.cert-manager.io" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.591776       1 controller.go:166] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="CustomResourceDefinition" "resource_name"="certificates.cert-manager.io" "resource_namespace"="" "resource_version"="v1" 
E1210 02:48:12.592982       1 sources.go:201] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="CustomResourceDefinition" "resource_name"="challenges.acme.cert-manager.io" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.593044       1 controller.go:166] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="CustomResourceDefinition" "resource_name"="challenges.acme.cert-manager.io" "resource_namespace"="" "resource_version"="v1" 
E1210 02:48:12.593504       1 sources.go:201] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="unable to fetch associated secret" "error"="Secret \"cert-manager-webhook-ca\" not found" "resource_kind"="CustomResourceDefinition" "resource_name"="orders.acme.cert-manager.io" "resource_namespace"="" "resource_version"="v1" "secret"={"Namespace":"cert-manager","Name":"cert-manager-webhook-ca"} 
I1210 02:48:12.593631       1 controller.go:166] cert-manager/secret/customresourcedefinition/generic-inject-reconciler "msg"="could not find any ca data in data source for target" "resource_kind"="CustomResourceDefinition" "resource_name"="orders.acme.cert-manager.io" "resource_namespace"="" "resource_version"="v1" 
I1210 02:48:12.594348       1 controller.go:207] cert-manager/certificate/apiservice/controller/controller-for-certificate-apiservice "msg"="Starting workers"  "worker count"=1
I1210 02:48:12.687693       1 controller.go:178] cert-manager/secret/validatingwebhookconfiguration/generic-inject-reconciler "msg"="updated object" "resource_kind"="ValidatingWebhookConfiguration" "resource_name"="cert-manager-webhook" "resource_namespace"="" "resource_version"="v1" 
```

I also see some warnings at the top of the logs via `kubectl logs -f pod/cert-manager-webhook-...`
```
W1210 02:48:12.508659       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1210 02:48:12.510094       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

**Comment by kishorj** [comment]
@DevOpserzhao, alternatively you can use use the helm template to generate the manifest and apply it. The helm template will generate necessary certificate/keys and has no dependency on cert-manager. Would this option work for your case?

**Comment by kishorj** [comment]
@DevOpserzhao, I'm closing the issue. If you have further concerns, feel free to reopen or create a new issue.

**Comment by ibekajames** [comment]
I just faced this issue as well. I wonder why the order is not set up correctly in the git repo itself rather than having people face this issue and then figuring out for themselves that they need to reorder things.

**Comment by robisoh88** [comment]
Could not replicate on first deployment, but upon attempting to redeploy after deleting manifests and 'aws-load-balancer-webhook-tls' Secret, the issue was consistent. 

    $ k get pods -A
    NAMESPACE      NAME                                           READY   STATUS              RESTARTS   AGE
    cert-manager   cert-manager-85c4777769-2r982                  1/1     Running             0          2m14s
    cert-manager   cert-manager-cainjector-67b59c8458-qwxf2       1/1     Running             0          2m14s
    cert-manager   cert-manager-webhook-5b5746d444-nzgs9          1/1     Running             0          2m14s
    kube-system    aws-load-balancer-controller-6d9d469c7-8697r   0/1     

    $ k describe po aws-load-balancer-controller-6d9d469c7-8697r -n kube-system
    ...
    Events:
      Type     Reason       Age                 From               Message
      ----     ------       ----                ----               -------
      Normal   Scheduled    2m14s               default-scheduler  Successfully assigned kube-system/aws-load-balancer-controller-6d9d469c7-8697r to ip-172-31-48-168.us-east-2.compute.internal
      Warning  FailedMount  11s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cert kube-api-access-rx2pt aws-iam-token]: timed out waiting for the condition
      Warning  FailedMount  7s (x9 over 2m14s)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "aws-load-balancer-webhook-tls" not found

    $ k get secret -A

    No resources found

Even applying the wait condition for cert-manager-webhook deployment to become available did not work:

    kubectl wait \
      --request-timeout=300s \
      -n cert-manager \
      --for=condition=Available deployment/cert-manager-webhook 
      
 After deploying the cert-manager only, I found from cert-manager and cert-manager-cainjector pod logs that they attempt to acquire leader lease and this process takes around a **minute and a half.** 

cert-manager pod logs: 
    
    I0815 19:07:34.039532       1 leaderelection.go:245] attempting to acquire leader lease kube-system/cert-manager-controller...
    I0815 19:08:58.494758       1 leaderelection.go:255] successfully acquired lease kube-system/cert-manager-controller

cert-manager-cainjector pod logs:
    
    I0815 19:07:34.160353       1 leaderelection.go:245] attempting to acquire leader lease kube-system/cert-manager-cainjector-leader-election...
    I0815 19:08:55.568166       1 leaderelection.go:255] successfully acquired lease kube-system/cert-manager-cainjector-leader-election
 
 The above wait command did not work because the condition waits for cert-manager-webhook deployment to transition to ready, but in the background the lease process did not complete (even when containers all become 1/1 ready). 
 
 To work around this add a sleep command to wait ~120 seconds after deploying the cert-manager manifests. 
 
     kubectl apply \
      --validate=false \
      -f https://github.com/jetstack/cert-manager/releases/download/v1.12.3/cert-manager.yaml

    sleep 120

    kubectl apply -f v2_5_4_full.yaml
    kubectl apply -f v2_5_4_ingclass.yaml

**Comment by DhirajBhakta** [comment]
For anyone facing this issue on **Fargate**, https://github.com/cert-manager/cert-manager/issues/3237#issuecomment-827523656 
> From their investigation, the issue mentioned is more related to cert-manager setup. The cert-manager-webhook deployment uses port 10250 which is also used for kubelet on the Fargate pods. Therefore when the connection was made to the cert-manager-webhook service it was reporting the error with ip address corresponding to pod cert-manager-webhook.
