### ISSUE TITLE
Multiple Deployments under the same Target Group

### ISSUE THREAD

**Issue by antmordel** [kubernetes-sigs/aws-load-balancer-controller#2361]
**Is your feature request related to a problem?**
I would like to have multiple deployments; i.e. `http-echo-a` and `http-echo-b` listed under the same target group. This will mean that I would have multiple deployments load balanced by the same path; i.e. http-echo.my-domain.dev:8080 can hit different deployments.

Is that possible with the v2.3.0 of the ALB? Many thanks in advance.

**Comment by M00nF1sh** [comment]
@antmordel 
We don't support this feature yet. But ALB supports a feature called weighted targetGroup which can achieve same effect.

checkout the `alb.ingress.kubernetes.io/actions.forward-multiple-tg` example in https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/#actions

**Comment by antmordel** [comment]
Many thanks @M00nF1sh ! I'll leave the issue open just in case someone else has the same doubt.

**Comment by M00nF1sh** [comment]
@antmordel 
Thanks for confirming this. we'll close this one as it's supported use case.  old closed issues can be searched as well :D
