### ISSUE TITLE
Access denied using default iam-policy

### ISSUE THREAD

**Issue by benzch** [kubernetes-sigs/aws-load-balancer-controller#2362]
Getting the following error when using default iam-policy: 
https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.0/docs/install/iam_policy.json

We used alb-ingress-controller version 1.1.7.

error logs: 
{"level":"error","ts":1636979057.3285396,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"xxxxxxxxx","namespace":"default","error":"AccessDenied: User: arn:aws:sts::xxxxxxxxx:assumed-role/aws-load-balancer-controller-dev/kiam-kiam is not authorized to perform: elasticloadbalancing:AddTags on resource: arn:aws:elasticloadbalancing:us-east-1:xxxxxxx:targetgroup/xxxxx-xxxxxxxxx/xxxxxxxxx because no identity-based policy allows the elasticloadbalancing:AddTags action\n\tstatus code: 403, request id: xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxx"}

Seems that we are missing permission even though I am using default policy.

* 2.3.0
* 1.18
* eks

**Additional Context**:

**Comment by M00nF1sh** [comment]
@benzch 
If i understand correctly, you were migrating from v1.1.7 to v2.3.0.
if so, then you'll need these **additional** IAM policy: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy_v1_to_v2_additional.json. (you can remove them once you finished migration, i.e. at least one successful reconcile event posted by new controller for each ingress).

Also, check our migration guide for other manual actions needed: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/upgrade/migrate_v1_v2/ :D

**Comment by benzch** [comment]
@M00nF1sh  that fixed the issue. Thank you!!!

**Comment by M00nF1sh** [comment]
@benzch glad it solves the issue.
