### ISSUE TITLE
Small documentation improvement around IAM policy

### ISSUE THREAD

**Issue by przemolb** [kubernetes-sigs/aws-load-balancer-controller#2369]
The docs https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/installation/#setup-iam-role-for-service-accounts says that there is a way to further restrict access to security groups tagged for the particular k8s cluster:
```
...
OR restrict access to security groups tagged for the particular k8s cluster. Replace CLUSTER-ID with your
k8s cluster id and add it to the above IAM permissions.

    "Condition": {
        "Null": {
            "aws:ResourceTag/kubernetes.io/cluster/CLUSTER-ID": "false"
        }
    }
```
Can anyone clarify in the docs what is the `CLUSTER-ID` ? Is it the name of the cluster ?
For example grepping for `id` in `aws eks describe-cluster --name ...` output displays different ids but nothing what would look like cluster id.

**Comment by M00nF1sh** [comment]
/kind document

@przemolb Yes, it's the clusterName of your cluster. You can find such tag on your worker security group which will be modified by the controller automatically.

**Comment by przemolb** [comment]
I used the cluster name and all worked fine. However in AWS (and not only) the "ID" has quite different purpose than name. And thought that docs clarification would remove any doubts.
