### ISSUE TITLE
InvalidSecurityGroup: The security group

### ISSUE THREAD

**Issue by john-jun** [kubernetes-sigs/aws-load-balancer-controller#2371]
{"level":"error","ts":1637322446.2133129,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"gateway","namespace":"gateway","error":"InvalidSecurityGroup: The security group 'sg-005646f2913a5dbe4' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidGroup.NotFound; Request ID: 19afdaba-4d40-42cd-bdbf-1d7e691dfe6c; Proxy: null)\n\tstatus code: 400, request id: 3e6c7d17-2b4e-4937-85c5-f9330df1d175"}

**Comment by kishorj** [comment]
@john-jun, did you specify the security group via annotation?

**Comment by kishorj** [comment]
@john-jun, I'm closing the issue. If you still encounter problems, feel free to reopen or file a new issue.
