### ISSUE TITLE
Add a webhook to prevent new usage of in-tree controller support

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes-sigs/aws-load-balancer-controller#2382]
**Is your feature request related to a problem?**
Users wants to prevent accidental usage of in-tree controller

**Describe the solution you'd like**
block new usages of NLB Services supported by in-tree controller via a webhook if certain knob is set.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by sftim** [comment]
Also see #2421

**Comment by johngmyers** [comment]
It seems a little odd for one service controller to block use of a different service controller. Assuming it's not possible to simply disable the in-tree controller, the appropriate place to implement a block would be in a generic policy-enforcing controller, such as Gatekeeper.
