### ISSUE TITLE
Documentation out of date for IAM perms needed

### ISSUE THREAD

**Issue by unacceptable** [kubernetes-sigs/aws-load-balancer-controller#2388]
**Describe the bug**
Documentation is out of date on the website when compared to what's in the repo on trunk.
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/5d86951a2c58917e6a3f795eb96047515d1e8569/docs/deploy/installation.md#setup-iam-manually
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.3.0/docs/deploy/installation.md#setup-iam-manually

**Steps to reproduce**
1. [Configure IAM manually via the installation guide.](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/installation/#setup-iam-manually)
2. This references v2.2.1's policy, which won't work.

**Expected outcome**
The ability to get accurate information when reviewing the documentation for the current version.

**Environment**

* N/A

**Additional Context**:
Recommend a patch version so the documentation is up to date for the latest version.

**Comment by kishorj** [comment]
@unacceptable, this is fixed by PR #2378. We will publish the new live docs based on the recent changes.

**Comment by kishorj** [comment]
We've published new live docs. The links are point to the correct IAM configuration.
