### ISSUE TITLE
"Failed to auto-create backend SG" with 2.3.0

### ISSUE THREAD

**Issue by Tenzer** [kubernetes-sigs/aws-load-balancer-controller#2389]
**Describe the bug**
After upgrading from AWS Load Balancer Controller version 2.2.4 to 2.3.0 we started seeing messages from the daemon that it couldn't create the backend security group:

<details><summary>Log lines</summary>

    {"level":"info","ts":1638375014.2486198,"logger":"backend-sg-provider","msg":"creating securityGroup","name":"k8s-traffic-private-715dc8493c"}
    {"level":"error","ts":1638375014.350597,"logger":"backend-sg-provider","msg":"Failed to auto-create backend SG","error":"UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 4PYfPMnAARfj-RyEmxkcFkjJdYw7m6A0tFTyCj3Dr47vZdX08ZJoXDPqcME4rCaV3vJ0be4MXNIVyxd2KpnKCVR0oDhAzNQ3NGk4czsl6qji9xX7FR4KfE5qe0wcGKckPWjw4NRyRMFA7BIlvgoxQ_gVoICxBvUu4NAI7JRvXxZX4VO-eE6sJO13r4yeaBEoWQ1m5ElEy12XxTacCjboo2jmkjYXxISzDFpMTF0i64NbmP6IN6TTneIscCxKTlf_HCIjNtaciCzriF5GI5ChjrJgnua8Zcfgt037mU-E3HgKiBKi-GRFv7sV0GUMDX3ZNuP5uE3qOiTlgKxm4kcwLpOy9PqQ885OTfQX7HXET0r9Zq6JMaz15F9FeO4gxf5hqtq2Q8WGa5L_zcwDxN0IwDs9K6lm2r_dIEYj-nwdOKMmPB_cSPFpcuvgHHv-OW_6Nu5tKaRF2uSN91sQg3RJYg5a76zBtynOpJ6CvlQVOxtaJAPREn4DtF_o-OpM4zb11kqGfGZGLBUlkPKBElfUcwGvi8TKRRtta52NsvU-87tApIOedUTSQGfPNX5UgMNV9sK-\n\tstatus code: 403, request id: ea62cfac-3c66-492f-8353-f4a77592c412"}
    {"level":"error","ts":1638375014.3508162,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"alb","namespace":"","error":"UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 4PYfPMnAARfj-RyEmxkcFkjJdYw7m6A0tFTyCj3Dr47vZdX08ZJoXDPqcME4rCaV3vJ0be4MXNIVyxd2KpnKCVR0oDhAzNQ3NGk4czsl6qji9xX7FR4KfE5qe0wcGKckPWjw4NRyRMFA7BIlvgoxQ_gVoICxBvUu4NAI7JRvXxZX4VO-eE6sJO13r4yeaBEoWQ1m5ElEy12XxTacCjboo2jmkjYXxISzDFpMTF0i64NbmP6IN6TTneIscCxKTlf_HCIjNtaciCzriF5GI5ChjrJgnua8Zcfgt037mU-E3HgKiBKi-GRFv7sV0GUMDX3ZNuP5uE3qOiTlgKxm4kcwLpOy9PqQ885OTfQX7HXET0r9Zq6JMaz15F9FeO4gxf5hqtq2Q8WGa5L_zcwDxN0IwDs9K6lm2r_dIEYj-nwdOKMmPB_cSPFpcuvgHHv-OW_6Nu5tKaRF2uSN91sQg3RJYg5a76zBtynOpJ6CvlQVOxtaJAPREn4DtF_o-OpM4zb11kqGfGZGLBUlkPKBElfUcwGvi8TKRRtta52NsvU-87tApIOedUTSQGfPNX5UgMNV9sK-\n\tstatus code: 403, request id: ea62cfac-3c66-492f-8353-f4a77592c412"}

</details>

**Steps to reproduce**
Install or upgrade to version 2.3.0?

**Expected outcome**
I would expect AWS Load Balancer Controller to create any security group it would need since it has the `ec2:CreateSecurityGroup` AWS permission without any restrictions.

**Environment**

* AWS Load Balancer controller version: 2.3.0
* Kubernetes version: 1.21.2
* Using EKS (yes/no), if so version? Yes, eks.2(?)

**Additional Context**:

I upgraded by applying the configuration from the [YAML file](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.3.0/v2_3_0_full.yaml) listed on the [2.3.0 release](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.3.0) and used the [IAM permissions linked](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.0/docs/install/iam_policy.json) from there as well.
The IAM role is granted to the AWS Load Balancer Controller daemon via a Kubernetes service account and OIDC.

For now I managed to work around this issue by adding the `--enable-backend-security-group=false` flag in the deployment.

**Comment by kishorj** [comment]
@Tenzer, would you be able to send the controller logs to k8s-alb-controller-triage@amazon.com? Also check the cloud trail for the failed CreateSercurityGroup event and verify the assumed role has the correct permissions.

**Comment by Tenzer** [comment]
Sure! I have done that now.

**Comment by Tenzer** [comment]
I have tried to upgrade to version 2.3.1 and it still gives the same errors when I remove the `--enable-backend-security-group=false` flag.

**Comment by Tenzer** [comment]
Kishor helped find the reason for the problem, which was the IAM policy in place didn't match the one from the documentation exactly. The discrepancy must be down to when we transcribed the IAM policy into Terraform's way of managing them, and we managed to leave out `/*` at the end of a `Resource` line.

**Comment by kkhushboo121** [comment]
@kishorj  recently update the ingress-controller from 1.1.9 to 2.43, using the helm but  getting following error :
`:"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"ingressxx","namespace":"na","error":"UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message:`

Also the set --enable-backend-security-group=false but having the same error.
