### ISSUE TITLE
Self Health Check for AWS LB Controller - ALB

### ISSUE THREAD

**Issue by varun-lb** [kubernetes-sigs/aws-load-balancer-controller#2392]
The Issue:
I currently have a setup of (Ingress ALB) based AWS LB controller. This has multiple services setup behind a single ALB using the group annotation feature. While this works great, when using this ALB as part of a TargetGroup that acts as a listener for an existing NLB, the (TG) target group (of this NLB)  keeps failing all health checks as the Ingress ALB created by AWS Load Balancer itself does not have any health check ports/path. It relies on the NLB TG to check the Port/Path of the underlying ALB TG which may/may not be accessible due to complex Header based logic rules applied.

Workarounds available:
Currently we have 2 workarounds - 
1) Deploy a sample container (nginx) as LoadBalancer service and point the TG of the NLB to this LoadBalancer and get a 200
2) Change the configuration of the NLB TG to accept 404 as a success code in its Health Check

Expected Solution:
A simple health check path on the Ingress ALB itself would solve this issue.

**Comment by kishorj** [comment]
@varun-lb, would TCP based health check not work for your use case?

**Comment by varun-lb** [comment]
Hey @kishorj, I dont think we get an option for the Health Check Protocol to be set as TCP when trying to add an Application LoadBalancer to a TargetGroup.
