### ISSUE TITLE
Cannot specify path/query longer than 128 characters for custom action

### ISSUE THREAD

**Issue by uripre** [kubernetes-sigs/aws-load-balancer-controller#2396]
When using a custom action `alb.ingress.kubernetes.io/actions.__`, a validation error is thrown if any property is long than 128 characters. This is especially problematic with the path/query fields in redirects, for example.

What's the underlying reason for this limitation? Any way to bypass or solve this?

**Steps to reproduce**
Have a custom `alb.ingress.kubernetes.io/actions.__` action with path/query longer than 128 characters, The following error appears:

`FailedDeployModel  78s  ingress  Failed deploy model due to failed to create listener rule: ValidationError: 1 validation error detected: Value '<PATH>' at 'actions.1.member.redirectConfig.path' failed to satisfy constraint: Member must have length less than or equal to 128`

**Comment by kishorj** [comment]
@uripre, This limitation is from the AWS ALB side, not a controller issue. For details, please refer to the ALB documentation https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#redirect-actions.

**Comment by uripre** [comment]
Thanks for clarifying @kishorj
