### ISSUE TITLE
InvalidInstanceID.NotFound when creating load balancer on shared VPC in separate account from worker nodes

### ISSUE THREAD

**Issue by pdbogen** [kubernetes-sigs/aws-load-balancer-controller#2398]
**Describe the bug**

In our environment, we run worker nodes in account `compute-platform` and I would like load-balancer-controller to manage a load balancer in account `workload`. Correspondingly, `aws-load-balancer-controller` is running with a pod-linked IAM role, such role is in account `workload`.

The controller is able to create load balancers, create target groups, etc., properly. It's not able to register targets to the target groups, even in `ip` mode. It reports:

```json
{
  "level":"error",
  "ts":1638499305.8151796,
  "logger":"controller-runtime.manager.controller.targetGroupBinding",
  "msg":"Reconciler error",
  "reconciler group":"elbv2.k8s.aws",
  "reconciler kind":"TargetGroupBinding",
  "name":"k8s-default-zpdbogen-56c261b12e",
  "namespace":"default",
  "error":"InvalidInstanceID.NotFound: The instance ID 'i-...' does not exist\n\tstatus code: 400, request id: ..."
}

```

**Environment**

* AWS Load Balancer controller version: **v2.2.4**
* Kubernetes version: **1.18**
* Using EKS (yes/no), if so version? **yes, 1.18 eks.9**

**Additional Context**:

**Comment by kishorj** [comment]
For ALB, you can disable security groups management by specifying the annotation `alb.ingress.kubernetes.io/security-groups`. We don't have similar feature for NLB, but we plan to provide a mechanism to disable security groups rules management in future releases.

**Comment by kishorj** [comment]
@pdbogen, We plan to support disabling NLB SG rules in management in v2.4.0, feature request #2358. I'm closing this issue. If you have further concerns, feel free to reopen or create a new issue.
