### ISSUE TITLE
ALB not allowed in Managed node groups

### ISSUE THREAD

**Issue by ngoyal16** [kubernetes-sigs/aws-load-balancer-controller#2402]
**Describe the bug**
We were using unmanaged nodegroup now recently we switched to managed node group.. managed node groups security group was not having permission for request from ALB. To fix the issue i have to add manual entry in managed node group SG

**Expected outcome**
ALB security group shoule be allowed managed node group SG

**Environment**

* AWS Load Balancer controller version: 2.2.4
* Kubernetes version: 1.21

**Comment by kishorj** [comment]
@ngoyal16, would you be able to share the controller logs when things don't work as expected? WHat manual entry did you add to the managed node group SG? You can email the logs to **k8s-alb-controller-triage AT amazon.com**.

**Comment by kishorj** [comment]
@ngoyal16, would you be able to share the controller logs with us?

**Comment by kishorj** [comment]
@ngoyal16, I'm closing the issue for now. If you have further concerns, feel free to reopen or create a new one.
