### ISSUE TITLE
Ingress gets deployed but target group IP is incorrect

### ISSUE THREAD

**Issue by Sparkton** [kubernetes-sigs/aws-load-balancer-controller#2403]
Hi, 
I deployed the [2048 example](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/master/docs/examples/2048) but the target groups deployed are taking the endpoints IP. I have gone through multiple documentations but cannot seem to get it working.
```
default       pod/2048-deployment-6cd485c86-dn5wl            1/1     Running   0          13s
default       pod/2048-deployment-6cd485c86-v7f55            1/1     Running   0          14s
default       pod/external-dns-59f8cf457d-6jbtk              1/1     Running   0          52m
kube-system   pod/alb-ingress-controller-bc8df847-ldtjd      1/1     Running   0          43m
kube-system   pod/coredns-66bff467f8-bffc5                   1/1     Running   0          57m
kube-system   pod/coredns-66bff467f8-sk9dq                   1/1     Running   0          57m
kube-system   pod/etcd-ip-172-31-35-137                      1/1     Running   0          57m
kube-system   pod/kube-apiserver-ip-172-31-35-137            1/1     Running   0          57m
kube-system   pod/kube-controller-manager-ip-172-31-35-137   1/1     Running   0          57m
kube-system   pod/kube-proxy-fd6wz                           1/1     Running   0          56m
kube-system   pod/kube-proxy-twjcg                           1/1     Running   0          57m
kube-system   pod/kube-scheduler-ip-172-31-35-137            1/1     Running   0          57m
kube-system   pod/weave-net-jh8lh                            2/2     Running   1          56m
kube-system   pod/weave-net-z77xv                            2/2     Running   1          56m

NAMESPACE     NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes     ClusterIP   10.96.0.1      <none>        443/TCP                  57m
default       service/service-2048   NodePort    10.103.2.238   <none>        80:31542/TCP             13s
kube-system   service/kube-dns       ClusterIP   10.96.0.10     <none>        53/UDP,53/TCP,9153/TCP   57m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/kube-proxy   2         2         2       2            2           kubernetes.io/os=linux   57m
kube-system   daemonset.apps/weave-net    2         2         2       2            2           <none>                   56m

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
default       deployment.apps/2048-deployment          2/2     2            2           14s
default       deployment.apps/external-dns             1/1     1            1           52m
kube-system   deployment.apps/alb-ingress-controller   1/1     1            1           43m
kube-system   deployment.apps/coredns                  2/2     2            2           57m

NAMESPACE     NAME                                              DESIRED   CURRENT   READY   AGE
default       replicaset.apps/2048-deployment-6cd485c86         2         2         2       14s
default       replicaset.apps/external-dns-59f8cf457d           1         1         1       52m
kube-system   replicaset.apps/alb-ingress-controller-bc8df847   1         1         1       43m
kube-system   replicaset.apps/coredns-66bff467f8                2         2         2       57m
```
Endpoints
```
~$ k get ep
NAME           ENDPOINTS                   AGE
service-2048   10.44.0.4:80,10.44.0.5:80   106s
```

[Target Groups](https://i.stack.imgur.com/UtrOL.png)

**Comment by davidy718** [comment]
try setting `alb.ingress.kubernetes.io/target-type: instance`

**Comment by Sparkton** [comment]
I tried both ip and instance target types but both lead to the same issue

**Comment by davidy718** [comment]
> I tried both ip and instance target types but both lead to the same issue

if you set `alb.ingress.kubernetes.io/target-type: instance` it should be instance id and not ip in the target group

**Comment by Sparkton** [comment]
> > I tried both ip and instance target types but both lead to the same issue
> 
> if you set `alb.ingress.kubernetes.io/target-type: instance` it should be instance id and not ip in the target group

On using instance as target-type I get the following as my target group and load balancer.

![Screenshot from 2021-12-08 20-16-40](https://user-images.githubusercontent.com/47005364/145228672-99d39922-fd89-4b8c-a2e0-b449307bd761.png)
The target group does not attach to a load balancer

No listeners get added in the load balancer and no targets are registered in the target group

**Comment by davidy718** [comment]
can you run `kubectl logs -f -n kube-system $(kubectl get po -n kube-system | egrep -o alb-ingress[a-zA-Z0-9-]+)` and see if you get any errors

**Comment by Sparkton** [comment]
```
kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to reconcile targetGroup targets due to No providerID found for node ip-xxx"  "controller"="alb-ingress-controller" "request"={"Namespace":"2048-game","Name":"2048-ingress"}
```
This is the error I get

**Comment by kishorj** [comment]
@Sparkton, what is your controller version? EKS/k8s version?

**Comment by Sparkton** [comment]
> @Sparkton, what is your controller version? EKS/k8s version?
Kubernetes: 1.18
And I am not using EKS

**Comment by kishorj** [comment]
@Sparkton, did you set up the cloudprovider as AWS? looks like your k8s node resources are not setup appropriately for AWS.

**Comment by Sparkton** [comment]
@kishorj  I have no errors with IP targets but the target groups ends up like shown in this [image](https://i.stack.imgur.com/UtrOL.png).
Also, could you tell what Ill need to change to set up the node resources appropriately.

**Comment by davidy718** [comment]
if your are not using EKS I don't think you can use `type: instance` but if your using IP you need to make sure your pod can get an IP that can be communicate from out side the cluster when using `type: IP` it will sent it to the IP of the pod 
[https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-type](url)
> ip mode will route traffic directly to the pod IP.

**Comment by Sparkton** [comment]
Any idea how I would go about to rectify this issue??
How can I make sure that the pods get IPs assigned to them that can be accessed from outside the cluster?

**Comment by davidy718** [comment]
you can use [https://github.com/aws/amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s)
