### ISSUE TITLE
Push all egress traffic through particular NatGW

### ISSUE THREAD

**Issue by przemolb** [kubernetes-sigs/aws-load-balancer-controller#2405]
We have EKS cluster with X node groups each in different AZ (+ the latest LB controller installed). It obviously means we have dedicated Nat GW for egress traffic for each AZ (and in general we wouldn't like to change that). But for some specific scenarios (internal testing) we would like to enforce all egress traffic through one of the Nat GWs.
Is it somehow possible ?

**Comment by kishorj** [comment]
@przemolb, unfortunately, this is not an issue with the load balancer controller. We recommend to cut a support ticket to the AWS EC2 to get further guidance.

**Comment by przemolb** [comment]
I didn't claim it is an issue. I didn't find any discussion forum dedicated for LB controller and I let myself ask here. It was more technical question than issue topic.
