### ISSUE TITLE
[Feature request] Merge tags from alb.ingress.kubernetes.io/tags between service and ingress

### ISSUE THREAD

**Issue by michelzanini** [kubernetes-sigs/aws-load-balancer-controller#2411]
**Is your feature request related to a problem?**

When monitoring healthy/unhealthy targets on a monitoring system it is really hard to identify what K8S service it came from since the target name only contains 8 first chars, and we have services with long names and the same prefixes.

This are two examples of targets that look very much the same and we can't distinguish:

```
k8s-sandbox-systemte-7ba41435fc
k8s-sandbox-systemte-be0d2a4b2e
```

**Describe the solution you'd like**

Will be good if we could count on an AWS tag in the Target Group that only contains the service name, such as:

```
ingress.k8s.aws/service: "my-long-k8s-service-name"
```

or

```
ingress.k8s.aws/target: "my-long-k8s-service-name"
```

**Describe alternatives you've considered**

I know we can add a tag by using:

```
alb.ingress.kubernetes.io/tags: Service=my-long-k8s-service-name
```

But I can't use this because my Ingress already has 5 tags added and when you use `alb.ingress.kubernetes.io/tags` on the service and on the Ingress together, the tags **don't** merge, instead, the service tags take priority. This way I can't add the tag myself without losing other important tags.

Another solution that would work great would be to merge tags from service and ingress for `alb.ingress.kubernetes.io/tags`. That would also help solving the issue.

**Note**:
The issue has been renamed to track the implementation that will merge tag values from `alb.ingress.kubernetes.io/tags` at service and ingress levels.

For example, adding this annotations:

service:
```
alb.ingress.kubernetes.io/tags: ServiceTag=my-tag-service
```

ingress:
```
alb.ingress.kubernetes.io/tags: IngressTag=my-ingress-service
```

Will tag the AWS target group with:

```
ServiceTag=my-tag-service
IngressTag=my-ingress-service
```

Current behaviour only tags `ServiceTag`.
I recommend if the same tag is found on both places that the `service` level overrides the value of the `ingress` (but only if it's the same tag).

**Comment by kishorj** [comment]
@michelzanini, the targets group for ALB will have the following tag:
ingress.k8s.aws/resource: <namespace>/<ingress-name>-<service-name>:<port>
check if parsing the tag works for your case

We will look into supporting merging of the tags specified via annotation between ingress and service.

**Comment by michelzanini** [comment]
Because the monitoring tool (Datadog) is limited, I can't really parse `ingress.k8s.aws/resource`, which contains some more info in the string besides the service name.
Another problem with `ingress.k8s.aws/resource` is that this tag is also at the load balancer, not only the target group, then Datadog reads that tag too and the value of `ingress.k8s.aws/resource` becomes something like `ingress.k8s.aws/resource:loadbalancer,sandbox/sandbox-ingress-alb-my-service:80` (see the `loadbalancer,` prefix here is the combined value) and the only thing I really want here is `my-service`.

**Comment by michelzanini** [comment]
> We will look into supporting merging of the tags specified via annotation between ingress and service.

Do you want me to create a separated issue - or maybe rename this one to do that? I guess if you can merge the `tags` annotation then it solves my problem anyway.

**Comment by kishorj** [comment]
@michelzanini, feel free to rename the issue.

/kind feature

**Comment by michelzanini** [comment]
I have renamed the issue and added this description to it:

The issue has been renamed to track the implementation that will merge tag values from alb.ingress.kubernetes.io/tags at service and ingress levels.

For example, adding this annotations:

service:
```
alb.ingress.kubernetes.io/tags: ServiceTag=my-tag-service
```

ingress:
```
alb.ingress.kubernetes.io/tags: IngressTag=my-ingress-service
```

Will tag the AWS target group with:

```
ServiceTag=my-tag-service
IngressTag=my-ingress-service
```

Current behaviour only tags ServiceTag.
I recommend if the same tag is found on both places that the service level overrides the value of the ingress (but only if it's the same tag).
