### ISSUE TITLE
[Question] Disable SG Rule creation on worker node SG

### ISSUE THREAD

**Issue by alexandrud** [kubernetes-sigs/aws-load-balancer-controller#2413]
Hi,

Is there a way to disable the creation of SG rules in the worker node security group?
![image](https://user-images.githubusercontent.com/2543941/145800060-a9677da2-14a4-49e6-9a59-d1f654a12128.png)
In the attached image we have 3 rules for 3 load balancers (that we added from terraform) plus all the highlighted rules that are added by the controller. We would like to tell the controller not to insert this security group rules anymore, if possible.

Our worker nodes sit in a private network and the only way to access ports is through load balancers. So what we do is create a sg rule for each load balancer and allow all ports between 30000-32767 for that source SG.

With  controller v2.3.0 we started getting CIDR rules for the IP blocks of the public networks which we don't want. This is causing AWS Inspector to say the ports are publicly accessible (although they're not).

**Comment by kishorj** [comment]
@alexandrud, we don't offer this capability for NLB. There is already a feature request #2358 we've scheduled for the v2.4.0 release.

**Comment by kishorj** [comment]
@alexandrud, since we already have a tracking issue for the v2.4.0 release feature, I'm closing this issue. Feel free to reopen if you have further concerns or put your comments in the issue #2358.
