### ISSUE TITLE
Creating Custom DNS using aws-load-balancer-controller

### ISSUE THREAD

**Issue by yashpotu** [kubernetes-sigs/aws-load-balancer-controller#2415]
**What am I trying to achieve?**
We have an app, that wants load balancer type :**External NLB.** We used aws-load-balancer controller to create this load balancer for us. It created a DNS something like this **k8s-xxxxxx-xxxxxxx-545656-345454**.elb.us-east-1.aws.com

**Describe the solution you'd like**
Is there any way I can customize this DNS to something like this Example:k8s-myappName-env.elb.us-east-1.aws.com

**Comment by M00nF1sh** [comment]
@yashpotu 
You can specify the NLB name via [annotation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#load-balancer-name). However, NLB will still automatically append other identifiers to the NLB name when generating the DNS name.

To get a fixed domain, you'll need to register your own domain name and setup alias records to point your domainName to the NLB's DNS.

**Comment by kishorj** [comment]
@yashpotu, I'm closing the issue. If you have further concerns, feel free to reopen the issue.
