### ISSUE TITLE
Fix Ingress API version in documentation example

### ISSUE THREAD

**Issue by Nuru** [kubernetes-sigs/aws-load-balancer-controller#2423]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/2e181b2cf31d41ce812deb18da629a5b0631144e/docs/guide/ingress/spec.md?plain=1#L30
```
apiVersion: extensions/v1
```

should be 
```
apiVersion: networking.k8s.io/v1
```

I do not want to sign the CLA and create a pull request. I hereby place this post in the public domain and invite any contributor to create a corresponding pull request.

**Comment by NIKU-SINGH** [comment]
Hey, I have created a PR resolving this [issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2429)

**Comment by M00nF1sh** [comment]
@NIKU-SINGH 
thanks so much for the PR to fixing this 😃
