### ISSUE TITLE
Fails to tag security group with default-tags

### ISSUE THREAD

**Issue by johngmyers** [kubernetes-sigs/aws-load-balancer-controller#2424]
**Describe the bug**

The controller is failing to tag the "k8s-traffic-*" security groups with the values specified in the `default-tags` flag.

**Steps to reproduce**

Run aws-alb-ingress-controller v2.3.1 with flags:

```
        - --cluster-name=k8s.redacted.cluster.domain
        - --enable-waf=false
        - --enable-wafv2=false
        - --enable-shield=false
        - --ingress-class=alb
        - --default-tags=KubernetesCluster=k8s.redacted.cluster.name
        - --aws-region=us-east-1
```

Create an `Ingress` with `kubernetes.io/ingress.class: alb` and `alb.ingress.kubernetes.io/scheme: internet-facing`.

**Expected outcome**

The `k8s-traffic-k8sredactedclustername-c066f345d7` security group to contain a `KubernetesCluster` tag with value `k8s.redacted.cluster.name`

**Environment**

* AWS Load Balancer controller version v2.3.1
* Kubernetes version 1.21.7
* Using EKS (yes/no), if so version? No

**Additional Context**:

**Comment by kishorj** [comment]
@johngmyers, thanks for reporting the issue. The controller currently doesn't apply default tags to the backend SGs, we will fix it in a patch release.

/kind bug
