### ISSUE TITLE
Update aws-load-balancer-controller ingress/spec to proper apiVersion values

### ISSUE THREAD

**Issue by todd-dsm** [kubernetes-sigs/aws-load-balancer-controller#2426]
This is a simple documentation update request. 

On the [Ingress specification] page the examples should reflect the appropriate `apiVersion` values:

* 1.19 and above: `extensions/v1 -> networking.k8s.io/v1` ?
* 1.18 and below: `apiVersion: extensions/v1beta1` seems okay?

**Steps to reproduce**
1. Open the [Ingress specification] page
2. Copy the "1.19 and above" example
3. Deploy it: ERROR

```shell
kubectl create -f addons/eks/ingress.yaml                                                                                                <aws:taos-personal-lab>
error: unable to recognize "addons/eks/ingress.yaml": no matches for kind "Ingress" in version "extensions/v1"
```

**Expected outcome**
An ALB is provisioned and directs traffic to the Ingress.

**Environment**

* AWS Load Balancer controller version: `aws-load-balancer-controller/v2.3/guide/ingress/spec/`
* Kubernetes version
  * Client Version: v1.23.0
  * Server Version: v1.21.2-eks-06eac09
* Using EKS (yes/no), if so version? yes (see above)

**Additional Context**:
NA

[Ingress specification]:https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/spec/

**Comment by M00nF1sh** [comment]
/kind documentation
we'll work to update all docs to latest api and  provide instructions per version
