### ISSUE TITLE
logging output command is broken on page; ez fix

### ISSUE THREAD

**Issue by todd-dsm** [kubernetes-sigs/aws-load-balancer-controller#2427]
**Describe the bug**
This line produces >1 pod and breaks as a result:
`kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o 'aws-load-balancer-controller[a-zA-Z0-9-]+')` 

Subsequently, `egrep` should not be used; it's generally an alias on newer systems to keep backward compatibility. Should use this instead: `grep -Eo...`

Something like this should work

`kubectl logs -n kube-system "$(kubectl get po -n kube-system | grep -Eo 'aws-load-balancer-controller[a-zA-Z0-9-]+' | tail -1)"                                                                                      `

**Steps to reproduce**

```shell
kubectl get po -n kube-system | grep -Eo 'aws-load-balancer-controller[a-zA-Z0-9-]+'
aws-load-balancer-controller-68d9d449b-2p92n
aws-load-balancer-controller-68d9d449b-t8626
```

**Expected outcome**
Logs for the found pod should be displayed in the Terminal.

**Environment**
* AWS Load Balancer controller version
* Kubernetes version: `v1.21.2-eks-06eac09`
* Using EKS (yes/no), if so version? above

**Additional Context**:

**Comment by oliviassss** [comment]
@todd-dsm I tried the command `kubectl logs -n kube-system "$(kubectl get po -n kube-system | grep -Eo 'aws-load-balancer-controller[a-zA-Z0-9-]+' | tail -1)`, it works on my side, I can see the logs output for the pod.
Can you please double check:
1. If your pods / deployment are running
2. If you have multiple pods, like 2 pods, 1 of them is standing by, and the other one will stream the logs for the controller. Please make sure you choose the right pod to get the logs.

**Comment by M00nF1sh** [comment]
@todd-dsm
Where do you see the command above? is it somewhere in our docs?

**Comment by kishorj** [comment]
@todd-dsm, I'm closing the issue for now. If you have further concerns regarding this matter, feel free to reopen or create a new issue.
