### ISSUE TITLE
Does ALB annotation support URL rewrite?

### ISSUE THREAD

**Issue by rudian** [kubernetes-sigs/aws-load-balancer-controller#2428]
I have set up an ingress with a custom path, it happened 404 issues.

here's my deployment YAML file
[https://drive.google.com/file/d/1Q2McLDDf9bc0zipwA3yZwMJroOIPDhHp/view?fbclid=IwAR0fbT3Opizd1RFI4dTfBcm_SLGod_cSQxuu__JgozoUxT6mI-wnSsdutEY](url)

**Comment by oliviassss** [comment]
@rudian Hi I couldn't open the link. Can you please send the yaml file to k8s-alb-controller-triage AT amazon.com? It would be good if you can also share the logs / error message. Thanks.

**Comment by M00nF1sh** [comment]
@rudian 
we don't support URLRewrite. ALB itself currently don't support such feature yet

**Comment by kishorj** [comment]
This requires support from the ALB side. Feature request #1571 to track this issue.

**Comment by irfn** [comment]
what sort of an ingress controller doesn't support a path rewrite.
