### ISSUE TITLE
Auto-discovery of VPC

### ISSUE THREAD

**Issue by olemarkus** [kubernetes-sigs/aws-load-balancer-controller#2430]
**Is your feature request related to a problem?**
When deploying a cluster with LBC through IaC, it is not that easy to inject the VPC ID into the LBC Deployment resource. That is, however, necessary when LBC runs with IRSA and with metadata is unavailable.

**Describe the solution you'd like**
It would be nice if VPC could be discovered through tags the same way subnets are.

**Comment by M00nF1sh** [comment]
/kind feature
we have been think about new ways to discover vpc, clusterName.
One possible way is to use the labels on nodes where the controller run

**Comment by olemarkus** [comment]
There are no labels for this information today, but I could definitely help out adding at least a VPC label through Cloud Controller Manager.

cluster name is less of a problem since we do know that up front.

**Comment by M00nF1sh** [comment]
we could get the region from the zone label possibly, and then find the vpcID by the instanceID of node(spec.providerID).
and hopefully we can get the clusterName from the tags on instance as well.

on the other hand, using tags on the vpc is also a good idea.

We'll evaluate which one is better.

**Comment by kishorj** [comment]
@olemarkus, we could get the Node resource, extract the providerID and invoke the ec2 `DescribeInstances` API to get the VPC id. The controller already has permissions to access the Node resources from k8s, and IAM permissions for the `DescribeInstances` call and would not depend on the CCM putting the appropriate label.

**Comment by olemarkus** [comment]
That sounds good to me.

**Comment by olemarkus** [comment]
@M00nF1sh @kishorj any update on this?

/remove-lifecycle stale
