### ISSUE TITLE
Json policy document improving

### ISSUE THREAD

**Issue by doctornkz** [kubernetes-sigs/aws-load-balancer-controller#2438]
Hello everyone! 

For a sake of consistency we can improve our AWS policy JSON document:

Instead of https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/e7bc45885e052b6734056fea7497bdfd2fb46e81/docs/install/iam_policy.json#L6 

```
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:AWSServiceName": "elasticloadbalancing.amazonaws.com"
                }
            }
        },

```
we can use :
```
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateServiceLinkedRole"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:AWSServiceName": "elasticloadbalancing.amazonaws.com"
                }
            }
        },
```
We are using this syntax here already : https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json#L77

It will help us with avoiding extra `if` string/list statements during JSON parsing. 

Thank you for your time!

**Comment by kishorj** [comment]
@doctornkz, thanks for letting us know. Feel free to raise a PR with the changes.

/kind feature
