### ISSUE TITLE
Change CLB to ALB

### ISSUE THREAD

**Issue by akshay-bharatdwaj** [kubernetes-sigs/aws-load-balancer-controller#2440]
Hi Team, 

Ee are using ingress-controller version of this repo in our project that creates a classic load balancers by default 

  annotations:
    {{/* The hostname should match the CN of the certificate */}}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.dnsHostname | quote }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.service.sslCert }}"

    {{- if .Values.service.securityGroups }}
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: {{ .Values.service.securityGroups | quote }}
    {{- end }}

    {{- if .Values.service.internal }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    {{- end }}
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics-exporter/metrics
    prometheus.io/port: "8180"

but we have a requirement to change the classic load balancer to application load balancer.
Could you please suggest how it can be done.

please find app details below :
appVersion: v1.1.6
description: A Helm chart for AWS ALB Ingress Controller
engine: gotpl
home:https://github.com/kubernetes-sigs/aws-alb-ingress-controller

**Comment by kishorj** [comment]
@akshay-bharatdwaj, you might have use service of type LoadBalancer to provision an AWS CLB before, and the load balancer got provisioned by the kubernetes kube-controller-manager. This controller has not supported CLB.

If you want to provision an ALB, you'd need to create an ingress resource instead. The ingess resource would use your kubernetes service for backend traffic - convention is to use sevice type of NodePort for instance targets or ClusterIP for IP targets.

**Comment by kishorj** [comment]
@akshay-bharatdwaj, did my previous response help solve your problem? I'm closing the issue for now, if you have further concerns regarding this matter, feel free to reopen or create a new issue.
