### ISSUE TITLE
kubernetes api-version should not be hard coded

### ISSUE THREAD

**Issue by burkempers** [kubernetes-sigs/aws-load-balancer-controller#2441]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/e7bc45885e052b6734056fea7497bdfd2fb46e81/controllers/ingress/group_controller.go#L39

I am running k8s version 1.22.  K8s 1.22 deprecated many v1beta1 api versions including "ingress" and "ingressClass".  With this line being hard coded it doesnt not allow for the k8s cluster to be upgraded.

**Comment by burkempers** [comment]
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by johngmyers** [comment]
API versions need to be hard-coded. Otherwise, how would the code know how to format or parse the data being sent over the API?

**Comment by burkempers** [comment]
Query k8s api-version to get a list of available api versions to then pass one of those values down into this method instead of hard coding.  The code might have to have different methods for any api version.

**Comment by johngmyers** [comment]
One would still need to hard-code a list of API versions that the code understands.

**Comment by burkempers** [comment]
Correct.  if there is a breaking change between the api versions.  if the api version is just getting upped to be an official version then there shouldnt have to be any code change.

**Comment by kishorj** [comment]
We've recently merged PR #2433 which migrates to ingress api version networking.k8s.io/v1. This enables the controller to support k8s 1.22 and later versions.

**Comment by kishorj** [comment]
@burkempers, I'm closing the issue for now. If you have further concerns, feel free to reopen or create a new issue.
