### ISSUE TITLE
Controller cannot recover from TooManyCertificates ALB error

### ISSUE THREAD

**Issue by mkozal** [kubernetes-sigs/aws-load-balancer-controller#2449]
**Describe the bug**
Since ALB allows multiple certificates per single listener that feature seen some use from me (using group.name). Unfortunately in deployment frenzy we've hit the limit and crossed 25/26 certificates limit. That resulted in errors so we started removing ingress resources but controller cannot really recover on its own.

**Steps to reproduce**
Deploy an ALB with single listener, default certificate and 25 additional certificates. Try adding one more ingress resource, wait for TooManyCertificates fail, try to remove some ingress entries.

**Expected outcome**
When ingress is removed finalizer automagically takes care of (i.e. removes) related AWS resources (cert, target group, listener rule etc.) and garbage collects an ingress afterwards.

**Environment**
* AWS Load Balancer controller version: v2.3.1
* Kubernetes version v1.21.2-eks-0389ca3
* Using EKS (yes/no), if so version? Yes.

**Additional Context**:
Original error is obviously that one
```"level":"error","ts":1641567239.1484585,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"internal","namespace":"","error":"TooManyCertificates: The maximum number of certificates has been reached\n\tstatus code: 400, ```

Model gets created successfully so I'm hoping no syntax errors on my side, especially since all the creation and so on happened perfectly fine (also: confirmed in next paragraph). My suspicion is that controller after building the model wants to handle all creations first (which "were"/are pending) and that involves certificate attachment while the cleanup would happen afterwards. Naturally we don't even arrive at this stage since limit is hit when adding cert to the listener.

This is somewhat confirmed with manual certificate removal from the listener: I had 26 total (25 extras and 1 default), removed 3 extras, then controller was able to add "pending" three that failed beforehand and immediately started to garbage collect the ones that were issued `delete ingress` earlier but were stuck due to TooManyCertificates API error. Both k8s ingresses as well as actual AWS resources get removed and everyone's happy.

Other Ingress groups don't get affected fortunately so only the one at the limit is hit.

**Comment by M00nF1sh** [comment]
@mkozal 
If you deleted an Ingress resource within a Group, then that Ingress's certificate won't be included.
Is it possible that your existing alive Ingresses still have certificate that exceed the 26 limit? (we can confirm it from the model been built from the logs)

**Comment by panaut0lordv** [comment]
Yes, I am 99% sure that model indeed did not include the "deleted" (i.e. finalizing) certificates in it. But still, even with correct (=<26 certs) build if there were ones that didn't exist beforehand it tried attaching them before cleaning up finalized, hence the issue. We since took a bit different approach to communication so I cannot provide you with any fresh logs but if you fail to replicate such case on your side I'll try to setup test bench.

Cheers!

**Comment by oliviassss** [comment]
@panaut0lordv Hi I was trying to repro the issue you're faced with, but no luck yet. This is how I did:

- Created an ingressA with 26 certificates (1 default and 25 extra, specified by annotations) within an ingress group, which reconciled successfully
- Tried to create an ingressB with 2 certificates (1 in common as in ingressA) within the same ingress group, which triggered the _TooManyCertificates_ error, and the controller stuck in the creation of ingressB
- Delete the ingressA by `kubectl delete ingressA`

From the controller logs, I can see the controller removed all the certificates of ingressA first and then continued to created ingressB successfully, so in my case the controller recovered from the _TooManyCertificates_ error.

Can you please double check if the ingress you are trying to create hit the certificate itself, or there exists other alive ingress that hit the limit? You can also send the logs around when your controller gets stuck in to our inbox for further investigation: k8s-alb-controller-triage AT amazon.com

**Comment by oliviassss** [comment]
Tried this case and was  able to reproduce this issue:

- Ingress A with more than 26 certs (so it fails reconcile in the first place)
- IngressB with additional certs
- Then try to edit ingress A to be under limit

I think the problem might be when the controller has TooManyCertificates error, `kube edit ingress` does not work as expected, it failed to remove the certificates. Checking the code base for root cause.

**Comment by oliviassss** [comment]
The root cause is that currently the controller adds new certificates before deleting undesired certificates, so when the controller is having TooManyCertificates error, if we just edit the ingress instead of deleting the ingress, the controller cannot recover. Will raise a PR for the fix.

**Comment by kishorj** [comment]
Fixed in v2.4.1 patch release. Closing the issue.
