### ISSUE TITLE
File 2048_full_latest.yaml doesn't exist

### ISSUE THREAD

**Issue by fibert** [kubernetes-sigs/aws-load-balancer-controller#2455]
**Describe the bug**
When doing this workshop, at Beginner > Exposing a Service > Ingress Controller > [Deploy Sample Application](https://www.eksworkshop.com/beginner/130_exposing-service/ingress_controller_alb/#deploy-sample-application) When running the given command:

```
export EKS_CLUSTER_VERSION=$(aws eks describe-cluster --name eksworkshop-eksctl --query cluster.version --output text)

if [ "`echo "${EKS_CLUSTER_VERSION} < 1.19" | bc`" -eq 1 ]; then     
    curl -s https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/examples/2048/2048_full.yaml \
    | sed 's=alb.ingress.kubernetes.io/target-type: ip=alb.ingress.kubernetes.io/target-type: instance=g' \
    | kubectl apply -f -
fi

if [ "`echo "${EKS_CLUSTER_VERSION} >= 1.19" | bc`" -eq 1 ]; then     
    curl -s https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/examples/2048/2048_full_latest.yaml \
    | sed 's=alb.ingress.kubernetes.io/target-type: ip=alb.ingress.kubernetes.io/target-type: instance=g' \
    | kubectl apply -f -
fi
```

`https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/examples/2048/2048_full_latest.yaml` returns 404.

To overcome this, I used the url `
https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.1/docs/examples/2048/2048_full_latest.yaml` instead (notice I replaced `main` with `v2.3.1` here)

**Comment by M00nF1sh** [comment]
@fibert 
Think for reporting this, we'll update workshop page with the tagged URL.

/assign kishorj
