### ISSUE TITLE
How to configure CORS in AWS Loadbalancer ingress controller

### ISSUE THREAD

**Issue by kvnreddy6680** [kubernetes-sigs/aws-load-balancer-controller#2456]
**Describe the bug**
Need to configure options http method  in AWS loadbalancer controller for CORS

**Steps to reproduce**

**Expected outcome**
Need to configure options http method  in AWS loadbalancer controller for CORS

**Environment**

* AWS Load Balancer controller version :2.2
* Kubernetes version:1.19
* Using EKS (yes/no), Yes

**Additional Context**:

**Comment by M00nF1sh** [comment]
ALB itself currently don't support CORS natively(we cannot modify the request/response from backend).
You'll need to handle CORS requests in your application. 

By default, the Ingress rule applies for all HTTP methods, but if you want a specific rule for OPTIONS request only, you can refer examples of our  `alb.ingress.kubernetes.io/conditions.${conditions-name}` annotation

**Comment by kishorj** [comment]
@kvnreddy6680, did the response from @M00nF1sh help solve your problem?

**Comment by kishorj** [comment]
@kvnreddy6680 I'm closing the issue. If you have further concerns, feel free to reopen or create a new issue.

**Comment by sukki37** [comment]
> ALB itself currently don't support CORS natively(we cannot modify the request/response from backend). You'll need to handle CORS requests in your application.
> 
> By default, the Ingress rule applies for all HTTP methods, but if you want a specific rule for OPTIONS request only, you can refer examples of our `alb.ingress.kubernetes.io/conditions.${conditions-name}` annotation

Hi, sorry to bother u, the problem I'm having is that it seems that ingress is intercepting all cross-domain requests, and the back-end service is not receiving them at all. Could u give me some advice on this?
