### ISSUE TITLE
security-groups annotation attachment not working

### ISSUE THREAD

**Issue by antigenius0910** [kubernetes-sigs/aws-load-balancer-controller#2457]
**Describe the bug**
I have my aws-loadbalancer-controller create with follow arg
```
  - args:
    - --cluster-name=XXXX
    - --ingress-class=alb
    - --disable-restricted-sg-rules=true
```
based on documentation here. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#security-groups

when I add annotation 
```
  annotations:
    alb.ingress.kubernetes.io/security-groups: sg-0248f7f1feed2xxxx
```
then this particular security group should be attach to my loadbalancer, however, a new security group has been created
```
ᐅ aws --profile=xxxx-staging elb describe-load-balancers --load-balancer-names ab6d68f8da95d499e9048758743fce76 | grep -A2 SecurityGroups
            "SecurityGroups": [
                "sg-09062ba8f62540221"
            ],
```

**Steps to reproduce**
```
ᐅ kubectl apply -f allowed_example.yaml

apiVersion: v1
kind: Service
metadata:
  name: example-service
  annotations:
    alb.ingress.kubernetes.io/security-groups: sg-0248f7f1feed2xxxx
spec:
  selector:
    app: example
  ports:
    - port: 1111
      targetPort: 1111
  type: LoadBalancer
```

```
Name:                     example-service
Namespace:                default
Labels:                   <none>
Annotations:              alb.ingress.kubernetes.io/security-groups: sg-0248f7f1feed2xxxx
Selector:                 app=example
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       172.20.234.196
IPs:                      172.20.234.196
LoadBalancer Ingress:     ab6d68f8da95d499e9048758743fce76-573891456.us-east-2.elb.amazonaws.com
Port:                     <unset>  1111/TCP
TargetPort:               1111/TCP
NodePort:                 <unset>  30359/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  28m   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   28m   service-controller  Ensured load balancer

```

```
ᐅ aws --profile=xxxx-staging elb describe-load-balancers --load-balancer-names ab6d68f8da95d499e9048758743fce76 | grep -A2 SecurityGroups
            "SecurityGroups": [
                "sg-09062ba8f62540221"
            ],
```

**Expected outcome**
existing security group "sg-0248f7f1feed2xxxx" should be attach to my new loadbalancer instead of creating a new "sg-09062ba8f62540221"

**Environment**

* AWS Load Balancer controller version
v2.3.0
* Kubernetes version
ᐅ kubectl version
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by oliviassss** [comment]
@antigenius0910 Hi, from the YAML, you are actually creating a NLB, but this annotation `alb.ingress.kubernetes.io/security-groups` is an annotation for ALB. Right now we do not support the security-group annotation for NLB. Please refer to our [live doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/) for the annotations supported for NLB.

**Comment by oliviassss** [comment]
@antigenius0910 from the Yaml, you are actually creating a CLB, but this annotation `alb.ingress.kubernetes.io/security-groups` is an annotation for ALB. To attach security groups to a CLB you should use `service.beta.kubernetes.io/aws-load-balancer-security-groups`. 

Please note, the service is managed by kubernetes in-built controller, not AWS LB controller. For more info, please refer to this [link](https://kubernetes.io/docs/concepts/services-networking/service/).

**Comment by antigenius0910** [comment]
@oliviassss ,

thank you for the detail explaining. closing this issue now
