### ISSUE TITLE
ALB ingress controller v1.1.9 sometime didn't register and de-register the target.

### ISSUE THREAD

**Issue by khushboo121** [kubernetes-sigs/aws-load-balancer-controller#2459]
Recently found ALB ingress controller sometimes doesn't register and de-register target when there is the new deployment of the application running behind the ALB ingress. Faced this issue with both target type instance and ip.

When rollout the application deployment which was exposed with ALB ingress, we started seeing 502 gateway errors after an investigation found the ALB target group doesn't have a healthy target available.
Checked the ALB ingress controller pod logs, found that there is no "Reconciled" msg available the that ALB. Manual de-registration and registration is working find so restarted the ALB ingress controller pod and again upgraded the application and again healthy targets are not getting registered.
In end to avoid the 502 error deployed new ALB ingress their registration and de-registration is working. 

**Environment**: Test

* AWS Load Balancer controller version : v1.1.9
AWS ALB Ingress controller
  Release:    v1.1.9
  Build:      6c19d2fb
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version: EKS 1.20.11

**Additional Context**:

**Comment by M00nF1sh** [comment]
@khushboo121 
Do you have the controller logs available? also, would you mind share your cluster arn and the timestamp when the deployment happen to `k8s-alb-controller-triage AT amazon.com.`

**Comment by khushboo121** [comment]
Following is the required annotation when using instance type ?
alb.ingress.kubernetes.io/target-node-labels: label1=value1, label2=value2

**Comment by kishorj** [comment]
@khushboo121, the annotation `alb.ingress.kubernetes.io/target-node-labels` is supported starting controller release v2.2.0 and if you specify this annotation helps you filter the worker nodes to register to the load balancer target group. If you do not specify the annotation, all worker nodes get registered.

In case of controller version v1.1.9, the above annotation gets ignored.

**Comment by DIG-TE** [comment]
Running into a similar problem with the latest image on master (2.4.0)
Running K8s 1.22, hosting using kubeadm
Target groups are not registering the worker nodes for some reason

**Comment by kishorj** [comment]
@DIG-TE, would you be able to share the controller logs with us and the event timeline? Would it be possible for your worker nodes to be in NotReady state? What CNI plugin do you use?

**Comment by khushboo121** [comment]
Recently we have enabled the wafv2 feature and the ALB controller doesn't have permission to "wafv2:GetWebACL on resource" so in the next service deployment target got updated and ALB-ingress-controller is not able to reconcile new targets.
Once permission is updated ALB ingress controller is able to Reconciler new targets.
