### ISSUE TITLE
Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1beta1-ingress?timeout=10s":  context deadline exceeded

### ISSUE THREAD

**Issue by llacoste** [kubernetes-sigs/aws-load-balancer-controller#2460]
**Describe the bug**
After installing the aws-load-balancer-controller via Helm by following the instructions [here](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html), I am getting the following error:

`
Error from server (InternalError): 
error when creating "<REDACTED | Link to minimal ingress is below in reproduction steps>": 
Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": 
Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1beta1-ingress?timeout=10s": 
context deadline exceeded
`

**Steps to reproduce**

1. Provision an EKS cluster with [the AWS EKS Terraform module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest)
2. Install aws-load-balancer-controller via helm as described [here](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html)
3. Attempt to create any ingress resource, such as [this one](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/minimal-ingress.yaml)

It should be noted that if I remove the aws-load-balancer-controller, I can create the minimal ingress just fine.

**Expected outcome**
To be able to create an ALB ingress resource that will have its state reflected in AWS.

**Environment**

* AWS Load Balancer controller version - `2.3.1`
* Kubernetes version - `1.21`
* Using EKS (yes/no), if so version? - `yes eks.4`

**Additional Context**:

- The permissions for the controller are granted via IAM Roles on the instances themselves, rather than via a service account.
- I have other clusters that are working. I started having trouble once I upgraded [the AWS EKS terraform module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest) from version `11` to version `18`.

Any help would be greatly appreciated! I've been digging into this for some time and cannot seem to figure out why I am having this problem.

**Comment by manoelhc** [comment]
facing the very same issue

**Comment by kishorj** [comment]
@llacoste, are the controller pods up and running?

**Comment by llacoste** [comment]
@kishorj, they are up and running. The logs contain no errors.

**Comment by manoelhc** [comment]
I'm facing the same issue too. The pods are up, running and reachable from other pods.  
Nothing in the logs as well. My alb controller in a private subnet btw.

**Comment by llacoste** [comment]
Incidentally, I just tried this with my original terraform code (which is using the AWS EKS terraform module at version 11) and I am having the same issue. This is odd because I have clusters built with identical code that is working.

**Comment by manoelhc** [comment]
It seems it's not reaching the service, that's why logs are clear. Perhaps something in the middle is preventing the access to the API like insecure cert, idk.

**Comment by kishorj** [comment]
which CNI do you use? Amazon VPC CNI or Calico or something else?

**Comment by llacoste** [comment]
I would assume Amazon VPC CNI, as I did not install Calico. Then again, I did not explicitly configure the Amazon VPC CNI either.

**Comment by llacoste** [comment]
@kishorj After reviewing the resulting cluster, it seems that the automation is using [amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s) based on the custom resources, service accounts, and pods running in the cluster. For example I can see `aws-node` pods running. I do not see any reference to Calico in the cluster.

**Comment by manoelhc** [comment]
I found the issue for my case. I enabled the VPC Flow Logs and I noticed the security groups created by the `terraform-aws-modules` module block the connection between pods from different node groups (which is my case).

**Comment by llacoste** [comment]
@manoelhc You're a godsend. Thank you @kishorj as well! I did not have multiple node groups, but after checking the security groups on the worker nodes I saw that the nodes could not talk to one another. Going to fix the automation now and move on to the next thing.

Thanks again!

**Comment by ashish3dwe** [comment]
> @manoelhc You're a godsend. Thank you @kishorj as well! I did not have multiple node groups, but after checking the security groups on the worker nodes I saw that the nodes could not talk to one another. Going to fix the automation now and move on to the next thing.
> 
> Thanks again!

Hi, I am stuck at exactly this point for a few days now. Can you please share how to modify the security groups via terraform?

**Comment by ashish3dwe** [comment]
> > @manoelhc You're a godsend. Thank you @kishorj as well! I did not have multiple node groups, but after checking the security groups on the worker nodes I saw that the nodes could not talk to one another. Going to fix the automation now and move on to the next thing.
> > Thanks again!
> 
> Hi, I am stuck at exactly this point for a few days now. Can you please share how to modify the security groups via terraform?

Never mind, got it, thanks. I added a couple of "aws_security_group_rule" to allow communication on port 9443 between node group and cluster security groups. Works well now.

**Comment by llacoste** [comment]
Hey @ashish3dwe, sorry for the delay. I added an entry to ` node_security_group_additional_rules`. This option is part of the terraform parameters for the EKS module.

**Comment by GrigorievNick** [comment]
Hi, I get the exact same issue.
but I don't which SG cause this error.
I can see that by default `aws-eks-module` allow ingress and egress traffic between [control-plane](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L62) and [Node](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L80) by 443 port.
Do I need open something else except 443?

**Comment by ashish3dwe** [comment]
> Hi, I get the exact same issue, but I don't which SG cause this error. I can see that by default `aws-eks-module` allow ingress and egress traffic between [control-plane](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L62) and [Node](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L80) by 443 port. Do I need to open something else except 443?

Hi @GrigorievNick , you need to open 9443. This is the webhook-bind-port used by the aws-load-balancer-controller. See here for reference - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/configurations/

**Comment by practical-gitops** [comment]
This resolved my issue hope it helps others https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2462#issuecomment-1031624085

**Comment by davidvuong** [comment]
Also having this issue, along with a few others but this explains the connectivity problem and provides a solution.

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md
