### ISSUE TITLE
Transient error: [this should never happen] no primary ENI found

### ISSUE THREAD

**Issue by poblahblahblah** [kubernetes-sigs/aws-load-balancer-controller#2461]
**Describe the bug**
We haven't actually noticed any issues with this error, but we've seen it pop up occasionally

```
[this should never happen] no primary ENI found
```

**Steps to reproduce**

Not sure - we see this about ~15 times every day across our fleet for K8s clusters.

**Expected outcome**

Again, we're not seeing any actual issues. The error appears to be transient, but we see it often enough that I figured it would be worth it to open a ticket.

**Environment**

* AWS Load Balancer controller version
2.2.4

* Kubernetes version
1.21

* Using EKS (yes/no), if so version?
Yes, 1.21

**Additional Context**:

**Comment by kishorj** [comment]
@poblahblahblah, thanks for reporting the issue. Would you also be able to email the controller logs to k8s-alb-controller-triage AT amazon.com?

**Comment by kishorj** [comment]
@poblahblahblah, what instance type do you use? Per the aws documentation the eni Attachment device index is 0 for the first (primary) interface. I'm uncertain whether it is due to CNI or instance type in your case. Would you be able to email further details to us, we will take a look?

**Comment by poblahblahblah** [comment]
Sorry for the silence - was on PTO for the past few weeks.

I'll get this to you tomorrow.

**Comment by kishorj** [comment]
@poblahblahblah, any updates?

**Comment by kishorj** [comment]
@poblahblahblah, I'm closing the issue. If you have further updates, concerns feel free to reopen or create a new issue.
