### ISSUE TITLE
ALB Ingress is not getting created

### ISSUE THREAD

**Issue by boopathykpm** [kubernetes-sigs/aws-load-balancer-controller#2462]
Installed the ALB ingress on the EKS cluster, the chart got installed successfully, the issue is when creating the ingress of the application. I'm trying to install the sample app 2048, when doing so I'm getting error as below 

```
Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1beta1-ingress?timeout=10s": context deadline exceeded
```

I guess the IngressClass is not validating properly. 

* AWS Load Balancer controller version (v2.3.1)
* Kubernetes version (1.21)
* Using EKS (yes/no), if so version? yes (1.21)

**Comment by kishorj** [comment]
@boopathykpm, error indicates that the k8s controlplane is not able to connect to the aws-load-balancer-controller pods running on your worker nodes. Could you ensure the cluster security group allows traffic between the k8s controlplane and the worker nodes? Please refer to issue #2460, the symptoms are the same.

**Comment by boopathykpm** [comment]
@kishorj Thanks for the update, It would be great if this information is captured in the documentation, I don't see this information anywhere in the documentation.

**Comment by kishorj** [comment]
@boopathykpm, what does your cluster create workflow look like? Did you use eksctl, or the aws clis, or some other tools.

**Comment by boopathykpm** [comment]
@kishorj Cluster is created using the Terraform [EKS](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest) module.

**Comment by boopathykpm** [comment]
@gitmaniak This is fixed, the reason for the failure is the service port number is not opened in the node security group.  This piece of information is not captured anywhere in the documentation.

**Comment by gitmaniak** [comment]
@boopathykpm yeah, I am currently working on a requirement and what I posted above was wrong. if I enable this flag (wait_for_load_balancer = true), that is when the above mentioned POST call happens and my pod might not have 9443 port open. If I do not use that flag, the ingress gets created but the following steps need to have some other alternative to wait till the load balancer endpoint is available.

I am using terraform EKS module. The node security group creation is handled internally. Could you help me on how to enable custom ports when using terraform eks module?

**Comment by arvryna** [comment]
hello, is this issue sorted ? i saw label - good-first-issue. would like to take it up, if it is open

**Comment by kishorj** [comment]
@arvryna, thanks for your interest, feel free to contribute to this issue.

/assign arvryna

**Comment by arvryna** [comment]
I'm new to this project, could you help me to get started with this issue ?

    Little bit background about the existing behaviour & expected behaviour
    What needs to be done as part of this issue?
    After making changes, how can I test it and verify?

**Comment by GrigorievNick** [comment]
HI @kishorj ,
I have same issue and I am 100% sure it's related to security group configuration like you described.
> @boopathykpm, error indicates that the k8s controlplane is not able to connect to the aws-load-balancer-controller pods running on your worker nodes. Could you ensure the cluster security group allows traffic between the k8s controlplane and the worker nodes? Please refer to issue #2460, the symptoms are the same.

but what I miss, is do I need to open all ports from the control-plane to my Nodes or I can open only 443 port?

**Comment by kishorj** [comment]
@GrigorievNick, for aws lb controller, you'd need to allow port 9443 for webhook access. Other application components might have different requirements, you'd need to figure out the optimum configuration based on your security requirements.

**Comment by DZDomi** [comment]
For people are stumbling on this after upgrading the aws terraform eks module to version `18.x`, the required configuration for the module to work with the load balancer controller is:

```
node_security_group_additional_rules = {
  ...
  ingress_allow_access_from_control_plane = {
    type                          = "ingress"
    protocol                      = "tcp"
    from_port                     = 9443
    to_port                       = 9443
    source_cluster_security_group = true
    description                   = "Allow access from control plane to webhook port of AWS load balancer controller "
  }
}
```

**Comment by ohookins** [comment]
Seems like it's also related to #2289

**Comment by kishorj** [comment]
documentation added in PR #2506

**Comment by alexvaque** [comment]
> node_security_group_additional_rules

after checking, investigating and reading this thread , I saw your comment and your solution works! thanks for sharing the Terraform code as well :)

**Comment by kuboraam** [comment]
wow, 4 hours on this and finally got it to work. Thanks @DZDomi! You're a life saver. It would be nice if they can add this security group as part of the "complete" example somewhere on the module page or [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf).

**Comment by simplicbe** [comment]
Important, a very similar message might occurs, when the aws certificate is not approved yet.
