### ISSUE TITLE
Auto-discover subnet is failing on a cluster

### ISSUE THREAD

**Issue by boopathykpm** [kubernetes-sigs/aws-load-balancer-controller#2463]
Hi, 

Facing an issue when creating the ingress for the ALB, the below is the error message I'm getting 

```
Failed build model due to couldn't auto-discover subnets: NoCredentialProviders: no valid providers in chain. Deprecated.
           For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

I had created the [policy](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.1/docs/install/iam_policy.json) and attached it to the node group role.  The subnets are tagged with `kubernetes.io/role/elb` key.  Still facing the issue. 

* AWS Load Balancer controller version v2.3.1
* Kubernetes version - v1.20.14
* Using EKS (yes/no), if so version? no ( created with kops)

**Comment by kishorj** [comment]
@boopathykpm, can you check whether IMDSv1 is disabled on your setup? The IMDSv2 isn't accessible from the container unless you configure the hop-limit to at least 2.

**Comment by kishorj** [comment]
If you use kops, make sure the hop limit is at least 2, for example

kops edit ig --name=$NAMAE nodes-<az>

```
  instanceMetadata:
    httpPutResponseHopLimit: 2
    httpTokens: required

```

and update your cluster

**Comment by kishorj** [comment]
closing the issue. If problem persists, or you have further concerns, feel free to reopen or create a new issue.
