### ISSUE TITLE
controller v2.3.1 giving ApiVersion deprecation warnings in EKS v1.21

### ISSUE THREAD

**Issue by oguzhanaygn** [kubernetes-sigs/aws-load-balancer-controller#2464]
Hi,

I created an EKS 1.21 cluster and I deployed aws load balancer controller onto it, I haven't create an Ingress or IngressClass yet, but in the aws-load-balancer-controller pod logs I saw,
```
{"level":"info","ts":1642595827.5104892,"logger":"KubeAPIWarningLogger","msg":"networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress"}
{"level":"info","ts":1642595827.5168498,"logger":"KubeAPIWarningLogger","msg":"networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList"}
```
I know about this deprecation and I will create my Ingress resources with networking.k8s.io/v1 ApiVersion, but as I said, I didn't create any Ingress resource yet. it seems controller itself using this ApiVersions and it's giving warning, is it expected behaviour or is it some sort of a bug?

Any help/explanation will be highly appreciated,
Thank you.

My server and client versions ;

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

Controller version:
v2.3.1

**Comment by kishorj** [comment]
@oguzhanaygn, thanks for reporting the issue. We plan to address it in the upcoming v2.4.0 release. Please refer to issue #2050 for further details.

**Comment by kishorj** [comment]
@oguzhanaygn, I'm closing this issue since we will support it in v2.4.0 release and we already have an issue to keep track of.
