### ISSUE TITLE
Question: Can we have ALB/NLB in one vpc and EKS cluster in other like Azure Application Gateway ingress controller ?

### ISSUE THREAD

**Issue by niteenkole** [kubernetes-sigs/aws-load-balancer-controller#2465]
**Is your feature request related to a problem?**
say if we have centralized ingress security VPC with firewall now in that security VPC we don't want to put any compute. Its like hub and spoke model. Now in spoke we can have ec2 ,eks.... spoke is tied to TGW and all .

ingress point is security VPC.

**Describe the solution you'd like**
Can we have ALB/NLB in security VPC and eks private in spoke vpc ?

Kind of like Azure:
Application Gateway ingress controller like Azure. Where you can expose your Kubernetes application (one vnet) in an existing AKS cluster through an existing Application Gateway deployed in separate virtual networks ?
https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json

I am new to EKS tried to search all documents to see if this can be done but not able to trace.

**Comment by M00nF1sh** [comment]
@niteenkole 
It's possible with v2.3.1 release. (PR: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1862)

You can either use the TargetGroupBinding resource to bind to a TargetGroup in another VPC.
or configure the controller to have another vpc's id.

**Comment by niteenkole** [comment]
Awesome. Thank You

**Comment by kishorj** [comment]
@niteenkole, I'm closing the issue. If you have further concerns, feel free to reopen or create a new issue.
