### ISSUE TITLE
--cloud-provider Deprecation and Node registration

### ISSUE THREAD

**Issue by matt-TE** [kubernetes-sigs/aws-load-balancer-controller#2468]
**Is your feature request related to a problem?**
Now that the cloud-provider flag is deprecated, I need a way for nodes to have ProviderID added so that nodes can be registered to target groups.

**Describe the solution you'd like**
The controller auto-discovers worker nodes for pods that are running for services defined in the Ingress file

**Describe alternatives you've considered**
I'm unsure of alternatives at this time

**Comment by kishorj** [comment]
@matt-TE, could you elaborate more in this? Node resources would always have ProviderID added regardless of the `cloud-provider` flag.

**Comment by matt-TE** [comment]
@kishorj for sure!

For context: I am currently upgrading a K8s cluster from 1.18.8 to 1.22.5.

As part of the upgrade to 1.22.5, Kubelet has deprecated the --cloud-provider flag, with it being fully removed in 1.23+

So, right now, yes, using --cloud-provider=aws as an extra arg for Kubelet works, but we will not be able to upgrade to 1.23.

When I remove the --cloud-provider extra arg, a ProviderId does not get assigned to my nodes, and I noticed the aws-load-balancer-controller looks for ProviderId when trying to register nodes to TargetGroups, and it fails.

I was running an image built off master from ~ 2 weeks ago since running the default v2.3.1 does not work with 1.22.5.

**Comment by kishorj** [comment]
@matt-TE  Once the --cloud-provider flag is not available, you'd need to configure external CCM. Please follow the following guide to setup AWS cloud provider - https://github.com/kubernetes/cloud-provider-aws/blob/master/docs/getting_started.md
