### ISSUE TITLE
1.3.4 not found

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/aws-load-balancer-controller#2469]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/Chart.yaml#L4

this line says 1.3.4 but only `--version 1.3.3` works

**Comment by kishorj** [comment]
@matti, we haven't synced the latest chart to the eks-charts repo. 1.3.3 is still the latest released chart - https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/Chart.yaml#L4.

**Comment by matti** [comment]
that is super confusing

**Comment by kishorj** [comment]
@matti, were there any changes in 1.3.4 that you were interested in? We are delaying the chart release until v2.4.0, unless there are critical fixes.

**Comment by matti** [comment]
no, just got confused

**Comment by kishorj** [comment]
We sync to eks charts periodically. The 1.3.4 is an exception since we want to wait for the upcoming v2.4.0 release. This repo contains the latest code. For stable releases, please refer to the charts from the eks-charts repository as mentioned in the installation steps.

I'm closing this issue.
