### ISSUE TITLE
keepTLSSecret should be true by default

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/aws-load-balancer-controller#2473]
running helm upgrade twice without `keepTLSSecret: true` results in

>"error":"Internal error occurred: failed calling webhook \"mtargetgroupbinding.elbv2.k8s.aws\": Post \"https://aws-load-balancer-webhook-service.aws-load-balancer-controller-1.svc:443/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"aws-load-balancer-controller-ca\")"}

found this from https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2071#issuecomment-998655678

**Comment by kishorj** [comment]
/kind feature
we will consider it for future chart releases
