### ISSUE TITLE
Address Field of Ingress Is Empty After Load Balancer is Provisioned

### ISSUE THREAD

**Issue by JeremyBolster** [kubernetes-sigs/aws-load-balancer-controller#2476]
**Describe the bug**

When provisioning an ingress/loadbalancer the address field of the ingress should be updated to that of the load balancer but it is left blank instead. This bug seems to be triggered when WAF is enabled on an EKS Private Cluster.

**Steps to reproduce**

1. Create Ingress
2. Wait for LB to be created
3. Run kubectl and see that the address field is blank.
```
$ kubectl get ingress -owide
NAME         CLASS   HOSTS   ADDRESS   PORTS   AGE
awslbc-test   alb     *                 80      89m
```

**Expected outcome**

I expect the address field to be populated regardless of WAF errors being produced.

```
$ kubectl get ingress -owide
NAME         CLASS   HOSTS   ADDRESS   PORTS   AGE
awslbc-test   alb     *          internal-k8s-awslbcon-awslbcte-redacted-redacted.us-west-2.elb.amazonaws.com       80      89m
```

**Environment**

* AWS Load Balancer controller version: `v2.3.0`
* Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81"`
* Using EKS (yes/no), if so version? `yes`, see k8s version

**Additional Context**:

There is a workaround for this issue. Disable WAF.

via helm
```
--set enableWaf=false --set enableWaf2=false --set enableShield=false
```
via command args
```
--enable-shield=false --enable-waf=false --enable-wafv2=false
```

**Additional Context**
Tangentially Related to: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1734

**Comment by kishorj** [comment]
@JeremyBolster, did the AWS load balancer controller reconcile your ingress/ingress group successfully? Are there any events reported in the ingress/ingress group?

**Comment by JeremyBolster** [comment]
> did the AWS load balancer controller reconcile your ingress/ingress group successfully?
From my observation the only "reconciliation" that is missing is the hostname field being populated. So, yes.

> Are there any events reported in the ingress/ingress group?
Yes, when WAF was still enabled I was getting the "`http` response from `https` server" error with the WAFv2 endpoint listed in the event. This was also captured in the logs.

**Comment by kishorj** [comment]
@JeremyBolster, it is designed behavior for the first reconcile where controller doesn't populate the status field unless all of the reconciliation is successful including WAF. In your case, you need to disable WAF since it is not available for your environment.

**Comment by kishorj** [comment]
@JeremyBolster, I'm closing this issue. If you have further concerns, feel free to reopen or create a new issue.
