### ISSUE TITLE
aws-load-balancer-nlb-target-type: ip results in NodePort and ClusterIP being assigned

### ISSUE THREAD

**Issue by ghostsquad** [kubernetes-sigs/aws-load-balancer-controller#2487]
**Describe the bug**
When creating a service and specifying the use of `nlb-target-type: ip`, it appears the service ends up getting a ClusterIP and NodePorts, even though those are not desired.

**Steps to reproduce**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: ambassador
  labels:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/name: edge-stack
    app.kubernetes.io/instance: edge-stack
    profile: main
```

**Expected outcome**

To see a NLB created, pointing traffic to pods. The service should not have nodeport OR a clusterIP.

**Environment**

* AWS Load Balancer controller version `2.2.4`
* Kubernetes version `1.21`
* Using EKS (yes/no), if so version? `yes, 1.21`

**Additional Context**:

```yaml
at 11:55:07 ❯ k get svc test -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"service.beta.kubernetes.io/aws-load-balancer-nlb-target-type":"ip","service.beta.kubernetes.io/aws-load-balancer-scheme":"internal","service.beta.kubernetes.io/aws-load-balancer-type":"external"},"name":"test","namespace":"ambassador"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8080},{"name":"https","port":443,"targetPort":8443}],"selector":{"app.kubernetes.io/instance":"edge-stack","app.kubernetes.io/name":"edge-stack","profile":"main"},"type":"LoadBalancer"}}
  creationTimestamp: "2022-01-28T19:55:06Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
  name: test
  namespace: ambassador
  resourceVersion: "1204291"
  uid: 5d0086c3-1178-4710-96e7-029ee526d597
spec:
  clusterIP: 172.20.118.162
  clusterIPs:
  - 172.20.118.162
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31928
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30706
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/name: edge-stack
    profile: main
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: <REDACTED>.us-west-2.elb.amazonaws.com
```

If I look at the NLB in the AWS UI, I can clearly see that it's pointing directly at the pods. That is the behavior I want. I don't want this service to get NodePorts or a ClusterIP. It doesn't make sense.

**Comment by kishorj** [comment]
@ghostsquad, ClusterIP and NodePort are allocated by kubernetes, not aws-load-balancer-controller. For NodePort, you can refer to https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation for further instructions on disabling allocation - feature will be beta in k8s 1.22.

**Comment by ghostsquad** [comment]
@kishorj thank you for that. So you know why I'm getting a clusterIp?

**Comment by ghostsquad** [comment]
@kishorj I think I found my answer. I didn't realize this was kubernetes doing some of the work and AWS controller doing other parts.

> LoadBalancer: Exposes the Service externally using a cloud provider's load balancer. NodePort and ClusterIP Services, to which the external load balancer routes, are automatically created.

Thank you for your quick response and guidance via documentation.
