### ISSUE TITLE
Target is not associate with NLB

### ISSUE THREAD

**Issue by carloscruzadomatrix** [kubernetes-sigs/aws-load-balancer-controller#2488]
**Describe the bug**
Target is not associate with NLB
Failed deploy model due to Internal error occurred: failed calling webhook "mtargetgroupbinding.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s": context deadline exceeded.

**Steps to reproduce**
- I install with the via YAML manifests
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/installation/

- I follow the step 2 and change the cluster name
apiVersion: apps/v1
kind: Deployment
. . .
name: aws-load-balancer-controller
namespace: kube-system
spec:
    . . .
    template:
        spec:
            containers:
                - args:
                    - --cluster-name=<INSERT_CLUSTER_NAME>

- I create serviceaccount with iam ARN rol create before
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: ${aws_iam_role}    
  name: aws-load-balancer-controller
  namespace: kube-system

- When I try to deploy service I haver the following error:
Failed deploy model due to Internal error occurred: failed calling webhook "mtargetgroupbinding.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s": dial tcp 10.0.12.203:9443: i/o timeout

kind: Service
apiVersion: v1
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:    
    service.beta.kubernetes.io/aws-load-balancer-name: "nlb-${app_name}" 
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 

**Expected outcome**
Deploy the service witout problem.

**Environment**

* AWS Load Balancer controller version 2.3.1
* Using EKS (yes/no), if so version? Yes, 1.21

**Additional Context**:
![image](https://user-images.githubusercontent.com/95088398/151891910-75c9997e-4b20-4c86-86f5-d0433fd25eee.png)

**Comment by kishorj** [comment]
@carloscruzadomatrix, do you use terraform? Could you check if your worker nodes allow allow access to port 9443 from the control plane? This looks similar to issue #2462

**Comment by carloscruzadomatrix** [comment]
Yes, I use terraform. You are right! all work when activate the SG with VPC CIDR and port 9443! Thank you

**Comment by kishorj** [comment]
Closing the issue. Keep track of the doc changes in 2462.
