### ISSUE TITLE
failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet with at least 8 free IP Addresses for ALB.

### ISSUE THREAD

**Issue by rakeshdevops12** [kubernetes-sigs/aws-load-balancer-controller#2491]
Hi Team,

i'm trying to create alb via ingress but getting below while creating. can you please help us on the same.

My ingress manifest is :

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-usermgmt-restapp-service
  labels:
    app: sia-app
  annotations:
    # Ingress Core Settings
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /filterdataset/homepage
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app-nodeport-service
              servicePort: 5000

**Comment by rakeshdevops12** [comment]
E0202 12:51:05.277265       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet with at least 8 free IP Addresses for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/eksdemo2': ['shared' or 'owned'] and 'kubernetes.io/role/elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[]'"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"ingress-usermgmt-restapp-service"}

Even we have added tags in public and private subnets.

**Comment by oliviassss** [comment]
@rakeshdevops12 just to confirm, you have tagged the subnets correctly, but you still see this error? 

- tag public subnets with `kubernetes.io/role/elb`
- tag private subnets with `kubernetes.io/role/internal-elb`
- common tag: `kubernetes.io/cluster/${cluster-name}`

If the error still exists with these tags, it might be that there is no sufficient IP addresses available in your subnets, you can refer to this [doc](https://aws.amazon.com/premiumsupport/knowledge-center/subnet-insufficient-ips/) to free up or add more IP addresses for your VPC.

**Comment by kishorj** [comment]
@rakeshdevops12, you could also query the subnets in your VPC using the following aws cli 

```
aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} Name=tag:kubernetes.io/role/elb,Values=1

```
replace ${VPC_ID} with your VPC id

If it returns empty, then the subnets are not tagged appropriately.

**Comment by kishorj** [comment]
@rakeshdevops12, do you still encounter this issue? I'm closing it for now, if you still have concerns feel free to reopen or create a new issue.
