### ISSUE TITLE
Handle incompatible `Service.spec.allocateLoadBalancerNodePorts` value

### ISSUE THREAD

**Issue by TBBle** [kubernetes-sigs/aws-load-balancer-controller#2492]
**Is your feature request related to a problem?**

The `ServiceLBNodePortControl` feature gate went to beta in k8s v1.22, which will be out on EKS in [approximately March 2022](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar).

This means we'll soon be in the place where `allocateLoadBalancerNodePorts: false` will be desirable for NLB-IP LB Services (to reduce NodePort allocation, iptables CPU cost, and node attack surface), but incompatible with NLB-Instance Services.

I realised this was an issue when [looking at a PR that was assuming NodePort was valid](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2275#discussion_r796811394), but due to a [missed documentation update](https://github.com/kubernetes/website/pull/31599), did not realise that this feature shipped as beta, until this evening.

**Describe the solution you'd like**

The two obvious approaches I see:
* Mutating webhook forces `allocateLoadBalancerNodePorts: true` on Services set up for NLB-Instance: Override the user's unworkable specification. (Assumes that the `allocateLoadBalancerNodePorts` setting was a mistake, not the choice of NLB-Instance)
* Validating webhook rejects Services set up for NLB-Instance with `allocateLoadBalancerNodePorts: false`: Reject the user's unworkable specification.

Of course, this must only operate on Services bound for this AWS LB Controller instance, whether by annotation or `loadBalancerClass` (#2489).

**Describe alternatives you've considered**

Since the AWS LB Controller doesn't currently validate or mutate Services, it would be consistent to catch this at reconcile time, allowing the Service to exist, but the LB setup to fail, as is the case for other unusable option combinations. This is probably pretty close to the status quo, although a brief glance through suggested that catching this (i.e. `NodePort: 0` on an LB Service) would be accidental at best, and come back as a failure in the AWS API call to setup the TargetGroup at worst. (I'm assuming the AWS API will not accept TCP port 0 as a target group destination...)

The [relevant KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1864-disable-lb-node-ports)'s guidance on this appears to be "the user can keep both halves", which aligns with the 'reconcile-time failure' approach, and increases my dispreference for this alternative.

> * What are other known failure modes?
> If `service.spec.allocateLoadBalancerNodePorts=false` but the load balancer implementation does depend on node ports.

> * What steps should be taken if SLOs are not being met to determine the problem?
> In a scenario where a user sets `service.spec.allocateLoadBalancerNodePorts=false` but the load balancer does require node ports, the user can re-enable node ports for a Service by setting `service.spec.allocateLoadBalancerNodePorts` back to `true`. This will trigger node port allocation from kube-apiserver.

----

Also, some attention should be paid to the situation where `allocateLoadBalancerNodePorts: false` is set, but NodePorts are explicitly specified, as this will (per https://groups.google.com/g/kubernetes-sig-network/c/bir0iGbkxJc and https://github.com/kubernetes/kubernetes/pull/103467, but not [_explicitly_ documented](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation)) lead to NodePorts existing, and hence be a usable configuration.

My initial reaction there is to say "reject it when `allocateLoadBalancerNodePorts: false` even if NodePorts are provided", since semantically, NLB-Instance mode needs NodePorts, and explicitly saying `allocateLoadBalancerNodePorts: false` shows user-intent to not use any NodePorts that might happen to exist. Or possibly shows user-misunderstanding about NLB-Instance mode requiring NodePorts. Or shows that the user _actually_ wanted NLP-IP mode and has perhaps misspelled the relevant annotation.

If mutating the Service with a webhook rather than validating it, then this problem is already solved: Forcing `allocateLoadBalancerNodePorts: true` won't have any practical effect in this case, and the semantics end up correct.

On the other hand, it's probably kinder to the user in this case to bring up the NLB-Instance since it's a workable configuration. This is more-compatible with handling this at reconcile time, I think, since we already see the numeric NodePort value at the right moment, and can hence just check that (we currently don't seem to) and ignore `allocateLoadBalancerNodePorts` completely.

This does allow the case where the user might later remove the NodePorts from the Service spec, and hence break a working LB setup through all fault of their own. Reconciling would catch this so it would be visible to the user via the events on the Service like an initial setup failure, but it would certainly not be a pleasant result.

**Comment by kishorj** [comment]
@TBBle, thanks for bringing this issue up. For the short term, we will make changes to the reconciler to fail when `allocateLoadBalancerNodePorts: false`, and the node port is not allocated. We will consider the webhook solution for the long term when have one for the service resources.
