### ISSUE TITLE
Controller deletes an ALB it didn't create when there are no ingresses left

### ISSUE THREAD

**Issue by bpiper** [kubernetes-sigs/aws-load-balancer-controller#2493]
I'm using Terraform to manage an ALB (because I need to hook it up with other non-k8s stuff), and also to create Kubernetes deployments + ingresses on EKS.  Because I only want the load balancer controller to manage listeners and target groups and not the ALB itself, I used these tags on the ALB:

```
    "ingress.k8s.aws/stack"    = "my-stack"
    "ingress.k8s.aws/resource" = "LoadBalancer"
    "elbv2.k8s.aws/cluster"    = "my-cluster-name"
```

This all works fine, but if I delete the deployments and ingresses via Terraform (they're in a stack that is separate from but dependent on the one with the ALB), then the ALB is getting deleted as well by the controller, because it sees that there are no ingresses and can therefore delete the 'unused' ALB, so it's basically stepping on Terraform's toes.

Is there any way for the controller to know explicitly that the ALB is managed by something else (and shouldn't be deleted), rather than just 'this is the ALB I should use for these ingresses'? If not, it would be great to have a tag/annotation that can do that.

I know this is kind of a grey area, but I think I do still prefer having the controller around to manage listeners and target groups for me.

AWS Load Balancer Controller: 2.3.1
EKS/Kubernetes: 1.21

**Comment by kishorj** [comment]
@bpiper, though you can manually specify tags to associate load balancer to k8s resources, controller supporting external lb is still not official - the ALB resource will get deleted if your ingress group becomes empty. Our long term plan is to support specifying externally managed load balancer ARN via annotation, feature request #2065 to track the issue.

**Comment by bpiper** [comment]
Thanks for clarifying @kishorj.  I'll keep an eye on that feature request.  The impact of the issue is something I can live with for now anyway.

**Comment by kishorj** [comment]
closing the issue in favor of the feature request 2065.
