### ISSUE TITLE
stickiness doesn't work

### ISSUE THREAD

**Issue by akhal3d96** [kubernetes-sigs/aws-load-balancer-controller#2494]
I set the group target annotation on the ingreess configuration to enable sticky sessions, however it doesn't seem to work

![image](https://user-images.githubusercontent.com/1307905/152649897-525c2861-34d3-49ef-a62b-c571348ffab1.png)

```
alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=200, load_balancing.algorithm.type=least_outstanding_requests
alb.ingress.kubernetes.io/target-type: ip
```
One thing worth noting is that inside the target group itself the attribute tab is showing this:

![image](https://user-images.githubusercontent.com/1307905/152650162-75977dae-c705-421a-b119-c5f0ca8f25a2.png)

I don't know if this is the expected behavior or not. 

**Environment**

* AWS Load Balancer controller version
v2.3.1

* Kubernetes version
v1.21.5-eks-bc4871b

* Using EKS (yes/no), if so version?
v1.21.5-eks-bc4871b

**Comment by kishorj** [comment]
@akhal3d96, in your case you don't use weighted target group, so you don't need stickiness on the listener rule. All of your requests will be sent to the target group configured. As you mentioned you can specify the target group attributes via the annotation and the setting take effect. Were you able to do any tests to verify the stickiness wasn't working in your case? Were the requests were being sent to different pods?

You might be referring to the weighted target group case, one way to configure for ingress is via annotation, please refer to the following live docs: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/#actions. When you have more then one target group on the listener rule, then the group-level stickiness come into picture, and you can configure that.

**Comment by kishorj** [comment]
I'm closing the issue. If you have further concerns feel free to reopen or create a new one.

**Comment by akhal3d96** [comment]
Okay thank you.
