### ISSUE TITLE
Desired AvailabilityZoneIDs support

### ISSUE THREAD

**Issue by shaoxt** [kubernetes-sigs/aws-load-balancer-controller#2496]
**Is your feature request related to a problem?**

When anything wrong in one of the AvailabilityZone of AWS, how can we turn off the traffic quickly to all ingresses in the cluster?
So that the traffic won't be impacted by the bad AZ.

There is some discussions about the approach to apply target node labels on each Ingress #2354.
Think about the case that couple hundreds ingresses in one cluster, it is tough to update each Ingress.

**Describe the solution you'd like**
The proposal is to have an argument "--desired-availability-zone-ids" on aws-load-balancer-controller, so that the controller can pickup the targets within the desired AZs. This can switch the entire cluster as quick as possible.

Sample:
```
--desired-availability-zone-ids=usw2-az2,usw2-az3
```
This argument will limit the subnets specified on the annotation of Ingress 
```
alb.ingress.kubernetes.io/subnets: IngressSubnetAz1, IngressSubnetAz2, IngressSubnetAz3
```
Even the ingress specified 3 subnets, but the targets NOT in the desired availability zones won't be used in the targetGroup.
The feature provides a lever to control the traffic out of one AZ quickly.

**Describe alternatives you've considered**
Since this feature only enabled once the argument is specified, so it won't impact any major feature.

**Comment by kishorj** [comment]
@shaoxt, I see the following issues with the suggested approach
- In case of NLB, we will not be able to delete existing AZ after creation
- The controller subnet autodiscovery performs discovery only for new load balancers, existing ones won't be affected

**Comment by shaoxt** [comment]
@kishorj 

- Yes, NLB doesn't reconcile when it is created.  
    -   Is there any reason to treat NBL differently with ALB ? 
- The subnet autodiscovery does apply on existing new load balancer after the aws-load-balancer got restarted.
It does limit the subnets from given AZs.

```
Availability Zones
[subnet-07a4c8b03446f6e2b - us-west-2a ](https://console.aws.amazon.com/vpc/home?region=us-west-2#subnets:filter=subnet-07a4c8b03446f6e2b)
IPv4 address: Assigned by AWS

[subnet-0cd52c2c9e095a466 - us-west-2b ](https://console.aws.amazon.com/vpc/home?region=us-west-2#subnets:filter=subnet-0cd52c2c9e095a466)
IPv4 address: Assigned by AWS
```
