### ISSUE TITLE
Security group ingress rules overwritten when used with multiple load balancers

### ISSUE THREAD

**Issue by hintofbasil** [kubernetes-sigs/aws-load-balancer-controller#2501]
**Describe the bug**

We create multiple load balancers across multiple clusters.  The targets for these load balancers use the same security groups.  When the load balancer controller adds ingress rules to these security groups (with description `elbv2.k8s.aws/targetGroupBinding=shared`) they overwrite the previously added ingress rules from the other load balancer controllers.

**Steps to reproduce**

Reproduction steps assume an EKS cluster.

1. Create a test security group
2. Create two EKS clusters
3. Deploy the AWS load balancer controller to both clusters
4. In both clusters create a target deployment and a `SecurityGroupPolicy` to bind this to the security group
5. In both clusters create a load balancer using the controller pointing to the deployment
6. Ensure the security group ingress rule was created
7. Restart the other load balancer controller
8. The ingress rule should change

Notes that may help with reproduction :- 

- All the resources are created in the same VPC
- Each cluster and load balancer combo are in different subnets
- The load balancer is ip based, internal, and uses a fixed IP address

**Expected outcome**

Separate ingress rules should be created for each load balancer

**Environment**

* AWS Load Balancer controller version
v2.2.0-rc1

* Kubernetes version
v1.19.15

* Using EKS (yes/no), if so version?
eks.7

**Additional Context**:

**Comment by kishorj** [comment]
@hintofbasil, do you share the same security group across multiple k8s cluster? 

In the current design, we don't support running multiple instances of the load balancer controller in the same cluster. There is already a feature request #2185 where we plan to use security group rule tags to identify which controller owns the security group rules. We will consider multiple controllers case with the feature request.

**Comment by maruina** [comment]
> @hintofbasil, do you share the same security group across multiple k8s cluster?

Working with @hintofbasil I can say yes, we do. :)
