### ISSUE TITLE
Human readable log timestamp

### ISSUE THREAD

**Issue by saiteja313** [kubernetes-sigs/aws-load-balancer-controller#2502]
**Is your feature request related to a problem?**
- I'm frustrated when I troubleshoot an issue by tracing through AWS Load Balancer Controller pod logs.

**Describe the solution you'd like**

- AWS Load Balancer controller currently logs timestamp in epoch format.
- Example log:
```
{"level":"info","ts":1644492891.6236484,"logger":"controllers.ingress","msg":"SG configured via annotation","LB SGs":["sg-123445566666"],"backend SG":null}
```

**Describe alternatives you've considered**
- I have to use epoch to Hum timestamp convertor during troubleshooting. Can we get hum readable timestamp. Please?

**Comment by kishorj** [comment]
@saiteja313, is it possible to import the logs to cloudwatch to get the appropriate conversion? Alternative is to have a script convert the timestamp from kubectl logs.

**Comment by M00nF1sh** [comment]
You can achieve this with JQ easily:
e.g. 
```
ks logs aws-load-balancer-controller-xxxx-xxxx | grep '^{' | jq '.ts|= (. | strftime("%Y-%m-%dT%H:%M:%SZ"))
```

**Comment by kishorj** [comment]
@saiteja313, did the response from @M00nF1sh help your case? I'm closing the issue, if you have further concerns, feel free to reach out.

**Comment by jcogilvie** [comment]
I would like to request for this to be reopened.

We all know ways to parse epoch time, but that doesn't really resolve the readability issue.  Workarounds become more burdensome the more times you have to invoke them.  

Further, for other tools like lens that are often used to view logs, CLI workarounds don't apply.  

It should be easy enough to just switch from epoch logs to ISO logs, and I would be surprised if anything downstream balked at the change, but if you're worried about it, maybe take a format flag.

**Comment by kishorj** [comment]
@jcogilvie, the next release v2.5.0 will have the human readable log timestamps.

**Comment by max-rocket-internet** [comment]
> I would like to request for this to be reopened.

I was going to ask the same. We just had an incident and reading the logs from the controller was difficult with Unix timestamps.

> the next release v2.5.0 will have the human readable log timestamps.

Excellent!
