### ISSUE TITLE
AWS Load Balancer Controller V2.4.0 - Release Date?

### ISSUE THREAD

**Issue by rkadekar** [kubernetes-sigs/aws-load-balancer-controller#2511]
Hello,
I am trying to find out when V2.4.0 is going to be released. We are in the middle of K8s V1.22 version upgrade. Current latest version V2.3.1 is blocking K8s V1.22 upgrade. I couldn't find any alternative way to make this work. If there is an alt solution please point me to that. Thank you!

**Comment by kishorj** [comment]
We just released v2.4.0. Please refer to the release notes for further details - https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.4.0.
