### ISSUE TITLE
Autorecover aws-load-balancer-controller managed SG inbound rules

### ISSUE THREAD

**Issue by stevo-f3** [kubernetes-sigs/aws-load-balancer-controller#2515]
**Is your feature request related to a problem?**
aws-load-balancer-controller managed security group inbound rules for LB Service `loadBalancerSourceRanges` definition are not being recovered, unless there is a change to `loadBalancerSourceRanges`. Currently (aws-load-balancer-controller v2.3.1, chart v1.3.3) accidental/unwanted deletion of controller managed SG rule requires detecting rule is missing + changing `loadBalancerSourceRanges` (back and forth) to trigger controller to reconcile/recover the rule.

**Describe the solution you'd like**
I expect aws-load-balancer-controller to reconcile (compare desired and actual) and recover all actual resources it manages (including inbound SG rules) even when there's no change event on declared desired state (Service definition, loadBalancerSourceRanges).

**Describe alternatives you've considered**
No effective alternatives come to mind

**Comment by kishorj** [comment]
@stevo-f3, when you make changes to the ingress/service, controller will restore the changes. We will investigate further why the sync-period setting did not work in this case.

**Comment by oliviassss** [comment]
Hi, we have shipped the fix in v2.5.4, please check the details in our release note: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.5.4. 
I'm closing this ticket as of now, please feel free to reach out or reopen if you have any issues. Thanks
