### ISSUE TITLE
The Rule of Application Load Balancer return fixed 404 and not forwarding to the Target Groups

### ISSUE THREAD

**Issue by quadrinho** [kubernetes-sigs/aws-load-balancer-controller#2519]
**Describe the bug**
The Rule of Application Load Balancer return fixed 404 and not forwarding to the Target Groups

**Steps to reproduce**
I add to the ingress the following annotations:

  annotations:
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: callyaflex-dev-mobile1.internal.vodafone.com
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: vfde-webapp-dev-mobile1-callyafl
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/security-groups: sg-0718a290aa7fdb86b
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/success-codes: 200-304
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=vfde-webapp-dev-mobile1-callyafl-logs
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30,load_balancing.algorithm.type=least_outstanding_requests,stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=180

but in the listeners there is not the target group created by the chart but a fixed 404 return response

**Expected outcome**
I expect to have a load Balancer with the correct listeners that forward to the target groups

**Environment**

* AWS Load Balancer controller version 2.3
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? 1.21

**Comment by kishorj** [comment]
@quadrinho, could you check whether the backend service you referenced exists in the same namespace as the ingress? Do you see any error in the controller logs? Also check if there are any error events reported against the ingress resource.

**Comment by kishorj** [comment]
@quadrinho, any update on this matter?

**Comment by sajirali** [comment]
i am also getting same error:

`aws-load-balancer-controller-58bbb566d5-nqxl8 {"level":"info","ts":1649737493.3059142,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"Manag │
│ edLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-game2048-ingress2-7728b5615c\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":80,\"toPort\":80,\"ipRanges\":[{\"cidrIP\":\"0.0 │
│ .0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"default │
│ Actions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticL │
│ oadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048- │
│ service-2048:80/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-game2048-ingress │
│ 2-5ab988ba18\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-02ed5ab16f68077bc\"},{\"subnetID\":\"subnet-02fd73950a015c10e\"},{\"subnetID\":\"subnet-075f29c0c9e7c3d9a │
│ \"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"},\"sg-0e896dd048dc13e83\"]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\":{\" │
│ name\":\"k8s-game2048-service2-3a66038e25\",\"targetType\":\"ip\",\"port\":80,\"protocol\":\"HTTP\",\"protocolVersion\":\"HTTP1\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/\",\" │
│ matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\": │
│ {\"template\":{\"metadata\":{\"name\":\"k8s-game2048-service2-3a66038e25\",\"namespace\":\"game-2048\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-20 │
│ 48-service-2048:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"service-2048\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":\"sg-0e896dd048dc13e83\"}}],\"ports\":[{\"protocol\" │
│ :\"TCP\",\"port\":80}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}`

- There are no listeners for the ALB
- Target group shows Load balancer: None Associated
- Registered targets show: Health status: unused with details: `Target group is not configured to receive traffic from the load balancer`

deploying: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/examples/2048/2048_full.yaml

EKS: 1.21
AWS LB Controller: 2.4.1
AWS VPC CNI Custom networking enabled.

**Comment by sajirali** [comment]
@kishorj there are no errors.
it even says:
`{"level":"info","ts":1649781500.913361,"logger":"controllers.ingress","msg":"created listener rule","stackID":"game-2048/ingress-2048","resourceID":"80:1","arn":"arn:aws:elasticloadbalancing:us-east-1 │
│ :2322xxxxxxxx:listener-rule/app/k8s-game2048-ingress2-5ab988ba18/700364bbb770fa0d/0f474d9e54e98610/b18747dc1d6e571c"}`

but there are no listeners.

![image](https://user-images.githubusercontent.com/17226011/163012365-2eb7fa38-4679-4d3b-b755-4bfaeb27e446.png)

**Comment by sajirali** [comment]
@kishorj full log from controller if it helps:

`aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781310.019052,"msg":"version","GitVersion":"v2.4.1","GitCommit":"c4471defda10f8184173192b9f9df4e411ee5dac","BuildDate":"2022-03-16T16:10:01+0000"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781313.1847458,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781313.193674,"logger":"setup","msg":"adding health check for controller"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781313.1938105,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781313.194006,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781313.1940975,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781313.1942768,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1-ingress"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781313.1944046,"logger":"setup","msg":"starting podInfo repo"}
aws-load-balancer-controller-754d6f768-zcfpb I0412 16:35:15.194668       1 leaderelection.go:243] attempting to acquire leader lease aws-load-balancer-controller/aws-load-balancer-controller-leader...
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781315.194687,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781315.1948538,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781315.1950943,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781315.1951838,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781315.1958597,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
aws-load-balancer-controller-754d6f768-zcfpb I0412 16:35:30.548618       1 leaderelection.go:253] successfully acquired lease aws-load-balancer-controller/aws-load-balancer-controller-leader
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5489166,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5492158,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5492246,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5492306,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5492373,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting Controller","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5495114,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0008e0fa0"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.549557,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0008e0ff0"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5495684,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5501778,"logger":"controller-runtime.manager.controller.service","msg":"Starting EventSource","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5503645,"logger":"controller-runtime.manager.controller.service","msg":"Starting Controller"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5507588,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5507853,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0008e1040"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5508027,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0008e1310"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5508163,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5508244,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.5508318,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting Controller"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781307.964906,"msg":"version","GitVersion":"v2.4.1","GitCommit":"c4471defda10f8184173192b9f9df4e411ee5dac","BuildDate":"2022-03-16T16:10:01+0000"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781311.1896665,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781311.2073655,"logger":"setup","msg":"adding health check for controller"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781311.2076561,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781311.2078137,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781311.2079008,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781311.2079947,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1-ingress"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781311.2082121,"logger":"setup","msg":"starting podInfo repo"}
aws-load-balancer-controller-754d6f768-bdx5k I0412 16:35:13.208500       1 leaderelection.go:243] attempting to acquire leader lease aws-load-balancer-controller/aws-load-balancer-controller-leader...
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781313.2088284,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781313.2089276,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781313.20914,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781313.2092533,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
aws-load-balancer-controller-754d6f768-bdx5k {"level":"info","ts":1649781313.2095928,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.651644,"logger":"controller-runtime.manager.controller.service","msg":"Starting workers","worker count":3}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.6517332,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting workers","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","worker count":3}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781330.6520607,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting workers","worker count":3}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781497.9889476,"logger":"backend-sg-provider","msg":"creating securityGroup","name":"k8s-traffic-sajirlocaltest1labuseast1-77ca6f6dec"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781498.486381,"logger":"controllers.ingress","msg":"Auto Create SG","LB SGs":[{"$ref":"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID"},"sg-0f6a38165d27e8ab3"],"backend SG":"sg-0f6a38165d27e8ab3"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781498.4875164,"logger":"controllers.ingress","msg":"successfully built model","model":"{\"id\":\"game-2048/ingress-2048\",\"resources\":{\"AWS::EC2::SecurityGroup\":{\"ManagedLBSecurityGroup\":{\"spec\":{\"groupName\":\"k8s-game2048-ingress2-7728b5615c\",\"description\":\"[k8s] Managed SecurityGroup for LoadBalancer\",\"ingress\":[{\"ipProtocol\":\"tcp\",\"fromPort\":80,\"toPort\":80,\"ipRanges\":[{\"cidrIP\":\"0.0.0.0/0\"}]}]}}},\"AWS::ElasticLoadBalancingV2::Listener\":{\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"HTTP\",\"defaultActions\":[{\"type\":\"fixed-response\",\"fixedResponseConfig\":{\"contentType\":\"text/plain\",\"statusCode\":\"404\"}}]}}},\"AWS::ElasticLoadBalancingV2::ListenerRule\":{\"80:1\":{\"spec\":{\"listenerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::Listener/80/status/listenerARN\"},\"priority\":1,\"actions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-service-2048:80/status/targetGroupARN\"}}]}}],\"conditions\":[{\"field\":\"path-pattern\",\"pathPatternConfig\":{\"values\":[\"/*\"]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-game2048-ingress2-5ab988ba18\",\"type\":\"application\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-02ed5ab16f68077bc\"},{\"subnetID\":\"subnet-02fd73950a015c10e\"},{\"subnetID\":\"subnet-075f29c0c9e7c3d9a\"}],\"securityGroups\":[{\"$ref\":\"#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID\"},\"sg-0f6a38165d27e8ab3\"]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\":{\"name\":\"k8s-game2048-service2-532a01ba9a\",\"targetType\":\"ip\",\"port\":80,\"protocol\":\"HTTP\",\"protocolVersion\":\"HTTP1\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":\"traffic-port\",\"protocol\":\"HTTP\",\"path\":\"/\",\"matcher\":{\"httpCode\":\"200\"},\"intervalSeconds\":15,\"timeoutSeconds\":5,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2}}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"game-2048/ingress-2048-service-2048:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-game2048-service2-532a01ba9a\",\"namespace\":\"game-2048\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/game-2048/ingress-2048-service-2048:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"service-2048\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"securityGroup\":{\"groupID\":\"sg-0f6a38165d27e8ab3\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":80}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781498.77108,"logger":"controllers.ingress","msg":"creating securityGroup","resourceID":"ManagedLBSecurityGroup"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781499.0534108,"logger":"controllers.ingress","msg":"created securityGroup","resourceID":"ManagedLBSecurityGroup","securityGroupID":"sg-0000f68db98ce0bb6"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781499.1647086,"msg":"authorizing securityGroup ingress","securityGroupID":"sg-0000f68db98ce0bb6","permission":[{"FromPort":80,"IpProtocol":"tcp","IpRanges":[{"CidrIp":"0.0.0.0/0","Description":""}],"Ipv6Ranges":null,"PrefixListIds":null,"ToPort":80,"UserIdGroupPairs":null}]}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781499.4933772,"msg":"authorized securityGroup ingress","securityGroupID":"sg-0000f68db98ce0bb6"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781499.525016,"logger":"controllers.ingress","msg":"creating targetGroup","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781499.7707653,"logger":"controllers.ingress","msg":"created targetGroup","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80","arn":"arn:aws:elasticloadbalancing:us-east-1:2322xxxxxxxxx:targetgroup/k8s-game2048-service2-532a01ba9a/3b0b69114ee02834"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781499.8331609,"logger":"controllers.ingress","msg":"creating loadBalancer","stackID":"game-2048/ingress-2048","resourceID":"LoadBalancer"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781500.6648436,"logger":"controllers.ingress","msg":"created loadBalancer","stackID":"game-2048/ingress-2048","resourceID":"LoadBalancer","arn":"arn:aws:elasticloadbalancing:us-east-1:2322xxxxxxxxx:loadbalancer/app/k8s-game2048-ingress2-5ab988ba18/700364bbb770fa0d"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781500.7210636,"logger":"controllers.ingress","msg":"creating listener","stackID":"game-2048/ingress-2048","resourceID":"80"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781500.7880402,"logger":"controllers.ingress","msg":"created listener","stackID":"game-2048/ingress-2048","resourceID":"80","arn":"arn:aws:elasticloadbalancing:us-east-1:2322xxxxxxxxx:listener/app/k8s-game2048-ingress2-5ab988ba18/700364bbb770fa0d/0f474d9e54e98610"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781500.8351254,"logger":"controllers.ingress","msg":"creating listener rule","stackID":"game-2048/ingress-2048","resourceID":"80:1"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781500.913361,"logger":"controllers.ingress","msg":"created listener rule","stackID":"game-2048/ingress-2048","resourceID":"80:1","arn":"arn:aws:elasticloadbalancing:us-east-1:2322xxxxxxxxx:listener-rule/app/k8s-game2048-ingress2-5ab988ba18/700364bbb770fa0d/0f474d9e54e98610/b18747dc1d6e571c"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781500.9135177,"logger":"controllers.ingress","msg":"creating targetGroupBinding","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781500.9727058,"logger":"controllers.ingress","msg":"created targetGroupBinding","stackID":"game-2048/ingress-2048","resourceID":"game-2048/ingress-2048-service-2048:80","targetGroupBinding":{"namespace":"game-2048","name":"k8s-game2048-service2-532a01ba9a"}}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781501.1337175,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"game-2048/ingress-2048"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781501.2333548,"msg":"authorizing securityGroup ingress","securityGroupID":"sg-074c64fba788ed4e1","permission":[{"FromPort":80,"IpProtocol":"tcp","IpRanges":null,"Ipv6Ranges":null,"PrefixListIds":null,"ToPort":80,"UserIdGroupPairs":[{"Description":"elbv2.k8s.aws/targetGroupBinding=shared","GroupId":"sg-0f6a38165d27e8ab3","GroupName":null,"PeeringStatus":null,"UserId":null,"VpcId":null,"VpcPeeringConnectionId":null}]}]}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781501.5295696,"msg":"authorized securityGroup ingress","securityGroupID":"sg-074c64fba788ed4e1"}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781501.7453291,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-east-1:2322xxxxxxxxx:targetgroup/k8s-game2048-service2-532a01ba9a/3b0b69114ee02834","targets":[{"AvailabilityZone":null,"Id":"100.64.123.236","Port":80},{"AvailabilityZone":null,"Id":"100.64.161.58","Port":80},{"AvailabilityZone":null,"Id":"100.64.187.170","Port":80},{"AvailabilityZone":null,"Id":"100.64.70.242","Port":80},{"AvailabilityZone":null,"Id":"100.64.90.25","Port":80}]}
aws-load-balancer-controller-754d6f768-zcfpb {"level":"info","ts":1649781502.4888468,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:us-east-1:2322xxxxxxxxx:targetgroup/k8s-game2048-service2-532a01ba9a/3b0b69114ee02834"}
`

**Comment by bala151187** [comment]
@sajirali you got to have this as part of your ingress . 
spec:
  defaultBackend:
    service:
      name: <<service_name>>
      port:
        number: <<service_port>>

**Comment by kishorj** [comment]
@sajirali, controller logs indicates creation of the listener. Are you able to trace in the cloud trail whether the given listener resource is created successfully and whether there are any delete events for the same resource?

**Comment by bala151187** [comment]
@kishorj
![Screen Shot 2022-04-13 at 12 56 04 PM](https://user-images.githubusercontent.com/5027627/163231740-c310e6bf-614a-4f79-8f53-9b27d2c5fdee.png)

do you have any idea on why am i seeing like this ..

**Comment by sajirali** [comment]
@kishorj thanks for asking me to check cloudtrail. i was doing all sorts of k8s/eks related troubleshooting. i am kinda embarrassed now. yep there are DeleteListener events through org level guardrails to remove listeners with port 80. for me there is no more issues and i will test with https.
