### ISSUE TITLE
Release Notes for 2.4.0 should mention breaking behavior change

### ISSUE THREAD

**Issue by ReillyBrogan** [kubernetes-sigs/aws-load-balancer-controller#2520]
**Describe the bug**
We upgraded one of our (QA) k8s clusters from using 2.3.0 to 2.4.0 just now and all of our instance NLB loadbalancers were deleted. It appears that there was a breaking change in behavior related to annotations, the `service.beta.kubernetes.io/aws-load-balancer-target-type: "nlb-instance"` annotation no longer works and users must use `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"` instead. If this change is not made prior to upgrading the aws-load-balancer-controller then users will experience a disruption in service until the annotation is fixed. 

The release notes should be updated to reflect this change

**Comment by ReillyBrogan** [comment]
AND it should mention that if `service.beta.kubernetes.io/aws-load-balancer-internal: 'true'` is set then the `load-balancer-source-ranges` defaults to the VPC of the NLB, which is also a breaking change.

**Comment by kishorj** [comment]
@ReillyBrogan, the controller has not supported the annotation `service.beta.kubernetes.io/aws-load-balancer-target-type:` in any of the released versions. Did you use a custom built controller? If so, which rev is it based on? The release tags are listed here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/tags. 

For internal load balancer, the source range is the VPC of NLB, and we document it in the live docs ([link](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#lb-source-ranges)). This behavior has not changed in 2.4.0. Could you give a specific example on why it would be a breaking change, or how it affects your use case in v2.3.0 to v2.4.0 upgrade?

**Comment by kishorj** [comment]
@ReillyBrogan, also could you share which v2.3.0 image you used, with the git rev?
