### ISSUE TITLE
Add NLB support for automatic elastic IP allocation from specified public IPv4 pool

### ISSUE THREAD

**Issue by adammw** [kubernetes-sigs/aws-load-balancer-controller#2523]
**Is your feature request related to a problem?**
Related to #1906 - the current annotation requires manual creation of EIP allocations outside of kuberentes/aws-load-balancer-controller to support BYOIP use-case.

**Describe the solution you'd like**
A new annotation similar to the one described in that ticket:
```
service.beta.kubernetes.io/aws-load-balancer-public-ipv4-pool: ipv4pool-ec2-0f123678912345678
```
The annotation will allocate a new set of random EIPs from the specific pool when the service is created and then use them.

**Describe alternatives you've considered**
The existing EIP annotation `service.beta.kubernetes.io/aws-load-balancer-eip-allocations` requires you to pre-allocate a number of EIPs (according to how many AZs you serve) dedicated to the NLB external to the controller then copy it in to the annotation, making management of the NLB require external software/clickops.

**Comment by kishorj** [comment]
@adammw, thanks for the feature request and the PR. We will sync up internally with the NLB team to see if they have plans to support ipv4pool natively.

**Comment by adammw** [comment]
@kishorj any updates on this from the service team? we have started internally using the controller with the linked PR in the meantime to aid in management of BYOIP EIPs.

**Comment by alam0rt** [comment]
would like to see this feature supported, are we able to reopen?

**Comment by JoelSpeed** [comment]
@kishorj Any update on this issue, is it likely to be supported for NLB?

**Comment by oliviassss** [comment]
@JoelSpeed, @alam0rt, @adammw, sorry for the delay, I just checked with NLB team, this feature is not yet supported by NLB, it's on their roadmap for H2 2024. I'd suggest to reach out to team for escalation. Thanks
