### ISSUE TITLE
Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation

### ISSUE THREAD

**Issue by jorsol** [kubernetes-sigs/aws-load-balancer-controller#2525]
**Describe the bug**
After uninstalling an old (working) version of aws-alb-ingress-controller:v1.1.6, I installed the AWS Load Balancer Controller 2.4.0.

There was an Ingress that was previously working and now I simply get 
`Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403`

The subnets are properly tagged, have enabled debug logs, but nothing shows what is the issue.

```
{"level":"info","ts":1645638944.749603,"logger":"subnets-resolver","msg":"multiple subnet in the same AvailabilityZone","AvailabilityZone":"us-east-1a","chosen":"subnet-xxxxe4792d12xxxx","ignored":[{"AssignIpv6AddressOnCreation":false,"AvailabilityZone":"us-east-1a","AvailabilityZoneId":"use1-az4","AvailableIpAddressCount":27,"CidrBlock":"10.144.2.0/26","CustomerOwnedIpv4Pool":null,"DefaultForAz":false,"EnableDns64":false,"EnableLniAtDeviceIndex":null,"Ipv6CidrBlockAssociationSet":null,"Ipv6Native":false,"MapCustomerOwnedIpOnLaunch":false,"MapPublicIpOnLaunch":false,"OutpostArn":null,"OwnerId":"TEST","PrivateDnsNameOptionsOnLaunch":{"EnableResourceNameDnsAAAARecord":false,"EnableResourceNameDnsARecord":false,"HostnameType":"ip-name"},"State":"available","SubnetArn":"arn:aws:ec2:us-east-1:TEST:subnet/subnet-xxxxf0f9ab9d0xxxx","SubnetId":"subnet-xxxxx0f9ab9d0xxxx","Tags":[{"Key":"type","Value":"private"},{"Key":"Environment","Value":"prod"},{"Key":"kubernetes.io/cluster/test-cluster","Value":"shared"},{"Key":"kubernetes.io/cluster/test-stg-cluster","Value":"shared"},{"Key":"kubernetes.io/role/internal-elb","Value":"1"},{"Key":"Team","Value":"TEST"},{"Key":"Name","Value":"test-svc-private-us-east-1a"},{"Key":"Project","Value":"TEST Services"}],"VpcId":"vpc-xxxx800dcf6a4xxxx"}]}
{"level":"error","ts":1645638944.7572603,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"test-api","namespace":"test-prod","error":"couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: xxxxcab8-03cc-4549-8313-b3c5770bxxxx"}
{"level":"debug","ts":1645638944.7574065,"logger":"controller-runtime.manager.events","msg":"Warning","object":{"kind":"Ingress","namespace":"test-prod","name":"test-api","uid":"xxxx4e90-xxxx-4f56-965f-9f465b83xxxx","apiVersion":"networking.k8s.io/v1","resourceVersion":"218498760"},"reason":"FailedBuildModel","message":"Failed build model due to couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: xxxxcab8-03cc-xxxx-8313-b3c5770bxxxx"}
```

**Environment**

* AWS Load Balancer controller version 2.4.0
* Kubernetes version 1.20
* Using EKS (yes/no), if so version? v1.20.11-eks-f17b81

**Comment by oliviassss** [comment]
@jorsol Did you update the IAM policy to v2.4.0? 
`curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.0/docs/install/iam_policy.json
`
And You can refer to our [live doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#iam-permissions) for more information.

**Comment by oliviassss** [comment]
@jorsol Also, please migrate from v1 to v2 if you haven't done so https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/upgrade/migrate_v1_v2/

**Comment by jorsol** [comment]
@oliviassss Yes, I applied the steps in https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#setup-iam-manually

I have the role with:

- AmazonEKSLoadBalancerControllerRole
  - [ALBIngressControllerIAMPolicy](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.0/docs/install/iam_policy.json)
  - [AWSLoadBalancerControllerAdditionalIAMPolicy](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/install/iam_policy_v1_to_v2_additional.json)

Still, no clue what is the exact issue, the logs don't mention anything helpful either.

**Comment by M00nF1sh** [comment]
@jorsol 
would you help double check whether your ALBIngressControllerIAMPolicy in iam console have the `ec2:DescribeAvailabilityZones` permission?

the old controller iam permission don't have such permission, and new ones(e.g. the link you provided) requires it. It could be that you didn't update the iam policy document to match latest one on github.

**Comment by jorsol** [comment]
I have checked and recreated everything again, now it seems to work, thanks!
