### ISSUE TITLE
shared backend securitygroup created without inbound rules

### ISSUE THREAD

**Issue by tnimni** [kubernetes-sigs/aws-load-balancer-controller#2529]
**Describe the bug**
When using the following annotations:
alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
alb.ingress.kubernetes.io/security-groups: development_mtls_cloudflare

the shared security group for backend is created without inbound rules so no traffic can reach the cluster

**Steps to reproduce**

apply an ingress with custom security group and the annotations above

**Expected outcome**
the shared security group should create with inboud rules that allow traffic to the cluster

**Environment**

* AWS Load Balancer controller version v2.4.0
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? EKS 1.21

**Additional Context**:

**Comment by kishorj** [comment]
@tnimni, If you configure security-groups manually via the `alb.ingress.kubernetes.io/security-groups` annotation, then you need to create the front-end ingress rules on the manually specified security groups. The backend security group is only for the traffic between the load balancer and the worker node, so there are no rules.

**Comment by M00nF1sh** [comment]
closing this as it's expected behavior. 
If you have further questions, please open a new issue :D
