### ISSUE TITLE
alb.ingress.kubernetes.io/actions.canary modification leads to ALB recreation

### ISSUE THREAD

**Issue by g-dury** [kubernetes-sigs/aws-load-balancer-controller#2532]
**Describe the bug**

alb.ingress.kubernetes.io/actions.canary modification (modification of the `serviceName`) leads to ALB recreation hence if we have live traffic - this is leading to downtime. Currently exploring other way to get traffic in - but wanted to know if this expected or not! Thanks!

**Steps to reproduce**
modify the field alb.ingress.kubernetes.io/actions.canary on your ingress and it leads to ALB being recreated which is creating downtime if traffic is live

**Expected outcome**
A concise description of what you expected to happen.
I don't want downtime on my app :/

**Environment**

* AWS Load Balancer controller version
v2.2.4
* Kubernetes version
1.21
* Using EKS (yes/no), if so version?
yes eks.4
**Additional Context**:
Example field:
```
alb.ingress.kubernetes.io/actions.canary:
{ "type":"forward", "forwardConfig":{ "targetGroups":[{"serviceName":"serviceA-1","servicePort":"https","weight":2},{"serviceName":"serviceA-2","servicePort":"https","weight":98}]}}
```

Thank you very much!

**Comment by kishorj** [comment]
@g-dury, does it delete and create a new ALB, or the target group? When you modify the serviceName to point to a different service, the ALB target group will change, this is expected.

**Comment by g-dury** [comment]
It does it for the target group yes but also for the ALB I am afraid ... `"msg":"deleting loadBalancer",` is one of the logs I see in my alb-ingress-controller pod on k8s!

**Comment by kishorj** [comment]
would you be able to share the controller logs? you can email to - k8s-alb-controller-triage AT amazon.com

**Comment by kishorj** [comment]
@g-dury, I'm closing the issue since we didn't hear back from you. If you have further concerns, feel free to reopen or create a new issue.
