### ISSUE TITLE
[Feature] Update Backend Service status.loadBalancer

### ISSUE THREAD

**Issue by iAnomaly** [kubernetes-sigs/aws-load-balancer-controller#2540]
**Is your feature request related to a problem?**
I covered this in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2347#issuecomment-1058613176 but a blocking limitation for us today is without the ability to create an ALB via Service (Instead of Ingress), there is no mechanism for the Service status.loadBalancer to be updated with the ALB hostname.

This is a formal feature request to add the ability to update any/all backend Services `status.loadBalancer` with the hostname of the Ingress created ALB (much the same way the Ingress `status.loadBalancer.ingress` is currently updated by this controller).

**Describe the solution you'd like**
New annotation (supported both on the `Ingress` and `Service` `Location`?) that causes the Ingress controller to update the backend Service(s) `status.loadBalancer` with the hostname of the ALB in the same way the Ingress controller updates the Ingress `status.loadBalancer.ingress`: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/controllers/ingress/group_controller.go#L205

**Describe alternatives you've considered**
The solution to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2347 would actually be a better/more generic solution to this problem but I'm going to assume the level of effort to take the separate Ingress and Service controllers and merge them together to handle both the Ingress and Service type is not trivial. 😅

**Comment by M00nF1sh** [comment]
@iAnomaly 
A single service might be used by different multiple Ingresses(thus multiple ALBs), thus we cannot do it tbh.

**Comment by M00nF1sh** [comment]
wondering why the "component" you owned has to read from the Service's status instead of Ingress's status to obtains the LB status :D

**Comment by iAnomaly** [comment]
> @iAnomaly A single service might be used by different multiple Ingresses(thus multiple ALBs), thus we cannot do it tbh.

Ya, I don't think this should be the default behavior by any means, but can't we use an annotation to opt-in to this behavior? We could be guard against collision (multiple Ingresses trying to set `status.loadBalancer` on the same Service) via this annotation.

> wondering why the "component" you owned has to read from the Service's status instead of Ingress's status to obtains the LB address :D

This seems to be how Ingress Controllers work. ingress-nginx and traefik ingress controller both work this way. I think because they are designed to manage Ingresses it doesn't make sense to also support reading from an Ingress status for LB. Kubernetes in-tree Service for example is the only way to create an external LB other than this aws-load-balancer-controller if that makes sense?

**Comment by iAnomaly** [comment]
@M00nF1sh Would you consider a PR for this if I work on it?
