### ISSUE TITLE
http to https redirect queries are not showing the expected result with CURL

### ISSUE THREAD

**Issue by rameshar16** [kubernetes-sigs/aws-load-balancer-controller#2541]
Hi All,
I have implemented the HTTP to HTTPS redirect with the ALB Ingress controller. The redirect rule is working fine with the browser, but the same is showing below when running the CURL query instead of the actual response. And, it is working if I add "-L" to the curl. Is there any option to configure HTTP to HTTPS REWRITE  instead of REDIRECT on ALB Ingress?

< HTTP/1.1 301 Moved Permanently
< Server: awselb/2.0
< Date: Tue, 08 Mar 2022 13:19:30 GMT
< Content-Type: text/html
< Content-Length: 134
< Connection: keep-alive

Thanks in advance!!!

Thanks and Regards,
Ramesh

**Comment by kishorj** [comment]
@rameshar16, with http to https redirect, the user agent needs to open a new connection to the new destination and send the request. In your case, your browser automatically does it behind the scenes, and `curl` does it with the `-L` option.

**Comment by rameshar16** [comment]
Hi @kishorj ,
As you said that the connection is working fine in the browser and through CURL with "-L".

We are exposing the API endpoints to the customers and a few of the customers send the connections via CURL as part of the automation/sanity testing. I am looking for any workaround at Ingress to make work the connection via CURL without "-L".

Thanks and Regards,
Ramesh

**Comment by kishorj** [comment]
@rameshar16, the http to https redirect works via http redirect. Either your client follows the redirect implicitly or via a mechanism similar to the curl `-L`. There are no other options in this case. I'm closing the issue.
