### ISSUE TITLE
[Feature] Option to restrict to only Ingress type resources

### ISSUE THREAD

**Issue by thejasn** [kubernetes-sigs/aws-load-balancer-controller#2543]
**Is your feature request related to a problem?**
In a cluster containing other controllers that provision load balancers for `Service` objects of type `loadbalancer` we need a way to restrict the aws-load-balancer-controller to only work on `Ingress` type resources. 

**Describe the solution you'd like**
Expose a command line arg to control this behavior. Something like `--ingressResourceOnly=true` would skip the reconciler setup for services.  

**Describe alternatives you've considered**
NA

**Comment by thejasn** [comment]
Hey @kishorj, Any thoughts or suggestions regarding this? Would be helpful before I start on the implementation. Thanks

**Comment by kishorj** [comment]
@thejasn,
do you run multiple instances of the lb controller in the same cluster?

Also, the controller already supports load-balancer-class, so you could use the load-balancer-class on your service resources instead of annotation.

**Comment by thejasn** [comment]
@kishorj Yeah, we will be running multiple instances of the aws load balancer controller in a cluster. SO basically we want to restrict to only `Ingress` resources and not have the controller process any `Service` type resources that are created. 

Utilizing the `--load-balancer-class` would help partially, but since it also requires a `LoadBalancerClass` to be added to the service spec, we can't exactly as users to provide valid value even though their service has nothing to do with it. 

One workaround could be modifying the checks here to consider empty load-balancer-class as not supported. And then maybe we can work with that.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/c4471defda10f8184173192b9f9df4e411ee5dac/pkg/service/service_utils.go#L54-L60

**Comment by thejasn** [comment]
Fixed by #2579
