### ISSUE TITLE
ingress controller fails to build model with AccessDeniedException for acm:ListCertificates 

### ISSUE THREAD

**Issue by divick** [kubernetes-sigs/aws-load-balancer-controller#2545]
**Describe the bug**
I have a k8s cluster created with kops and aws-load-balancer installed as part of kops addons. In my case I am not using kube2iam instead I am directly attaching the iam_policy to the nodes but for some reason the ingress fails to build the model with the following warning:

```
Warning  FailedBuildModel  10m  ingress  Failed build model due to ingress: production/production-rabbitmq: AccessDeniedException: User: arn:aws:sts::xxxxxx:assumed-role/masters.production.xxxxx.com/i-03f7fa18f5141864b is not authorized to perform: acm:ListCertificates
```

**Steps to reproduce**
1. Create a kops cluster with 1.21.4 with aws-load-balancer-controller addon i.e.  awsLoadBalancerController: true in the cluster definition yaml file.
2. Create an ingress and the issue will manifest.

**Expected outcome**
I expected the alb to have been created as a result.

**Environment**
k8s cluster created using kops 

* AWS Load Balancer controller version 2.2.0
* Kubernetes version -- 1.21.7
* Using EKS (yes/no), if so version? -- NO

**Additional Context**:
I don't understand why does ingress try to get sts token with role assumed to be of master instead of node. I have attached the iam policy to the nodes and not the masters.

**Comment by kishorj** [comment]
@divick, could you check if the lb controller pods are running on mater instance when installed via kops addon? If so, then the policy need to be attached to the master node.

**Comment by divick** [comment]
@kishorj yes the conroller pod runs on the master instance. But I don't see anywhere in kops docs that the permissions are to be applied to master nodes.

I think I see the real problem. If I don't specify the certificate then the controller needs access to ACM to list certificates so as to list and apply the appropriate matching certificate. My problem only manifested when I did not annotate the ingress with certificate arn.

I think the docs definitely needs updating.
