### ISSUE TITLE
EKS sg opens ports for lb across all nodes rather than nodepool specific to deployment

### ISSUE THREAD

**Issue by ragarcia26** [kubernetes-sigs/aws-load-balancer-controller#2548]
**Is your feature request related to a problem?**
"I'm frustrated when:" I create a service thats for a deployment tied to nodepool "A" but the sg for the lb is shared across all subnets regardless of nodes and thus are opened against nodes that don't host the deployment no need that security posture. I've added `service.beta.kubernetes.io/aws-load-balancer-target-node-labels:` to improve performance of loadbalancing to target those nodes only.  

**Describe the solution you'd like**
A way to limit SG rules to nodepool rather than the eks sg

**Describe alternatives you've considered**
`service.beta.kubernetes.io/aws-load-balancer-target-node-labels:` only removes nodes from targets. 
`service.beta.kubernetes.io/load-balancer-source-ranges` isn't realistic as the source range includes the AWS network

**Comment by kishorj** [comment]
@ragarcia26, the controller looks for the cluster name tag in the security group - it expects only one SG with the tag. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/#security-group

You could remove the cluster tag from the EKS SG, and add a cluster tag on the SG dedicated to each node group. Note the instance can have only one security group with the cluster tag.
