### ISSUE TITLE
no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1"

### ISSUE THREAD

**Issue by laurecs** [kubernetes-sigs/aws-load-balancer-controller#2551]
**Describe the bug**
Getting the following error:

`error: unable to recognize "aws-load-balancer-controller.yaml": no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1"`

**Steps to reproduce**
Provisioning  Load Balancer Controller based on the guide below, with Kubernetes manifest.

https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html

The images are successfully pulled from the local ECR repo.

`kubectl apply -f aws-load-balancer-controller.yaml`

**Expected outcome**
Did not expect the error.

**Environment**

* AWS Load Balancer controller version - 2.4.0
* Kubernetes version
* Using EKS (yes/no), if so version? 1.21

**Additional Context**:

The controller gets installed, here is the output:

`
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
aws-load-balancer-controller   1/1     1            1           77s
`

Getting related error when deploying the 2048 game application:

`
Error from server (invalid ingress class: IngressClassParams.elbv2.k8s.aws "alb" not found): error when creating "2048.yaml": admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: IngressClassParams.elbv2.k8s.aws "alb" not found
`

Full output on deployment:

`customresourcedefinition.apiextensions.k8s.io/ingressclassparams.elbv2.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/targetgroupbindings.elbv2.k8s.aws created
role.rbac.authorization.k8s.io/aws-load-balancer-controller-leader-election-role created
clusterrole.rbac.authorization.k8s.io/aws-load-balancer-controller-role created
rolebinding.rbac.authorization.k8s.io/aws-load-balancer-controller-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/aws-load-balancer-controller-rolebinding created
service/aws-load-balancer-webhook-service created
deployment.apps/aws-load-balancer-controller created
certificate.cert-manager.io/aws-load-balancer-serving-cert created
issuer.cert-manager.io/aws-load-balancer-selfsigned-issuer created
mutatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook created
ingressclass.networking.k8s.io/alb created
error: unable to recognize "aws-load-balancer-controller.yaml": no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1"
`
Pods and services:
`
NAMESPACE      NAME                                            READY   STATUS    RESTARTS   AGE
cert-manager   cert-manager-774c895d95-7p2cv                        1/1     Running   0          170m
cert-manager   cert-manager-cainjector-76dc78cf46-4zxkz         1/1     Running   0          170m
cert-manager   cert-manager-webhook-759dfbcb9c-jx6fv            1/1     Running   0          170m
kube-system    aws-load-balancer-controller-6b9ff64474-lt6vk    1/1     Running   0          129m
kube-system    aws-node-4g2h2                                                   1/1     Running   0          4d5h
kube-system    aws-node-4lzrr                                                      1/1     Running   0          30h
kube-system    aws-node-dmxgg                                                  1/1     Running   0          30h
kube-system    aws-node-j746v                                                    1/1     Running   0          30h
kube-system    aws-node-k24rh                                                   1/1     Running   0          30h
kube-system    aws-node-r65xb                                                   1/1     Running   0          4d5h
kube-system    aws-node-spfzj                                                    1/1     Running   0          4d5h
kube-system    aws-node-t6gx7                                                   1/1     Running   0          30h
kube-system    aws-node-t8l67                                                    1/1     Running   0          30h
kube-system    coredns-65ccb76b7c-97xcv                                 1/1     Running   0          4d7h
kube-system    coredns-65ccb76b7c-bck8f                                  1/1     Running   0          4d7h
kube-system    kube-proxy-67g2n                                                1/1     Running   0          30h
kube-system    kube-proxy-clpdw                                                 1/1     Running   0          30h
kube-system    kube-proxy-fvhjb                                                   1/1     Running   0          30h
kube-system    kube-proxy-jlj9b                                1/1     Running   0          30h
kube-system    kube-proxy-jnfjd                                1/1     Running   0          4d5h
kube-system    kube-proxy-rkq8v                                1/1     Running   0          30h
kube-system    kube-proxy-rrd2x                                1/1     Running   0          30h
kube-system    kube-proxy-smc88                                1/1     Running   0          4d5h
kube-system    kube-proxy-v6hjp                                1/1     Running   0          4d5h

                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
cert-manager   cert-manager                                       ClusterIP   172.20.28.194    <none>        9402/TCP        171m
cert-manager   cert-manager-webhook                        ClusterIP   172.20.207.252   <none>        443/TCP         171m
default        kubernetes                                                 ClusterIP   172.20.0.1       <none>        443/TCP         4d7h
kube-system    aws-load-balancer-webhook-service    ClusterIP   172.20.98.224    <none>        443/TCP         130m
kube-system    kube-dns                                               ClusterIP   172.20.0.10      <none>        53/UDP,53/TCP   4d7h
`

**Comment by slavikbialik** [comment]
I just experienced the same issue. I found this solution.
First update the CRDs and then try to apply again:
`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"`

**Comment by kishorj** [comment]
@laurecs, if you ran helm upgrade, then the CRDs will not be updated, you will have to update them manually. Were you able to fix your issue by applying the CRDs?

**Comment by laurecs** [comment]
Solved. Thanks

**Comment by morariu** [comment]
> I just experienced the same issue. I found this solution. First update the CRDs and then try to apply again: `kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"`

How is this solved in a private network then? I am not using Helm.

**Comment by morariu** [comment]
> @laurecs, if you ran helm upgrade, then the CRDs will not be updated, you will have to update them manually. Were you able to fix your issue by applying the CRDs?

@kishorj any suggestions on how to fix this in a network without internet access and without helm? I don't understand why the AWS is off - this is not an upgrade but a new installation. Thanks

**Comment by kishorj** [comment]
@morariu, the CRDs are included in the manifest. To overcome the error, you can either:
- apply the manifest again
or
- separate the `IngressClassParams` and `IngressClass` from the manifest and apply subsequently

**Comment by stozinho** [comment]
I was hit by v similar issue yesterday:

`Failed deploy model due to the server could not find the requested resource (post targetgroupbindings.elbv2.k8s.aws)`

Fix was same as outlined above: 
`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"`

I am running version 2.4.1 of the Image. Seeing as this issue closed does that mean that it has been resolved?

**Comment by hanamurayuki** [comment]
Now, github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master is 404.

Below command solves this error.
`kubectl apply -f v2_7_2_full.yaml` <-- As usual
`kubectl apply -f v2_7_2_ingclass.yaml` <-- This one 

YAML exists in https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.7.2
