### ISSUE TITLE
A Certificate Validation Error

### ISSUE THREAD

**Issue by igory-bwr** [kubernetes-sigs/aws-load-balancer-controller#2552]
A ingress doesn't get up and produces an error message in a aws-load-balancer-controller pod log:

``` 
{"level":"error","ts":1647361971.0844,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"test-app","namespace":"test-app","error":"ValidationError: Certificate ARN 'arn:aws:acm:eu-west-1:********:certificate/ee2c420e-d744-465d-8789-90ad5ec1115d' is not valid\n\tstatus code: 400, request id: 6173b0bd-8e5c-4bdc-a7d5-604649bd9095"}
```
I cannot figure out how to get what's exactly wrong with the certificate. What does `status code: 400` mean? 
Is there any external tool to make preliminary validation for certificates?

**Comment by kishorj** [comment]
@igory-bwr
Could you verify the following
- whether the certificate has expired
- if the certificate resource is from a different region

**Comment by igory-bwr** [comment]
@kishorj Thanks a lot. 

It was my bad. I didn't update a kubectl context and the app was deployed to the cluster on another region. But the error message is really confusing. 
A non-validity for me proposes a presence. 

Also I've noticed that a certificate auto discovery get blocked if it find out more than one matching certificates. I suppose an issuing warning would be more consistent behavior for this case. 
Anyway, thanks
