### ISSUE TITLE
ingress routing issue not picking up the existing ALB address 

### ISSUE THREAD

**Issue by saiajay15** [kubernetes-sigs/aws-load-balancer-controller#2556]
![image](https://user-images.githubusercontent.com/88763124/158675863-84164bbe-c2b8-492e-a8bb-ce85b60da110.png)
After deleting this address in ALB it picking up same address as host name even after deleting .

Firstly I deleted the inactive alb in aws console then deleted the ingress completely and deployed again eventhough it is picking the same inactive alb.
Please can anyboady help me on this How can the ingress pick the active alb.

**Comment by kishorj** [comment]
@saiajay15, did you tag the ALB with the tags for the ingress? The v2 version of the controller identifies ALB based on the AWS resource tags, not the name. What is the version of your aws-load-balancer-controller?

**Comment by kishorj** [comment]
@saiajay15, I'm closing the issue. If you have further concerns, feel free to reopen or create a new issue.
