### ISSUE TITLE
LB SG tagged on nodes SG 

### ISSUE THREAD

**Issue by FernandoMiguel** [kubernetes-sigs/aws-load-balancer-controller#2557]
Very new to this controller so apologies if this question is already answered somewhere.

This controller has the ability to create a SG per LB to then allow nodes inbound traffic from the ALB ENI.

But how do nodes know that SG id given their SG is created at cluster creation time?

Also, fargate nodes inherit their SG from the EKS cluster SG, not the EKS manage nodes, making this further muddy waters.

My current alternative is to create an extra. SG during cluster setup and then pass it along to the controller. 

Thanks in advance.

**Comment by kishorj** [comment]
@FernandoMiguel, in case the controller auto-generates an ALB security group, or if you configure management of security group rules [[via annotation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#manage-backend-security-group-rules)], controller updates cluster-tagged the security group attached to the EC2 instance or the ENI.

Cluster tag is of the form:

Key | Value
-- | --
kubernetes.io/cluster/${cluster-name} | owned or shared

**Comment by FernandoMiguel** [comment]
Found a new issue.
```
2022-03-22T10:58:28.591992732Z {"level":"error","ts":1647946708.5919392,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"k8s-awslbc-echoserv-6c16dd3b83","namespace":"awslbc","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/ec2-organic-teal for eni eni-02098466afa77f350, got: [sg-00b6e774e405b189f sg-0279a1ec89f69a6d1 sg-07b7c76edfdbb8930]"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ```

our ec2 eks managed nodes have several SGs attached due to SG rules limit.

**Comment by kishorj** [comment]
@FernandoMiguel, in case you have multiple SG attached to your instance/ENI, controller expects one SG with the cluster tag. If none of the SGs have the cluster tag, or more than one SG are tagged, controller will not be able to reconcile further.

**Comment by FernandoMiguel** [comment]
@kishorj is this a design pattern? a hard limit of the controller?
i worked around by only tagging one of the SGs, but feels kinda weird and might bite us on the rear in the future.

thanks for the help

**Comment by kishorj** [comment]
This is a design choice to make it consistent with the kubernetes in-tree controller. We are thinking about supporting multiple tagged SG in future releases - issue #2367

**Comment by kishorj** [comment]
closing the issue.

**Comment by kaykhancheckpoint** [comment]
> Found a new issue. our ec2 eks managed nodes have several SGs attached due to SG rules limit.
> 
> ```
> 2022-03-22T10:58:28.591992732Z {"level":"error","ts":1647946708.5919392,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"k8s-awslbc-echoserv-6c16dd3b83","namespace":"awslbc","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/ec2-organic-teal for eni eni-02098466afa77f350, got: [sg-00b6e774e405b189f sg-0279a1ec89f69a6d1 sg-07b7c76edfdbb8930]"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ```
> ```

Im having the same problem now, can you detail how you fixed this issue?

**Comment by argais** [comment]
Just ran into this exact same issue :/ is there any available work around?
