### ISSUE TITLE
Ingress fails for some hyphened hostnames

### ISSUE THREAD

**Issue by samsilborydoxo** [kubernetes-sigs/aws-load-balancer-controller#2561]
I have a few legacy apps that use internal hosts with hyphens.  This to my understanding is a valid hostname, but the ALB ingress bails with a dash in the name if that name is short.

Example:
sam@sam-bastion:~ kubectl apply -f 1.yaml
ingress.networking.k8s.io/foo created
sam@sam-bastion:~ kubectl describe ingress foo
Name:             foo
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  foo.com
              /   foo:12443 (<error: endpoints "foo" not found>)
  foo-bar
              /   foo:12443 (<error: endpoints "foo" not found>)
Annotations:  alb.ingress.kubernetes.io/scheme: internal
              alb.ingress.kubernetes.io/target-type: ip
              kubernetes.io/ingress.class: alb
Events:
  Type     Reason             Age   From     Message
  ----     ------             ----  ----     -------

  Warning  FailedDeployModel  3m24s (x8 over 8m56s)  ingress  (combined from similar events): Failed deploy model due to failed to create listener rule: ValidationError: Condition value 'foo-bar' contains a character that is not valid
           status code: 400, request id: 658917de-6b87-4df4-b467-04e5309b663b
sam@sam-bastion:~$ cat 1.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    app: foo
  name: foo
  namespace: default
spec:
  rules:
  - host: foo.com
    http:
      paths:
      - backend:
          service:
            name: foo
            port:
              number: 12443
        path: /
        pathType: Prefix
  - host: foo-bar
    http:
      paths:
      - backend:
          service:
            name: foo
            port:
              number: 12443
        path: /
        pathType: Prefix

sam@sam-bastion:~ kubectl get pods -n kube-system aws-load-balancer-controller-9b4b65cd9-rx46q -o yaml  |grep image:
    image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.4.0
    image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.4.0
    
  This works with host names like foo-bar.example.com or foo-bar.com.

**Comment by kishorj** [comment]
@samsilborydoxo, this error is from AWS not from the controller. As per the AWS ALB doc https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#host-conditions, you must include at least one "." character for the host condition and you can include only alphabetical characters after the final "." character.

**Comment by kishorj** [comment]
@samsilborydoxo, I'm closing the issue. This is enforced by the AWS, not an issue on the controller side. If you have further concerns, feel free to reopen or create a new issue.
