### ISSUE TITLE
RevokeSecurityGroupIngress responsible for SG inbound rules getting deleted 

### ISSUE THREAD

**Issue by zeevMetz** [kubernetes-sigs/aws-load-balancer-controller#2578]
We're running our AWS-LB-Controller (using NLB for FTP service with few passive ports and one active port). Now, we encounter an issue where Security Group inbound rules are deleted (SG rules with `elbv2.k8s.aws/targetGroupBinding=shared` description). Looking at CloudTrail we see that `ec2:RevokeSecurityGroupIngress` in our IAM role is responsible for that, we removed it from our IAM role but then for some reason when pods restarted, we're getting unhealthy health-check and looking at the aws-lb-controller logs we see

`{"level":"error","ts":1648057864.807936,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"k8s-ferefact-ftplet-090bfc06bc","namespace":"fe-refactor-ftplet","error":"UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: "}`

I'm using this IAM role https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json
Restating the aws-lb-controller pods in `kube-system` fix it

**Expected outcome**
SG inbound rules shouldn't be deleted

* AWS Load Balancer controller version = v2.3.1
* Kubernetes version = v1.21.5
* Using EKS (yes/no), if so version? yes
* Helm Chart version = 1.3.2

**Comment by kishorj** [comment]
@zeevMetz, the aws lb controller requires the IAM permission to manage security group rules for traffic. If you remove the iam permission, controller will continue to log error messages, restarting controller will not fix.

The controller removes the security group ingress rules when it determines the rules are no longer necessary for your service. Did you delete the services?

**Comment by zeevMetz** [comment]
@kishorj Thanks for your response. 
When adding `ec2:RevokeSecurityGroupIngress` back to IAM role, at some point the health-check is unhealthy (the service itself is up), looking at the SG inbound rules of that node I do see that the rules added by the aws lb controller are missing which causes the health-check to become unhealthy. 
any idea what causing that?

**Comment by kishorj** [comment]
The controller automatically adds the necessary rules for traffic access and health check. You could force a reconcile by either modifying the service or restarting the controller - see if the controller configures the SG rules. The SG rules with the comment `elbv2.k8s.aws/targetGroupBinding=shared` should be managed only by the controller.

**Comment by zeevMetz** [comment]
@kishorj  Yes, I do see `elbv2.k8s.aws/targetGroupBinding=shared` tag with the correct port in our SG inbound rule.
![Screen Shot 2022-03-24 at 19 34 12](https://user-images.githubusercontent.com/43029743/159976663-7273a378-89e6-4117-bcfd-009afdc8def2.png)

But as I mentioned earlier, at some point the controller for some reason revoking those rules (the service itself is still running) and the health checks are in unhealthy status.
Any thoughts on what might cause this?

**Comment by kishorj** [comment]
do you happen to run multiple instances of the controller in the same cluster, or share the security group across multiple clusters in the same vpc?

**Comment by zeevMetz** [comment]
@kishorj yes I run 2 instances of the controller in `kube-system` namespace. The security group is shared with all our worker nodes in one cluster

**Comment by M00nF1sh** [comment]
@zeevMetz 
When you say 2 instance, do you mean two deployment?
We only support one deployment of the controller, which can have 2 or more Pod under leadership-election.

If you have multiple deployment, then the controllers will conflicts each other, since each one will reconcile the worker SG rules based on its own set of Ingresses/Services.

We have a on-going feature request to support multiple deployment.

**Comment by zeevMetz** [comment]
@M00nF1sh 
Sorry for misleading you, I meant 2 replicas and on deployment (edit the [thread](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2578#issuecomment-1079916321))

**Comment by kishorj** [comment]
@zeevMetz, would you be able to email the controller logs to k8s-alb-controller-triage AT amazon.com?
Also check in your cloud trail for the RevokeSecurityGroupIngress call to check the user-agent of the component making the call.

**Comment by j-bruce** [comment]
I'm seeing this exact same issue using 2.6.0 and 2.61.

**Comment by ognjen-it** [comment]
I'm seeing the issue using helm 1.13.4 and app v2.13.4
