### ISSUE TITLE
More than 2 million replicas without explanation

### ISSUE THREAD

**Issue by luisvillalobossalgado1987** [kubernetes-sigs/aws-load-balancer-controller#2580]
Without apparent cause, suddenly aws ingress controller created mor than 2 million replicas (march 24, 00:14 aprox. GMT-3) causing unresponsive node group ("Degraded" warning message) and impossibility to recover worker nodes. We had to scale the number of nodes in the cluster to 0 and associate a new target group with larger machines in order to recover the functionality of the kubernetes cluster and finally uninstall aws-load-balancer-controller.

<img width="1792" alt="aws-load-balancer-controller" src="https://user-images.githubusercontent.com/72559915/159937983-c930058f-8571-4301-ad4e-68e613484639.png">

Today our kubernetes cluster doesn't have aws-load-balancer-controller, we removed it to get it working again. However, we have many kubernetes ingresses that define access to our services. We need to know 2 things:
- If we reinstall aws-load-balancer-controller, will it be able to autodetect the ingress created?
- How do we prevent the incident from happening again?

**Environment**

* AWS Load Balancer controller: v2.2
* Kubernetes: v1.21
* Elastic Kubernetes Service: eks.4 

The aws-load-balancer-controller deployment yaml is attached. Except for the cluster name, it should be identical to the one that generated the problem.

[aws-load-balancer-controller-qa.md](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/8342712/aws-load-balancer-controller-qa.md)

**Comment by kishorj** [comment]
The default replicas for helm chart is 2. Configuring more replicas for lb controller doesn't help since only one is actively reconciling, others wait for the leader election lock.

If you reinstall aws-load-balancer-controller, the existing ingresses/services will continue to work fine if you use the same ingress class configuration. The replicas scaling is not due to controller, it is likely due to an external component trying to scale up the deployment.

**Comment by M00nF1sh** [comment]
@luisvillalobossalgado1987

We don't have any logic that could scale the controller replica. So it must from an external component as @kishorj mentioned.
Could check your control plane logs to verify which entity scaled it? (If u didn't enabled control plane logs, you can cut a support ticket to EKS)

**Comment by absalon-blue** [comment]
@M00nF1sh 

Hi, 

(I'm coworker with @luisvillalobossalgado1987 )

Sadly logs were not enabled a that time. Only clue that we have now, we got several and consecutive error logs from aws-load-balancer-controller PODs like that:

`I0324 02:12:24.735675       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/aws-load-balancer-controller-leader...
`
![Captura de Pantalla 2022-03-31 a la(s) 02 14 44](https://user-images.githubusercontent.com/82412270/160983133-2c74de48-8fdd-41da-8f62-bcd11d542640.png)

As you can see in the image, there are millisecond between them. Sounds like an anomalous behaviour

**Comment by kishorj** [comment]
@luisvillalobossalgado1987, I'm closing the issue. If you still encounter problems, please cut a support ticket to EKS for further investigation. If you have further concerns, feel free to reopen or create a new issue.
