### ISSUE TITLE
"error":"CertificateNotFound: Certificate 'arn:aws:acm:us-east-2:xxxx:certificate/xxx' not found status code: 400

### ISSUE THREAD

**Issue by vitarkah** [kubernetes-sigs/aws-load-balancer-controller#2581]
**Describe the bug**
"error":"CertificateNotFound: Certificate 'arn:aws:acm:us-east-2:xxx:certificate/xxxx' not found\n\tstatus code: 400

**Steps to reproduce**
`---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:xxx:certificate/xxxx
    alb.ingress.kubernetes.io/conditions.argogrpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]    
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  name: argocd
  namespace: argocd
spec:
  rules:
  - host: argocd.domain
    http:
      paths:
      - backend:
          serviceName: argogrpc
          servicePort: 443
        pathType: ImplementationSpecific
      - backend:
          serviceName: argocd-server
          servicePort: 443
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - argocd.domain`

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
*aws-load-balancer-controller:v2.4.1

* Kubernetes version
1.21

* Using EKS (yes/no), if so version?
Yes. 1.21

**Additional Context**:
aws --region us-east-2 acm describe-certificate --certificate-arn 'arn:aws:acm:us-east-2:xxx:certificate/xxx' 
returns the certificate just fine.

**Comment by kishorj** [comment]
@vitarkah, could you verify the following 
- whether the certificate has expired
- if the certificate resource is from a different region than the eks cluster

**Comment by vitarkah** [comment]
@kishorj 
- certificate appears to be expired.  Guess this might be it
- It is from same region (us-east-2).  But I need to check somethi

**Comment by vitarkah** [comment]
The certificate turned out to be expired. However there is an opportunity to update the error message it feasible.  Not found was misleading and ended up going down the wrong path. Closing this issue out. Thanks for your question @kishorj !!
