### ISSUE TITLE
How to add the health-check path per target group?

### ISSUE THREAD

**Issue by rameshar16** [kubernetes-sigs/aws-load-balancer-controller#2583]
Hi All,
Is it possible to add the health check path per target group instead of passing via annotations?

Thanks and Regards,
Ramesh

**Comment by kishorj** [comment]
Here are the current options for health check configuration:
1. Do nothing; controller configures the the traffic-port as the health check port
2. Specify annotation; this will configure the specified port/protocol/path for all target group health checks
3. Create targetgroupbinding; you create a LB target group, configure the health check manually and use targetgroupbinding to bind it to a k8s service

**Comment by M00nF1sh** [comment]
You can also specify the health-check annotations on Service Instead of Ingress, these annotations on Service takes priority than Ingress.

**Comment by kishorj** [comment]
@rameshar16, I'm closing the issue since the recommendation from @M00nF1sh should help you configure separate health check per target group. If you have further concerns feel free to reopen or create a new issue.
