### ISSUE TITLE
aws alb-controller going to CrashLoopBackOff state 

### ISSUE THREAD

**Issue by Pra9jha** [kubernetes-sigs/aws-load-balancer-controller#2584]
* kops version: 1.22.4 / 1.22.2 
* kubectl version --client : v1.22.4 
* alb-controller version : v2.2.1 / v2.4.1 and v2.3.1
* Created IAM policy and attached to the worker-node IAM-roles
* We have also created cert managers certificates

**Error message :** 
{"level":"info","ts":1648193174.6142926,"msg":"version","GitVersion":"v2.3.1","GitCommit":"1d492cb8648b2053086761140d9db9236f867237","BuildDate":"2021-12-08T18:13:11+0000"}
{"level":"error","ts":1648193177.7583256,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect vpcID from EC2Metadata, specify --aws-vpc-id instead if EC2Metadata is unavailable: EC2MetadataError: failed to make EC2Metadata request\n\n\tstatus code: 401, request id: "}

**Note** : we are not using Fargate therefore should not be asking for '--aws-vpc-id' , even if we provide '--aws-vpc-id' and '--aws-region' error changes but the issue continues .

**Error after adding vpc-id and region** : NoCredentialProviders: no valid providers in chain.

Thanks and Regard ,
Prashant Jha

**Comment by kishorj** [comment]
@Pra9jha,
If you use kops, you'd need to ensure the hop limit is at least 2 on your node igs for IMDSv2 to work, for example

kops edit ig --name=$NAMAE nodes-<az>

```
  instanceMetadata:
    httpPutResponseHopLimit: 2
    httpTokens: required

```

Would you be able to share the log entry corresponding to the `NoCredentialProviders: ...` error

**Comment by kishorj** [comment]
@Pra9jha, I'm closing the issue. If you have further concerns feel free to reopen or create a new issue.
