### ISSUE TITLE
alb.ingress.kubernetes.io/security-groups Annotations alone don't work.

### ISSUE THREAD

**Issue by KimSeongIl** [kubernetes-sigs/aws-load-balancer-controller#2586]
**Describe the bug**
A concise description of what the bug is.

**Steps to reproduce**

I have alb.ingress.kubernetes.io/security-groups: sg-040eb82467a2e4f3b
I am trying to add a security group using annotations.

However, adding sg-040eb82467a2e4f3b to the inbound rule of the node group does not work.
I get a 504 gateway response.

alb.ingress.kubernetes.io/manage-backend-security-group-rules: 'true'

When I add the annotations it works, but I don't know the difference between the automatically created security group and the one I added manually.

Do I have to always use the 
alb.ingress.kubernetes.io/manage-backend-security-group-rules: 'true' 
annotation to make it work?

**Expected outcome**
I want it to work with the security group I created. This is because automatically created security groups cannot be tagged automatically.

**Environment**

* AWS Load Balancer controller version: 1.4.1
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes

**Additional Context**:

**Comment by kishorj** [comment]
@KimSeongIl, automatically created security groups will get deleted by the controller when no longer needed. If you don't specify security groups annotation, controller creates a frontend SG which specifies the client CIDRs that can access the LB, and a shared backend SG which is used to allow the loadbalancer traffic to your application pods.

If you specify security groups annotation, controller will not manage the backend security group rules by default. You will need to create the necessary ingress rules on your instance/ENI security groups. If you specify the `alb.ingress.kubernetes.io/manage-backend-security-group-rules` as true, controller will manage the backend rules for you.

In your case, you can either manage the backend ingress rules yourself, or let the controller manage them via annotation.

**Comment by kishorj** [comment]
@KimSeongIl, I'm closing the issue. If you have further concerns, feel free to reopen or create a new issue.
