### ISSUE TITLE
Listener and listener-rule AWS tagging records leak when deleting an ALB

### ISSUE THREAD

**Issue by tyrken** [kubernetes-sigs/aws-load-balancer-controller#2588]
We have a simple non-shared ALB per ingress system, and recently noticed when cleaning up an old cluster (with ALBC v2.3.0) that a number of minor AWS resources had leaked.  E.g. if you run the below (with a suitable replacement for `myclustername`) you can see all the LB resources for a cluster created by this controller:

```bash
aws resourcegroupstaggingapi get-resources --tag-filters "Key=elbv2.k8s.aws/cluster,Values=myclustername" --query ResourceTagMappingList[].ResourceARN
```

If you then delete an ingress that originally created an ALBs (i.e. not just a TargetGroup via the CRD), the "loadbalancer" and "targetgroup" resources are deleted, but not the "listener" or "listener-rule" ones.

The controller pod logs show creation log lines for the listener/rule resource but no matching deletion log entry unlike for loadbalancer/targetgroup.  No other errors visible apart from a "Reconciler error" that it can't find the load-balancer (that it deleted a few millisecs ago so might be expected!)

**Environment**

* AWS Load Balancer controller version: 2.3.0 but I also saw this with a test cluster on 2.4.1
* Kubernetes version: 1.20
* Using EKS: yes, latest 1.20 platform version

**Comment by M00nF1sh** [comment]
@fargue 
@tyrken 
We only deletes the LoadBalancer when deleting the Ingresses. The Listener/ListenerRules should automatically be deleted when the LoadBalancer is deleted.

I suspect it's eventually consistency issue with resourcegroupstaggingapi, can you confirm whether these resources eventually go away or stuck in your account?

**Comment by tyrken** [comment]
According to AWS support the listener/listener-rule resources themselves are deleted when the loadbalancer is, but the `resourcegrouptaggingapi` records get left behind.  They don't seem to get cleared up (at least we have some that are at a guess months old) ever.

`aws elbv2 describe-listeners` fails for the listener resource ARNs found.  Interestingly you can `aws elbv2 delete-rule` one of the listener-rule ARNs repeatedly without error.  Doing so does clean up the `resourcegroupstaggingapi` record for that resource type but nothing gets through for the listener ones.

**Comment by kishorj** [comment]
This appears to be an issue on the resource tagging apis. We are following up with the ELB team for further investigation.
