### ISSUE TITLE
Target service need not be of type NodePort

### ISSUE THREAD

**Issue by irl-segfault** [kubernetes-sigs/aws-load-balancer-controller#2589]
**Describe the bug**
The official docs mention that the backing `Service` to which an Ingress routes must be of type NodePort.   However, all works if the service is of type `ClusterIP` as well.  

**Steps to reproduce**
Create resources specified in the [official example](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/examples/2048/2048_full_latest.yaml) but edit the `service-2048` service to be of type `ClusterIP`

**Expected outcome**
Would expect things not to work, but they do.

**Environment**
EKS

* AWS Load Balancer controller version  2.4.1
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? Yes v1.21

Opening this "bug" to clear up whether or not services *need* to be type `NodePort`.  I believe most users would prefer to use `ClusterIP`, and i indeed this is a valid service type (as it appears to be) the docs should be updated to reflect this.

Thanks!

**Comment by kishorj** [comment]
@irl-segfault 
Type `NodePort` is required for instance targets, live docs link - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/how-it-works/#instance-mode

For IP targets `ClusterIP` is sufficient. The official example specifies ALB with IP target, so your change to `ClusterIP` does not have effect.

**Comment by irl-segfault** [comment]
Awesome, thanks for clarifying.
