### ISSUE TITLE
disable-ingress-class-annotation doesnt get enforced when editing existing ingress object 

### ISSUE THREAD

**Issue by kousik93** [kubernetes-sigs/aws-load-balancer-controller#2591]
**Describe the bug**
When editing an existing valid ingress object, disable-ingress-class-annotation isn't enforced and allows adding the ' kubernetes.io/ingress.class' annotation

**Steps to reproduce**

- Pass the flag to controller to disable ingress class annotation (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/configurations/#disable-ingress-class-annotation)
- Create a valid ingress object in cluster
```
$ cat ing.yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: "internal"
  labels:
    app: test
  name: test-ingress
  namespace: ieng
spec:
  ingressClassName: external
  rules:
  - host: test-app.example.com
    http:
      paths:
      - backend:
          service:
            name: test-app
            port:
              number: 8000
        pathType: ImplementationSpecific
```
```
$ kubectl apply -f ing.yaml
ingress.networking.k8s.io/test-ingress created
```
- Now edit the ingress object to add the ingress class annotation
```
$ kubectl -nieng annotate ing test-ingress "kubernetes.io/ingress.class=internal"
ingress.networking.k8s.io/test-ingress annotated
```

**Expected outcome**
When annotating the existing ingress, the change should have failed and thrown error

**Environment**

* AWS Load Balancer controller version - v2.3.1
* Kubernetes version - 1.21
* Using EKS (yes/no), if so version? - Yes, eks.4

**Additional Context**:
When applying a new ingress object with the annotation, it fails as expected, but when editing existing object, adding the annotation is allowed

**Comment by M00nF1sh** [comment]
@kousik93 
The ```disable-ingress-class-annotation``` is designed to prevent users to use "alb" as  `kubernetes.io/ingress.class` only.  Thus it can used to force users to use IngressClass if user want to leverage the AWSLoadBalancerController's functionality.

However, it's not intended to block other ingress class annotation like "nginx", and in your case it's using "internal"

**Comment by kousik93** [comment]
@M00nF1sh  Here, im applying an ingress object for the first time, with both ingressClassName and the annotation present. 
This gets blocked with the following error as expected
```
$ kubectl apply -f ing.yaml 
The Ingress "test-ingress" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "internal": can not be set when the class field is also set
```
However, adding the ingress object without the annotation and then editing the object to add the annotation works. 
This scenario should also be prevented as the expectation is to not have annotation & ingressClassName set together at any point in time

**Comment by M00nF1sh** [comment]
@johngmyers 
> In this example, internal is an IngressClass that is backed by LBC.  the `internal` specified via `kubernetes.io/ingress.class` won't be linked to to the `IngressClass` Resource. If you don't setup a controller that watches for Ingress with `kubernetes.io/ingress.class: internal` annotation, then that Ingress will became no-op. So you cannot use any LBC backed IngressClass through that annotation. The only exception is `kubernetes.io/ingress.class: alb`, which will be blocked. Note, (even this `alb` in the annotation is not linked to the `alb` IngressClass resource. IngressClass are only linked through spec.IngressClassName).

@kousik93 
The error you got is [from Kubernetes instead of this controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L250). This controller itself don't prevent you to set both IngressClassName and `kubernetes.io/ingress.class` annotation. (and `kubernetes.io/ingress.class` annotation takes priority than IngressClassName).

**Comment by kishorj** [comment]
@kousik93, I'm closing the issue for now. If you have further concerns regarding this matter, feel free to reach out to us.
