### ISSUE TITLE
Support for setting minimum TLS version

### ISSUE THREAD

**Issue by dalgibbard** [kubernetes-sigs/aws-load-balancer-controller#2593]
I see in the recent PR https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2394 we've got the TLS version updated to 1.2 -- this is great, but still includes some weaker ciphers which are not permitted in strict environments (such as 64bit CBC or 3DES ciphers).
To work around this, I've found the simplest solution for other products (example: Kubernetes Metric Server or Keda) is to set the additional arg of ```--tls-min-version=VersionTLS13``` (This saves messing with long cipher strings etc).

It seems that this flag is not supported by AWS Load Balancer Controller however; as well as the Helm chart not supporting the passing of extra/custom args.

**Describe the solution you'd like**
* A means to set the Minimum TLS version to something other than default (or make TLS 1.3 the default)
* Allow this to be settable via the Helm chart - either by extra arg/flag, or environment variable.

**Describe alternatives you've considered**
N/A

**Comment by kishorj** [comment]
@dalgibbard, We already set the TLS to 1.3 in v2.4.1 patch release. PR #2547

**Comment by dalgibbard** [comment]
Ah I thought I saw that; but when I searched closed PRs for "TLS" it didn't show up 🤦 Thank you! Will close.
