### ISSUE TITLE
Question about ALB configuration for proxy read timeout and request and response file size limit?

### ISSUE THREAD

**Issue by newwuhan5** [kubernetes-sigs/aws-load-balancer-controller#2594]
We have following questions:
What is the max boy size supported in ingress ALB to avoid 413 error?  What is the configuration parameter to set to 200 mb limit?  What is the max timeout similar to idle_time configuration?  For instance, "alb.ingress.kubernetes.io/load-balancer-attributes": "idle_timeout.timeout_seconds=60", which for idle time out.  Is there a way to configure: "alb.ingress.kubernetes.io/load-balancer-attributes": "max_timeout.timeout_seconds=300" as an example.  We want timeout to be controlled at ingress level, not sure if is it possible?

**Comment by kishorj** [comment]
@newwuhan5, there is no request size limitation for ALB. The idle timeout is a load balancer attribute and you can have only one value per ALB.

**Comment by kishorj** [comment]
@newwuhan5, I'm closing the issue. If you have further concerns, feel free to reach out.

**Comment by shivraj001** [comment]
Hello @kishorj , I'm also facing this issue while sending a request body( json content) of size more then 50MB. it throws 413 payload too large error.
We have integrated WAF also, but there is no such rule included.
