### ISSUE TITLE
Error from server (InternalError): error when creating "./aws-load-balancer-controller.yml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"

### ISSUE THREAD

**Issue by sowmyaselva** [kubernetes-sigs/aws-load-balancer-controller#2604]
**Error from server (InternalError): error when creating "./aws-load-balancer-controller.yml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"**

**Steps to reproduce**

**Expected outcome**
Aws-load-balancer-controller should be successfully deployed

**Environment**

* AWS Load Balancer controller version -  2.41
* Kubernetes version - 1.21
* Using EKS (yes/no), if so version? Yes

**Additional Context**:

**Trying redeploying the same manifest aws-load-balancer-controller.yml with a sleep of 60 seconds**

**Comment by kishorj** [comment]
@sowmyaselva, can you verify if the controller pods are up and running? You can check the controller pod logs, or describe the pod to see if there recent events. If you disable IMDSv1, make sure you set up the correct hop limit for [IMDSv2](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#using-metadata-server-version-2-imdsv2).

**Comment by kishorj** [comment]
@sowmyaselva, I'm closing the issue. If problem persists after verifying the cert-manager is up and running in your cluster, feel free to reopen or create a new issue.
