### ISSUE TITLE
Issue upgrading

### ISSUE THREAD

**Issue by amarkezic** [kubernetes-sigs/aws-load-balancer-controller#2616]
**Describe the bug**
I am trying to update alb ingress controller

**Steps to reproduce**
upgrade from version 2.1.3 to latest (v2.4.0)

**Expected outcome**
working update

**Environment**

* AWS Load Balancer controller version v2.1.3
* Kubernetes version: 1.22
* Using EKS (yes/no), if so version? no

**Additional Context**:

To upgrade i ran
helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=<cluster_name> --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller

Error given:
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: [unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]

**Comment by kishorj** [comment]
@amarkezic, could you check the chart version you applied? ensure you run `helm repo udate`.

**Comment by soosin-spresto** [comment]
I have same issue too.
The chart version is 1.4.1.....

**Comment by soosin-spresto** [comment]
I Fixed it. I did not upgrade, uninstall and install was working.
