### ISSUE TITLE
Upgrade to v2 from v1.1.8

### ISSUE THREAD

**Issue by prajithp13** [kubernetes-sigs/aws-load-balancer-controller#2617]
We are planning to upgrade the controller version to v2 but we couldn't find any exact steps to install the v2.0.1 helm chart in the migration guide.  Please confirm if the v2.4.1 is compatible with the >= 1.1.3? 

**Environment**

* AWS Load Balancer controller version: 1.1.8
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by kishorj** [comment]
@prajithp13, you can follow the upgrade guide from https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/upgrade/migrate_v1_v2/. You can use the latest v2.4.1

You will need to ensure the iam permissions for the controller contains all permissions mentioned in https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.1/docs/install/iam_policy.json
