### ISSUE TITLE
HTTP and HTTPS health checks on NLB-IP

### ISSUE THREAD

**Issue by sjmiller609** [kubernetes-sigs/aws-load-balancer-controller#2622]
**Is your feature request related to a problem?**

On version 2.4

If I have a Service of Type LoadBalancer with multiple ports, for example like this:
```
istio-public-ingressgateway   LoadBalancer   172.***   *****.elb.us-east-1.amazonaws.com   80:32411/TCP,443:32153/TCP   253d
```
Possibly one of the ports is HTTP and the other is HTTPS. This is annotated like this for NLB-IP mode:
```
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=200,deregistration_delay.connection_termination.enabled=true,preserve_client_ip.enabled=false
          service.beta.kubernetes.io/aws-load-balancer-internal: "false"
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          # Below: How to set HTTP and HTTPS on the appropriate ports?
          # service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
```

In AWS, we will have one target group per port on the Service. In my case of using NLB-IP, the HTTP port is only wanted for HTTPS redirect.

The question is, **how can we use the application-aware health checks like HTTP and HTTPS on such a service with different protocols per port**? I would think this is a very normal need?

**Describe the solution you'd like**

I'm not sure if i'm doing it wrong, it seems like a nice solution would be something allowing for per-port protocol specification like this maybe?
```
service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: 8080:http,8443:https
service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: 8080:/foo,8443:/bar
```
Possibly for all service.beta.kubernetes.io/aws-load-balancer-healthcheck-* annotations

**Describe alternatives you've considered**

My ingress controller only supports NLB, so I have to use this instead of ALB. I found NLB instance mode doesn't work as well as NLB-IP mode so I'm trying this mode for now, but I'm open to any working approach.

Possibly we can do only use a single port on the NLB, just for the HTTPS traffic. In order to do HTTP to HTTPS redirect we need another layer in front like cloudfront or ALB, this would be out-of-band of the AWS LB controller and could handle the redirecting.

Another possibility is to just set them to HTTPS and allow the HTTP port to "fail open" on the NLB. This might look like HTTP healthchecks basically not working and HTTPS working, HTTP target group is all unhealthy, but still routes there because no healthy instances and NLB still routes to unhealthy instances

**Comment by kishorj** [comment]
@sjmiller609, one option is to use TargetGroupBinding - you create the NLB and the target groups with desired configuration, then use TargetGroupBinding to bind each of the target groups to the backend service.

/kind feature
