### ISSUE TITLE
2048 Ingress example not working with new Nginx Ingress

### ISSUE THREAD

**Issue by samceena** [kubernetes-sigs/aws-load-balancer-controller#2625]
The ingressClassName example [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/examples/2048/2048_full.yaml#L52) does not seem to be working with the [Nginx Ingress](https://kubernetes.github.io/ingress-nginx/)

When i created the ingress i get the error: `"Ignoring ingress because of error while validating ingress class" ingress="game-2048/ingress-2048" error="no object matching key \"alb\" in local store"`. this worked after changing `ingressClassName: alb` to `ingressClassName: nginx` . Perhaps a simple documentation would be useful if not an issue to fix the PR?.
It took me some time to figure this out.
Please advise.

* AWS Load Balancer controller version: 2.3.1
* Kubernetes version: 1.22
* Using EKS (yes/no), if so version? yes.

**Comment by kishorj** [comment]
@samceena, I'm closing the issue. If you have further concerns, feel free to reach out or create a new issue.
