### ISSUE TITLE
Websocket Error: Invalid HTTP upgrade", code: 404

### ISSUE THREAD

**Issue by rampn443** [kubernetes-sigs/aws-load-balancer-controller#2631]
**Describe the bug**
We have deployed an ALB for our spingboot application which consists of both Rest and Websocket services hosted in EKS cluster. We have added health check, ssl redirect etc. annotations in the ingress.yaml file. The listener is HTTPS: 443 and the SSL certificate is from ACM.

When we hit the ALB endpoint, rest service is working fine but receiving the following error with the websocket service.

Websocket Optional(wss://xxx.xx.xx.com:443/xx/xx/xx/xx) disconnected with error Optional(Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 404))

* app.kubernetes.io/instance:  aws-load-balancer-controller
* app.kubernetes.io/name:	  aws-load-balancer-controller
* app.kubernetes.io/version:	v2.3.0
* helm.sh/chart:	aws-load-balancer-controller-1.3.2
* Kubernetes version: 1.19
* Platform version: eks.7

**Additional Context**:

**Comment by kishorj** [comment]
@rampn443, could you check if the comments from a prior issue https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1090#issuecomment-561842212 helps?
If not, would you be able to share the ingress spec?

**Comment by kishorj** [comment]
@rampn443, closing the issue since we did not hear back from you. For websocket, you need to ensure:
- your ingress has rule for the initial request path to the websocket
- you configure larger idle timeout (default is 60 seconds), or setup heartbeat from the application layer
