### ISSUE TITLE
Ingress Address not updated when cluster has  Private Nodes

### ISSUE THREAD

**Issue by skamalj** [kubernetes-sigs/aws-load-balancer-controller#2641]
**Describe the bug**
I have a cluster where nodes do not have internet access (no NAT or anything else).
ALB Controller creates a ALB, which I can see in the console, and this URL, taken from [AWS](url) console,  takes me to application page and it opens and works all ok. 

The problem is ingress fails to update with this endpoint. The error is 
" Failed Deploy Model due to Request error send request failed
caused by: "https://wafv2.ap-south-1.amazonaws.com/" dial tcp <IP address> i/o timeout "

I have also attached image of this status on ingress.

**Steps to reproduce**
1. Create private cluster where nodes do not have internet access.
2. Deploy ALBC
3. Deploy application on this page - https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html
`kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.1/docs/examples/2048/2048_full.yaml`

**Expected outcome**
Ingress address should be updated and available when describing it.

**Environment**

* AWS Load Balancer controller version - 2.4.1
* Kubernetes version - 1.22
* Using EKS (yes/no), if so version? Yes, 1.22

**Additional Context**:
![ingress-error-private-nodes](https://user-images.githubusercontent.com/32254183/167268243-1dabb447-e73b-400f-bb31-21d5cc6da17e.jpg)

**Comment by skamalj** [comment]
I have tried this for both internet-facing and internal ingress,  both result in same error.

**Comment by skamalj** [comment]
I have worked around by adding these 3 settings while deployment. 
  --set enableShield=false \
  --set enableWaf=false \
  --set enableWafv2=false

I think for now , if required, these will need to be enabled manually on load balancers later on.

**Comment by kishorj** [comment]
@skamalj, I'm closing the issue. If problem persists, feel free to reach out to us.
