### ISSUE TITLE
unable to determine AWS Shield subscription state elasticloadbalancing.ap-east-1.amazonaws.com/\": dial tcp 13.248.36.93:443: i/o timeout

### ISSUE THREAD

**Issue by tracycyx** [kubernetes-sigs/aws-load-balancer-controller#2642]
creating alb ingress and meet below erros , i am using 2.4.2 ingress controller , sg outbound for all traffice , inbound already open to port 443 with cidr 13.248.0.0/16 and 52.94.0.0/16 . bUt still can not creaet alb successfully . While these events triggered during alb creation ? is it possible to disable ? or how to fix this issue ? 

{"level":"error","ts":1651994781.9259355,"logger":"controllers.ingress","msg":"unable to determine AWS Shield subscription state, skipping AWS shield reconciliation","error":"RequestError: send request failed\ncaused by: Post \"https://shield.us-east-1.amazonaws.com/\": dial tcp 52.94.225.165:443: i/o timeout"}
{"level":"error","ts":1651995159.2684016,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"ingress-credit","namespace":"credit-demo","error":"RequestError: send request failed\ncaused by: Post \"https://elasticloadbalancing.ap-east-1.amazonaws.com/\": dial tcp 13.248.36.93:443: i/o timeout"}
C:\Softwares\GitHub\EKS\eks-demo\worker\example>kubectl get ingress -n credit-demo

NAME             CLASS    HOSTS                                    ADDRESS   PORTS   AGE

ingress-credit   <none>   credit-dev.eks.ape1.dev.aws.cloud.hsbc             80      48m

Manifest file 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: credit-demo
  name: ingress-credit
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: "subnet-0e4ccc4ebd7ffff49,subnet-0f3472e1f8511c81c"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/shield-advanced-protection: 'false'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]' 
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: '/cspapi/v1/process/drawdownRequest/health'
    alb.ingress.kubernetes.io/security-groups: "sg-06b5d9060ca71290e"
spec:
  rules:
    - host: credit-dev.eks.ape1.dev.aws.cloud.hsbc
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: credit-service
              port:
                number: 8080

**Comment by tracycyx** [comment]
the elb has been solved after i added an elb endpoint , may i know whether we could disable below event even i add annotation alb.ingress.kubernetes.io/shield-advanced-protection: 'false' ; it is still there 
{"level":"error","ts":1651994781.9259355,"logger":"controllers.ingress","msg":"unable to determine AWS Shield subscription state, skipping AWS shield reconciliation","error":"RequestError: send request failed\ncaused by: Post "[https://shield.us-east-1.amazonaws.com/\](https://shield.us-east-1.amazonaws.com/%5C)": dial tcp 52.94.225.165:443: i/o timeout"}

and also error about wafv2.ap-east-1.amazonaws.com ; becaue we are in private network , so i don't want to get these abled , any way to disable them

**Comment by ysam12345** [comment]
@tracycyx Maybe using [controller command line flags](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/configurations/#controller-command-line-flags) mentioned in #2641 will work?

**Comment by kishorj** [comment]
@tracycyx, you can disable shield, waf and wafv2 via controller command line flags, or specify in helm values during chart installation. I'm closing the issue for now, if you still face issues, feel free to reach out to us.
