### ISSUE TITLE
Need parameter/option to set annotation for IngressClass in helm chart

### ISSUE THREAD

**Issue by rahul-paigavan** [kubernetes-sigs/aws-load-balancer-controller#2646]
**Describe the bug**
Need an option/parameter to add annotations to IngressClass in helm chart.

**Steps to reproduce**
Values file currently do not have an option to specify the annotations for IngressClass the is getting created.
I would like to have below annotation set:
```
ingressclass.kubernetes.io/is-default-class: "true"
```

**Expected outcome**
After specifying the parameter with annotation it should get added to IngressClass.

**Environment**

* AWS Load Balancer controller version: 2.2.4
* Kubernetes version: 1.19
* Using EKS (yes): 1.19

**Additional Context**:

* AWS Load Balancer controller chart version: 1.4.1

**Comment by lemeurherve** [comment]
FTR, this is (now) possible by setting `ingressClassConfig.default` value to `true`.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/ingressclass.yaml#L29-L32
