### ISSUE TITLE
POD Not Running - alb ingress

### ISSUE THREAD

**Issue by roma28MFB** [kubernetes-sigs/aws-load-balancer-controller#2647]
**Describe the bug**
Hello, I created an alb ingress pod but it does not run and shows me the following errors when consulting the log.

F0510 19:31:06.485643       1 main.go:107] no matches for kind "Ingress" in version "extensions/v1beta1"
W0510 20:02:08.403456       1 config.go:46] Environment variable configuration is deprecated, switch to the --aws-region flag.
W0510 20:02:08.403831       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

![imagen](https://user-images.githubusercontent.com/52689705/167712742-6b24d41e-fc59-4154-a902-da50783a1e84.png)

Describe pod:
![imagen](https://user-images.githubusercontent.com/52689705/167710681-014db85d-bc09-454f-b0c0-fcbdcb734ae4.png)

**Steps to reproduce**

- apply file Service-ClusterRoleBinding-ServiceAccount.yaml
  [Service-ClusterRoleBinding-ServiceAccount.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/8664569/Service-ClusterRoleBinding-ServiceAccount.txt)
- eksctl utils associate-iam-oidc-provider --region=us-east-1 --cluster=***[my-cluster]*** --approve
- create policy (policy.json)
  [Policy.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/8664568/Policy.txt)
- eksctl create iamserviceaccount --region us-east-1 --name alb-ingress-controller --namespace kube-system --cluster ***my-cluster*** --attach-policy-arn arn:aws:iam::***mypolicy*** --override-existing-serviceaccounts --approve
- apply file alb-ingress-controller.yaml
  [alb-ingress-controller.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/8664567/alb-ingress-controller.txt)
- kubectl edit deployment.apps/alb-ingress-controller -n kube-system and replace arg cluster-name with my cluster name.

**Environment**

* AWS Load Balancer controller version 
1.1.9
* Kubernetes version
1.22
* Using EKS (yes/no), if so version?
0.96.0
**Additional Context**:
* Istio version
1.13.3

Thanks in advance

**Comment by kishorj** [comment]
@roma28MFB, you will not be able to run controller version 1.1.9 on k8s 1.22 or later. You will need at least controller version v2.4.0.

**Comment by roma28MFB** [comment]
@kishorj, thanks for you asnwer
