### ISSUE TITLE
[Feature] TargetGroupBinding for TargetGroup outside of ALB Controller's VPC

### ISSUE THREAD

**Issue by KamikazeZirou** [kubernetes-sigs/aws-load-balancer-controller#2650]
## Is your feature request related to a problem?

I'd like to bind pods to a TargetGroup in a VPC outside the EKS cluster. A similar feature was added in #1862, but it does not work in my case.

The infrastructure configuration I would like to build is shown below.
![image](https://user-images.githubusercontent.com/33488934/168240993-e11b26c0-1857-4086-8592-fc4a12f487b0.png)

When registering the pod's IP address to the TargetGroup that is in a VPC outside the EKS cluster, it is necessary to set "all" for the availability zone. [In the current implementation](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/4c33010f204fef2868a396adf7fac6d13d027250/pkg/targetgroupbinding/resource_manager.go#L373-L402), "all" is set if the pod's IP address is not in the VPC CIDRs configured in the ALB Controller. In my case, the VPC of the ALB Controller is the same as the VPC of the EKS cluster, so "all" is not set.

## Describe the solution you'd like

Set "all" to the availability zone if the pod's IP address is in the VPC of the TargetGroup.

## Describe alternatives you've considered

The problem can be avoided by deploying two ALB Controllers on one cluster.
However, I do not know if it is possible to deploy two ALB Controllers.

## Note

I think that this issue is the same as aws/eks-charts#745.

**Comment by kishorj** [comment]
@KamikazeZirou, are the VPCs in the same account or different accounts?

**Comment by KamikazeZirou** [comment]
@kishorj 

> @KamikazeZirou, are the VPCs in the same account or different accounts?

They are in the same account.
