### ISSUE TITLE
Existing targets removed when creating TargetGroupBinding for exisitng NLB TG

### ISSUE THREAD

**Issue by mbeaucha** [kubernetes-sigs/aws-load-balancer-controller#2651]
**Describe the bug**
I have existing NLB and target groups using IP target mode. The TGs have existing targets in them from another deployment mechanism (in this case an ECS service). I defined/deployed a new TargetGroupBinding to add the same type of service under EKS, and when doing so all the existing targets in the TG are removed, and only the TargetGroupBinding targets are present.

**Steps to reproduce**
Create NLB & TGs with IP mode
Add targets to TG by some other means (manual, ECS, etc)
Deploy TGB under EKS, see all previous targets removed.

**Expected outcome**
I would expect the new targets from the TargetGroupBinding to be added to the TG without affecting the other registered targets.

**Environment**

* AWS Load Balancer controller version - 2.4.1
* Kubernetes version - 1.22
* Using EKS (yes/no), if so version? Yes (1.22)

**Additional Context**:
I'm attempting to develop a migration of my system from ECS to EKS while re-using the ELB resources, both for seamless transition reasons, and because aws-load-balancer-controller Service annotations don't have enough flexibility yet to recreate my NLBs and TGs as currently configured.

**Comment by kishorj** [comment]
@mbeaucha, the controller assumes exclusive ownership of the targetgroup targets, so it will remove the existing targets if they are not part of the deployment (for ip targets), or the k8s cluster nodes for instance targets.

**Comment by wuyudian1** [comment]
Users should have the right to choose whether to enable this feature。
