### ISSUE TITLE
Add support for multiple VPC

### ISSUE THREAD

**Issue by Skaopap** [kubernetes-sigs/aws-load-balancer-controller#2652]
Hello,

In our use case we have : 
- A fonctionnal multiple account/vpc transitgateway network architecture 
- An EKS deployed in an account 1 within private subnets in a VPC A 
- We need to create public ALB in an account 2 in a VPC-ingress B within public subnets

Will this be functional if we define correct cross-account access for the alb-controller and use the alb.ingress.kubernetes.io/subnets annotation ?

**Comment by kishorj** [comment]
It is possible to create ALB in one account and the target-group targets in another account, but you will need to configure the following:
- vpc peering
- route table configuration
- subnet tagging for auto discovery
- cross account IRSA for the AWS LB controller

These are the limitations:
- security group rules for traffic access cannot be managed by the controller. You will have to manually configure the ALB security group, and the SG ingress rules in the target account
- IP targets only, instance targets don't work

**Comment by raonitimo** [comment]
> It is possible to create ALB in one account and the target-group targets in another account, but you will need to configure the following:
> 
> * vpc peering
> * route table configuration
> * subnet tagging for auto discovery
> * cross account IRSA for the AWS LB controller
> 
> These are the limitations:
> 
> * security group rules for traffic access cannot be managed by the controller. You will have to manually configure the ALB security group, and the SG ingress rules in the target account
> * IP targets only, instance targets don't work

Hey @kishorj, I'm trying to setup something very similar except I don't want to create an ALB. I want to use a target rule binding to register pods into an existing target group living in another account. Can you please give some pointers on what not to miss? 

I have the VPC peering in place, cross account IRSA working, currently trying to figure out how `alb.ingress.kubernetes.io/security-groups` [annotation](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2398#issuecomment-989308192) translates into the CR. Getting `InvalidInstanceID.NotFound: The instance IDs xxx do not exist` error.

**Comment by kgtw** [comment]
Hi @kishorj, is there any plan to support this in the near future? Seems like with the recent changes in https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2945 for subnet discovery, this should make the implementation possible.

Alternatively, is there any plans to support running multiple instances of the controller within the same cluster to achieve the desired result?
