### ISSUE TITLE
Redirection from one domain to another with 308 status code

### ISSUE THREAD

**Issue by vipulJain05** [kubernetes-sigs/aws-load-balancer-controller#2654]
We are using ALB-load-balancer-controller's helm chart 1.2.7 with AWS EKS to manage our ALB.
Now we want to redirect our site from `test.example.com` to `app.example.io` but because AWS doesn't support the 308 status code to redirect the domain, all POST calls are automatically converted into the GET endpoint and because of that POST endpoints of our services start failing.
Is there any way in ingress or in the load balancer  to redirect to another domain with same HTTP method came at source endpoint.

**Comment by kishorj** [comment]
@vipulJain05, ALB currently doesn't support HTTP 308 redirect. For the redirection, you can provision a NLB with your your application issuing the required redirect - this is a bit costly alternative.

**Comment by kishorj** [comment]
Controller will not be able to support this unless it is available on the ALB side. We are tracking this request in issue 1571.
