### ISSUE TITLE
v2.4.2 tag Helm chart references v2.4.1

### ISSUE THREAD

**Issue by MartinEmrich** [kubernetes-sigs/aws-load-balancer-controller#2662]
ATM, the Git tag "v2.4.2" points to a revision where the Helm chart still references the image version v2.4.1:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/77370be7f8e13787a3ec0cfa99de1647010f1055/helm/aws-load-balancer-controller/values.yaml#L9

**Comment by kishorj** [comment]
The eks-charts repo has the correct reference to the v2.4.2 image tag

https://github.com/aws/eks-charts/blob/aaba08ea04affe98ed26c9b878e9109c67104796/stable/aws-load-balancer-controller/values.yaml#L9

We will modify the image tag in this repo for the next patch release.
