### ISSUE TITLE
Frontend to backend traffic not routed even health check is passing

### ISSUE THREAD

**Issue by rahul-chawla** [kubernetes-sigs/aws-load-balancer-controller#2663]
**Describe the bug**
A concise description of what the bug is.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by rahul-chawla** [comment]
Can u help me how I fix this

**Comment by kishorj** [comment]
@rahul-chawla, could you provide further details on this?
- ALB or NLB?
- internal or internet-facing
- whether the security group rules are configured as expected
- how you exposed your application? via ingress, or service type LoadBalancer

**Comment by kishorj** [comment]
@rahul-chawla, I'm closing the issue since we don't have enough details to provide further assistance. If you still have concerns, feel free to reach out to us.
