### ISSUE TITLE
IMDSv2 Doc Suggests Insecure Configuration

### ISSUE THREAD

**Issue by mkantzer** [kubernetes-sigs/aws-load-balancer-controller#2665]
**Describe the bug**
The [IMDSv2 section of the Installation Guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#using-metadata-server-version-2-imdsv2) suggests increasing the endpoint hop limit to 2, despite this being directly against the recommendation of [EKS best practices](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node). This Best Practice is relevant even for non-EKS clusters running in AWS.

This is also without any suggestion that this could seriously impact a cluster's security posture.

**Steps to reproduce**
- read the 2 linked documents

**Expected outcome**
A removal of the recommendation, or at least a warning about the security implications, and a guide on a minimally-scoped NetworkPolicy to allow _only_ the AWS LB Controller minimal access.

**Environment**

* AWS Load Balancer controller version N/A
* Kubernetes version N/A
* Using EKS (yes/no), if so version? N/A

**Additional Context**:

**Comment by tkent** [comment]
Just to chime in, we're using AWS Security Hub and we _can't_ set the hops to 2 without violating the [AutoScaling.4 rule](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#autoscaling-4-remediation) (which has a severity of High). A bit of a catch 22.
