### ISSUE TITLE
Failed deploy model due to the server could not find the requested resource (post targetgroupbindings.elbv2.k8s.aws)

### ISSUE THREAD

**Issue by stozinho** [kubernetes-sigs/aws-load-balancer-controller#2666]
**Describe the bug**

After installation of AWS LBC I saw the following error on Ingress objects which were trying to update ALB Listeners accordingly: 
`Failed deploy model due to the server could not find the requested resource (post targetgroupbindings.elbv2.k8s.aws)`

**Steps to reproduce**

Fresh install of AWS LBC via Helm chart. Helm chart ver 1.4.1; LBC ver v2.4.1. we set `enableCertManager=true`. 
Manually installing missing CRDs 'fixes' the issue 
`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"`

**Expected outcome**

I would expect that the CRD targetgroupbindings.elbv2.k8s.aws is created ordinarily. However, in my case it was not installed. 

**Environment**

* AWS Load Balancer controller version - v2.4.1
* Kubernetes version - v1.21 
* Using EKS (yes/no), if so version? - yes, v1.21 

**Additional Context**:

I have noticed a very similar [issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2551) is closed (and that is where i found the 'fix' to manually install the missing CRDs). 
In my case we deploy LBC through terraform, and cannot tolerate additional manual step to install missing CRDs, which should be installed with LBC as we specify `enableCertManager=true`

**Comment by Glaaj** [comment]
I can attest to this, we are running into the same problem here causing the LBC to fail as it misses CRD's inside the cluster.

Are you by any chance using something similar to this:
```terraform
resource "kubectl_manifest" "crds" {
  yaml_body = file("${path.module}/yamls/crds.yaml")
}
```

I found out the file is only read until it runs into the delimiter "---" in the crds.yaml which causes it to stop before it starts to create the targetgroupbindings CRD.

Quick fix for me was to read 2 seperate yaml's :
```terraform
resource "kubectl_manifest" "ingessclassparams" {
  yaml_body = file("${path.module}/yamls/ingressclassparams.yaml")
}

resource "kubectl_manifest" "targetgroupbindings" {
  yaml_body = file("${path.module}/yamls/targetgroupbindings.yaml")
}
```

Hoping this helps you :)

**Comment by Glaaj** [comment]
When I check the [documentation](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/main/helm/aws-load-balancer-controller#installing-the-chart) it shows to install the CRD's separately from the helm chart itself. (See screenshot)

![Screenshot 2022-06-16 at 09 31 40](https://user-images.githubusercontent.com/83582518/174016885-d6d9276a-01f6-4342-bb27-60c131210074.png)

**Comment by stozinho** [comment]
@Glaaj brill thank you

**Comment by Glaaj** [comment]
Did this fix it for you? Just curious :)

**Comment by stozinho** [comment]
@Glaaj I'll let you know when we try i imagine it will
