### ISSUE TITLE
Installing full yaml from scratch does not work

### ISSUE THREAD

**Issue by rittneje** [kubernetes-sigs/aws-load-balancer-controller#2672]
**Describe the bug**
When running `kubectl apply` on the full yaml file from scratch (i.e., in a new cluster), we get an error:

> error: unable to recognize "STDIN": no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1"

From testing, this seems to happen because it tries to use the new CRDs before they are fully ready. We had to split the CRDs into their own file, apply that, and then run `kubectl wait --for condition=established`. After that, we are able to successfully apply the rest of the yaml.

**Steps to reproduce**

Run `kubectl apply -f full.yaml` against a fresh cluster.

**Expected outcome**

Following the instructions from https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html to install the AWS Load Balancer Controller via a Kubernetes manifest (step 5) should work. If the file needs to be split in two, then the release artifacts from this repo ought to reflect that, and the instructions updated accordingly.

**Environment**

* AWS Load Balancer controller version: 2.4.2
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version?: 1.21

**Additional Context**:

**Comment by M00nF1sh** [comment]
Thanks for reporting this. we'll validate this and split the yaml into two if it's a valid race condition

**Comment by kishorj** [comment]
@rittneje, we will provide a separate yaml for the IngressClass and IngressClassParams manifests starting v2.4.3 patch release and update the documentation.
