### ISSUE TITLE
AWS EKS LB - access log enable issue

### ISSUE THREAD

**Issue by micemuni** [kubernetes-sigs/aws-load-balancer-controller#2673]
Hi All,
I am deploying application on AWS EKS cluster via terraform. As part of that i have created load balancer and now there is requrement to enable access log for those load balancer. 
I have tried the below option and terraform showing applied but the same is not reflecting in AWS console ( meaning no changes on LB access log ) looks still access-log disabled. 

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#:~:text=access%2Dlog%2Denabled-,boolean,-false 
the following annotations are deprecated in v2.3.0 release in favor of [service.beta.kubernetes.io/aws-load-balancer-attributes](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#load-balancer-attributes)
```
service.beta.kubernetes.io/aws-load-balancer-access-log-enabled
service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name
service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled 
``` 

I see that there is some deprecated but not sure how to enable access log on load balancer which is created via kubernetes resources. 
please let me know if any solution OR fix..? 

Thank you in advance.

**Comment by oc-christopher-billett** [comment]
You will need to add annotations to your ingress

`alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-access-log-bucket,access_logs.s3.prefix=my-app`

**Comment by M00nF1sh** [comment]
@micemuni 
It depends on what method you created the LoadBalancer. 
If it's CLB(Classic LoadBalancer), then you have to use `service.beta.kubernetes.io/aws-load-balancer-access-log-enabled`
If it's NLB(Network LoadBalancer), then it can be either provisioned by either a built-in controller in Kubernetes or this AWSLoadBalancerController, depends on the `service.beta.kubernetes.io/aws-load-balancer-type` annotation. and this new [service.beta.kubernetes.io/aws-load-balancer-attributes](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#load-balancer-attributes) only works if it's provisioned by  AWSLoadBalancerController.

Would you help post your full Service yaml here?

**Comment by micemuni** [comment]
@oc-christopher-billett  @M00nF1sh  
I used kubernetes ingress terraform resources https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/ingress, please guide me how can i add access log..?

**Comment by kishorj** [comment]
@micemuni, I'm closing this issue. If issue persists, feel free to reach out to us.
