### ISSUE TITLE
Add additional subnet tags filter

### ISSUE THREAD

**Issue by AndrewChubatiuk** [kubernetes-sigs/aws-load-balancer-controller#2674]
**Is your feature request related to a problem?**
EKS workload is running in availability zones and local zones. Local and availability zone subnets use `kubernetes.io/role/internal-elb = 1` tags and alb ingress fails to spin up load balancer with `Failed build model due to couldn't auto-discover subnets: subnets in multiple locales: [availability-zone local-zone]` error.

**Describe the solution you'd like**
I would like to add an ability to provide extra tags in alb ingress annotation for subnets filtering to limit alb to either local or availability zone subnets (or any other subnets type)

**Describe alternatives you've considered**
Now I have to hardcode subnet names for each environment in [alb.ingress.kubernetes.io/subnets](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#subnets), but their names and amount differ from env to env, from project to project

**Comment by M00nF1sh** [comment]
Do you have some LBs in normal AZ and some LBs in local AZs?
If so, there should be a way to tell the controller which AZ to provision the LB

**Comment by AndrewChubatiuk** [comment]
you mean zone list or a boolean flag `is-local` to identify a zone type?
