### ISSUE TITLE
Fail to create WAFv2 webACL association on LoadBalancer

### ISSUE THREAD

**Issue by amazingguni** [kubernetes-sigs/aws-load-balancer-controller#2676]
**Describe the bug**

Fail to create WAFv2 webACL association on LoadBalancer, even if entering correct `wafv2-acl-arn`

**Steps to reproduce**

Enter correct `wafv2-acl-arn`, when creating ingress resource

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/wafv2-acl-arn: |
      arn:aws:wafv2:ap-northeast-2:52362***:regional/webacl/***/2da3c1f7-508c-41cd-ad3b-*****
// ...
```

**Expected outcome**

Create WAFv2 webACL association successfully

**Environment**

* AWS Load Balancer controller version  : 1.4.1
* Kubernetes version: v1.22.9-eks-a64ea69
* Using EKS (yes/no), if so version? v1.22.9-eks-a64ea69

**Additional Context**:

I found error message below on ingress resource

> I think there is additional line feeding after wafv2 arn. IMO it can be reason of this problem

```
  Warning  FailedDeployModel  12m (x16 over 50m)  ingress  (combined from similar events): Failed deploy model due to failed to create WAFv2 webACL association on LoadBalancer: ValidationException: 1 validation error detected: Value 'arn:aws:wafv2:ap-northeast-2:523625819788:regional/webacl/stage-catcha-acl/2da3c1f7-508c-41cd-ad3b-383a37b241af
' at 'webACLArn' failed to satisfy constraint: Member must satisfy regular expression pattern: .*\S.*
          status code: 400, request id: 78da791f-6a48-4ed7-b647-30c241e97c7f
  Normal  SuccessfullyReconciled  5m45s (x3 over 9h)  ingress  Successfully reconciled 
```

**Comment by kishorj** [comment]
@amazingguni, the error is due to the additional whtespace in the ARN. What does the model look like? You can get the model from the controller logs. Also, would you be able to eliminate the whitespace from the ingress spec and retry?

**Comment by amazingguni** [comment]
@kishorj 
After removing whitespace, It works perfectly!!! thanks for your help
