### ISSUE TITLE
v2.4.2 release is missing yaml asset

### ISSUE THREAD

**Issue by rittneje** [kubernetes-sigs/aws-load-balancer-controller#2679]
The v2.4.2 release does not include any v2_4_2_full.yaml asset. https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.4.2

Even if there is no difference from the v2.4.1 yaml other than the image tag, it should still be published to avoid confusion.

**Comment by jaxxstorm** [comment]
Also running into this. @M00nF1sh are you moving away from including the yaml asset with each release? If that's the case, we'll need to find a new strategy for some codegen stuff we do. 

Anyone who is generating typed code would need the full yaml asset so I'm hoping it has just been forgotten. I'm happy to add a PR to fix it if it's just the same as `v2.4.1` but the release will need to be updated for the new commit
