### ISSUE TITLE
Setting the namespace for the serviceMonitor is not working

### ISSUE THREAD

**Issue by v1nc3nt27** [kubernetes-sigs/aws-load-balancer-controller#2682]
I'm trying to set the namespace for the service monitor in the helm chart, but for some reason the service monitor is always getting installed in the same namespace where the resources are installed. Is it possible that https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2609 is not working correctly? 

I'm installing the chart with the helm provider (terraform) and the other service monitor values are working. Everything, including the service monitor, is created in namespace `loadbalancer`. The service monitor should be created in `different_namespace`.

```
resource "helm_release" "aws_load_balancer_controller" {
  name              = "ingress"
  chart             = "aws-load-balancer-controller"
  repository        = "https://aws.github.io/eks-charts"
  namespace         = "loadbalancer"
  create_namespace  = true
  cleanup_on_fail   = true
  version           = "1.4.2" 

  set {
    name  = "autoDiscoverAwsRegion"
    value = "true"
  }
  set {
    name  = "autoDiscoverAwsVpcID"
    value = "true"
  }
  set {
    name  = "clusterName"
    value = "test"
  }
  set {
    name = "serviceMonitor.enabled"
    value = "true"
  }
  set {
    name = "serviceMonitor.interval"
    value = "10s"
  }
  set {
    name = "serviceMonitor.namespace"
    value = "different_namespace"
  }
```
Am I missing something here? From what I can see in the code, this should work:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/b31a648bc3421864476b67a81ddb6111d9c61bbe/helm/aws-load-balancer-controller/templates/servicemonitor.yaml#L6-L10

**Comment by kishorj** [comment]
@v1nc3nt27, the namespace support is not available on the eks-charts repo as of the current chart version v1.4.2. We will include the feature in the chart version v1.4.3 and later releases.

**Comment by v1nc3nt27** [comment]
@kishorj Great, thanks a lot! If there is a feature request or so for this already you can just close the issue then (couldn't find anything).

**Comment by kishorj** [comment]
closing the issue since chart v1.4.3 is already released.

**Comment by v1nc3nt27** [comment]
Yup, I also tested it now and it works as expected. Thanks!
