### ISSUE TITLE
ALB ingress object to contain listener ARN

### ISSUE THREAD

**Issue by wildtapir** [kubernetes-sigs/aws-load-balancer-controller#2686]
**Is your feature request related to a problem?**
I am trying to integrate AWS HTTP API gateway using [apigatewayv2 ACK](https://aws-controllers-k8s.github.io/community/reference/apigatewayv2/v1alpha1/integration/) . One of the parameters I need to provide is `integrationURI` which is an ARN of ALB Listener.

**Describe the solution you'd like**
ALB ingress object to contain listener ARN so I can query for it dynamically.

**Comment by iamnoah** [comment]
The `TargetGroupBinding` has `spec.targetGroupARN` which will let you query the load balancer for listeners.

**Comment by kishorj** [comment]
Here is one way to do it
- From the kubectl output, look for the status field, you will see the load balancer DNS name
- Extract the load balancer name, for example if dns name is `k8s-default-demoserv-xxx-yyy.REGION.elb.amazonaws.com`, lb name is `k8s-default-demoserv-xxx`
- describe load balancer, `aws elbv2 describe-load-balancers --names k8s-default-demoserv-xxx`, get the `LoadBalancerArn`
- describe listeners, `aws elbv2 describe-listeners --load-balancer-arn arn:aws:elasticloadbalancing...`

**Comment by kishorj** [comment]
This controller applies labels to all k8s resources it creates, for example all TargetGroupBinding resources created by this controller have the following labels:

* explicit IngressGroup
    * `ingress.k8s.aws/stack: groupName`
* implicit IngressGroup:
    * `ingress.k8s.aws/stack-namespace: namespace`
    * `ingress.k8s.aws/stack-name: ingressName`
* NLB (service of type LoadBalancer or with NLB annotations)
    * `service.k8s.aws/stack-namespace: namespace`
    * `service.k8s.aws/stack-name: serviceName`

You should be able to associate the TargetGroupBinding resources to your ingress stack based on the lablels.

**Comment by wildtapir** [comment]
Thank you @kishorj . Let me be more clear. What I need is `listener arn` of an ALB. `listener arn` is not the same as `targetGroupARN`. Do you know of any object in k8s that would contain `listener arn` of an ALB?

**Comment by eligithubacc** [comment]
I have similar a problem. @wildtapir any luck so far?

**Comment by wildtapir** [comment]
Hi @eligithubacc. Nope, I was not able to use `kubectl` only to get `listener arn`.
