### ISSUE TITLE
Allow user to set AvailabilityZone "all" or "null" or "autoDetect" when createing TargetGroupBinding

### ISSUE THREAD

**Issue by wuyudian1** [kubernetes-sigs/aws-load-balancer-controller#2691]
**Is your feature request related to a problem?**
We have several business groups running in different VPCs,  and now we are trying to migrate them to a single EKS cluster.
Due to the huge complexity of our traffic path, we wanna migrate micro-services into EKS, and reuse the current ELB and target groups.
So, we need to bind PODs to different target group in multiple VPCs otherthan the EKS's native VPC.
As we know, if we need to bind PODs to TargetGroup out of the EKS native VPC,  `vpcId` should be set to the ID of that VPC(). 
THE PROBLEMS ARE:
1.  If `vpcId` is associated with another VPC,  we can no longger bind PODs to target groups in the EKS's native VPC, beacaus argument `AvailabilityZone ` is set to "all" by LBC, but the POD IPs are in the range of native VPC's CIDR.
2. `vpcId` can only be associated with ONE VPC, we now have many VPCs to hold the target groups.

**Describe the solution you'd like**
So, if we set `vpcId` to the EKS's native VPC's ID, or just omit it, In order to bind PODs to our old target groups, I think we need a feature:  set the value of `AvailabilityZone` in TargetGroupBinding's manifest by ourselves.

**Describe alternatives you've considered**
Or, we can create multiple LBC instances like nginx ingress class dose. We can deploy different LBC instance with different `vpcId` values, and use them in TargetGroupBinding's manifest  on demand.

**Comment by kishorj** [comment]
@wuyudian1, this is not something we can support at the moment. It requires at least the following features:
- Controller support multiple VPCs
- possibly run multiple controller instances in the same cluster

We will keep it in the roadmap
