### ISSUE TITLE
ingressclassparams.elbv2.k8s.aws "alb" already exists

### ISSUE THREAD

**Issue by yasin-kismet** [kubernetes-sigs/aws-load-balancer-controller#2698]
**Describe the bug**
I am trying to deploy 2 different applications on aws eks using pulumi. If I am applying ingress for the first time, there is no problem, but when I want to make an update, I get the error `ingressclassparams.elbv2.k8s.aws "alb" already exists`.

**Environment**

* AWS Load Balancer controller version: 1.4.2
* Kubernetes version: the latest version used on the aws eks
* Using EKS (yes/no), if so version?: eks.2

**Comment by kishorj** [comment]
@yasin-kismet, I'm closing this issue since it doesn't appear to be an issue with the controller. If you have further concerns, feel free to reach out to us.
