### ISSUE TITLE
Leader election not using leases

### ISSUE THREAD

**Issue by DTTerastar** [kubernetes-sigs/aws-load-balancer-controller#2701]
**Describe the bug**
I blew away a pod and the leader didn't switch to other pod.  I also noticed it's using a configmap to do the lease instead of the built-in lease object.  Is there a reason for that?

**Steps to reproduce**
kubectl  delete pod aws-load-balancer-controller-58bb5b665-snsff

**Expected outcome**
Failover to other pod

**Environment**

* AWS Load Balancer controller version
* 2.42
* Kubernetes version
* 1.2.1
* Using EKS (yes/no), if so version?
yes, 1.21
**Additional Context**:

**Comment by kishorj** [comment]
@DTTerastar, if you have more than one replicas, the pod which gets the leader election lock is active. Could you verify there is an active controller pod by checking the logs? 

We will migrate to using leases in future releases.
/kind feature

**Comment by DTTerastar** [comment]
I figured out my issue, it wasn't a problem with leader election.  My logging was filtering too much and I missed the other pod working.  I'm glad to hear you'll move to the leases at some point!
