### ISSUE TITLE
Controller doesn't deregister pods that are terminated by Graceful Node Shutdown feature

### ISSUE THREAD

**Issue by romich** [kubernetes-sigs/aws-load-balancer-controller#2702]
**Describe the bug**
If GracefulNodeShutdown feature configured as described [here](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown), pods are not deregistered from ALB when kubelet does graceful shutdown.

**Steps to reproduce**
1. Configure GracefulNodeShutdown
2. Deploy a pod that AWS LB Controller would register in ALB in IP mode
3. Terminate instance

**Expected outcome**
Controller deregisters IP targets as soon as they start to terminate.

**Environment**

* AWS Load Balancer controller version 2.4.1
* Kubernetes version v1.22.9-eks-a64ea69

**Additional Context**:
Not sure if it's controller or Kubernetes bug.

Our service catches SIGTERM and sleeps for 27 seconds before exiting (no preStop hooks), this is visible from logs (instance termination requested at 17:11:30):
```
{"time":"2022-06-22T16:59:15Z","event":"App is listening.","level":"info"}
{"time":"2022-06-22T17:11:30Z","event":"App is shutting down.","level":"info"}
{"time":"2022-06-22T17:11:57Z","event":"App exits.","level":"info"}
```
But LB controller starts deregistering only after pod has already exited.
```
{"level":"info","ts":"2022-06-22T16:59:14Z","msg":"registering targets","arn":"[tg-arn]","targets":[{"AvailabilityZone":null,"Id":"10.25.91.44","Port":8081}]}
{"level":"info","ts":"2022-06-22T16:59:14Z","msg":"registered targets","arn":"[tg-arn]"}
{"level":"info","ts":"2022-06-22T17:11:59Z","msg":"deRegistering targets","arn":"[tg-arn]","targets":[{"AvailabilityZone":"us-east-1d","Id":"10.25.91.44","Port":8081}]}
{"level":"info","ts":"2022-06-22T17:11:59Z","msg":"deRegistered targets","arn":"[tg-arn]"}
```
kubelet config:
```
  [...]
  "shutdownGracePeriod": "6m",
  "shutdownGracePeriodCriticalPods": "1m"
```
Confirmed working:
```
# systemd-inhibit --list
     Who: kubelet (UID 0/root, PID 10204/kubelet)
    What: shutdown
     Why: Kubelet needs time to handle node shutdown
    Mode: delay

1 inhibitors listed.
```

**Comment by kishorj** [comment]
The pod termination handling and the Endpoint/EndpointSlice update happen in parallel. Controller de-registers the targets after getting updated Endpoint from the API server.

There is a similar issue reported earlier: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366
