### ISSUE TITLE
Allow service.beta.kubernetes.io/aws-load-balancer-target-group-attributes to specific port for nlb

### ISSUE THREAD

**Issue by gagan-eg** [kubernetes-sigs/aws-load-balancer-controller#2708]
**Is your feature request related to a problem?**
We would like to apply target-group-attributes  (proxy-protocol) to only one of the ports (target groups) in the service object for the NLB. Currently based on reading the code I don't see how to do it

**Describe the solution you'd like**
NLB allows attributes such as proxy-protocol to be applied to individual target groups and we would like to configure different target groups differently for NLB. I believe this may be possible for ALB by doing an ingress object and then NodePort service objects with different annotations for target groups but I don't think this is possible to do for NLB.

**Describe alternatives you've considered**
I don't have an alternative currently.

**Comment by M00nF1sh** [comment]
one workaround for now is to create the TargetGroups yourself(so you can customize the attributes), and the use the [targetgroupbinding](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/) resource to bind the Service to the TargetGroups(to dynamically update target group targets).

But i admit that this is a valid feature request to allow customer fully control ALB/NLB behavior from Kubernetes. 
We'll find a better model to support such configuration flexibility when we add gateway API support.

**Comment by jurgen-weber-deltatre** [comment]
We could use this feature also, our use case is we have the standard http ports with it on but with ingress nginx behind it. I added a nginx streaming port (https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/). This port I need it disabled. Right now for that target group, I just manually disabled it.
