### ISSUE TITLE
Publish image to ecr public.

### ISSUE THREAD

**Issue by BobDu** [kubernetes-sigs/aws-load-balancer-controller#2709]
**Is your feature request related to a problem?** 
Now, docker hub exist [rate limits](https://www.docker.com/increase-rate-limits/)
So, use alb image docker.io/amazon/aws-alb-ingress-controller is a bad idea.
But, if we use ecr region image, we need to set different image path in different region eks infra.

Can push image in ecr [public](https://gallery.ecr.aws/?searchTerm=aws-load-balancer-controller) .

**Describe the solution you'd like**
N/A
**Describe alternatives you've considered**
N/A

**Comment by kishorj** [comment]
We are already tracking this task, please refer to the issue #1990 for further details.
