### ISSUE TITLE
allow ALB to target service objects

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes-sigs/aws-load-balancer-controller#2716]
**Is your feature request related to a problem?**
It's my understanding that it is "hard-coded" to have ingress objects create ALBs, while Service objects create NLB. I would like to have the option of creating ALBs for service objects as well. This can be valuable especially for creating load balancers for the ingress controller itself.

**Describe the solution you'd like**
An Service annotation that lets me specify that an ALB should be created instead of an NLB

**Describe alternatives you've considered**
Creating the ALB myself.

**Comment by M00nF1sh** [comment]
@trondhindenes 
Yes, it's sort of "hard-coded" to only create ALB for Ingresses instead of Services. 
To create a ALB for your Service, you should create an Ingress targeting your Service.
