### ISSUE TITLE
Documentation points to IAM policy beyond quota limits for ACLSizePerRole

### ISSUE THREAD

**Issue by trmiller** [kubernetes-sigs/aws-load-balancer-controller#2718]
**Describe the bug**
Following the documentation posted on the [aws user guids](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html), under section 1 a - the example policies being shown are too large.  Doing so gets the error `Failed to create role <role name>.  Cannot exceed quota for ACLSizePerRole: 4096`

**Steps to reproduce**
* Create IAM Policy
* Select Custom Trust Policy
* Paste contents of [example a](curl -o iam_policy_us-gov.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.2/docs/install/iam_policy_us-gov.json) or [example b](curl -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.2/docs/install/iam_policy.json) 
* Name Policy
* See error

**Expected outcome**
* Policy should be created
* Even though these are just examples, following the steps should work

**Environment**

* N/A - related to AWS IAM Policy limits

**Additional Context**:
The default quote is 2048, upping it to the max of 4096 is still too big.

**Comment by kishorj** [comment]
@trmiller, the aws doc section 1 talks about creating the IAM policy. Your error indicates error with role creation. Did you use content from iam_policy.json in the trust configuration in section 2?

**Comment by kishorj** [comment]
@trmiller, I'm closing the issue. If problem persists, feel free to reach out.
