### ISSUE TITLE
Linkerd - set custom header

### ISSUE THREAD

**Issue by scottgerring** [kubernetes-sigs/aws-load-balancer-controller#2720]
**Is your feature request related to a problem?**
I'd like to be able to use linkerd with the ALB ingress, but I have no way of setting the `l5d-dst-override` header before traffic is passed from the ingress controller to linkerd. 

**Describe the solution you'd like**
I'd like a way to configure custom headers on the ingress annotations.

**Describe alternatives you've considered**

- Passing all traffic through an intermediate service first
- Putting Cloudfront in front of the whole thing to force the headers there 

This is also discussed https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1081

**Comment by scottgerring** [comment]
Hey @kishorj thanks for the reply!
Is there a workaround you are aware of? I've seen allusions to working with ALB scattered throughout the documentation but nothing concrete on implementation.

**Comment by M00nF1sh** [comment]
@scottgerring 
I'm not aware of workaround with ALB itself given it don't support request/response modification. You might use a NLB -> Nginx Ingress Controller to achieve it.(Nginx Ingress supports header modification)

Closing this for now given the ALB feature itself is tracked via #1571
