### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by sqsous-plenty** [kubernetes-sigs/aws-load-balancer-controller#2722]
**Is your feature request related to a problem?**
We have deployed our ingress with alb ingress controller, but we need to do some rate limiting on the services

**Describe the solution you'd like**
rate limiting annotations like in HAproxy or Traefik 

**Describe alternatives you've considered**
We tried to move to Traefik, but its not working as needed as ALB ingress controller 
also using WAF doesnt work, since its not that flexible

**Comment by kishorj** [comment]
@sqsous-plenty, would you not be able to use AWS WAF to achieve the rate limit? You can specify the waf acl arn via annotation, for further details, refer to the [addions](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#addons) live doc.

**Comment by sqsous-plenty** [comment]
The WAF is not flexible at all,
we cant define per second rate limit, which is what we need

**Comment by M00nF1sh** [comment]
@sqsous-plenty. our controller cannot support it until ALB itself provides the rate limit feature.

the only workaround is the WAF solution above with the limitations.

all ALB features will be centrally tracked at https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571, closing this.
