### ISSUE TITLE
support custom request header

### ISSUE THREAD

**Issue by shuaiyy** [kubernetes-sigs/aws-load-balancer-controller#2728]
**Describe the solution you'd like**

I need to add a cookie value to http header, just like the nginx ingress controller

```
nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header X-User-Id $cookie__id;"
```

**Comment by kishorj** [comment]
@shuaiyy, ALB doesn't support adding custom request headers at the moment. Feature request #1571 to keep track of the issue.

**Comment by kishorj** [comment]
Closing the issue since we are already tracking the feature request.

**Comment by riyasyash** [comment]
Any update on this feature?
