### ISSUE TITLE
Helm: add helm envFrom value parameter

### ISSUE THREAD

**Issue by cesarmira** [kubernetes-sigs/aws-load-balancer-controller#2729]
**Is your feature request related to a problem?**
We define our clusters name as a value in a Kubernetes secret. Then, we set the arg `- --cluster-name=$(CLUSTER_NAME)` (or `clusterName: $(CLUSTER_NAME)` in the chart. At the moment, as we can't set the envFrom from the chart, we need to template the chart and apply the resources via flux. 

**Describe the solution you'd like**
Update chart to include the value envFrom.

**Describe alternatives you've considered**
This is the only was to read secrets as env var.

**Comment by omerap12** [comment]
Hey, if this still necessary I can take it. @cesarmira @kishorj
