### ISSUE TITLE
How to apply security updates if github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master returns 404

### ISSUE THREAD

**Issue by 030** [kubernetes-sigs/aws-load-balancer-controller#2730]
**Describe the bug**
A concise description of what the bug is.

> ```
> Important
> 
> The deployed chart doesn't receive security updates automatically. You need to manually upgrade to a newer chart when it becomes available. When upgrading, change install to upgrade in the previous command, but run the following command to install the TargetGroupBinding custom resource definitions before running the previous command.
> 
> kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
> ```

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by kishorj** [comment]
Due to the `-k` flag, kubectl builds the resources using kustomize (ref: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) from the given URL and applies them. This URL is in go-getter format, you will get a 404 if you try with a normal http client.

You can do a dry-run of the kubectl apply to see what resources would be modified, for example:
```
 kubectl apply --dry-run=client -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
```

If you use install the helm chart via helm install, you need not run the `kubectl apply -k ...` for the CRDs.

**Comment by kishorj** [comment]
Not sure why you had the kubectl apply mixed up with security updates section.

For updating the controller, you can either update via helm, or apply a new manifest with the new controller version.

**Comment by 030** [comment]
@kishorj 

The important paragraph is mixed with helm and kubectl. When I read it I had the impression that one always should run the kubectl apply -k ... command even when helm was used in order to run an helm upgrade, but as I understand now I can just run a helm upgrade without issuing the kubectl apply -k ... command. 

> ```
> Important
> 
> The deployed chart doesn't receive security updates automatically. You need to manually upgrade to a newer chart when it becomes available. When upgrading, change install to upgrade in the previous command, but run the following command to install the TargetGroupBinding custom resource definitions before running the previous command.
> 
> kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
> ```

**Comment by kishorj** [comment]
If you are upgrading the chart, then `kubectl apply -k` is required. The helm install command will take care of the CRDs as well, so a separate `kubectl apply -k` is not required. The URL is in go-getter format, so you will get a 404 if you try to access directly, this is expected.

I'm closing this issue. If you have further concerns, feel free to reach out.
