### ISSUE TITLE
Stickiness not working with ALB weighted-routing

### ISSUE THREAD

**Issue by hanyhesham** [kubernetes-sigs/aws-load-balancer-controller#2734]
I was working on a project that requires weighted routing between two versions of the application, I used ALB ingress controller and sticky sessions.

I tried to enable sticky sessions by following this [doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#actions)
 
Then I added weighted routing as following:

    alb.ingress.kubernetes.io/actions.weighted-routing: |
      {
        "type":"forward",
        "forwardConfig":{
          "targetGroups":[
            {
              "serviceName":"example1",
              "servicePort":"80",
              "weight":50
            },
            {
              "serviceName":"example2",
              "servicePort":"80",
              "weight":50
            }
          ]
        }
      }

I got the following error:

`Warning  FailedDeployModel  4s (x8 over 5m18s)  ingress  (combined from similar events): Failed deploy model due to InvalidConfigurationRequest: This target group appears behind a rule with group stickiness disabled (arn:aws:elasticloadbalancing:us-east-2:xxxx). You must enable group stickiness before enabling target stickiness`

I searched for solutions and found one that is working with me:

Adding additional block in the `alb.ingress.kubernetes.io/actions.weighted-routing`

    alb.ingress.kubernetes.io/actions.weighted-routing: |
          "TargetGroupStickinessConfig": {
              "Enabled": true,
              "DurationSeconds": 120
          }
          
I don't know if i missed some instructions from the doc or  you should add this info, thanks.

**Comment by kishorj** [comment]
@hanyhesham, the annotation doc you referred to mentions the additional `TargetGroupStickinessConfig` as well in the annotation `alb.ingress.kubernetes.io/actions.forward-multiple-tg`. Could you confirm whether you enabled stickiness on the target group via the annotation `alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60`, and the target type is ip?

**Comment by hanyhesham** [comment]
@kishorj 

Yes I could see it, I just find it so confusing when referring to weighted-routing.

I was working on a PR that makes it more readable instead of mentioning it inside other parts, for e.g:

 - If you are using `alb.ingress.kubernetes.io/target-group-attributes` with `stickiness.enabled=true`, you should add `TargetGroupStickinessConfig` under `alb.ingress.kubernetes.io/actions.weighted-routing`
 
I fixed that part for my case, I just wanted to mention that in case someone else faced that.

**Comment by hanyhesham** [comment]
PR:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2740

**Comment by john-kajabi** [comment]
FYI: I only got this to work when i removed the other annotation for `stickiness.enabled=true`
