### ISSUE TITLE
ingressClass cannot be set as default when deployed using helm chart

### ISSUE THREAD

**Issue by robertpolasek-brt** [kubernetes-sigs/aws-load-balancer-controller#2738]
**Describe the bug**
In the helm chart there is ingressclass.yaml  file which is responsible for creation of ingressClass resource. Annotations are omitted from this file which prevents creation of default ingressClass as a part of helm chart. 

Default ingress class is specified by the annotation  `"ingressclass.kubernetes.io/is-default-class": "true"`.  

There should be a way to supply annotations for ingressClass from helm values and that way support default ingress class creation. 

* AWS Load Balancer controller version
 2.4.2  

* Kubernetes version
1.21

* Helm chart version
1.4.2

**Comment by kishorj** [comment]
@robertpolasek-brt, thanks for raising the issue. Feel free to raise a PR to address this.
