### ISSUE TITLE
K8s gateway support

### ISSUE THREAD

**Issue by yanivpaz** [kubernetes-sigs/aws-load-balancer-controller#2751]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
I want to use the new K8s gateway resource : https://gateway-api.sigs.k8s.io/
it can be either replacement for ingress resource  ( with more feature ) or replacement for this:  
https://aws.amazon.com/blogs/containers/integrate-amazon-api-gateway-with-amazon-eks/

**Describe alternatives you've considered**
stay with ingress resource

**Comment by kishorj** [comment]
@yanivpaz, thanks for bringing it up. This item is already in our roadmap and we have the issue #1338 to keep track of the feature.

**Comment by kishorj** [comment]
I will close this as a duplicate.

**Comment by yanivpaz** [comment]
its not the same  issue
