### ISSUE TITLE
Listener certificates for SNIInfo

### ISSUE THREAD

**Issue by AndriySidliarskiy** [kubernetes-sigs/aws-load-balancer-controller#2766]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

Listener certificates for SNI
Additional certificates support Server Name Indication (SNI). This enables the load balancer to support multiple domains on the same port and provide a different certificate for each domain.

Now I don't see annotation for this feature in alb. Can we resolve it?

**Comment by kishorj** [comment]
@AndriySidliarskiy, you can either configure multiple certificates via the annotation `alb.ingress.kubernetes.io/certificate-arn` [1], or let the controller automatically discover the certificates [2].

[1] https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#certificate-arn
[2] https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/cert_discovery/

**Comment by kishorj** [comment]
@AndriySidliarskiy, I'm closing the issue. If you have further concerns, feel free to reach out to us.
