### ISSUE TITLE
App routing if url is not root 404 response.

### ISSUE THREAD

**Issue by antonyRoberts** [kubernetes-sigs/aws-load-balancer-controller#2767]
**Describe the bug**

Single Page web application, where app loads fine if the url is the root, when the app is loaded routing within the app works as expected.  But if the page is to be opened, on anything but the root have 404 not found responses. 

So, https://example.com/ works as expected, but opening a page directly like https://example.com/home results in a 404.

 
**Steps to reproduce**

`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soc-frontend
  labels:
    app: soc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soc-frontend
  template:
    metadata:
      name: soc-frontend
      labels:
        app: soc-frontend
    spec:
      containers:
      - name: soc-frontend
        image: xxxxxxxxxxxxx
        imagePullPolicy: Always
        ports:
        - containerPort: 4020
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

apiVersion: v1
kind: Service
metadata:
  name: soc-frontend
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  selector:
    app: soc-frontend
  type: NodePort

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soc-alb-ingress
  annotations:
    # Ingress Core Settings
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=1800
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTP": 4020}, {"HTTPS":3701}, {"HTTPS":3641}, {"HTTPS": 443}, {"HTTP": 8080}, {"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.lb_cookie.duration_seconds=60
    alb.ingress.kubernetes.io/certificate-arn: xxxxxxxxxxxxxxxxxxxxxxx
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
    alb.ingress.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "80"
spec:
  rules:
    - host: ws-api.example.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: soc-api-server
                port:
                  number: 3701
    - host: ws-users.example.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: soc-users-server
                port:
                  number: 3641                  
    - host: example.com
      http:
        paths:
          - path: "/*"
            pathType: ImplementationSpecific
            backend:
              service:
                name: soc-frontend
                port:
                  number: 80
`
**Expected outcome**
Should send all routes on the host to the frontend service

**Environment**

* AWS Load Balancer controller version 
v2.4.3
        image: amazon/aws-alb-ingress-controller:v2.4.3
* Kubernetes version
1.22
*Using EKS (yes/no), if so version?
yes  eks.5
**Additional Context**:

**Comment by kishorj** [comment]
@antonyRoberts, your ingress spec indicates all paths for thestateofcomedy.com be forwarded to your soc-frontend service. Do you not see the ALB rules for this host? If the ALB listener rules are in place, check if the 404 is from your application.

**Comment by antonyRoberts** [comment]
Here are the rules in aws, 
IF Path is/auth/* Host isthestateofcomedy.com THEN Forward to k8s-default-socauths-7b4fbd3e1c: 1 (100%) Group-level stickiness: Off
IF Path is/* Host isthestateofcomedy.com THEN Forward to k8s-default-socfront-d0b1ecf3ad: 1 (100%) Group-level stickiness: Off 
last HTTPS 443: default action This rule cannot be moved or deleted IF Requests otherwise not routed THEN Return fixed response 404 (more...)

Routing all works like it should on local servers and on a kubernetes cluster served locally which is why I believe its an issue with the ALB, or I guess it could be the nginx.server serving the frontend app, but I'm not sure where I should make the change... Any help would be appreciated

**Comment by kishorj** [comment]
You could send request via curl with the -v option and check the response headers. If it is from ALB, you would have something similar to`server: awselb/2.0` in the header. If it is from your app, it would look something like `server: nginx`.

**Comment by antonyRoberts** [comment]
It was the nginx server, conf needed to have   
location / {
    try_files $uri $uri/ /index.html =404;
  }
thanks @kishorj for the help
