### ISSUE TITLE
configure feature gates with helm chart

### ISSUE THREAD

**Issue by nickvanwegen** [kubernetes-sigs/aws-load-balancer-controller#2775]
Hi, 

I opened a blank issue because I don't think its a bug but maybe something that is missing. 

I am trying to use feature gates when deploying using the helm chart maybe I am blind but I cannot see a way to configure them. 

In the docs I see that there is a flag to use `--feature-gates=key1=value1,key2=value2` but I cannot see a way to use this with the helm chart. I would maybe expect something like en `extraArg` value in the helm chart?

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/configurations/#feature-gates

If I missed something please let me know but I would like to use the `ServiceTypeLoadBalancerOnly` setting for my deployment.

**Comment by khizunov** [comment]
@kishorj can I take this?

**Comment by kishorj** [comment]
Closing the issue. The change will be included in the next chart release.

**Comment by nickvanwegen** [comment]
@kishorj Sorry to bother you but is there any idea of when the next helm chart release will be?
