### ISSUE TITLE
Support for app_cookie Target group attributes 

### ISSUE THREAD

**Issue by maxgda** [kubernetes-sigs/aws-load-balancer-controller#2778]
**Is your feature request related to a problem?**
We are trying to set a custom app_cookie for stickiness
in the annotation docs the following link is given for the target group attributes:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#target-group-attributes
In the code it seems that only 2 properties are actually supported(stickiness.enabled and duration).

**Describe the solution you'd like**
```
alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.type=app_cookie,stickiness.app_cookie.cookie_name=SERVERID,stickiness.app_cookie.duration_seconds=1860
alb.ingress.kubernetes.io/target-type: ip
```

**Describe alternatives you've considered**
custom name for the lb_cookie (AWSALB)

**Comment by kishorj** [comment]
@maxgda, the controller does not restrict the target group attributes you can specify in the annotation. What version of controller are you running?

**Comment by maxgda** [comment]
Hey @kishorj thanks for the quick response.
So my above 2 lines should work completely fine? I should receive a SERVERID cookie instead of AWSALB?

**Comment by kishorj** [comment]
@maxgda, I'm  closing the issue. If you are still unable to address your problem, feel free to reach out to us.
