### ISSUE TITLE
How should i debug this CRD?

### ISSUE THREAD

**Issue by lc32781971** [kubernetes-sigs/aws-load-balancer-controller#2781]
i want to add some logics to this crd and rebuild it again . 
is there a way to start it up locally ? how should i do the debugging ?

Thanks

**Comment by kishorj** [comment]
@lc32781971, are you looking to modify the CRDs or the validation? The current CRDs are defined in apis/elbv2/v1beta1, you can run `kustomize build config/crd` to generate new CRDs. The mutating/validating webhooks are in the webhooks/ directory.

**Comment by lc32781971** [comment]
> @lc32781971, are you looking to modify the CRDs or the validation? The current CRDs are defined in apis/elbv2/v1beta1, you can run `kustomize build config/crd` to generate new CRDs. The mutating/validating webhooks are in the webhooks/ directory.
> 
> If you are looking for something else, let us know.

i'm looking to customize the CRD , i need to start it up locally and debug , is there a developer guide ? there should be something i need to prepare before running it . can i know how did you guys do the development?

**Comment by kishorj** [comment]
You can refer to the contributing guidelines at https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/CONTRIBUTING.md. If there is anything missing or need further clarification, feel free to reach out to us.

**Comment by kishorj** [comment]
@lc32781971, I'm closing the issue. If you have further concerns, you can email us at `k8s-alb-controller-triage AT amazon.com`, or reach out on kubernetes slack, or reopen this issue.
