### ISSUE TITLE
AWS Load Balancer controller created public-facing Load balancer bound to private subnet

### ISSUE THREAD

**Issue by gsusI** [kubernetes-sigs/aws-load-balancer-controller#2782]
I wanted to share a situation that I've come across, which is puzzling me.

I found a Load Balancer created by the AWS Load Balancer Controller linked to one public subnet and one private subnet:

My subnets are adequately tagged to be automatically discovered by load balancers and ingress controllers, as described in [the documentation][1] and clarified in an ever more clear way in [this question][2]:
- Private subnets:
  - `kubernetes.io/cluster/<cluster_name>`: `shared`
  - `kubernetes.io/role/internal-elb`: `1`
- Public subnets:
  - `kubernetes.io/cluster/<cluster_name>`: `shared`
  - `kubernetes.io/role/elb`: `1`

My Load Balancer service in Kubernetes has the necessary annotations to state that it's a public-facing load balancer:

```
    service.beta.kubernetes.io/aws-load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=<bucket_name>,access_logs.s3.prefix=<prefix>
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: <eip_allocation_id_1>, <eip_allocation_id_2>
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <certificate_id>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-type: external
```

The manual workaround was to delete the Elastic Load Balancer and the LoadBalancer service in Kubernetes and then re-creating the service, which launched a new Elastic Load Balancer, this time with the right subnets attached.

Re-creating the service without deleting the ELB didn't help.

  [1]: https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html
  [2]: https://aws.amazon.com/premiumsupport/knowledge-center/eks-vpc-subnet-discovery/

**Comment by kishorj** [comment]
@gsusI, the subnet auto-discovery request uses the `vpc-id` and the `role` key as the filter. Controller auto-discovers the subnets during NLB creation only, it does not update the subnets later. It is possible the subnets had the public tag at the time of the service creation, could you verify the tags were not modified in your case?

**Comment by gsusI** [comment]
It might have happened that the subnets didn't have tags when the controller first created the NLB. I'm more hesitant to believe that the subnets had the wrong tags when the service was first created, but it is a possibility.

I did, however, delete the service, and even the cluster (not the NLB, though), and after re-creating the cluster, node groups, deployment and service the NLB linked to the newly created LoadBalancer service was still pointing to a private subnet.

**Comment by kishorj** [comment]
Controller doesn't modify the NLB subnets after creation. If you were to preserve the NLB somehow (possible, but a bit hacky), NLB will continue to have the original subnets.

**Comment by kishorj** [comment]
@gsusI, I'm closing the issue. If you are able to repro the issue or have further concerns, feel free to reach out to us.

**Comment by sophie-warner-annalise-ai** [comment]
I'm having a similar problem. I've also tried deleting the load balancer and the ingress. v2.13.3

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-ingress
  annotations:
    alb.ingress.kubernetes.io/frontend-nlb-scheme: internet-facing
    alb.ingress.kubernetes.io/enable-frontend-nlb: "true"
    alb.ingress.kubernetes.io/scheme: internal
```

Public and private subnets have both tags mentioned above, routes to an IGW, 57 IP addresses. 

There are no logs in the LBC relevant to subnets even with debug logs turned on.
