### ISSUE TITLE
Error: Waiting for default secret of "kube-system/aws-load-balancer-controller" to appear

### ISSUE THREAD

**Issue by b2jude** [kubernetes-sigs/aws-load-balancer-controller#2784]
**Describe the bug**
I'm getting the error below when creating service account for aws-load-balancer-service.  Hashicorp kubernetes provider v2.13.0 release note below stated that the bug is fixed.  I have configured the kubernetes provider v2.13.0 and tried to create the service account but i'm still getting the same error. As per release note, there are new resources that were added to the provider to handle the issue d/kubernetes_service_account, r/kubernetes_default_service_account, r/kubernetes_service_account.  I'm not sure how to use these resources to work with secrets  Can someone show me how to create service account for aws-load-balancer-controller using this kubernetes provider ?   

BUG Fixes Release note:
https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md#2130-august-23-2022

**Steps to reproduce**
resource "kubernetes_service_account" "aws-load-balancer-controller" {
count = var.is_enabled ? 1 : 0
metadata {
name = "aws-load-balancer-controller"
namespace = "kube-system"
labels = {
"app.kubernetes.io/name"= "aws-load-balancer-controller"
"app.kubernetes.io/component"= "controller"
}
annotations = {
"eks.amazonaws.com/role-arn" = var.aws_load_balancer_controller_role_arn
"eks.amazonaws.com/sts-regional-endpoints" = "true"
}
}

automount_service_account_token = true

}

**Expected outcome**
A concise description of what you expected to happen.
service account created 
**Environment**

* AWS Load Balancer controller version  NA
* Kubernetes version  1.24
* Using EKS (yes/no), if so version?  Yes

**Additional Context**:

**Comment by kishorj** [comment]
@b2jude, this is not specific to the aws-laod-balancer-controller. In previous releases, the `automount_service_account_token` needed to be set to true - it was false by default. Not sure what might have changed recently. Would you be able to follow up in the upstream?

**Comment by kishorj** [comment]
@b2jude, I'm closing this issue for now. If you have further concerns, feel free to reach out.
