### ISSUE TITLE
load-balancer-attributes, Reconciler error, Failed build model due to conflicting attributes

### ISSUE THREAD

**Issue by xgengsjc2021** [kubernetes-sigs/aws-load-balancer-controller#2787]
**Describe the bug**
I tried to enable access_log for my elb in eks cluster. After update the config of my ingress it did not take effect and returned errors. The below is the ingress setting

```
"alb.ingress.kubernetes.io/load-balancer-attributes" = "access_logs.s3.enabled=true,access_logs.s3.bucket=my-s3-logs,access_logs.s3.prefix=my-elb"

```

The error from ingress service:
```
Events:
  Warning  FailedBuildModel  6m25s (x5 over 11m)  ingress  Failed build model due to conflicting attributes access_logs.s3.prefix: my-elb | "my-elb"
  Warning  FailedBuildModel  57s (x13 over 11m)   ingress  Failed build model due to conflicting attributes access_logs.s3.bucket: my-s3-logs | "my-s3-logs"
```

The error from alb-aws-load-balancer-controller pod:
```
{"level":"error","ts":1661987614.1261075,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"my-dev-01-lb","namespace":"","error":"conflicting attributes access_logs.s3.bucket: my-s3-logs | \"my-s3-logs\""}
```

**Expected outcome**
expected to see the access_log enabled.

**Environment**

* AWS Load Balancer controller version
Helm version: "1.4.1"
* Kubernetes version: 
1.22

* Using EKS (yes/no), if so version?
yes, eks.4

**Comment by kishorj** [comment]
@xgengsjc2021, if you have an ingress group, then you need to ensure the load-balancer-attributes across ingresses don't conflict. You can either specify attributes on a single ingress or specify the same attributes across all ingresses in the group. The error indicate you have two values for the bucket names - one with quotes, and one without.

**Comment by xgengsjc2021** [comment]
@kishorj Thank you so much. The issue got fixed.
