### ISSUE TITLE
Multiple aws-load-balancer-controllers being able to share a single ALB

### ISSUE THREAD

**Issue by krishgu** [kubernetes-sigs/aws-load-balancer-controller#2788]
Does the AWS LB Controller support sharing a single ALB with multiple EKS's?

The tags that are seen on the load-balancer are:
Tag|Value
-- | -- 
`ingress.k8s.aws/resource` | LoadBalancer 
`ingress.k8s.aws/stack` | alb-name
`elbv2.k8s.aws/cluster` | cluster1-name

Does the `elbv2.k8s.aws/cluster` tag's value be a comma-separated set of values? How is it used in the "reconciliation" process by the AWS LB Controller?

Thanks.

**Comment by kishorj** [comment]
@krishgu, we currently don't have this feature in the immediate roadmap as it is difficult to share the load balancer level config between multiple controllers. There is a possibility of merging the listener rules configuration and utilizing weighted target groups to forward traffic to targets in different clusters.
