### ISSUE TITLE
Does the AWS LB Controller support sharing a single ALB with multiple EKS's?

### ISSUE THREAD

**Issue by krishgu** [kubernetes-sigs/aws-load-balancer-controller#2789]
Does the AWS LB Controller support sharing a single ALB with multiple EKS's?

The tags that are seen on the load-balancer are:
Tag|Value
-- | -- 
`ingress.k8s.aws/resource` | LoadBalancer 
`ingress.k8s.aws/stack` | alb-name
`elbv2.k8s.aws/cluster` | cluster1-name

Does the `elbv2.k8s.aws/cluster` tag's value be a comma-separated set of values? How is it used in the "reconciliation" process by the AWS LB Controller (especially the deletion of AWS resources such as Target-Groups, Rules etc) when the Ingress is deleted?

**Comment by kishorj** [comment]
@krishgu, Since this issue is similar to #2788, I'm closing it as a duplicate.
