### ISSUE TITLE
TargetGroupBinding can't bind external ip to the ALB target group rule

### ISSUE THREAD

**Issue by somnathpawar** [kubernetes-sigs/aws-load-balancer-controller#2794]
Hello, I am trying to use the ALB controller to create an ingress for an external service with IPv4 as endpoint. 

I have external IP which is configured as "Endpoints" for the service. It works completely fine with classic load balancer using nginx ingress controller. But when I am trying to use AWS Load Balancer controller & ALB, the target group rule is getting created for the ingress, but an external endpoint Is not getting registered on the Target Group target, as the IP is not part of VPC CIDR range but from outside host.

```items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      name: api
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 443
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Endpoints
    metadata:
      creationTimestamp: null
      name: api
    subsets:
      - addresses:
          - ip: 192.114.114.182
        ports:
          - port: 80
            protocol: TCP
            
   - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      creationTimestamp: null
      name: api
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: "ip"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/certificate-arn: "xxx.xxx.xxx"
    spec:
      ingressClassName: alb
      rules:
        - host: staging.xxx.com
          http:
            paths:
              - path: /api
                pathType: Prefix
                backend:
                  service:
                    name: api
                    port:
                      number: 80
    status:
      loadBalancer: { }  
```

Is there away to make this work? I want to register this external IP as target group target for the ingress.

**Comment by kishorj** [comment]
@somnathpawar, classic load balancer does not support IP targets. You could configure your ALB to use instance targets intead of ip targets. The LB controller doesn't support endpoint addresses that are not pod references. If you intend to use IP targets, you will require endpoints with pod references.

**Comment by kishorj** [comment]
This is similar to #2683

**Comment by somnathpawar** [comment]
> @somnathpawar, classic load balancer does not support IP targets. You could configure your ALB to use instance targets intead of ip targets. The LB controller doesn't support endpoint addresses that are not pod references. If you intend to use IP targets, you will require endpoints with pod references.

Perfect, this works with target type "instance". Thanks for the quick reply @kishorj!
