### ISSUE TITLE
Self Healing: Allow AWS Controller to Detect and Fix AWS Resource Changes on Interval

### ISSUE THREAD

**Issue by lucas-howard-macmillan** [kubernetes-sigs/aws-load-balancer-controller#2800]
**Is your feature request related to a problem?**

If a load balancer is deleted through the AWS Console, the AWS load balancer does not notice or re-create the load balancer.

The AWS load balancer controller must be restarted, and then the missing load balancer is recreated.

**Describe the solution you'd like**

An argument that could be passed into the controller indicating that it should do a full scan of AWS on a certain interval in an attempt to detect and fix drift within AWS from the expected state.

This would basically emulate the behavior that the AWS load balancer controller does when it starts up.

Potentially, for large deployments, you might also need a segment size argument as well
i.e.

Every 5 minutes scan AWS for 100 ingresses, then the next 5 minutes the next 100 ingresses etc..

**Describe alternatives you've considered**

I have used all existing arguments, such as sync period, but none of them cause the load balancer to be re-created.

**Comment by kishorj** [comment]
/assign @M00nF1sh 
Investigate further on the periodic sync issue
This is similar to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2515

**Comment by lukonjun** [comment]
Experienced the same behaviour. I assumed when I delete the LB via the AWS Console the ALB Controller would automatically recreate, however it did not.

**Comment by 0xF4D3C0D3** [comment]
I'm experiencing the same issue. It only gets recovered when the number of replicas behind the service is changed.

**Comment by ChrisV78** [comment]
Experienced the same by accident, removed a ALB from the AWS console and the lb-controller only recreates the ALB the moment you restart the lb-controller deployment.

**Comment by lucas-howard-macmillan** [comment]
@oliviassss Thank You!
