### ISSUE TITLE
Option to disable ingress validation webhook

### ISSUE THREAD

**Issue by nickvanwegen** [kubernetes-sigs/aws-load-balancer-controller#2801]
**Is your feature request related to a problem?**

I am already using ingress-nginx for my ingress objects. Sometimes I encounter some issues where the LB-controller wants to validate ingress objects while its not even handling them 

**Describe the solution you'd like**

I would like to be able to disable the ingress validating part of the lb-controller validating webhook

**Describe alternatives you've considered**

none just want to be able to disable lb-controller webhook from validating ingress objects.
I also notived the feature-gate to let the LB-controller only look at service of type loadbalancer but i see that the webhook is installed via helm and there is no bool to enable or disable the ingress part so this would also not fix it.

**Comment by lakshkeswani** [comment]
@kishorj I am interested on working on this and I am new to this repository, can you please guide me from where I should start

**Comment by nuno-silva** [comment]
#3011 seems to be taking care of the disabling the webhook for ingresses.

However, another part of this issue, which I believe is what was #2939 was about, is being able to disable the ingress/ALB part of the controller completely.

This is currently possible for Service/NLB via the `EnableServiceController` feature gate, but not for Ingress/ALB. A new `EnableIngressController` feature gate would solve this. Is this being considered? If not, perhaps #2939 should be re-open.

A workaround for this is to use an ingress class that does not exist, such as `--ingress-class=this-class-does-not-exist-on-purpose`.

**Comment by samcannell** [comment]
I disagree; I'd really like the Helm chart to provide the selectively disable parts of the admission webhook configuration.

My use case is that I'm deploying aws-load-balancer-controller from Terraform using the Helm chart.  I'm **only** using aws-load-balancer-controller to manipulate the members of an ALB target group; there are no Service or Ingress resources that it's responsible for looking after.

There is no reason that Terraform should need to manage ordering carefully here, however if I leave ordering up to Terraform I often run into issues where the ValidatingWebhookConfiguration resource is created before the Service backing it is ready to serve connections, which will cause any attempt to create an Ingress resource to fail.

My only option is to add dependencies onto **every** Terraform module that needs to create an Ingress resource, which absolutely tanks the performance of Terraform's plan phase.  I can't stress this enough -- the time taken to run `terraform plan` drops from ~15 minutes to 30 seconds if I just remove the top-level inter-module dependencies referring to aws-load-balancer-controller.

Now, this is undoubtedly a deficiency with Terraform, but I don't think it negates my point that I don't need the AWS LB controller to manage Ingress resources, so it shouldn't ever interfere with my creation of them.  Undoubtedly I'm probably using the AWS LB controller in a somewhat unconventional way, but I don't feel that makes my use case any less valid.

**Comment by aceeric** [comment]
I created a very similar issue along these lines which addresses a variation of this issue:  [11341](https://github.com/kubernetes/ingress-nginx/issues/11341). The common theme is - integrators are deploying workloads with automation tools and the ingress controller validation behavior doesn't support some of those use cases.

**Comment by xer0devit** [comment]
Business case for requesting AWS to release a formal feature which allows their stakeholders to disable Ingress management completely (incl. validation) within AWS Load Balancer Controller by means of a customer friendly configuration handle (for example user-supplied helm-chart value):

- Operationalize out-tree AWS Load Balancer Controller as recommended by AWS with the goal to benefit from formal support and new features, for purpose of only managing service resource (NLB, TG). A seperate Ingress Controller product is used to control our Ingress resources (TLS termination, path rewrite,...etc).
- Depending on a plethora of workarounds tends to question the operational, production readiness of a product as proclaimed new default. What guarantees those workarounds even keep working as newer versions of the get released ?

**Comment by oliviassss** [comment]
@xer0devit, hi, as long as you do not specify `controller: ingress.k8s.aws/alb` in the ingress class, or `kubernetes.io/ingress.class: alb` on the ingress, the controller won't manage these ingresses at all.

**Comment by shethyogita83** [comment]
Hey @xer0devit,

Thanks for sharing your use-case with us. 

We reviewed this issue with our team and are planning to add it to our roadmap list.

Meanwhile, community contributions are also welcome to fix this issue.

Thanks
