### ISSUE TITLE
backendSecurityGroup setting ignored

### ISSUE THREAD

**Issue by chriskinsman** [kubernetes-sigs/aws-load-balancer-controller#2811]
**Describe the bug**
ALB not using Backend sg

I am specifying --enable-backend-security-group=true
--backend-security-group=sg-XXXXXXXXXXXXX

**Steps to reproduce**

Setup aws-load-balancer-controller with above options
Launch an app that uses ingress, in our case an AWS EMR managed endpoint started with created-managed-endpoint
Check security groups on ALB.  They do not include group in command line.

Logs show:

{"level":"info","ts":1663799897.8904047,"logger":"controllers.ingress","msg":"SG configured via annotation","LB SGs":["sg-XXXXXXXXXXXXXXXXXXX"],"backend SG":null}

Note no backend SG.  Unclear if that SG should be coming from ingress annotation or via the backendSecurityGroup setting but in any case the backendSecurityGroup setting is not being added the sec

**Expected outcome**
A concise description of what you expected to happen.

The backendSecurityGroup to be retrofitted onto existing ALBs and added to new ALBs

**Environment**

* AWS Load Balancer controller version : 2.4.3
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes 1.21

**Additional Context**:

**Comment by chriskinsman** [comment]
Found that this setting won't affect already running ALBs.  Only affects newly created ones...

**Comment by chriskinsman** [comment]
Actually it looks like what might be happening is this setting gets overriden by the security-groups annotation on the ingress perhaps?  Is there a way to make this additive?

In this case aws emr-containers create-managed-endpoint is creating the ingress and we have no control over it.  The ALB is broken because we need an additional group added to ensure that the ALB can connect to the nodes.

**Comment by kishorj** [comment]
@chriskinsman, you can annotate your ingress as follows to configure backend rules:
```
alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
```

For further details you can refer to the live docs at https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#manage-backend-security-group-rules

**Comment by chriskinsman** [comment]
I don't control the ingress.  It is created by the aws cli.  

I think you are saying the only way to make this work is to manually update the ingress after the aws cli creates it.

**Comment by kishorj** [comment]
@chriskinsman, if Ingress is managed by some other component, any manual changes could get overwritten. 

With the security-groups annotation, the ingress SG rules need to be configured separately unless the `alb.ingress.kubernetes.io/manage-backend-security-group-rules` annotation is set to `true`. Is your use case different than the one configured by emr?

**Comment by chriskinsman** [comment]
The aws cli with emr-containers just sets it up manually so adding the annotation manually shouldn't get overwritten.

We will follow up with that team to offer an option to set that annotation when they create the ingress.
