### ISSUE TITLE
Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet

### ISSUE THREAD

**Issue by hiteshghia** [kubernetes-sigs/aws-load-balancer-controller#2812]
When trying to deploy the sample application [here](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) the controller is failing to create the load balancer with the following error:
```│ 
{"level":"debug","ts":1663820503.429755,"logger":"controller-runtime.manager.events","msg":"Warning","object":{"kind":"Ingress","namespace":"ga ││ me-2048","name":"ingress-2048","uid":"f748a08a-08ba-4409-a2ca-71eff8262a75","apiVersion":"networking.k8s.io/v1","resourceVersion":"2315298"},"r ││ eason":"FailedBuildModel","message":"Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet"}
```
 
Followed [this](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) guide to deploy the aws load balancer controller.
Using the iam policy linked in that doc.
All my public subnets have the  tags:
```
kubernetes.io/role/elb | 1
kubernetes.io/cluster/<clusterName> | owned
```
And all of my private subnets have the tags:
```
kubernetes.io/role/internal-elb | 1
kubernetes.io/cluster/<clusterName> | owned
```

What else can I check for?

**Environment**

* AWS Load Balancer controller version -  2.4.3
* Using EKS - Yes, 1.22

**Comment by hiteshghia** [comment]
After I added this annotation explicitly listing out the subnets, it did the needful - 
`alb.ingress.kubernetes.io/subnets:`
but its not ideal.

**Comment by kishorj** [comment]
Check if you are able to query the subnets via the aws-cli:
```
aws ec2 describe-subnets --filters Name=tag:kubernetes.io/role/elb,Values=1 Name=tag:kubernetes.io/cluster/<clusterName>,Values=shared,owned
```
Also verify if the cluster name is configured correctly in the controller command line flags.

**Comment by hiteshghia** [comment]
Thanks @kishorj , yes I did run that and it correctly returns the 3 public subnets in different azs. 
Also the clusterName is correctly configured in the controller command args.

**Comment by kishorj** [comment]
@hiteshghia, could you send the cloud-trail trace for the `DescribeSubnets` calls in both cases:
- When you run the aws describe-subnets cli
- The call made by the lb controller
You can email the details to k8s-alb-controller-triage AT amazon.com.

**Comment by kishorj** [comment]
@justinrlee, controller provisions internal NLB by default unless you specify the scheme via the annotation  `service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing`. 

Since you've specified the loadBalancerClass, the annotation  `service.beta.kubernetes.io/aws-load-balancer-type: external` has no effect.

**Comment by justinrlee** [comment]
Ah, thank you! Somehow I missed that documentation note.

**Comment by neoakris** [comment]
You basically need to tag subnets correctly (and you have to do it for at least 2 subnets, the error message incorrectly says at least 1)
https://aws.amazon.com/premiumsupport/knowledge-center/eks-load-balancer-controller-subnets/

If you manage VPC with Terraform TF is great about updating tags instantly.

public_subnet_tags = {
  "kubernetes.io/cluster/${local.cluster_name}" = "shared"
  "kubernetes.io/cluster/temp"                  = "shared" # temp extra cluster
  "kubernetes.io/role/elb"                      = "1"
}
private_subnet_tags = {
  "kubernetes.io/cluster/${local.cluster_name}" = "shared"
  "kubernetes.io/cluster/temp"                  = "shared" # temp extra cluster
  "kubernetes.io/role/internal-elb"             = "1"
}
