### ISSUE TITLE
Question: create LB on other VPC doesn't work.

### ISSUE THREAD

**Issue by sleep-dev** [kubernetes-sigs/aws-load-balancer-controller#2818]
Currently we have the eks on "A" VPC, and I want to make LB on "B" VPC which is connecting via Transit Gateway.

In the EKS on "A" VPC, I install the aws-load-balancer-controller by below command
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=my-cluster \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller 
  --set vpcId=vpc-ID of B VPC

I made the some ingress on the EKS, but target in the target-group of created aws-lb is empty.
(aws-lb which created by aws-load-balancer-controller is in "B" vpc)

is there something wrong in my progress? or is it impossible?
please help

**Comment by kishorj** [comment]
@sleep-dev, could you provide the following info:
- controller version, k8s version
- Are the VPCs in the same AWS account?
- Target type: ip or instance
- do you see any errors in the controller logs

**Comment by sleep-dev** [comment]
@kishorj thank you for comment.

controller version :	v2.4.1  ( helm chart version 1.4.1 )
vpc are in same account
both target type doesn't work basically we use the ip type. 

with the ip type, controller shows the below log.

{"level":"error","ts":1664306754.7946818,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"k8s-infra-argocdar-bfb92bf06b","namespace":"infra","error":"InvalidGroup.NotFound: You have specified two resources that belong to different networks.\n\tstatus code: 400, request id: 847a5156-507f-4c1e-950d-b95f3c7992c2"}

The targetgroup which created by controller belong in B VPC which lb created in while I think the target group should belong in A VPC because the ip target is in EKS Cluster. 

is there something wrong that i know?

**Comment by kishorj** [comment]
Could you verify you setup VPC peering between the two VPCs - you will need peering to be setup if you intend to share security groups across the VPCs. The reconcile failure is on the AuthorizeSecurityGroupIngress call where controller is trying to setup ingress rules on the ENI(instance) security group on your VPC with the EKS cluster.

**Comment by sleep-dev** [comment]
It is hard to peering cause we already use the Transit Gateway.
is there any other option? like setting security group manually.

**Comment by sleep-dev** [comment]
@kishorj  It works now thank you
