### ISSUE TITLE
error with chart version 1.4.5

### ISSUE THREAD

**Issue by onacht** [kubernetes-sigs/aws-load-balancer-controller#2820]
**Describe the bug**
upgrading chart version from 1.4.2 to 1.4.5 and the new pod enters a state of crashloopback with the error:
standard_init_linux.go:228: exec user process caused: exec format error 
this is the only log that is avalible

**Expected outcome**
pod should have been running

* Kubernetes version
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.11-eks-18ef993
* Using EKS (yes/no), if so version?
* 1.22

**Comment by kishorj** [comment]
@onacht, which AMI do you use for the worker nodes?

**Comment by M00nF1sh** [comment]
is it amd64 or arm64 for your worker nodes?

**Comment by onacht** [comment]
hi, thank you for your answers
i pulled the image, tagged it and pushed to our ecr using my mac
the problem was that my mac have a m1 processor which caused the format error
