### ISSUE TITLE
Configure ingress with new group name does not delete old alb automatically

### ISSUE THREAD

**Issue by jennyli-z** [kubernetes-sigs/aws-load-balancer-controller#2821]
**Describe the bug**
Configure ingress with new group name does not delete old alb automatically

**Steps to reproduce**
1. create ingress with name A
2. change ingress name to B(it already created alb before for other ingress)
3. the ingress change to bind with new alb
4. check the aws console ,the old one still exists.

**Expected outcome**
The old one should be deleted automatically.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?
yes,Using EKS. 1.23
**Additional Context**:

**Comment by jennyli-z** [comment]
finalizers:
    - group.ingress.k8s.aws/[New group]

Yes, it has  a finalizer with new created group of alb.

**Comment by Fodoj** [comment]
I've noticed the same issue - adding or changing group on Ingress objects creates new ALB (good) but does not clean up the old ALB (not good)
