### ISSUE TITLE
Preserve existing third-party AWS Load Balancer tags.

### ISSUE THREAD

**Issue by guntiseiduks** [kubernetes-sigs/aws-load-balancer-controller#2822]
**Is your feature request related to a problem?**
Kubernetes AWS Load Balancer controller is removing all tags and recreating only k8s managed tags during update operation, i.e. third party tags are removed. That creates resource governance problem in case there are tags that must not be deleted due to, for example, IAMs or organization wide SCPs set on tags.

**Describe the solution you'd like**
Existing tags are preserved and union of k8s managed and third party tag keys is applied to application load balancer where k8s managed tag keys are taking precedence.

**Describe alternatives you've considered**
Alternatives can be custom governance solution which involves much effort and seems not to be the best practice solution for this problem.

**Comment by M00nF1sh** [comment]
@guntiseiduks 
For this use case, the controller exposed a flag called `--external-managed-tags` where you can supply a list of tagKeys to be whitelisted and these tags will then be not touched by the controller.  see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/configurations/
e.g. `--external-managed-tags=TagKeyA,TagKeyB`.

**Comment by guntiseiduks** [comment]
> @guntiseiduks For this use case, the controller exposed a flag called `--external-managed-tags` where you can supply a list of tagKeys to be whitelisted and these tags will then be not touched by the controller. see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/configurations/ e.g. `--external-managed-tags=TagKeyA,TagKeyB`.
Got it. Thank you for the tip that should do the trick.
