### ISSUE TITLE
Prometheus endpoint is exposing high cardinality unbounded metrics

### ISSUE THREAD

**Issue by fkrestan** [kubernetes-sigs/aws-load-balancer-controller#2823]
**Describe the bug**

It seems that the `rest_client_request_latency_seconds` histogram metric exposed on the Prometheus metrics endpoint has unbounded cardinality. At the minimum, it seems to include a `url` label which contains URIs of all API versions registered in a given Kubernetes API server including it's query parameters. In my clusters, this is 742 time series per controller instance.

An example of the metrics including labels as exposed by the metrics endpoint to the Prometheus:
```
...
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.002"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.004"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.008"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.016"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.032"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.064"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.128"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.256"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="0.512"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET",le="+Inf"} 1
rest_client_request_latency_seconds_sum{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET"} 0.001278107
rest_client_request_latency_seconds_count{url="https://172.20.0.1:443/apis/batch/v1?timeout=32s",verb="GET"} 1
...
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.002"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.004"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.008"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.016"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.032"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.064"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.128"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.256"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="0.512"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET",le="+Inf"} 1
rest_client_request_latency_seconds_sum{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET"} 0.005832849
rest_client_request_latency_seconds_count{url="https://172.20.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s",verb="GET"} 1
...
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.002"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.004"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.008"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.016"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.032"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.064"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.128"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.256"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.512"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="+Inf"} 1
rest_client_request_latency_seconds_sum{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET"} 0.004987509
rest_client_request_latency_seconds_count{url="https://172.20.0.1:443/apis/networking.k8s.io/v1/ingressclasses?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET"} 1
...
```

See
- https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels
- https://prometheus.io/docs/practices/naming/

on why this is an issue.

**Steps to reproduce**

Deploy the `aws-load-balancer-controller` using the Helm Chart with the `ServiceMonitor` enabled (`serviceMonitor.enabled=true` Chart value). Get metrics from the exposed Prometheus endpoint (Chart default, `:8080/metrics`).

**Expected outcome**

The `rest_client_request_latency_seconds` metric either not being present at in the exposed metrics or filterable via the `ServiceMonitor` deployed by the Helm Chart.

**Environment**

* AWS Load Balancer controller v2.4.4.
* Kubernetes version v1.21
* EKS v1.21.14-eks-6d3986b

**Additional Context**:

This can be solved on multiple levels:
- If this is intended behavior
  - introduce a cli flag to disable this metric or
  - allow filtering out (dropping) the metric in `ServiceMonitor` deployed through the Helm Chart using the `spec.endpoints.relabelings` field.
- If this is not intended remove the metric from the exposed metrics endpoint.

**Comment by fkrestan** [comment]
The `Helm Chart` changes to `ServiceMonitor` seems like a quick solution that should be useful beyond the scope of this issue. I can send a PR for this if you think that's the best course of action.

That being said, dropping the metrics, either via a flag or unconditionally, seems like the more correct long term solution.

**Comment by M00nF1sh** [comment]
@fkrestan 
The metrics cames from our controller-runtime dependency. With some research, seems that they have removed this metrics in new versions: https://github.com/kubernetes-sigs/controller-runtime/issues/1423

We'll update the dependencies to have this change in up-coming releases.

**Comment by jdn5126** [comment]
> @fkrestan The metrics cames from our controller-runtime dependency. With some research, seems that they have removed this metrics in new versions: [kubernetes-sigs/controller-runtime#1423](https://github.com/kubernetes-sigs/controller-runtime/issues/1423)
> 
> We'll update the dependencies to [v0.9.7](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.9.7) to have this change in up-coming releases.

@M00nF1sh feel free to assign this to me

**Comment by jdn5126** [comment]
This issue can be closed

**Comment by yodaflomaster** [comment]
Hello @jdn5126 @M00nF1sh 
I updated helm chart version current version 

- Chart version: 1.4.6
- AWS Load Balancer controller: v2.4.5
- EKS: 1.21.14-eks-fb459a0

And redeploy helm chard (delete and install) but i still see exposed rest_client_request_latency_seconds_bucket metrics from aws-load-balancer-controller.
`# HELP rest_client_request_latency_seconds Request latency in seconds. Broken down by verb and URL.
# TYPE rest_client_request_latency_seconds histogram
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.002"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.004"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.008"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.016"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.032"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.064"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.128"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.256"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="0.512"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET",le="+Inf"} 1
rest_client_request_latency_seconds_sum{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET"} 0.010152667
rest_client_request_latency_seconds_count{url="https://172.20.0.1:443/api/v1/endpoints?limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D",verb="GET"} 1
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/namespaces/%7Bnamespace%7D/configmaps/%7Bname%7D",verb="GET",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/namespaces/%7Bnamespace%7D/configmaps/%7Bname%7D",verb="GET",le="0.002"} 0
rest_client_request_latency_seconds_bucket{url="https://172.20.0.1:443/api/v1/namespaces/%7Bnamespace%7D/configmaps/%7Bname%7D",verb="GET",le="0.004"} 127`

Service Monitor disabled.
`serviceMonitor:
  enabled: false
  additionalLabels: {}
  interval: 1m`

**Comment by tenitski** [comment]
Same here, metric is still emitted.
