### ISSUE TITLE
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled annotation doesn't work

### ISSUE THREAD

**Issue by khumps** [kubernetes-sigs/aws-load-balancer-controller#2826]
**Describe the bug**
Adding the annotation `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled="true"`
Causes the service to not be able to create an NLB with the error `Error syncing load balancer: failed to ensure load balancer: error parsing service annotation: service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled="true"`
**Steps to reproduce**

Create a service with the following definition:
```
Name:                     ingress
Namespace:                ingress
Annotations: 
                          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
                          service.beta.kubernetes.io/aws-load-balancer-type: nlb
Type: LoadBalancer
```

**Expected outcome**
Service should respond with `Ensuring load balancer` and a NLB should be created with cross zone load balancing enabled.

**Environment**

* AWS Load Balancer controller version: `2.4.4`
* Kubernetes version: `1.21`
* Using EKS (yes/no), if so version? `11`

**Additional Context**:
Creating the service without cross-zone-load-balancing-enabled succeeds, adding the annotation after ensures load balancer **but does not actually check off cross zone load balancing**

**Comment by M00nF1sh** [comment]
@khumps 
I think what you were doing is 
```
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: '"true"'
```
So the value became `"true"` instead of `true`
You should use either
```
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```
```
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
```

**Comment by khumps** [comment]
> @khumps I think what you were doing is
> 
> ```
> service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: '"true"'
> ```
> 
> So the value became `"true"` instead of `true` You should use either
> 
> ```
> service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
> ```
> 
> ```
> service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
> ```
> 
> You can confirm the above theory by `kubectl get service/<youObject> -o yaml`

Interesting, when I run `kubectl describe service <my-service>` it outputs 
```
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```

But when I run `kubectl get <my service> -o yaml` it outputs 
```
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: '"true"'
```

The service manifest is being generated by helm. Using `--set-string` instead of `--set` solved my issue. Thanks for help troubleshooting!
