### ISSUE TITLE
Dry Run Mode

### ISSUE THREAD

**Issue by RoryCrispin** [kubernetes-sigs/aws-load-balancer-controller#2828]
This is a Feature Request

Has a Dry Run mode been considered? 

Use Case:
We are currently working towards rolling out an upgrade from the legacy in-tree controller to this much improved controller but are finding a few issues in assuring ourselves that the migration will not cause downtime for in-use Load Balancers.

I have read through the source code and understand that so long as we tag the existing load balancer such that it is recognised by the tracking code in https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/deploy/tracking/provider.go  then the controller will adopt it - and I have taken the precaution of removing the various Delete IAM grants from the ServiceAccount policy - however the controller still has the ability to cause downtime in a number of ways. For instance, I have seen it create a new target group and update the load balancer listeners to point at that instead.

In all of these cases I would sleep easier knowing that we had previewed the modifications that the controller planned to enact before we run them on a live environment.

**Comment by M00nF1sh** [comment]
@RoryCrispin 
Thanks for this feature request. How would you prefer to let the dry-run output the details? e.g. in logs to outline changes will be done?

I think for now, it would work if you remove all "write" IAM permissions assigned to the controller(except for write tags).

**Comment by RoryCrispin** [comment]
Hey @M00nF1sh,

As you say - running the service with only tag write permission effectively puts it into dry-run mode, having a `--dry-run` flag would simply be a convenience factor. It's generally supported across the ecosystem of controllers, for instance `external-dns` supports a `--dry-run` and also an `--upsert-only`

I find that the controller is pretty good at logging what it wants to do and also continuing to work just fine when permissions are not granted to it, so the IAM solution is a passable workaround, thanks.

On a tangent, I did find that sometimes it would be helpful if the controller explained why it wants to perform certain actions - for instance I spent some time tracing a target group recreation before finding that the controller wanted to do so to update the health check interval, so it may be nice to add some logging in there for audit sake, say I get a page that the controller has rolled the target group at 2am - I would appreciate knowing why it did so - in any case this controller is a significant improvement on the verbosity of the in-tree controller.

You mention  that the migration path from the `legacy in-tree controller` is not supported. Do you plan to support this at all in the future? 
When the in-tree controller is dropped from k8s then I expect that there will be a group of EKS users needing to migrate production critical workloads to the new controller.
This was briefly discussed at the SIG Cloud Provider meeting at Kubecon Valencia and I understood that the migration path would be built out at some point in the future,

Anecdotally - if the resources are tagged correctly and TargetGroupBindings are retroactively constructed then this migration can run smoothly.

Apologies for rambling on the ticket, let me know if there is a better forum to discuss this off topic content. Perhaps you have office hours? 

Thanks
