### ISSUE TITLE
Ability to define custom name and tags for Security Groups

### ISSUE THREAD

**Issue by felipeng** [kubernetes-sigs/aws-load-balancer-controller#2830]
**Is your feature request related to a problem?**
Yes, because is hard to identify which Security Groups is for each LB because the SecurityGroups are created without name nor tags

**Describe the solution you'd like**
It would be very useful to be able to define the Security Groups' name and tags via annotations

**Describe alternatives you've considered**
No idea

**Comment by M00nF1sh** [comment]
@felipeng 
With v2.0.0+ version, the security groups already have tags like below
```
ingress.k8s.aws/stack: game-2048/ingress-2048
elbv2.k8s.aws/cluster: m00nf1sh-dev-123
ingress.k8s.aws/resource: ManagedLBSecurityGroup
```
will above be sufficient? the `ingress.k8s.aws/stack` is the Ingress's name/namespace

**Comment by felipeng** [comment]
I am using 2.4.4, I've noticed that the AWS Load Balancer Controller created a SG rule in existing SecurityGroup, however, 
and the description is: `elbv2.k8s.aws/targetGroupBinding=shared` it would be nice to link with the NLB resource adding the name or DNS name there
