### ISSUE TITLE
Subnet getting selected for launching load-balancer(classic) even if required tags absent 

### ISSUE THREAD

**Issue by chetandhembre** [kubernetes-sigs/aws-load-balancer-controller#2832]
**Describe the bug**
I created subnet with proper tags so that it will be consider while creating load-balancer. But after sometime removed all tags, I was expecting going forward subnet wont be use when new load-balancer created. 

**Steps to reproduce**
1. create subnet
2. add all required tags so that loadbalancer will be created in subnet
3.  remove all tags from subnet
4. create new loadbalancer 

**Expected outcome**
We subnet tags are removed, it should not be used in creating load-balancer 

**Environment**
* AWS Load Balancer controller version: ``
* Kubernetes version `1.23`
* Using EKS (yes/no), if so version?: yes eks version `eks.2`

**Additional Context**:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2832#tasklist-block-a1cd86d4-236b-4389-97f0-6896ab242344

**Comment by kishorj** [comment]
If the subnets do not have any cluster tags at all, the subnets do get considered for auto-discovery. If there are multiple subnets for the same AZ, then subnets tagged for the cluster gets precedence.

**Comment by kishorj** [comment]
@chetandhembre, what is the tag you removed? kubernetes.io/cluster/${cluster-name} or something else? Please refer to https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/subnet_discovery/ for further details.

**Comment by chetandhembre** [comment]
I removed all tags only Name tag is present.
