### ISSUE TITLE
Add annotation for drain state of nodes

### ISSUE THREAD

**Issue by thefirstofthe300** [kubernetes-sigs/aws-load-balancer-controller#2837]
My company's k8s clusters make use of Flatcar as the node OS and we make use of [FLUO](https://github.com/flatcar/flatcar-linux-update-operator) for automatic updating. FLUO coordinates reboots across nodes through the use of annotations and labels to ensure that no more than one node is rebooting at a time. The reboot sequence essentially starts with the node being cordoned, followed by an annotation being set when all pods are evicted signaling the agent on the node to reboot the instance, followed by an annotation cleanup on the other side of the reboot to ensure that the reboot doesn't occur again.

My problem comes when the reboot occurs. Right now, FLUO and the ALB controller are racing to complete their node operations first: FLUO is racing to reboot the node and the ALB controller is racing to drain the node. Every time FLUO appears to win, causing a burst of 504s being thrown by the ALB.

FLUO has a mechanism to allow external processes to signal when FLUO can safely reboot the node using before/after annotations. If the specified before-reboot annotation is not set to `true`, FLUO will wait until an external process sets it to true. The specified after-reboot annotation will cause FLUO to reboot the node and wait until an external process sets the annotation to true before continuing with more reboots.

Obviously, I could write my own automation to check the drain state of the node across all LBs; however, it makes more sense to have the ALB controller set the annotation as it already keeps track of this state for all relevant LBs.

What are people's thoughts on adding an option to have the ALB controller set a node annotation based on the registration status of a node for all LBs, e.g. `elbv2.aws.com/node-deregistered=true/false`?

**Comment by kishorj** [comment]
@thefirstofthe300, you can apply the label `node.kubernetes.io/exclude-from-external-load-balancers` to your node resources. On seeing this label, controller will de-register the instance target from the load balancer target group. You could start the cordon process and the reboot after the label is applied. In case of de-registration, the target will be in Draining until the existing connections get flushed out, or a timeout specified via deregistration delay on the target group.

**Comment by thefirstofthe300** [comment]
Unfortunately, this solution doesn’t address the issue at all. The set of steps you laid out is currently what our clusters do. The issue lies in timing. As you acknowledge, there is a stretch of time after deregistration when requests are drained away from the node. If all of the pods are evicted before the drain completes, the reboot occurs, forcibly closing the connections proxied through the node (even if the ALB and ALB controller believes it has, for example, another 240 seconds to complete the drain) and leading to the 504 spike.What I am asking for is some sort of annotation to be applied to the instance indicating the status of the ALB’s drain, e.g. is it complete (true/false). I was thinking this annotation would be useful to block the reboot controller on.On Oct 19, 2022, at 3:25 PM, Kishor Joshi ***@***.***> wrote:﻿
@thefirstofthe300, you can apply the label node.kubernetes.io/exclude-from-external-load-balancers to your node resources. On seeing this label, controller will de-register the instance target from the load balancer target group. You could start the cordon process and the reboot after the label is applied. In case of de-registration, the target will be in Draining until the existing connections get flushed out, or a timeout specified via deregistration delay on the target group.
