### ISSUE TITLE
opentelemetry support on alb controller

### ISSUE THREAD

**Issue by atilsensalduz** [kubernetes-sigs/aws-load-balancer-controller#2842]
Hi folks,

is there a way configure distributed tracing on ingress controller? I would like to send span data to my observability backend.

Regards,

**Comment by M00nF1sh** [comment]
@atileren 
I haven't tried opentelemetry, but seems AWS offers a https://aws.amazon.com/blogs/opensource/distributed-tracing-with-opentelemetry/, and the `X-Amzn-Trace-Id ` tracking header is supported by ALB.
