### ISSUE TITLE
Listener gets deleted on NLB

### ISSUE THREAD

**Issue by DanielMcAssey** [kubernetes-sigs/aws-load-balancer-controller#2844]
**Describe the bug**
We deploy 2 services with different NodePort's and after deploying the 2nd service, the first services Listener is deleted from the NLB.
They are 2 different UDP ports targeting different nodes.

**Steps to reproduce**
Create a service with UDP port 5000 on Node 1
Create a service with UDP port 5001 on Node 2
Apply both
Only 2nd service listener is added

**Expected outcome**
I should have 2 listeners pointing to different target groups

**Environment**

* AWS Load Balancer controller version 2.4.4
* Kubernetes version 1.23
* Using EKS (yes/no), if so version? Yes 1.23

**Additional Context**:
The target group is create for both, but the 2nd service removes the first services listener, leaving the target group hanging

**Comment by kishorj** [comment]
@DanielMcAssey, what does your service spec look like?

**Comment by DanielMcAssey** [comment]
Sure, here are both services:
`apiVersion: v1
kind: Service
metadata:
  namespace: scalable-cluster
  labels:
    service: service-0
  name: service-0
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "primary-nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-attributes: "deletion_protection.enabled=true,load_balancing.cross_zone.enabled=true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-XXXXXXXXXXXXXX,eipalloc-XXXXXXXXXXXX"
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - protocol: UDP
      port: 50000
      targetPort: 50000
      nodePort: 50000
  selector:
    k8s-app: pod-0
----------
apiVersion: v1
kind: Service
metadata:
  namespace: scalable-cluster
  labels:
    service: service-1
  name: service-1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "primary-nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-attributes: "deletion_protection.enabled=true,load_balancing.cross_zone.enabled=true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-XXXXXXXXXXXXXX,eipalloc-XXXXXXXXXXXX"
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - protocol: UDP
      port: 50001
      targetPort: 50001
      nodePort: 50001
  selector:
    k8s-app: pod-1
`

**Comment by M00nF1sh** [comment]
@DanielMcAssey 
You used the same NLB name for both service: 'primary-nlb'. Currently we don't support reuse the same NLB for two different service. 
You have to either a single Service with two port in service spec instead of two service or have two NLB.

We can improve our code to error out if we detects a NLB was used by two Services.

**Comment by DanielMcAssey** [comment]
Ah, any reason why? As AWS NLB supports this use case.
Is there scope to change it? Would you accept a PR?

**Comment by DanielMcAssey** [comment]
/reopen

Just want to address this again if possible, would a PR be accepted to change this behaviour? As AWS NLB supports this use case.

**Comment by DanielMcAssey** [comment]
Is this technically the same as #228 and #3247 ?

**Comment by shiyuhang0** [comment]
I think is the same as https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3247. 
I met the same issue as yours. Just wait for the new feature
