### ISSUE TITLE
Multiple ALB controllers

### ISSUE THREAD

**Issue by anoopmun** [kubernetes-sigs/aws-load-balancer-controller#2847]
Having issues when creating ingress.

Have two ALB controllers ss-dev-external and ss-dev-internal  in 2 different namespaces. When configuring ingress in the ss-dev-internal namespace, the following errors in noticed in the ALB controller logs.

{"level":"error","ts":1666470035.5002139,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"aws-alb-ingress-internal-int-dev-to-nginx-ingress","namespace":"ss-dev-internal","error":"Internal error occurred: failed calling webhook \"mtargetgroupbinding.elbv2.k8s.aws\": Post \"[https://aws-load-balancer-webhook-service.ss-dev-external.svc:443/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s](https://aws-load-balancer-webhook-service.ss-dev-external.svc/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding?timeout=10s)\": x509: certificate is valid for ss-dev-external-webhook-service.ss-dev-external, ss-dev-external-webhook-service.ss-dev-external.svc, ss-dev-external-webhook-service.ss-dev-external.svc.cluster.local, not aws-load-balancer-webhook-service.ss-dev-external.svc"}

The above error seems a bit odd, as the endpoint being used belongs to the initial one (ss-dev-external).. Also the endpoint aws-load-balancer-webhook-service.ss-dev-external.svc seems incorrect as well and it should have been ss-dev-external-webhook-service.ss-dev-external.svc.

Any thoughts on this issue.

**Comment by kishorj** [comment]
@anoopmun, we currently don't support deploying multiple installations of the aws load balancer controller in the same cluster. While it is possible to configure multiple deoloyments, you'd need to disable the webhooks and SG rule management on subsequent controllers. Please refer to #2185 for further details.
