### ISSUE TITLE
need function $request_time | $upstream_response_time in alb

### ISSUE THREAD

**Issue by bruceforlearn** [kubernetes-sigs/aws-load-balancer-controller#2850]
I'm frustrated when I want to check application latency from aws alb to pod

a easy nginx docker could do it very well,just like that:
log_format main | $request_time | $upstream_response_time |
log:
XXX.IP - - [25/Oct/2022:09:20:07 +0000] "POST /client/user/logout HTTP/2.0" 200 2 "-" "XXX/1.0.1 (com.luiz.XXX; build:25; iOS 14.7.1) Alamofire/5.6.2" "- "|0.011|0.012

this is a aws testing method,it works but not enough
```
curl -kso /dev/null https://XXX/client/user/XXX -w "==============\n\n
| dnslookup: %{time_namelookup}\n
| connect: %{time_connect}\n
| appconnect: %{time_appconnect}\n
| pretransfer: %{time_pretransfer}\n
| starttransfer: %{time_starttransfer}\n
| total: %{time_total}\n
| size: %{size_download}\n
| HTTPCode=%{http_code}\n\n"
==============
```

when production env happens  error, I need to check the log system to locate the problem quickly

**Comment by bruceforlearn** [comment]
ALB：
─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────┬────────┬────────
 time│ Concurrency│ success│ failed│   qps  │long time│short time│average│download bytes │per/bytes│ error code
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────┼────────┼────────
   1s│      0│      0│      0│    0.00│    0.00│    0.00│    0.00│        │        │
   2s│     22│     22│      0│  508.49│ 1986.85│ 1946.77│ 1966.60│      44│      21│200:22
   3s│    169│    169│      0│  436.41│ 2941.06│ 1946.77│ 2291.43│     338│     112│200:169
   4s│    269│    286│      0│  366.58│ 3999.82│ 1322.76│ 2727.94│     572│     142│200:286
   5s│    335│    414│      0│  349.27│ 4305.10│ 1322.76│ 2863.15│     828│     165│200:414
   6s│    430│    562│      0│  309.22│ 5954.13│ 1322.76│ 3233.99│   1,124│     187│200:562
   7s│    508│    775│      0│  290.85│ 6959.13│ 1322.76│ 3438.21│   1,550│     221│200:775
   8s│    518│    907│      0│  292.82│ 7867.07│ 1322.76│ 3415.10│   1,814│     226│200:907
   9s│    560│   1088│      0│  281.56│ 8336.01│ 1322.76│ 3551.67│   2,176│     241│200:1088
  10s│    567│   1270│      0│  285.19│ 9864.21│ 1322.76│ 3506.48│   2,540│     253│200:1270
  11s│    572│   1435│      0│  288.02│10930.35│ 1322.76│ 3471.93│   2,870│     260│200:1435
  12s│    574│   1580│      0│  291.07│11957.41│ 1322.76│ 3435.55│   3,160│     263│200:1580
  13s│    586│   1779│      0│  287.40│12871.95│ 1322.76│ 3479.43│   3,558│     273│200:1779
  14s│    609│   1920│      0│  278.99│13521.23│ 1322.76│ 3584.37│   3,840│     274│200:1920
  15s│    612│   2134│      0│  279.83│14508.07│ 1308.62│ 3573.63│   4,268│     284│200:2134
  16s│    612│   2255│      0│  278.87│14508.07│ 1308.62│ 3585.95│   4,510│     281│200:2255
  17s│    623│   2474│      0│  277.64│16653.94│ 1308.62│ 3601.82│   4,948│     291│200:2474
  18s│    632│   2667│      0│  274.42│17532.81│ 1308.62│ 3644.06│   5,334│     296│200:2667
  19s│    635│   2789│      0│  275.40│18744.96│ 1308.62│ 3631.11│   5,578│     293│200:2789
  20s│    653│   3011│      0│  268.30│19352.78│  822.83│ 3727.11│   6,022│     301│200:3011
  21s│    654│   3127│      0│  266.86│20414.17│  822.83│ 3747.34│   6,254│     297│200:3127
  22s│    655│   3333│      0│  268.08│21646.82│  822.83│ 3730.22│   6,666│     302│200:3333
  23s│    660│   3508│      0│  266.50│22663.96│  822.83│ 3752.41│   7,016│     305│200:3508
  24s│    660│   3659│      0│  266.34│22663.96│  822.83│ 3754.62│   7,318│     304│200:3659
  25s│    660│   3809│      0│  266.46│22663.96│  822.83│ 3752.93│   7,618│     304│200:3809
  26s│    662│   4013│      0│  265.68│25740.94│  822.83│ 3763.97│   8,026│     308│200:4013
  27s│    663│   4153│      0│  265.80│26558.07│  822.83│ 3762.26│   8,306│     307│200:4153
  28s│    664│   4338│      0│  264.05│27564.06│  822.83│ 3787.14│   8,676│     309│200:4338

**Comment by bruceforlearn** [comment]
direct http ip:port
─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────┬────────┬────────
time│ Concurrency│ success│ failed│ qps │long time│short time│average│download bytes │per/bytes│ error code
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────┼────────┼────────
   1s│     52│     52│      0│ 1594.06│  689.09│  517.38│  627.33│     104│     103│200:52
   2s│    502│    544│      0│  692.69│ 1983.89│  462.78│ 1443.66│   1,088│     543│200:544
   3s│    929│   1492│      0│  607.96│ 2997.57│  400.34│ 1644.84│   2,984│     994│200:1492
   4s│   1000│   2591│      0│  741.37│ 3097.05│  400.34│ 1348.85│   5,182│   1,295│200:2591
   5s│   1000│   3240│      0│  770.68│ 3097.05│  400.34│ 1297.56│   6,480│   1,295│200:3240
   6s│   1000│   3743│      0│  803.07│ 3097.05│  400.34│ 1245.22│   7,486│   1,247│200:3743
   7s│   1000│   4384│      0│  744.43│ 4047.51│  400.34│ 1343.31│   8,768│   1,252│200:4384
   8s│   1000│   5297│      0│  716.39│ 4097.93│  400.34│ 1395.88│  10,594│   1,324│200:5297
   9s│   1000│   6795│      0│  788.44│ 4097.93│  400.34│ 1268.33│  13,590│   1,509│200:6795
  10s│   1000│   7420│      0│  822.98│ 4097.93│  400.34│ 1215.10│  14,840│   1,483│200:7420
  11s│   1000│   7577│      0│  819.00│ 4097.93│  400.34│ 1221.00│  15,154│   1,377│200:7577
  12s│   1000│   7636│      0│  812.23│ 4097.93│  400.34│ 1231.19│  15,272│   1,272│200:7636
  13s│   1000│   7869│      0│  763.49│ 4834.55│  400.34│ 1309.77│  15,738│   1,210│200:7869
  14s│   1000│   8995│      0│  671.77│ 5364.75│  400.34│ 1488.61│  17,990│   1,284│200:8995
  15s│   1000│  10127│      0│  699.76│ 5364.75│  400.34│ 1429.06│  20,254│   1,350│200:10127
  16s│   1000│  10784│      0│  720.22│ 5364.75│  400.34│ 1388.46│  21,568│   1,347│200:10784
  17s│   1000│  11361│      0│  724.37│ 5364.75│  400.34│ 1380.51│  22,722│   1,336│200:11361
  18s│   1000│  11533│      0│  716.97│ 5364.75│  400.34│ 1394.76│  23,066│   1,281│200:11533
  19s│   1000│  12455│      0│  684.93│ 5364.75│  400.34│ 1460.01│  24,910│   1,311│200:12455
  20s│   1000│  13568│      0│  696.78│ 5364.75│  398.11│ 1435.17│  27,136│   1,356│200:13568
  21s│   1000│  14501│      0│  720.34│ 5364.75│  398.11│ 1388.23│  29,002│   1,381│200:14501
  22s│   1000│  14978│      0│  717.79│ 5364.75│  398.11│ 1393.17│  29,956│   1,361│200:14978
  23s│   1000│  15678│      0│  722.10│ 5364.75│  398.11│ 1384.86│  31,356│   1,363│200:15678
  24s│   1000│  15963│      0│  722.53│ 5364.75│  398.11│ 1384.03│  31,926│   1,330│200:15963
  25s│   1000│  16374│      0│  705.36│ 5364.75│  398.11│ 1417.71│  32,748│   1,309│200:16374
  26s│   1000│  16983│      0│  692.46│ 5364.75│  398.11│ 1444.13│  33,966│   1,306│200:16983
  27s│   1000│  17678│      0│  674.90│ 6639.01│  398.11│ 1481.71│  35,356│   1,309│200:17678
  28s│   1000│  18377│      0│  675.99│ 6639.01│  398.11│ 1479.31│  36,754│   1,312│200:18377
  29s│   1000│  19412│      0│  681.71│ 6639.01│  398.11│ 1466.90│  38,824│   1,338│200:19412
  30s│   1000│  19705│      0│  686.96│ 6639.01│  398.11│ 1455.68│  39,410│   1,313│200:19705
  31s│   1000│  20303│      0│  678.81│ 6639.01│  398.11│ 1473.16│  40,606│   1,309│200:20303
  32s│   1000│  21123│      0│  676.50│ 6639.01│  398.11│ 1478.20│  42,246│   1,320│200:21123
  33s│   1000│  21767│      0│  677.91│ 6639.01│  398.11│ 1475.11│  43,534│   1,319│200:21767
  34s│   1000│  22416│      0│  674.11│ 6639.01│  398.11│ 1483.43│  44,832│   1,318│200:22416
  35s│   1000│  23765│      0│  691.18│ 6639.01│  398.11│ 1446.81│  47,530│   1,357│200:23765
  36s│   1000│  23781│      0│  691.32│ 6639.01│  398.11│ 1446.52│  47,562│   1,321│200:23781

**Comment by M00nF1sh** [comment]
@bruceforlearn 
ALB have cloudwatch metrics such as TargetResponseTime to track the delay,  maybe you can check out: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html

Also, have you changed to use "ip" mode to minimize latency? the default "instance" mode have two traffic hop(i.e. the kube-proxy) for traffic from ALB to reach backend pod.

**Comment by bruceforlearn** [comment]
@M00nF1sh thank you 
1. cloudwatch is not free. I deploy a loki(a opensource log system) to collect my all logs. alb logs store in s3 with gz format and the log don't contain $request_time | $upstream_response_time function
2. so customer deploy log system couldn't collect alb latency information, this is a issue.
3. all my target type is ip mode, please look my photo.
4. I found alb latency question that is alb need warm up before high Concurrency.
![image](https://user-images.githubusercontent.com/29446582/198173197-a847546a-7faa-4ca2-9ce2-7b238512ea22.png)
