### ISSUE TITLE
Certificate RSA 4096 not accepted with autodiscovery

### ISSUE THREAD

**Issue by Adriks976** [kubernetes-sigs/aws-load-balancer-controller#2854]
**Is your feature request related to a problem?**

When I import a certificate in ACM (RSA_4096), Alb controller is not able to use it with autodiscovery. If I put the certificate arn in the annotations it is working. 
When I import a certificate in ACM (RSA_2048), Auto discovery is working. No need to add the annotation.
 

**Describe the solution you'd like**

My guess is that the request to aws is only for 2048 certificates. Without options default filtering returns only RSA_2048 certificates.
aws acm list-certificates :
-> only RSA_2048
aws acm list-certificates --include keyTypes=RSA_2048,RSA_4096
-> Both

**Describe alternatives you've considered**
Unless we change the api request on acm list-certificate we have to import only 2048 certs or to add annotations.

What do you think about that?

Thanks 

Adrik

**Comment by kishorj** [comment]
Issue #2719 to keep track of the fix.
I'm closing this one as a  duplicate.
