### ISSUE TITLE
Allow security group to be specified for the NLB health check and traffic ports

### ISSUE THREAD

**Issue by mattjamesaus** [kubernetes-sigs/aws-load-balancer-controller#2856]
**Is your feature request related to a problem?**
In heavily regulated environments using the generic worker node security group (SG) isn't always an option, this leaves the user to create specific SGs for each node group and remove the generic worker node security group. When creating an NLB however it appears that it's not possible to explicitly specify a SG to have the AWS LB Controller write the security group rules.

**Describe the solution you'd like**
When using `service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules : true` i'd like another annotation to be created, something like, `service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-id` that would allow me the cluster operator to provide a security group ID that would be modified by the controller vs the generic cluster worker security group, you could have it fall back to the default if the new annotation isn't provided.

**Describe alternatives you've considered**
Managing the SG completely out of band with `service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: false` but that's fairly brittle and detracts away from the convenience provided by having the controller manage the SG provided.

PS thanks for all the hard work on this project!

**Comment by M00nF1sh** [comment]
@mattjamesaus 
We expect one security group with the `kubernetes.io/cluster/cluster-name` tag. would it be possible for you to tag the security group desired with that tag only?
If not we might consider expose a cluster-level setting for the tagKey instead of this per Ingress override.

BTW, once NLB supports security group like ALB, would this request still matters?

**Comment by jibinrajck** [comment]
> **Is your feature request related to a problem?** In heavily regulated environments using the generic worker node security group (SG) isn't always an option, this leaves the user to create specific SGs for each node group and remove the generic worker node security group. When creating an NLB however it appears that it's not possible to explicitly specify a SG to have the AWS LB Controller write the security group rules.
> 
> **Describe the solution you'd like** When using `service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules : true` i'd like another annotation to be created, something like, `service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-id` that would allow me the cluster operator to provide a security group ID that would be modified by the controller vs the generic cluster worker security group, you could have it fall back to the default if the new annotation isn't provided.
> 
> **Describe alternatives you've considered** Managing the SG completely out of band with `service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: false` but that's fairly brittle and detracts away from the convenience provided by having the controller manage the SG provided.
> 
> PS thanks for all the hard work on this project!

+1
