### ISSUE TITLE
Does this support elb aka classic lb? 

### ISSUE THREAD

**Issue by Ashtonian** [kubernetes-sigs/aws-load-balancer-controller#2863]
Does this or did this support provisioning elbs for service types? I'm trying to figure out what is creating a classic elb in my cluster based on the service annotations and I have an older version of this controller running. The docs seem to indicate that it only supports the newer alb/nlb. If it did change - what version? 

nlb has a much smaller keep alive window compared to a elb.

**Comment by M00nF1sh** [comment]
@Ashtonian 
Hi, we only support NLB(Service) and ALB(Ingresses). Given NLB is preferred than ELB, we don't have plans to support ELB in this controller.

**Comment by kishorj** [comment]
@Ashtonian, closing the issue since we don't plan to support classic LB from this controller.

**Comment by kaykhan** [comment]
This controller at one point did support the creation of classic load balancers in version `1.4.8`.

The reason i bring this up is because im having trouble exposing a mongodb service via a classic load balancer
