### ISSUE TITLE
No Targets registered in Target Group

### ISSUE THREAD

**Issue by micmel5997** [kubernetes-sigs/aws-load-balancer-controller#2867]
So I have been working with the ALB controller in order to control ALB spend on our AWS EKS cluster. While I have a working application and listener for the default listener rule, I am unable to add a secondary listener successfully. Below is what I am using in my values file for an ingress in a new helm project. The Listener rule gets created, and a target group gets created, but there are no targets that get registered. What am I missing?

ingress:
  metadata:
    name: group-name
    annotationEnabled: enabled
    annotations:
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/certificate-arn: ###########
      alb.ingress.kubernetes.io/ssl-policy: ###########
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/healthcheck-port: '8080'
      alb.ingress.kubernetes.io/group.name: group-name
  spec:
    ingressClassName: alb
    rules:
    - host: app.name.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-name
              port:
                number: 8080

**Comment by kishorj** [comment]
@micmel5997, since the target-type is IP, could you verify whether the backend service app-name has ready endpoints? You can check for the Endpoint/Endpointslice resource corresponding to the app-name service. Do you see any errors in the controller logs?
