### ISSUE TITLE
Support Gateway Load Balancer

### ISSUE THREAD

**Issue by marcincuber** [kubernetes-sigs/aws-load-balancer-controller#2873]
**Describe the solution you'd like**
I would like to deploy Gateway Load Balancers using this controller from within EKS cluster. 
https://docs.aws.amazon.com/elasticloadbalancing/latest/gateway/introduction.html

As this controller is already responsible for deploying NLBs and ALBs, I believe adding support for GLBs is reasonable. 

**Describe alternatives you've considered**
Apigatewayv2 controller which deploys Api Gateway and redirects traffic to NLBs based on path.

**Comment by kishorj** [comment]
@marcincuber, could you provide further details on your use-case?
