### ISSUE TITLE
Vulnerabilities reported while scanning v2.4.1 image

### ISSUE THREAD

**Issue by Vamsi0473** [kubernetes-sigs/aws-load-balancer-controller#2874]
**Describe the bug**
While scanning the v2.4.1 docker image of alb ingress controller we see following vulnerabilities
controller (gobinary)
![image](https://user-images.githubusercontent.com/46375277/200612155-0d2ff3a7-cd35-4f0d-826d-e7d7033f4d73.png)

**Steps to reproduce**
Scan the image for vulnerabilities
**Expected outcome**
No vulnerabilities

**Environment**
non prod

* AWS Load Balancer controller version v2.4.1
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes

**Additional Context**:
I also tried v2.4.4 but seeing following vulnerabilities
![image](https://user-images.githubusercontent.com/46375277/200611865-47c4f95e-25ce-4f71-8180-7397659d2174.png)

Can someone please help me on how avoid this vulnerabilities
Thanks,
Vamsi

**Comment by kishorj** [comment]
@Vamsi0473, we are currently working on the v2.4.5 patch release to address the recent CVEs.
