### ISSUE TITLE
CertificateNotFound 

### ISSUE THREAD

**Issue by bearrito** [kubernetes-sigs/aws-load-balancer-controller#2875]
**Describe the bug**
```
{"level":"error","ts":1667948559.5220675,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"gw-ingress","namespace":"istio-system","error":"CertificateNotFound: Certificate 'arn:arn:aws:acm:us-west-2:XXXXXXX' not found\n\tstatus code: 400, request id: 070a47fa-d1ac-4734-9c5a-937535d410e0"}
```
**Steps to reproduce**
I created a wild-card cert in ACM *.domain.mycorp.com. The certificate is valid in ACM.
I'm using the chart found at https://github.com/aws-samples/eks-alb-istio-with-tls/tree/main/helm/ALB-Istio-TLS to create the ingress.

Created with
```
 helm install alb-istio-ingress ./helm/ALB-Istio-TLS \
> --set host=domain.mycorp.com \
> --set certificate_arn=arn:arn:aws:acm:XXXXX
```

The json found here https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.4/docs/install/iam_policy.json doesn't included, so I added the following permission

```
    "Effect": "Allow",
            "Action": [
                "acm:GetCertificate"
            ],
            "Resource": "arn:aws:acm:us-west-2:XXXXX"
        }

```

My only thought on the matter is the usage of  second sub-domain? eg x.domain.mycorp.com? Is this supported?

Edit: I updated to use only a single subdomain so something like `domain.mycorp.com` and still see the same result.

**Expected outcome**
Associating the cert with the ALB

**Environment**

* AWS Load Balancer controller version - Latest from `helm repo add eks https://aws.github.io/eks-charts
`
* Kubernetes version - 1.23
* Using EKS (yes/no), if so version? - Latest, created with `eksctl`

**Comment by kishorj** [comment]
@bearrito, your certificate arn `arn:arn:aws:acm:us-west-2:XXXXXXX` is not valid. It should have looked like `arn:aws:acm:us-west-2:XXXXXXX`

**Comment by kishorj** [comment]
@bearrito, I'm closing the issue. If problem persists, feel free to reach out to us.
