### ISSUE TITLE
Shall we expose informer factory to watch resource changes

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes-sigs/aws-load-balancer-controller#2884]
**Is your feature request related to a problem?**
I'm frustrated when I want to subscribe the targetgroupbinding resource change and do some customized stuff, like argo-rollout, it has [informer pkg](https://github.com/argoproj/argo-rollouts/tree/master/pkg/client/informers/externalversions) and works well, but for our repo, I can't find a way to use the informer since we're using kubebuilder.

**Describe the solution you'd like**
Shall we expose informer factory to watch resource changes, or do we have another suggested solution for solving this issue?

**Describe alternatives you've considered**
If we can't fix this within our repo, I might consider to make a private sharedInformer to subscribe targetgroupbinding resource changes.

**Comment by Colstuwjx** [comment]
How about use informer-gen to generate these client libs, just like argo-rollout project did.
/cc @M00nF1sh

**Comment by kishorj** [comment]
You should be able watch for the CRD changes via the controller runtime similar to what this controller does. You should also be able to do similar steps on your side - either import the CRD definition from this controller, or copy it over.

If you are not able to use the dynamic informer using the controlelr runtime, you can raise a PR for the changes, we will include it in our repo.
