### ISSUE TITLE
Deploying an AWS load balancer controller gives error events in ingress in me-central-1 only

### ISSUE THREAD

**Issue by julian-labuschagne** [kubernetes-sigs/aws-load-balancer-controller#2885]
**Describe the bug**
Deploying an AWS load balancer controller gives error events in ingress in me-central-1 only.

```
Events:
  Type     Reason             Age                   From     Message
  ----     ------             ----                  ----     -------
  Warning  FailedDeployModel  7m1s (x102 over 24h)  ingress  Failed deploy model due to RequestError: send request failed
caused by: Post "https://wafv2.me-central-1.amazonaws.com/": dial tcp: lookup wafv2.me-central-1.amazonaws.com on 172.20.0.10:53: no such host
```

**Steps to reproduce**

Create a new service role:

```
eksctl create iamserviceaccount \
  --cluster=Production \
  --namespace=kube-system \
  --name=aws-load-balancer-controller \
  --role-name "AmazonEKSLoadBalancerControllerRoleAE" \
  --attach-policy-arn=arn:aws:iam::035565423426:policy/AWSLoadBalancerControllerIAMPolicyUAE \
```

Install ALBC using helm:

```
helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=Production --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region=me-central-1 --set vpcId=vpc-00000000000000000 --set image.repository=759879836304.dkr.ecr.me-central-1.amazonaws.com/amazon/aws-load-balancer-controller 
```

I also tried with the following:

```

devops@Julians-MacBook-Pro uae % helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=Production --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region=me-central-1 --set vpcId=vpc-00000000000000000 --set image.repository=759879836304.dkr.ecr.me-central-1.amazonaws.com/amazon/aws-load-balancer-controller --set enableWaf=false --set enableWaf2=false --set enableShield=false
```

When creating ingress and looking at the events I keep getting this message:

```
Events:
  Type     Reason             Age                   From     Message
  ----     ------             ----                  ----     -------
  Warning  FailedDeployModel  7m1s (x102 over 24h)  ingress  Failed deploy model due to RequestError: send request failed
caused by: Post "https://wafv2.me-central-1.amazonaws.com/": dial tcp: lookup wafv2.me-central-1.amazonaws.com on 172.20.0.10:53: no such host
```

I noticed on the latest release 2.4.5 there does not seem to be an ECR image for me-central-1.

Could it be that this version is not yet supported?

**Expected outcome**

That the ingress creates a new loadbalancer which can be used for DNS.

**Environment**

* AWS Load Balancer controller version

* Kubernetes version

v1.22
* Using EKS (yes/no), if so version?

eks.8

**Additional Context**:

I noticed on the latest release 2.4.5 there does not seem to be an ECR image for me-central-1.

**Comment by kishorj** [comment]
@julian-labuschagne, WAFv2 is not available in the me-central-1 region yet. 
you can disable  wafv2 via controller command line flag. For example:
```
--enable-wafv2=false
```

You could also specify via helm values during chart install/upgrades as follows
```
--set enableWafv2=false 
```

**Comment by julian-labuschagne** [comment]
Hey @kishorj , Thanks for the response it is much appreciated.

I uninstalled the aws-load-balancer-controller helm chart: `helm -n kube-system uninstall aws-load-balancer-controller`

I then reinstalled the helm chart with the following flags: `--set enableWaf=false --set enableWaf2=false --set enableShield=false` like this:

```bash
helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=Production --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region=me-central-1 --set vpcId=vpc-00000000000000000 --set image.repository=759879836304.dkr.ecr.me-central-1.amazonaws.com/amazon/aws-load-balancer-controller --set enableWaf=false --set enableWaf2=false --set enableShield=false
```
I still get the following events when describing my ingress objects:

```
Events:
  Type     Reason             Age   From     Message
  ----     ------             ----  ----     -------
  Warning  FailedDeployModel  13s   ingress  Failed deploy model due to RequestError: send request failed
caused by: Post "https://wafv2.me-central-1.amazonaws.com/": dial tcp: lookup wafv2.me-central-1.amazonaws.com on 172.20.0.10:53: no such host
```

**Comment by kishorj** [comment]
The helm value to set is `enableWafv2=false`, you have `enableWaf2=false` - note there is a v in between Waf and 2. You can upgrade the chart without uninstall/reinstall with new value.

**Comment by julian-labuschagne** [comment]
Hi @kishorj Please note that I have used all three these switches. 

* `--set enableWaf=false` 
* `--set enableWaf2=false`
* `--set enableShield=false`

According to the docs you need to set those three switches to false to skip the WAF. 

I also tried each switch separately and in combination each time I get the same result with the same error. 

The WAF is also not enabled by annotation in my ingress so I am not sure why it's even trying to use the WAF atm.

**Comment by julian-labuschagne** [comment]
Thank you very much @kishorj  That was indeed the issue. You have quite an Eagle Eye! Your help was really appreciated!
