### ISSUE TITLE
Feature Request: Ingress Metrics like Request per Seconds

### ISSUE THREAD

**Issue by RamazanKara** [kubernetes-sigs/aws-load-balancer-controller#2886]
**Is your feature request related to a problem?**
We want to scale our applications based on metrics featured from the ingress - like nginx ingress controller is able to do.

**Describe the solution you'd like**

Provide Ingress Metrics for Scaling

**Describe alternatives you've considered**
Cloudwatch is not a good solution for this - as scaling with for example Keda based on Cloudwatch Metrics has to be applied after the ALB Controller deploys the ingress - to get the alb and target group metrics.

**Comment by kishorj** [comment]
/kind feature
Unlike nginx ingress controller, this controller doesn't get visibility into the created load balancer. It is possible for the controller to read the cloudwatch metrics and expose as prometheus metrices, however, there are potential performance issues. We will keep it in the backlog for the time being. It also possible to have a generic controller translate the cloudwatch metrics.

**Comment by RamazanKara** [comment]
Thank you for the answer. It would be awesome if this feature gets implemented to scale workloads based on request counts.
