### ISSUE TITLE
Controller times out when calling elasticloadbalancing.us-east-2.amazonaws.com

### ISSUE THREAD

**Issue by jacobpella** [kubernetes-sigs/aws-load-balancer-controller#2890]
The controller is unable to create an alb and I see the following timeout error:

```
{"level":"error","ts":1668782290.826262,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"graphql-router","namespace":"default",
"error":"RequestError: send request failed\ncaused by: Post \"https://elasticloadbalancing.us-east-2.amazonaws.com/\": dial tcp 10.33.4.169:443: i/o timeout"}
```

I exec'd into a container in the cluster and was able to verify outbound 443 works:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/106621459/202734451-24feb0bd-dea5-42a0-95b5-8e59a83ca9af.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/106621459/202737228-0128c079-59e0-443f-a9eb-268f6b52ebd0.png">

**Environment**

* AWS Load Balancer controller version: v2.4.3
* Kubernetes version: 1.22
* eks.6

**Comment by kishorj** [comment]
@jacobpella, do you have custom aws endpoints? If so, can you verify the route exists between your cluster and the custom endpoints?

**Comment by jacobpella** [comment]
Not that I am aware of.

**Comment by jacobpella** [comment]
I stand corrected.
![Screenshot 2022-11-18 at 9 50 37 AM](https://user-images.githubusercontent.com/106621459/202746678-b84a801a-121c-4224-a2e5-3ac12028b530.png)

I was attempting to setup apigateway -> vpclink -> privatealb. Deleting the endpoint I created allowed the lb to be created.

**Comment by jacobpella** [comment]
Thank you @kishorj I'll close as this is user error; not relating to the plugin.
