### ISSUE TITLE
LBC 2.4.5 fails the k/k Ingress Suite

### ISSUE THREAD

**Issue by johngmyers** [kubernetes-sigs/aws-load-balancer-controller#2891]
**Describe the bug**

Since upgrading from 2.4.3 to 2.4.5, LBC is consistently failing the k/k Ingress suite

**Steps to reproduce**

Look at https://testgrid.k8s.io/kops-misc#kops-aws-aws-load-balancer-controller

It started failing after kubernetes/kops#14540 merged.

**Expected outcome**

The k/k e2e tests should pass.

**Environment**

* AWS Load Balancer controller version 2.4.5
* Kubernetes version CI version of 1.26
* Using EKS (yes/no), if so version? no

**Additional Context**:

The "Ingress Suite.[It] test ingresses with multiple path and backends with podReadinessGate enabled standalone Ingress should behaves correctly" test appears to be consistently failing.

Key definitions of the test:

https://github.com/kubernetes/kops/blob/6311f1b60ca4b701adb3e794cc7268dcda8dd911/tests/e2e/scenarios/aws-lb-controller/run-test.sh

https://github.com/kubernetes/test-infra/blob/bfe654789fc3884faac4ca6052711a18bc89df0f/config/jobs/kubernetes/kops/kops-periodics-misc2.yaml#L1264-L1318

**Comment by kishorj** [comment]
I tried with kops 1.25.4, tests were successful. I will test with 1.26 next.

**Comment by kishorj** [comment]
@johngmyers 
I tried on a kops 1.26 cluster, all the tests passed on my account. I further reviewed the testgrid failures and it looks like the application deployment for the tests was never ready. The tests application uses the dockerhub image `chinmay5j/colorteller:latest` - is it possible the test account is unable to access the dockerhub image?

We can update the tests to use ECR public hosted image,  I can modify the e2e tests.

As for the kops e2e tests, troubleshooting would be easier if we can add the controller logs to the script tests/e2e/scenarios/aws-lb-controller/run-test.sh - thoughts?

**Comment by johngmyers** [comment]
@kishorj thank you for looking into this. I think this was figured out in kubernetes/kops#14845: that testing image isn't built for ARM64.

**Comment by kishorj** [comment]
@johngmyers, I've posted arm64 image for one of the test app. The service tests are currently failing, I will post the arm64 images for the test images.

**Comment by hakman** [comment]
@kishorj I think there's one more to be fixed: `kishorj/hello-multi:v1`.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/8409bd52953c21d0d3f0603a05300e9ee6e134a6/test/e2e/service/nlb_instance_target.go#L15

You may be able to use https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost or some other similar image from k/k if you want.

**Comment by kishorj** [comment]
> @kishorj I think there's one more to be fixed: `kishorj/hello-multi:v1`.
> 
Thanks. I've a PR out to update the test image.
