### ISSUE TITLE
NoCredentialProviders: no valid providers in chain. Deprecated

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#2893]
**Describe the bug**
A concise description of what the bug is.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: 2.4.5
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes. `eksctl 0.120.0`

**Additional Context**:

**Comment by kishorj** [comment]
@khteh, this error indicates the lb controller pod doesn't have proper IAM permissions configuration in place. You could do either of the following:
- setup IRSA (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), you can refer to the live docs for further steps, link: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#option-a-iam-roles-for-service-accounts-irsa
- If you attached the IAM permissions to your worker node, then you need to ensure the pods have access to IMDS. If you disabled IMDSv1, then you need to ensure the IMDSv2 hop limit is at least 2. This is insecure as compared to the IRSA.

**Comment by khteh** [comment]
I have followed through https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html but after applying and modifying the `sa` reference, I see different errors:
```
{"level":"error","ts":1669772545.5195894,"logger":"controller.ingress","msg":"Reconciler error","name":"ingress","namespace":"default","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: c39c1d33-40cc-447e-a039-bc462e7552e8"}
{"level":"error","ts":1669772566.005932,"logger":"controller.ingress","msg":"Reconciler error","name":"ingress","namespace":"default","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 84593330-3c9b-41be-b343-9c0935719668"}
{"level":"error","ts":1669772606.9763772,"logger":"controller.ingress","msg":"Reconciler error","name":"ingress","namespace":"default","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: c40b3275-550a-4db1-bb69-add5fce62c05"}
{"level":"error","ts":1669772689.024965,"logger":"controller.ingress","msg":"Reconciler error","name":"ingress","namespace":"default","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: e6f0848d-f3e9-4b15-845a-8ae74459aed0"}
```
The alb pods are using `regional` STS endpoints.

**Comment by khteh** [comment]
Resolved. I used the wrong `sa` name in the IAM Role trust relationship.

**Comment by khteh** [comment]
Spotted another error in the logs:
```
{"level":"error","ts":1669775216.0763822,"logger":"controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"k8s-default-svcpgadm-ff7003bedd","namespace":"default","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/mycluster for eni eni-<eniid>, got: [sg-<sgid1> sg-<sgid2>] (clusterName: mycluster)"}
```
