### ISSUE TITLE
`kubectl delete ingress` gets stuck

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#2894]
**Describe the bug**
A concise description of what the bug is.
```
$ kubectl delete ingress ingress
ingress.networking.k8s.io "ingress" deleted
```
Nothing is deleted. Neither the ingress resource nor the LB.
**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: 2.4.5
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes. `eksctl 0.120.0`

**Additional Context**:

**Comment by kishorj** [comment]
@khteh, the ingress resource gets deleted only after the lb controller is successful in cleaning up the underlying AWS LB resources. Do you see any errors in the controller logs?

**Comment by khteh** [comment]
```
{"level":"error","ts":1669276777.9842744,"logger":"controllers.ingress","msg":"unable to determine AWS Shield subscription state, skipping AWS shield reconciliation","error":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
{"level":"error","ts":1669276778.8389933,"logger":"controller.ingress","msg":"Reconciler error","name":"ingress","namespace":"default","error":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
```
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2893

**Comment by kishorj** [comment]
Closing since the it is due to the IAM permissions setup as mentioned in the linked issue.
