### ISSUE TITLE
sts.us-west-2.amazonaws.com net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by rajaie-sg** [kubernetes-sigs/aws-load-balancer-controller#2901]
**Describe the bug**

We are running aws-load-balancer-controller in our EKS cluster on nodes with public IPs in public subnets (access Internet through Internet Gateway).

The controller pod runs fine at startup and for an unspecified time interval afterwards, but at some random point, it starts failing with the following error

```
{"level":"error","ts":1669754500.125206,"logger":"controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"XXXXXXXXXXX","namespace":"XXXXXXXXXXX","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-west-2.amazonaws.com/\": net/http: TLS handshake timeout"}
```

The EKS cluster is running `v1.12.0-eksbuild.1` of the Amazon VPC CNI plugin.

**Steps to reproduce**

I am not able to reproduce the issue. It works fine for a while then randomly starts failing

**Expected outcome**
The LB controller does not throw any STS timeout errors. 

**Environment**

* AWS Load Balancer controller version
2022-11-29T18:16:55-05:00 {"level":"info","ts":1669763815.6117048,"msg":"version","GitVersion":"v2.4.5","GitCommit":"d9482de36bf51a17e7def869f677f35c2b6c6045","BuildDate":"2022-11-09T20:46:04+0000"}

* Kubernetes version
1.24
* Using EKS (yes/no), if so version?
Yes. eks.2

**Additional Context**:

- No VPC endpoints are configured for `sts`, so all communication with that endpoint should happen over the Internet
- lb-controller is using IRSA
- Deployed on nodes in a managed node group in EKS

**Comment by M00nF1sh** [comment]
@rajaie-sg 
I don't think it's controller issue but a generic EKS networking issue.
You'll need to cut a support ticket to EKS with cluster details and event time.
