### ISSUE TITLE
expect exactly one securityGroup tagged with kubernetes.io/cluster/mycluster for eni eni-<eniid>, got: [sg-<sgid1> sg-<sgid2>] (clusterName: mycluster)

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#2902]
**Describe the bug**
A concise description of what the bug is.
```
{"level":"error","ts":1669775216.0763822,"logger":"controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","name":"k8s-default-svcpgadm-ff7003bedd","namespace":"default","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/mycluster for eni eni-<eniid>, got: [sg-<sgid1> sg-<sgid2>] (clusterName: mycluster)"}
```
There are indeed 2 SGs: 
"[k8s] Shared Backend SecurityGroup for LoadBalancer" - 0 Permission entries (Inbound rules)

Tags:
elbv2.k8s.aws/resource | backend-sg
elbv2.k8s.aws/cluster | mycluster

Description: [k8s] Shared Backend SecurityGroup for LoadBalancer

"[k8s] Managed SecurityGroup for LoadBalancer". - 2 Permission entries (Inbound rules)

Tags:
ingress.k8s.aws/stack | default/ingress
elbv2.k8s.aws/cluster | mycluster
ingress.k8s.aws/resource | ManagedLBSecurityGroup

Description: [k8s] Managed SecurityGroup for LoadBalancer

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: 2.4.5
* Kubernetes version 1.24
* Using EKS (yes/no), if so version?yes. `eksctl 0.120.0`

**Additional Context**:

**Comment by kishorj** [comment]
@khteh, the SGs you mentioned in the description don't have the cluster tag `kubernetes.io/cluster/mycluster`, these are created automatically by the controller to attach to the ALB.

The error you mention is related to the Security group attached to your EC2 instance (or ENI). You'd need ingress rules on the instance (or ENI) SG to permit traffic from the ALB. In your case, the controller attempts to automatically add the ingress rules. However, your instance (or ENI) has multiple security groups with the cluster tag `kubernetes.io/cluster/mycluster` and is the source of the error. If you have multiple security groups, you need to make sure only one of them has the cluster tag.
