### ISSUE TITLE
[Question] NLB, loadBalancerSourceRanges and multiple services

### ISSUE THREAD

**Issue by joaogbcravo** [kubernetes-sigs/aws-load-balancer-controller#2904]
Using version v2.4.3

I have multiple services running on the same K8s cluster using NLBs.
Each of them has a similar configuration:
```
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-type: external
```
Some of them are listening on the same port.
Some of them have some CIDR specified on the `spec.loadBalancerSourceRanges`.

Lets say service A listens on 443 and has loadBalancerSourceRanges 100.100.100.100/32
Lets say service B listens on 443 and doesn't have any loadBalancerSourceRanges

This makes the security group have two entries for that port. The 0.0.0.0/0 is added by default from service B.
```
Port: Source
443: 0.0.0.0/0
444: 100.100.100.100/32
```

And with this configuration, I am able to access service A from everywhere, whereas I thought I would be able only to access it from 100.100.100.100/32.

So... am I doing something wrong? If so, can you please tell me what I missing?
...or this is the expected behaviour... and this "security hole" is documented somewhere and I missed it? What one should do in this scenario? use ALB? other option? 

Thank you

**Comment by kishorj** [comment]
At the moment, NLBs do not support security groups, so the only way to allow access is via CIDR rules on the instance/ENI security groups - for details please refer to the aws documentation https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html#target-security-groups. 

You either need to restrict spec.loadBalancerSourceRanges across all services, or disable client IP preservation in your case.
