### ISSUE TITLE
Readiness Probes instead of Readiness Gates and slow start

### ISSUE THREAD

**Issue by RamazanKara** [kubernetes-sigs/aws-load-balancer-controller#2905]
**Is your feature request related to a problem?**
We would like to use kubernetes internal readiness probes as a method for the ALB Ingress controller to route traffic to a Container and find the use of readiness gates and slow start very hard to finetune without getting 5xx errors on scaleup/down

**Describe the solution you'd like**
ALB Controller reads readiness probes, check if pod has healthy readiness probe and then only routes traffic to the specific pod.

**Describe alternatives you've considered**
The current alternative is to use readiness gates but that requires a worse process with configuring a horrible slow start delay.

**Comment by M00nF1sh** [comment]
@RamazanKara 
I didn't understand the proposed solution yet. The readinessProbes on pods is respected by Kubelet and reflected as Pod's ready condition and will decide whether pod will be "ready" in Endpoints or not, which is already read by ALB Controller. 
Why would ALB Controller needs to read these `readiness probes` directly?

Also, would you help elaborate more on the "slow start" issue you observed with readiness gate?

**Comment by gazal-k** [comment]
I wonder if the OP meant something like #1269
