### ISSUE TITLE
[Question] Load balancer controller cannot access oicd secret in application namespace

### ISSUE THREAD

**Issue by JM322** [kubernetes-sigs/aws-load-balancer-controller#2906]
As per documentation the aws-load-balancer-controller is installed in the `kube-system` namespace. For the configuration of `alb.ingress.kubernetes.io/auth-idp-oidc` I added the secret containing the ClientID and the ClientSecret to the ingress' namespace. But because the controller is deployed in a different namespace the rule creation fails with the following error:

`Failed build model due to ingress: <Ingress Namespace>/<App>-ingress: secrets "oicd-secret" is forbidden: User "system:serviceaccount:kube-system:aws-load-balancer-controller" cannot get resource "secrets" in API group "" in the namespace "<Ingress Namespace>"`

How do you enable the creation of oicd auth rules on the loadbalancer without reinstalling the aws-load-balancer-controller in every namespace where authentification is needed?

**Comment by kishorj** [comment]
@JM322, starting v2.4.1 release, controller doesn't have permissions to secret resources by default. You need to grant the RBAC permissions to the secrets, we have an example in the live docs- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/examples/secrets_access/. You could also allow access to all secrets by setting the helm value `clusterSecretsPermissions.allowAllSecrets=true` during chart installation, but we don't recommend this.

**Comment by JM322** [comment]
@kishorj Thank you very much, that solved my issue. Maybe a link in the documentation would be usefull.
