### ISSUE TITLE
Controller 2.4.5 Not Reconciling Changes to ACM Certificate

### ISSUE THREAD

**Issue by ndrafahl** [kubernetes-sigs/aws-load-balancer-controller#2915]
**Describe the bug**
We recently went through the migration from alb-ingress-controller v1.1.8 to aws-load-balancer-controller v2.4.5 following the [migration guide](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/upgrade/migrate_v1_v2/) I've noticed that the new controller is no longer reconciling the ACM certificate that is applied to one of the two listeners that are on the existing ALB that the previous controller was managing.

I have noticed though that if I do a `kubectl rollout restart` of the deployment for the controller (or simply kill one of the running controller pods) when the new pod comes up it builds the model and then will update the ACM certificate back to what the ALB is currently set to utilize via the `alb.ingress.kubernetes.io/certificate-arn` annotation.

Undoubtedly I'm missing something super obvious, but was just looking to see if I could find a place to start looking.

**Steps to reproduce**
- Go out to the 443 Listener on the ALB and manually update the ACM Certificate to a different ACM certificate than the one that is set via the `alb.ingress.kubernetes.io/certificate-arn` annotation on the Ingress.
- Wait
- The Controller does not appear to ever reconcile the ACM Certificate

**Expected outcome**
- Go out to the 443 Listener on the ALB and manually update the ACM Certificate to a different ACM certificate than the one that is set via the `alb.ingress.kubernetes.io/certificate-arn` annotation on the Ingress.
- Wait
- The Controller automatically notices the difference and reconciles back to the ACM Certificate set via the annotation (similar to what the previous alb-controller was doing).

**Environment**
- Using an ALB deployed out in AWS and our Kubernetes Cluster is running in EKS.  (Let me know if there's more info about environment needed).

* AWS Load Balancer controller version -> 2.4.5
* Kubernetes version -> 1.21
* Using EKS (yes/no), if so version? -> Yes, eks.11

Thank you!

**Comment by ndrafahl** [comment]
Just to add a bit of information, not sure if it's entirely helpful, but in the model from the logs from aws-load-balancer-controller the `AWS::ElasticLoadBalancingV2::LoadBalancer`'s name does not match the ALB that it is managing when I restart the controller pods (it's prefixed with `k8s-ingressn-ingressa-` where's the current ALB is prefixed with `f62a47bc-ingressnginx-ingr-`.

The `securityGroup` in that same spec though does match the Security Group ID that the controller is attaching to `f62a47bc-ingressnginx-ingr-`.

**Comment by kishorj** [comment]
@ndrafahl, if you make changes to the AWS resources out of band, the current controller doesn't reconcile them at the moment. The AWS resources get reconciled when the k8s resource gets created/updated or during controller startup.

There is already an existing issue #2800 to investigate and fix this.

**Comment by ndrafahl** [comment]
Hey @kishorj thanks for the confirmation, I thought I was missing something obvious as the previous controller we were upgrading from was doing it, but good to know it's something that'll be added in the future.

I'll close this one out since the other issue covers this.

Thanks much!
