### ISSUE TITLE
Classic load balancer getting created from service even though loadBalancerClass specified

### ISSUE THREAD

**Issue by trevor-carlson1** [kubernetes-sigs/aws-load-balancer-controller#2916]
**Describe the bug**
When trying to create a simple NLB from a Service object, a classic load balancer is created even though I have `spec.loadBalancerClass` set to `service.k8s.aws/nlb` with the following annotations:
```
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
service.beta.kubernetes.io/aws-load-balancer-scheme: internal
```

**Steps to reproduce**

**Expected outcome**
I would expect an NLB to be created, not a classic load balancer

**Environment**

* AWS Load Balancer controller version: 2.4.5
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes, eks.11

**Additional Context**:

**Comment by kishorj** [comment]
@trevor-carlson1, you'd need EKS 1.22 or later for the load balancer class support.

**Comment by trevor-carlson1** [comment]
Wow, this went over my head. Thanks for the reply
