### ISSUE TITLE
Failed to delete securityGroup: InvalidGroup.NotFound: The security group does not exist. 

### ISSUE THREAD

**Issue by iamrohit07** [kubernetes-sigs/aws-load-balancer-controller#2918]
Hello,
 
We are trying to delete the ingress resource and recreate it. While deleting ingress resource we got below logs in alb ingress controller.

{"level":"error","ts":1670579986.8052735,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"ingress","namespace":"default","error":"failed to delete securityGroup: timed out waiting for the condition"}

While inspecting we found that there are ENI's attached to so I removed ENI manually and deleted SG manually. 

Then tried to recreate the SG and now facing below error.

{"level":"error","ts":1670590481.5220387,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"ingress","namespace":"default","error":"failed to delete securityGroup: InvalidGroup.NotFound: The security group 'sg-xxxxxxxx' does not exist\n\tstatus code: 400, request id: 12134"}

Can anyone help to remove the ingress so that we can re create it.

Thanks.

**Comment by kishorj** [comment]
@iamrohit07, did you delete the security group created by the controller for the ALB? What is the current state of the ALB provisioned for your ingress?

**Comment by kishorj** [comment]
@iamrohit07, I'm closing the issue. If problem persists, feel free to reach out to us.
