### ISSUE TITLE
Support for multiple namespaces for watchNamespace argument

### ISSUE THREAD

**Issue by herrbpl** [kubernetes-sigs/aws-load-balancer-controller#2923]
**Is your feature request related to a problem?**
Currently it is possible only to specify single namespace to watch. Or leave value unspecified to watch all namespaces. But sometimes more flexibility is needed. Like watching 2 or three namespaces but not all.

**Describe the solution you'd like**
Change watchNamespace option to stringList and watch multiple namespaces with single instance

**Describe alternatives you've considered**
I considered adding multiple instances running with different configuration but this is no go because this adds requirement to create multiple LB-s instead of having one.

**Comment by kishorj** [comment]
@herrbpl, the watchNamespace feature is provided by controller-runtime and currently it doesn't support multiple namespaces. What is your use-case for multiple namespaces?

**Comment by herrbpl** [comment]
Hi. For example we have case where we don't want users to give direct access to create AWS objects via service or ingress objects, we actually use NGINX ingress controller behind ALB (created/configured via AWS LB Controller) but for system apps we might need to create AWS objects from more than one namespace (ie,  ALB for NINGX ingress, another ALB for ArgoCD etc). So there are lot of cases where you want to limit list of watched namespaces but not to single namespace only.

I understand if this introduces some additional work however, it should be pretty standard stuff to watch multiple namespaces instead of all/single. Hope you can take it into works.

**Comment by kishorj** [comment]
@herrbpl, in v2.5.0 release, we plan to support running multiple controller deployments in the cluster - this will allow you to have a specific controller watch a particular namespace. Feature #2185.
