### ISSUE TITLE
Hanging, with no error message

### ISSUE THREAD

**Issue by davidhao3300** [kubernetes-sigs/aws-load-balancer-controller#2929]
[**Describe](### url) the bug**

We applied the helm chart on v2.4.4, but the webhook as no endpoints registered. 

**Steps to reproduce**

Just applied the helm chart, no modifications made

**Expected outcome**

Webhook service should have endpoints and allow the creation of ingresses

**Environment**

* AWS Load Balancer controller version v2.4.4
* Using EKS (yes/no), if so version? Yes, 1.23.13

**Additional Context**:

We took a stackdump, and the one that looked suspicious to me is 
```
goroutine 394 [select]:
k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc0008aa000, {0x0?, 0x0?, 0x7f76eb4eefc0?}, {0x7f76ea3aa518?, 0xc00100c240}, 0xc000487bf8, 0xc000821140, 0xc000b14900)
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:463 +0x1b0
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0008aa000, 0xc000b14900)
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:427 +0x691
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:221 +0x26
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00036f4c0?, {0x7f76ea39ca08, 0xc000550730}, 0x1, 0xc000b14900)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0008aa000, 0xc000b14900)
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:220 +0x211
sigs.k8s.io/aws-load-balancer-controller/pkg/k8s.(*defaultPodInfoRepo).Start(0xc000696be0, {0x7f76ea3b83c0?, 0xc0006bfa40?})
	/workspace/pkg/k8s/pod_info_repo.go:90 +0x45
main.main.func1()
	/workspace/main.go:161 +0x6f
created by main.main
	/workspace/main.go:159 +0x20e5
```

Looks like we're looping until we run some k8s command. I'd like some advice on how to log what the issue is

Full logs + golang stackdump created with QUIT attached as a file since they're too long
[aws_load_balancer_logs.txt](https://github.com/kubernetes-sigs/aws-load-balancer-controller/files/10230578/aws_load_balancer_logs.txt)

**Comment by kishorj** [comment]
@davidhao3300,
do you see webhook errors when you try to create ingress resources? Do you have ingress/service resources the controller is not reconciling? Could you also check if the controller pods pass the liveness readiness checks?

**Comment by davidhao3300** [comment]
Yup, webhook errors due to no endpoints in the webhook service being available, so unable to apply the ingress YAML.
Pod passes liveness and readiness checks, no crash-looping/restarts

**Comment by kishorj** [comment]
The no endpoints available usually happens when the controller pods are not ready. Can you describe the controller pods to see if there are any events? Also check if the controller pods got restarted.

It could be possible the pods are not able to access the IMDS in case you have IMDSv2 with hop limit of 1 configured. In this case, you will either have to set the region and the vpc id via controller flags, or increase the hop limit.
