### ISSUE TITLE
Controller silently ignores SSL ports that it isn't actually listening on

### ISSUE THREAD

**Issue by siggimoo** [kubernetes-sigs/aws-load-balancer-controller#2931]
**Describe the bug**
When setting the `service.beta.kubernetes.io/aws-load-balancer-ssl-port` annotation, any ports listed that a load balancer isn't actually listening on are quietly ignored. This can result in connections going unsecured without anyone knowing.

**Steps to reproduce**
1. Deploy a service with a particular listening port.
2. Include in that service the annotation `service.beta.kubernetes.io/aws-load-balancer-ssl-port` set to any value other than the above listening port.

**Expected outcome**
The load balancer should ideally fail to deploy and should report an error indicating that it cannot apply an SSL certificate to a port it isn't listening on.

**Environment**
* AWS Load Balancer controller version 2.4.4
* Kubernetes version 1.2.2
* Using EKS (yes/no), if so version? Yes, version 9

**Comment by kishorj** [comment]
@siggimoo, the purpose of the `service.beta.kubernetes.io/aws-load-balancer-ssl-port` annotation is to allow users to create both TLS and non-TLS listeners on the same NLB. If you want all listeners to be TLS, then you can omit this annotation. For TLS listeners, you'd still need to specify TLS certificates.

**Comment by siggimoo** [comment]
That's not my issue. As I understand the purpose of this annotation (which your explanation supports), the values listed are supposed to be a subset of the listeners. Put another way, any value listed in the annotation should also be found in the set of listeners. The problem I'm reporting arises when the above condition is not true -- when the annotation lists a value that is _not_ in the set of listeners.

For example:
* listeners = 8080
* aws-load-balancer-ssl-cert = ... ARN of some certificate ...
* aws-load-balancer-ssl-port = 443

In this scenario, it's requested that a certificate be attached to something that doesn't exist (a listener on port 443). The result is a load balancer with no certificate attached and no error to indicate that's the case. Unless there's some use-case I'm not understanding, I see no purpose in just silently ignoring this. It's most likely the result of a misconfiguration (which is how I found it), and given the security implications I think most people would want to know when it occurs.

**Comment by M00nF1sh** [comment]
@siggimoo 
we can add more validations for this.  However we'll need to do this in a new minor version as doing this change might break existing working services.

/kind feature

**Comment by Sajiyah-Salat** [comment]
I am a beginner and I would like to make change in this. I understand the issue but dont know what to change and where? It would helpful if you give me some detail about that.
