### ISSUE TITLE
aws-load-balancer-controller doesn't merge Ingress rules for ingresses within same IngressGroup

### ISSUE THREAD

**Issue by mattpopa** [kubernetes-sigs/aws-load-balancer-controller#2932]
**Describe the bug**
 The controller will automatically merge Ingress rules for all Ingresses within IngressGroup and support them with a single ALB. In addition, most annotations defined on an Ingress only apply to the paths defined by that Ingress.

**Steps to reproduce**
1. Deploying a helm chart (deployment1) with ingress rules and `alb.ingress.kubernetes.io/group.name: mygroup` creates an ALB w/ rules as expected
2. Deploy a second helm chart (deployment2) with extra ingress rules and `alb.ingress.kubernetes.io/group.name: mygroup`

**Expected outcome**
The controller will automatically merge Ingress rules for all Ingresses within IngressGroup and support them with a single ALB. In addition, most annotations defined on an Ingress only apply to the paths defined by that Ingress.

**Reality**
Only the ingress rules from deployment1 are applied on the ALB, and deployment2 rules are only showing up on the ingress definition but are not being applied on the ALB.

There are no error logs, and the last log line is
```
{"level":"info","ts":1671147709.6357698,"logger":"controllers.ingress","msg":"successfully deployed model","ingressGroup":"mygroup"}
```

**Environment**

* AWS Load Balancer controller version: 2.4.5
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes, 1.21

**Comment by kishorj** [comment]
@mattpopa, could you verify if the backend service for deployment2 exists in the namespace?

**Comment by mattpopa** [comment]
the service exists, endpoint is valid, except targetGroup hasn't been created 😞 

the CRDs are in place, they have access and they do create ALBs and targetGroups when I don't use `group.name`

**Comment by kishorj** [comment]
do you have the model from the controller logs?

**Comment by mattpopa** [comment]
Yes, it was ignoring the new targetgroup, and just mentioned the old one. No errors, only Info level logs.

My scenario is to get an internal ALB next to my existing public (internet-facing) ALB, using terraform+helm to deploy an app. There are 2 ingresses, one for the internal facing which will only have private IPs and be used for inter VPC comms, and the other for public facing traffic, and each should have their own target group (individual deployments). I cannot filter for the existing target group to automate tg assignment for the internal alb, and individual deployments for internal and public should work fine.

When a 2nd ingress is deployed using the public group, then no target group is created and no routes are being merged. No errors are issued, just info logs confirming success for the initial ingress + tg.

If it cannot create the tg I would expect an error level log.

**Comment by magzim21** [comment]
@mattpopa How did you solve this?
I am experiencing the same issue
