### ISSUE TITLE
TLS Secret - Auto Rotate 2.0.0

### ISSUE THREAD

**Issue by ramachittala** [kubernetes-sigs/aws-load-balancer-controller#2936]
**Describe the bug**
We are running load balancer controller (2.0.0) in EKS

**Steps to reproduce**
kubectl get secters -n <aws-load-balancer-controller-ns>

**Expected outcome**
No errors should return.

2022/12/05 12:33:05 http: TLS handshake error from 1.2.3.4:51800: remote error: tls: bad certificate
2022/12/05 12:33:05 http: TLS handshake error from 2.3.4.5:51804: remote error: tls: bad certificate
2022/12/05 12:33:05 http: TLS handshake error from 5.6.7.8:51814: remote error: tls: bad certificate

**Environment**

* AWS Load Balancer controller version 2.0.0
* Kubernetes version v1.21.14-eks-fb459a0
* Using EKS (yes/no), if so version? Yes 

**Additional Context**:
We have deleted tls secret and then issue is fixed. Can you please help us understand this will fixed 2.4.2 version. or We have to delete the tls secret whenever it is expired.

$ openssl x509 -enddate -noout -in cert.pem
notAfter=Mar  6 16:06:38 2023 GMT

**Comment by nipr-jdoenges** [comment]
This sounds like the same issue as #2927

**Comment by ramachittala** [comment]
@nipr-jdoenges @kishorj  We integrated with Cert manager. As of no auto renewal haven't been configured on certificate. 
Will that help to fix our problem.
https://cert-manager.io/docs/usage/certificate/

**Comment by kishorj** [comment]
@ramachittala, cert manager should automatically renew the certificates. Please troubleshoot the cert-manager component to figure out why the certificate did not get renewed.

**Comment by kishorj** [comment]
@ramachittala, I'm closing this issue. If you have further concerns regarding this matter, feel free to reach out to us.
