### ISSUE TITLE
Allow disabling ALB/Ingress management completely (and NLB management)

### ISSUE THREAD

**Issue by robinkb** [kubernetes-sigs/aws-load-balancer-controller#2939]
**Is your feature request related to a problem?**

We deployed the aws-load-balancer-controller in our organization in order to create Network Load Balancers in our EKS clusters. Mainly because we had trouble with the deprecated Classic Elastic Load Balancer provisioning with the in-tree Kubernetes controller. However, we already use the NGINX Ingress Controller to control our Ingress resources, and do not want this functionality from aws-load-balancer-controller.

Unfortunately, it is impossible to do this in the current Helm chart implementation. I can disable some functionality related to Ingresses, but it's impossible to disable the ValidatingWebhook. Because aws-load-balancer-controller deploys a ValidatingWebhook for a component that it doesn't even manage, it's interrupting our flow and I had to fork the chart.

**Describe the solution you'd like**

I would like a simple toggle (or a number of toggles) in the Helm chart that allows me to disable Ingress/ALB Management completely, including extra resources like the ValidatingWebhook.

**Describe alternatives you've considered**

I forked the chart and added a toggle to disable the ValidatingWebhook, but I don't want to maintain a fork.

**Extra notes**

I'm willing to put in some time to implement the changes in the Helm chart, if necessary. But I need a design first.

**Comment by kishorj** [comment]
@robinkb, we already have a feature request #2801 for this issue. We plan to provide a helm template value to disable ingress validation webhook.

**Comment by kishorj** [comment]
I wasn't able to get much about "NLB management" from the issue details, could you explain further?

**Comment by robinkb** [comment]
Ah, my apologies, I looked for existing issues but didn't find that one. Disabling management of Load Balancer Services (by fulfilling them with Network Load Balancers) is not something that I personally want, but maybe that's something that someone else would require. The AWS Load Balancer Controller currently does two very different things, and as a user, it makes sense to me that either of those things can be disabled.

But I have no personal requirement for that, so this issue can be closed in favor of #2801. Though I would love an easier way to disable Ingress management completely by just toggling one boolean, instead of digging through all the configuration options and guessing which ones I should disable.

**Comment by kishorj** [comment]
@robinkb, the management of NLB can be disabled via the feature gate `EnableServiceController` - please refer to the [live doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/configurations/#feature-gates) for further details. I'm closing this issue.

**Comment by nuno-silva** [comment]
#2801 seems to be taking care of the disabling the webhook for ingresses.

However, this issue is about being able to disable the ingress/ALB part of the controller completely, not (just) the webhook.

This is currently possible for Service/NLB via the `EnableServiceController` feature gate, but not for Ingress/ALB. A new `EnableIngressController` feature gate would solve this.

A workaround for this is to use an ingress class that does not exist, such as `--ingress-class=this-class-does-not-exist-on-purpose`.

As mentioned in #3011 by many people, perhaps this issue should be re-open as the scope for #2801 does not cover this issue.

**Comment by xer0devit** [comment]
Business case for requesting AWS to release a formal feature which allows their stakeholders to disable Ingress management completely (incl. validation) within AWS Load Balancer Controller by means of a customer friendly configuration handle (for example user-supplied helm-chart value):

- Operationalize out-tree AWS Load Balancer Controller as recommended by AWS with the goal to benefit from formal support and new features, for purpose of only managing service resource (NLB, TG). A seperate Ingress Controller product is used to control our Ingress resources (TLS termination, path rewrite,...etc).
- Depending on a plethora of workarounds tends to question the operational, production readiness of a product as proclaimed new default. What guarantees those workarounds even keep working as newer versions of the get released ?
