### ISSUE TITLE
ALB is deleted when deletion_protection is true

### ISSUE THREAD

**Issue by yasinlachiny** [kubernetes-sigs/aws-load-balancer-controller#2940]
**Describe the bug**
deletion_protection is on in our infra and I can see it in AWS console. But still, I can remove it at a certain condition

**Steps to reproduce**
Enable deletion_protection
Change `scheme` from `internal` to `internet_facing` from ingress in EKS
it will delete ALB and recreate it

**Expected outcome**
A concise description of what you expected to happen.
I expected to see some log that it can't change the scheme because deletion_protection is enabled
**Environment**
* AWS Load Balancer controller version:
 v2.4.4
* Kubernetes version
1.22.12
* Using EKS (yes/no), if so version?
yes, 1.22.12
**Additional Context**:
Is it a bug? Because when I enabled the `deletion_protection` I don't want to be deleted at any circumstances.

**Comment by balajisa09** [comment]
If the deletion protection is enabled from console and not as an annotation , the controller will delete the load balancer.
refer : https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/annotations.md for deletion_protection annotation.

**Comment by kishorj** [comment]
@balajisa09 is correct, this is the expected behavior if deletion protection is not specified in the annotation.

Live doc link - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#load-balancer-attributes

**Comment by yasinlachiny** [comment]
Thank you for your response. @kishorj  @balajisa09 

The problem is that I enabled it via annotations in ingress. I just checked the AWS console to be sure that it's enabled.
I created a merge request based on my issue. Could you please check it?
I tested it in my env and it's working fine
