### ISSUE TITLE
Managing nodegroups with several Security Groups

### ISSUE THREAD

**Issue by chary1112004** [kubernetes-sigs/aws-load-balancer-controller#2948]
**Describe the bug**
We have issue:

- 1 security group is created during created eks
- 1 security group is created during cluster-autoscaler

Error log:
expect exactly one securityGroup tagged with kubernetes.io/cluster/<cluster name> for eni eni-00ecd1b506ce989a0, got: [sg-0115455eb691defca sg-0726def54ced4f7cb] (clusterName: <cluster name>)

With this error then ingress use this ALB return error 503

**Steps to reproduce**
- Setup EKS
- Install cluster-autoscaler

**Expected outcome**
Ingress use ALB should work.

**Environment**

* AWS Load Balancer controller version: v2.4.4
* Kubernetes version: 1.22
* Using EKS (yes/no), if so version: yes - version: 1.22

**Additional Context**:
- When we remove tag in kubernetes.io/cluster/{cluster name} in first security group (1 security group is created during created eks) then after a while eks is automatically added it back. Refer to https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
For security group is created by cluster-autoscaler then it is out of control.

Any solution to resolve this issue would be very much appreciated.

Thank you!

**Comment by M00nF1sh** [comment]
@chary1112004 
Currently we only allow one security group with such tag as that's how we identify security groups to modify to allow inbound rules.
we have a pending feature request to tolerate it: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2367

**Comment by chary1112004** [comment]
@M00nF1sh thank you for your information then I will subscribe to that feature request.

**Comment by kishorj** [comment]
closing the issue since we already have 2367 to keep track.
