### ISSUE TITLE
Add annotations about security-groups, but i did not work

### ISSUE THREAD

**Issue by 501658362** [kubernetes-sigs/aws-load-balancer-controller#2958]
**Describe the bug**
Add  annotations (alb.ingress.kubernetes.io/security-groups: internal_gateway_sg) to ingress, but i got an error.
Error log:  
 ```{"level":"error","ts":1672986498.692221,"logger":"controller.ingress","msg":"Reconciler error","name":"app-gateway-test2","namespace":"default","error":"couldn't find all securityGroups, nameOrIDs: [internal_gateway_sg], found: []"}```

**Steps to reproduce**
1. init resoures by terraform
```
resource "aws_iam_role_policy_attachment" "attach-AWSLoadBalancerControllerIAMPolicy" {
  role = aws_iam_role.AmazonEKSLoadBalancerControllerRole.name
  policy_arn = aws_iam_policy.AWSLoadBalancerControllerIAMPolicy.arn
}

resource "aws_iam_policy" "AWSLoadBalancerControllerIAMPolicy" {
  name = "${var.eks_cluster_name}_AWSLoadBalancerControllerIAMPolicy"
  policy = templatefile("${path.module}/yaml/iam_policy.json", {})
}


resource "aws_iam_role" "AmazonEKSLoadBalancerControllerRole" {
  name = "${var.eks_cluster_name}_AmazonEKSLoadBalancerControllerRole"
  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Federated" : "arn:aws:iam::${var.account_id}:oidc-provider/${module.eks.oidc_provider}"
        },
        "Action" : "sts:AssumeRoleWithWebIdentity",
        "Condition" : {
          "StringEquals" : {
            "${module.eks.oidc_provider}:sub" : "system:serviceaccount:kube-system:aws-load-balancer-controller",
            "${module.eks.oidc_provider}:aud" : "sts.amazonaws.com"

          }
        }
      }
    ]
  })
  tags = {
    eks-role = "eks-role"
    cluster = var.eks_cluster_name
  }
}


resource "kubernetes_service_account" "alb-service-account" {
  metadata {
    name = "aws-load-balancer-controller"
    namespace = "kube-system"
    labels = {
      "app.kubernetes.io/name" = "aws-load-balancer-controller"
      "app.kubernetes.io/component" = "controller"
    }
    annotations = {
      "eks.amazonaws.com/role-arn" = aws_iam_role.AmazonEKSLoadBalancerControllerRole.arn
      "eks.amazonaws.com/sts-regional-endpoints" = "true"
    }
  }
  depends_on = [
  ]
}

resource "helm_release" "lb" {
  name = "aws-load-balancer-controller"
  repository = "https://aws.github.io/eks-charts"
  chart = "aws-load-balancer-controller"
  namespace = "kube-system"
  depends_on = [
    kubernetes_service_account.alb-service-account
  ]

  set {
    name = "region"
    value = var.region_code
  }

  set {
    name = "vpcId"
    value = module.vpc.vpc_id
  }

  set {
    name = "serviceAccount.create"
    value = "false"
  }

  set {
    name = "serviceAccount.name"
    value = "aws-load-balancer-controller"
  }

  set {
    name = "clusterName"
    value = var.eks_cluster_name
  }
}
```
2.  create an ingress
```---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-gateway-test2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: internal_gateway_sg
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-gateway
                port:
                  number: 80
```
3. And i got an error    
 ```{"level":"error","ts":1672986498.692221,"logger":"controller.ingress","msg":"Reconciler error","name":"app-gateway-test2","namespace":"default","error":"couldn't find all securityGroups, nameOrIDs: [internal_gateway_sg], found: []"}```

**Expected outcome**
My security group should auto attach to alb

**Environment**

* AWS Load Balancer controller version
 2.4.5
* Kubernetes version
1.22
* Using EKS (yes/no), if so version?
yes 1.22
**Additional Context**:
Please take a look, It bothers me.  I had check iam perimission, even add admin permission for alb controller, But it did not work

**Comment by kishorj** [comment]
@501658362, the security group name has to match the `Name` tag on your security group, not the `GroupName` attribute. Please refer to the live docs http://127.0.0.1:8000/guide/ingress/annotations/#security-groups for further details. In addition, the SG must also be from the same VPC as the controller.

**Comment by 501658362** [comment]
> @501658362, the security group name has to match the `Name` tag on your security group, not the `GroupName` attribute. Please refer to the live docs http://127.0.0.1:8000/guide/ingress/annotations/#security-groups for further details. In addition, the SG must also be from the same VPC as the controller.

I add Name tag to security group, it work, thank you very much for your kind reply!
