### ISSUE TITLE
ALB controller eks requst sts timeout

### ISSUE THREAD

**Issue by Moneshs** [kubernetes-sigs/aws-load-balancer-controller#2964]
**Describe the bug**
ALB controller is running but while creating the ingress its not creating the alb in aws

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version = 2.4.4
* Kubernetes version=1.2.4
* Using EKS (yes/no), if so version? yes,

* Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:40:13Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-eks-ffeb93d", GitCommit:"abb98ec0631dfe573ec5eae40dc48fd8f2017424", GitTreeState:"clean", BuildDate:"2022-11-29T18:45:03Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

**Additional Context**:

 kubectl get pods -n kube-system |grep aws-load
aws-load-balancer-controller-77cbbd5874-lhwq2   1/1     Running   0          35m

LOGS:
{"level":"info","ts":1673251949.2110667,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting workers","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","worker count":3}
{"level":"info","ts":1673251949.2111063,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting workers","worker count":3}
{"level":"error","ts":1673252938.2675526,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"engagedly-production","namespace":"","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-east-1.amazonaws.com/\": dial tcp 10.0.1.5:443: i/o timeout"}
{"level":"error","ts":1673253311.9323003,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"engagedly-production","namespace":"","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-east-1.amazonaws.com/\": dial tcp 10.0.1.5:443: i/o timeout"}
{"level":"error","ts":1673253682.7682083,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"engagedly-production","namespace":"","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-east-1.amazonaws.com/\": dial tcp 10.0.1.5:443: i/o timeout"}

Service account:

Name:                aws-load-balancer-controller
Namespace:           kube-system
Labels:              app.kubernetes.io/name=aws-load-balancer-controller
Annotations:         eks.amazonaws.com/role-arn: aws:iam::<account-id>:role/aws-load-balancer-controller
                     eks.amazonaws.com/sts-regional-endpoints: true
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>

Describe ALB PODS:
Name:                 aws-load-balancer-controller-77cbbd5874-lhwq2
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 
Start Time:           Mon, 09 Jan 2023 08:12:08 +0000
Labels:               app.kubernetes.io/component=controller
                      app.kubernetes.io/name=aws-load-balancer-controller
                      pod-template-hash=77cbbd5874
Annotations:          kubernetes.io/psp: eks.privileged
Status:               Running
IP:                  
IPs:
  IP:          
Controlled By:  ReplicaSet/aws-load-balancer-controller-77cbbd5874
Containers:
  controller:
    Container ID:  containerd://467c54a12a70f27f88a1fe5f8c5841c2a4c868e66dbb78a1b0adabcc015ac21c
    Image:         amazon/aws-alb-ingress-controller:v2.4.4
    Image ID:      docker.io/amazon/aws-alb-ingress-controller@sha256:29b6f9f936cf96c326d1a8a2ef88086962b63d30c691fb22c791d47382bf796e
    Port:          9443/TCP
    Host Port:     0/TCP
    Args:
      --cluster-name=
      --ingress-class=alb
      --aws-vpc-id=
      --aws-region=
    State:          Running
      Started:      Mon, 09 Jan 2023 08:12:09 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  500Mi
    Requests:
      cpu:     100m
      memory:  200Mi
    Liveness:  http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Environment:
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           us-east-1
      AWS_REGION:                   us-east-1
      AWS_ROLE_ARN:                 aws:iam::<account-id>:role/aws-load-balancer-controller
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rpgr6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aws-load-balancer-webhook-tls
    Optional:    false
  kube-api-access-rpgr6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Normal   Scheduled         38m                   default-scheduler  Successfully assigned kube-system/aws-load-balancer-controller-77cbbd5874-lhwq2 to ip-10-0-60-197.ec2.internal
  Normal   Pulled            38m                   kubelet            Container image "amazon/aws-alb-ingress-controller:v2.4.4" already present on machine
  Normal   Created           38m                   kubelet            Created container controller
  Normal   Started           38m                   kubelet            Started container controller

**Comment by kishorj** [comment]
@Moneshs, this is an issue with the networking configuration, not the controller itself. Possible issues - network policy configuration, external SNAT enabled but nodes are public. You will need to cut a support ticket to EKS if you are not able to get it to work.
