### ISSUE TITLE
ALB annotations are not working properly 

### ISSUE THREAD

**Issue by ismferd** [kubernetes-sigs/aws-load-balancer-controller#2965]
**Describe the bug**
Once we added those annotations in order to get the access logs:
```
service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: nlb-logs-testing
```
That works perfect, the problem was trying to disable the access log:
```
service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "false"
```
We get an reconciliation error about the schema:
`{"level":"error","ts":1673278986.2667832,"logger":"controller","msg":"Reconciler error","controller":"service","name":"test","namespace":"test","error":"ValidationError: The value of 'access_logs.s3.bucket' cannot be empty\n\tstatus code: 400, request id: 03ebe04f-0283-4295-a6f5-35caa2abb177"}`

The error persist even removing completely both annotation

**Steps to reproduce**
Modify the svc adding those annotations:
```
service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: nlb-logs-testing
```
change the value of `aws-load-balancer-access-log-enabled: ` to false

**Expected outcome**
Disable access log without errors

**Environment**

* AWS Load Balancer controller version: aws-alb-ingress-controller:v2.1.3
* Kubernetes version: 2.21
* Using EKS (yes/no), if so version? yes, 2.21

**Additional Context**:

**Comment by kishorj** [comment]
@ismferd, we recommend to use the annotation `service.beta.kubernetes.io/aws-load-balancer-attributes` instead, for details please refer to the [live-doc]( https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#load-balancer-attributes). You need to update to the latest version for this annotation to work.

**Comment by ismferd** [comment]
@kishorj Do you know if we can get any incompatibilities between versions? I mean, we are using others annotations for the controller like:
```
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: nlb-logs-testing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthcheck
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTPS
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```

**Comment by kishorj** [comment]
These annotations are deprecated, but will continue to work for the time being:
```
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: nlb-logs-testing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```
