### ISSUE TITLE
Add support for (or document) `deregistration_delay.connection_termination.enabled`

### ISSUE THREAD

**Issue by applike-ss** [kubernetes-sigs/aws-load-balancer-controller#2969]
**Is your feature request related to a problem?**
I'd like to use deregistration_delay.connection_termination.enabled, however it is not documented.
I'm not sure whether it is working OOTB, until i try it in some spare time.

**Describe the solution you'd like**
Add support for (or document) `deregistration_delay.connection_termination.enabled`

**Describe alternatives you've considered**
Try it out in spare time and create a PR - or continue business as usual without an improvement.

**Comment by kishorj** [comment]
@applike-ss, you can specify the target group attributes supported by AWS ALB/NLB. For NLB, you can get a list of target group attributes from the [AWS doc](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-group-attributes).

The controller [live doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#target-group-attributes) provides further details on configuring the target group attributes. To enable enable connection termination on deregistration:
```
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.connection_termination.enabled=true
```
