### ISSUE TITLE
docs/install/v2_4_6_full.yaml is missed

### ISSUE THREAD

**Issue by Vadim-Zenin** [kubernetes-sigs/aws-load-balancer-controller#2977]
**Describe the bug**
Automated deployment could not find installation file based on release version v2.4.6

**Steps to reproduce**
```bash
DOWNLOAD_DIR="${HOME}/Downloads"
EKS_LB_CONTROLLER_VERSION="v2.4.6"
EKS_LB_CONTROLLER_INSTALL_VERSION="$(echo ${EKS_LB_CONTROLLER_VERSION} | sed -e 's/\./_/g')"
curl -sL -o ${DOWNLOAD_DIR}/aws-load-balancer-controller/${EKS_LB_CONTROLLER_INSTALL_VERSION}_full.org.yaml https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/${EKS_LB_CONTROLLER_INSTALL_VERSION}_full.yaml
cat ${DOWNLOAD_DIR}/aws-load-balancer-controller/${EKS_LB_CONTROLLER_INSTALL_VERSION}_full.org.yaml
```
404: Not Found

**Expected outcome**
Downloded ${EKS_LB_CONTROLLER_INSTALL_VERSION}_full.yaml file.

**Environment**

* AWS Load Balancer controller version
v2.4.6
* Using EKS (yes/no), if so version?
1.24

**Comment by Vadim-Zenin** [comment]
I found the file under release:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.4.6/v2_4_6_full.yaml

**Comment by kishorj** [comment]
@Vadim-Zenin, the installation manifests are now part of the release artifacts, we no longer include them in the docs/install directory.

**Comment by kishorj** [comment]
@Vadim-Zenin, I'm closing the issue. If you have further concerns regarding this matter, feel free to reach out to us.
