### ISSUE TITLE
readinessGates auto injection is not working when we are using helm chart for deployments

### ISSUE THREAD

**Issue by rijoparakkal** [kubernetes-sigs/aws-load-balancer-controller#2979]
**Describe the bug**
Normal manifest deployment is working and we can see readiness gate injection is happening but when we switch to helm based deployment the injection is not happening. is it related to the order of creation in helm ? how we can fix the issue

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by kishorj** [comment]
@rijoparakkal, I'm assuming you are referring to your app deployment not this controller itself. The controller injects the readiness gates only when it finds the matching services/target group bindings. It is possible your application pods got created before the service, or before the LB controller completed provisioning the NLB and the target groups for the service.

The purpose of the readiness gate is to keep the existing pods until the new ones are registered and healthy in case of rolling updates. The lack of readiness gates for initial deployment would not affect it.

**Comment by rijoparakkal** [comment]
> @rijoparakkal, I'm assuming you are referring to your app deployment not this controller itself. The controller injects the readiness gates only when it finds the matching services/target group bindings. It is possible your application pods got created before the service, or before the LB controller completed provisioning the NLB and the target groups for the service.
> 
> The purpose of the readiness gate is to keep the existing pods until the new ones are registered and healthy in case of rolling updates. The lack of readiness gates for initial deployment would not affect it.

Hi @kishorj  , I just updated the target type as IP and after first few deployments the configs are automatically injected , Thanks for the comment
