### ISSUE TITLE
Allow to configure AWS GO SDK Client Logging

### ISSUE THREAD

**Issue by afischer-opentext-com** [kubernetes-sigs/aws-load-balancer-controller#2997]
**Problem**

While implementing the AWS Load Balancer Controller we had a hard time enable it properly working due to the sheer absense of debug logging. 

Our setup incorporates an HTTP proxy and due to human error we had a misconfiguration in that config (environment variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY): The proxy url had no protocol (*facepalm*).

The result was that the aws-load-balancer-controller pod properly started and ran but basically did nothing which was obvious to use. 

**Proposed solution**

It would have been absolutely helpful if we could - either via environment variable or command line flag - enable the [ClientLogMode](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/logging/) of the underlying AWS SDK for Go. This would have immediately reported issues with the HTTP client calling the API instead of idling around without _any_ helpful message. 

**Alternatives**

There is no alternative I can think of. Checking VPC Flow logs was of little to no help in understanding the issue.

**Comment by oliviassss** [comment]
We have a controller command line flag `--log-level`, the default value is `info` but you can set to `debug`. Does it help in your case?

**Comment by afischer-opentext-com** [comment]
We tried that and it did not improve the situation. We saw two more log lines during bootup of the pod but that's it. It was not helpful unfortunately.
