### ISSUE TITLE
NLB Load Balancer Type: External not working in K8s 1.24

### ISSUE THREAD

**Issue by egkelly** [kubernetes-sigs/aws-load-balancer-controller#3000]
**Describe the bug**
When annotating an NLB service with `service.beta.kubernetes.io/aws-load-balancer-type: "external"`, the load balancer controller does not recognize the service and it spins continually on `Ensuring Load Balancer` and the NLB is not created in AWS. Nothing is logged in the load balancer controller, which would indicate that the controller is following the behavior described [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#legacy-cloud-provider)

* Note: This was working in Kubernetes version 1.23 but broke upon upgrading to 1.24

**Steps to reproduce**
Create a service of type LoadBalancer and set the following annotations to designate an NLB
```  
  service.beta.kubernetes.io/aws-load-balancer-type: "external",
  service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
```

Upon applying, the service will be stuck in `Pending` and the only event logged is `Ensuring Load Balancer`

**Expected outcome**
Internet-facing NLB is created

**Environment**

* AWS Load Balancer controller version: `2.4`
* Kubernetes version: `1.24`
* Using EKS (yes/no), if so version? `eks.3`

**Additional Context**:
A workaround is to set the annotation to be `service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"` which successfully creates an internet-facing NLB.

**Comment by kishorj** [comment]
@egkelly, with `service.beta.kubernetes.io/aws-load-balancer-type: "external"` annotation, you'd also need to specify the [NLB target type](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#nlb-target-type) via annotation.

**Comment by kishorj** [comment]
Please refer to the [NLB configuration section](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/#configuration) in the live docs.

**Comment by sshepel** [comment]
Same problem here. 

Annotations are in place:
```
service.beta.kubernetes.io/aws-load-balancer-type: "external"
service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
```
Subnet tags for auto-discovery are also there.

Service External IP is constantly in a `Pending` state and LB has not appeared in AWS Console.

From cluster events I can see the following events related to Service: 
```
message: "Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: <id>"
```
IAM policies for LBs services account have been used from `2.4.6` release, Helm chart version is `1.4.7`.

**Comment by dilyevsky** [comment]
Same problem on EKS 1.25 - no NLB is visible in the console and no logs from kcm/cloud-controller beside this event:

```
  Normal  EnsuringLoadBalancer  6m26s (x2 over 7m30s)  service-controller  Ensuring load balancer
```

Annotations:
```
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
              service.beta.kubernetes.io/aws-load-balancer-type: external
```

**Comment by rogerson96** [comment]
Mesmo problema no EKS 1.26 
 
    Normal  EnsuringLoadBalancer  12m   service-controller  Ensuring load balancer

    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"

**Comment by dilyevsky** [comment]
@rogerson96  try these (i was able to get it to work after reading the controller implementation code):

```
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
```

TBH the current state of AWS controller docs is a complete dumpster fire...

**Comment by rogerson96** [comment]
@dilyevsky  this way it creates the nlb but with the target type instance, I don't know why but it ignores this annotation
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip

have you been through this?

**Comment by dilyevsky** [comment]
@rogerson96 IP routing only supported if you run native AWS CNI plugin (https://github.com/aws/amazon-vpc-cni-k8s). If you use something like calico or cilium it will still use instance.

**Comment by bianchi2** [comment]
EKS 1.25, `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip` is ignored, instance type targets are created instead. AWS CNI addon version is v1.12.2-eksbuild.1

**Comment by pkutishch** [comment]
the same here, NLB created,  however targets are instances what led to the nf_conntrack table overflow.
