### ISSUE TITLE
Cannot updtae 2.4.5 to 2.4.6 from yaml based deployment to helm 

### ISSUE THREAD

**Issue by hetpats** [kubernetes-sigs/aws-load-balancer-controller#3005]
HI,
We have been using the alb controller for more than 2 years and are at v 2.4.5 we now want to migrate to 2.4.6 but using helm based deployment instead of yaml install. 
However due to existing ingress objects we cannot delete the targetgroupbindings crd, and hence the validation webhook doesn't get removed when we run kubectl delete to remove existing alb installtion. basically the hook waits for all the target group to be deleted before it  deletes it self.
Is there a way to update or migrate from yaml to helm without deleting all the ingress on the cluster ?

ERROR ON cluster Logs : "targetgroupbindings.elbv2.k8s.aws waiting for 12 items to be removed"

**Comment by kishorj** [comment]
@hetpats, you could keep the crds from v2.4.5, and also the ingress and the targetgroup binding resources. The v2.4.6 controller will be able to pick up the existing resources.

**Comment by oliviassss** [comment]
@hetpats, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks
