### ISSUE TITLE
How to set when no need to set security groups in case of nlb service 

### ISSUE THREAD

**Issue by ar-bella-jeong** [kubernetes-sigs/aws-load-balancer-controller#3008]
**Is your feature request related to a problem?**
I used terraform to create my cluster and security group. However, when I use nlb(internal-facing), the controller set security groups to cluster sg using load-balancer-source-ranges.

**Describe the solution you'd like**
I'd like to maintain all security groups in terraform configuration. Is there any way to not set security group when I launch nlb?

**Comment by oliviassss** [comment]
Currently the SG feature is not supported for NLB.

You can disable the backend SG by setting the controller flag `--enable-backend-security-group=false`. Or if needed, you can set frontend SG created by you to your ALB via the annotation `alb.ingress.kubernetes.io/security-groups` 
For more info, you can check:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2118
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#security-groups

**Comment by oliviassss** [comment]
@ar-bella-jeong, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks
