### ISSUE TITLE
AWS Load balancer controller deletes security group inbound rules and adds open to internet automatically 

### ISSUE THREAD

**Issue by harsha20494** [kubernetes-sigs/aws-load-balancer-controller#3012]
**Describe the bug**
AWS Load balancer controller deletes security group inbound rules and adds open to internet automatically 

**Steps to reproduce**
1. Add inbound rules to ALB security group.
2. Leave the setup for one month.

**Expected outcome**
 1. We observed the security rules that we added to ALB got removed from AWS load balancer controller user and open to internet got added automatically 

**Environment**

* AWS Load Balancer controller version(latest)
* Kubernetes version(1.22)
* Using EKS (yes) 
**Additional Context**:

**Comment by M00nF1sh** [comment]
@harsha20494 
You should not manually modify the securityGroup created by ALB, the rules is automatically managed by the controller, every reconcile(e.g. when node changes) will bring it to the desired state controller expects.
You can use annotation https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#inbound-cidrs to customize the inbound CIDR to desired one.

Alternatively, you can use annotation(https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#security-groups) to specify a security **created by you** if you want more flexibility.

**Comment by oliviassss** [comment]
@harsha20494, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks
