### ISSUE TITLE
ALB Controller Pod restarting with error messages.

### ISSUE THREAD

**Issue by sabinayakc** [kubernetes-sigs/aws-load-balancer-controller#3013]
**Describe the bug**
I deployed the `alb controller` using https://aws-ia.github.io/terraform-aws-eks-blueprints/v4.22.0/add-ons/aws-load-balancer-controller/. 

After deployment, I see the below errors:
```
{"level":"error","ts":1675116192.6487575,"logger":"controller-runtime.manager","msg":"Failed to get API Group-Resources","error":"Get \"https://10.100.0.1:443/api?timeout=32s\": dial tcp 10.100.0.1:443: i/o timeout"}
{"level":"error","ts":1675116192.648819,"logger":"setup","msg":"unable to start manager","error":"Get \"https://10.100.0.1:443/api?timeout=32s\": dial tcp 10.100.0.1:443: i/o timeout"}
```

**Expected outcome**
Should be able to deploy controller.

**Environment**

* AWS Load Balancer controller version: 1.4.5 Helm Chart (v2.4.4 app version)
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version?: EKS 1.24

**Additional Context**:
- Custom Networking is Enabled: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking 
- Control Plane Subnets are provided

**Comment by newgithubusr** [comment]
Hi,
How did you resolve this issue ?
