### ISSUE TITLE
Support ALB Creation for K8S Services

### ISSUE THREAD

**Issue by jls-appfire** [kubernetes-sigs/aws-load-balancer-controller#3017]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
We would like the ability to specify whether an ALB or an NLB is created for K8S services.

**Describe alternatives you've considered**
* Using the AWS LB Controller annotations directly on each ingress and sharing the LB across multiple ingresses. This works as well, but there are concerns about security and who can enable / disable logging or other important or security features (TBF the documentation states this as a known issue for which work is being done). Using this method we also lose the ability to leverage Traefik middleware. We've used the middleware on a few occasions to quickly remedy security issues (e.g. adding response custom headers ahead of a patch from development, filtering out request headers, etc) and would like to keep this option available.
* Launching Traefik and manually creating an Ingress (pointing to Traefik) which results in an ALB being created that talks to Traefik. But this is an extra step (not terrible, but would like to avoid) and we have to then use a wildcard DNS entry and route all traffic to that ALB / ingress. This has some side effects - each subdomain has to have it's own LB and Ingress, it just feels "hacky" and insecure to use wildcard DNS (yes, it's been done for a long time and may not be that bad, hence "feels" insecure). We also found that when using this mechanism, the "ADDRESS" field of the ingress (from `kubectl get ingress ...`) is never updated. For an ingress that previously held a value, it continues to show the previous (and now incorrect) address; for a new ingress the ADDRESS field is blank. This prevents use of external-dns for automated DNS management, hence the wildcard DNS entry. 
* Creating an NLB on the Traefik service using LB Controller annotations. This mostly works, but prevents the use of TLS from the NLB to the Traefik service because the NLB (I *think*, based on reading the NLB docs) does not pass along SNI / do any negotiation with the backend. This seems to be a well known / documented issue.
* Using annotations (in previous LB controller versions) to create an ELB instead of an NLB. But this has security implications - in very specific circumstances (using HTTP 1.0 and HTTP -> HTTPS redirects), the ELB can be forced to expose it's private IP address, giving attackers additional information about a users infrastructure. I had opened a ticket with AWS support about this issue and the answer I was given was "ELBs are deprecated, use an ALB", but I cannot use an ALB with a service, only with an Ingress. Hence this feature request.

I did a bit of searching for another Github issue that may have explained why an ALB is not available with a K8S service as the backend, but if I missed the issue, please link it to this one so I can review. I've also spent several hours reading, and re-reading the LB controller documentation, but could find no existing way to create an ALB for a service. The navigation menu specifically calls out ALB -> Ingress and NLB -> Service so I took that to mean this is a new feature.

**Comment by oliviassss** [comment]
Hi I'm trying to understand your use case especially the NLB and Traefik service. The NLB supports TLS feature with SNI, what do you mean by it does not pass along SNI? [Demo](https://exampleloadbalancer.com/nlbsni_demo.html)
If you need a TLS communication btw the NLB and server, you can try to install a certificate on the server, and then just change the target group settings on the NLB to point to the secure ports on the server.

**Comment by jls-appfire** [comment]
Hi @oliviassss - thank you for the response. Here is the scenario:

Client -> NLB (with TLS termination using ACM) -> Traefik K8S Service -> Traefik K8S Pod

When I configure Traefik with two ports on the service (one for non-TLS, one for TLS), the *Client -> NLB with TLS term -> Traefik K8S Service :80 **without** TLS -> Traefik K8S Pod -> My Test Service* works fine.

But *Client -> NLB with TLS term -> Traefik K8S Service :443 **with** TLS -> Traefik K8S Pod -> My Test Service* always returns an HTTP 404.

To confirm Traefik works fine, I did the following (in this example, my-service.mydom.com is a CNAME pointing to the FQDN of the NLB):
* `kubectl port-forward service/my-traefik-service 8443:443`
* `curl -v --connect-to 'my-service.mydom.com:443:localhost:8443 https://my-service.mydom.com/` (to talk directly to the Traefik service and force the host headers / SNI negotiations)

Talking directly to the Traefik service works perfectly and I receive the correct TLS certificate (in this case a Let's Encrypt cert). But when I just use `curl -v https://my-service.mydom.com`, I see the AWS ACM certificate (which is correct) but I always receive an HTTP/404 error. I verified that the hosts in the target group are all marked online / available. I tried using both TLS and TCP as the protocol for the target group to talk to the Traefik K8S service. Neither one worked.

I've spent the past two days reading over various documentation so I hope I haven't missed anything, however that is entirely possible. That would be the ideal case as well since it represents the least amount of work for everyone.

**Comment by jls-appfire** [comment]
I may have found out what I was doing wrong. I think that I did the following (I am going to repeat these steps to make sure):

* Created the Traefik ingress with the NLB annotations but set `backend-protocol` to `tcp`
* Changed the `backend-protocol` from `tcp` to `ssl` and applied the changes, but did not destroy anything first
* Forgot to check that the protocol on the target group was updated (I **don't think it was in my latest test but didn't pay enough attention**)
* Tried testing connectivity to the backend services through the public https://my-service.mydom.com and it failed, so educated guessed that it was an NLB -> backend TLS issue.

I've spent in total about five or six days trying to get this to work unfortunately and finally decided just ask for the ALB on a service since that worked so effortlessly for me.

Side question - why is an ALB not supported on a K8S service?

**Comment by jls-appfire** [comment]
@oliviassss I do have this working now, there were probably another five or six changes I had to make, mostly on the Traefik side, but some on the NLB side.

I don't have a strong reason to keep this open at this point, but still am curious as to why can users not select an ALB vs NLB for either a Service or an Ingress?
