### ISSUE TITLE
[Bug] An error was reported "unable to discover at least one subnet" on cluster

### ISSUE THREAD

**Issue by yang-wang11** [kubernetes-sigs/aws-load-balancer-controller#3021]
**Describe the bug**

When I used the `kubeadm` tool to create a k8s cluster and deploy this AWS `load balancer controller` for managing the `LoadBalancer` service resource. the controller returned the `unable to discover at least one subnet` error message.

**Steps to reproduce**
1. [create k8s cluster](https://kubernetes.io/docs/setup/production-environment/)
2. follow the instructions below to deploy this controller with the required privileges, and set the environment `--cluster-name` to empty
    https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/
3. error logs from this controller 
```
aws-load-balancer-controller-7858ff68b9-4qhx7 controller {"level":"error","ts":1675413608.3014076,"logger":"controller.service","msg":"Reconciler error","name":"sample","namespace":"sample","error":"unable to discover at least one subnet"}
aws-load-balancer-controller-7858ff68b9-4qhx7 controller {"level":"error","ts":1675413775.8055873,"logger":"controller.service","msg":"Reconciler error","name":"sample","namespace":"sample","error":"unable to discover at least one subnet"}
```

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
  aws-load-balancer-controller:v2.4.6
* Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Using EKS (yes/no), if so version?
no

**Additional Context**:

**Comment by kishorj** [comment]
@yang-wang11, you need to set the cluster-name. Any reason why you set to empty?

**Comment by yang-wang11** [comment]
@kishorj 
as I mentioned before, I didn't use the EKS cluster only the VM instances, but the cluster-name is a mandatory field.
