### ISSUE TITLE
ALB controller does not allow the upgrade header

### ISSUE THREAD

**Issue by vumdao** [kubernetes-sigs/aws-load-balancer-controller#3023]
**Describe the bug**
```
kubectl exec -it app-95c87457d-tv4mz --kubeconfig /Users/vudao/workspace/gitlab/eks-vcluster/kube-config/dev-kubeconfig.yaml -- bash
Defaulted container "app" out of: app, glowrootapp (init)
Error from server (BadRequest): Upgrade request required
```

The kubectl client sends a request with the Upgrade header,[ if the apiserver is forwarded the request without the upgrade request, the handler will return that error.](https://github.com/kubernetes/kubernetes/blob/bc6afee04938d29dfede98610604b944f3123602/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L214-L220).

**Steps to reproduce**
Ref: https://github.com/loft-sh/vcluster/issues/877

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version v2.4.6
* Kubernetes version v1.24.8-eks-ffeb93d
* Using EKS v1.24.8-eks-ffeb93d

**Comment by M00nF1sh** [comment]
I'm not familiar with the vcluster, did you put your APIServer behind a ALB? 
If that's the case, ALB only supports HTTP and HTTP/2.0 protocol, and cannot be used for kubectl. have you considered to use a NLB instead?

**Comment by vumdao** [comment]
Thanks @M00nF1sh yep, I put the APIServer behind a ALB. It works well with NLB

**Comment by ajaydevtron** [comment]
Hello @M00nF1sh 
Any workaround for ALB ?
Thanks 🙏 in Advance
