### ISSUE TITLE
React.JS / Next.JS application keeps getting 502 error which does NOT happen in our local developement environment

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#3032]
**Describe the bug**
Latest version of ALB. Don't spot any of the HTTPCode_ELB_502_Count, HTTPCode_Target_5XX_Count, elb_status_code and target_status_code in the logs. I am using SPDY and HTTP/2 backend protocol with default 60-second idle timeout. I have configured the following:

```
  server.on("connection", function(socket) {
    // Set the socket's idle timeout in milliseconds. 2 minutes is the default
    // for Node's HTTPS server. We are currently using SPDY:
    // https://nodejs.org/api/https.html#https_server_settimeout_msecs_callback
    socket.setTimeout(70000)
    socket.setKeepAlive(70000)

    // Wait for the timeout event. The socket will emit it when the idle timeout
    // elapses.
    socket.on("timeout", function() {
      // Call destroy again.
      socket.destroy();
    });
  });
```

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version `2.4.6`
* Kubernetes version `v1.24.8-eks-ffeb93d`
* Using EKS (yes/no), if so version? Yes `v1.24.8-eks-ffeb93d`

**Additional Context**:

**Comment by kishorj** [comment]
@khteh, could you verify if the target group targets are healthy?

**Comment by oliviassss** [comment]
@khteh, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks
