### ISSUE TITLE
Controller doesn't always honor path order

### ISSUE THREAD

**Issue by machad** [kubernetes-sigs/aws-load-balancer-controller#3033]
**Describe the bug**
The controller does not always honor path order when creating ALB rule priorities. 

**Steps to reproduce**
Deploy multiple ingress templates, each with multiple paths, that use the same group name. 

**Expected outcome**
The paths should be added to the ALB in the order in which they are specified in the ingress yaml file. 

**Environment**

* AWS Load Balancer controller version: 2.4.6
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? Yes, EKS 14

**Additional Context**:
I have several ingress templates that use the same group name in order to share a single load balancer. Each of these templates point to different services on the back end. Each have an IP restricted path and an open path. The IP restricted path is /health, the open path is /*. The templates specify the path definitions something like this:
* If host header matches and source ip matches and /health, forward to the backend
* If host header matches and /health, return a static 404
* If host header matches and /*, forward to the backend

This definition works in the correct order most of the time. After several of these are deployed, the controller stops honoring the order. I start to see the priority of the /* rule go above the /health rules, which will cause the IP restriction not to work. This also seems to be happening when we have 23+ rules.

**Comment by kishorj** [comment]
@machad, controller maintains rule order for `ImplementationSpecific` path types only. `Prefix` and `Exact` path types need to honor the precedence defined in the ingress spec - https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches

**Comment by michaljrk** [comment]
I stumbled upon the same issue - ALB  rules order (priority) doesn't match the one specified in my Ingress definition.
I tried both - `ImplementationSpecific` and `Prefix` path types and the result is the same.
Is there any option to control the rules order/priority on ALB?

**Comment by murasaki718** [comment]
> @machad, controller maintains rule order for `ImplementationSpecific` path types only. `Prefix` and `Exact` path types need to honor the precedence defined in the ingress spec - https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches

I've run into this exact issue with the latest version. I've tried a few techniques but failed. The old should follow the order present in the ingress manifest

**Comment by nlederman** [comment]
We've also hit this issue in our infrastructure as of the latest version. You'd think something like that would get hit in testing but I suppose not. Reverting to v2.4.1 worked for us. Thanks @avivgold098

**Comment by JohnPolansky** [comment]
We've also hit this issue in our infrastructure using 2.4.5. We tried 2.4.7 but it has the same issue. We downgraded to 2.4.1 and it fixes it. We can't go to 2.5.1 until we make some other changes so not sure if it's fixed there, but we need this issue fixed before we can upgrade. Hopefully we can get it fixed soon or explain how we can better control the order of rules.

**Comment by jutley** [comment]
I just ran into this issue. It looks like this was introduced in version 2.4.3, in PR #2409.

Supposedly the issue is that the Kubernetes spec says that the longest match must be used, with exact matches beating prefix matches in a tie-breaker.

But there doesn't seem to be any prescriptive guidance on how to handle `ImplementationSpecific` paths. The new behavior is very troublesome. If someone creates a rule to redirect _all_ HTTP traffic to HTTPS, and a more specific rule to route a specific path to a specific service, then HTTP traffic to that specific path _will not get directed to HTTPS_.

The guidance I've seen is to create two Ingresses with a common group name and explicit group ordering, but this is unnecessarily complicated UX for a very desirable (and basic) use case.

**Comment by soumaity01** [comment]
I observed the similar behavior, the order of the rules are not maintained as per the definition. There should be some way to organize the ALB listener rule. Requesting to look into it.
