### ISSUE TITLE
IngressGroup documentation should warn about ALB changes

### ISSUE THREAD

**Issue by JacobHenner** [kubernetes-sigs/aws-load-balancer-controller#3034]
The documentation for [IngressGroup](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#ingressgroup) should mention that changes to the value of `alb.ingress.kubernetes.io/group.name` will change the ALB the Ingress object is associated with - possibly triggering ALB creation or deletion. This is especially important for the annotation unset -> set case, as it's not intuitive that a new ALB is required or that the previous one will be replaced.

It seems like this concern [was raised previously](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2271#issuecomment-936707359), but not addressed at that time.

**Comment by M00nF1sh** [comment]
/kind documentation

Yes, changing group name will cause LB recreation. we can call out this in our documentation.  The LoadBalancer's is uniquely identified by it's groupName.
