### ISSUE TITLE
API version "extensions/v1beta1" is deprecated for kubernetes V1.24

### ISSUE THREAD

**Issue by chejuro1** [kubernetes-sigs/aws-load-balancer-controller#3039]
The ingress controller appears to populate this version "extensions/v1beta1" of api  instead of networking.k8s.io/v1 after deploying ALB to work with  kubernetes V1.24 
Below is the complete logs for ingress controller pod 
-------
W0208 17:14:34.247738       1 config.go:46] Environment variable configuration is deprecated, switch to the --aws-region flag.
W0208 17:14:34.248786       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
F0208 17:14:34.388214       1 main.go:107] no matches for kind "Ingress" in version "extensions/v1beta1"

**Comment by kishorj** [comment]
@chejuro1, you need to update the controller to v2.4.x release.

**Comment by chejuro1** [comment]
I am working with terraform module to deploy AWS ALB. Where should I update the controler?

**Comment by chejuro1** [comment]
I though I was using the latest version on AWS ALB terraform module .
module "alb_ingress_controller" {
  source  = "iplabs/alb-ingress-controller/kubernetes"
  version = "3.4.0"

**Comment by oliviassss** [comment]
@chejuro1, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks.
