### ISSUE TITLE
Alb extension api issue 

### ISSUE THREAD

**Issue by chejuro1** [kubernetes-sigs/aws-load-balancer-controller#3040]
Please I am having this error after deploying aws alb v2.4.5 on kubernetes v1.24 
---
kubectl logs  aws-alb-ingress-controller-5bd68bff7-l9qfx -n kube-system
{"level":"info","ts":1675896010.56112,"msg":"version","GitVersion":"v2.4.5","GitCommit":"d9482de36bf51a17e7def869f677f35c2b6c6045","BuildDate":"2022-11-09T20:46:04+0000"}
{"level":"info","ts":1675896010.606742,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}    
{"level":"error","ts":1675896010.6306434,"logger":"setup","msg":"unable to create controller","controller":"TargetGroupBinding","error":"no matches for kind \"TargetGroupBinding\" in version \"elbv2.k8s.aws/v1beta1\""}

**Comment by kishorj** [comment]
Looks like you are upgrading from v1 version of the ingress controller. 
You need to follow these guides:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/upgrade/migrate_v1_v2/
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/

The errors indicate you don't have the required crds installed.

**Comment by kishorj** [comment]
You need to completely uninstall v1 controller and install v2. You can keep the existing ingress resources though.

**Comment by oliviassss** [comment]
@chejuro1 I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks
