### ISSUE TITLE
Expose metrics for readiness gate status

### ISSUE THREAD

**Issue by alexku7** [kubernetes-sigs/aws-load-balancer-controller#3042]
**Is your feature request related to a problem?**
Today there is one way only to determine the status of the readiness gate by running "kubectl describe pod" command.
It's non convenient in automated CD pipelines.

**Describe the solution you'd like**
Expose the appropriate metrics by LB controller, so we can create alerts in easier way in case the pod can't pass the readiness gate and as result isn't actually ready to serve workloads 

**Describe alternatives you've considered**
None

**Comment by alexku7** [comment]
:(

**Comment by hoangminhtu-dh** [comment]
I'd second this. Readiness gate is a crucial part of my project's gateway rollout and without exposed metrics on possible readiness hiccups, I'd have to comb through log lines and events from various places just to be informed one or multiple pods weren't ready.
