### ISSUE TITLE
Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet

### ISSUE THREAD

**Issue by dv000-7** [kubernetes-sigs/aws-load-balancer-controller#3051]
**Describe the bug**

I am trying to deploy alb(ingress) . application is getting deployed but load balancer is not creating showing error  "Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet.
"
**Steps to reproduce**
1. deploy eks cluster
2. helm repo add eks https://aws.github.io/eks-charts
3. kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
4.helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=<k8s-cluster-name> --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller

**Expected outcome**
 Normal    SuccessfullyReconciled   targetgroupbinding/k8s-default-appname-ad8ee871f8   Successfully reconciled
 but getting 
   Warning   FailedBuildModel         ingress/appname                        Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet.
   
**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by oliviassss** [comment]
Hi, you need to set the clusterName, but you leave it empty in your command. Any specific reason?

**Comment by dv000-7** [comment]
hello, i have given clustername in my cli

**Comment by oliviassss** [comment]
Can you pls check if your subnets are properly tagged?

- public subnets: `kubernetes.io/role/elb: 1`
- private subnets: `kubernetes.io/role/internal-elb: 1`
- common tag: `kubernetes.io/cluster/${cluster-name}`, with value `owned` or `share`

You can check our live doc for more ref: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/subnet_discovery/
Also some similar issue: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2812

Let me know if these can address your issue.

**Comment by oliviassss** [comment]
@dv000-7, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks.
