### ISSUE TITLE
Annotation to enable AWS Shield for NLB resources

### ISSUE THREAD

**Issue by cdobbyn** [kubernetes-sigs/aws-load-balancer-controller#3053]
**Is your feature request related to a problem?**
n/a

**Describe the solution you'd like**
I would like to be able to use an annotation to protect a NLB resource (not ALB) with AWS Shield (as long as Advanced feature is enabled).

**Describe alternatives you've considered**
It is possible today to add a NLB using this controller today. Then you need to go and add that resource to AWS Shield separately (either via GUI or some kind of IaC).

**Comment by cdobbyn** [comment]
I have raised this with our TAM, as I believe this feature is not possible to implement today without changes to the API for this project to be able to leverage. If I get traction and resolution I will re-post here.

**Comment by sftim** [comment]
@cdobbyn if this integration with AWS Shield happened via an IngressClass and its parameterss, would that work for you?

**Comment by cdobbyn** [comment]
@sftim Maybe, how do you think that would work?

**Comment by sftim** [comment]
> @sftim Maybe, how do you think that would work?

I've not really got capacity to outline how to implement this. It feels like the right fit, thought.

**Comment by abebars** [comment]
> > @sftim Maybe, how do you think that would work?
> 
> I've not really got capacity to outline how to implement this. It feels like the right fit, thought.

I believe it's possible to make this available if the resource has `aws-load-balancer-eip-allocations` in that case we can use that annotation as a prerequisite to make the API call and activate the protection.

I would assume these two annotations would need to go together, what do you think?
cc: @cdobbyn

**Comment by cdobbyn** [comment]
@abebars - I'd prefer to not have to assign a EIP allocation as we stand these clusters up as necessary and rip them out. They don't share a VPC so we'd have to do a bunch up front to make this work / link it together (terraform -> argo secret -> argo -> render chart -> kubernetes). 

Please excuse my ignorance, I don't fully understand the way things work within the controller. Is this a problem because we would want to do this action immediately when the NLB is created? I don't see why it couldn't be something that get's applied after the NLB is fully created.

**Comment by abebars** [comment]
> @abebars - I'd prefer to not have to assign a EIP allocation as we stand these clusters up as necessary and rip them out. They don't share a VPC so we'd have to do a bunch up front to make this work / link it together (terraform -> argo secret -> argo -> render chart -> kubernetes).
> 
> Please excuse my ignorance, I don't fully understand the way things work within the controller. Is this a problem because we would want to do this action immediately when the NLB is created? I don't see why it couldn't be something that get's applied after the NLB is fully created.

@cdobbyn I am not sure that I understand the conflict for what are both asking; maybe we are asking about 2 things, but Currently, AWS Sheild Advanced doesn't support NLB directly, So basically, without creating EIPs beforehand, you can't protect an NLB.

This can be solved in 2 ways if I understand this correctly, Allow the controller to create EIP Allocations automatically, and that will make it viable to assign these IPs to Sheild Advanced.

The other option would be to allow the usage of `aws-load-balancer-eip-allocations` which also can be protected using Sheild Advanced.

As a proposal, I would expect the following 

**Case 1**
`service.beta.kubernetes.io/aws-load-balancer-shield-advanced-protection : 'true'` 
- Without defining anything else, the controller will create EIP Allocations and Pass them to the load balancer so the EIP can be protected.

**Case 2**
`service.beta.kubernetes.io/aws-load-balancer-shield-advanced-protection : 'true'` 
`service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-xyz, eipalloc-zzz`
- If the eip-allocations are supplied the controller doesn't need to create them and can just apply the protection to these resources if there is no protection.


Let me know if that makes sense to you

**Comment by james-callahan** [comment]
I think @abebars's design above seems suitable enough?

  - Add the logic to the controller for creating/managing EIPs
  - Add the new annotation
  - Add IAM permissions to the deployment config
