### ISSUE TITLE
v2.4.6 not available on hub.docker.com

### ISSUE THREAD

**Issue by elliotdobson** [kubernetes-sigs/aws-load-balancer-controller#3055]
**Describe the bug**
v2.4.6 has not yet been published to https://hub.docker.com/r/amazon/aws-alb-ingress-controller and thus the image `docker.io/amazon/aws-alb-ingress-controller:v2.4.6` is not available.

**Steps to reproduce**
```console
$ docker pull docker.io/amazon/aws-alb-ingress-controller:v2.4.6
Error response from daemon: manifest for amazon/aws-alb-ingress-controller:v2.4.6 not found: manifest unknown: manifest unknown
```

**Expected outcome**
v2.4.6 image should be published to hub.docker.com, like they are on AWS Public ECR.

**Comment by kishorj** [comment]
@elliotdobson, we will no longer publish images to hub.docker.com, please use the public-ecr instead:
public.ecr.aws/eks/aws-load-balancer-controller:v2.4.6

**Comment by elliotdobson** [comment]
@kishorj is there any mention of that in the README or CHANGELOG?

**Comment by kishorj** [comment]
It is mentioned in the changelog: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.4.6
