### ISSUE TITLE
how to use paths with * in front

### ISSUE THREAD

**Issue by matus258** [kubernetes-sigs/aws-load-balancer-controller#3056]
**Is your feature request related to a problem?**
I would like to use paths with * in front
example: */api
To get all paths that have api
example: /gui/api or /app/api

**Comment by oliviassss** [comment]
We don't support * in `Exact` or `Prefix`, however, you can use wildcards in `ImplementationSpecific` pathType.

**Comment by matusalem-santos** [comment]
Thanks @oliviassss!
pathType: ImplementationSpecific 
`*/api` not working but `/*/api` is working
