### ISSUE TITLE
Verbosity of 403 UnauthorizedOperation errors

### ISSUE THREAD

**Issue by nicoaws** [kubernetes-sigs/aws-load-balancer-controller#3058]
**Is your feature request related to a problem?**
When the ALB controller has an IAM permission issue, the log message isn't helpful in determining what operation the ALB was attempting, which could massively help remediation times.|

```Warning  FailedBuildModel  21m  ingress  Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.```

**Describe the solution you'd like**
I'd like the ALB error log messages to include the AWS API action attempted so that the relevant policy could be amended.

```Warning  FailedBuildModel  21m  ingress  Failed build model due to UnauthorizedOperation (ec2:DescribeAvailabilityZones): You are not authorized to perform this operation.```

**Comment by NesManrique** [comment]
Hello @kishorj I just hit this too. I first configured the same actions described in the documentation

```
{
    "Effect": "Allow",
    "Action": [
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:RevokeSecurityGroupIngress"
    ],
    "Resource": "*"
},
```

Then I saw these logs, so I adjusted accordingly. Later I saw similar logs to OP and just to try I added the rest of the actions described in the "Attach IAM Policies to Nodes" section of the docs.

```
"error":"AccessDenied: User: arn:aws:sts::1234567890:assumed-role/alb/167688920141234567 is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers because no identity-based policy allows the elasticloadbalancing:DescribeLoadBalancers action\n\tstatus code: 403"

"error":"AccessDenied: User: arn:aws:sts::1234567890:assumed-role/alb/167688920141234567 is not authorized to perform: elasticloadbalancing:DescribeTags because no identity-based policy allows the elasticloadbalancing:DescribeTags action\n\tstatus code: 403"
```

This is how my policy looks at the end

```
{
    "Effect": "Allow",
    "Action": [
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:RevokeSecurityGroupIngress",
        "elasticloadbalancing:DescribeLoadBalancers",
        "elasticloadbalancing:DescribeTags",
        "ec2:DescribeVpcs",
        "ec2:DescribeSecurityGroups",
        "ec2:DescribeInstances",
        "elasticloadbalancing:DescribeTargetGroups",
        "elasticloadbalancing:DescribeTargetHealth",
        "elasticloadbalancing:ModifyTargetGroup",
        "elasticloadbalancing:ModifyTargetGroupAttributes",
        "elasticloadbalancing:RegisterTargets",
        "elasticloadbalancing:DeregisterTargets"
    ],
    "Resource": "*"
},
```

And the logs I'm seeing now.

```
{"level":"error","ts":1676916709.039641,"logger":"controller.service","msg":"Reconciler error","name":"ingress-nginx-test","namespace":"ingress-nginx","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: a49abd36-1234-1234-1234-efa4c1eaa7a4"}
{"level":"debug","ts":1676916709.0397198,"logger":"events","msg":"Warning","object":{"kind":"Service","namespace":"ingress-nginx","name":"ingress-nginx-test","uid":"31e81976-1234-1234-1234-183022c78fa8","apiVersion":"v1","resourceVersion":"145372083"},"reason":"FailedBuildModel","message":"Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: a49abd36-1234-1234-1234-efa4c1eaa7a4"}
```

**Comment by lifeoasis-chudee** [comment]
Hello I just fixed the error.
I will share my solution case.

Have you created a cluster or nodegroup with eksctl?
If so, did you add the options below?

```
iam:
  withAddonPolicies:
    albIngress: true
```

If so, run that command
```
eksctl get iamidentitymapping --cluster <your-cluster>
```

Then the ARN will come out.
And go to aws iam dashboard and search for that role.

If there is a PolicyAWSLoadBalancerController policy of type inline there, give it permission "ec2:DescribeAvailabilityZones".

**Comment by NesManrique** [comment]
> Hello @kishorj I just hit this too. I first configured the same actions described in the documentation
> 
> ```
> {
>     "Effect": "Allow",
>     "Action": [
>         "ec2:AuthorizeSecurityGroupIngress",
>         "ec2:RevokeSecurityGroupIngress"
>     ],
>     "Resource": "*"
> },
> ```
> 
> Then I saw these logs, so I adjusted accordingly. Later I saw similar logs to OP and just to try I added the rest of the actions described in the "Attach IAM Policies to Nodes" section of the docs.
> 
> ```
> "error":"AccessDenied: User: arn:aws:sts::1234567890:assumed-role/alb/167688920141234567 is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers because no identity-based policy allows the elasticloadbalancing:DescribeLoadBalancers action\n\tstatus code: 403"
> 
> "error":"AccessDenied: User: arn:aws:sts::1234567890:assumed-role/alb/167688920141234567 is not authorized to perform: elasticloadbalancing:DescribeTags because no identity-based policy allows the elasticloadbalancing:DescribeTags action\n\tstatus code: 403"
> ```
> 
> This is how my policy looks at the end
> 
> ```
> {
>     "Effect": "Allow",
>     "Action": [
>         "ec2:AuthorizeSecurityGroupIngress",
>         "ec2:RevokeSecurityGroupIngress",
>         "elasticloadbalancing:DescribeLoadBalancers",
>         "elasticloadbalancing:DescribeTags",
>         "ec2:DescribeVpcs",
>         "ec2:DescribeSecurityGroups",
>         "ec2:DescribeInstances",
>         "elasticloadbalancing:DescribeTargetGroups",
>         "elasticloadbalancing:DescribeTargetHealth",
>         "elasticloadbalancing:ModifyTargetGroup",
>         "elasticloadbalancing:ModifyTargetGroupAttributes",
>         "elasticloadbalancing:RegisterTargets",
>         "elasticloadbalancing:DeregisterTargets"
>     ],
>     "Resource": "*"
> },
> ```
> 
> And the logs I'm seeing now.
> 
> ```
> {"level":"error","ts":1676916709.039641,"logger":"controller.service","msg":"Reconciler error","name":"ingress-nginx-test","namespace":"ingress-nginx","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: a49abd36-1234-1234-1234-efa4c1eaa7a4"}
> {"level":"debug","ts":1676916709.0397198,"logger":"events","msg":"Warning","object":{"kind":"Service","namespace":"ingress-nginx","name":"ingress-nginx-test","uid":"31e81976-1234-1234-1234-183022c78fa8","apiVersion":"v1","resourceVersion":"145372083"},"reason":"FailedBuildModel","message":"Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: a49abd36-1234-1234-1234-efa4c1eaa7a4"}
> ```

I also fixed my issue. I missunderstood the documentation and only applied the first policy mentioned in it instead of the one specified below in a separate url.
