### ISSUE TITLE
NLB created for ClusterIP type services

### ISSUE THREAD

**Issue by samox73** [kubernetes-sigs/aws-load-balancer-controller#3059]
**Describe the bug**
According to the [doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/) NLBs should only be provisioned for services of type `LoadBalancer`. However, using version `2.4.1` of the aws-load-balancer-controller an NLB is still provisioned for services of type `ClusterIP`, e.g.:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
  uid: ef0bce7f-bfa4-4f1c-be7b-b7ab20969a90
  resourceVersion: '164326876'
  creationTimestamp: '2023-02-17T10:53:57Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-nlb-target-type":"ip","service.beta.kubernetes.io/aws-load-balancer-scheme":"internal","service.beta.kubernetes.io/aws-load-balancer-type":"external"},"name":"test","namespace":"test"},"spec":{"ports":[{"name":"test","port":5432,"protocol":"TCP","targetPort":5432}],"type":"ClusterIP"}}
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
  finalizers:
    - service.k8s.aws/resources
  selfLink: /api/v1/namespaces/test/services/test
status:
  loadBalancer:
    ingress:
      - hostname: >-
          k8s-test-test-53f4370f4c-4842210baab994be.elb.eu-central-1.amazonaws.com
spec:
  ports:
    - name: test
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: 172.20.161.180
  clusterIPs:
    - 172.20.161.180
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
```

**Steps to reproduce**
- deploy the controller helm chart with necessary values:
  ```
  autoDiscoverAwsRegion: "true"
  autoDiscoverAwsVpcID: "true"
  clusterName: test
  replicaCount: 1
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXX:role/alb-controller-role
    name: alb-controller
  ```
- deploy a test service:
  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: test
    namespace: test
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal
      service.beta.kubernetes.io/aws-load-balancer-type: external
  spec:
    ports:
      - name: test
        protocol: TCP
        port: 5432
        targetPort: 5432
    type: ClusterIP
  ```
- observe the newly created NLB:
  ![image](https://user-images.githubusercontent.com/29289920/219632102-5e3d432c-dbcb-47ce-9767-8b87a1e1bceb.png)

**Expected outcome**
NLB should **not** be provisioned for `ClusterIP` services.

**Environment**

* AWS Load Balancer controller version: 2.4.1
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes, eks4

**Additional Context**:

**Comment by kishorj** [comment]
@samox73, you will need to enable the feature`ServiceTypeLoadBalancerOnly`, for details please refer to the live docs https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/configurations/#feature-gates

**Comment by samox73** [comment]
@kishorj thank your for pointing that out. Could you consider updating the official doc page for NLB-provisioning, so it is transparent that per default not only `LoadBalancer` services are used?

**Comment by alexellis** [comment]
Hi @samox73 just curious, but were the annotations added automatically, or by yourself?

```yaml
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
```

If you added them yourself, it would seem to be expected that an LB was created, if you didn't then this seems like a much more serious bug.

**Comment by samox73** [comment]
The annotations were added manually by myself. Their use case is--when deploying the postgres operator (by zalando)--that services should get these annotations. Whether load balancing is activated in the operator, the service either has type `ClusterIP` or `LoadBalancer`.
