### ISSUE TITLE
deregisting target for unknown reason

### ISSUE THREAD

**Issue by xncbf** [kubernetes-sigs/aws-load-balancer-controller#3069]
I found the log deregisting in alb ingress controller but it doesn't automatically reregisting again.
The pod was running normally and there were no issues.
When calling ping internally, it works fine.
Why unwanted deregisting? And why isn't it automatically registered?

**Comment by xncbf** [comment]
I'm using one controller using two replicas.

This is the log from one of them controller

>{"level":"info","ts":1676814406.2301478,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:ap-northeast-2:925517469638:targetgroup/k8s-rcsapp-rcssende-24d496d02c/2a976e5b7700ac18","targets":[{"AvailabilityZone":"ap-northeast-2a","Id":"172.31.178.98","Port":80}]}
{"level":"info","ts":1676814406.2712817,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:ap-northeast-2:925517469638:targetgroup/k8s-rcsapp-rcssende-24d496d02c/2a976e5b7700ac18"}

**Comment by KanShiori** [comment]
I met the same issue with version v2.4.2, the controller deregistered targets during my pods rolling upgrade, and registered them again after 50min.

>2023-02-24 11:42:30	
{"level":"info","ts":1677210150.4308767,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570334:targetgroup/k8s--5c1e8bc538/5d8f911b3ecff7d4"}
2023-02-24 11:42:30	
{"level":"info","ts":1677210150.2258124,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570334:targetgroup/k8s-5c1e8bc538/5d8f911b3ecff7d4","targets":[{"AvailabilityZone":null,"Id":"172.30.13.76","Port":4000}]}Show context
2023-02-24 10:50:44	
{"level":"info","ts":1677207044.5998342,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570334:targetgroup/k8s-5c1e8bc538/5d8f911b3ecff7d4"}
2023-02-24 10:50:44	
{"level":"info","ts":1677207044.4940577,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570334:targetgroup/k8s-5c1e8bc538/5d8f911b3ecff7d4","targets":[{"AvailabilityZone":"us-west-2b","Id":"172.30.13.76","Port":4000}]}

**Comment by KanShiori** [comment]
I met the same issue with version v2.4.2, the controller deregistered targets during my pods rolling upgrade, and registered them again after 50min. 


>2023-02-24 11:42:30 
{"level":"info","ts":1677210150.4308767,"msg":"registered targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570414:targetgroup/k8s-tidb1373-dbtidbpr-5c1e8bc538/5d8f911b3ecff7d4"}Show context 
2023-02-24 11:42:30 
{"level":"info","ts":1677210150.2258124,"msg":"registering targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570414:targetgroup/k8s-tidb1373-dbtidbpr-5c1e8bc538/5d8f911b3ecff7d4","targets":[{"AvailabilityZone":null,"Id":"172.30.13.76","Port":4000}]} 
**2023-02-24 10:51:15	
{"level":"error","ts":1677207075.1627727,"msg":"ignore pod Endpoint without non-exist podInfo","podKey":"tidb1373933076659200564/db-tidb-0","errorError":"PANIC=runtime error: invalid memory address or nil pointer dereference"}**
2023-02-24 10:50:44 
{"level":"info","ts":1677207044.5998342,"msg":"deRegistered targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570414:targetgroup/k8s-tidb1373-dbtidbpr-5c1e8bc538/5d8f911b3ecff7d4"} 
2023-02-24 10:50:44 
{"level":"info","ts":1677207044.4940577,"msg":"deRegistering targets","arn":"arn:aws:elasticloadbalancing:us-west-2:385595570414:targetgroup/k8s-tidb1373-dbtidbpr-5c1e8bc538/5d8f911b3ecff7d4","targets":[{"AvailabilityZone":"us-west-2b","Id":"172.30.13.76","Port":4000}]}
