### ISSUE TITLE
bug(docs) or feat(clarify VPC tagging requirements - small LoE big impact)

### ISSUE THREAD

**Issue by neoakris** [kubernetes-sigs/aws-load-balancer-controller#3076]
**Is your feature request related to a problem?**  
Install Pre Reqs Docs are too vague about VPC tagging requirement.   
If the docs were improved the following related issue (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2812  ) might not exist.  

What it looks like today:  
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#deployment-considerations

Deployment Considerations[¶](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#deployment-considerations)
Additional Requirements for non-EKS clusters:[¶](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#additional-requirements-for-non-eks-clusters)
Ensure subnets are tagged appropriately for auto-discovery to work
For IP targets, pods must have IPs from the VPC subnets. You can configure amazon-vpc-cni-k8s plugin for this purpose.

--------------------------------------------------------

**Describe the solution you'd like**
"Deployment Considerations" info should be moved to "Network Configuration" (it's definitely a network config issue, and because it's in the wrong spot it's easy to miss)  
 
Also elaborate on it as the following vague statement isn't remotely useful: "Ensure subnets are tagged appropriately for auto-discovery to work.".

At bare minimum reference this https://aws.amazon.com/premiumsupport/knowledge-center/eks-load-balancer-controller-subnets/ 
consider pointing out an example snippet of how VPC should be tagged:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d7016cf39d25245eb0c2992971d711fbe8ddf71e/examples/complete/main.tf#L418-L424 

```
public_subnet_tags = {
  "kubernetes.io/cluster/${local.cluster_name}" = "shared"
  "kubernetes.io/role/elb"                      = "1"
}
private_subnet_tags = {
  "kubernetes.io/cluster/${local.cluster_name}" = "shared"
  "kubernetes.io/role/internal-elb"             = "1"
}
```

--------------------------------------------------------

**Describe alternatives you've considered**
Not sure if this is a bug or a feature request

**Comment by kishorj** [comment]
@neoakris, thanks for the feedback. For the subnet tagging, we can add link to the subnet auto discovery live docs (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/subnet_discovery/). If you have any changes in mind, feel free to raise a PR.

/kind documentation

**Comment by neoakris** [comment]
@kishorj @M00nF1sh @johngmyers 
https://engineering.doit.com/demystifying-the-kubernetes-aws-lb-controller-5e06ad0f276d 
I wrote a blog post about this project that I wanted to put on your radar. I'm also trying to work with my employer's AWS partnership rep to have their docs team get eyes on it to see if they can help in terms of AWS's public docs.


Also about PR: 
I need to study for 4 exam recertifications that are lapsing, but I'll set a slack reminder to check the docs at the end of the year. If no one was able to get to it within a few months, I'll try to make a 1-2 doc related PRs when some spare time free's up later in the year.
