### ISSUE TITLE
Temporarily protect specific AWS resources from reconciliation

### ISSUE THREAD

**Issue by yktakaha4** [kubernetes-sigs/aws-load-balancer-controller#3080]
Thanks to this OSS and contributors.

**Is your feature request related to a problem?**

Sometimes it is necessary to manually change the configuration of ALBs for temporary work during maintenance or system failures.
The current aws-load-balancer-controller keeps checking the difference between Ingress and ALB during startup, so manual changes are overwritten after a certain time.

**Describe the solution you'd like**

Define `protect-reconcile-tags` to allow skipping reconcile of AWS resources that have the specified tags.
(Alternatively, to simplify implementation, only one tag may be allowed)

Use as follows.

1. Apply aws-load-balancer-controller with any `protect-reconcile-tags`. (e.g. `protect-reconcile=true`)
2. Apply any ingress and create ALB.
3. Manually add the tag `protect-reconcile=true` to the ALB.
4. When reconcile the Ingress, if the AWS resource tag contains `protect-reconcile-tags`, either error or ignore the change.
5. If the `protect-reconcile=true` tag is removed from ALB, it will be reconciled as before.

If this proposal is worth implementing I would like to create a PR if possible for me.

My understanding is that there are some validation methods, but I think they are inappropriate as they do not have the state of the tag on AWS.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/49805eac72ec533acdbc2580d6f57c68a9cad45c/webhooks/networking/ingress_validator.go#L52-L89

We could exclude resources that match the `protect-reconcile-tags` in `matchResAndSDKLoadBalancers`, but I am not sure if this is the best way.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/49805eac72ec533acdbc2580d6f57c68a9cad45c/pkg/deploy/elbv2/load_balancer_synthesizer.go#L126-L167

**Describe alternatives you've considered**

Deleting aws-load-balancer-controller will stop the reconcile, but is inappropriate when performing maintenance work on a specific ALB in production.

I would be glad to know if there is a correct way to do this.

**Comment by kishorj** [comment]
@yktakaha4, the current recommend way is to scale the controller deployment to 0 replicas and enable the controller back to the default replicas once you are ready for the controller to reconcile.

**Comment by yktakaha4** [comment]
Thank you for your answer. I understand.
Hopefully there will be further discussion on how to manually maintain the ALB without affecting the controller's deployment status.
