### ISSUE TITLE
IAM Policy throws syntax error when applying

### ISSUE THREAD

**Issue by cristian-castro-al** [kubernetes-sigs/aws-load-balancer-controller#3092]
**Describe the bug**
I was updating the controller to version 2.4.7 and everything went ok, but when I'm trying to update the IAM Policy document for the controller permissions I got the following error: "An error occurred (MalformedPolicyDocument) when calling the CreatePolicyVersion operation: Syntax errors in policy".

**Steps to reproduce**

1. Download the [IAM Policy document](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json).
2. Applying it with AWS CLI.

**Expected outcome**
New policy version created.

**Environment**

* AWS Load Balancer controller version: `2.4.7`
* Kubernetes version: `1.23`
* Using EKS (yes/no), if so version? Yes, `1.23`

**Additional Context**:
I guess the problem is related with this condition:
```
"Condition": {
    "StringEquals": {
        "elasticloadbalancing:CreateAction": [
            "CreateTargetGroup",
            "CreateLoadBalancer"
        ]
    }
}
```
I didn't find "CreateAction" in [Actions defined by Elastic Load Balancing V2](https://docs.aws.amazon.com/service-authorization/latest/reference/list_elasticloadbalancingv2.html#elasticloadbalancingv2-actions-as-permissions).

**Comment by yws-ss** [comment]
Hello @cristian-castro-al ,

Can you share your AWS CLI version? Also, please try to update the AWS CLI version to latest version and try again.

**Comment by cristian-castro-al** [comment]
Hi @yws-ss,

You were right! I was using was-cli 2.7.20. I updated to 2.11.4 and it worked.

Thanks!
