### ISSUE TITLE
aws-load-balancer-controller not responding intermittently 

### ISSUE THREAD

**Issue by OliverRC** [kubernetes-sigs/aws-load-balancer-controller#3093]
**Describe the bug**
We have intermittent failures where calls to the `aws-load-balancer-controller` pods in our cluster just timeout and therefore cause our Helm deployments to fail as the ingress cannot be patched.

After much investigation and calls with AWS support we can see nothing wrong with the EKS networking or cluster. 
There are no strange events in the control plan logs either.

I also noticed at the time of the failure the following command took a really long time to respond (> 30s)
```kubectl get validatingwebhookconfiguration aws-load-balancer-webhook -o yaml```

Typically this responds immediately but when we face an issue it is very slow

It is as if the `aws-load-balancer-controller` pod is running but internally stalled, or requires a "warm up".

**Steps to reproduce**
Unclear, however EKS with Fargate would be a good starting point

**Expected outcome**
`aws-load-balancer-controller` should respond timelessly and consistently. 
The pod should not stall internally

**Environment**

* AWS Load Balancer controller version = 2.4.7
* Kubernetes version = 1.23
* Using EKS (yes/no), if so version? Yes - using Fargate

**Additional Context**:
The `aws-load-balancer-controller` has run for as 100 days with no issues. 
All of a 'sardine' it's not randomly failing/stalling.

**Tried**

1. Updated the `aws-load-balancer-controller` to the latest
2. Restarted the pods
3. Killed pods and created new pods
4. Scaled the deployment
5. Reviewed all networking in VPC and subnets
6. Reviewed security groups
7. Reviewed dumped Flow logs
8. Reviewed EKS Control Plane logs
9. Calls with senior engineer at AWS

** Command Outputs **

```
kubectl get deployment aws-load-balancer-controller -n kube-system
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
aws-load-balancer-controller   2/2     2            2           271d
```

```
kubectl get pod -n kube-system
NAME                                           READY   STATUS    RESTARTS   AGE
aws-load-balancer-controller-984bcf547-lmjwt   1/1     Running   0          7d18h
aws-load-balancer-controller-984bcf547-vcx2w   1/1     Running   0          7d18h
coredns-cc7bd487f-zmtcw                        1/1     Running   0          116d
coredns-cc7bd487f-ztq4d                        1/1     Running   0          120d
```

(at time of issue took really long to respond)
```
 kubectl get validatingwebhookconfiguration aws-load-balancer-webhook
NAME                        WEBHOOKS   AGE
aws-load-balancer-webhook   2          271d
```

```
kubectl get mutatingwebhookconfiguration
NAME                                             WEBHOOKS   AGE
0500-amazon-eks-fargate-mutation.amazonaws.com   2          271d
aws-load-balancer-webhook                        2          271d
pod-identity-webhook                             1          271d
vpc-resource-mutating-webhook                    1          271d
```

**Comment by kishorj** [comment]
@OliverRC, the ` kubectl get validatingwebhookconfiguration aws-load-balancer-webhook -o yaml` command doesn't require a functional AWS LB controller. This is a query to the Kubernetes API server - either the api server is busy, or you have some other webhooks delaying the response. Would it be possible for you to create a ticket with the EKS support so we can help investigate further?

**Comment by OliverRC** [comment]
The above command was an observation that I thought may be related. 
If it does not use actually communicate with the `aws-loadbalancer-controller` pods then maybe it is a "red-herring"

The root issue is that our deployments fail to patch the ingress with:

```
UPGRADE FAILED: release my-release-name failed, and has been rolled back due to atomic being set: cannot patch "my-ingress" with kind Ingress: Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": failed to call webhook: Post "[https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s](https://aws-load-balancer-webhook-service.kube-system.svc/validate-networking-v1-ingress?timeout=10s)": context deadline exceeded
```

* No pod restarts
* Nothing in the `aws-loadbalancer-controller` pod logs
* Nothing in the EKS control plane logs
* No changes in networking configurationn
* No evidence of networking issue in VPC Flow Logs

I have logged EKS support cases and they were unable to find anything wrong with our cluster and networking setup.
It is as if the pods have stalled internally. I could see that the webhook was running in the pods.

**Comment by OliverRC** [comment]
I have tried killing and recreating the pods. The pod restarted a number of times.
Looking at the pod logs there are errors of the pod trying to contact something.

```
{
    "level": "error",
    "ts": 1678710528.3525379,
    "logger": "setup",
    "msg": "unable to start manager",
    "error": "Get \"https://10.100.0.1:443/api?timeout=32s\": dial tcp 10.100.0.1:443: i/o timeout"
}
```

What is `10.100.0.1` as this is not a IP in my VPC

**Comment by berry2012** [comment]
@OliverRC 10.100.0.1 is for DNS inside your cluster and it is gotten from the ServiceIPv4 CIDR of your Kubernetes cluster so it is not from your VPC. The 10.100.0.1 is mapped to your Cluster's API Server endpoint.
Do you mind sharing further details on how you installed ALB controller in the cluster.
I'd recommend your exec into the pods and confirm if they can reach the Cluster's API Server endpoint.

**Comment by OliverRC** [comment]
The ALB installed using the Helm,

I tried to exec into the pod:
```
kubectl exec -i -t -n kube-system aws-load-balancer-controller-984bcf547-w4wbb -c aws-load-balancer-controller -- sh -c "clear; (bash || ash || sh)"```

But I also get a timeout. `Error from server: error dialing backend: dial tcp 192.168.115.243:10250: i/o timeout`

I really don't understand what is going on as we've not changed anything and suddenly our EKS cluster is feeling so broken.

**Comment by kishorj** [comment]
@OliverRC, webhooks require control plane to be able to access port 9443 on your worker nodes. Could you ensure your worker node SG configuration allows port 9443 from the k8s control plane?

**Comment by OliverRC** [comment]
Hi there, AWS support engineers have been through our whole networking stack and checked the EKS control plane backing our cluster and cannot see anything wrong.

There is definitely access from the control plane to the pods, and the pods are running on port 9443

**Comment by 0xF4D3C0D3** [comment]
I also bumped into this issue. I allowed 9443 port from cluster and am using aws-load-balancer-controller v2.4.6. There was about 5~15 seconds delay reflexing real state in AWS TargetGroup for my case.
