### ISSUE TITLE
Deregistration for TargetGroupBinding does not start immediately when  Pod is terminating

### ISSUE THREAD

**Issue by lcshiung** [kubernetes-sigs/aws-load-balancer-controller#3097]
**Describe the bug**
When using `TargetGroupBinding`, even when used together with the `preStop` lifecycle hook, and `terminationGracePeriodSeconds`, the deregistration of the Pod only starts after the Pod is terminated - ignoring the `preStop` lifecycle hook setting.

**Expected outcome**
When a Pod is due for termination, and the `preStop` hook triggered, the deregistration of the Pod should start immediately to allow connections to the Pod to be drained. This will allow graceful termination of connections in conjunction with the `preStop` lifecycle hook.

**Comment by kishorj** [comment]
@lcshiung, did you enable pod readiness gates?

**Comment by oliviassss** [comment]
@lcshiung I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks.
