### ISSUE TITLE
Vulnerabilities reported while scanning v2.4.6 and v2.4.7 images

### ISSUE THREAD

**Issue by kadirtaskiran** [kubernetes-sigs/aws-load-balancer-controller#3100]
**Describe the bug**
While scanning the v2.4.6 and v2.4.7 docker images of alb ingress controller we see following vulnerabilities.

![Screen Shot 2023-03-10 at 18 23 21](https://user-images.githubusercontent.com/3438508/224355247-ab926d00-bda2-43d9-a4f6-d2600735aef5.png)
![Screen Shot 2023-03-10 at 18 23 31](https://user-images.githubusercontent.com/3438508/224355282-073a4838-7167-4734-8623-13ef3571220a.png)

**Steps to reproduce**
Scan the image for vulnerabilities

**Expected outcome**
No vulnerabilities

**Environment**

* AWS Load Balancer controller version v2.4.6 and v2.4.7
* Kubernetes version 1.24.9
* Using EKS (yes/no), if so version? Yes

**Additional Context**:

Can someone please help me on how avoid this vulnerabilities
Thanks,
Kadir

**Comment by oliviassss** [comment]
Closing the issue as the Vulns have been addressed.
