### ISSUE TITLE
Unable to create controller - TargetGroupBinding error

### ISSUE THREAD

**Issue by dweinstein87** [kubernetes-sigs/aws-load-balancer-controller#3101]
When attempting to deploy the aws-load-balancer-controller via terraform and helm charts I receive the following error:
`{"level":"info","ts":1678476543.9496298,"msg":"version","GitVersion":"v2.4.7","GitCommit":"2ba14d1e232c1f2aa02063a3edd2ef855ba468d9","BuildDate":"2023-02-23T07:33:14+0000"}
{"level":"info","ts":1678476543.9995778,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"error","ts":1678476544.0298407,"logger":"setup","msg":"unable to create controller","controller":"TargetGroupBinding","error":"no matches for kind \"TargetGroupBinding\" in version \"elbv2.k8s.aws/v1beta1\""}
`
A concise description of what the bug is.
I have updated my charts and I am deploying with Helm 3 but continue to receive this error on deploy

**Expected outcome**
The aws load balancer controller deploys normally

**Environment**
AWS

* AWS Load Balancer controller version: v2.4.7
* Kubernetes version: 1.23
* Using EKS (yes/no), if so version? Yes eks.6

I have reviewed [issue 495](https://github.com/aws/eks-charts/issues/495) have have made sure I am using the newest charts, container image, and updated the necessary apis.

**Comment by dweinstein87** [comment]
Resolved

**Comment by hrishinan** [comment]
solution?

**Comment by s-jeon-mercury-inc** [comment]
how can i fix? @dweinstein87

**Comment by dweinstein87** [comment]
I was trying to run the charts from a local repo. Running this command was the manual fix and I updated the Helm chart to to point to the public repo instead and it works.

`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master" `
