### ISSUE TITLE
How to check ingress log on AWS？

### ISSUE THREAD

**Issue by zibuyule** [kubernetes-sigs/aws-load-balancer-controller#3102]
When I created an ingress resource as follows, I got 502 when I accessed it in the browser.
And I access it from another pod  within kubernetes and it seems to be working normally.
![keycloak-error](https://user-images.githubusercontent.com/5792519/224473219-15622d84-de05-4bf3-a28b-55269deb0877.png)

![pod](https://user-images.githubusercontent.com/5792519/224473542-7fd76f37-4696-4914-831b-214ebc466cd5.png)

How can I check for this error?

First, I tried checking the logs of pod: aws-load-balancer-controller-79f55f66d6-rvkwn. 
It looks like it only prints the logs for creating the AWS ALB.

![aws-load-balancer-controller log](https://user-images.githubusercontent.com/5792519/224473133-3b486e3d-935c-4ea1-9503-55637044914e.png)

So where do I go to check the access logs?

Thanks!

**Comment by oliviassss** [comment]
Hi can you check if the target groups are up and healthy? You can go to AWS console, EC2 -> Target Groups and click on the corresponding TG.

**Comment by kishorj** [comment]
@zibuyule, you could enable access logs on your ALB, and get the logs from S3. For details, please refer to setting the load balancer attributes: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#load-balancer-attributes

**Comment by ArjunDandagi** [comment]
I have a feeling that you are using ALB and ingress resources . but the service is ClusterIP and you are not using aws VPC CNI

**Comment by oliviassss** [comment]
@zibuyule, I'm closing the issue as for now, please feel free to reach out or reopen if you have more questions. Thanks
