### ISSUE TITLE
re-attach LB after service restore by changing UID ?

### ISSUE THREAD

**Issue by grosser** [kubernetes-sigs/aws-load-balancer-controller#3103]
**Is your feature request related to a problem?**
I want to backup a cluster to yaml and than restore from yaml without re-creating the LB.

Workflow: `get svc -o yaml > file`, shut down cluster, bring up new cluster, `apply -f file`
and have the LB work again

but the controller always delete the LB after I apply and then creates a new LB

**Describe the solution you'd like**
I think this comes from the controller using the service metadata.uid to identify the LB
so if we can allow that to be overwritten by for example `metadata.annotations.aws-controller-uid=UID`
then I should be able to re-attach my service the the existing LB

**Describe alternatives you've considered**
Restoring from etcd backup, but that does not work on EKS.

**Comment by oliviassss** [comment]
@grosser we have feature request regarding reusing LBs - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/228, https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2638.
Right now you can label the existing LBs properly for the controller to pick it up, but it's a bit hacky, you can refer to this [thread](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/228#issuecomment-1239493874) and our [live doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#resource-tags).

**Comment by grosser** [comment]
thx! will give that a try!

**Comment by kishorj** [comment]
@grosser, controller uses resource tags to identify NLB corresponding to a given service. As long as you keep the service name/namespace and cluster name the same, controller will be able to pickup the existing LB.

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#aws-resource-tags

**Comment by grosser** [comment]
thanks, I need to update to latest and try this ... did not work with our old version 🤞

**Comment by oliviassss** [comment]
@grosser, I'm closing this issue as of now, please feel free to reach out or reopen if you have any questions. Thanks

**Comment by grosser** [comment]
this seems to not work at all since the service UID is hardocded to be in the model
so a LB could never be reused by another serivce

**Comment by grosser** [comment]
the LB name that is generated has the format internal-a + service-UID-without-dashes + some sha
`internal-a13e9269f72444980bcf20b26e9e33bf-518807424.us-west-2.elb.amazonaws.com`
nothing in the codebase looks like this ...
the only thing I could find is "k8s-%.8s-%.8s-%.10s" and similar references

also dug through the codebase and found the lb matching logic, but did not find any place where it actually uses the service UID to match services against existing lbs

**Comment by grosser** [comment]
this might be a dead end ... the LB seems to be managed by the controller-managers aws.go and not this repo ...
