### ISSUE TITLE
helm upgrade of lbc replaces working network load balancers nlbs causing downtime

### ISSUE THREAD

**Issue by dustyketchum** [kubernetes-sigs/aws-load-balancer-controller#3105]
**Describe the bug**
`helm upgrade` replaces working network load balancers nlbs

**Steps to reproduce**
Following instructions here:
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
1. Create a load balancer controller service account.
2. Install load balancer controller using helm.
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=my-cluster \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller 
3. Create an NLB using kubernetes
4. helm repo update
5. Install updated CRDs for newer version of LBC such as 2.4.7 (this is best practice, but doesn't seem to matter for this issue):
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
6. Upgrade the load balancer controller using helm.
helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=my-cluster \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller
7. From the pod logs, we can see that the upgraded load balancer controller then
"successfully built model",
"created targetGroup"
"created loadBalancer",
"created listener,
"created targetGroupBinding",
"deleting targetGroupBinding",
"deRegistered targets",
"registered targets",
"deleted targetGroupBinding",
"successfully deployed model"
8. We now have a service outage since our NLB was replaced.

**Expected outcome**
The load balancer controller should recognize the existing network load balancer without replacing it, OR the documentation should be updated to reflect that upgrading the load balancer controller requires downtime and is destructive. Functionality of 'helm upgrade' seems to be more like a fresh install, it doesn't upgrade maintain existing infrastructure, it replaces it.

**Environment**
AWS LBC 2.4.2 was upgraded to 2.4.7
EKS 1.24

**Additional Context**:

**Comment by oliviassss** [comment]
The helm upgrade creates new pods and removes old pods, which may cause downtime. However, you can have liveness and readiness probe to have the helm to delete the old pods after the new ones are up and running. We support [Pod Readiness Gate](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/pod_readiness_gate/#pod-readiness-gate) for `target-type: ip`, can you check if the Pod Readiness Gate is configured properly on the namespace of the NLB?

**Comment by dustyketchum** [comment]
Hi @oliviassss, thanks for the reply
`The helm upgrade creates new pods and removes old pods, which may cause downtime` - I assume you are referring to the load balancer controller pods in the kube-system namespace here, which is also what I'm referring to above.

We do have liveliness and readiness probes enabled on the application, and they appear to be working as expected, and we can see them when we use `kubectl get pods -A -o wide` - it takes up to 5 minutes for a new pod to attach itself to the NLB target.  However this doesn't help with the load balancer controller upgrade and isn't relevant to my question if I am understanding correctly.  Upgrading the load balancer controller only replaces the load balancer pods, not our application pods, the application pods are re-registered with the new load balancer per the "deRegistered targets", "registered targets" steps found in our logs above.

**Comment by M00nF1sh** [comment]
the controller upgrade shouldn't replace NLB. Did you modified settings such as "clusterName" during your upgrade?
The NLBs is tags and identified by the clusterName and Service name. So if there is no change to clusterName and ServiceName, it won't be replaced.

Would you help check your cloudtrails as well to see whether there are aws tag changes?

**Comment by dustyketchum** [comment]
Thanks for the reply @M00nF1sh .  We didn't change the clustername or any other settings that I'm aware of.  
Looking at the current NLBs, the only 3 tags are for:
elbv2.k8s.aws/cluster [clustername]
service.k8s.aws/resource LoadBalancer
service.k8s.aws/stack [namespace/servicename]

To re-test this, I helm uninstalled the lbc, then helm installed 2.4.2 again with:

helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=clustername \
  --version=1.4.2 \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller

Next I brought up our service which created the NLB.
I then helm upgraded to current while the service was running, this time it didn't change the NLB.
I don't see anything in Cloudtrail that looks related.
