### ISSUE TITLE
Supporting multiple port 80/443 TargetGroupBinding for different tenants/brands.

### ISSUE THREAD

**Issue by gencube** [kubernetes-sigs/aws-load-balancer-controller#3106]
**Describe the bug**
Since K8s/EKS is a multiple namespaced environment(custA, custB), it should naturally support multiple brands(custA-echo, custB echo) using port 80/443. CloudFront / CloudFlare can mapped to these ports.

**Steps to reproduce**
Repeat this for different namespace for custA and custB hashicorp http-echo deployed in different K8s/EKS namespaces.
https://github.com/hashicorp/http-echo

See: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/targetgroupbinding/targetgroupbinding/
 
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-tgb
spec:
  serviceRef:
    name: awesome-service # route traffic to the awesome-service
    port: 80
  targetGroupARN: <arn-to-targetGroup>

**Expected outcome**
**Ability to support multi-namespaces that use the same service port on 80/443, since K8s/EKS can support such ingress mapping.**

**Environment**
* AWS Load Balancer controller version = 2.4.5 /  helm chart: 1.4.6
* Kubernetes version:  v1.24.8-eks-ffeb93d
* Using EKS (yes/no), if so version? yes

**Additional Context**:
Deployed using helm chart 1.4.6:  
- https://aws.github.io/eks-charts
- https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller

---
helm repo add eks https://aws.github.io/eks-charts
helm install aws-load-balancer-controller eks/aws-load-balancer-controller --set clusterName=my-cluster -n kube-system

**Comment by kishorj** [comment]
@gencube, could you clarify your requirements further?
Are you looking for multiple targetgroupbinding for the same AWS target group?
