### ISSUE TITLE
 TargetGroupBinding  resource add ownerReferences  metadata

### ISSUE THREAD

**Issue by w564791** [kubernetes-sigs/aws-load-balancer-controller#3108]
Is your feature request related to a problem?
A description of what the problem is. For example: I'm frustrated when [...]
I want delete my ingress resources and delete the associated targetGroup resoreces both.
Describe the solution you'd like
A description of what you want to happen.
When I delete the ingress resource, but the associated targetGroupbindings resource cannot be deleted automatically, a large number of “None associated” targetGroups in my aws account.
Describe alternatives you've considered
Manually delete the targetGroupbindings resource?
A description of any alternative solutions or features you've considered.
I think that the TargetGroupBinding resource needs ownerReferences metadata, and when the ingress resource is deleted, the associated TargetGroupBinding resource is automatically cleaned up

**Comment by kishorj** [comment]
@w564791, when you delete the ingress resources, the controller will cleanup the associated TargetGroupBinding resources as well.  Do you see any errors in the controller logs related to cleaning up the corresponding AWS resources?

Do you have a specific reason to require the ownerReferences since controller is already doing the cleanup automatically.

**Comment by w564791** [comment]
> 

Hi kishorj ,thanks for your reply,
I did the test again,
1.
[root@monitor-tools ec2-user]# kubectl  get targetgroupbinding                                                                                                                        
NAME                              SERVICE-NAME            SERVICE-PORT   TARGET-TYPE   AGE                                                                                            
k8s-default-kunlunfl-2b19994ee8   kunlun-flink-pre-cal    8081           ip            6d   
2. 
[root@monitor-tools ec2-user]# kubectl  get ing                                                                                                                                       
NAME                    CLASS    HOSTS                       ADDRESS   PORTS   AGE                                                                                                                                                                                              
kunlun-flink-pre-cal    <none>   *.com                                 80      6d   
3.
kubectl  get ing  kunlun-flink-pre-cal -o yaml >kunlun-flink-pre-cal .yaml
kubectl  delete -f kunlun-flink-pre-cal .yaml
4.because of the "finalizers", I need to delete the field to finish ing delete action
5.
[root@monitor-tools ec2-user]# kubectl  get targetgroupbinding                                                                                                                        
NAME                              SERVICE-NAME            SERVICE-PORT   TARGET-TYPE   AGE                                                                                            
k8s-default-kunlunfl-2b19994ee8   kunlun-flink-pre-cal    8081           ip            6d   

the targetgroupbinding still exists

**Comment by sftim** [comment]
`ownerReferences` allows for [cascading deletion](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#cascading-deletion) even if the controller is unhealthy or has been removed. It's a handy feature.

**Comment by oliviassss** [comment]
@w564791, I'm closing this issue as of now, please feel free to reach out or reopen if you have any questions. Thanks
