### ISSUE TITLE
[Feature request] - Support for multiple VPCs on a single installation of the controller

### ISSUE THREAD

**Issue by rodrigorfk** [kubernetes-sigs/aws-load-balancer-controller#3109]
**Is your feature request related to a problem?**

The PR #1862 merged on version `v2.3.1` has introduced initial support for multiple VPCs, however it does not allow a true mesh of VPCs to be used on a single installation of the controller, let me explain it a bit further:

- **What is provided there out of the box right now**:
  - You can have the controller deployed on a Kubernetes cluster in one VPC (let's call it `vpc-a`), this is the VPC where the controller pod and all application pods are going to run, assuming that you are using the `amazon-vpc-cni`, those Pods are going to get IPs from `vpc-a` CIDR range.
  - You can have all LBs managed by the controller or TargetGroups managed externally on a single different VPC (let's call it `vpc-b`) , the `vpc-b` ID must be provided on the `--aws-vpc-id` controller argument, and all the LBs managed by the controller are going to be created in that `vpc-b`
  - You won't be able to get LBs managed by the controller on the `vpc-a` where the controller and the EKS cluster is running.
  - You can only use external managed TargetGroups, via the `TargetGroupBinding` CRD, with TGs for the `vpc-b`.

- **What I would like to have**:
  - You can have the controller deployed on a Kubernetes cluster in one VPC (let's call it `vpc-a`), this is the VPC where the controller pod and all application pods are going to run, assuming that you are using the `amazon-vpc-cni`, those Pods are going to get IPs from `vpc-a` CIDR range.
  - You want the LBs managed by the controller to be created on the `vpc-a` where the controller is running.
  - You want that TargetGroups managed externally on multiple different VPCs (let's call it `vpc-b`, `vpc-c`, `vpc-n`) could have their TargetGroups managed by the controller, via the `TargetGroupBinding` CRD, by having Pods (in IP mode) registered to it by the Controller.
  - You want to have a single installation of the controller, avoiding administration overhead and resource consumption introduced by running multiple deployments of the controller.

**Describe the solution you'd like**
From a implementation perspective, I believe the change is quite simple and I actually already have a patched version of the controller providing such solution running for more than a year in my company. The change is on how the `registerPodEndpoints` function [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/edb5e9921352d8e68f613fda4d1b5581aaf05efe/pkg/targetgroupbinding/resource_manager.go#L373) deal with the VPC id, instead of using the controller level `m.vpcID`, we have introduced a new `targetGroupInfoProvider` which resolves the VPC id from the incoming `tgARN`, allowing the controller to work with TGs from any VPC.

**Describe alternatives you've considered**
I haven't considered any alternative apart of running multiple installations of the controller, the solution described above is working quite well for us and I would be happy to open a Pull Request, sharing the implementation we are using internally.

**Comment by rodrigorfk** [comment]
I've notice just now that similar issue was reported in #3084 and a fix is in progress at #3085 .

**Comment by sebltm** [comment]
We needed to implement this internally, so I have a private fork that fixes by adding an annotation to the service to indicate in which VPC/Subnet the Load Balancer should be created
