### ISSUE TITLE
Single Ingress with Mutliple Backend Protocol Version(per Target Group)

### ISSUE THREAD

**Issue by indranilvyasFlipp** [kubernetes-sigs/aws-load-balancer-controller#3110]
**Is your feature request related to a problem?**
At the moment add two services as a backend to Ingress resource and Controller creates two target groups with the same  backend version protocol when using this annotation `alb.ingress.kubernetes.io/backend-protocol-version: 'HTTP2'` 

**Describe the solution you'd like**
ability to define Target Group protocol version per Backend Service

**Describe alternatives you've considered**
For now, we have to create separate Ingress resources with desired backend protocol for each backend service

**Comment by kishorj** [comment]
@indranilvyasFlipp, you could specify the annotation in the backend service instead of the ingress. The annotation on the service takes precedence over the one in the ingress.

**Comment by indranilvyasFlipp** [comment]
@kishorj 
My backend service is Istio Ingress Gateway with NodePort exposing HTTP/1 and GRPC ports, can I add two backend protocol version annotation per port exposed on the NodePort service

**Comment by kishorj** [comment]
@indranilvyasFlipp, you can't do it on a single service, you will have to split it into two NodePort services.

**Comment by oliviassss** [comment]
@indranilvyasFlipp, I'm closing this issue as of now, please feel free to reach out or reopen if you have any questions. Thanks
