### ISSUE TITLE
Auto-generated cert-manager certificate expires after 90 days causing AWS Load Balancer Controller failure

### ISSUE THREAD

**Issue by miquelaws** [kubernetes-sigs/aws-load-balancer-controller#3111]
**Is your feature request related to a problem?**
Yes. When you install the AWS Load Balancer Controller using [this instructions](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/#add-controller-to-cluster) via YAML manifests, you need to install cert-manager that uses an auto-generated certificate. That certificate expires after 90 days, causing Controller failure if you don't manage that expiration.

**Describe the solution you'd like**
I suggest creating a note in the documentation, with a reminder/disclaimer saying this should be taken into account. 

**Describe alternatives you've considered**

**Comment by kishorj** [comment]
@miquelaws, the cert-manager should automatically refresh the expiring certs. Did it not work in your case? You need to have the cert-manager running in your cluster.

**Comment by runningman84** [comment]
In our case for some unknown reason the certifcate object aws-load-balancer-serving-cert got missing after some time. This causes certificates to expire....

**Comment by oliviassss** [comment]
@runningman84 which version of cert-manager did you install? Could it be related to the issue discussing in cert-manager community? https://github.com/cert-manager/cert-manager/issues/4754

**Comment by oliviassss** [comment]
@miquelaws, I'm going to close the issue as for now, please feel free to reach out or reopen if you have any questions, thanks.
