### ISSUE TITLE
Not all logs are in JSON

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-sigs/aws-load-balancer-controller#3112]
**Describe the bug**
While most logs that come out of the controller are in JSON format, there are occasionally log messages that come out *not* in json format.

e.g. obtaining the leader lease
```
I0322 03:29:44.771866       1 leaderelection.go:243] attempting to acquire leader lease aws-load-balancer-controller/aws-load-balancer-controller-leader...
```

**Steps to reproduce**
restart a running controller and look at the logs

**Expected outcome**
all logs should be in json format

**Environment**

* AWS Load Balancer controller version: 2.4.6
* Kubernetes version 1.26.1
* Using EKS (yes/no), if so version? no

**Additional Context**:

**Comment by M00nF1sh** [comment]
some logs are from the controller-runtime, we'll see whether there is ways to redirect the log streams and rewrite it in golang

**Comment by Almenon** [comment]
Do you know what the significance of the I0606  / E0606 at the start of the log is? I googled around but didn't find anything.
