### ISSUE TITLE
Topology spread support across AZs

### ISSUE THREAD

**Issue by akendler** [kubernetes-sigs/aws-load-balancer-controller#3118]
**Is your feature request related to a problem?**
For HA workloads, it is a best practice to use topology spread to spread the workload pods between AZs to protect against AZ failure. with CAS, the current option is to have multiple replicas on different hosts, which may reside in the same AZ. Should the AZ fail, the controller will be offline for some time, before the cluster responds with creating additional replicas.

**Describe the solution you'd like**
Add topology spread options to the deployment/helm chart, to allow customers to spread using the zone key.

**Comment by ArjunDandagi** [comment]
interested in taking this up . if accepted.
