### ISSUE TITLE
Log message for conflicting SSL policy lists the same ingress name twice

### ISSUE THREAD

**Issue by jbg** [kubernetes-sigs/aws-load-balancer-controller#3125]
**Describe the bug**
When two ingresses in the same group have conflicting SSL policies, the log message lists the same ingress twice, making it more difficult to determine the source of the conflict.

**Steps to reproduce**
Create two ingresses, `first-ingress` and `second-ingress` sharing the same group but with different SSL policies.

The resulting error looks like:

```json
{"level":"error","ts":1679760043.6535313,"logger":"controller.ingress","msg":"Reconciler error","name":"ingress-group-name","namespace":"","error":"failed to merge listenPort config for port: 443: conflicting sslPolicy, default/first-ingress: ELBSecurityPolicy-TLS-1-2-2017-01 | default/first-ingress: ELBSecurityPolicy-TLS13-1-2-2021-06"}
```

Note that `first-ingress` is referenced alongside both SSL policies.

**Expected outcome**
An error listing the two different ingress names which have the conflicting SSL policies.

**Environment**

* AWS Load Balancer controller version: 2.4.7
* Kubernetes version: 1.25
* EKS version: 1-25-eks-9

**Additional Context**:

The errant code is presumably [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/ingress/model_builder.go#L324).

**Comment by kishorj** [comment]
/kind bug

@jbg, thanks for reporting, we will investigate further and fix.
