### ISSUE TITLE
Service Type: Load Balancer does not appear to work.

### ISSUE THREAD

**Issue by jseiser** [kubernetes-sigs/aws-load-balancer-controller#3130]
**Describe the bug**
Creating a NLB from a servicetype Load Balancer does not appear to actually pass traffic.

**Steps to reproduce**
1. Install AWS LB Controller
2.  Create NLB for a Service Type Load Balancer

**Expected outcome**
Sending traffic to the NLB should reach the pod.

**Environment**

* AWS Load Balancer controller version v2.4.7
* Kubernetes version 1.25
* Using EKS (yes/no), if so version? 1.25

**Additional Context**:
Attempting to expose a ActiveMQ Server.  Using the service directly works without issue. The NLB creates, their is a healthy target, but traffic does not appear to actually get to the pod.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: amq-stomp-jls-dev.trex.network
    meta.helm.sh/release-name: amq-jls-dev
    meta.helm.sh/release-namespace: jls-dev
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: external
  creationTimestamp: "2023-03-29T19:56:17Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  - service.k8s.aws/resources
  labels:
    app.kubernetes.io/instance: amq-jls-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: amq
    app.kubernetes.io/version: v0.1.2
    helm.sh/chart: amq-0.2.3-alpha_5fdd6288
    ingress: externaldns
  name: amq-jls-dev-stomp
  namespace: jls-dev
  resourceVersion: "11077620"
  uid: 2b69cd8c-bcce-479c-a18f-537518e7a844
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.113.169
  clusterIPs:
  - 172.20.113.169
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: stomp
    nodePort: 32178
    port: 61613
    protocol: TCP
    targetPort: stomp
  selector:
    app.kubernetes.io/instance: amq-jls-dev
    app.kubernetes.io/name: amq
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxxx.elb.us-gov-west-1.amazonaws.com
```

Attempting to use the NLB.  I am inside the VPC, so the internal NLB is not an issue.

```
❯ pipenv run python -m stomp -V -H xxxx.elb.us-gov-west-1.amazonaws.com -P 61613
Sending {cmd=STOMP,headers=[{'accept-version': '1.1'}],body=}
```

Nothing happens, no indication on the POD any traffic reached it.

Doing a port forward to the service itself works.

```
❯ kubectl port-forward --namespace=jls-dev service/amq-jls-dev-stomp 61613:61613
Forwarding from 127.0.0.1:61613 -> 61613
Forwarding from [::1]:61613 -> 61613

❯ pipenv run python -m stomp -V -H localhost -P 61613
Sending {cmd=STOMP,headers=[{'accept-version': '1.1'}],body=}
CONNECTED
server: ActiveMQ/5.17.4
heart-beat: 0,0
session: ID:amq-jls-dev-0-40181-1680119782233-3:411
version: 1.1
```

I can also see the NLB creation, updated the node's secgrp to allow port `32178` in. So its not a sec. group issue either.

**Comment by kishorj** [comment]
@jseiser, do you see the TCP connection establish at all? or you see the SYN timeout.
Could you also verify whether the egress traffic to port 61613 from your client is permitted? 

Since your NLB target group targets are healthy, I suspect the issue is between your client and the NLB frontend.

**Comment by jseiser** [comment]
@jseiser 

> Could you also verify whether the egress traffic to port 61613 from your client is permitted?

All egress traffic is permitted.

```
❯ nc -z -v amq-svc-jls-dev.trex.network 61613
Connection to amq-svc-jls-dev.trex.network (10.1.3.82) 61613 port [tcp/*] succeeded
```

**Comment by jseiser** [comment]
I was able to make this work using these settings

```
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.type=source_ip
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
```

**Comment by jseiser** [comment]
I wanted to follow up. It actually doesnt work long term. Sometimes it sends traffic, other times it does not appear traffic reaches anything.

This should be a workable setup, considering AWS offers ActiveMQ, behind a NLB.
