### ISSUE TITLE
Support both gRPC and HTTP2 webpages on the same service

### ISSUE THREAD

**Issue by Dunge** [kubernetes-sigs/aws-load-balancer-controller#3133]
**Is your feature request related to a problem?**
I'm having a ASP.NET Core web service (net6) hosting both a gRPC service and webpages (MVC) on an HTTP2 endpoint. It use the exact same URL for both.

When using nginx-ingress, I can add this annotation to the ingress resource:
```
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
```
And both work fine. (Except one minor problem with the host header: https://github.com/kubernetes/ingress-nginx/issues/8843)

I decided to try using ALB ingress instead if it would work with this header problem. Using these annotation and of course the alb ingress class name:
```
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.AwsCertificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
```

With this an application load balancer get created, and the gRPC service works perfectly.
Unfortunately, when visiting the URL from a web browser, I receive an `464 No Reason Phrase` in my browser and I see the log `Service 'AWS.ALB' is unimplemented.` appearing on my web server. As if it try to use a gRPC service that would be called AWS.ALB instead of routing to the webpage.

Anyone can shed some light on if this is possible (without having the web server listening on different sub paths?)

**Comment by Dunge** [comment]
Ok, I by switching the `backend-protocol-version` from GRPC to HTTP2 it seems to work for both.
Looking at the ALB target creation:

![image](https://user-images.githubusercontent.com/6548184/229219695-b74f6b1b-7156-41fb-94a0-a8400dbc1794.png)

I'm wondering what are those "gRPC-specific features" that might not be supported?

**Comment by M00nF1sh** [comment]
@Dunge you might cut a support ticket to ELB team on the specific unsupported features

**Comment by Dunge** [comment]
Seeing how [ALB doesn't support converting HTTP1 request to HTTP2 backend](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#target-group-protocol-version), I'll not be using it.
