### ISSUE TITLE
After the main pod restart - flush NLB listeners

### ISSUE THREAD

**Issue by PLeS207** [kubernetes-sigs/aws-load-balancer-controller#3134]
Hello team, I am faced with the issue 
I'm using NLB load balancer, which was created via nginx-ingress helm chart, Problem is that I want to use multiple services with multi ports and NLB doesn't support this configuration, because of this I add manually (via terraform) the necessary targets groups and add necessary listeners, everything work correctly, but when I restart main pod of aws-load-balancer-controller it automatically deletes all my configured listeners. Can I somehow prevent the deletion of my listeners from NLB ? or maybe you suggest another approach to how I can use NLB with multi services?

**Comment by oliviassss** [comment]
@PLeS207, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks
