### ISSUE TITLE
[Helm] v1.4.8 (app version 2.4.7) does not include RBAC for leases

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/aws-load-balancer-controller#3143]
**Describe the bug**
helm chart v1.4.8 does not have permission to create leases.
```
error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:kube-system:k8s-aws-load-balancer-controller" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

**Steps to reproduce**
- `❯ helm template k8s --version=1.4.8 --set clusterName=my-cluster -n kube-system k8s/aws-load-balancer-controller | grep leases`
- verify that no output

**Expected outcome**
- Role includes the leases permission

**Environment**

* AWS Load Balancer controller version 2.4.7
* Kubernetes version 1.24
* Using EKS (yes/no), if so version? no

**Additional Context**:

**Comment by a7i** [comment]
The changes on main branch have leases so seems like something wrong with the release

**Comment by kishorj** [comment]
@a7i, you need to upgrade to helm chart 1.5.2 or later. I'm closing the issue.
