### ISSUE TITLE
alb controller fails to discover certificate when there are multiple certificates for the same host

### ISSUE THREAD

**Issue by Anagabsoares** [kubernetes-sigs/aws-load-balancer-controller#3148]
According to this [thread](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3028)  the alb controller should be able to discover a certificate even when there are multiple certificates for the same host. However, I am still getting the error: `Failed build model due to ingress: app98/eks-sample-app-test: multiple certificates found for host: <host_name>`. Did the changes make it through? 

the image being used: `public.ecr.aws/eks/aws-load-balancer-controller:v2.4.7`

**Comment by kishorj** [comment]
@Anagabsoares, this enahcement will be available in the upcoming v2.5.0 release, we are almost there.

**Comment by kishorj** [comment]
we just released v2.5.0, closing the issue.
