### ISSUE TITLE
Create NLB which will pass 443 communication to ALB

### ISSUE THREAD

**Issue by VladoDzamba** [kubernetes-sigs/aws-load-balancer-controller#3150]
I want to create NLB which will pass 443 communication to ALB. Same as is described [here](https://aws.amazon.com/blogs/networking-and-content-delivery/application-load-balancer-type-target-group-for-network-load-balancer/).

I found annotation for ALB which is pointing to target group directly. Does exist something similar for NLB?

`alb.ingress.kubernetes.io/actions.forward-single-tg: {"type":"forward","targetGroupARN": "arn:aws:elasticloadbalancing:eu-west-2:566853649351:targetgroup/robo-alb/890600825486edfd","servicePort":443}`

**Comment by M00nF1sh** [comment]
We currently don't support configure such setup from this controller. You have to setup the NLB through external tools and configure it with a ALB target with ALB provisioned by this controller.
There are some on-going community effort like https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2379 that trying to add such feature

**Comment by oliviassss** [comment]
@VladoDzamba, I'm closing this issue as for now, please feel free to reach out or reopen if you have any questions. Thanks
