### ISSUE TITLE
Deploying on Cluster with IMDSv2 enforced causes crashes

### ISSUE THREAD

**Issue by vpineda1996** [kubernetes-sigs/aws-load-balancer-controller#3155]
**Describe the bug**
When I launch a worker node running on the EKS AMI on a 1.26 EKS cluster, I install the Load Balancer controller through the EKS provided helm chart, the controller fails to start. Disabling IMDSv2 enforcement fixes the issue.

```
bash-4.2# k logs -n kube-system aws-load-balancer-controller-86b7bcf755-5vqxn
{"level":"info","ts":"2023-04-14T23:45:23Z","msg":"version","GitVersion":"v2.5.0","GitCommit":"14f5a70b3319d5ab141aee9893bbb425c9a55958","BuildDate":"2023-04-14T17:30:51+0000"}
{"level":"error","ts":"2023-04-14T23:45:26Z","logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: EC2MetadataError: failed to make EC2Metadata request\n\n\tstatus code: 401, request id: "}
```

**Steps to reproduce**

1. Create a 1.26 cluster
2. Create a worker node with IMDSv2 enforced
3. Install helm chart
```
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
-n kube-system \
--set clusterName=$CLUSTER_NAME \
--set serviceAccount.create=true \
--set enableShield=false \
--set enableWaf=false \
--set enableWafv2=false
```
4. Look at logs

**Environment**

* AWS Load Balancer controller version: latest in helm chart
* Kubernetes version: 1.26
* Using EKS (yes/no), if so version? Yes 1.26

**Additional Context**:

**Comment by kishorj** [comment]
With IMDSv2, you need to setup IRSA and set the helm value `region` and  `vpcId`.

You could also set the IMDSv2 hop count to 2, but this is an insecure option.

**Comment by vpineda1996** [comment]
Should the controller log out those instructions? I think it might be something a lot of people might struggle to find.

**Comment by oliviassss** [comment]
@vpineda1996 Hi, please check our live doc for the instruction on IMDSv2: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/installation/#using-the-amazon-ec2-instance-metadata-server-version-2-imdsv2

**Comment by alegermer** [comment]
Thanks @kishorj  and @oliviassss, I have tested both the `--http-put-response-hop-limit 2` and adding the `--set region=<region> --set vpcId=<vpc-id>` to the helm chart and both ways have worked. IRSA does not seem to be required for it to work.

However, I don't see further information regarding the insecure concerns of the IMDSv2 hop count @kishorj mentioned, could you please clarify the risk here?

**Comment by oliviassss** [comment]
@alegermer, the larger the hop limit, the more redirects the instance metadata requests can travel. you can check more infos here:https://aws.github.io/aws-eks-best-practices/security/docs/iam/#update-the-aws-node-daemonset-to-use-irsa

I'm closing the issue as for now, please feel free to reach out or reopen if you have more questions. Thanks
