### ISSUE TITLE
Existing load balancer subnets should be reconciled if subnet tags are updated

### ISSUE THREAD

**Issue by jukie** [kubernetes-sigs/aws-load-balancer-controller#3157]
**Is your feature request related to a problem?**
Related to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2930
It is a frequent occurrence that users modify subnets where worker nodes operate and also add tags to the corresponding subnets for the AWS Load Balancer Controller. However, since the Load Balancer Controller doesn't manage this aspect, cluster operators are responsible for either rolling the load balancers or updating them in-place to apply the subnet changes. This feature is necessary because a service pod could be deployed in the new subnet, but it wouldn't be able to receive traffic from the load balancer.

**Describe the solution you'd like**
aws-lb-controller should check for subnet updates and reconcile existing load balancers. The default action could be similar to the approach taken by external-dns's upsert-only mode and only add new subnets to the lb's vs removing them if tags are removed.

**Describe alternatives you've considered**
Before adding a new subnet for worker nodes, manually rotate/update all existing lb's.

**Comment by sosheskaz** [comment]
/remove-lifecycle stale

I also have this issue.

**Comment by sosheskaz** [comment]
2.6.0 did not fix this behavior for me.
