### ISSUE TITLE
error retrieving resource lock kube-system/aws-load-balancer-controller-leader

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#3164]
**Describe the bug**
public.ecr.aws/eks/aws-load-balancer-controller:v2.5.1

[aws-load-balancer-controller-d7bbf8bf9-5bbcx] E0419 06:55:25.634099       1 leaderelection.go:330] error retrieving resource lock kube-system/aws-load-balancer-controller-leader: leases.coordination.k8s.io "aws-load-balancer-controller-leader" is forbidden: User "system:serviceaccount:kube-system:aws-alb-sa" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"

**Steps to reproduce**

**Expected outcome**
No error in the log.

**Environment**

* AWS Load Balancer controller version 2.5.1
* Kubernetes version 
* Using EKS (yes/no), if so version? yes
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8", GitCommit:"0ce7342c984110dfc93657d64df5dc3b2c0d1fe9", GitTreeState:"clean", BuildDate:"2023-03-30T17:29:41Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.8-eks-ec5523e", GitCommit:"83fe90de881ffe7450876d204ccdc37a0f95bda3", GitTreeState:"clean", BuildDate:"2023-03-20T21:32:06Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```
**Additional Context**:

**Comment by kishorj** [comment]
@khteh, the new image is not compatible with the v2.4.x and older manifests. You either need to do a helm upgrade or apply the new manifest. The v2.5.x controller requires permission to `leases` resources which is not included in the prior ones.
