### ISSUE TITLE
Time format aws-load-balancer-controller

### ISSUE THREAD

**Issue by marcin-kasinski** [kubernetes-sigs/aws-load-balancer-controller#3166]
Image version:

aws-load-balancer-controller:v2.4.2

Installed from chart:

  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  version    = 1.4.2

How can I set ts log format 

{"level":"info","ts":1681991553.1140616,"msg":"

When I send these logs to EKS, they are rejected by the ts field format.

I would like to change this field to for example 2023/04/20 13:55:48.

**Comment by kishorj** [comment]
@marcin-kasinski, this is available in the latest release v2.5.x. You need to update to chart version 1.5.2

**Comment by marcin-kasinski** [comment]
@kishorj ok I will do it.

Can you explain how in this newer version I can change the format of the logs?

**Comment by kishorj** [comment]
v2.5 displays the human readable timestamp by default, you just need to upgrade.
