### ISSUE TITLE
Failed deploy model due to DuplicateLoadBalancerName

### ISSUE THREAD

**Issue by vb3328998** [kubernetes-sigs/aws-load-balancer-controller#3173]
**Describe the bug**
A concise description of what the bug is.
I manually created an ALB and wanted to specify it using LBC. The error was as follows: "Failed deploy model due to DuplicateLoadBalancerName: A load balancer with the same name 'k8s test alb1' exists, but with different settings

status code: 400, request id: 92932165-d47c-44ba-af06-8e11a4e7484c"

**Steps to reproduce**
add ALB and LBC use
**Expected outcome**
A concise description of what you expected to happen.
Successfully reconciled
**Environment**
k8s
* AWS Load Balancer controller version
v2.5.1
* Kubernetes version
* Using EKS (yes/no), if so version?
yes,1.24
**Additional Context**:

**Comment by M00nF1sh** [comment]
@vb3328998 
Did you used the [`alb.ingress.kubernetes.io/load-balancer-name` annotation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/annotations/#load-balancer-name) on your Ingress?
It appear you have another Ingress specified same load-balancer-name. You should give each Ingress a different name if you use that annotation, we currently don't have validations around that.

You can goto your EC2 console, find that load balancer, and check the AWS Tags to see what's the existing Ingresses that also uses the name.

**Comment by oliviassss** [comment]
@vb3328998, Hi I'm closing this issue for now, please feel free to reach out or reopen if you have any questions. Thanks
