### ISSUE TITLE
Provide a FIPS version of this image (compiled against BoringCrypto Go)

### ISSUE THREAD

**Issue by mamccorm** [kubernetes-sigs/aws-load-balancer-controller#3179]
**Is your feature request related to a problem?**
Sort of - For anyone who might want to run this within an environment requiring FIPS 140-2 (such as FedRAMP), this would need to be compiled against BoringCrypto Go.

Since go v1.19 it is actually very simple to do this, by adding the build argument 'GOEXPERIMENT=boringcrypto'. 

**Describe the solution you'd like**
I'd love if if this repository was updated to produce two go binaries,  the regular one, plus an additional image build against BoringCrypto Go. And i'd love it if both where published as images to the container registry.

This would require perhaps updating the MakeFile to support both builds, and the CI pipeline to push the new image to the registry, perhaps pre-pended with '-fips' on the tag.

**Comment by M00nF1sh** [comment]
@electricthunder 
i'm not familiar with this boringcrypto tbh, will need to check whether it works for default environment like us-west-2. 

If so, we can just produce a single image with the setting instead of maintain two.

**Comment by electricthunder** [comment]
Yea its not specific to AWS as such, once the app is compiled against BoringCrypto go, it'll use FIPS crypto libraries and this will satisfy FedRAMP requirements.

I can't go into specifics here, but we're already doing this and running in EKS clusters within AWS. Certainly one image is an option, but there can be performance concerns so typically we see vendors provide a separate image.

Appreciate the prompt response and loopback
