### ISSUE TITLE
Allow Ingress to use host header rules even if the host's certificate is not associated with the ALB

### ISSUE THREAD

**Issue by mbonica1990** [kubernetes-sigs/aws-load-balancer-controller#3183]
**Is your feature request related to a problem?**
I have a use case where I am intentionally creating ingresses with host header-based routing, using hostnames that don't have valid SSL certificates associated with the load balancer. (To clarify again, I am doing this on purpose.) I am able to do this on an ALB through the AWS SDK, but when I try to do it on the ingress controller, I get a reconciler error: "no certificate found for host". The rule on the ALB is then not created.

This functionality seems to be coming from here:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/ff8c13d4cc368f8073421a46918cadd7c0fc760a/pkg/ingress/cert_discovery.go

This is preventing me from using the ALB load balancer controller in the same way that I would set up my ALB without it.

**Describe the solution you'd like**
I understand why the load balancer checks for the presence of the appropriate ACM cert - it's handy - but I don't think it should be mandatory, as AWS allows me to do this without the appropriate certificate. I would like an argument that would allow me to opt out of this check.

**Describe alternatives you've considered**
- I could associate valid SSL certificates with the ALB, but as I mentioned earlier, I am giving these hosts incorrect SSL certificates on purpose.
- I have been using other ingress controllers that don't do this, but as all I really need is host/path-based routing, I really want to stop using them and use an ALB, which does that for me.
-

**Comment by oliviassss** [comment]
@mbonica1990 the validation on certificate is a security requirement, if there's no certificate specified by `alb.ingress.kubernetes.io/certificate-arn`, the controller will do certificate auto discover as you pointed out. Can you check if the annotation `alb.ingress.kubernetes.io/certificate-arn` works in your case? For more info please check:
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/annotations/#certificate-arn
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/cert_discovery/
