### ISSUE TITLE
Optional Certs not being attached when adding cert annotation for the first time

### ISSUE THREAD

**Issue by nickzelei** [kubernetes-sigs/aws-load-balancer-controller#3185]
**Describe the bug**
When adding the SSL cert annotation for the first time with multiple certificates, only the default certificate is associated with the load balancer.
After restarting the deployment of the aws load balancer controller, it properly adds the second certificate.

**Steps to reproduce**
I create a service of type LoadBalancer and have it spin up initially without any SSL certificates attached.
This spins up the LB in standard HTTP mode.

Initial Annotations:
```
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    service.beta.kubernetes.io/aws-load-balancer-type: external
```

I then create two ACM certificates.
Once they have been properly issued, I then attach them by adding the ssl annotation:
```
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:295461250191:certificate/ea714dcd-1dcd-47b9-a750-f6fdbe771d35,arn:aws:acm:us-west-2:295461250191:certificate/a4ce1483-bb9a-41e6-a203-804c4d40cf5f
```

This updates the NLB to use only the first certificate. The second cert remains unused.
I roll the aws-lbc pods, then the second certificate is added.

I have been able to consistently repro this by:
1. removing the ssl-cert annotation
2. waiting for ACM to mark the certs as unused.
3. Re-adding the ssl-cert annotation with both certs.
4. aws-lbc consistently only adds the first certificate
5. rolling the deployment via `kubectl`
6. aws-lbc associates the missing certificate

To workaround this, when adding the cert, only add a single one with the annotation. Then update the service to include the second cert.
This isn't ideal as automated systems are adding both of these at the same time.

**Expected outcome**
I expect each certificate to be associated with the load balancer regardless of how or when they are added to the annotation.

**Environment**

* AWS Load Balancer controller version
  * v2.5.1 (via helm chart 1.5.2)
* Kubernetes version
  * 1.25
* Using EKS (yes/no), if so version?
  * yes - eks.2

**Additional Context**:

Here is a link to the logs. The first file is the booting up of the AWS-LBC. You can see at the bottom when it detects the addition of the cert annotation.
It shows that it is modifying the various listeners.
The second file is after the restart and it prints out that it is now adding the second certificate.
https://gist.github.com/nickzelei/0e074f0ed376cd535e5675c6a9ba6b02

**Comment by oliviassss** [comment]
Thanks for all the details, we will probably need to revisit our logic here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/ff8c13d4cc368f8073421a46918cadd7c0fc760a/pkg/deploy/elbv2/listener_manager.go#L172

**Comment by oliviassss** [comment]
@nickzelei, I'm able to reproduce the issue. The controller skipped adding extra certificates because it detects no sslpolicy on sdk listeners for the first time.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/ff8c13d4cc368f8073421a46918cadd7c0fc760a/pkg/deploy/elbv2/listener_manager.go#L162
We should check the ssl policy on res listeners instead of sdk listeners, will raise a PR to fix it soon.

**Comment by nickzelei** [comment]
Thanks for the info @oliviassss - glad you are able to reproduce!
