### ISSUE TITLE
Add possibility to disable Prometheus scraping via Helm char settings

### ISSUE THREAD

**Issue by FilimonovEugene** [kubernetes-sigs/aws-load-balancer-controller#3187]
**Problem**
When AWS ALB Controller deployed with hostNetwork=true its pods may fail to start on the node where port 8080 is already in use by another process. I'd like to completely disable Prometheus scraping.

**Solution**
Helm chart setting to disable Prometheus scraping.

**Alternatives**
Pod anti-affinity rule for AWS ALB Controller to not shcedule pods on the nodes with components required 8080 port.

**Comment by oliviassss** [comment]
Would you be able to specify `metrics-bind-addr` controller flag to choose an alternate port for this? Also try to set the `metrics-bind-addr` to 0 to disable this feature completely.

**Comment by oliviassss** [comment]
@FilimonovEugene, closing this issue as duplicate, we can track it here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3201. Thanks
