### ISSUE TITLE
Incorrect apiVersion for CertManager Issuer/Certificate 

### ISSUE THREAD

**Issue by hawkesn** [kubernetes-sigs/aws-load-balancer-controller#3188]
Note: Relates to: https://github.com/aws/eks-charts/issues/942

**Describe the bug**
When using ArgoCD, helm charts are rendered via `helm template`. The `.Capabilities` function may not always work in this case.
As a result, the `.Capabilities` follows the `else` statement and defaults to `cert-manager.io/v1alpha2`.

Potentially related to: https://github.com/argoproj/argo-cd/issues/3631

Considering that `cert-manager.io/v1` has been around for the [last two years](https://github.com/cert-manager/cert-manager/blame/master/deploy/crds/crd-issuers.yaml#LL21C14-L21C14),  it should default to that version not `v1alpha2`

**Steps to reproduce**
Run `helm template` on the chart with `enableCertManager: true` and a clusterName set.

**Expected outcome**
`.Capabilities` should correctly identify the apiVersion, otherwise, default to `v1`. OR a user specified fallback mechanism in place in the event that it cannot.

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: 1.5.2
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes, 1.24

**Additional Context**:

**Comment by oliviassss** [comment]
Thanks for the feedback, we can remove the older version and exclusively support `cert-manager.io/v1` in the next helm chart release.
/kind feature

**Comment by hawkesn** [comment]
Solved with: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3188
