### ISSUE TITLE
SFTP example?

### ISSUE THREAD

**Issue by tooptoop4** [kubernetes-sigs/aws-load-balancer-controller#3190]
i see example for
alb.ingress.kubernetes.io/backend-protocol-version: GRPC

but can protocol be SFTP instead?

**Comment by oliviassss** [comment]
The SFTP is not supported by ALB so we cannot support either. Would you be able to share more details about the use case?

**Comment by oliviassss** [comment]
@tooptoop4, I'm closing the issue for now, please free feel to reach out or reopen if you have more questions.
