### ISSUE TITLE
Add env credential values from Secret

### ISSUE THREAD

**Issue by stelucz** [kubernetes-sigs/aws-load-balancer-controller#3191]
**Is your feature request related to a problem?**
The EBS CSI Driver uses Secret as env values source for AWS credentials. When CSI driver is deployed it would be nice to reuse Secret in the same way for the LB controller.

**Describe the solution you'd like**
Populate env variables from Secret in the same way as the EBS CSI Driver does. Ref: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L104-L115

**Comment by oliviassss** [comment]
The credentials are statically stored, the recommend way is to use IRSA which retrieve temporary credentials. Why not use the recommended IRSA to configure credentials in your use case?

**Comment by M00nF1sh** [comment]
@stelucz 
I don't have a strong opinion against use the secret. But you should use [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) as it's more safe and easier to use than store static credentials in secret(where you need to handle rotates as best practices)

**Comment by stelucz** [comment]
@oliviassss Is not IRSA (iam service account) proprietary to eks only? If not, how can I configure it/deploy it in k8s cluster on top of AWS VMs? Thanks.

In our case, there is already EBS CSI driver using Secret for credentials. So the point was to reuse it in the same way for LB controller.

**Comment by M00nF1sh** [comment]
@stelucz 
Thanks for explaining your use case. The self-managed k8s cluster use case makes sense to me. 
Would you mind open a PR to add this support? we are happy to take it.

BTW, the IRSA solution is available for self-managed k8s as well if you want prefer the extra security it provides, however,  it's indeed a bit complex to setup it on a self-managed cluster. see https://github.com/aws/amazon-eks-pod-identity-webhook

**Comment by stelucz** [comment]
Hi @M00nF1sh 
thanks for linking it. I will look into that.
PR is already there, please check https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3192

Cheers!
