### ISSUE TITLE
IngressClassParams don't support all alb controller annotations, leading to duplicated code

### ISSUE THREAD

**Issue by paul-civitas** [kubernetes-sigs/aws-load-balancer-controller#3194]
Lets say you have multiple websites you want to share the same ALB. So each website has its own ingress.

You want the ALB to be named a specific thing so you specify a [alb.ingress.kubernetes.io/load-balancer-name](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/annotations/#load-balancer-name) in the ingress. From here though it's unclear. Do you specify the [alb.ingress.kubernetes.io/load-balancer-name](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/annotations/#load-balancer-name) in every single ingress, or just one of them but then put them in the same ingress group?

It seems the intended method is to configure the ALB via the IngressClassParams, then configure the rules via the Ingress. However IngressClassParams only supports a small subset of the knobs.

**Comment by oliviassss** [comment]
We will gradually support more annotations to IngressClassParams. For the `alb.ingress.kubernetes.io/load-balancer-name`, you can specify on one of the ingress within the ingress group. Please be mindful of the issue #3173 if you specify the load balancer name. For ingress group we recommend using ingress group name to influence the load balancer name.

**Comment by oliviassss** [comment]
@paul-civitas, I'm closing this issue for now, please feel free to reach out or reopen if you have any questions. Thanks

**Comment by paul-civitas** [comment]
I was discussing this type of thing with my TAM, and it seems the situation is difficult yeah. We also discussed gateway API support for the ALB controller.
