### ISSUE TITLE
Unable to create NLB through AWS LBC in EKS with Fargate profile only.

### ISSUE THREAD

**Issue by srik-git** [kubernetes-sigs/aws-load-balancer-controller#3198]
**Describe the bug**
I am trying to create NLB using AWS LBC in an AWS EKS cluster with just Fargate profile no (managed) node group. It fails to bring up pods. It works fine if we have a EC2 nodes for deployment and most AWS blogs use it this way) 

**Steps to reproduce**
Create a EKS cluster with one Fargate profile and allow Fargate nodes only (patched CoreDNS as described in https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html for deploying Pods to Fargate (none to Amazon EC2 nodes) ) and try to create NLB as follows:
1) Create AWS LBC (Load Balancer Controller) policy -- success 
curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.7/docs/install/iam_policy.json

2) Create IAM role and attach policy -- success 
aws iam create-policy \
> --policy-name somepolicy \
>  --policy-document file://iam-policy.json

3)  Create a Service Account for AWS Load Balancer Controller -- success
eksctl create iamserviceaccount \
>  --cluster=someCluster \
> --name=aws-load-balancer-controller \
>  --namespace=kube-system \
> --attach-policy-arn=<arn for the above policy> \
> --approve

4) 14) The following installs CustomResourceDefinitions necessary for the controller to function -- success
$ kubectl apply -k \
>     "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"

5) 14) The following installs CustomResourceDefinitions necessary for the controller to function --success
$ kubectl apply -k \
>     "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"

6) Rollout deployment: 
kubectl -n kube-system rollout status deployment aws-load-balancer-controller

**Expected outcome**
Successful creation of pods in the kube-system namespace. I gives this:
Waiting for deployment "aws-load-balancer-controller" rollout to finish: 0 of 2 updated replicas are available...

error: deployment "aws-load-balancer-controller" exceeded its progress deadline

Nothing in the pod logs and the pods are stuck in pending state for ever.
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version
* Latest ALB
* Kubernetes version:
* Client Version: v1.26.2-eks-a59e1f0
Kustomize Version: v4.5.7
Server Version: v1.26.4-eks-0a21954

* Using EKS (yes/no), if so version?
* Latest EKS

**Additional Context**:

**Comment by oliviassss** [comment]
@srik-git are there existing self-managed nodes on your cluster? Would you be able to check if the existing nodes can communicate to your Fargate pods successfully?
ref: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html

**Comment by srik-git** [comment]
> @srik-git are there existing self-managed nodes on your cluster? Would you be able to check if the existing nodes can communicate to your Fargate pods successfully? ref: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html

@oliviassss As I said above there are no self-managed nodes in the cluster just Fargate nodes. I should have said this, if there are self-managed nodes then it works. I am looking to deploy it in the pure Fargate cluster.

**Comment by M00nF1sh** [comment]
@srik-git 
To deploy this controller in EKS-Fargate, you need to manually specify `--aws-vpc-id` and `--aws-region` on the controller pod or via helm settings(vpcId, region).
The reason is there is no IMDS available in fargate, so the controller cannot auto-discover above settings.

**Comment by oliviassss** [comment]
@srik-git, I'm closing this issue for now. Please feel free to reach out or reopen if you have any questions. Thanks
