### ISSUE TITLE
Warn/Fail if VPC doesn't exist

### ISSUE THREAD

**Issue by andyndang** [kubernetes-sigs/aws-load-balancer-controller#3199]
**Is your feature request related to a problem?**

Accidentally passed in the wrong VPC and all my controller was telling me was this error message: "unable to resolve at least one subnet"

**Describe the solution you'd like**
Fail the controller health check or print out error messages if the VPC ID doesn't exist in the account

**Describe alternatives you've considered**
Had to manually checked the arguments of the pod to realize I passed in the wrong param

**Comment by M00nF1sh** [comment]
sounds like a improvement we shall do, at least have more clear error messages.
