### ISSUE TITLE
Support ALBs for LoadBalancer services

### ISSUE THREAD

**Issue by jalitzinger** [kubernetes-sigs/aws-load-balancer-controller#3204]
**Is your feature request related to a problem?**
Is there interest in PRs to support ALBs for LoadBalancer services in  addition to NLBs?

Some example use cases/reasons:
- More configurable timeouts
- Ability to leverage LB  security groups for IP allowlisting, versus requiring the node security group
- Leveraging the ALB rule capability to handle some traffic at the edge.
- Ability to leverage ingress controllers behind the ALB and do dynamic routing/traffic manipulation inside the cluster.
- The TLS policy options for Classic Load Balancers are smaller and not currently being updated.
- Ability to leverage the ALB WAF.

Those are only a few examples. While some of these can be satisfied on their own, some (such as timeouts) make the existing options incompatible.  While there are workarounds, they seem somewhat inelegant compared to the  option of just specifying an ALB for a LoadBalancer service.

**Describe the solution you'd like**
ALBs as a supported type for LoadBalancer services, similar to the support for classic load balancers.

**Describe alternatives you've considered**
This can be worked around in some cases (e.g. an alternative ingress controller) by leveraging an Ingress and NodePort service.  However, this brings its own implications.

**Comment by M00nF1sh** [comment]
@jalitzinger 
we don't want to support that for now as there is a new Gateway API that aims to replace Ingress/Service api.
this problem don't exists once we support gateway api.
