### ISSUE TITLE
Question: How would you provide Root CA to AWS Load Balancer Controller Pods

### ISSUE THREAD

**Issue by rshsmi** [kubernetes-sigs/aws-load-balancer-controller#3207]
**Describe the bug**
Inability to provide Root CA Cert to AWS Load Balancer Controller Pods (CA is reuqired for HTTP Proxy)

**Steps to reproduce**
Set Env varibles;
http_proxy=xx.xx.xx:1234
https_proxy==xx.xx.xx:1234

**Expected outcome**

**Environment**

* AWS Load Balancer controller version: 1.4.5
* Kubernetes version: 1.23
* Using EKS (yes/no), if so version? yes, 1.23

**Additional Context**:
AWS Load Balancer Controller Helm Chart is installed on EKS, we have corporate proxy to reachout to internet, I set the env varibles for proxy server in helm chart values file but I don't see any way to provide the CA which proxy server are required.

**Comment by chris-gooch** [comment]
We have a similar scenario and have tried the above but it says they are not valid options. 
Also tried the same with volumes & volumeMounts but still does not appear to be using the custom CA certificate.
Any other clues on how to debug this as we cannot get shell access to troubleshoot manually either.
