### ISSUE TITLE
Installing fails with webhook related error

### ISSUE THREAD

**Issue by denmaddog** [kubernetes-sigs/aws-load-balancer-controller#3215]
From time to time the deployment of application fails without any changes in our pipeline (Gitlab), with error:

> Error: release app1 failed: Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "[https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s](https://aws-load-balancer-webhook-service.kube-system.svc/validate-networking-v1-ingress?timeout=10s)": context deadline exceeded
  Error: plugin "tiller" exited with error

After some time and couple of retries of the same job the release gets installed/upgraded.

The pipeline job is using `helmfile apply`.

We do have aws-load-balancer-controller installed but the release having issue has ingress resources defined using nginx ingress controller, not aws-load-balancer-controller:
`Annotation: kubernetes.io/ingress.class: shared-internal`

Why would releasing the app with helmfile apply POST anything to `https://aws-load-balancer-webhook-service.kube-system.svc/validate-networking-v1-ingress?timeout=10s`?

Can you please help?

Thanks,

Zeljko

**Comment by denmaddog** [comment]
Hi @oliviassss ,

```
CHART:  aws-load-balancer-controller-1.4.2
APP VERSION: v2.4.2 
```

**Comment by oliviassss** [comment]
@denmaddog Is there a security group rule to allow accessing to port 9443 from the kubernetes control plane? All ingresses pass through the validation webhook, only the ingresses that the controller supports are processed further, others are ignored.

**Comment by oliviassss** [comment]
@denmaddog, I'm closing this issue for now, please feel free to reach out or reopen if you still see this issue. Thanks
