### ISSUE TITLE
Target Group Not Attached with NLB Created from Nginx Ingress Controller and AWS Load Balancer Controller

### ISSUE THREAD

**Issue by sujeetkp** [kubernetes-sigs/aws-load-balancer-controller#3225]
I am trying to install nginx ingress controller along with AWS Load Balancer Controller. Below is the code for nginx ingress controller, AWS LB Controller. My NLB target group targets are not getting registered. I could see 2 listeners are created 80/443, but the target groups are empty. 
 
          resource "helm_release" "nginx_ingress_controller" {
        
                  name       = "nginx-ingress"
                  repository = "https://kubernetes.github.io/ingress-nginx"
                  chart      = "ingress-nginx"
                
                  namespace = var.nginx_ingress_namespace
                  create_namespace = true
                
                  values = [
                    "${file("config-files/nginx-ingress-controller-values.yml")}"
                  ]
                
                  wait = true
          
        }
        
        nginx-ingress-controller-values.yml 
        
        controller:
          service: 
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-name: apps-ingress
              service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance

I have followed below document to install AWS Lod Balancer Controller.
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html

        resource "helm_release" "aws-load-balancer-controller" {
          
              depends_on = [
                module.eks
              ]
              
              name       = "aws-load-balancer-controller"
              repository = "https://aws.github.io/eks-charts"
              chart      = "aws-load-balancer-controller"
              
              namespace = var.aws_lb_namespace
            
              set {
                name  = "clusterName"
                value = local.eks_cluster_name
              }
              set {
                name  = "serviceAccount.create"
                value = "true"
              }
              set {
                name  = "serviceAccount.name"
                value = var.aws_lb_service_account
              }
              set {
                name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
                value = "${module.iam_role_aws_lb_controller.iam_role_arn}"
              }
            
              wait = true
          
        }

Versions-

        NAME                        	NAMESPACE            	REVISION	UPDATED                             	STATUS  	CHART                             	APP VERSION
        aws-load-balancer-controller	kube-system          	1       	2023-06-05 21:05:32.526691 +0530 IST	deployed	aws-load-balancer-controller-1.5.3	v2.5.2

nginx ingress is of version 1.8.0
Kubernetes is 1.27 EKS.

**Comment by sujeetkp** [comment]
Even I tried with a simple LoadBalancer Service, still the targets are not getting attached -

      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
          deploy: first
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
              version: "1.14.2"
          spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
              - containerPort: 80
      
      ---
      
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-svc
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      spec:
        type: LoadBalancer
        selector:
          app: nginx
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80

**Comment by M00nF1sh** [comment]
@sujeetkp sujeetkp 

What's the status of nodes in your cluster? the controller only register healthy nodes.

What's the logs from the controller?

**Comment by oliviassss** [comment]
@sujeetkp, hi, are you still seeing this issue? would you be able to share the controller logs? you can send it to k8s-alb-controller-triage AT amazon.com

**Comment by oliviassss** [comment]
@sujeetkp, I'm closing this issue as for now, thanks.
