### ISSUE TITLE
Allow instance/IP target group bindings for external EC2 Instances

### ISSUE THREAD

**Issue by mooseracer** [kubernetes-sigs/aws-load-balancer-controller#3236]
**Is your feature request related to a problem?**
There are options for provisioning EC2 Instances through kubernetes controllers (ACK, various Crossplane terraform/aws providers), but in those it's a lot of extra work to also manage their elbv2 ingress. ACK doesn't even support it, and Crossplane is a lot of extra complexity if you just need this one thing. So there's a hole here -- when orchestrating our container stack, how are we meant to simply stand up a supporting EC2 instance and throw it behind an ALB?

This is probably related to [issue 3174](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3174).

**Describe the solution you'd like**
I'd like a simple way to have AWS LBC create the ALB/listener/listener rules/target groups, and also register any passed in EC2 instance IDs or private IPs.

**Describe alternatives you've considered**
I tried creating all the ingress resources except for target group registration, and then had something else register the EC2 IP for me. But apparently there's a periodic reconciliation that deregisters it again. I'd be happy enough to have a way to mark a target group as being exempt from the cleanup cycle.

**Comment by oliviassss** [comment]
@mooseracer, the controller automatically manages ALB/listener/listener rules/target groups based on your ingress resources, you should not modify the AWS resources separately.

**Comment by rkujawa** [comment]
@oliviassss Currently with ALB controller it is not possible to create an Ingress that would point to a resource outside of the cluster, and this is what @mooseracer wants. It is the problem I reported in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3174. From Ingress spec point of view, this should be possible. It's a limitation of ALB controller.

**Comment by oliviassss** [comment]
closing for duplication, let's track it in #3174
