### ISSUE TITLE
Make `enable-leader-election` toggle-able via Helm Chart

### ISSUE THREAD

**Issue by rblaine95** [kubernetes-sigs/aws-load-balancer-controller#3243]
**Is your feature request related to a problem?**
The AWS Load Balancer Controller currently has a [command line argument](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/configurations/#controller-command-line-flags) for enabling/disabling leader election.

Would it be possible to be able to set this to `false` via the helm chart?
Is there a specific reason why this hasn't already been done?

**Describe the solution you'd like**
Able to set `--enable-leader-election=true|false` via the Helm Chart like other CLI arguments.

**Comment by dabcoder** [comment]
I have a branch for this in my fork, will open a PR for review very soon.
