### ISSUE TITLE
Enable Prometheus metrics without ServiceMonitor

### ISSUE THREAD

**Issue by prashcr** [kubernetes-sigs/aws-load-balancer-controller#3244]
**Is your feature request related to a problem?**
I want to enable Prometheus metrics on aws-load-balancer-controller without creating a `ServiceMonitor` and having [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) on my Kubernetes cluster. This is because I'm using an alternative Prometheus collector: [Grafana Agent](https://grafana.com/docs/grafana-cloud/data-configuration/agent/).

Currently the Helm chart defines a single `serviceMonitor.enabled` variable to enable both the [Prometheus metrics service](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/service.yaml#LL1C8-L1C8) and the [ServiceMonitor](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/servicemonitor.yaml#LL1C8-L1C8).

**Describe the solution you'd like**
The Helm charts defines a new `metrics.enabled` variable. The [metrics Service](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/service.yaml) is created `if metrics.enabled OR serviceMonitor.enabled`

**Related**
https://github.com/aws/eks-charts/issues/959

**Comment by oliviassss** [comment]
@prashcr, thanks for bringing this up, feel free to raise a PR.

**Comment by prashcr** [comment]
@oliviassss Thanks, here it is: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3245

**Comment by darren-recentive** [comment]
@oliviassss @orsenthil @jerryhe1999
Anything I can do to help in finishing up this Issue / PR? 😄

**Comment by Helinanu** [comment]
Is the pending PR still valid? Would really like this feature since we cannot use prometheus operator

**Comment by booleanbetrayal** [comment]
We also do not use Prometheus Operator, but would like access to AWS LB Controller metrics. Can this be re-opened?

**Comment by zac-nixon** [comment]
I think this has been handled by https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/2e8cf3f8cd545c21b68d428b538581265427202b
