### ISSUE TITLE
Fix prerequisite k8s version in helm chart's readme

### ISSUE THREAD

**Issue by stevo-f3** [kubernetes-sigs/aws-load-balancer-controller#3259]
**Describe the bug**
By the release notes https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases chart 1.5.0+ i.e. controller v2.5.0 requires k8s 1.22+, while current (1.5.4) chart's readme lists k8s 1.19+ as prerequisite https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/README.md#prerequisites

**Steps to reproduce**

N/A

**Expected outcome**
Chart's readme prerequisites list to be up to date.

**Environment**

* AWS Load Balancer controller version: 2.5.3
* Kubernetes version: 1.24
* Using EKS (yes/no), if so version? yes

**Additional Context**:

**Comment by oliviassss** [comment]
@stevo-f3, Thanks, we will update our docs.
/kind documentation

**Comment by stevo-f3** [comment]
Fixed with https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3347
