### ISSUE TITLE
unable to create target group in cross account pod and alb 

### ISSUE THREAD

**Issue by nessa829** [kubernetes-sigs/aws-load-balancer-controller#3260]
**Describe the bug**
A concise description of what the bug is.

I am currently implementing an internet-facing load balancer (LB) in the public account that communicates with an EKS cluster in the service account while setting up a subnet sharing + VPC peering environment. However, despite following the instructions in the referenced blog post, it does not work. : 
https://aws.amazon.com/ko/blogs/containers/expose-amazon-eks-pods-through-cross-account-load-balancer/ 

**Steps to reproduce**
I have done as below. 
1. vpc peering(tgw) and Subnet sharing: Successfully accessing the public account from the service account. Also i can list the public account subnet from service account. 

2. OIDC provider creation in the public account and IAM creation for LB controller.

3. Apply the IAM role to LB controller's service account in the service EKS cluster.

4. Deploying the service ingress in the service account with specified subnets and security groups.

However, I consistently encounter an issue where the ALB is created successfully in the public account, but the target group attempts to be created in the service account, resulting in the error message "The following target groups are in a different VPC than the load balancer" in the ALB ingress controller.

I would like to know if there are any additional configurations required to achieve cross-account setup. 

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version 
* Kubernetes version
The EKS version is 1.27, and the ALB controller version is 2.5.2.

* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by oliviassss** [comment]
@nessa829, Hi, is the public account an AWS account? And are the 2 accounts under the same AWS organization?

**Comment by nessa829** [comment]
@oliviassss Thank you for reply.
I got a clue that it might be a matter of vpcID. 
I will try that. 
But in the mean time, is it possible to have multiple alb ingress controller in a cluster? 
i need to make both private alb (in service Account )  and public alb (in public account). 
That mean it need to have different vpcId. 

I tried as below, but i got an error. 

```


resource "helm_release" "aws-load-balancer-controller" {
  name       = "aws-load-balancer-controller"
  chart      = "aws-load-balancer-controller"
  repository = "https://aws.github.io/eks-charts"
  version    = "1.5.3"
  namespace  = "kube-system"

  dynamic "set" {
    for_each = {
      "region"                            = "ap-northeast-2"
      "vpcId"                             = local.vpc_id
      "image.repository"                  = "602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/amazon/aws-load-balancer-controller"
      "serviceAccount.create"             = "true"
      "serviceAccount.name"               = local.lb_controller_service_account_name
      "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn" = module.iam_assumable_role_alb_controller.iam_role_arn
      "clusterName"                       = module.eks.cluster_id
      "targetgroupbindingMaxExponentialBackoffDelay": "30s"
    }
    content {
      name  = set.key
      value = set.value
    }
  }

  values = [
    file("${path.cwd}/yaml/alb-controller/values.yaml")
  ]
}

resource "kubernetes_namespace" "alb_controller_public" {
  metadata {
    name = "alb-controller-public"
  }
}

resource "helm_release" "aws-load-balancer-controller-public" {
  name       = "aws-load-balancer-controller-public"
  chart      = "aws-load-balancer-controller"
  repository = "https://aws.github.io/eks-charts"
  version    = "1.5.3"
  namespace  = "kube-system"

  dynamic "set" {
    for_each = {
      "region"                            = "ap-northeast-2"
      "vpcId"                             = var.public_vpc_id
      "ingressClass"                      = "alb-public"
      "image.repository"                  = "602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/amazon/aws-load-balancer-controller"
      "serviceAccount.create"             = "true"
      "serviceAccount.name"               = local.lb_controller_service_account_name_public
      "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn" = var.public_alb_irsa_arn
      "clusterName"                       = module.eks.cluster_id
      "targetgroupbindingMaxExponentialBackoffDelay": "30s"
    }
    content {
      name  = set.key
      value = set.value
    }
  }

  values = [
    file("${path.cwd}/yaml/alb-controller/values.yaml")
  ]

```


```
module.eks.helm_release.aws-load-balancer-controller-public: Creating...
╷
│ Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "aws-load-balancer-tls" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "aws-load-balancer-controller-public": current value is "aws-load-balancer-controller"
│ 
│   with module.eks.helm_release.aws-load-balancer-controller-public,
│   on ../modules/eks-cluster/alb-controller.tf line 101, in resource "helm_release" "aws-load-balancer-controller-public":
│  101: resource "helm_release" "aws-load-balancer-controller-public" {
│ 
╵

```

**Comment by oliviassss** [comment]
@nessa829, currently we don't support multiple controllers per cluster since the controller assumes solo ownership of worker node SG rules. We do have this feature on our roadmap, though. You can refer to the discussions here to get more info:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2183
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2233
