### ISSUE TITLE
Support for importing existing ALB

### ISSUE THREAD

**Issue by kahirokunn** [kubernetes-sigs/aws-load-balancer-controller#3263]
**Is your feature request related to a problem?**
When migrating Terraform to ALB Ingress, if an existing ALB is not available, the ALB will need to be recreated.

**Describe the solution you'd like**
We would like to be able to configure the cluster to use existing ALBs so that we do not have to recreate them when we rebuild the cluster.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by oliviassss** [comment]
@kahirokunn, thanks, we have the feature in our roadmap and are tracking it here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/228

**Comment by kahirokunn** [comment]
Okay. Thx!
