### ISSUE TITLE
Disable backend SG rule management

### ISSUE THREAD

**Issue by nakamume** [kubernetes-sigs/aws-load-balancer-controller#3265]
**Is your feature request related to a problem?**
We'd like to manage all backend security-group(SG) rules manually and outside of the controller. This would allow -
- To limit the number of rules that are created for backends. This has already been greatly improved with the introduction of `EnableBackendSecurityGroup` for ingresses but services still create a lot of rules. If the users manually create the rules, they can further optimize it.
- Platform teams to control which ports should be opened. Currently product teams can use whatever ports they want and the controller creates the corresponding rules. If the rules are managed outside of controller (manually) - platform teams would have better controls on what ports should be opened.
- We (personally) manage our rules using terraform and general allowed some ports from sources within our VPC. So, in almost all cases, the rules added by the controller are redundant for us.

**Describe the solution you'd like**
- A controller flag to enable/disable backend SG rule management.
- At least for ingresses, a param can be introduced in `IngressClassParam`. But not sure if something like this exists for services.

**Describe alternatives you've considered**
Both ingress and service support annotations to disable the backend SG rule management, but that's repetitive and doesn't provide platform teams to enforce the restriction on controller level.

**Comment by johngmyers** [comment]
Platform teams can control ports with a policy-enforcing admission controller such as Gatekeeper.
