### ISSUE TITLE
ACM certificate from a different account

### ISSUE THREAD

**Issue by omri-shilton** [kubernetes-sigs/aws-load-balancer-controller#3276]
Not a bug, but a question regarding ACM certificates and the controller.
I want to access ACM certificates from a different AWS account. 
Is there a way to achieve that?

**Comment by oliviassss** [comment]
@omri-shilton, I find some refs for the CA sharing across accounts, see if it helps with your use case:
- https://aws.amazon.com/about-aws/whats-new/2020/08/aws-certificate-manager-private-certificate-authority-supports-private-ca-sharing/
- https://docs.aws.amazon.com/privateca/latest/userguide/granting-ca-access.html
- https://aws.amazon.com//blogs/security/how-to-use-aws-ram-to-share-your-acm-private-ca-cross-account/

**Comment by oliviassss** [comment]
@omri-shilton, I'm closing the issue as for now, please feel free to reach out if you have any questions, thanks.

**Comment by fernandezcuesta** [comment]
sorry for necroposting, but I have the very same question, ACM-PCA not being an option so far. Any hints?
