### ISSUE TITLE
Remove Ingress but leave NLB

### ISSUE THREAD

**Issue by chadxzs** [kubernetes-sigs/aws-load-balancer-controller#3278]
This is a usage question, I searched the docs and the past issues and didn't find the answer to my question anywhere.

I am currently using an NLB created by the AWSLBC and want to move to using Terraform to manage this NLB instead and use AWSLBC TargetGroupBinding. I want to "disconnect" the NLB so that it stays in AWS, as it is associated with a VPC Endpoint Service and cannot be deleted unless I disconnect any VPC Endpoints, which I do not want to do.

Is the best way to accomplish this to delete the finalizer on the ingress? Or are there other considerations?

p.s. happy to take this to a mailing list or some user forum but I didn't see anything.

**Comment by M00nF1sh** [comment]
@chadxzs 
The best way is to delete the finalizer on ingress and then delete the ingress.
Also, after ingress deleted, remove the tags on the NLB/SecurityGroup/TargetGroups. (otherwise if you recreate the ingress again, the controller will adopt these existing resource)

**Comment by chadxzs** [comment]
Thank you.
