### ISSUE TITLE
Error retrieving resource lock kube-system/aws-load-balancer-controller-leader: leases.coordination.k8s.io "aws-load-balancer-controller-leader" is forbidden

### ISSUE THREAD

**Issue by assist-lucian** [kubernetes-sigs/aws-load-balancer-controller#3286]
**Describe the bug**
```error
E0718  1 leaderelection.go:330] error retrieving resource lock kube-system/aws-load-balancer-controller-leader: leases.coordination.k8s.io "aws-load-balancer-controller-leader" is forbidden: User "system:serviceaccount:kube-system:aws-load-balancer-controller" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```
**Steps to reproduce**
Upgrading EKS from kube version 1.21 to 1.22, and AWS Load Balancer Controller chart from v2.3.1 to v2.5.x.

**Expected outcome**
All existing ingress rules should be parsed without any issue.

**Environment**

* AWS Load Balancer controller version 
helm chart v2.5.x
* Kubernetes version
1.22 and up
* Using EKS (yes/no), if so version?
yes, eks.14
**Additional Context**:
Issue: 
   -  missing  rule for leases resource from coordination.k8s.io
Fix: Add rule for
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
```
```yaml
- apiGroups: ["coordination.k8s.io"]
  resources: [leases]
  verbs: [get, list, watch, create, patch, update]
```

**Comment by umegaya** [comment]
I got same issue. I used aws-load-balancer-controller 2.5.4 and eks with k8s version 1.27
I temporary used 2.4.7 to solve the problem.

**Comment by oliviassss** [comment]
@assist-lucian, @umegaya would you be able to share how to upgrade the controller version? do you use helm upgrade, or you just edit the image in the deployment?
We migrated to support configMapLease since v2.5.0, together with other manifest update. So we suggested to `helm repo update` and then upgrade the controller via helm.
ref:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2993
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.5.0

**Comment by umegaya** [comment]
@oliviassss I used terraform helm provider. first I just changed chart version and `terraform apply`, but this error happened. then I remove aws-load-balancer-controller installation by using `helm uninstall` and `terraform apply` again but no help.

hope that helps.

**Comment by mdrajibkhan** [comment]
When we use aws load balancer controller image version 2.4.7 it is working fine but when we adjust another version of images then we got same issues
