### ISSUE TITLE
Expose relabel rules for ServiceMonitor in the Helm Chart

### ISSUE THREAD

**Issue by sidewinder12s** [kubernetes-sigs/aws-load-balancer-controller#3287]
**Is your feature request related to a problem?**

Would like to configure relabel/drop rules in the ServiceMonitor

**Describe the solution you'd like**

Expose this as an option in the helm chart

**Describe alternatives you've considered**

Could move to using Annotations rather than serviceMonitors

**Comment by kishorj** [comment]
@sidewinder12s, do you have a PR/code snippet for this? If so feel free to contribute.
