### ISSUE TITLE
Unable to create internal NLB

### ISSUE THREAD

**Issue by franciscoprin** [kubernetes-sigs/aws-load-balancer-controller#3293]
**Describe the bug**
Unable to create an internal NLB.

**Steps to reproduce**
Add these annotations to your services:
```
service.beta.kubernetes.io/aws-load-balancer-type:  "nlb"
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
```

**Expected outcome**
The above configuration should create an internal NLB, instead an internet-facing NBL is getting created. 

**Environment**

* AWS Load Balancer controller version: v2.4.7
* Kubernetes version: 
   ```
   Client Version: v1.23.17
   Server Version: v1.22.17-eks-a5565ad
   ```
* Using EKS (yes/no), if so version? yes and 1.22

**Additional Context**:
 I had also used `service.beta.kubernetes.io/aws-load-balancer-internal: true` annotation with not luck.

**Comment by franciscoprin** [comment]
So, I am not sure why, but these annotations works:
```
       "service.beta.kubernetes.io/aws-load-balancer-internal": true
        "service.beta.kubernetes.io/aws-load-balancer-subnets" = "subnet-0c6c0664f13690437,subnet-03d1cd3e2b4516d55,subnet-0afdec0b7949e7c29"
```
while this doesn't:
```
        "service.beta.kubernetes.io/aws-load-balancer-scheme"  = "internal"
        "service.beta.kubernetes.io/aws-load-balancer-subnets" = "subnet-0c6c0664f13690437,subnet-03d1cd3e2b4516d55,subnet-0afdec0b7949e7c29"
```

Also, I am not sure why I have to use the `aws-load-balancer-subnets` annotation my private subnets are tagged with:
> Key – kubernetes.io/role/internal-elb
    Value – 1

as described in the docs: https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html

**Comment by kishorj** [comment]
@franciscoprin, it is due to this annotation:
```
service.beta.kubernetes.io/aws-load-balancer-type:  "nlb"
```
the service gets reconciled by CCM.

There are a couple options:
1. Install AWS Load Balancer controller v2.5.x or later and recreate the service
2. Set the spec.loadBalancerClass or the aws-load-balancer-type as per https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/service/nlb/#configuration
