### ISSUE TITLE
Tags annotation not independent

### ISSUE THREAD

**Issue by stephan242** [kubernetes-sigs/aws-load-balancer-controller#3294]
**Describe the bug**
Right now, if two Ingresses share an ALB, then both of them need an identical `alb.ingress.kubernetes.io/tags` annotation. I want to have different `Name` tags for each Ingress, to be able to see which ALB rule belongs to which microservice in the AWS Load Balancer WebUI in the first column of the "Listener rules" view.

However I get this error:
```
{"level":"error","ts":"2023-07-26T12:35:28Z","msg":"Reconciler error","controller":"ingress","object":{"name":"mynamespace-myenv"},"namespace":"","name":"mynamespace-myenv","reconcileID":"9c3fa25f-4821-442a-99d6-55398d765aa6","error":"conflicting tag Name: mynamespace-myenv | mynamespace-myenv-mymicroservicename"}
```

This seems related to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1940 which explains that ALB,TG and SG all need to have the same Tags ... however there is only one SG per ALB, but there can be many Ingresses per ALB.

So essentially I would like to see `mynamespace-myenv-mymicroservicename` in the "Name tag" column of the AWS Console "Listener rules" table, instead of `mynamespace-myenv` for each of these dozens of rules I have there.

**Steps to reproduce**
Create 2 Ingresses with diverging tag annotations.

**Expected outcome**
Allow different Ingresses to have diverging Tag annotations. Meanwhile document that all ingresses need to have identical Tag annotations if they share an ALB.

**Environment**

* AWS Load Balancer controller version: v2.5.2
* Kubernetes version: 1.27
* Using EKS (yes/no), if so version? yes, 1.27

**Additional Context**:

**Comment by oliviassss** [comment]
@stephan242, hi, unfortunately right now we do not allow multiple values for the same key for ingress group and agree we can improve here.
/kind feature

**Comment by M00nF1sh** [comment]
@stephan242 

Currently the tags are for all resources, including the loadbalancer(which is shared),  thus we require tags are not conflicting with each other.

What if we additional tag the rules with your ingress's name&namespace, will it suit your need?
