### ISSUE TITLE
 WAF and CloudFront integration

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [kubernetes-sigs/aws-load-balancer-controller#3298]
**Is your feature request related to a problem?**
I would like to see WAF and Cloudfront integration to since the alternative is to configure part of the deployment as k8s resources, another part using Terraform 

**Describe the solution you'd like**
Ingress annotations to define WAF and CloudFront resources to be created 

**Describe alternatives you've considered**
Having split configuration, some as k8s resources, some as terraform

**Comment by gytis-ivaskevicius** [comment]
**Risks:**
- CloudFront takes forever to be created, maybe it should not be k8s responsibility

**Comment by M00nF1sh** [comment]
@gytis-ivaskevicius 
I agree that this could be a useful feature but it will make our controller complicated. (e.g. there are many settings for WAF).
the currently approach we took is we ask users to create WAF through other tools(e.g. teraform and then specify the waf arn on Ingresses).
We are lacking cloudfront support though. would it suit your need if we add support to specify a  cloudfront ARN on Ingress?(however the cloudfront settings itself should be managed by other tools)

**Comment by DameonSmith** [comment]
@M00nF1sh I would really like support for providing a cloud front distribution ARN that the controller could then register itself to. Ideally it could register different services as different origins with path forwarding in the distribution too. 

I'm not sure what the options are to support something like this now would be. Is there a stop gap where we could manually register these load balancers with a distribution? I've been cautious to do that up until now as I'm not sure how deterministic the ARNs are, I wouldn't want a load-balancer to be deallocated behind the scenes and have that cause a service interruption.
