### ISSUE TITLE
Compatibility matrix with EKS/Kubernetes version

### ISSUE THREAD

**Issue by ramachittala** [kubernetes-sigs/aws-load-balancer-controller#3302]
It would be great if we have the compatibility matrix with EKS/Kubernetes version. So that we can compare easily with the versions.

**Comment by oliviassss** [comment]
@ramachittala you mean the AWS LBC versions compatibility with the EKS/K8s version? We call it out with our release note: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases. For example, v2.5.4 requires EKS/K8s 1.22+. But sure we can improve the docs by adding a matrix.
/kind documentation

**Comment by anhadgill23** [comment]
What's the highest version of Kubernetes it supports, though? It needs to be clarified. 

We are running v2.4.4. Does it work with Kubernetes v1.26? I couldn't find it in the release notes.

**Comment by oliviassss** [comment]
@anhadgill23 we support upto k8s 1.27

**Comment by anhadgill23** [comment]
Thank you. If you could add a compatibility matrix explicitly, that'd be helpful.

**Comment by oliviassss** [comment]
@anhadgill23, Hi, we have this compatibility matrix in our live doc. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/#supported-kubernetes-versions
I'm closing this issue for now, thanks.
