### ISSUE TITLE
Automatically tag AWS resources using Ingress/Service labels

### ISSUE THREAD

**Issue by NickLarsenNZ** [kubernetes-sigs/aws-load-balancer-controller#3303]
**Is your feature request related to a problem?**

I see there is a way to add tags to the AWS resources: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/annotations/#resource-tags.

Having a single annotation with a list of tags makes extending the list near impossible (eg: if using Kustomize). Also, it means duplication of already existing labels.

It would be nice if we could automatically use labels that are already on the resource.

**Describe the solution you'd like**

- Ability to use `Ingress` or `Service` labels as AWS tags.
- A filter to exclude unnecessary tags (eg: `app`) or include only matching label prefixes (eg: `example.com/*`.

**Describe alternatives you've considered**

Simply using the `alb.ingress.kubernetes.io/tags` annotation, with impending copy/paste errors, overwriting the list on subsequent Kustomize layers.

**Comment by oliviassss** [comment]
@NickLarsenNZ, thanks for pointing out. I think there's some improvement we can do for the AWS resource tags, but there's limit that for each resource it could only have up to 50 tags https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html. Can you please explain a bit about the use case that why you need the labels to also be in the AWS tags? Thanks.

**Comment by M00nF1sh** [comment]
@NickLarsenNZ 

We may not use all labels as AWS tags since these labels are used to organize k8s resources.  But in general i think its a good idea, maybe have only pass certain labels with specific prefix as AWS resource tags.

However, such security related features requires AWS AppSec reviews, and there is already tags annotation alternative, i'm afraid we don't be able to implement this soon.

**Comment by NickLarsenNZ** [comment]
Thanks for the replies.

> Can you please explain a bit about the use case that why you need the labels to also be in the AWS tags?

I have two use cases:
- To be able to see which environment/app/tenants the target groups belong to (same with the load balancer, but with less granular tags).
- To be able to build SLO dashboards using scraped metrics from Cloudwatch. That way we can have consistent labels being used in prometheus queries (eg: `example.com/tenant: cyberdyn`.

The current way to add labels is too inflexible:
- Cannot be appended to unless using a templating tool such as Helm. In our case we use Kustomize to add to the manifests at various layers (base layer, app variant layer (sometimes), then per tenant layer).
- Is a duplication of already existing information. At best, that is simply duplication (I can live with that), but often leads to copy/paste errors down the track which has the consequence of historical metrics having the wrong labels and polluting existing metrics.

> but there's limit that for each resource it could only have up to 50 tags

That is good to know, but I don't think that should be a reason not to. Everything has limits, and perhaps a failure Event (or validating webhook) could inform the implementor when there are too many tags.

> But in general i think its a good idea, maybe have only pass certain labels with specific prefix as AWS resource tags.
>
> However, such security related features requires AWS AppSec reviews, and there is already tags annotation alternative, i'm afraid we don't be able to implement this soon.

Yes, perhaps an opt in for pattern matching for users who don't need it, or deem their labels too sensitive to not leave Kubernetes (I can't imagine the case in which labels would be ok in the Kubernetes cluster but not ok in the load balancer for a security reason - could you give an example?).
