### ISSUE TITLE
Certificate discovery doesn't work for imported certs

### ISSUE THREAD

**Issue by mitter91** [kubernetes-sigs/aws-load-balancer-controller#3308]
**Describe the bug**
Certificate discovery doesn't work for imported certs

**Steps to reproduce**
Import to ACM certificate from non-AWS issuer
try to use autodiscovery in ingress resource to find that cert

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version - 2.5.4
* Kubernetes version - 1.26
* Using EKS (yes/no), if so version? - yes

**Comment by oliviassss** [comment]
@mitter91, what's the type of the imported cert? they controller currently only support RSA_2048, we will have the fix in our coming release to include all the supported types.
similar issue: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2719
fix: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3314

**Comment by mitter91** [comment]
@oliviassss RSA-4096, got it, if problem was in type, and fix is on the way, you can close issue

**Comment by oliviassss** [comment]
@mitter91, We have shipped the improvement with v2.6.0 release, I'm closing the issue as for now. Please feel free to reopen if you have any issue. Thanks
