### ISSUE TITLE
ALB rules added by any other tools was deleted by aws-loader-balancer-controller 

### ISSUE THREAD

**Issue by tiandengpan** [kubernetes-sigs/aws-load-balancer-controller#3311]
Hi team:
The rules in an ALB added by some thing else was deleted by aws-loader-balancer-controller.
How can I keep the rules that was not created by aws-loader-balancer-controller?

**Comment by oliviassss** [comment]
@tiandengpan, Hi it's an expected behavior that the controller reconciles based on the manifest, so it will revert the "manual" change on the managed resources. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/how-it-works/

**Comment by tiandengpan** [comment]
Thanks you,
