### ISSUE TITLE
Reconciler not working when resources is deleted outside process

### ISSUE THREAD

**Issue by svelango** [kubernetes-sigs/aws-load-balancer-controller#3317]
**Describe the bug**
Created a NLB via AWS Load Balancer controller.  Deleted the resources via Console. See this error in log that List Target failing but doesn't go beyond it.

{"level":"error","ts":"2023-08-08T12:08:14Z","msg":"Reconciler error","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","TargetGroupBinding":{"name":"k8s-ingressn-ingressn-45716c0d9d","namespace":"ingress-nginx"},"namespace":"ingress-nginx","name":"k8s-ingressn-ingressn-45716c0d9d","reconcileID":"b7a8e56e-de60-4498-8015-de753e15d8de","error":"TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:region:awsaccountid:targetgroup/k8s-ingressn-ingressn-45716c0d9d/a13ec8f869a991b7' not found\n\tstatus code: 400, request id: 42066138-8aeb-44b0-bd33-e649652c3e59"}

{"level":"error","ts":"2023-08-08T12:08:14Z","msg":"Reconciler error","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","TargetGroupBinding":{"name":"k8s-ingressn-ingressn-ff94aa5659","namespace":"ingress-nginx"},"namespace":"ingress-nginx","name":"k8s-ingressn-ingressn-ff94aa5659","reconcileID":"7833de47-9a3b-4d16-863d-ed6c21eb4b45","error":"TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:region:awsaccountid:targetgroup/k8s-ingressn-ingressn-ff94aa5659/b6dd126ca2fccdcd' not found\n\tstatus code: 400, request id: c19919fc-ddbc-4b54-b073-98061d051f60"}

{"level":"error","ts":"2023-08-08T12:08:14Z","msg":"Reconciler error","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","TargetGroupBinding":{"name":"k8s-ingressn-ingressn-45716c0d9d","namespace":"ingress-nginx"},"namespace":"ingress-nginx","name":"k8s-ingressn-ingressn-45716c0d9d","reconcileID":"b1a9c945-0a36-4b06-898d-ff99f794d033","error":"TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:region:awsaccountid:targetgroup/k8s-ingressn-ingressn-45716c0d9d/a13ec8f869a991b7' not found\n\tstatus code: 400, request id: 3c7317a3-7fac-48c0-a74f-3563e69982b5"}

**Steps to reproduce**

**Expected outcome**
Was expecting a new NLB will be created 

**Environment**

* AWS Load Balancer controller version 2.5.4
* Kubernetes version1.23
* Using EKS (yes/no), if so version? eks.8

**Additional Context**:

**Comment by oliviassss** [comment]
@svelango, hi, we do not recommend manually change the resources managed by the controller. The controller auto-reconciles every 10hr by default to revert the manual changes. pls check the note here: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/how-it-works/

**Comment by svelango** [comment]
Thanks.  Understand out of band is not recommended. Just curious as part of deployment can we update the 10hrs to 5hrs or something.

**Comment by oliviassss** [comment]
@svelango, yes you can update the it to 5hrs or other interval you need by the controller runtime flag `--sync-period`, see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/configurations/#sync-period

I'm closing this issue as for now, feel free to reach out if you have more questions. Thanks.
