### ISSUE TITLE
Changing the type of the service by operator from LoadBalancer to ClusterIP does not remove the Load balancer

### ISSUE THREAD

**Issue by rkosyk** [kubernetes-sigs/aws-load-balancer-controller#3324]
I have MongoDB operator in my EKS cluster.
The operator created the next LoadBalancer services:
```
$ kubectl get services -n psmdb-operator
NAME          TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)           AGE
test-cfg-0    LoadBalancer   172.20.237.147   k8s-psmdbope-testcfg0-96d90d83c4-38010c209bdf5a60.elb.us-east-1.amazonaws.com   27017:30990/TCP   4h20m
test-cfg-1    LoadBalancer   172.20.195.92    k8s-psmdbope-testcfg1-7227b0edfc-5fb0b583960eaa06.elb.us-east-1.amazonaws.com   27017:31247/TCP   51m
test-cfg-2    LoadBalancer   172.20.33.119    k8s-psmdbope-testcfg2-1a8ff0d1c2-8b9fa2288be92317.elb.us-east-1.amazonaws.com   27017:30197/TCP   51m
test-rs0-0    LoadBalancer   172.20.218.165   k8s-psmdbope-testrs00-92cdc34329-6529cd20e84e0814.elb.us-east-1.amazonaws.com   27017:31885/TCP   4h20m
test-rs0-1    LoadBalancer   172.20.209.139   k8s-psmdbope-testrs01-0792976850-5a0a2d50c4969f39.elb.us-east-1.amazonaws.com   27017:31459/TCP   51m
test-rs0-2    LoadBalancer   172.20.202.87    k8s-psmdbope-testrs02-ff0148b8ae-88e5029ad45a98f0.elb.us-east-1.amazonaws.com   27017:32705/TCP   51m

```

When I ask the operator to change the type of the services from LoadBalancer to ClustrIP implicitly by changing its custom resource, it does changes:
```
$ kubectl get services -n psmdb-operator
NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
test-cfg-0    ClusterIP   172.20.237.147   <none>        27017/TCP   4h27m
test-cfg-1    ClusterIP   172.20.195.92    <none>        27017/TCP   58m
test-cfg-2    ClusterIP   172.20.33.119    <none>        27017/TCP   58m
test-rs0-0    ClusterIP   172.20.218.165   <none>        27017/TCP   4h27m
test-rs0-1    ClusterIP   172.20.209.139   <none>        27017/TCP   58m
test-rs0-2    ClusterIP   172.20.202.87    <none>        27017/TCP   58m

```
But when checking in the AWS console we can see that Load balancers exist and are not removed.

If I change the service type from LoadBalancer to ClusterIP directly on the same services by hand I can see in AWS console that Load balancers have been removed.

What can be the reason for such different behavior? When the type of the services changed manually by me and when by the operator? In the first case, Load balancers in AWS console were not removed, in the second case, they were removed.

**Environment**

* AWS Load Balancer controller version - 2.5.4
* Kubernetes version - 1.23
* Using EKS - yes

**Comment by oliviassss** [comment]
@rkosyk, Hi, I'm not very familiar with the MangoDB operator, how did it change the service from LoadBalancer to ClusterIP?

**Comment by oliviassss** [comment]
@rkosyk-dh-nf, sorry for the late reply. yeah from the even it looks like the LB has been deleted by the controller. Can you please double check in the controller's log to see if it deletes the resources? If so, the issue might rely in else where.
