### ISSUE TITLE
Loadbalancer Controllers of different clusters running on Same VPC try to manage same SG and cause deadlock 

### ISSUE THREAD

**Issue by kakarotbyte** [kubernetes-sigs/aws-load-balancer-controller#3325]
**Describe the bug**
LoadBalancer Controllers of different clusters running on Same VPC try to manage same Sg and cause deadlock 

**Steps to reproduce**

Launch 2 clusters in Same VPC.

**Cluster A:**
- Install Karpenter
- Install AWS LoadBalancer Controller with IRSA.
- Create a test deployment, service, ingress.

**Cluster B:**
- Has cluster SG
-  Nodes use cluster SG.
-  Install AWS LoadBalancer Controller with IRSA.
- AWS LoadBalancer controller manages the SG rules of the Cluster B SG.
- Create a test deployment, service, ingress.

**Reproduction:**
- In Cluster A create a Karpenter node template (AWSNodeTemplate) which uses **cluster SG of Cluster B**
- Launch nodes using that Karpenter node template in Cluster A.
- Delete/remove the nodes launched by Karpenter.

**Reproduction Outcome**
- At this point **AWS LoadBalancer Controller of Cluster A** will cache **cluster SG of Cluster B** as one of the backend node Security group. As this is considered as a backend end node SG by AWS LoadBalancer Controller it will try to manage and reconcile it continously.
- This is a problem because each SG rule that is managed by AWS LoadBalancer controller has description `elbv2.k8s.aws/targetGroupBinding=shared`. Since both Cluster's **AWS LoadBalancer Controller's**  will assume the following:
   -  Cluster A's AWS LoadBalancer Controller:  It will consider Rule Added by cluster B's **AWS LoadBalancer Controller's** to be not valid and will try to delete them using RevokeSecurityGroupIngress API. At the same time if there are any rules it needs to add it will add them using AuthorizeSecurityGroupIngress API
   - Cluster B's AWS LoadBalancer Controller:  It will consider Rule Added by cluster A's **AWS LoadBalancer Controller's** to be not valid and will try to delete them using RevokeSecurityGroupIngress API. At the same time if there are any rules it needs to add it will add them using AuthorizeSecurityGroupIngress API
- Essentially the change in SG will cause ALB to fail health checks intermittently.
   
**Current workarounds**
 **Workaround 1:**
    -  Allow all traffic from VPC CIDR in SG. this will bypass the deadlock cause ALB health checks to not fail. 
 **Workaround 2**
    - Two clusters in same vpc should have different set of SGs above with current versions. Make sure that cluster A is not using any node SG's from cluster B as its own node SG. Once this is confirmed restart the LoadBalancer controller to clear cache.
   ```  
   $ kubectl scale deployment -n kube-system aws-load-balancer-controller --replicas 0
   $ kubectl scale deployment -n kube-system aws-load-balancer-controller --replicas 1
   ```
**Expected outcome**
- Expected outcome is that LoadBalancer Controller's should not manage the rules it didnt create. 

**Feature enhancement request:**
- To resolve this please utilize [Tag security group rules](https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html#:~:text=descriptions%2Degress%20commands.-,Tag%20security%20group%20rules,-Add%20tags%20to) and add an unique identifier.

**Comment by dlmather** [comment]
I commented on an older ticket for this, but I have a patch here https://github.com/dlmather/aws-load-balancer-controller/tree/dmather/patch-aws-lb-controller-sg-conflicts to support tagging by cluster name to handle this. I think tackling the full problem is a bit more complicated than what my solution handles (there are issues around situations where the same SG rule is being added by multiple clusters), but if there is interest I am willing to try to clean up what I have and raise a PR here.

**Comment by M00nF1sh** [comment]
added this to our backlog. i think we can solve this via tagging on SG rules.
PR are definitely welcome :D
