### ISSUE TITLE
AWS load balancer controller takes a long time to start (to fully operate)

### ISSUE THREAD

**Issue by kwarunek** [kubernetes-sigs/aws-load-balancer-controller#3326]
**Describe the bug**
We have deployed the aws-load-balancer-controller with 2 replicas. However, during the leader change (due to rotation or the TTL of the worker node), the other replica takes over leadership. This transition takes a considerable amount of time to fully complete operations. It appears that the new replica rebuilds the model and attempts to reconcile (reread all TG/ALB from AWS API to be precise) all configurations, even for the tg/alb that do not require it.

In the initial 10-20 minutes after starting or assuming leadership, any changes made to the endpoints experience delays and are not promptly reflected in the TG/ALB. This delay persists until the 'start/first_reconcile' process is finished.

This makes no sense to deploy more than 1 instance of controller.

From the metrics (attached screenshots) we deduce that it's probably due to API limits/throttling.

**Expected outcome**
The model needs to be rebuilt, but reconciliation could potentially rely on a timestamp (endpoint last change vs tgb last reconcile) within the TargetGroupBinding. This approach would involve considering only the changes that have occurred.

**Environment**

* AWS Load Balancer controller version 2.5.2
* Kubernetes version 1.24
* Using EKS: yes

**Additional Context**:
Number of
* provisioned ALB by controller: ~100
* TargetGRoupBindings: ~ 1500

ALB controller args:

- --cluster-name=zzzzzz
- --ingress-class=alb
- --aws-region=yy-xxxx-1
- --aws-vpc-id=vpc-xxxxxxxx
- --enable-shield=false

![Screenshot 2023-08-10 at 00-41-47 AWS Load Balancer Controller - EKS - k8s-apps-v1 - Dashboards - Grafana](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/670887/1ddd23b1-56c2-453b-989b-d9c488be7b53)
![Screenshot 2023-08-10 at 00-40-31 AWS Load Balancer Controller - EKS - k8s-apps-v1 - Dashboards - Grafana](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/670887/95bd15d4-1e42-4d35-a681-ea833412bbbe)

**Comment by M00nF1sh** [comment]
/area performance
@kwarunek thanks for sharing this, this is a interesting problem as the standby replica only have cache for k8s Objects,  but not cache for AWS objects(where the master replica have such cache in memory).

I think the timestamp is a good idea to skip already fully reconciled TGBs.

BTW, Would you help share the controller logs as well, would like to understand the operations done in the controller.

**Comment by oliviassss** [comment]
@kwarunek, hi, would you consider enabling RGT API by via controller flag `--feature-gates=EnableRGTAPI=true`? It can avoid ELB API throttling issue and will help to reduce the reconcile time, especially for the case where there are numerous resources. You can check more about the feature gate flag in our [release note](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.5.2) and [live doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/configurations/#feature-gates). Please be mindful that RGT API does not work on private clusters.

**Comment by shraddhabang** [comment]
@kwarunek We have also made some improvements around this area in v2.7.1. Could you please upgrade to this new version and see if this resolves your problem?

**Comment by kwarunek** [comment]
It's a bit better but still it takes ~10minutes
 
![Screenshot 2024-05-13 at 14-26-16 AWS Load Balancer Controller - AWS - Dashboards - Grafana](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/670887/d8d38c85-3810-4931-aa14-db0f486adbbc)
![Screenshot 2024-05-13 at 14-26-49 AWS Load Balancer Controller - AWS - Dashboards - Grafana](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/670887/ca50a11c-351f-4603-a6a1-7dc1e7abc10e)

**Comment by yuvraj9** [comment]
++ we are facing this issue right now. Our aws api also gets throttled

**Comment by xdrus** [comment]
/reopen

There are customers affected by this, especially at bigger scale.

**Comment by zac-nixon** [comment]
The fix for this was released under 2.9.1.
