### ISSUE TITLE
What other variables can I use for defaultTags values?

### ISSUE THREAD

**Issue by tomroberts-srt** [kubernetes-sigs/aws-load-balancer-controller#3328]
Hi all

Under the [resource annotations docs](<https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/annotations/#resource-tags>), there's an example of the default tags where the values are populated using variables.
```
elbv2.k8s.aws/cluster: ${clusterName}
ingress.k8s.aws/stack: ${stackID}
ingress.k8s.aws/resource: ${resourceID}
```

Can someone please point me in the direction of what other variables (e.g. `${clusterName}`) would be available to defaultTags if I wanted to expand on this list?

Thanks!

**Comment by M00nF1sh** [comment]
@tomroberts-srt 
these tags are populated by default by the controller. for customer defined tags(e.g. via alb.ingress.kubernetes.io/tags annotation), you cannot use variables/placeholders, you can only use plain-text key-value pairs.

**Comment by oliviassss** [comment]
@tomroberts-srt, we have an example for the `alb.ingress.kubernetes.io/tags: Environment=dev,Team=test` in our live doc [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#resource-tags). I'm closing this issue as for now. Thanks
