### ISSUE TITLE
Re-use an existing alb

### ISSUE THREAD

**Issue by pavelpp** [kubernetes-sigs/aws-load-balancer-controller#3338]
**Is your feature request related to a problem?**
I am trying to re-use an existing alb, managed separately, but I found that the annotation [alb.ingress.kubernetes.io/load-balancer-name](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#load-balancer-name) does not work. I am just getting an error "FailedDeployModel","message":"Failed deploy model due to DuplicateLoadBalancerName: A load balancer with the same name 'public-alb' exists, but with different settings". I compared the settings of the existing alb to the one that alb controller created for EKS services. Apart from tags and different rules they look identical.

**Describe the solution you'd like**
I would like to re-use an existing alb I manage in a different terraform module. It already has certain static rules on https listener and I want alb controller to manage only the EKS-related rules per ingresses. I do not want alb controller to recreate my alb, nor tag it etc, etc.

**Comment by oliviassss** [comment]
Hi, we have duplicate requests for this feature and have it in our roadmap. You can check more info:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/228

**Comment by pavelpp** [comment]
@oliviassss not sure it's the same. Sounds like the last suggestion here https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/228#issuecomment-1660570114 is to use the alb.ingress.kubernetes.io/group.name which we are already using. I need to manage alb lifecycle externally.

**Comment by shraddhabang** [comment]
Closing this issue as we have duplicate [#228 ](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/228)
