### ISSUE TITLE
Permission denied with controller version 2.6.0

### ISSUE THREAD

**Issue by arturhoo** [kubernetes-sigs/aws-load-balancer-controller#3339]
**Describe the bug**

After upgrading the controller to version 2.6.0 using the Helm chart 1.6.0 and spinning up a new `Service` of type `LoadBalancer`, got the following permission denied:

```
Events:
  Type     Reason            Age   From     Message
  ----     ------            ----  ----     -------
  Warning  FailedBuildModel  32s   service  Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ...
```

Redacted decoded message: https://gist.github.com/arturhoo/e709b07b2ec865bb885bb91b6bc36d98

**Steps to reproduce**

1. Install AWS LB Controller as per installation instructions, including with the correct IAM policies.
2. Spin up a new `Service` of type `LoadBalancer` with the annotations `service.beta.kubernetes.io/aws-load-balancer-type: external` and `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip`
3. Observe error event on service

**Expected outcome**

Expected service to be provision correctly with an NLB.

**Environment**

* AWS Load Balancer controller version: 2.6.0
* Kubernetes version: 1.27
* Using EKS (yes/no), if so version? yes, platform version eks.4

**Additional Context**:

Reverting to 2.5.4 (helm chart 1.5.5) brings it back to a working state.

**Comment by oliviassss** [comment]
Hi, @arturhoo, looks like your controller is not authorized to tag the SGs. Can you double-check the IAM policy of your controller? https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json#L99C17-L99C17

**Comment by arturhoo** [comment]
Hey @oliviassss, thanks for the reply. I can confirm that the IAM policy contains the permissions you linked and match the rest of that policy.

Kindly note that our IAM policy was working before the upgrade and is now working after reverting back to 2.5.4.

**Comment by oliviassss** [comment]
@arturhoo, would you be able to share more error messages or logs? Thanks

**Comment by arturhoo** [comment]
Here are the only extra logs I have @oliviassss. These are coming from the `awsloadbalancercontroller` pods themselves:

```
{
  level:  'error',
  ts:     '2023-08-14T12:02:56Z',
  logger: 'backend-sg-provider',
  msg:    'Failed to auto-create backend SG',
  error:  'UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: <redacted>
	status code: 403, request id: 22a95990-e2be-4c39-afd9-88833e94b51f',
}
```

**Comment by arturhoo** [comment]
Hey @oliviassss - I have reviewed our policies once more and actually spotted an erroneous entry under the `CreateTags` statement. It was there based on a misunderstanding of scope down instructions on https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/#option-a-recommended-iam-roles-for-service-accounts-irsa:~:text=Example%20condition%20for%20cluster%20name%20resource%20tag%3A

Apologies for creating this issue in error.

**Comment by oliviassss** [comment]
@arturhoo, no worries at all! Glad it was resolved.
