### ISSUE TITLE
incompatible with in-tree legacy controller

### ISSUE THREAD

**Issue by pcheung-sfdc** [kubernetes-sigs/aws-load-balancer-controller#3340]
**Describe the bug**
This version doesn't play nice with the legacy in-tree controller. Every Service (type LoadBalancer) gets an NLB.

**Steps to reproduce**
Create a service with annotation `service.beta.kubernetes.io/aws-load-balancer-internal: "true"`, and `service.beta.kubernetes.io/aws-load-balancer-type: ""` (or any value here), and the aws-load-balancer-controller would create an NLB, when the expected behavior is to ignore, and let in-tree controller take over. (as documented [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#legacy-cloud-provider))

In fact, even without setting any annotations, the aws-load-balancer-controller would take over and create an NLB, as long as the Service type is LoadBalancer.

**Expected outcome**
I expect that by setting `service.beta.kubernetes.io/aws-load-balancer-type: ""`, the aws-load-balancer-controller would ignore, and let the in-tree controller take over. But regardless of what that is set to, as long as `service.beta.kubernetes.io/aws-load-balancer-internal: "true"` is set, it will always default to creating an NLB.

**Environment**

* AWS Load Balancer controller version 2.6.0
* Kubernetes version 1.23
* Using EKS (yes/no), if so version? yes, v1.23

**Additional Context**: 
N/A

**Comment by pcheung-sfdc** [comment]
Disabling the ServiceMutatorWebhook resolved my issue.

**Comment by pcheung-sfdc** [comment]
I can see when the [PR](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2925/files#diff-511c96c8a9a81485405fe349214d9b5fcf46502d4c16942fe6eb11a30f40afa5) was added for the webhook, it essentially made LBC the default for handling Service type LoadBalancers. This essentially disables CCM completely, and the documentation [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#legacy-cloud-provider) no longer applies. Is the recommended way to use CCM for creating Classic ELBs, at the same time using LBC to create NLBs to:
1. disable the webhook
2. add loadBalancerClass for Services needing NLB?

**Comment by oliviassss** [comment]
Thanks for reporting this, yes we need to improve the legacy provider section in our doc. We do have a warning in Installation for setting the default controller back to CCM: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/

/kind documentation
