### ISSUE TITLE
Support CrossZone disabled for ALBs

### ISSUE THREAD

**Issue by suket22** [kubernetes-sigs/aws-load-balancer-controller#3341]
**Is your feature request related to a problem?**
When creating LoadBalancer resources, I see that [we can specify the annotation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/) `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled` to toggle whether cross-zone should be enabled on the resulting NLB. 

However, there's no corresponding annotation that I can set on the `Ingress` resource, which results in cross-zone being enabled on the target groups created for the ALB. This is because target groups inherit the setting from the load balancer and ALBs always have cross-zone enabled.

If we have the option to disable cross-zone load balancing on an ALB, we will be able to perform a zonal shift [as described here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/zonal-shift.html). 

**Describe the solution you'd like**
Ideally, I'd like support for a new annotation (maybe `alb.ingress.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled` ?) for Ingress resources. I think we can default to `true` to ensure backwards compatibility. 

The support for this was added last year as described in https://aws.amazon.com/about-aws/whats-new/2022/11/application-load-balancers-turning-off-cross-zone-load-balancing-per-target-group/

**Describe alternatives you've considered**
No alternative that I can think of.

**Comment by johngmyers** [comment]
My recommendation is that settings that affect the load balancer as a whole should only be fields in `IngressClassParams` and should not be supported as new annotations on the Ingress.

**Comment by oliviassss** [comment]
We should support it on ALB via TG attributes already: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#custom-attributes.
For the NLB side the annotation has deprecated since v2.3.0 in favor of `service.beta.kubernetes.io/aws-load-balancer-attributes`: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#load-balancer-attributes

**Comment by suket22** [comment]
Thanks for the pointer @oliviassss, I totally missed `alb.ingress.kubernetes.io/load-balancer-attributes` and that works for the use case I was mentioning above. I'll close this.
