### ISSUE TITLE
[Feature Request] Allow adding additional tags to the Backend Security Group programatically

### ISSUE THREAD

**Issue by wilief** [kubernetes-sigs/aws-load-balancer-controller#3344]
**Is your feature request related to a problem?**
When attempting to set IAM policies to restrict certain actions to resources with specific tags applied to them this becomes a problem when trying to programmatically set the tags for the Backend Security Group as the automatic creation of this Security Group only sets two tags by default "elbv2.k8s.aws/cluster: <cluster_name>" and "elbv2.k8s.aws/resource: backend-sg" without the use of Default tags.

**Describe the solution you'd like**
A new annotation or setting from the controller level that would allow setting the tags for the Backend Security Group without the use of the DefaultTags

**Describe alternatives you've considered**
Considered using DefaultTags but this does not allow for overwriting values for keys that are set as well as creating the security group resource manually but I am trying to avoid creating the resource manually.

**Comment by oliviassss** [comment]
@wilief, thanks for brining this up. Just for better understanding, these tags are on controller level right? and they are not expected to be removed/updated if there's any update/deletion on ingress or service resource?

/kind feature

**Comment by wilief** [comment]
@oliviassss, Thank you for your response. My understanding is that these tags would be set on the controller level.

**Comment by oliviassss** [comment]
@VarunTyagi86, would you be able to provide the ingress manifest, and also the controller logs during which this issue occurred? thanks
