### ISSUE TITLE
failed waiting for *v1beta1.IngressClassParams Informer to sync

### ISSUE THREAD

**Issue by djcee-b** [kubernetes-sigs/aws-load-balancer-controller#3345]
**Describe the bug**
We have upgraded to 2.6.0 of the image and 1.6.0 of the chart for aws-load-balancer-controller and we are getting the following error in the logs: Timeout: failed waiting for *v1beta1.IngressClassParams Informer to sync

We was originally on 2.5.0 and we ran the following command to upgrade the CRDs as described in the release notes:
kubectl apply -k "http://github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master

The error message comes every time the pod restarts

**Steps to reproduce**
1. Upgrade Image Version from 2.5.0 to 2.6.0
2. Upgrade Chart Version to 1.6.0

**Expected outcome**
The error message not to appear

* AWS Load Balancer controller version: 2.6.0
* Kubernetes version: 1.24.16
* Using EKS (yes/no), if so version? Yes-  v1.24.16-eks-2d98532

**Comment by oliviassss** [comment]
@djcee-b, hi, did you try `helm repo update` before you upgrade the controller? the link couldn't be opened, can you please double check the CRDs have been updated?

**Comment by djcee-b** [comment]
Hi All
Reapplying the crds fixed the issue!
Thanks

**Comment by zephyros-dev** [comment]
I'm also seeing this issue on Chart version 1.6.0 whenever the pod is restarted. It doesn't seems to affect anything afterward, but I'd like to know why it happened and if this is "normal" behavior or not.
