### ISSUE TITLE
Error endpoints "response-403" not found with alb.ingress.kubernetes.io/actions.${action-name}

### ISSUE THREAD

**Issue by chary1112004** [kubernetes-sigs/aws-load-balancer-controller#3349]
**Describe the bug**

We are facing issue while describe ingress

```
Rules:
  Host                         Path  Backends
  ----                         ----  --------
 example.com
                               /metrics                 response-403:use-annotation (<error: endpoints "response-403" not found>)
```

ingress manifest
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.response-403: |
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"403 External access to endpoint not allowed"}}
    alb.ingress.kubernetes.io/actions.root-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301", "Path": "/auth"}}'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/group.name: alb-ingress
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "8443"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2019-08
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: application
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-09-19T04:10:23Z"
  finalizers:
  - group.ingress.k8s.aws/alb-ingress
  generation: 2
  labels:
    app: application
    app.kubernetes.io/managed-by: Helm
  name: application
  namespace: default
  resourceVersion: "417101858"
  uid: c7047b08-d71c-455b-a6cb-88277b14fe05
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: response-403
            port:
              name: use-annotation
        path: /metrics
        pathType: ImplementationSpecific
      - backend:
          service:
            name: application-service
            port:
              number: 8443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - example.com
    secretName: example-secret
```

**Expected outcome**
- And while we access from https://example.com/metrics it still returns metric data that we expect it returns 403.
- There is no error due to describe ingress.

Any solution to resolve this issue would be very much appreciated.

**Environment**

* AWS Load Balancer controller version: v2.5.2
* Kubernetes version: 1.25
* Using EKS (yes/no), if so version?

**Comment by chary1112004** [comment]
I realize that in listerner if I change path: /metrics higher than path: / then it will works as expect.
So how could we set priority in the ingress?

**Comment by oliviassss** [comment]
@chary1112004, Does the ingress reconcile successfully? If so, it might be something else. I found some online discussions on this error, please check if it helps with your case

- https://stackoverflow.com/questions/63558461/endpoints-default-http-backend-not-found-in-ingress-resource
- https://stackoverflow.com/questions/59844622/ingress-configuration-for-k8s-in-different-namespaces/59845018#59845018

**Comment by chary1112004** [comment]
Hi @oliviassss ,

Thank you for the feedback. 

For your question: **Does the ingress reconcile successfully?** -> Yes, it is still reconcile successfully.

And I recognize that if I put **application-service** to defaultBackend then the default backend in ingress always get evaluated last (Refer from https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/695#issuecomment-433519111). And while we access from https://example.com/metrics that it returns 403 as expectation.

However, while we describe ingress, it is still appear error
```
response-403:use-annotation (<error: endpoints "response-403" not found>)
```

Regards!

**Comment by oliviassss** [comment]
@chary1112004, nice to hear it works out for you. I think it might be some rendering issue of the `kubectl describe` cli
