### ISSUE TITLE
Ingress can not be deleted when securitygroups updated

### ISSUE THREAD

**Issue by haorenfsa** [kubernetes-sigs/aws-load-balancer-controller#3357]
**Describe the bug**
Ingress can not be deleted when securitygroups updated in the meantime by other ingress in the same group

**Steps to reproduce**
- Add `Ingress A` of `ingress group A` with `securitygroup A`;
- Add `Ingress B` of `ingress group A` with `securitygroup A & B`;
- Delete `Ingress A`

Your would see events like this:
```
LAST SEEN   TYPE      REASON                   OBJECT                                                MESSAGE
18m         Warning   FailedBuildModel         ingress/ingressA                          Failed build model due to conflicting securityGroups: [sg-a] | [sg-a sg-b]
```

**Expected outcome**
A can be deleted

**Environment**

* AWS Load Balancer controller version
* Kubernetes version 1.26
* Using EKS (yes/no), if so version? yes, newest

**Additional Context**:

**Comment by oliviassss** [comment]
@haorenfsa, thanks for reporting, this is a bug, and we need to fix it
/kind bug
/assign

**Comment by zen** [comment]
@oliviassss When do you guys expect to fix that? 

I think this bug is wider than initially reported. We have an ingress created with 2 SGs, then it was edited for one Ingress instance and one more group added. Now we cannot add new services to it, all other services are unmanegable.

**Comment by haorenfsa** [comment]
keep open....

**Comment by haorenfsa** [comment]
keep open....

**Comment by WalterKhumalo** [comment]
Keep open..

**Comment by haorenfsa** [comment]
em. looks like it's not gonna be solved in a short time. For anyone run into this.

Here's our walk around solution:

we wrote a controller to scan all ingresses in same group. It gathers all the security groups in their annotations, and then use them to update these ingresses.

The deleting ingresses should also be updated until they're gone.
