### ISSUE TITLE
Be able to balance master nodes

### ISSUE THREAD

**Issue by safeops-marboleda** [kubernetes-sigs/aws-load-balancer-controller#3360]
**Is your feature request related to a problem?**
I was having issues using the controller in a K3s cluster, everything was created but no instance was attached to the target group. I realized the problem was my instances are master nodes, as I have a really small configuration. I removed the master and controlplane labels from the nodes and now everything works, but I don't know if this could cause problems to the normal behavior of the cluster, so I prefer to not have my nodes like that

**Describe the solution you'd like**
I would like to have an option to tell the controller to manage master nodes as well, if such option already exists I haven't found it.

**Describe alternatives you've considered**
My options are to manually delete the master and controlplane labels from my nodes, or having to create a bigger cluster having workers and master nodes. The first one I don't know if it's safe to do, and the second could be very complicated to get with the limited resources I have.

**Comment by oliviassss** [comment]
@safeops-marboleda, probably we can implement a feature flag to disable the label check for master nodes, and the default value is `false`. If it's set to `true`, we can remove the labelNodeRoleMaster here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/backend/endpoint_utils.go#L24C15-L24C34
You are welcome to contribute and raise a PR, thanks.

/kind feature
