### ISSUE TITLE
Option to set AuthenticationRequestExtraParams

### ISSUE THREAD

**Issue by ramnamy** [kubernetes-sigs/aws-load-balancer-controller#3362]
**Is your feature request related to a problem?**
I would like to set AuthenticationRequestExtraParams when enabling Auth so that I can send additional params to IdP

**Describe the solution you'd like**
I would like to have the option to set this AuthenticationRequestExtraParams via annotations

**Describe alternatives you've considered**
I can manually set AuthenticationRequestExtraParams but this is very hard to track

**Comment by shraddhabang** [comment]
@ramnamy You can set these using existing annotation ``alb.ingress.kubernetes.io/auth-idp-cognito`` for example 


``"alb.ingress.kubernetes.io/auth-idp-cognito":  {"userPoolARN":"arn:aws:cognito-idp:us-west-2:xxx:userpool/xxx","userPoolClientID":"my-clientID","userPoolDomain":"my-domain","authenticationRequestExtraParams":{"key":"value"}} ``
