### ISSUE TITLE
Possibly incorrect documentation for "service.beta.kubernetes.io/aws-load-balancer-security-groups" annotations

### ISSUE THREAD

**Issue by nick-telia** [kubernetes-sigs/aws-load-balancer-controller#3365]
**Describe the bug**
According to [the docs](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/4e697f8431094f1673f2f38e0c7f3ae3d22834bd/docs/guide/service/annotations.md) for the annotation `service.beta.kubernetes.io/aws-load-balancer-security-groups`:

> When this annotation is not present, the controller will automatically create one security group. The security group will be attached to the LoadBalancer and allow access from `inbound-cidrs` to the `listen-ports`. Also, the securityGroups for target instances/ENIs will be modified to allow inbound traffic from this securityGroup.

This paragraph resembles the one from the Ingress annotations doc page, although there are no corresponding annotations for a Service, that could also be seen in [pkg/annotations/constants.go](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/4e697f8431094f1673f2f38e0c7f3ae3d22834bd/pkg/annotations/constants.go#L25).

**Environment**

* AWS Load Balancer controller version 2.6.0
* Kubernetes version 1.27
* Using EKS (yes/no), if so version? eks.4

**Comment by oliviassss** [comment]
@nick-telia, thanks, we can track the issue in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3333
close because of duplicate

**Comment by nick-telia** [comment]
The issue is still present despite the fact that #3333 has been marked as "Closed".

Could #3365 be re-opened?
