### ISSUE TITLE
Consider versioning CRDs regularly

### ISSUE THREAD

**Issue by daodennis-ri** [kubernetes-sigs/aws-load-balancer-controller#3366]
**Describe the bug**
I've noticed that even though the CRDs change the version of the CRD does not change, I understand helm does not support CRDs beyond the first install and that's only if they are in the crds/ folder.

I believe this is the version specifically for one of the CRDs:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/4e697f8431094f1673f2f38e0c7f3ae3d22834bd/config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml#L39

If it is a specific design decision to lock the CRDs to version `v1alpha1` for instance could that be reflected in the developer documentation or READMEs?

**Expected outcome**
CRDs to be versioned when changes are made to them.
**Environment**

* AWS Load Balancer controller version
Any
* Kubernetes version
Any
* Using EKS (yes/no), if so version?
Yes

**Additional Context**:

Thank you!

**Comment by oliviassss** [comment]
@daodennis-ri, the TGB CRD contains multiple versions, we are now supporting `v1beta1`: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/4e697f8431094f1673f2f38e0c7f3ae3d22834bd/config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml#L198C1-L198C18
the `v1alpha1` is for backward compatibility.

**Comment by oliviassss** [comment]
@daodennis-ri, I'm closing this issue as for now, please feel free to reach out if any questions, thanks
