### ISSUE TITLE
v2.6.0 Release contains wrong app version

### ISSUE THREAD

**Issue by dgdevops** [kubernetes-sigs/aws-load-balancer-controller#3367]
**Describe the bug**
The source code of the v2.6.0 Release contains wrong application version in the Chart.yaml & values.yaml files.

**Steps to reproduce**
N/A

**Expected outcome**
AS IS:
Chart.yaml:
```
version: 1.5.5
appVersion: v2.5.4
```

values.yaml:
`image.tag: v2.5.4
`

SHOULD BE:
Chart.yaml:
```
version: 1.6.0
appVersion: v2.6.0
```

values.yaml:
`image.tag: v2.6.0`

**Environment**
N/A

* AWS Load Balancer controller version v2.6.0
* Kubernetes version N/A
* Using EKS (yes/no), if so version? N/A

**Additional Context**:

**Comment by oliviassss** [comment]
We did bump up the version in Chart.yaml: https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/Chart.yaml#L4
Can you please verify your helm chart by running `helm repo update`?

**Comment by dgdevops** [comment]
Hello @oliviassss,
The `helm repo update` fetches the correct Chart.yaml & values.yaml and yes, the master branch contains the updates for v2.6.0, however the v2.6.0 Release has wrong application version in its `Source code (zip)` & `Source code (tar.gz)` files. It seems the v2.6.0 [Release](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.6.0) was created based on the v2.5.4 code.

**Comment by oliviassss** [comment]
@dgdevops, I'm closing this issue for now, feel free to reach out if you have more questions, thanks
