### ISSUE TITLE
When using 2.6.0 with NLB, security group are not being associated with annotations.

### ISSUE THREAD

**Issue by neeraj-n-singh** [kubernetes-sigs/aws-load-balancer-controller#3376]
**Describe the bug**
After adding annotations into the ingress for security group while using lb-controller 2.6.0 with NGINX ingress controller, the NLB was created but the security group was never attached to it.
            "service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout": "60",
            "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": true,
            "service.beta.kubernetes.io/aws-load-balancer-type": "nlb",
            "service.beta.kubernetes.io/aws-load-balancer-backend-protocol" : "tcp",
            "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol" : "*",
            "service.beta.kubernetes.io/aws-load-balancer-security-groups" : "sg-123456"

**Steps to reproduce**
1. Install aws-lb-controller 2.6.0 using helm.
2. Create nginx ingress object along with the above annotations.
3. Ingress object will be created with NLB
4. Login to AWS console, and look for security section and there was no security group attached to NLB.

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* AWS Load Balancer controller version: 2.6.0
* Kubernetes version: 1.23
* Using EKS (yes/no), if so version? 1.23

**Additional Context**:

**Comment by oliviassss** [comment]
@neeraj-n-singh, would you be able to share the controller logs so we can have more info?

**Comment by nrjsingh167** [comment]
It was on dev cluster and I re-created it from scratch. When I checked the controller logs in the past, I couldn't see any error on the same.  But now I can see this is fixed on the fresh cluster but the reason is not yet known to me.

**Comment by oliviassss** [comment]
@nrjsingh167, thank you, feel free to reach out if you encounter it again, we can debug via the controller logs.
