### ISSUE TITLE
HTTP/3?

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-load-balancer-controller#3378]
Is HTTP/3 in your roadmap? When?

**Comment by oliviassss** [comment]
I'd say the limitation is from ELB side, currently HTTP/3 is not supported in aws elastic load balancing: https://aws.amazon.com/elasticloadbalancing/features/
closing this issue for now

**Comment by khteh** [comment]
I don't see HTTP/3 in the URL. Where is this feature tracker?
