### ISSUE TITLE
It's works with eks fargate?

### ISSUE THREAD

**Issue by oliverdavidnoguerasanmartin** [kubernetes-sigs/aws-load-balancer-controller#3379]
I created  example game-2048 from https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html.
Alb created correctly and a rule with target group of ip's (dynamic from fargate cluster).
But there is not registred targets in target group, so alb is returning 503 status.

I use exactly yamls from this https://github.com/listentolearn/aws-eks-app-deployment/blob/main/ingress.yaml.
Alb and rule are correctly created, but without registed targets.

![image](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/141166588/00e06618-fa88-41d0-9645-1930e2ef48a3)

**Comment by oliviassss** [comment]
@oliverdavidnoguerasanmartin, can you pls check the controller logs for any info?
if you want to deploy to fargate, you need to add the below flags 
```
    --set region=region-code
    --set vpcId=vpc-xxxxxxxx
```
see: https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
we have a PR in progress to call this out in our live doc too: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3322

**Comment by oliverdavidnoguerasanmartin** [comment]
Yes, I saw controller logs.And previous this post I had errors, but now not.

![image](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/141166588/8915ef34-261c-4e81-aca3-17db9547ab61)

In which component I must to set these flags? I didn't use helm to install controller, I used cdk.

**Comment by oliverdavidnoguerasanmartin** [comment]
I apply this:

**Comment by oliverdavidnoguerasanmartin** [comment]
I apply this:

kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
../helm.exe install aws-load-balancer-controller eks/aws-load-balancer-controller
--set clusterName=cluster name
--set serviceAccount.create=false
--set region=region
--set vpcId=vpc-id
--set serviceAccount.name=aws-load-balancer-controller
-n kube-system
And works, I think was more first apply.

**Comment by abiancini** [comment]
> I apply this:
> 
> kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master" ../helm.exe install aws-load-balancer-controller eks/aws-load-balancer-controller --set clusterName=cluster name --set serviceAccount.create=false --set region=region --set vpcId=vpc-id --set serviceAccount.name=aws-load-balancer-controller -n kube-system And works, I think was more first apply.

I did the exact same thing and I still get a 503. What else can I do to get this working?
