### ISSUE TITLE
AWS load balancer controller support policy

### ISSUE THREAD

**Issue by shazib-summar** [kubernetes-sigs/aws-load-balancer-controller#3381]
Hello, what is the support policy for AWS load balancer controller. Which versions are supported at a given time? I went through the [Live Docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/) but couldn't find anything relevant to this.

If i were to use AWS load balancer controller in my prod env, which version should I use?

**Comment by M00nF1sh** [comment]
You should use the most up to date version when possible(we maintains backwards compatibility).
Currently we do support older versions(e.g. via support tickets), but we only provides security updates and bug fixes to latest available minor versions.

**Comment by shazib-summar** [comment]
Thanks a lot @M00nF1sh (love your username), should this information be in present in the readme for more visibility. I can see this being of interest to a lot of users. 

I'll be more than happy to make a PR.

**Comment by oliviassss** [comment]
@shazib-summar, thanks, you are more than welcome to raise a PR.
