### ISSUE TITLE
Support for optionally enforcing NLB security groups on PrivateLink traffic

### ISSUE THREAD

**Issue by omallo** [kubernetes-sigs/aws-load-balancer-controller#3386]
**Is your feature request related to a problem?**
I would like to be able to leverage [this AWS feature](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-security-groups.html#update-security-settings) which allows me to configure whether NLB security groups should block PrivateLink traffic or not, so that I can easily limit incoming traffic on an NLB to PrivateLink connections while blocking any other traffic. Achieving this is not easily possible without the mentioned feature, as described [here](https://medium.com/@fabian_lober/internal-server-error-api-gateway-with-network-load-balancer-92ab1aa2bd7b).

**Describe the solution you'd like**
I would like the AWS Load Balancer controller to support a new annotation on a Kubernetes LoadBalancer service which allows me to enable/disable the enforcement of NLB security groups on PrivateLink traffic. Such a boolean valued annotation would map 1:1 to the corresponding AWS functionality.

**Describe alternatives you've considered**
No satisfying alternative solution to the described problem was found.

**Comment by lteixeira-dock** [comment]
Up

**Comment by jawanjalShiva** [comment]
We are facing the same issue. We are using VPCLink to route traffic from apigw to my internal NLB. AWS LB Controller is creating NLB and when I use "service.beta.kubernetes.io/load-balancer-source-ranges" annotation (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#lb-source-ranges).  I'm using internal NLB and whitelisting apigw IPs is not helping here.  

I had to set "Enforce inbound rules on PrivateLink traffic" to "off" in NLB Security configuration to allow traffic from apigw.

**Comment by Puneeth-n** [comment]
facing the same issue here

**Comment by veekaly** [comment]
@oliviassss I'd like to work on this feature

**Comment by shraddhabang** [comment]
@veekaly Thank you for showing interest in picking this issue? Do you have any updates on this?

**Comment by lteixeira-dock** [comment]
Any update?

**Comment by shraddhabang** [comment]
Delivered in v2.8.0
