### ISSUE TITLE
AWS EKS Load Balancer Controller pods crashing with errors

### ISSUE THREAD

**Issue by goudakrishna** [kubernetes-sigs/aws-load-balancer-controller#3389]
**Describe the bug**
Error logs from aws-load-balancer controller pod - Same errors for all these three versions v2.5.3, v2.5.4 and v2.6.0
{"level":"info","ts":"2023-09-15T05:51:44Z","msg":"version","GitVersion":"v2.6.0","GitCommit":"b805cc2327d00dde47f7e254843a6e234fab74f7","BuildDate":"2023-08-10T17:39:08+0000"}
{"level":"error","ts":"2023-09-15T05:51:52Z","msg":"Failed to get API Group-Resources","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": dial tcp 172.20.0.1:443: connect: no route to host"}
{"level":"error","ts":"2023-09-15T05:51:52Z","logger":"setup","msg":"unable to start manager","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": dial tcp 172.20.0.1:443: connect: no route to host"}

**Steps to reproduce**
AWS EKS cluster version 1.27 deployed with EKS Managed nodes (linux v1.27.3-eks-xxxxxx) and vpc-cni addon (v1.14.1-eksbuild.1) with custom networking enabled to ca-central-1 region. Used same private subnets and security group for both EKS Control plane and data plane with inbound and outbound access to 443 port.

aws-load-balancer controller installed using terraform helm chart resource. Tried same with helm chart versions ( 1.5.4, 1.5.5. 1.6.0 ) 

resource "helm_release" "lbc" {

  namespace  = local.namespace
  name       = lookup(var.helm, "name", "aws-load-balancer-controller")
  repository = lookup(var.helm, "repository", "https://aws.github.io/eks-charts")
  chart      = lookup(var.helm, "chart", "aws-load-balancer-controller")
  version    = lookup(var.helm, "version", "1.6.0")

  cleanup_on_fail = lookup(var.helm, "cleanup_on_fail", true)

  dynamic "set" {
    for_each = merge({
      "clusterName"                                               = local.cluster.name
      "serviceAccount.name"                                       = local.serviceaccount
      "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn" = local.lbc_role_arn
    }, lookup(var.helm, "vars", {}))
    content {
      name  = set.key
      value = set.value
    }
  }
}

**Expected outcome**
Load balancer controller pods should be in running state without any errors.

**Environment**

* AWS Load Balancer controller version v2.5.3, v2.5.4 and v2.6.0
* Kubernetes version 
Client Version: v1.27.6
Kustomize Version: v5.0.1
Server Version: v1.27.4-eks-xxxxx

* Using EKS (yes/no), if so version? yes, 1.27

**Additional Context**:
v2.5.3 lbc controller worked with same setup in 1.26 EKS cluster.

**Comment by M00nF1sh** [comment]
it's failed to talk apiserver via the clusterIP, this don't seem like error in the controller itself.
Is your kube-proxy pods up and running? would you mind check the kube-proxy logs(the one runs on same node as this controller)?

**Comment by goudakrishna** [comment]
@M00nF1sh  Thanks for quick reply. This issue was in my sandbox environment, So, I tried cluster destroy and redeploy, after that I didn't see this issue. Thanks again!
