### ISSUE TITLE
Remove tag from subnet

### ISSUE THREAD

**Issue by gaussye** [kubernetes-sigs/aws-load-balancer-controller#3400]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]
When I create the LB with load-balancer-controller, I tag kubernetes.io/cluster/my-cluster, kubernetes.io/role/internal-elb for the subnets that NLB will be created in. A question is that what will happen if I remove the 2 tags from subnets after creation? Will the NLB will be removed also?
**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by oliviassss** [comment]
@gaussye, hi, I did a quick test - created an internal NLB and then removed the tags from the discovered subnets, I trigger a controller reconcilliation by setting the `--sync-period=1m `, and the NLB was not deleted, it still used the previous discovered subnets.
