### ISSUE TITLE
No application load balancer created but no errors

### ISSUE THREAD

**Issue by lisaRangosch** [kubernetes-sigs/aws-load-balancer-controller#3402]
**Describe the bug**
I tried to deploy a Kubernetes cluster (with two isolated subnets in AWS EKS with load-balancer-controller. Everything worked in February with version 2.4.6. When I tried to deploy a new cluster with version 2.6.1, no application load balancer was created. I tried different Kubernetes versions and also checked the release nodes. I used the new 2.6.1 iam load balancer policy. The Subnets are also tagged.
No error occurs in kubectl logs or in the pods AWS logs. The pods are running. No ingress is created. 

**Steps to reproduce**
- https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html inside a VPC with two public subnets and two isolated subnets in two separate regions (all 4 subnets are tagged)

**Expected outcome**
A working application loadbalancer

**Environment**
* AWS Load Balancer controller version: 2.6.1
* Kubernetes version: 23, 24, 25, 26 tested
* Using EKS (yes/no), if so version? yes

**Additional Context**:
* Command to install aws-load-balancer-controller
helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system  --set deletion_protection.enabled=true --set clusterName=$CLUSTERNAME --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set image.repository=602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon/aws-load-balancer-controller --set enableWaf=false --set enableWafv2=false --set vpcId=$VPCID

* kubectl logs -n kube-system deployment.apps/aws-load-balancer-controller
{"level":"info","ts":"2023-09-26T09:02:39Z","msg":"version","GitVersion":"v2.6.1","GitCommit":"5a5885bfbd3c7237ac190859fe0f20e96c95f1f2","BuildDate":"2023-09-11T17:49:28+0000"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-v1-service"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-ingressclassparams"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-networking-v1-ingress"}
{"level":"info","ts":"2023-09-26T09:02:40Z","logger":"setup","msg":"starting podInfo repo"}
{"level":"info","ts":"2023-09-26T09:02:42Z","logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting server","kind":"health probe","addr":"[::]:61779"}
{"level":"info","ts":"2023-09-26T09:02:42Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2023-09-26T09:02:42Z","logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":"2023-09-26T09:02:42Z","logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
I0926 09:02:42.163968       1 leaderelection.go:248] attempting to acquire leader lease kube-system/aws-load-balancer-controller-leader...
I0926 09:02:42.193353       1 leaderelection.go:258] successfully acquired lease kube-system/aws-load-balancer-controller-leader
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc00037eaa0"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc00037eaf0"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1.Ingress"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1.Service"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc00037eb40"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"channel source: 0xc00037eb90"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1beta1.IngressClassParams"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"ingress","source":"kind source: *v1.IngressClass"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting Controller","controller":"ingress"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1beta1.TargetGroupBinding"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1.Service"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1.Endpoints"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","source":"kind source: *v1.Node"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting Controller","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting EventSource","controller":"service","source":"kind source: *v1.Service"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting Controller","controller":"service"}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting workers","controller":"service","worker count":3}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting workers","controller":"ingress","worker count":3}
{"level":"info","ts":"2023-09-26T09:02:42Z","msg":"Starting workers","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","worker count":3}

**Comment by oliviassss** [comment]
@lisaRangosch, hi would you be able to share the ingress manifest that you applied to create the ALB?

**Comment by lisaRangosch** [comment]
Ingress manifest:
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/success-codes: '302'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: _<certificate-arn>_ 
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: '{_oidc information_}'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10

**Comment by oliviassss** [comment]
@lisaRangosch, is the ingress got created? if you describe the ingress, any info in the Events?
BTW, the `deletion_protection.enabled` should be specified by the annotation `alb.ingress.kubernetes.io/load-balancer-attributes` or `service.beta.kubernetes.io/aws-load-balancer-attributes`, instead of a helm chart value.

**Comment by lisaRangosch** [comment]
@oliviassss no, there is no ingress created and I can't see any events.

**Comment by oliviassss** [comment]
@lisaRangosch, can you try to `kubectl apply -f` our same yaml files, for example, https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/examples/2048/2048_full.yaml, and see if the ALB get created successfully?

**Comment by oliviassss** [comment]
@lisaRangosch, closing this issue for now, please feel free to reach out if there's any question, thanks.
