### ISSUE TITLE
path-based routing doesn't work properly

### ISSUE THREAD

**Issue by rabioz** [kubernetes-sigs/aws-load-balancer-controller#3409]
Hello, I am trying path-based routing on the ALB ingress controller. However, although the "/" path works, the "/test" path gives a 403 error. When I move the app service from "/test" path to "/" path, it works here. So there is only a routing to the "/" path, not the other paths.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ui
  namespace: dev
  annotations:
    # Ingress core settings
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-name: test-dev
    alb.ingress.kubernetes.io/tags: project=test, env=dev
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: dev
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.order: 1000
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: xxx
    alb.ingress.kubernetes.io/actions.response-403: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"403 External access to endpoint not allowed"}}
spec:
  rules:
  - host: "xxx.test.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-ui
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: dev
  annotations:
    # Ingress core settings
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-name: test-dev
    alb.ingress.kubernetes.io/tags: project=test, env=dev
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: dev
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: xxx
    alb.ingress.kubernetes.io/actions.response-403: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"403 External access to endpoint not allowed"}}
spec:
  rules:
  - host: "xxx.test.com"
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 8080

I expect routing to be done to paths other than only "/".

* AWS Load Balancer controller is installed by helm and version is v2.6.1
* Kubernetes version: 1.27
* EKS version: 1.27

**Comment by oliviassss** [comment]
@rabioz, hi, are you seeing the 403 error for /test path from console, or from command line like `kubectl describe ingress`?
