### ISSUE TITLE
EKS Ingress Controller- WebIdentityErr: failed to retrieve credentials - caused by: InvalidIdentityToken: Incorrect token audience

### ISSUE THREAD

**Issue by hs-vishal** [kubernetes-sigs/aws-load-balancer-controller#3410]
I  installed eks through eksctl and set the aws load balancer controller as per the document
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/

Getting the below error from the ingress and not sure what I am doing wrong.

{"level":"error","ts":"-----------","msg":"Reconciler error","controller":"ingress","object":{"name":"----","namespace":"--"},"namespace":"--","name":"----","reconcileID":"0b2sasdsa23e-cf30-4a8d-8a05-8b4b6dbf6a64","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: Incorrect token audience\n\tstatus code: 400, request id: 188-4eed-bb0b-deafe73caef7"}

  Warning  FailedBuildModel  2m53s  ingress  Failed build model due to WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: Incorrect token audience
  status code: 400

**Environment**

* AWS Load Balancer controller version v2.6.0
* Kubernetes version 1.27
* Using EKS (yes/no), if so version? yes version eks.5

**Additional Context**:
I have set a proper trust relationship for the role looks like
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::11111111222223333333:oidc-provider/oidc.eks.ap-south-1.amazonaws.com/id/EX11111111222223333333"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.ap-south-1.amazonaws.com/id/11111111222223333333:aud": "sts.amazonaws.com",
                    "oidc.eks.ap-south-1.amazonaws.com/id/11111111222223333333:sub": "system:serviceaccount:kube-system:aws-load-balancer-controller"
                }
            }
        }
    ]
}`

**Comment by oliviassss** [comment]
@hs-vishal, hi, it does not look like a controller issue to me, more like authentication issue from user side. Are you using a private cluster?
