### ISSUE TITLE
[NLB] Resolve health check port when a port name is provided

### ISSUE THREAD

**Issue by fad3t** [kubernetes-sigs/aws-load-balancer-controller#3418]
Hello,

We're having a service with multiple ports: a UDP port that's receiving the traffic, and a TCP port for the health check.
Both ports are exposed as (dynamic) nodePorts. For now we have to statically defined the nodePort for the TCP health check, and reference that port in the `service.beta.kubernetes.io/aws-load-balancer-healthcheck-port` annotation.

Instead, we would like to pass the port name to the annotation, and leave the LB controller resolve it.
I saw this has been implemented for the ALB (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/799) but not for the NLB yet. I guess the same logic could be applied.

Thanks,
Fred

**Comment by oliviassss** [comment]
Close this issue as the PR as shipped with v2.6.2 release.

**Comment by javorkolev123** [comment]
Hello,

Do I understand correctly that this feature has already been added? It does not seem to be documented though - https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/guide/service/annotations/#healthcheck-port.

**Comment by fad3t** [comment]
Hi,
That's correct, feature is there but I missed the doc.
