### ISSUE TITLE
Tags specified via alb.ingress.kubernetes.io/tags do not get added to listener default rule 

### ISSUE THREAD

**Issue by kpanic9** [kubernetes-sigs/aws-load-balancer-controller#3421]
**Describe the bug**
The tags specified via [alb.ingress.kubernetes.io/tags](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#tags) do not get added to the load balancer listener's default rule.

**Steps to reproduce**
Create a Ingress resource with [alb.ingress.kubernetes.io/tags](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#tags) annotation.

**Expected outcome**
Tags are added to default listener rule.

**Environment**
AWS

* AWS Load Balancer controller version 2.4.3
* Kubernetes version 1.25
* Using EKS yes, if so version? 1.25

**Comment by oliviassss** [comment]
@kpanic9, hi, is the alb reconciled successfully, would you be able to share the controller logs? 

Some factors that may interfere the tags on LS:
1. tags specified on controller level through `--default-tags` won't be overridden by annotation
2. we validate the tag specified via annotation with the tags specified in controller flag `--external-managed-tags` to make sure there's no collision
3. there's a merge behavior on the tags, the priority rank: tags in ingress class > tags in svc annotation > tags in ingress annotation

ref: 
1. https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/eacb0c370c0fbe6abcd15b00b7e7e35ca039c2ed/pkg/ingress/model_build_tags.go#L65
2. https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/eacb0c370c0fbe6abcd15b00b7e7e35ca039c2ed/pkg/ingress/model_build_tags.go#L55

**Comment by kpanic9** [comment]
Hi @oliviassss ,

I am not able to get the logs from the controller as we don't have a long retention for logs in lower environments at the moment.

From the source code, I can see the listener rules are getting tags for each path in the ingress resource (https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/276c6933dbe69a46962875e14f724e73cc2ba5ca/pkg/ingress/model_build_listener_rules.go#L32).

But the listener rule I am referring to is the default rule, which gets created from https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/ingress/model_build_listener.go#L47

I had a look in to the AWS SDK as well. Looks like the tags we specify on CreateListenerInput (https://pkg.go.dev/github.com/aws/aws-sdk-go/service/elbv2#CreateListenerInput) are only for the listener. Those tags don't get applied to the default listener rule (https://pkg.go.dev/github.com/aws/aws-sdk-go/service/elbv2#Action).

Having a more close look, I think this needs to be fixed from the AWS SDK side.

**Comment by kpanic9** [comment]
AWS SDK team mentioned this is not something support from the AWS SDK.
