### ISSUE TITLE
Zone DNS affinity

### ISSUE THREAD

**Issue by milandasek-printify** [kubernetes-sigs/aws-load-balancer-controller#3431]
Hello,

When can we expect support for Zone DNS affinity?
https://aws.amazon.com/about-aws/whats-new/2023/10/aws-nlb-availability-performance-capabilities/

I guess something like:
`service.beta.kubernetes.io/aws-load-balancer-zone-dns-affinity-enabled`

Thank you

**Comment by alex-berger** [comment]
@milandasek-printify, this already works by setting the `service.beta.kubernetes.io/aws-load-balancer-attributes` annotation accordingly, for example like this:

```yaml
service.beta.kubernetes.io/aws-load-balancer-attributes: dns_record.client_routing_policy=availability_zone_affinity
```

I also created https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3470 to (slightly) improve user experience (input validation).
