### ISSUE TITLE
Don't want to update EKS's cluster security group for instance targets.

### ISSUE THREAD

**Issue by keyolk** [kubernetes-sigs/aws-load-balancer-controller#3434]
**Is your feature request related to a problem?**

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/nlb/#security-group

From the guide, the ALBC updates the security group which is tagged with `kubernetes.io/cluster/${cluster-name}`
Actually, EKS's cluster security group is the target.

From my understanding, the cluster security group is for communication between the control plane and worker nodes.
Would better keep it minimal.

But seems there is no option to set dedicated security groups to update.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/targetgroupbinding/networking_manager.go#L520

**Describe the solution you'd like**
How about if we can set dedicated security group for worker nodes?

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by keyolk** [comment]
Also realted with https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2367

**Comment by keyolk** [comment]
Oh, seems https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3147 solve this problem

**Comment by oliviassss** [comment]
@keyolk, hi, yes we have the PR merged, and we plan to have it release in our coming minor release v2.7.0.
I'm closing this issue for duplication. Thanks
