### ISSUE TITLE
Helm Chart's default tag for images not aligned with git tag (Starting from v2.6.0)

### ISSUE THREAD

**Issue by guessi** [kubernetes-sigs/aws-load-balancer-controller#3441]
**Describe the bug**

Yes, I'm aware of official helm chart is hosted under [aws/eks-charts](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller) and there's no problem with eks-charts.

But it would be nice to keep version tag aligned with actual version, or put warning message to users who use this repo as chart source.

Starting from git tag `v2.6.0`, the image tag started get wrong, 

Git tag `v2.6.0` is pointing to image `v2.5.4`,
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.6.0/helm/aws-load-balancer-controller/values.yaml#L7-L10

Git tag `v2.6.1` is pointing to image `v2.6.0`,
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.6.1/helm/aws-load-balancer-controller/values.yaml#L7-L10

**Steps to reproduce**

**Expected outcome**

Version tag for the image would better to be aligned with git tag.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by oliviassss** [comment]
@guessi, thanks, let's track in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3439
closing for duplications.

**Comment by guessi** [comment]
@oliviassss sure, np
