### ISSUE TITLE
Terminate TLS in cluster

### ISSUE THREAD

**Issue by jseiser** [kubernetes-sigs/aws-load-balancer-controller#3444]
**Is your feature request related to a problem?**
Is it possible to terminate TLS on a pod in the cluster?  We have requirements that the traffic from the LB to the cluster must also be encrypted.  Interservice traffic is already handled via a service mesh.  I can not find anyway to allow traffic to go from the LB to the cluster via TLS, without having to create/mount tls certificates on the pod the ingress service is routing too.

**Describe the solution you'd like**
Allow for cert-manager to create/manage certicates on the ingress pod.

**Describe alternatives you've considered**
We currently utilize nginx-ingress and terminate TLS on the nginx pod.

**Comment by mikutas** [comment]
I think [alb.ingress.kubernetes.io/backend-protocol: HTTPS](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#traffic-routing) helps. The annotation configures [target group protocol](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#target-group-routing-configuration). You will need to have cert-manager create cert on the target pod.

>Because the load balancer is in a virtual private cloud (VPC), traffic between the load balancer and the targets is authenticated at the packet level, so it is not at risk of man-in-the-middle attacks or spoofing
