### ISSUE TITLE
[Docs] Update the docs page for NLBs to include new SG information

### ISSUE THREAD

**Issue by tculp** [kubernetes-sigs/aws-load-balancer-controller#3448]
**Describe the bug**
The docs page for NLB Security Groups (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/nlb/#security-group) still says "AWS doesn't support attaching security groups to NLBs.", which is no longer correct.

Announcement
https://aws.amazon.com/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/

"If you are using Kubernetes, you can enable security groups on your NLB by using [AWS Load Balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) version 2.6.0 or later."

This docs page should be updated to include information about the new capabilities.

**Comment by oliviassss** [comment]
@tculp, thanks we have updated our source doc, and will deploy it to live doc soon.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/service/nlb.md#security-group

**Comment by tculp** [comment]
Awesome, thanks!
