### ISSUE TITLE
[Docs] Helm specify to not create SA when using IRSA

### ISSUE THREAD

**Issue by darwin67** [kubernetes-sigs/aws-load-balancer-controller#3449]
**Describe the bug**
This is not necessarily a bug but seems more like a typo in the docs.

On the installation guide, when installing with IRSA, the docs specify to set `serviceAccount.create=false`, which doesn't really make sense because the whole point of IRSA is to use service accounts.

![aws-lb-irsa](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/5746693/0bac6d0f-ae37-4cb2-aca3-edd628dd7386)

And as expected, if I set it to `false`, the controller pods doesn't come up because the serviceaccount is not available.

Setting it back to `true`, will allow the controller pods to come up, so I'm suspecting it's an oversight on the docs, but is there an actual legit reason why this attribute should be set to `false`?
Not sure if I'm missing something here.

**Steps to reproduce**

Install aws-lb-controller following instructions

**Expected outcome**

Following the docs should have pods running, and not hang.

**Environment**

* AWS Load Balancer controller version: 1.6.1
* Kubernetes version: 1.28
* Using EKS (yes/no), if so version? yes, 1.28

**Additional Context**:

**Comment by oliviassss** [comment]
@darwin67, hi, in the installation doc we already created a SA named `aws-load-balancer-controller` [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/#option-a-recommended-iam-roles-for-service-accounts-irsa), in this helm command, essentially we are telling it not to create a new SA but use the existing SA.
