### ISSUE TITLE
Controller not updating port range for backend security group

### ISSUE THREAD

**Issue by sjherrick** [kubernetes-sigs/aws-load-balancer-controller#3455]
**Describe the bug**
Newly created Kubernetes services are using NodePorts that fall outside of the port range for the inbound rule allowed from the shared frontend security group in the backend security group managed by the Load Balancer Controller.

**Steps to reproduce**
Create a new kubernetes service and ingress where the service NodePort happens to fall outside the current allowed ports.

**Expected outcome**
In the past it seems the Load Balancer Controller would update the security group rule when new services were created. e.g. this log message:

{"level":"info","ts":1698351894.8756566,"msg":"authorizing securityGroup ingress","securityGroupID":<removed>,"permission":[{"FromPort":30090,"IpProtocol":"tcp","IpRanges":null,"Ipv6Ranges":null,"PrefixListIds":null,"ToPort":32050,"UserIdGroupPairs":[{"Description":"elbv2.k8s.aws/targetGroupBinding=shared","GroupId":"<removed>,"GroupName":null,"PeeringStatus":null,"UserId":null,"VpcId":null,"VpcPeeringConnectionId":null}]}]}

Log messages like this are no longer appearing when new services are created. 

**Environment**

* AWS Load Balancer controller version
2.4.6
* Kubernetes version
v1.24.17-eks-f8587cb
* Using EKS (yes/no), if so version?
v1.24.17-eks-f8587cb

**Additional Context**:
The Load Balancer Controller _does_ update the security group, but doesn't set the port range correctly. For example if I manually change the security group port range and deploy a new service and ingress, the LBC updates the port range to what it was previously. 

I'm considering a workaround of setting `--disable-restricted-sg-rules=true` .

**Comment by oliviassss** [comment]
@sjherrick, hi the controller dynamically adjust the port range based on the value range of target port and health check ports (see the commit for more details: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2236). And if you manually change the port range from console, during the next reconciliation the controller will revert any manual change, since controller reconciles based on manifest. 
Would you consider editing the target port or health check port in your manifest to include NodePort?
The workaround you proposed also works, if you are okay with it allowing the traffic with ALL port.

**Comment by sjherrick** [comment]
@oliviassss Thanks very much for the response. I'll look at the commit to understand the mechanism a bit better.

I do understand that manual changes will be reverted by the controller - I just included that detail to confirm that the controller is functioning, but not correctly expanding the port range to include some of the target groups.

_Would you consider editing the target port or health check port in your manifest to include NodePort?_
All of my target group's service type is NodePort in their manifests. 

I ended up using the workaround I mentioned. I don't feel great about it, but it needed to be done to prevent further impacts. I hope to revisit this soon.

**Comment by skynnes** [comment]
I'm also experiencing this exact issue
AWS Load Balancer controller version
v2.8.0 
Kubernetes version
1.29
Using EKS (yes/no), if so version?
eks.7

**Comment by sjherrick** [comment]
@skynnes fyi setting `--disable-restricted-sg-rules=true` does get it working if you're not too bothered by opening the whole range of tcp ports from ALB->nodes

**Comment by billnbell3** [comment]
Why is this closed?

I have ingress controllers set for 3000. But since the first time the ALB was created it set the SG range 4001-8088 it is stuck there.

I don't know why ? Seems like a defect.

Bill
