### ISSUE TITLE
error with 2.6.2 release artifacts

### ISSUE THREAD

**Issue by bllfr0g** [kubernetes-sigs/aws-load-balancer-controller#3458]
There appears to have been an error posting the 2.6.2 release artifacts.

`v2_6_2_full.yaml` and `v2_6_2_ingclass.yaml` have identical contents. The correct `v2_6_2_full.yaml` was not posted.

**Comment by oliviassss** [comment]
@bllfr0g, hi, I have updated the correct file for v2_6_2_full.yaml, sorry for the inconvenience.

Closing this issue as for now, please feel free to reach out if you have any questions.
