### ISSUE TITLE
Disable all SG creation and modification

### ISSUE THREAD

**Issue by levinedaniel** [kubernetes-sigs/aws-load-balancer-controller#3468]
**Is your feature request related to a problem?**

As a corporation that is required to manage Security Groups centrally, it would be ideal to have one central configuration option to disable all SG actions including frontend sg creation, backend sg creation, and backend sg modifications.

To prevent frontend SG creation, with the update to 2.6.0, we _have_ to add the annotation [service.beta.kubernetes.io/aws-load-balancer-security-groups](http://service.beta.kubernetes.io/aws-load-balancer-security-groups) in order for the front end SG to not be created. Since we and many other teams still just rely on the instance sgs, there should be a way to opt out of this creation. 

To prevent backend SG manipulation, we have to add the annotation [alb.ingress.kubernetes.io/manage-backend-security-group-rules](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#manage-backend-security-group-rules) or [service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#manage-backend-sg-rules).  We currently have implemented a policy agent to enforce this annotation. A native solution would be more preferable. 

**Describe the solution you'd like**

Two potential solutions would be to either:
- Add a flag that disables _all_ sg creation/manipulation
- Add flags for disabling frontend sg creation and backend rule manipulation. 

**Describe alternatives you've considered**
Like I said above, there is currently no way to prevent frontend SGs on NLB if you are relying on using instance SGs. 

The alternative for backend SG manipulation is to use a mutating webhook. Given that the LBC comes with a mutating webhook in-tree controller LB creation we could add logic to that for this functionality.

**Comment by oliviassss** [comment]
@levinedaniel, we actually have a feature gate flag `NLBSecurityGroup` to disable it, sorry I missed updating the doc for this flag. Can you pls try to set `- --feature-gates=NLBSecurityGroup=false`, and see if it works for your case?
ref: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/config/feature_gates.go#L23

**Comment by epollia** [comment]
Hello. I try used `--feature-gates=NLBSecurityGroup=false`

```
     args:
        - '--cluster-name=test'
        - '--ingress-class=alb'
        - '--aws-region=eu-north-1'
        - '--aws-vpc-id=vpc-xxxxxxxxxxx'
        - '--log-level=info'
        - >-
          --feature-gates=NLBSecurityGroup=false,ServiceTypeLoadBalancerOnly=true

```
But LBC creating rules in SG. I can't disable managment all sg and rules by LBC.

;(

**Comment by fungaren** [comment]
@epollia You still need add the annotation to your service:

```yaml
service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
```
