### ISSUE TITLE
Unclear how to make ingressClass default

### ISSUE THREAD

**Issue by imishchuk-carbon** [kubernetes-sigs/aws-load-balancer-controller#3491]
Hello, team.

**Describe the bug**

I'm looking into making ingressClass default for any ingress that does not explicitly define which ingressClass to use. If I'm reading [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.6.2/helm/aws-load-balancer-controller/values.yaml#L112-L114) correctly, adding `ingressClass: ` to helm values _should_ achieve my goal. Problem is that this value is used in ingressClass definition [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.6.2/helm/aws-load-balancer-controller/templates/ingressclass.yaml#L26) to define its name, hence it cannot be empty. Helm upgrade log

```
Helm upgrade failed: error while running post render on files: missing metadata.name in object {{networking.k8s.io/v1 IngressClass} {{ } map[app.kubernetes.io/instance:aws-system-aws-loadbalancer-controller app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:aws-load-balancer-controller app.kubernetes.io/version:v2.6.2 helm.sh/chart:aws-load-balancer-controller-1.6.2] map[]}}
```

Additionally, I've found this [issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3048), so it looks like above behavior is expected? Then, it's confusing why document suggests `If not specified, controller will match all ingresses without ingress class annotation and ingresses of type alb`

Answering question from 3048 `Any specific reason why you don't want to use spec.ingressClassName ?`: No specific reason, I'm totally fine with using `spec.ingressClassName`, but docs are confusing by suggesting that ingressClass can be configured to be default.

**Steps to reproduce**

1. Create a Helm release and specify:

```
values:
  ...
  ingressClass:
```

2. Run upgrade

**Expected outcome**

IngressClass becomes default for any ingress without explicit specification of IngressClass

**Environment**

* AWS Load Balancer controller version: `1.6.2`
* Kubernetes version `1.28`
* Using EKS (yes/no), if so version?: `eks.3`

Thank you.

**Comment by imishchuk-carbon** [comment]
Hey.

As usual, reading docs some more [pointed](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.6.2/helm/aws-load-balancer-controller/templates/ingressclass.yaml#L29-L32) me to correct value to be used to set ingressClass as default. Then it's just a matter of fixing wording for `ingressClass` value.

**Comment by oliviassss** [comment]
@imishchuk-carbon, sorry for the delay response. it's called out in the helm chart doc: https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/v2.6.2/helm/aws-load-balancer-controller

Closing this issue as for now, please feel free to reach out in any questions, thanks
