### ISSUE TITLE
Cleanly remove all AWS resources created by LBC

### ISSUE THREAD

**Issue by cbugneac-nex** [kubernetes-sigs/aws-load-balancer-controller#3492]
**Is your feature request related to a problem?**
Is there a way to cleanly delete all resource created by AWS LBC ?
Tried to delete all IngresClass and IngresClassParams but looks like there are ingress objects which are part of other Helm charts which I cannot simply remove.
Turning off LBC does also leave all resources running.

**Describe the solution you'd like**
I want o simulate a failure - disappearance of all ALB, TG SG, etc. in order to test a failure case.
Is there a config or API via which I can purge all resources created in a clean way ?

**Describe alternatives you've considered**
Delete manually all ALB, TG, SG created by LBC.

**Comment by oliviassss** [comment]
@cbugneac-nex, you can try to `kubectl delete -f [your manifest file]`, or `kubectl delete --all all -n [the namespace]`
