### ISSUE TITLE
Getting Reconciler error for Target Group deleted outside

### ISSUE THREAD

**Issue by cbugneac-nex** [kubernetes-sigs/aws-load-balancer-controller#3493]
**Describe the bug**
The target group has been manually deleted and now AWS LBC complains with Reconciler error:

```json
{"level":"error","ts":"2023-11-21T18:30:01Z","msg":"Reconciler error","controller":"ingress","object":{"name":"external"},"namespace":"","name":"external","reconcileID":"d581f2e7-432f-4846-89cb-6256f54a01c1","error":"targetgroupbindings.elbv2.k8s.aws \"k8s-****-41b5089ba6\" already exists"}

{"level":"error","ts":"2023-11-21T18:29:44Z","msg":"Reconciler error","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","TargetGroupBinding":{"name":"k8s-****-92079e73c6","namespace":"frontend1"},"namespace":"frontend1","name":"k8s-*-92079e73c6","reconcileID":"ff769157-eac2-4abf-8518-2e49b168d928","error":"TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:eu-west-1:**********:targetgroup/k8s-*****-92079e73c6/4a72f476695c29d0' not found\n\tstatus code: 400, request id: 6b938ea8-8214-4acb-98b4-99b93e0a84ca"}
```

One of TG already exists (it was re-created with the same name).
But another one was deleted and doesn't exist.

PS: Seen https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/how-it-works/ and recommendation not to do it but it's already done.

Tried to uninstall/install LBC no luck.
Tried to set syncPeriod to 5 mins - no luck.
How to make it sync it's local object stores ? Is there any way to reset it's state ?

**Steps to reproduce**
Stop LBC.
As part of disaster recovery exercise delete TG resources in AWS.
Start LBC.

**Expected outcome**
Somehow to manually reconcile AWS LBC.

**Environment**

* AWS Load Balancer controller version 2.6.1
* Kubernetes version 1.25
* Using EKS - yes

**Additional Context**:
Please could someone help with this ?

Note: Seen https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3317 but it doesn't help.

**Comment by cbugneac-nex** [comment]
Update: I had to delete all Ingress objects referencing Ingress Class in TG in order for LBC to complete successfully reconciliation.

**Comment by oliviassss** [comment]
@cbugneac-nex, yeah we do not recommend manually editing the resources managed by the controller as pointed above, it may cause reconcile issue. Closing this issue as for now, thanks

**Comment by shaunlandau1973** [comment]
> Update: I had to delete all Ingress objects referencing Ingress Class in TG in order for LBC to complete successfully reconciliation.

Howdy. Can you elaborate? I'm in the same boat right now. I delete everything but keep getting back to same point of conflict. I did this intentionally to verify my least-privilege IAM policy for the service account.
