### ISSUE TITLE
NLB svc: changes to spec.LoadBalancerSourceRanges don't get propagated

### ISSUE THREAD

**Issue by ptimofee** [kubernetes-sigs/aws-load-balancer-controller#3495]
**Describe the bug**
`spec.LoadBalancerSourceRanges` for k8s svc (NLB) doesn't get updated once you deploy it.
I. e. it gets propagated to NLB security group only during initial creation.
When you later change spec.LoadBalancerSourceRanges to add/delete new/old ip range the controller just ignores it forever.
This is confusing since the [documentation recommends](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#access-control) using `Spec.LoadBalancerSourceRanges` instead of `service.beta.kubernetes.io/load-balancer-source-ranges` annotation.
The latter one works as expected, i. e. changes do propagated to the security group immediately.

**Steps to reproduce**
Deploy k8s svc with spec.LoadBalancerSourceRanges set to 1.2.3.4/32.
Wait for controller to provision NLB. Verify security group has 1.2.3.4/32 inbound rule.
Add additional range like 4.3.2.1/32 to spec.LoadBalancerSourceRanges.
Wait forever in attempt to see that new range in the security group.

**Expected outcome**
`spec.LoadBalancerSourceRanges` for NLB should work the same as `service.beta.kubernetes.io/load-balancer-source-ranges` annotation, i. e. changes should be reflected in sg.

**Environment**

* AWS Load Balancer controller version
v2.6.2

* Kubernetes version
1.28.3

* Using EKS (yes/no), if so version?
yes, 1.28

**Additional Context**:
What is also interesting the controller rollbacks manual changes to sg after long period of time (sync-period of 10h?). And whatever is set in `spec.LoadBalancerSourceRanges` at present time the controller uses the values set during initial propagation.

**Comment by oliviassss** [comment]
/kind documentation
Thanks for pointing out, we need to fix the typo in our doc https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#access-control, from `Spec.LoadBalancerSourceRanges` to `Spec.loadBalancerSourceRanges`

**Comment by shraddhabang** [comment]
Fixed with this: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3472
