### ISSUE TITLE
Support Automatic Target Weights

### ISSUE THREAD

**Issue by Palmer-Reed-bah** [kubernetes-sigs/aws-load-balancer-controller#3497]
**Is your feature request related to a problem?**
n/a

**Describe the solution you'd like**
AWS recently added a new target routing algorithm for ALB called [Automatic Target Weights](https://aws.amazon.com/about-aws/whats-new/2023/11/application-load-balancer-availability-target-weights/), which promises anomaly detection and stateful routing in addition to simple healthchecking and circuit-breaking. Please add support for this type of routing if it is not already available.

**Describe alternatives you've considered**
n/a

**Comment by oliviassss** [comment]
@Palmer-Reed-bah, hi, it should be configurable through target group attribute annotation for example, `alb.ingress.kubernetes.io/target-group-attributes: load_balancing.algorithm.type=weighted_random,load_balancing.algorithm.anomaly_mitigation=on`
ref: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/annotations.md#target-group-attributes

CC: @shraddhabang

**Comment by Palmer-Reed-bah** [comment]
thank you @oliviassss, will give that a try

**Comment by oliviassss** [comment]
@Palmer-Reed-bah, I'm closing this issue as for now, feel free to reach if any question, thanks
