### ISSUE TITLE
support for (mTLS) Mutual Transport Layer Security

### ISSUE THREAD

**Issue by berry2012** [kubernetes-sigs/aws-load-balancer-controller#3499]
**Is your feature request related to a problem?**
_Originally posted by @kishorj in https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1973#issuecomment-841568062_

**Describe the solution you'd like**
I'd like to see ALB controller add support for mTLS.
The [Application Load Balancer now reliably verifies certificate-based client identities](https://aws.amazon.com/blogs/aws/mutual-authentication-for-application-load-balancer-to-reliably-verify-certificate-based-client-identities) hence the ask if this can now be effected in the ALB controller settings.

**Describe alternatives you've considered**
1. With Nginx Ingress controller by adding additional annotations to your Ingress Resource to specify Client-Certificate Authentication.
https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/auth/client-certs/ingress.yaml

2. With ALB controller provisioning an ALB after creating the ingress resource then manually editing the created ALB from EC2 console to enable the mTLS (not smooth, but it is a workaround for now). Having a way to use annotations to specify the certificate stored in secret will give better experience.

**Comment by arununzer** [comment]
+1 , Can we have the support for mTLS for ALB controller as an ingress Annotations like we have it for nginx ingress controller

**Comment by shraddhabang** [comment]
Thank you for bringing this up. We are currently working on the implementation to support mTLS configuration through controller. We are planning to release this in coming month in next minor release.

**Comment by JCachada** [comment]
Hey 😄 No pressure, but is this still planned for release in the next minor? Have there been any updates to the plan in the meantime?

**Comment by kangadrewie** [comment]
> Hey 😄 No pressure, but is this still planned for release in the next minor? Have there been any updates to the plan in the meantime?

+1 -- I see the ticket is still in todo, this would be a great addition

**Comment by arununzer** [comment]
Hello Folks, Any idea on when it will be released ..an appropriate release date ?

**Comment by oliviassss** [comment]
@JCachada, @kangadrewie, @arununzer, hi all, I think the team are working on releasing this feature with v2.7.0, targetting on mid Jan. Thanks

**Comment by suman-ganta** [comment]
Hi @oliviassss, is v2.7.0 still on track to release this week?

**Comment by shraddhabang** [comment]
@suman-ganta I have raised a PR for this feature. The release for v2.7.0 is set by end of January. Thank you for your patience.

**Comment by arununzer** [comment]
Thanks @shraddhabang  for the mTLS release
