### ISSUE TITLE
Add checks to picks subnets which obey `alb.ingress.kubernetes.io/scheme` rule.

### ISSUE THREAD

**Issue by someshkoli** [kubernetes-sigs/aws-load-balancer-controller#3500]
**Is your feature request related to a problem?**
Recently came across a situation where I provisioned a alb with `scheme` set as `internet-facing`. Requests were randomly throwing timeouts due to some reason x I could not understand. Turns out one of the subnet that was automatically selected was private in nature (did not have internet gateway association).

Like I cant think of a situation where people would set the traffic as external / internal & want private / public subnet respectively in their system, then why allow it in first place. 

**Describe the solution you'd like**
I know that we do have ability to manually assign subnets to the loadbalancer, but that's a bit problematic because now I have to hardcode subnet ids. 
Instead,  can we have a check to pick only public (subnets having internetgateway association) subnets (from list of subnets assigned to the eks cluster) when `scheme` is set to `internet-facing` and vice versa when `scheme` is set to `internal`

**Describe alternatives you've considered**
Right now only option I have (from what I understood from docs) is to hardcode the subnet ids in my ingress declaration.

**Comment by frimik** [comment]
Subnets need proper Tags. 

See section about Public and Private subnets mentioning, among other things, this tag: `kubernetes.io/role/elb`.

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/subnet_discovery/

https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#network-requirements-subnets
