### ISSUE TITLE
Add the ability to create a horizontal pod autoscaler to the helm chart

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/aws-load-balancer-controller#3501]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
The ability to create a horizontal pod autoscaler via helm chart values.

**Describe alternatives you've considered**
Manual creation or an in-house helm chart with a HPA template and the upstream aws-load-balancer-controller chart as a dependency.

**Comment by oliviassss** [comment]
Closed as shipped in v2.7.0, helm chart v1.7.0
