### ISSUE TITLE
Targets are not supported error while target group binding

### ISSUE THREAD

**Issue by gac3k** [kubernetes-sigs/aws-load-balancer-controller#3508]
**Describe the bug**
While new targets are being added to the specific target group I am getting the following error:

```"InvalidTarget: Targets {i-instanceIDHere} are not supported\n\tstatus code: 400"```

This is happening totally randomly from my point of view, and I have a hard time trying to reproduce it. It works fine most of the time just to break occasionally. 

Additional problem is that when that error happens, reconciliation process is hanging and I am often being left with no valid targets registered in the target group, and effectively with no traffic reaching the cluster.

I am using karpenter for autoscaling, but I also have general purpose machines from the default auto-scaling group.

**Steps to reproduce**

- Add a new instance to the cluster node list
- Node is not registered in the target group for load balancer, and the following error occurs, also other targets (instances) are being removed.

**Expected outcome**
Node should be properly registered and bound to the target group.

**Environment**

* AWS Load Balancer controller version: 2.6.1
* Kubernetes version: 1.26.10
* Using EKS: yes

**Additional Context**:

**Comment by M00nF1sh** [comment]
@gac3k 
Are you registering targets into targetGroups of networking load balancers?
if so, it could be due to the instance types:

> With a Network Load Balancer, you cannot register instances by instance ID if they have the following instance types: C1, CC1, CC2, CG1, CG2, CR1, CS1, G1, G2, HI1, HS1, M1, M2, M3, and T1. You can register instances of these types by IP address.

**Comment by oliviassss** [comment]
@gac3k, I'm closing this issue as for now, feel free to reach if any question, thanks

**Comment by mausch** [comment]
> With a Network Load Balancer, you cannot register instances by instance ID if they have the following instance types

Docs for this:
https://awscli.amazonaws.com/v2/documentation/api/2.18.18/reference/elbv2/register-targets.html

If you still want to use one of those instance types with a NLB you can force IP registration by adding the following annotation to the nginx LoadBalancer service:

`service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip`
