### ISSUE TITLE
Question About external LBs

### ISSUE THREAD

**Issue by fcastello** [kubernetes-sigs/aws-load-balancer-controller#3511]
**Is your feature request related to a problem?**
More of a problem is a question about a use case I have, that I haven't found if it is possible or not

**Describe the solution you'd like**
I have a use case that I already have a network load balancer created outside of EKS which I want to only do the target group binding to a service in EKS which is nodeport type.
I am curious if it is possible to do the targetgroup binding to exisiting infrastructure

**Comment by vasekboch** [comment]
This would be usefull for Terraform. As you describe the loadbalancer, and you can manage it or link it to some other service. With current setup, you need to write some hacks to search for correct LB and waiting for it when is available.

**Comment by shraddhabang** [comment]
@fcastello  Have you looked at using [TargetGroupBinding](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/targetgroupbinding/targetgroupbinding/) CRD?

**Comment by dtwilliamsWork** [comment]
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/use_cases/self_managed_lb/
