### ISSUE TITLE
Clarification on Ingress Group Behavior

### ISSUE THREAD

**Issue by btlem** [kubernetes-sigs/aws-load-balancer-controller#3512]
Per the documentation, Ingresses annotated with the same IngressGroup will be merged into a single ALB. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#ingressgroup

My question is what happens in the case in which the ALB reaches capacity for the number rules? Does the controller know how to handle this case and create a new ALB for the excess rules, or will this hang indefinitely?

**Comment by M00nF1sh** [comment]
@btlem 
It will hang indefinitely(reconcile will fail). The controller currently don't have such auto-split functionality.
