### ISSUE TITLE
Registered Targets using wrong port

### ISSUE THREAD

**Issue by travis-jorge** [kubernetes-sigs/aws-load-balancer-controller#3519]
When the controller is registering targets its using port 443 instead of 80 where is this configured I can not find it. 
![image](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/80355769/84307010-c00c-44ab-8241-4025693c01a2)
i added the port 80 manually to show it works with the correct port.

**Comment by shraddhabang** [comment]
@travis-jorge Could you please provide us the manifest for the Ingress you are trying to create. Also it would be helpful if you can provide a controller log file. 

My hunch is you are creating a secure listener which creates a listener on port 443 by default.

**Comment by shraddhabang** [comment]
Also take a look at this [doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#listen-ports) where we mention that if you are creating a secure listener it will default to port 443
