### ISSUE TITLE
Impossible to know configuration options for Ingress specification

### ISSUE THREAD

**Issue by Stephane-Ag** [kubernetes-sigs/aws-load-balancer-controller#3526]
**Is your feature request related to a problem?**
There is basically no way to know how I can modify the `spec` section of the ingress yaml file and the configurations available.

**Describe the solution you'd like**
For the [spec doc](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/spec.md) to have actual detail to it like the [annotations doc](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/annotations.md) does.

**Describe alternatives you've considered**
There's no alternatives as there's no other docs on this I could find.

**Comment by shraddhabang** [comment]
\kind feature

**Comment by shraddhabang** [comment]
@Stephane-Ag Can you please take a look at this [document](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec) which describes the Ingress Specifications?

**Comment by Stephane-Ag** [comment]
@shraddhabang Ah, so it does exist! If [this page](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec) could be linked to [this one](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/guide/ingress/spec.md), that would be great then.
