### ISSUE TITLE
pulling aws-load-balancer-controller image fails with 401 Unauthorized

### ISSUE THREAD

**Issue by BogdanSorlea** [kubernetes-sigs/aws-load-balancer-controller#3527]
upon deployment rollout restart, I get
```Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.4.1": rpc error: code = Unknown desc = failed to pull and unpack image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.4.1": failed to resolve reference "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.4.1": pulling from host 602401143452.dkr.ecr.us-west-2.amazonaws.com failed with status code [manifests v2.4.1]: 401 Unauthorized```
and the pod does not come up.

what changed? what are the steps to remediate?
quick search in issues yields nothing

**Comment by BogdanSorlea** [comment]
right, I guess the registry endpoint got consolidated and changed

**Comment by oliviassss** [comment]
@BogdanSorlea, hi I couldn't reproduce this issue in my setup. Can you try to run a `docker pull`? maybe also check if you have authenticated. thanks
