### ISSUE TITLE
aws-load-balancer-target-group-attributes not working as expected for disable preserve_client_ip.enabled

### ISSUE THREAD

**Issue by sanketg86** [kubernetes-sigs/aws-load-balancer-controller#3528]
**Describe the bug**
I am deploying ingress-nginx for aws load balancer and want to disable preserve_client_ip for https Listeners after adding below annotation still not disable. 

```
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
service.beta.kubernetes.io/aws-load-balancer-internal: true
service.beta.kubernetes.io/aws-load-balancer-type: nlb
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false

```

**Expected outcome**
Preserve client IP addresses
Off

**Environment**

* AWS Load Balancer controller version :  Helm chart version: 4.7.3 ,  nginx-controller: v1.8.4
* Kubernetes version: 1.28
* Using EKS (yes/no), if so version? yes, EKS 1.28

**Comment by shraddhabang** [comment]
@sanketg86 Could you please tell us which version of AWS Load Balancer controller you are using? I see you have mentioned the nginx-controller version.

**Comment by rajeevpnair** [comment]
@sanketg86  I am facing the same issue with version aws-load-balancer-controller:v2.5.1
