### ISSUE TITLE
Unable to register rule on ALB due to a WAFv2 conflicting ARN

### ISSUE THREAD

**Issue by velvetzhero** [kubernetes-sigs/aws-load-balancer-controller#3535]
**Describe the bug**
We are using one `ALB` for many services in different namespaces. All use the same `group-name`.
 We are getting the following error since we've associated our `ALB` to a `WAFv2` acl:
{"level":"error","ts":"2024-01-23T15:09:35Z","msg":"Reconciler error","controller":"ingress","object":{"name":"external"},"namespace":"","name":"external","reconcileID":"0e7c9e99-c2e4-4b7b-b6b1-808136a81287","error":"conflicting WAFv2 WebACL ARNs: [arn:aws:wafv2:CORRECT_ARN arn:aws:wafv2:WRONG_ARN]"}

We are not sure where the wrong ARN is coming from. We suspect an old ACL reference, that was created and then deleted, but we're unsure.
Despite the error, some of the rules just "pass" and are created on the ALB, but some others are not, and so their service stays unreachable.So, the behavior is inconsistent.

**Steps to reproduce**
- You need to have a WAFv2 ACL associated with an `external-facing` load balancer.
- Try to create an `ingress` as follow:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service
  namespace: namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: external
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:CERT_ARN
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/wafv2-acl-arn: 'arn:aws:wafv2:eu-central-1:ACL_ARN'
spec:
  rules:
    - host: 'your host'
      http:
        paths:
          - path: /path
            backend:
              service:
                name: service
                port:
                  number: 80
            pathType: Prefix

**Expected outcome**
To have a new ALB rule created without errors on the controller's logs.

**Environment**

* AWS Load Balancer controller version --> v2.6.2
* Kubernetes version --> 1.26
* Using EKS (yes/no), if so version? --> yes 1.26

**Additional Context**:
- We update the `controller`  version regularly, as well as other components in the cluster.

**Comment by shraddhabang** [comment]
@velvetzhero Hey , If you are using the Ingress Group, then we recommend that you use same WAFv2 WebACL ARN among all the Ingresses within the Ingress group. 
If you have conflicts among the ingresses for this configuration, this is expected error from controller. 
Take a look at this: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/0b82ebbcc0b66d168e9ef74cd94b41b7e3e9a8ac/pkg/ingress/model_build_load_balancer_addons.go#L10

**Comment by velvetzhero** [comment]
@shraddhabang Thank you, it was on our end.
I had many looks at [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/0b82ebbcc0b66d168e9ef74cd94b41b7e3e9a8ac/pkg/ingress/model_build_load_balancer_addons.go#L29), but your last comment made me realise we may just have ingresses out there on the cluster that has the `wrong` WAF ACL..I was looking for errors on my codebase :] ( which was the wrong place to look into on the first place ! )
