### ISSUE TITLE
When using loadBalancerSourceranges with large amount of CIDRs to multiple frontend sec groups should be created

### ISSUE THREAD

**Issue by dylanhitt** [kubernetes-sigs/aws-load-balancer-controller#3538]
**Is your feature request related to a problem?**
When dealing with a large number of CIDRs the controller will fail to update it's frontend security group with:
```
"error":"RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.\n\tstatus code: 400
```

**Describe the solution you'd like**
Has there been any consideration for splitting up into separate security groups when the limit is reached? 

**Describe alternatives you've considered**
- Defining our own security groups with: `service.beta.kubernetes.io/aws-load-balancer-security-groups`
- Raising our limit in AWS with a request. (The max is of course 1000 rules). But if this could split out into groups that would be nice. for example we're currently maxed out at 200 rules since we elected to keep the default of 5 sec groups. To go higher we'd need to adjust to 4 sec groups for 250 rules and so on.

Thank you for a great project and I'd be happy to assist where I can.

**Comment by 2rs2ts** [comment]
I was wondering whatever became of my old request to add this feature to the in-tree provider that [I was told should be implemented in the LBC](https://github.com/kubernetes/kubernetes/issues/68684#issuecomment-1536471856); wondering if anyone ever made a request on this repo for it. So, thanks for opening this, pity though it is that it rotted. Hopefully someone either reopens this or tells us to make a new issue.

**Comment by dylanhitt** [comment]
Yes, this is very limiting. Luckily in my use case I can continue to consolidate down (we're no sitting at 333 rules for 3 groups). I personally hope AWS extends this feature. I know there are other solutions, but some [projects] require large numbers of rules. 

If this a feature that is determined that the community needs I'd be happy to implement.
