### ISSUE TITLE
Ingress Reconciliation Slowness

### ISSUE THREAD

**Issue by niroowns** [kubernetes-sigs/aws-load-balancer-controller#3540]
**Describe the bug**
We have a very large cluster with over 900 ingress objects (with both ingresses and ingress groups) and growing.  This cluster, on the restart of the controllers, is taking over 1.5 hrs to reconcile after some tuning and tweaks we've made.  The following controller flags have been tweaked:

- --ingress-max-concurrent-reconciles=**250**
- --targetgroupbinding-max-concurrent-reconciles=**250**
- --aws-api-throttle=WAF Regional:^AssociateWebACL|DisassociateWebACL=0.5:1,WAF Regional:^GetWebACLForResource|ListResourcesForWebACL=1:1,WAFV2:^AssociateWebACL|DisassociateWebACL=0.5:1,WAFV2:^GetWebACLForResource|ListResourcesForWebACL=1:1,Elastic Load Balancing v2:^RegisterTargets|^DeregisterTargets=4:20,Elastic Load Balancing v2:.*=**20:40**

At this point, we are noticing two things:
1) The controller is being limited by server side api limits such that we can't increase any of the above values for the tuning flags further
2) While this reconciliation happens (1.5 hrs), any CRUD commands to ingresses get delayed until the full reconciliation cycle is complete

**Expected outcome**
1) A CRUD event on ingresses should not be delayed during the reconciliation window
2) Ingresses should not take over 1.5 hours to reconcile

**Environment**

* AWS Load Balancer controller version: 2.6.2
* Kubernetes version: 1.27
* Using EKS (yes/no), if so version? Yes

**Additional Context**:  These are private clusters, so we can't take advantage of RGT.

**Comment by M00nF1sh** [comment]
@niroowns 
As a first step, I have built a patched image which cache the describeTags results. This shall dramatically reduce the APIcalls(especially) duration controller restart), thus reduce the time needed to reconcile new Ingresses.

The image is built on top of existing v2.6.2 release, and is available in dockerHub as `m00nf1sh/aws-load-balancer-controller:v2.6.2-cache-tags`, would you help test it?

**Comment by M00nF1sh** [comment]
the code for above image is https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3550

**Comment by niroowns** [comment]
Thanks @M00nF1sh , we'll try this in our development environment and report back.

**Comment by oliviassss** [comment]
Closing this issue as the fix being shipped with v2.7.1.
