### ISSUE TITLE
Helm Chart does not allow to set `--service-target-eni-security-group-tag` 

### ISSUE THREAD

**Issue by kitos9112** [kubernetes-sigs/aws-load-balancer-controller#3556]
**Is your feature request related to a problem?**
After successfully merging https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3147 into master, we can simply test the feature but cannot define it in our helm release value. 

There's no ability to configure `--service-target-eni-security-group-tag` in the helm chart as a custom argument.

**Describe the solution you'd like**
Be able to configure the new released flag to fit the current helm chart model.

**Describe alternatives you've considered**
[OR] have the option to pass custom arguments to the helm chart via extra values (it'd be nicer :))

**Comment by shraddhabang** [comment]
The [PR](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3147) did not add the ``--service-target-eni-security-group-tag`` value to Helm Chart values and hence the helm chart was not updated for it.

**Comment by shraddhabang** [comment]
We can add this to the current helm chart model to configure this via helm chart release
