### ISSUE TITLE
Enable configuring health-based detection for AWS Shield Advanced protections

### ISSUE THREAD

**Issue by hhamalai** [kubernetes-sigs/aws-load-balancer-controller#3562]
**Is your feature request related to a problem?**

I need to enable health-based detection capabilities on my dynamically created load balancer's AWS Shield protections as described here https://docs.aws.amazon.com/waf/latest/developerguide/ddos-advanced-health-checks.html

Defining the protections manually via AWS Console works, but is not automated/viable as load balancers from ingresses come and go.

**Describe the solution you'd like**
Extra ingress annotation, which (when Shield Advanced is in use) can be used to attach the existing route53 health check to my protection.

**Comment by shraddhabang** [comment]
@hhamalai Thank you for brining this to our attention. We are tracking this issue [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2777). We will be fixing this soon.

**Comment by shraddhabang** [comment]
@hhamalai Thank you for brining this to our attention. We are tracking this issue [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2777). We will be fixing this soon.
