### ISSUE TITLE
Ability to request TargetGroup only

### ISSUE THREAD

**Issue by plaformsre** [kubernetes-sigs/aws-load-balancer-controller#3578]
**Is your feature request related to a problem?**
Missing functionality to create an AWS TargetGroup without any type of an AWS Load Balancer. We have a use case where the Target Group has to be associated across AWS accounts and must not be associated to any other LB. 

**Describe the solution you'd like**
Create an AWS TargetGroup with one (1) or more Listeners without a Load Balancer solely with a K8S manifest that is being parsed by the AWS Load Balancer Controller.

The functionality is highly likely already there, what we need is a custom CRD being exposed called 'TargetGroup'.

**Describe alternatives you've considered**
Creating the TargetGroup with Terraform or CloudFormation, but this is suboptimal as then we have to manage not only K8s manifests for deployment, but also other infrastructure code (e.g. Terraform, cloud-formation).

**Comment by oliviassss** [comment]
@plaformsre, hi, you mean the AWS LBC should only manage TGs without any ALB or NLB? Can you try to deploy a targetgroupbinding? would it work for your use case?
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/targetgroupbinding/targetgroupbinding/

**Comment by uptickmetachu** [comment]
/reopen

This is still useful to my team.

We need the ability to have ALB controller manage / create targetgroups (by name if possible) against a service.

That way we can then create ingresses that share a single service without them creating/managing their own target groups.
