### ISSUE TITLE
Helm update to version 1.7.x resulting in pods Readiness probe failed: HTTP probe failed with statuscode: 404

### ISSUE THREAD

**Issue by myevit** [kubernetes-sigs/aws-load-balancer-controller#3582]
Helm update to version 1.7.x resulting in Pod: aws-load-balancer-controller Readiness probe failed: HTTP probe failed with statuscode: 404 

helm versions  1.4.1 through 1.6.2 working as expected 

1.7.x pod logs:
```
{"level":"info","ts":1708126775.380832,"msg":"version","GitVersion":"v2.4.6","GitCommit":"a92e689dfe464f5b24784f398947e0fef31dc470","BuildDate":"2023-01-12T06:29:16+0000"}
{"level":"info","ts":1708126775.410416,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1708126775.4145405,"logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":1708126775.414611,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1708126775.4146783,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1708126775.414728,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1708126775.4147651,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1-ingress"}
{"level":"info","ts":1708126775.4148157,"logger":"setup","msg":"starting podInfo repo"}
{"level":"info","ts":1708126777.415071,"msg":"starting metrics server","path":"/metrics"}
I0216 23:39:37.415030       1 leaderelection.go:243] attempting to acquire leader lease kube-system/aws-load-balancer-controller-leader...
{"level":"info","ts":1708126777.415177,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1708126777.4158258,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1708126777.415922,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1708126777.4159951,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
```

**Comment by greg-anetac** [comment]
+1 started seeing this today

**Comment by wweiwei-li** [comment]
This is known issue. Can you confirm that you are using latest version for controller also. If you are updating chart version, you need also to use v2.7.0 controller version

**Comment by myevit** [comment]
Helm chart reporting App Version v 2.7.1
Also, in the helm chart 1.7.1 it set to public.ecr.aws/eks/aws-load-balancer-controller:v2.4.6
whatever version is in that container the one is running in chart 1.7.1...
```
image:
  pullPolicy: IfNotPresent
  repository: public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.4.6
```

**Comment by wweiwei-li** [comment]
https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml. Here is the most recent helm chart, which links to the right controller version.  Can you tell us from where did you see the v2.4.6.

**Comment by ravikyada** [comment]
For this time, I changed the readiness probe health check back to "healthz", and its worked properly.

@davidkl97  Please check whether it is an issue or if any workaround needs to be done here.

**Comment by davidkl97** [comment]
Hey, @ravikyada which image version you are using?
please note that readiness probe change requires newer images as suggested [here](https://github.com/aws/eks-charts/pull/1059) due to the the fact that readyz endpoint registered in newer version(image version 2.7.0)

**Comment by ravikyada** [comment]
ok thank you @davidkl97 for the help
