### ISSUE TITLE
Documentation for in tree controller to manage load balancer services out of date

### ISSUE THREAD

**Issue by cpaton** [kubernetes-sigs/aws-load-balancer-controller#3583]
**Describe the bug**

Version 2.5.0 introduced a mutating webhook to default the ingress class of services of type load balancer on create.  Documentation on https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/nlb/#configuration doesn't mention this behaviour and continues to reference annotation values as a way to have the in tree controller manage the creation of the load balancer

**Steps to reproduce**

**Expected outcome**

Documentation matches default behaviour

**Environment**

* AWS Load Balancer controller version >= 2.5.0
* Kubernetes version : 1.27
* Using EKS (yes/no), if so version? 1.27

**Additional Context**:

**Comment by oliviassss** [comment]
@cpaton, thanks for pointing out. Community contribution to improve the doc is more than welcome.

/kind documentation
