### ISSUE TITLE
"null" should not be in quotes

### ISSUE THREAD

**Issue by bllfr0g** [kubernetes-sigs/aws-load-balancer-controller#3587]
**Describe the bug**

In v2_7_1_full.yaml, `"null"` is in quotes on lines 936 and 1023. It should not be quoted (and it isn't elsewhere.)

**Steps to reproduce**

`apply` the yaml file, get an error.

**Expected outcome**

`apply` the yaml file, no error.

**Environment**

* Kubernetes version

1.29

* Using EKS (yes/no), if so version?

yes, 1.29

**Comment by gg-kialo** [comment]
In previous releases (2.6.2) there was no `creationTimestamp` in the metadata of the webhooks.

**Comment by shraddhabang** [comment]
I have updated the yaml file with the fix. Thank you for bringing this to our notice.
