### ISSUE TITLE
occured error ' cannot parse "null" as "2006" ' when apply aws-load-balancer-controller v2_7_1_full.yaml

### ISSUE THREAD

**Issue by opgee** [kubernetes-sigs/aws-load-balancer-controller#3589]
**Describe the bug**
Therer are two config places (936 and 1023 row) of ` creationTimestamp: "null" ` on release yaml file https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.7.1/v2_7_1_full.yaml caused below errors when apply the yaml file to EKS:

unable to decode "v2_7_1_full.yaml": parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
unable to decode "v2_7_1_full.yaml": parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"

**Steps to reproduce**
1. download file: ` curl -Lo v2_7_1_full.yaml https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.7.1/v2_7_1_full.yaml `
2. check by: ` grep -Ei '"null"' ./v2_7_1_full.yaml `
3. apply by: ` kubectl apply -f v2_7_1_full.yaml `

**Expected outcome**
Unabled to created mutatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook and validatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook

**Environment**

* AWS Load Balancer controller version is v2.7.1
* Kubernetes version is 1.28
* Using EKS version is eks.7

**Additional Context**:
run cmd ` sed -i.bak -e 's|\"null\"|null|' ./v2_7_1_full.yaml ` to replace "null" with null to fix the issue.

**Comment by shraddhabang** [comment]
@opgee Thank you for bringing this to our attention. I have updated the ``v2_7_1_full.yaml `` file in the release notes.
