### ISSUE TITLE
IMDSv1 method in the Controller

### ISSUE THREAD

**Issue by Bruce-Lu674** [kubernetes-sigs/aws-load-balancer-controller#3604]
**Describe the bug**
Hi team,

I met the error when install the AWS Load Balancer Controller in Amazon EKS optimized AL2023 AMIs.

[ec2-user@ip-10-0-1-49 ~]$ kubectl get pod -n kube-system
NAME                                            READY   STATUS             RESTARTS        AGE
aws-load-balancer-controller-6dc89c6754-45q4s   0/1     CrashLoopBackOff   7 (4m5s ago)    24m
aws-load-balancer-controller-6dc89c6754-wjvjx   0/1     CrashLoopBackOff   7 (4m36s ago)   24m

Error Log:
[ec2-user@ip-10-0-1-49 ~]$ kubectl logs aws-load-balancer-controller-6dc89c6754-45q4s -n kube-system
{"level":"info","ts":"2024-03-06T07:04:37Z","msg":"version","GitVersion":"v2.7.1","GitCommit":"f689bbdf73d30f23b44acfef2c3b8e7280cd66ee","BuildDate":"2024-02-09T16:21:17+0000"}
{"level":"error","ts":"2024-03-06T07:04:40Z","logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect vpcID from EC2Metadata or Node name, specify --aws-vpc-id instead if EC2Metadata is unavailable: failed to fetch VPC ID from instance metadata: EC2MetadataError: failed to make EC2Metadata request\n\n\tstatus code: 401, request id: "}

**Steps to reproduce**
1. Create EKS 1.29 
and NodeGroup use AL2023
2. Deploy the AWS Load Balancer Controller by Helm
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=LAB-1-29 \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  --set enableShield=false \
  --set enableWaf=false \
  --set enableWafv2=false \

**Expected outcome**
AL2023 enforces the use of IMDSv2, the Controller should not continue to use IMDSv1 and there should be no errors in the deployment 

**Environment**
EKS 1.29
Nodegroup AL2023 Optimized ami

* AWS Load Balancer controller version   public.ecr.aws/eks/aws-load-balancer-controller:v2.7.1
* Kubernetes version 1.29
* Using EKS (yes/no), if so version? yes

**Additional Context**:
It looks like AWS ALB Controller is still using IMDSv1 to get VPC information, as described in the documentation(https://aws.amazon.com/cn/blogs/security/get-the-full-benefits-of-imdsv2-and-disable-imdsv1-across-your-aws-infrastructure/), it is not a safe way to continue using IMDSv1, for AWS customers, security is most important,May I know whether we have any plan to migrate to IMDSv2?

I check the AWS Go SDK still using v1, seems  v1 use the IMDSv1 to fetch the metadata, if aws load balancer have any plan to migrate to AWS SDK Go V2?

Related Code : 
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/networking/vpc_info_provider.go#L132
https://github.com/aws/aws-sdk-go-v2/blob/service/ec2/v1.149.4/service/ec2/api_op_DescribeVpcs.go#L21

This is Workaround (Manually specify the vpc-id):
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=LAB-1-29 \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  --set enableShield=false \
  --set enableWaf=false \
  --set enableWafv2=false \
  --set vpcId=vpc-xxxx

**Comment by oliviassss** [comment]
@Bruce-Lu674, thanks for the feedback. aws-sdk-go-v1 should use IMDSv2 by default, and if the IMSDv2 call fails, it will fall back to IMDSv1.
I was suspecting your IMDSv2 call failed, when using IMDSv2, you need to set the hop limit to 2 or higher in order to allow the LBC to perform the metadata introspection. Can you please double check?
You can refer to our live doc on how to set the hop limit, thanks. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/deploy/installation/#using-the-amazon-ec2-instance-metadata-server-version-2-imdsv2

**Comment by Bruce-Lu674** [comment]
@oliviassss Cool, that's useful !
