### ISSUE TITLE
alb-ingress-controller pod is restarting in kube-system namespaces after upgrading EKS cluster

### ISSUE THREAD

**Issue by yashwanth-bit** [kubernetes-sigs/aws-load-balancer-controller#3610]
Hi K8s,

I have update my EKS cluster from 1.21 to 1.25 , after upgrading i can't able to access my application from outside. when i check about issue i found alb-ingress-controller  pod in kube-system namespace is restaring multiple times and its prompting me with Back-off restarting failed container.

logs contain

-------------------------------------------------------------------------------

W0312 05:18:26.678877       1 config.go:46] Environment variable configuration is deprecated, switch to the --aws-region flag.
W0312 05:18:26.679169       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E0312 05:18:56.679789       1 manager.go:173] kubebuilder/manager "msg"="Failed to get API Group-Resources" "error"="Get https://172.20.0.1:443/api?timeout=32s: dial tcp 172.20.0.1:443: i/o timeout"  
F0312 05:18:56.679819       1 main.go:79] Get https://172.20.0.1:443/api?timeout=32s: dial tcp 172.20.0.1:443: i/o timeout
Logs from 12/03/2024, 0

Could you please help me out on this

**Comment by yashwanth-bit** [comment]
I am waiting for your reply. Could you please response ASAP

**Comment by M00nF1sh** [comment]
@yashwanth-bit 
it seems the controller cannot communicate to your kubernetes APIServer given `[https://172.20.0.1:443/api?timeout=32s](https://172.20.0.1/api?timeout=32s): dial tcp 172.20.0.1:443: i/o timeout`. 
The error occurs when APIServer is not reachable from the node where the controller runs in. It could be multiple factors e.g. APIServer is unhealthy, APIServer's endpoints it not updated somehow(e.g. no free IP address in your subnets for the upgrade or even incorrect security group settings. 
However, neither of them is a issue with this controller itself, I'd suggest open a support ticket with EKS support team via aws console to further resolve it.

**Comment by yashwanth-bit** [comment]
ok

**Comment by pbaveja** [comment]
hey @yashwanth-bit 

Did you resolve this error? How did you do this?

**Comment by 1mini2** [comment]
same here 🙋🏻‍♀️
```
│ {"level":"info","ts":"2024-05-29T11:59:58Z","msg":"version","GitVersion":"v2.5.1","GitCommit":"06abaed66e17a411ba064f34e6018b889780ac66","BuildDate":"2023-04-17T22:36:53+0000"}
│ {"level":"error","ts":"2024-05-29T12:00:28Z","msg":"Failed to get API Group-Resources","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": dial tcp 172.20.0.1:443: i/o timeout"}
│ {"level":"error","ts":"2024-05-29T12:00:28Z","logger":"setup","msg":"unable to start manager","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": dial tcp 172.20.0.1:443: i/o timeout"}
```

Can you share how you solved this?
