### ISSUE TITLE
Support for failover using latency routing

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [kubernetes-sigs/aws-load-balancer-controller#3611]
**Is your feature request related to a problem?**
We run applications in multiple regions and have latency routing set up, we wish to configure it so that if one region is unhealthy traffic would get routed to another region automatically

**Describe the solution you'd like**
I am not sure about implementation but I would expect to be able to easily implement this kind of routing. 
If such routing was based on DNS, I'd expect some documentation on how to actually make it work. 
If this feature was to be implemented on floating IPs then I would expect few extra annotations to configure it

**Describe alternatives you've considered**
None, currently we are trying to hack something together

**Comment by M00nF1sh** [comment]
such feature could only be implemented from ELB side.  
Adding a ELB feature flag tag for our elb team.
/kind feature

**Comment by shraddhabang** [comment]
@gytis-ivaskevicius Have you looked into trying out using [AWS Global accelerator](https://docs.aws.amazon.com/global-accelerator/latest/dg/introduction-benefits-of-migrating.html#:~:text=Acceleration%20for%20latency%2Dsensitive%20applications) with ALB for latency routing? We dont support this integration yet on our controller. But we can look into it if it solves your problem.

**Comment by gytis-ivaskevicius** [comment]
@shraddhabang This looks like exactly what we need! I'd love if you guys could add support for this
