### ISSUE TITLE
Feature to specify multiple certificate arns

### ISSUE THREAD

**Issue by eamon-straughn** [kubernetes-sigs/aws-load-balancer-controller#3623]
**Is your feature request related to a problem?**
It's really inconvenient not being able to specify multiple arns for certificates on the ELB requiring you to either manually add them each time you load an ingress or service. You should be able to specify multiple arns similar to how you can add multiple subnets in annotation.

**Describe the solution you'd like**
When I annotate multiple arns for certificates it should appear in the https listener automatically. ELB would be configured with all the certificates I specify. Currently you have to manually add the additional certs each time the ingress is specified.

**Describe alternatives you've considered**
Manually creating the load balancer but this doesn't solve the issue

**Comment by shraddhabang** [comment]
We do support multiple certficates for an [ingress](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#certificate-arn) and [services](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/#ssl-cert). Have you tried using these annotations?
