### ISSUE TITLE
Deployment not working with AL2023

### ISSUE THREAD

**Issue by fwy-bhaidas** [kubernetes-sigs/aws-load-balancer-controller#3625]
I Don't know whether this a bug, but when I used the AL2023, it the pod back-off restarting with below error. I am sure this AL2023 related issue as same version works with AL2.

I have tested this with helm version 1.6.0 & 1.7.2 and I am using Karpenter with Managed Node Groups to provision the nodes

`{"level":"error","ts":"2024-03-24T11:59:23Z","msg":"Failed to get API Group-Resources","error":"Get \"https://10.100.0.1:443/api?timeout=32s\": dial tcp 10.100.0.1:443: i/o timeout"}`

It would be highly appreciated if there instruction on how to use this for AL2023.

**Comment by huangm777** [comment]
Hi--thanks for bringing this to our attention. To clarify, are you trying to install the controller with AL2023 node groups on your cluster? We will try to reproduce the issue that way if so.

**Comment by fwy-bhaidas** [comment]
Hi @huangm777 , Sorry I raise the issue in hurry, so I may have provided insufficient data. 

I am trying to install Controller with the help of FluxCD GitOps way using helm chart, I have Karpenter provisioner which launch AL2023 AMI and this Controller getting installed on it using FluxCD. I hope this help.

Note: I have changed description in original issue above.

**Comment by aravindsagar** [comment]
Hi @fwy-bhaidas, thank you for elaborating on the issue. I tried reproducing the issue by launching an EC2 instance with AL2023 AMI, deploying a cluster there and installing aws-load-balancer-controller. I was able to bring up an ingress successfully. Please correct me if the issue you're facing is something else.

Also the error message you are seeing suggests an issue with communicating with kubernetes APIServer. Can you take a look at these issues and see if they're related?
1. https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3093
2. https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3610
