### ISSUE TITLE
Headless Service not registering with TargetGroup.

### ISSUE THREAD

**Issue by danieljimenez** [kubernetes-sigs/aws-load-balancer-controller#3636]
**Describe the bug**
Load balancer targets are not registered with a service when the service is set to "headless" mode.

**Steps to reproduce**
1. create a service manifest with the clusterIP set to "None", this makes a headless service
2. create a target group binding manifest with references to the service manifest

**Expected outcome**
nodes/pods running the service are registered with the load balancer target group in AWS.

**Environment**

* AWS Load Balancer controller version
v2.7.1
* Kubernetes version: 
```
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-508b6b3
```
* EKS Version: 
v1.29

**Additional Context**:
When I switch to a nodeport type, the nodes do register with the target group. Are headless services not supported?

**Comment by wweiwei-li** [comment]
@danieljimenez 
Can we know which mode do you use?  Are you using instance mode or ip mode for targetGroupBinding?

**Comment by danieljimenez** [comment]
I'm using the default, which I believe is `instance mode`.

**Comment by wweiwei-li** [comment]
Your Kubernetes service must specify the NodePort type to use instance mode.  Instead, you can switch to use IP mode by specify the `alb.ingress.kubernetes.io/target-type: ip`
