### ISSUE TITLE
 Using Target Type: IP in Production Environments

### ISSUE THREAD

**Issue by omegion** [kubernetes-sigs/aws-load-balancer-controller#3648]
Hi,

We're in the process of transitioning from CLB to ALB for our production clusters. We are evaluating whether to continue using the `instance` target type or switch to `ip`. Utilizing IP addresses could streamline the request path by reducing hops. However, the prospect of the ALB needing to register the IP of each pod during rotations raises concerns about potential complications.

Could anyone with experience in this area share insights or suggestions to help us make an informed decision? 🙏🏼

**Comment by wweiwei-li** [comment]
we would suggest use ip mode if transition to ALB as it will reduce hops. A lot of our existing users are using it.
