### ISSUE TITLE
Documentation missing for v2.7.2 release

### ISSUE THREAD

**Issue by stevehipwell** [kubernetes-sigs/aws-load-balancer-controller#3651]
**Describe the bug**
The documentation for the changes made in `v2.7.2` haven't been released.

As an aside why were SemVer minor changes added to a patch release?

**Steps to reproduce**
Look for the docs change in #3470 for `dns_record.client_routing_policy` in the latest (v2.7) [docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/).

**Expected outcome**
I'd expect to see the correct docs for the released versions.

**Environment**

* AWS Load Balancer controller version
* Kubernetes version
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by wweiwei-li** [comment]
Thanks for bringing this to our attention. The document is published and up to date
