### ISSUE TITLE
TargetGroupBinding is not working due to errornous target registration

### ISSUE THREAD

**Issue by scharwaechter** [kubernetes-sigs/aws-load-balancer-controller#3668]
**Describe the bug**
Referring to /main/pkg/targetgroupbinding/resource_manager.go, function registerPodEndpoints (line 409):  the instance id is set to the instance IP.   
This leads to errors during target registration:

{"level":"info","ts":"2024-04-29T11:26:54Z","msg":"registering targets","arn":"arn:aws:elasticloadbalancing:...","targets":[{"AvailabilityZone":null,"Id":"10.19.173.98","Port":8080}]}
{"level":"error","ts":"2024-04-29T11:26:54Z","msg":"Reconciler error","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","TargetGroupBinding":{"name":"tg-binding","namespace":"ns"},"namespace":"ns","name":"tg-binding","reconcileID":"545d72f9-6b2f-44d1-afba-94bfcfa538db","error":"ValidationError: Instance ID '10.19.173.98' is not valid\n\tstatus code: 400, request id: c2b1f56d-4d18-43cd-abd6-4ec175f1e286"}

**Steps to reproduce**
Add a TargetGroupBinding for a pod endpoint.

**Expected outcome**
Pod Endpoints are being registered as LB Targets via TargetGroupBinding.

**Environment**

* AWS Load Balancer controller version: 2.7.2
* Kubernetes version: 1.29
* Using EKS (yes/no), if so version? yes

**Additional Context**:

**Comment by scharwaechter** [comment]
Done. As usual, my fault. Thanks anyway

**Comment by ajhindle** [comment]
Hi @scharwaechter 
I'm getting this error too now.
What was your fix?
I'm seeing it in a new environment but haven't seen it in other environments with ALB controller before.
Thanks

**Comment by scharwaechter** [comment]
Hi @ajhindle,

in my situation it simply the wrong type of targetgroup. There are two types of targetgroups: instanceid and ip. The TargetType of the targetgroupbinding and the type of the target group must match.

Best regards,

Hanno
