### ISSUE TITLE
[Feature Request] Add Ingress/Service object annotations to support recently added HTTP client keepalive duration

### ISSUE THREAD

**Issue by kswift** [kubernetes-sigs/aws-load-balancer-controller#3670]
**Is your feature request related to a problem?**
Elastic Load Balancing team recently released `HTTP client keepalive duration` which can be configured for ALBs -> https://aws.amazon.com/about-aws/whats-new/2024/03/application-load-balancer-http-keepalive-duration/

This keepalive value specifies the maximum amount of time that ALB will maintain an HTTP connection with a client before closing the connection.

**Describe the solution you'd like**
Specify this duration value via Ingress/Service object annotations.

**Describe alternatives you've considered**
Configuring manually via awscli or console in meantime.

**Comment by omerap12** [comment]
Hey @shraddhabang , are you sure that's documentation issue?

**Comment by ChuksGrinage** [comment]
From what I understand, annotations are just a key/value pairing of the options available to the ALB. And seeing that [KAT](https://aws.amazon.com/about-aws/whats-new/2024/03/application-load-balancer-http-keepalive-duration/) is a fairly recent addition we can see how our annotation list would be out of date.

**Comment by ChuksGrinage** [comment]
We can confirm that you can set `client keepalive time (KAT)`  by simply including annotation:
For example: `alb.ingress.kubernetes.io/load-balancer-attributes: client_keep_alive.seconds=3600`

We are working to update the docs for future references

**Comment by omerap12** [comment]
@ChuksGrinage  so nothing is needed for me then?

**Comment by ChuksGrinage** [comment]
@omerap12 Yes, no action is needed. Thank you!
