### ISSUE TITLE
AWS LB controller only register pod as target if pod had passed readiness check

### ISSUE THREAD

**Issue by manhnt98** [kubernetes-sigs/aws-load-balancer-controller#3678]
Hi team, I've been searching around but haven't find a clear answer, can you confirm this:
- When using "ip" target type, the controller only register pod as target to Target Group if pod had passed readiness check and is Ready

I tested and it seem right, just need confirmation.

**Comment by manhnt98** [comment]
Ans is readiness checked in [this line](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/backend/endpoint_resolver.go#L174)

**Comment by andreybutenko** [comment]
Hi @manhnt98, thanks for the question!

Yes and yes - the controller only registers a pod as a target if the pod passed readiness checks, and that is the line of code with the readiness check :)

/kind question

**Comment by manhnt98** [comment]
Thank you!
