### ISSUE TITLE
ProviderID is not specified for node error in LBC v2.7.2

### ISSUE THREAD

**Issue by ArturChe** [kubernetes-sigs/aws-load-balancer-controller#3685]
**Describe the bug**
"Hi! I have updated the EKS version from 1.27 to 1.29 and the AWS Load Balancer Controller Helm chart from 1.5.5 to 1.7.2, and I've started to receive the following errors:
```
{"level":"error","ts":"2024-05-09T07:13:08Z","msg":"Reconciler error","controller":"targetGroupBinding","controllerGroup":"elbv2.k8s.aws","controllerKind":"TargetGroupBinding","TargetGroupBinding":{"name":"k8s-xxx","namespace":"prod"},"namespace":"prod","name":"k8s-xxx","reconcileID":"xxx","error":"providerID is not specified for node: ip-xxx.ec2.internal"}
```
Have I missed some configuration, or is this an AWS issue where it does not properly propagate the provider ID to nodes?

**Steps to reproduce**
Update Helm chart  from 1.5.5 to 1.7.2.

**Expected outcome**
No errors?

**Environment**

* AWS Load Balancer controller version v2.7.2
* Helm chart v1.7.2
* Kubernetes version 1.29
* Using EKS 1.29

**Comment by M00nF1sh** [comment]
@ArturChe 
The LBC requires nodes have providerID on node object, which shall exists on node object if you are using EKS.
Is it a transient error or constantly failing? would you help past the node YAML of your node here?

**Comment by huangm777** [comment]
Thanks for your feedback. As requested we will be closing the issue shortly.
