### ISSUE TITLE
You cannot enable both slow start and weighted random algorithm on a target group

### ISSUE THREAD

**Issue by ibalat** [kubernetes-sigs/aws-load-balancer-controller#3686]
**Describe the bug**
I am trying to update target group attributes but alb controller is logging below log. But, my attributes not include any slow start config. This error effect all target groups and it logging same error log for all target groups. It locked all alb

I use:
`"alb.ingress.kubernetes.io/target-group-attributes" = "load_balancing.algorithm.type=weighted_random, load_balancing.algorithm.anomaly_mitigation=on, deregistration_delay.timeout_seconds=35"`

I tried all combination like no attribute and slow_start.duration_seconds=0 but every time it logged same error

In UI:
<img width="861" alt="image" src="https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/146727489/8871ff77-1dda-4f1f-a9aa-a64fc2c59ec1">

```
{"level":"debug","ts":"2024-05-09T14:36:04Z","logger":"events","msg":"Failed deploy model due to InvalidConfigurationRequest: You cannot enable both slow start and weighted random algorithm on a  │
│ target group\n\tstatus code: 400, request id: xxx","type":"Warning","object":{"kind":"Ingress","namespace":"stage","name":"xxx","uid":"xxx","apiVersio │
│ n":"networking.k8s.io/v1","resourceVersion":"xxx"},"reason":"FailedDeployModel"}
```

**Expected outcome**
It have to update target group attributes

**Environment**

* AWS Load Balancer controller version v2.7.2
* Kubernetes version v1.29
* Using EKS (yes/no), if so version? yes

**Comment by ibalat** [comment]
we checked all ingress with `kubectl get ingress -nprod -oyaml | grep  -A 10 slow_start` and just one ingress contains "**slow_start**" configuration (_at the same time, this ingress set weigted algorithm on alb UI_). **This damaged ingress blocked all remain ingress updates.** I think that this situation is a bug. I guess alb controller merge all configs and update bulky. If one ingress has a problem, all others logs same error message and update not completed. Can it be solved please

**Comment by aravindsagar** [comment]
Hi, target groups do not support slow start and weighted random algorithm at the same time. Also if any of the ingresses in an ingress group is broken, updates to the whole group will fail. This is by design to avoid further issues arising.

Can you let us know if the slow start or the load balancing algorithm attributes were changed in the UI or it got into this state in some other way?
