### ISSUE TITLE
Service Monitor

### ISSUE THREAD

**Issue by rjop-hccgt** [kubernetes-sigs/aws-load-balancer-controller#3694]
**Describe the bug**
I believe there is an issue with the Helm chart, particularly in this line (https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/deployment.yaml#L30). I think the logic should be inverted and the prometheus labels should be added only when the `.Values.serviceMonitor.enabled` flag is set to `true`

**Steps to reproduce**
1. In the values.yaml set the `serviceMonitor.enabled` to `true`. 
2. Run `helm template ./ --values values.yaml | kubectl apply -f - `

**Expected outcome**
The AWS Load Balancer controller deployment shouldn't have the prometheus annotations enabled.

**Environment**

* AWS Load Balancer controller version: v2.7.2
* Kubernetes version: 1.29
* Using EKS (yes/no), if so version? yes, eks.6

**Additional Context**:

**Comment by omerap12** [comment]
Yes, I'll take this

**Comment by omerap12** [comment]
ping @rjop-hccgt

**Comment by rjop-hccgt** [comment]
thanks @omerap12

**Comment by omerap12** [comment]
Hey @oliviassss ,
I checked, and you're right—it’s done on purpose. But, with our current approach, we're forcing the use of Prometheus, either by using `ServiceMonitor` or annotations on deployments. Should we really be enforcing this?
