### ISSUE TITLE
Does not work on Fresh EKS Cluster with Amazon Linux 2023 AMI Type Nodes

### ISSUE THREAD

**Issue by sschamp** [kubernetes-sigs/aws-load-balancer-controller#3695]
**Describe the bug**
The pods fail to run on EKS Nodes which are using AL2023 instead of AL2:

```
{"level":"info","ts":"2024-05-14T10:15:35Z","msg":"version","GitVersion":"v2.7.2","GitCommit":"fb6460383b75e937e24548e69b6732f49b88755c","BuildDate":"2024-03-22T21:39:56+0000"}
{"level":"error","ts":"2024-05-14T10:15:38Z","logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect vpcID from EC2Metadata or Node name, specify --aws-vpc-id instead if EC2Metadata is unavailable: failed to fetch VPC ID from instance metadata: EC2MetadataError: failed to make EC2Metadata request\n\n\tstatus code: 401, request id: "}
```

**Steps to reproduce**

- Create a NodeGroup with any Instance Type but set the AMI Type to:
`Amazon Linux 2023 (x86_64) Standard (AL2023_x86_64_STANDARD)`
- Schedule `aws-load-balancer-controller-*` on the new Nodes (either by setting NodeAffinity, or by using a New Cluster)

**Expected outcome**
The Pods to be able to read the meta-data of the Node Instance.

**Environment**

* AWS Load Balancer controller version: 2.7.2
* Kubernetes version: EKS 1.29

**Additional Context**:

It might be because AL2023 no longer allows you to query `http://169.254.169.254/latest/meta-data/` directly.
They have started using IMDSv2 instead of IMDSv1. (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html)
You need to provide a token first:

`curl -s http://169.254.169.254/latest/meta-data/ --header "X-aws-ec2-metadata-token: $TOKEN"`

eg:
`/usr/bin/curl --noproxy '*' -w "\n" -s -H "X-aws-ec2-metadata-token: $(curl --noproxy '*' -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")" http://169.254.169.254/latest/meta-data/instance-id`

**Comment by oliviassss** [comment]
@sschamp, hi, it might be the ec2 instance use hop limit as 1 for default, can you change the hop limit to 2 and see if it fixes the issue? or you can specify the `--aws-vpc-id` directly through the controller flag.
see: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/deploy/installation/#using-the-amazon-ec2-instance-metadata-server-version-2-imdsv2

**Comment by sschamp** [comment]
I went with the option of manually specifying `--aws-vpc-id` and all is well again.
This issue can be closed.

**Comment by oliviassss** [comment]
Thanks for the confirmation, closing it now.

**Comment by oliviassss** [comment]
@fcuello-fudo, can you check your instance hop limit? in order for the controller to fetch the vpc id it requires the hop limit to be at least 2
we call out in live doc: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/deploy/installation/#using-the-amazon-ec2-instance-metadata-server-version-2-imdsv2

**Comment by jenademoodley** [comment]
By default, AL2023 nodes in a managed node group have the hop limit set to 1:
https://aws.amazon.com/blogs/containers/amazon-eks-optimized-amazon-linux-2023-amis-now-available/

> For IMDSv2 the default hop count for MNG is set to 1. 

Can we update the docs as this is a breaking change on the load balancer controller which users won't immediately be aware of.

**Comment by atheiman** [comment]
Can the pod not determine what VPC its running in with its pod identity association or IRSA role ?

**Comment by zswanson** [comment]
> Can the pod not determine what VPC its running in with its pod identity association or IRSA role ?

It can, but the default IMDS settings prevent pods from using it. You can either increase the hops on the nodes settings, or use hostNetwork=true on the controller pod as the workaround.

**Comment by reubenhEROAD** [comment]
The default `HttpPutResponseHopLimit` for AL2 `amazon-eks-node-1.30` images changed from 2 to 1 in the last three months. This is a flagrant change and ironic to me that this directly breaks AWS's own functionality (`aws-load-balancer-controller` with default config).

Versions:
```
karpenter_version             = "1.0.8"
eks_version                   = "1.30"
aws_lb_controller_app_version = "v2.10.1"
```

Karpenter `EC2NodeClass` manifest: 
```
Spec:
  Ami Family:  AL2
  Ami Selector Terms:
    Name:  amazon-eks-node-1.30-*
```

Error from `aws-load-balancer-controller` pod assigned to node using newer `amazon-eks-node-1.30` AMI: 
```
{"level":"error","ts":"2025-06-05T23:03:11Z","logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to get VPC ID: failed to fetch VPC ID from instance metadata: error in fetching vpc id through ec2 metadata: get mac metadata: operation error ec2imds: GetMetadata, canceled, context deadline exceeded"}
```

Default HttpPutResponseHopLimit changed between these two AMI versions: 
```
old: ami-0235c0f0b5d96077a amazon-eks-node-1.30-v20250317
new: ami-0a9de68e014a5fa58 amazon-eks-node-1.30-v20250519
```

Older AMI with default `HttpPutResponseHopLimit` set to 2:
```
$ aws ec2 describe-instances --instance-id i-004ce2660b1b45a07 --query 'Reservations[].Instances[].{ImageId:ImageId,HttpPutResponseHopLimit:MetadataOptions.HttpPutResponseHopLimit}' | jq -r .[]
{
  "ImageId": "ami-0235c0f0b5d96077a",
  "HttpPutResponseHopLimit": 2
}
```

Newer AMI with default `HttpPutResponseHopLimit` set to 1:
```
$ aws ec2 describe-instances --instance-id i-08b23ef67a01b0e9d --query 'Reservations[].Instances[].{ImageId:ImageId,HttpPutResponseHopLimit:MetadataOptions.HttpPutResponseHopLimit}' | jq -r .[]
{
  "ImageId": "ami-0a9de68e014a5fa58",
  "HttpPutResponseHopLimit": 1
}
```

I noticed this by chance in a non-production cluster, and I'm very lucky none of my production cluster assigned `aws-load-balancer-controller` pods to any Karpenter nodes using the newer AMI version. I wonder how many other people this has tripped up? Great lesson to always pin AMI versions.

**Comment by iterion** [comment]
How is there no response from AWS on this? This is a huge issue now on both Bottlerocket and AL2. The workaround for this is to use hostNetwork I guess? And yet, even the helm chart is defaulting to hostNetwork: false as I write this. Please consider addressing this in some way.

**Comment by Aiv114** [comment]
@iterion Yes its bad, it costed me a bit to figure this out but you have a few options: 
1 set http-put-response-hop-limit to 2 
2 Specify VPC in config

I went for hop limit increase but this is might not be the best option.

**Comment by ali-sheshkalani** [comment]
Could using Amazon EKS Pod Identity help fix this `failed to get VPC ID` issue with AWS Load Balancer Controller?
I already have the ServiceAccount and the pod identity association configured, but the controller still fails.

[update]
I noticed that many official docs (e.g., [Upgrade from Amazon Linux 2 to Amazon Linux 2023)](https://docs.aws.amazon.com/eks/latest/userguide/al2023.html) mention EKS Pod Identity as a way to avoid relying on IMDS. However, in practice it doesn’t seem to resolve the issue with the `aws-load-balancer-controller`.

The controller pod appears to fail before the EKS Pod Identity Agent can handle its request. As a workaround, if I provide the --`vpc-id` flag, the controller becomes healthy and I can then see related logs in the `eks-pod-identity-agent` pods.

This makes me think the controller first tries to fetch the VPC ID from IMDS, and if it’s not available, it never falls back to EKS Pod Identity. That behavior feels like a bug.

**Comment by madhan987** [comment]
If i want to update the `HttpPutResponseHopLimit to _2` using the command `aws ec2 modify-instance-metadata-options --http-put-response-hop-limit 2 --http-tokens required --region <region> --instance-id <instance-id>`. 

Do i need to update all the instances which are part of my NodeGroup manually?

**Comment by dsoprea** [comment]
I could use some guidance as to where to apply that `--aws-vpc-id` change suggested above. It's really not obvious to me. Is this supposed to be in the AWS LB addon config? In the node-group config?

We're seeing this failure *only* in the `aws-load-balancer-controller` pod:

```
{
    "time": "2025-09-03T01:59:41.992283653Z",
    "stream": "stderr",
    "_p": "F",
    "log": "{\"level\":\"error\",\"ts\":\"2025-09-03T01:59:41Z\",\"logger\":\"setup\",\"msg\":\"unable to initialize AWS cloud\",\"error\":\"failed to introspect vpcID from EC2Metadata or Node name, specify --aws-vpc-id instead if EC2Metadata is unavailable: failed to fetch VPC ID from instance metadata: EC2MetadataError: failed to make EC2Metadata request\\n\\n\\tstatus code: 401, request id: \"}",
    "log_processed": {
        "level": "error",
        "ts": "2025-09-03T01:59:41Z",
        "logger": "setup",
        "msg": "unable to initialize AWS cloud",
        "error": "failed to introspect vpcID from EC2Metadata or Node name, specify --aws-vpc-id instead if EC2Metadata is unavailable: failed to fetch VPC ID from instance metadata: EC2MetadataError: failed to make EC2Metadata request\n\n\tstatus code: 401, request id: "
    },
    "kubernetes": {
        "pod_name": "aws-load-balancer-controller-5dd457665-wtd2r",
        "namespace_name": "kube-system",
        "pod_id": "94a898e9-296a-4d2a-a2de-51d83273b706",
        "host": "ip-10-1-41-8.us-west-2.compute.internal",
        "container_name": "aws-load-balancer-controller",
        "docker_id": "b88342f3b6d495b4deea1b5ae4bd603b7e33e71077147e530af8a34c3b639765",
        "container_hash": "public.ecr.aws/eks/aws-load-balancer-controller@sha256:3b2a740425b6c540686f12c640d8871964cc194cecbc4babdf9769fd27cd54f1",
        "container_image": "public.ecr.aws/eks/aws-load-balancer-controller:v2.7.1"
    }
}
```

It's restarting constantly in one of our environments (not all of them; we're using workspaces, and the Terraform config is otherwise identical). The documentation for the AWS LB addon/chart is here, for reference:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/values.yaml

There is a `vpcId` option that I'd expect to be the equivalent of `--aws-vpc-id`:

```
  enable_aws_load_balancer_controller = true

  aws_load_balancer_controller = {
    values = [
      <<-EOT
      tolerations:
        - key: karpenter.sh/controller
          value: "true"
          effect: NoSchedule

      vpcId: ${var.vpc_id}
      EOT
    ]
  }
```

(The `tolerations` option is already present in our config.)

When I try to apply this, it suddenly seems to want to remove all of the metadata. Why could this possibly be?

<img width="788" height="685" alt="Image" src="https://github.com/user-attachments/assets/b0e0482a-a499-4f0c-bc7d-cf69d3721af1" />


When I remove `vpcId`, the plan becomes a no-op, so it's definitely because of that option.

Thank you.
