### ISSUE TITLE
[Doc] Worker node security groups selection

### ISSUE THREAD

**Issue by yyyoungha** [kubernetes-sigs/aws-load-balancer-controller#3705]
**Is your feature request related to a problem?**
[Worker node security groups selection](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/9b4999b63ca90c53fb3dbe3c823b8ca7fa84ba3d/docs/guide/service/nlb.md#worker-node-security-groups-selection) is only mentioned under the [/docs/guide/service/](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/9b4999b63ca90c53fb3dbe3c823b8ca7fa84ba3d/docs/guide/service) path. However, I have found through testing that this works the same in Ingress. 

The path to which this document is located may lead one to misunderstand that this only applies to Services and not Ingress.

**Describe the solution you'd like**
Worker node security groups selection is the same in Ingress, so this content should also be included in the Ingress guide.

**Describe alternatives you've considered**
Since it applies to both Ingress and Service, it would also be a good to create a separate folder under the [/docs/guide](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/9b4999b63ca90c53fb3dbe3c823b8ca7fa84ba3d/docs/guide) path and explain how LBC detects security groups and add rules.

**Comment by shethyogita83** [comment]
Hi @yyyoungha, 

Thanks for reaching out.
Appreciate all the detailed info and your suggestion!

Our team will look into this and will try to put it on our tasks list for doc updates.

Thanks

**Comment by oliviassss** [comment]
@yyyoungha, we originally have this doc in service side, because they are for backend service. I think it's the same case for ingress because of the backend svc that ingress is on, so I'd prefer to leave the doc in service side.

**Comment by oliviassss** [comment]
Closing this issue as for now, please feel free to reopen if any follow-up questions. Thanks
