### ISSUE TITLE
Potential thundering herd caused by readiness probes triggering deregistration when using IP target type

### ISSUE THREAD

**Issue by thefirstofthe300** [kubernetes-sigs/aws-load-balancer-controller#3711]
**Describe the bug**
I honestly feel like this is more of a documentation bug than anything. Here's my scenario:

I recently was part of an outage caused by our readiness probes all failing at once during a chaos test. We found the bug that caused the outage and fixed it; however, our RCA basically boiled down to the readiness probes all failing at once resulted in a thundering herd exacerbated by the behavior of the AWS LB controller. For some context, we use the IP target type.

The ALB controller resolves targets for a TargetGroupBinding using the Kubernetes Endpoints and EndpointSlices APIs. If an endpoint is not found in that list but is found in the ALB targets, the endpoint is immediately deregistered.

In our failure mode, all targets become unready due to failing k8s readiness probes. Immediately upon failing the readiness probe check, Kubernetes removed the pod from the serving pool which is expected behavior according to the k8s API. What was unexpected was the immediate deregistration of all targets from the ALB. The pods were still alive and serving. Our assumption was that the ALB health checks would fail, triggering the fail-open mechanism and distribute load across all of our pods.

Instead, the controller did the exact opposite of best practice during a thundering herd scenario. It deregistered all targets and only reintroduced targets that were marked as ready. The pod would then immediately be crushed by the thousands of requests being directed to it by the ALB, fail the readiness probe, and be deregistered. The ALB was unable to fail-open due to the constant churn of registered targets.

Upon further investigation, we determined that a more correct way to configure our load balancers would be to use a headless service for our TargetGroupBindings with the `publishNotReadyAddresses` flag set to true and configure the LB health check to point to our readiness probe. This configuration places more of the onus to make proper routing decisions back onto the LB and simplifies the actions taken by the LB controller.

I do not believe I have seen this sort of configuration documented anywhere or this potential mechanism for inducing a thundering herd described in any of the documentation.

Two questions
1) Am I correct in understanding how TargetGroupBinding resources resolve Kubernetes endpoints?
2) Is the proposed configuration viable and are there any potential pitfalls with it?

Finally, it would be nice to have this type of failure documented as a potential failure mode if care is not taken with proper configuration with IP type targets.

**Comment by M00nF1sh** [comment]
@thefirstofthe300
>  1. Am I correct in understanding how TargetGroupBinding resources resolve Kubernetes endpoints?
> Instead, the controller did the exact opposite of best practice during a thundering herd scenario. It deregistered all targets and only reintroduced targets that were marked as ready.

Yes, the TargetGroupBinding resource expects pod's container ready to be true for a target to be registered. Personally think you should tune your readiness probes thus it don't mark pod as not ready. Since under normal logic, a "unready pod" shall be take out of service. It feels your readiness probes is incorrect somehow, as if your "pod" is indeed able to handle traffic, it shall be ready instead of fail, would you share more details?

We do have a special ["fail open" support](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.8.0/pkg/backend/endpoint_resolver.go#L210) that if all nodes stoped reporting health check, we will keep targets in ALBs instead of register them at once. 


2. Is the proposed configuration viable and are there any potential pitfalls with it?
Use "publishNotReadyAddresses" works due to we use endpoint's ready before pod container ready check. It's ok to do this way(use the targetGroup's health checks) as long as you are doing http based checks.

**Comment by thefirstofthe300** [comment]
In the case of the fail-open support, it wouldn't have helped us based on the condition our service was in. The nodes were all healthy and functional. It was the pods themselves that were experiencing the issue. From what I'm seeing in that code, the fail-open support only kicks in if the nodes on which the pods are scheduled are all in an Unknown state but the pods themselves were last reported to be healthy.

Our readiness probe is more or less correct. Our service is written in Java and makes use of thread pools for the request handlers. Request mapping to threads is exactly 1:1. 

In our case, the readiness probe was functional; however, there were no serving threads available to handle the readiness probe causing the timeout. There's a number of ways we can improve our ability to shed load quickly to prevent thread exhaustion, but that work isn't something we can really get to right away. In the meantime, we really need some sort of solution that allows us to distribute load across all of our pods; hence, the desire to use a service that publishes all endpoints regardless of readiness and relies on the ALB configuration to determine whether a pod is in a good state to serve traffic.

I was entirely unaware of the fail open support. It appears to be buried in the docs under the feature gates section. Given how common a thundering herd failure mode is for high traffic volume services, it is probably worth addressing both the fail-open support and configurations to deal with thundering herd in the docs as both are currently non-obvious.
