### ISSUE TITLE
Typo in the release docs - the word "requrired" instead of "required"

### ISSUE THREAD

**Issue by kyandaks** [kubernetes-sigs/aws-load-balancer-controller#3713]
**Describe the bug**
In the docs on the release page, the word "requrired" is used instead of "required"
Page - https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases?page=2

Sections to update:
- v2.5.1
- v2.4.7

![image](https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/45067380/04e6764c-4798-48c4-8538-b888b2b01d36)

**Comment by M00nF1sh** [comment]
Thanks for pointing those out :D the release notes were manually drafted. 
Just corrected the typos :D
