### ISSUE TITLE
SecurityHub ELB.4 - DropHttpHeaders Default to false - support bool routing.http.drop_invalid_header_fields.enabled

### ISSUE THREAD

**Issue by riverad03** [kubernetes-sigs/aws-load-balancer-controller#3726]
## Problem to Solve ##
Security Hub Issue ELB.4 can not be supported without the support of the drop_invalid_header_fields.enabled bool configuration
Allowing for this change to ALB configurations of Kube clusters. This control evaluates AWS Application Load Balancers (ALB) to ensure they are configured to drop http headers. By default, ALBs are not configured to drop invalid http header values.

## What is the goal of the topic? (optional) ##
To allow a setting in aws-load-balancer-controller and then to ensure ALB configured by aws-load-balancer-controller  will be properly configure an ALB to dropInvalidHttpHeaders when the boolean is configured to True

## Impact ##
This will allow Security Hub Issue ELB.4 to be support in aws-load-balancer-controller 

## Solution ##
What needs to be changed
Change code that manages ALB configuration and allow for the dropInvalidHttpHeaders.enabled value to be set, and then implement the configuration change on the ALB implementation code to support the configuration

Create test cases for this configuration

## Acceptance Criteria ##
Test run showing the setting set, and the mock has the value set or not set

**Comment by wweiwei-li** [comment]
we can support the LB attributes by specifying it here like :  https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#custom-attributes:~:text=Custom-,attributes,-%C2%B6.  Can you reference to it ?

**Comment by andreybutenko** [comment]
Here is an example of how to set this attribute with existing AWS LBC annotations:

```
alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
```

For reference:

* [LBC docs for load balancer attributes](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#load-balancer-attributes)
* [ELB docs for load balancer attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html)

Please post if you have any questions or concerns :) thank you!

**Comment by universam1** [comment]
@wweiwei-li @andreybutenko The mentioned annotations are applied per Ingress resource, but not globally as a default at the controller? That's an issue for us, because we cannot enforce security policies at cluster level, which in practical term requires training of many developers instead of one central configuration provided by infra team.
