### ISSUE TITLE
cilium hubble does not see aws-loadbalancer-controller calls to sts.eu-west-3.amazonaws.com

### ISSUE THREAD

**Issue by faelis** [kubernetes-sigs/aws-load-balancer-controller#3741]
**Describe the bug**
When trying to audit the network I/O with cilium hubble, I can't see the flow between the aws-loadbalancer-controller and the fqdn sts.eu-west3.amazonaws.com.
I also tested a ciliumnetworkpolicy that allow tofqdn to sts.eu-west-3.amazonaws.com, it throw a i/o timeout error when requesting sts.eu-west-3.amazonaws.com, But cilium hubble does not show any drop, it not even show the DNS request made by the pod to resolve sts.eu-west-3.amazonaws.com

Where is the magic?

**Steps to reproduce**
spin up EKS + no CNI chaining + cilium + no kube-proxy + aws-loadbalancer-controller with IRSA
**Expected outcome**
Seeing all the flow related to the aws-loadbalancer-controller pod.

**Environment**

* AWS Load Balancer controller version : v2.7.1
* Kubernetes version : 1.29
* EKS: v1.29.1-eks-61c0bbb ; OS: Bottlerocket OS 1.20.1 (aws-k8s-1.29) ; kernel:  6.1.90

**Additional Context**:
none

**Comment by M00nF1sh** [comment]
@faelis 
It depends on how you setups the controller. If you run the controller without IRSA(Iam for service accounts), then it won't make sts calls(instead it obtain iam credentials from ec2 metadata)

**Comment by faelis** [comment]
@M00nF1sh
Thanks to have a look at my issue :),
Our controller run with IRSA. we can confirm this because with une fqdn network policy, it log a timeout when calling sts endpoint.
