### ISSUE TITLE
incorrect logging configuration prevents visibility of controller runtime trace logs

### ISSUE THREAD

**Issue by cnmcavoy** [kubernetes-sigs/aws-load-balancer-controller#3744]
**Describe the bug**
ALB Controller logging incorrectly configures go.uber.org zap logging instead of controller runtime's zap logging configuration. As a result, any logs printed at `V(2)` or higher verbosity can not be seen, even at "debug" level logging. 

**Steps to reproduce**
Enable debug level logs, and look for any `V(2)` level log statements. They won't appear in the logs.

**Expected outcome**
Expected enabling "debug" logging to reveal debug logs.

**Environment**

* AWS Load Balancer controller version: 2.8.1
* Kubernetes version: Server Version: v1.28.9-eks-036c24b
* Using EKS (yes/no), if so version? yes

**Additional Context**:

**Comment by ChuksGrinage** [comment]
Hello, thanks for reporting the issue and publishing a PR. We are currently reviewing. /kind bug
