### ISSUE TITLE
Backend-protocol version to HTTP2/GRPC not working with istio ingress backend for ALB.

### ISSUE THREAD

**Issue by anannaya** [kubernetes-sigs/aws-load-balancer-controller#3751]
**Describe the bug** 
Backend-protocol version to HTTP2/GRPC not working with istio ingress backend for ALB.

**Steps to reproduce**
Add the annotation to ingress object : alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
**Expected outcome**
Protocol version should change in istio ingress bakend pods in target groups.
**Environment**
EKS
* AWS Load Balancer controller version ; 2.5.3
* Kubernetes version 1.27
* Using EKS (yes/no), if so version?
Yes. v1.27.9-eks-5e0fdde
**Additional Context**:

**Comment by ChuksGrinage** [comment]
Thanks for bringing this to our attention. Could you provide us with your logs and configuration manifest? /kind/bug

**Comment by anannaya** [comment]
I don't know its a issue or not.  But the problem is Ingress annotaion does not overwrite the k8s Service annotation,  So my case i had to manually edit the service to make it work.
