### ISSUE TITLE
Ignore manual added resources to ALB

### ISSUE THREAD

**Issue by martin-finalis** [kubernetes-sigs/aws-load-balancer-controller#3763]
**Is your feature request related to a problem?**
I am trying to avoid alb controller to remove listeners that are being added outside the controller. For example, some lambda functions are being created with node + serverless framework (which adds itself the rule in the listener). As soon as the controller starts reconciling, those rules are deleted.

**Describe the solution you'd like**
Some way to instruct alb controller that should ignore some rules.

**Describe alternatives you've considered**
I tried [external-managed-tags](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/configurations/) without success.

**Comment by oliviassss** [comment]
@martin-finalis, The controller reconciles per the manifest as other k8s controller, with that said, it is supposed to manage the resources created by it, and to revert any manual modifications to it. We call out in the live doc: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/how-it-works/

In your use case, iiuc, the rules are added externally and got reverted? if the rule is not created by the controller, the controller should not remove them. Can you double-check for these rules, do you have the AWS resource tags
```
elbv2.k8s.aws/cluster: ${clusterName}
ingress.k8s.aws/stack: ${stackID}
ingress.k8s.aws/resource: ${resourceID}
```
As the controller will uses these tags to track the resources created by it and manage them. If you want to bypass this maybe have the lambda function not to add these tags to the rules.
You can check here for more details: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/guide/ingress/annotations/#resource-tags

**Comment by martin-finalis** [comment]
Hi! sorry for the delay on the reply. So far I tried:

- not adding any tag to the lambdas
- adding some predefined tag (ie: donotdelete = 1) to the lambda, and the same as an external tag `--external-managed-tags=[donotdelete=1]`
- adding the same exact tags as any other rule

but everytime the lambda created rule is deleted.

Thanks!!

**Comment by martin-finalis** [comment]
Sorry if i caused some inconvenience, but i am still with this issue. Maybe is an expected behaviour, and in that case is ok. But i believe that i am missconfiguring something, i am using the controller for a while and i think that has to be a way to manual add rules to the alb listener without being deleted

**Comment by modevops** [comment]
I am trying to do path based routing between eks  and and ec2 instance by deleting manually added resources it defeats the purpose of having a customer mananged loadbalancer. Alb ingress should not delete manually added resources on a customer managed loadbalancer.  It should not delete the listener. Right now it impossible to share an alb between eks and ec2 instance.  To me it is very poor design. Why will you not fix this issue.

**Comment by JannatBawa** [comment]
The product should provide the ignore rules as well
