### ISSUE TITLE
helm chart repository at github.io is currently down

### ISSUE THREAD

**Issue by fusionx1** [kubernetes-sigs/aws-load-balancer-controller#3772]
**Describe the bug**
helm chart repository at github.io is currently down

**Steps to reproduce**
run the ff commands:
helm install aws-load-balancer-controller eks/aws-load-balancer-controller --set clusterName=xxxxxxx -n kube-system --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller

**Expected outcome**
Im getting this error `Error: INSTALLATION FAILED: Get "https://aws.github.io/eks-charts/aws-load-balancer-controller-1.7.2.tgz": read tcp 192.168.1.5:55044->185.199.109.153:443: read: connection reset by peer`

**Environment**
im using the latest branch on our test branch

* AWS Load Balancer controller version - 1.7.2
* Kubernetes version 1.28
* Using EKS (yes/no), if so version? yes

**Additional Context**:

**Comment by shraddhabang** [comment]
Do you mean controller version v2.7.2 instead of v1.7.2?

**Comment by shraddhabang** [comment]
Could you please try to curl this HTTP address please? It looks like a connection issue to us.

**Comment by shraddhabang** [comment]
Also could you please try to first update the helm repo and then try to install the controller through it?
`helm repo update`
