### ISSUE TITLE
[Feature Request]: Cause Of "but with different settings" Message

### ISSUE THREAD

**Issue by jrbil** [kubernetes-sigs/aws-load-balancer-controller#3774]
**Is your feature request related to a problem?**

Customers have to manually compare settings between Load Balancers/Target Groups when these errors messages are generated:

```A load balancer with the same name 'XXXXXXX' exists, but with different settings.```

```A target group with the same name 'XXXXXXX' exists, but with different settings.```

**Describe the solution you'd like**

Is there a way to generate the cause of the message or provide additional information?

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by M00nF1sh** [comment]
/kind bug
This seems to be triggered by the idempotent behavior of ELB APIs.   
The controller tries to find a LB/TargetGroup by tags and then tries to create one if none found. From this error message, seems it didn't found a LB and tries to create one but the ELB rejected it. 
Would you help share some information for us to debug further?
1. the name and AWS tags on the load balancer and target group of the name "xxxxxx".
2. the Ingress/Service's namespace/name that shows the error message when reconciling?

**Comment by jrbil** [comment]
@M00nF1sh 
&nbsp;
In this case:

1. The customer's Service was using a NLB that was created outside of Service but a custom TargetGroupBinding was not being used to manage it. The NLB was created before Security Groups were introduced for NLBs. 

2. Previously v2.4.0 of the AWS Load Balancer Controller was installed which doesn't support Security Groups for NLBs.

3. The customer upgraded to v2.6.0 of the Controller which supports Security Groups. As part of their upgrade process for their Services the customer deleted and recreated the Service. The Controller tried to manage the NLB but couldn't due to it not having a default Security Group, leading to the error.
&nbsp;

The workaround was to:

1. Set the **```--feature-gates=NLBSecurityGroup=false```** argument in the Controller's Deployment to disable NLB Security Groups.

2. Set the **```--deletion_protection.enabled=true```**  parameter in the Service to prevent deletion of the NLB and its Listener and Target Group.

3. Delete the Service.

   - kubectl showed that the delete failed because the Listener and Target Group can't be deleted.


4. Reinstall the Service.

5. Recommend to the customer that they use a custom TargetGroupBinding to manage the NLBs going forward.
&nbsp;
Feature request is to have the message say something like ```A load balancer with the same name 'XXXXXXX' exists, but with different settings. Setting not found: load balancer 'XXXXXXX' is missing a Security Group```.

**Comment by fabn** [comment]
+1000 for this, it's very weird to have a message saying that settings are different without knowing which ones
