### ISSUE TITLE
Erro to start controller

### ISSUE THREAD

**Issue by gustavoffilho** [kubernetes-sigs/aws-load-balancer-controller#3777]
Hi,

When I try to install the controller by helm in EKS , I have the error message:

FailedCreate        replicaset/aws-load-balancer-controller-6b8c57f774   Error creating: Timeout: request did not complete within requested timeout - context deadline exceeded

Any ideia about it?

**Comment by M00nF1sh** [comment]
this seems not a issue for this controller but issues with the APIServer/ETCD itself.

Would you help open a support case with EKS team through aws console?
