### ISSUE TITLE
switch to aws-sdk-go-v2 as v1 is going away

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/aws-load-balancer-controller#3784]
Context: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/
Migration guide: https://aws.github.io/aws-sdk-go-v2/docs/migrating/

Basically maintenance mode on July 31, 2024 and reach end-of-support on July 31, 2025. The SDK will not 
receive API updates for new or existing services, or be updated to support new regions.

**Comment by shraddhabang** [comment]
Thank you for pointing it out. We are aware of this. We will soon start work on this.
