### ISSUE TITLE
How can we get LoadBalancer ARN

### ISSUE THREAD

**Issue by LuoYuWuSheng** [kubernetes-sigs/aws-load-balancer-controller#3787]
**Is your feature request related to a problem?**
NO

**Describe the solution you'd like**
Some CloudProvider patch the LoadBalancer ID on k8s service‘s annotations
Can ALB support this feature？

**Comment by wweiwei-li** [comment]
Hey, to better understand your feature request, can you elaborate on the solution. else, can you provide reference to CloudProviders who patch the LoadBalancer ID on k8s service‘s annotations.
