### ISSUE TITLE
One misconfigured ingress breaks all the others

### ISSUE THREAD

**Issue by RobinFrcd** [kubernetes-sigs/aws-load-balancer-controller#3790]
**Describe the bug**
Hi,
When I deploy a single misconfigured ingress, it breaks all futures ingresses. For example, if I deploy an ingress with a host that has no certificate, I get: `Warning  FailedBuildModel        22m (x469 over 4d21h)  ingress  Failed build model due to ingress: InvalidIngress: no certificate found for host: ...`. But not only for this `InvalidIngress`, for all future ones.

**Steps to reproduce**
1. Create any **invalid** ingress: `invalid-ingress` (with invalid host for example)
2. Create a **valid** ingress: `valid-ingress`
3.  `valid-ingress` is stuck with a `FailedBuildModel` from `invalid-ingress`

**Expected outcome**
A single invalid ingress shouldn't block the whole controller. Only concerned ingress should be affected.

Thank you very much !

PS: Not sure why `Warning  FailedBuildModel` is a warning when the ingress is 100% down when having this warning.

**Comment by wweiwei-li** [comment]
Hey, are you creating these ingresses in a single ingress.group to share an ALB. Or you were creating two independent ingress.

**Comment by RobinFrcd** [comment]
Hi, yes indeed, I share the loadbalancer to save costs as have more than 40 ingresses !

**Comment by wweiwei-li** [comment]
When you are using ingress group, this is by designed. We would suggest you fix or remove the bad ingress.
