### ISSUE TITLE
How to troubleshoot controller errors? Failed deploy model due to InvalidParameter: 1 validation error(s)

### ISSUE THREAD

**Issue by brunopadz** [kubernetes-sigs/aws-load-balancer-controller#3811]
**Describe the bug**
It's not necessarily a bug, but I'm having a hard time trying to find out what's the root cause of an error.

I'm basically getting the following error on all my Ingresses: 
```
Failed deploy model due to InvalidParameter: 1 validation error(s). minimum field value of 1, CreateTargetGroupInput.Port.
```

I know it's a well documented error, and I've already configured the `alb.ingress.kubernetes.io/target-type = ip`, checked the SG for any tag misconfig and everything seems fine.

I've also increased the log level to debug, but it doesn't help much since the error returns for all the ingresses.

Is there anything else I can do to see what could be the issue? I'm really running out of ideas.

**Expected outcome**
Ingresses successfully reconciled 

**Environment**

* AWS Load Balancer controller version: 2.8.2
* Kubernetes version: 1.28
* Using EKS (yes/no), if so version?: yes - 1.28.11-eks-db83b0

**Comment by M00nF1sh** [comment]
@brunopadz 
There should be an log like "successfully built model: <a json blob>", would you help post it here.

/kind bug
we should error out quickly instead of throw the error when calling aws sdk

**Comment by brunopadz** [comment]
Hey @M00nF1sh, yeah, I noticed that last Friday and it helped identify the issue.

Thanks a million.
