### ISSUE TITLE
setting `hostNetwork` now required with aws vpc cni when using karpenter v1.0

### ISSUE THREAD

**Issue by applike-ss** [kubernetes-sigs/aws-load-balancer-controller#3818]
**Describe the bug**
With karpenter v1.0 the put hop count on the ec2 node classes are set from 2 to 1, which makes pods unable to use the IMDS.

My assumption is that the comment about `hostNetwork` which states that it is not needed for aws vpc cni is not correct anymore.

I believe it might need adjustment to:
```
# Specifies if aws-load-balancer-controller should be started in hostNetwork mode.
# This is required if using a custom CNI where the managed control plane nodes are unable to initiate
# network connections to the pods, for example using Calico CNI plugin on EKS. This is not required or
# recommended if using the Amazon VPC CNI plugin, unless karpenter >= v1.0 is in use.
# With karpenter >= v1.0 in use you have to set your region and vpcId, because it sets your node pools `spec.metadataOptions.httpPutResponseHopLimit=1`).
```

Let me know if i'm doing something wrong here, however enabling host networking on a pod does not sounds ideal to me.
I'd believe that both makes sense:
* karpenter setting the hop count to 1 (ensuring a malicious pod gets as few information as possible)
* aws-load-balancer-controller not enabling host networking by default

So I'd suggest the user to set region and vpcId to not have the load balancer controller ask for it via the metadata service.

**Comment by applike-ss** [comment]
refs:
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1561
* https://github.com/kubernetes-sigs/karpenter/releases/tag/v1.0.0

**Comment by applike-ss** [comment]
> @applike-ss Also note, that you can restore karpenter's previous behavior by just adding: `spec.metadataOptions.httpPutResponseHopLimit` to the EC2NodeClass, like so:
> 
> ```
> apiVersion: karpenter.k8s.aws/v1beta1
> kind: EC2NodeClass
> metadata:
>   name: blue
> spec:
>   metadataOptions:
>     httpPutResponseHopLimit: 2
> ```
> 
> https://karpenter.sh/docs/concepts/nodeclasses/#specmetadataoptions

Thank you, i am aware of that.
I do wonder now what is the proposed usage.
I would like to use the best practice here (which i assume to be hopCount=1 on the karpenter node pool AND not using host networking.
If i get it right, then i do have to specify region and vpcId in my case of using aws + karpenter v1 default values. Am I wrong?

**Comment by applike-ss** [comment]
@asaf400 yes, afaik there is two methods of injecting aws authentication variables for pods. One being the traditional IRSA method via pod identity webhook and the newer one being pod identity agent (eks-addon).

I am using the traditional method and thus would also need to specify the region, however I also specified the vpcId.

Do you know if the vpcId is even needed? I did not test it tbh., but i assumed that i would need to specify it to make sure the alb controller does not need to request the IMDS to determine its vpcId for searching for subnets.

**Comment by applike-ss** [comment]
I just had a quick peek and in fact the metadata service will be asked for the vpcId when it is not given from external or could not be inferred based on some tag on the vpc.

`main.go` calls `aws.NewCloud`, which then calls `getVpcID`.

This func tries to first infer it based on the name tag (or custom one if given) of the vpc.

If that fails, it is being inferred via the metadata.

**Comment by Viggy07** [comment]
I see the same issue with accessing metadata after upgrading the Karpenter to V1 with EKS pod identity as well.

**Comment by applike-ss** [comment]
v2.9.0 (https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.9.0) introduced another method: Getting the VPC ID based on a tag (known tag name + tag value). Use a more recent version (>= v2.9.2) if you are using AWS Shield.

I'll close this one due to:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/ba4152c1ba7c75be194d75cf343219d4aeaeb116/helm/aws-load-balancer-controller/values.yaml#L161
