### ISSUE TITLE
Support NLB TCP idle timeout

### ISSUE THREAD

**Issue by eaterm** [kubernetes-sigs/aws-load-balancer-controller#3843]
**Is your feature request related to a problem?**
We are using NLB's with services that have long running idle connections. 
Now we have configured some keepalive in the nginx controller. This is custom and the controller doesn't support it by default.

**Describe the solution you'd like**
Add support for the new AWS feature to change the idle timeout of a NLB.
https://aws.amazon.com/about-aws/whats-new/2024/09/aws-network-load-balancer-tcp-idle-timeout/

**Comment by andreybutenko** [comment]
Hi from the Elastic Load Balancing team! @wweiwei-li is actively working on adding support for this :) We will share details soon

**Comment by wweiwei-li** [comment]
Hey, the listener attributes support will be part of the v2.9.0 release, which is targeted for the end of sept now.
