### ISSUE TITLE
"kubectl apply -k" command described in v2.8.0 release note fails.

### ISSUE THREAD

**Issue by takawaha** [kubernetes-sigs/aws-load-balancer-controller#3849]
**Problem**
"kubectl apply -k" command described in v2.8.0 release note fails.
This appears to be an incorrect.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.8.0
> If you are upgrading the charts using helm upgrade, you need to update CRDs manually ```kubectl apply -k https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/crds/crds.yaml```

**Suggested Solution**
The following appears to be the correct command.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/main/helm/aws-load-balancer-controller#installing-the-chart
> ```shell script
> kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
> ```

**Comment by shraddhabang** [comment]
Thanks for bringing this to our attention. Updated the release notes.
