### ISSUE TITLE
AWS NLB-IP support for istio 1.21 +

### ISSUE THREAD

**Issue by parshva-shah-dsw** [kubernetes-sigs/aws-load-balancer-controller#3851]
We are currently using AWS NLB which is routing packets to worker node of EKS cluster which gives socket connection error whenever we scale PODs up or down. AWS team has recommended to use NLB-IP mode so traffic can be routed directly to POD ip and we will not face this issue. We are using Istio 1.21. My query is: Is Istio 1.21 certified to run with NLB-IP mode from AWS ? If yes, is there any documentation available for such deployment.

**Comment by shraddhabang** [comment]
@parshva-shah-dsw Yes you can use the Istio gateway with NLB-IP mode. Unfortunately, we don't have any documentation for it.
