### ISSUE TITLE
Explicitly set subnet and not use auto discovery

### ISSUE THREAD

**Issue by ketozhang** [kubernetes-sigs/aws-load-balancer-controller#3878]
**Is your feature request related to a problem?**
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/subnet_discovery/

Currently assigning subnets to your ALB requires access to adding tags to the VPC. This introduces challenges in permission (users does not control VPC, but only EKS) and organization (in IaC, should this action be performed by VPC stack, the EKS stack, or Helm stack)?

**Describe the solution you'd like**
Define the desired subnet(s) in Kubernetes files (Services and Ingress). Could this be possible with annotations? Can't we already specify subnets when creating ALBs through the ELB service?

**Comment by ketozhang** [comment]
There is already an annotation for this...
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#subnets

..., but not included in any of the guides.

**Comment by ChuksGrinage** [comment]
Thanks for bringing this to our attention. You are can specify your subnets using these annotations.
