### ISSUE TITLE
Publish Helm chart directly from this repository to Public ECR

### ISSUE THREAD

**Issue by bryantbiggs** [kubernetes-sigs/aws-load-balancer-controller#3880]
**Is your feature request related to a problem?**
- Publish Helm chart directly from this repository to Public ECR

**Describe the solution you'd like**
- Publish Helm chart directly from this repository to Public ECR so that we can remove the dependency on `eks-charts` 

- This chart should be published from this repository primarily due to 2 reasons:
    1. To deploy new versions of `aws-load-balancer-controller` artifacts in unison - both the image and the helm chart
    2. It is where the maintainers primarily operate and where users should come for feature requests, bugs/issues, documentation, etc.
    
The container image is already being published to Public ECR, the same should be done for the Helm chart which then allows both the image and the chart to be published together to Public ECR

We have opened a PR on the `eks-charts` repo to deprecate and remove this chart and direct users to this project going forward - https://github.com/aws/eks-charts/pull/1172

**Describe alternatives you've considered**
- None

**Comment by shraddhabang** [comment]
The new [release](https://github.com/aws/eks-charts/releases/tag/v0.0.182) has been cut on eks-charts. You should now be able to fetch the latest version.

**Comment by bryantbiggs** [comment]
no no no 😅 - @shraddhabang this isn't about the latest version. this is about moving away from the chart being hosted on the GitHub created chart index to Public ECR, and then any future chart releases are published directly from this repository to Public ECR

For example - node-termination-handler now does this https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler and we have been able to remove this from the `eks-charts` repository https://github.com/aws/eks-charts/pull/1155

**Comment by shraddhabang** [comment]
Sorry my bad. Just realised I added comment on the wrong one. :D
Yes I have read this already. Sorry about the confusion. I will reopen this one.

**Comment by oliviassss** [comment]
@bryantbiggs, hi we do not have plan to deprecate aws-load-balancer-controller chart from eks-chart as right now. Eventually we shall move to host our charts into public ECR, but it's not ready yet. And this will break users who relies on eks-chart to install the controller

**Comment by bryantbiggs** [comment]
> we do not have plan to deprecate aws-load-balancer-controller chart from eks-chart as right now. 

understood, and thats why the issue - to get it on the teams radar. Charts need to start moving out of `eks-charts` and into their respectie repositories where the source artifacts live and the teams own and maintain. please re-open the issue so we can track this effort to start publishing the chart directly from this repository - cc @M00nF1sh

**Comment by ksauzz** [comment]
@bryantbiggs

Hi,
I'm not sure why AWS teams is moving the charts to ECR even though causing breaking changes related to helm commands. I think this breaks some users' CI/CD and automation tools, and make customers unhappy. I already faced [some issue of NTH](https://github.com/aws/aws-node-termination-handler/issues/1085) related to OCI.

I hope any official helm chart should be published as standard helm registry, not as OCI.

Thank you.

**Comment by bryantbiggs** [comment]
its just like what is stated in the issue you linked - its better to control the artifacts from the source where they are created. `eks-charts` doesn't have an owner, and maintainers aren't actively looking there for questions, issues, or feature requests

**Comment by ksauzz** [comment]
Sorry to say but it sounds not reasonable to me for introducing breaking changes. And ECR couldn't be only choice as a destination. I imagine it was so tough to maintain the issues like eks-charts', but I wish AWS would care the compatibility for developers as well.
Thanks.

**Comment by mkilchhofer** [comment]
Why not anouncing it in the next minor version (maybe with Kubernetes default deprecation period of two minors)?

I think the OCI distribution method is now default for plenty of artifacts around the K8s ecosystem:
- container images
- sboms
- image attestation files (in-toto.io)
- Helm charts
- ...

@oliviassss / @M00nF1sh can you maybe reopen this issue?
