### ISSUE TITLE
Support NLB zonal shift

### ISSUE THREAD

**Issue by z0rc** [kubernetes-sigs/aws-load-balancer-controller#3909]
**Is your feature request related to a problem?**
https://aws.amazon.com/about-aws/whats-new/2024/10/cross-zone-network-load-balancer-zonal-shift-autoshift/

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/enable-zonal-shift.html

**Describe the solution you'd like**
Control this option via AWS LB Controller.

**Describe alternatives you've considered**
N/A

This should work nicely with newly released [EKS ARC zonal shift](https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-eks-application-recovery-controller-arc/).

**Comment by wweiwei-li** [comment]
Hey, to use this feature, it requires two steps.  First, enable configuration to allow zonal shift to act on your load balancer(s) using the NLB console or API. Second, trigger zonal shift or enable zonal autoshift for the chosen NLBs via Amazon Application Recovery Controller console or API.

**Comment by wweiwei-li** [comment]
Hey, to use this feature, it requires two steps. 
1. First,  enable configuration to allow zonal shift to act on your load balancer(s) using the NLB console or API. 
2. Second, trigger zonal shift or enable zonal autoshift for the chosen NLBs via Amazon Application Recovery Controller console or API.

In terms of controller: 

1. For step one, you can use annotation `service.beta.kubernetes.io/aws-load-balancer-attributes: zonal_shift.config.enabled=true ` to enable it via controller
2. For step two. it is not supported by controller now. you need to do it via Application Recovery Controller console , Application Recovery Controller API or ELB console.

**Comment by z0rc** [comment]
Thanks, I wasn't aware that zonal shift can be enabled via attributes, that simplifies things. Hopefully ARC side configuration will be supported by AWS LBC eventually.

**Comment by z0rc** [comment]
@wweiwei-li after reading further, NLB zonal shift also requires that target group attribute `unhealthy target connection termination` to be `off`. By default this attribute is `on`. Does AWS LBC support setting this attribute on target group (not listener)?

**Comment by z0rc** [comment]
Answering my own question, it's `service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: target_health_state.unhealthy.connection_termination.enabled=false`.

Also it's better to enable cross-zone load balancing on NLB when considerting zonal shift.

So Service requires following annotations for NLB to enable zonal shift:
```
service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true,zonal_shift.config.enabled=true
service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: target_health_state.unhealthy.connection_termination.enabled=false
```

**Comment by wweiwei-li** [comment]
Yes, That's correct. you can use `service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: target_health_state.unhealthy.connection_termination.enabled=false` to disable it.

**Comment by z0rc** [comment]
@shraddhabang please clarify why this was closed. Support of NLB zonal shift isn't complete, without configuration on the ARC side.

For example feature request for [PrivateLink support](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1859) is valid and open. And in also requires configuration changes outside of managed NLB, just like situation here.
