### ISSUE TITLE
Tagging process - Creation of resource then tag, or tagging at creation?

### ISSUE THREAD

**Issue by uk-rj** [kubernetes-sigs/aws-load-balancer-controller#3940]
**Describe the bug**
Our company has a product that alerts when certain resources are created without a minimum set of tags and this alert is firing when we create new NLBs through the ALB controller.

The tags are set via the default-tags attribute, a redacted version is below:
--default-tags=environment=prd,internal:name=the_name,created-by=aws-load-balancer-controller

When I look at the NLB I can see that the tags have all been applied and can see the tags being reflected in the AWS LB controller logs when it builds the model.

The people who manage the alert software state that the resource didn't have a tag at the point of alerting.

Please can you confirm, does the controller first create the NLB and then apply the tag as a separate step? Or does it create the NLB with the tags?  And does this still apply when using default-tags attribute as opposed to resource-tags in the annotation?

**Expected outcome**
The NLB/ALBs are tagged at the point of creation.

**Environment**
* AWS Load Balancer controller version - helm chart 1.9.2 / app version 2.9.2
* Kubernetes version 1.30
* Using EKS (yes/no), if so version? Yes, 1.30

**Additional Context**:

Thank you for your help!!!

**Comment by zac-nixon** [comment]
We create the tags during creation of the load balancer:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/pkg/deploy/elbv2/load_balancer_manager.go#L53-L63. Perhaps you are seeing eventual consistency delay between the tags system and the lb system.

**Comment by uk-rj** [comment]
Thank you @zac-nixon, really appreciate you coming back to me! This is really helpful.
