### ISSUE TITLE
Add CORS headers

### ISSUE THREAD

**Issue by fabgaubert** [kubernetes-sigs/aws-load-balancer-controller#3962]
Hi

I cannot find a way to add CORS headers with the ALB Controller.

It seems it's available in the ALB
https://aws.amazon.com/about-aws/whats-new/2024/11/aws-application-load-balancer-header-modification-enhanced-traffic-control-security/
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/header-modification.html

Is there any anotations for that feature ?

Regards

**Comment by shraddhabang** [comment]
@fabgaubert We support these in [v2.10.1](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.10.1).
Use this annotation annotation to set the headers on ALB. https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#listener-attributes
