### ISSUE TITLE
Endpoints Unreachable After Upgrading AWS Load Balancer Controller to Version 2.10.1

### ISSUE THREAD

**Issue by jnielsen-monster** [kubernetes-sigs/aws-load-balancer-controller#3967]
**Describe the bug**
When upgrading to AWS Load Balancer Controller version 2.10.1, the controller does not respect FIPS endpoints configured using the --aws-api-endpoints parameter. Instead, it defaults to standard non-FIPS endpoints (elasticloadbalancing.us-east-1.amazonaws.com). This issue did not occur in version 2.8.2.

**Steps to reproduce**
1. Install AWS Load Balancer Controller version 2.10.1 with the following parameter:
```
--aws-api-endpoints=elasticloadbalancing=https://elasticloadbalancing-fips.us-east-1.amazonaws.com,waf=https://waf-regional-fips.us-east-1.amazonaws.com,wafv2=https://wafv2-fips.us-east-1.amazonaws.com
```
2. Deploy services with LoadBalancer ingress configured.
3. Monitor CloudWatch logs for API requests made by the controller.
```
fields @timestamp, @message, @logStream, @log
| filter eventSource="elasticloadbalancing.amazonaws.com"  
| filter sessionCredentialFromConsole!="true"
| filter @message like /\"clientProvidedHostHeader\":\"elasticloadbalancing/
| sort @timestamp desc
| limit 100
```
4. Observe that `clientProvidedHostHeader` shows the non-FIPS endpoint:
```
elasticloadbalancing.us-east-1.amazonaws.com
```
**Expected outcome**
The controller should route API calls to the configured FIPS endpoints, such as `elasticloadbalancing-fips.us-east-1.amazonaws.com`.

**Environment**
- **AWS Load Balancer Controller version:**  
  - 2.8.2 (working as expected)  
  - 2.10.1 (issue observed)  
- **Kubernetes version:**  
  - 1.24
- **Using EKS:**  
  - Yes, version 1.24

**Additional Context**  
- This issue appears to coincide with the transition to AWS SDK for Go v2 introduced in version 2.9.  
- FIPS endpoints are critical for compliance requirements in our environment.  
- Manually testing FIPS endpoints from other Pods confirms their accessibility (`curl`, `ping`, etc.), so the issue appears specific to the controller's behavior.  
- Log output does not indicate any errors related to endpoint configuration.

Please advise on how to ensure FIPS endpoints are used in AWS Load Balancer Controller version 2.10.1.

**Comment by shraddhabang** [comment]
Hey @jnielsen-monster , Instead of using serviceName, can you try using a serviceID for setting the custom endpoints for ELB like this
```--aws-api-endpoints=Elastic Load Balancing v2=https://elasticloadbalancing-fips.us-east-1.amazonaws.com```

**Comment by jnielsen-monster** [comment]
You are right. Thank you so much.
