### ISSUE TITLE
Unknown ' "logger":"KubeAPIWarningLogger","msg":"unknown field \"spec.vpcID\""" ' warning message in AWS LB Controller log

### ISSUE THREAD

**Issue by cooloncoolon** [kubernetes-sigs/aws-load-balancer-controller#3970]
**Describe the bug**
There is an unknown ' "logger":"KubeAPIWarningLogger","msg":"unknown field \"spec.vpcID\"" ' warning message in AWS LB Controller logs everytime the lead controller pod starts.
However the vpcId discovers correctly, so it seems the AWS LB works as expected. And even if I set the vpcId explicitly via values, the warning message in still in AWS LB Controller log.

**Steps to reproduce**

Deploy AWS LB Controller v 2.10.1 and check pod logs

**Expected outcome**
no "KubeAPIWarningLogger","msg":"unknown field \"spec.vpcID\" ' warning message in AWS LB Controller log

**Environment**

* AWS Load Balancer controller version 
> v2.10.0
* Kubernetes version
> 1.29 
* Using EKS (yes/no), if so version?
> EKS used - yes, eks.23 

**Additional Context**:
n/a

**Comment by zac-nixon** [comment]
Hi! Did you upgrade your cluster? The CRD definition was updated ~9 months ago to add this new field.
https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/ac21af638efdbf378f194b88ed12b70b5b0ae50a

It's possible that you have the wrong CRD definition installed.

**Comment by cooloncoolon** [comment]
indeed CRDs were not upgraded to the latest version. we had to explicity instruct flux to upgrade CRDs in this aws lb controller helmrelease.
all works now, issue can be closed

**Comment by cooloncoolon** [comment]
indeed CRDs were not upgraded to the latest version. we had to explicity instruct flux to upgrade CRDs in this aws lb controller helmrelease.
all works now, issue can be closed
