### ISSUE TITLE
Unable to scale beyond 1000 pods.

### ISSUE THREAD

**Issue by yuvraj9** [kubernetes-sigs/aws-load-balancer-controller#3984]
Hi,

EKS - 1.29
AWS load balancer controller version - 2.8.1

Our deployment is unable to add more than 1000 targets in target group of load balancer. We have pod readiness gates enabled and pods after 1000 stays in unready state. Our targets per targetgroup limit is already set to 1800.

We tried scaling deployment to 1500 but even when pods are in Running state they are not getting added in target group.

```
kubectl get pods
NAME                                          READY   STATUS             RESTARTS           AGE     IP               NODE                                                NOMINATED NODE   READINESS GATES
xxx-primary-xxx-wkzkg          4/4     Running            0                  14m     IP    xxx    <none>           0/1
xxx-primary-xxx-wmscb          4/4     Running            0                  14m     IP   xxx    <none>           0/1
```

<img width="1227" alt="image" src="https://github.com/user-attachments/assets/667953f2-d635-4278-99ac-6a29b71fc28c" />

**Comment by staizen-stephen** [comment]
This is the default service quota for an ALB target group. Have you already requested an increased quota on your account?

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html

**Comment by aravindsagar** [comment]
Hi, apart from the targets per target group limit, there's also a Targets per Application Load Balancer limit which is set to 1000 by default. Please see https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html and request an increase.

**Comment by ubarar-poolside** [comment]
Running into the same issue here as well, @yuvraj9. @aravindsagar, we're using NLBs and have all our of limits increased to well beyond 1k.

I see no error logs from the load balancer controller, nor in CloudTrail. This feels like a limitation inside the controller.

**Comment by zac-nixon** [comment]
Nice catch @staizen-stephen! This is the relevant k8s docs that explain the limit: https://kubernetes.io/docs/concepts/services-networking/service/#over-capacity-endpoints. The controller does support endpoint slices, it's not enabled by default.

https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/configurations/

in your lbc deployment file:
```
- --enable-endpoint-slices
```

add this the lbc container args.

**Comment by staizen-stephen** [comment]
> Nice catch @staizen-stephen! This is the relevant k8s docs that explain the limit: https://kubernetes.io/docs/concepts/services-networking/service/#over-capacity-endpoints. The controller does support endpoint slices, it's not enabled by default.
> 
> https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/configurations/
> 
> in your lbc deployment file:
> ```
> - --enable-endpoint-slices
> ```
> 
> add this the lbc container args.
> 
Just to be clear, it wasn't my catch. I was also focused on the AWS quotas. I'm just repeating what another contributor identified.

**Comment by ubarar-poolside** [comment]
Thank you @staizen-stephen, this was the culprit for us as well. We're using the [helm chart](https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller), and added `enableEndpointSlices: true` to our values file.
