### ISSUE TITLE
Will the security group described by '[k8s] Shared Backend SecurityGroup for LoadBalancer' be revoked?

### ISSUE THREAD

**Issue by ma345564280** [kubernetes-sigs/aws-load-balancer-controller#3988]
Will the security group described by '[k8s] Shared Backend SecurityGroup for LoadBalancer' be revoked if add some security group rules to it manually?

What's the best practice of adding rules to this security group?My use case is  combine the nginx ingress controller with aws-load-balance-controller.

**Comment by ma345564280** [comment]
AWS LBC create [k8s] Managed SecurityGroup for LoadBalancer and [k8s] Shared Backend SecurityGroup for LoadBalancer automatically. Base on my observe, When I add rules to '[k8s] Managed SecurityGroup', they will be revoked. If we add rules to ' [k8s] Shared Backend SecurityGroup for LoadBalancer ', they won't be revoked.


Is this behavior the default behavior of AWS LBC?

**Comment by ma345564280** [comment]
I create a new nlb by aws lbc and see the shared security group attached to the new nlb as well. is that possible to add new rules to this sg based on the ingress?

**Comment by zac-nixon** [comment]
You are free to change the the security group rules as you see fit. The LBC will only manage rules with description `[k8s] Managed SecurityGroup'`. If you add the description manually, the LBC will try to manage those rules as well.

**Comment by ma345564280** [comment]
thank you zac-nixon for your clarification
