### ISSUE TITLE
Intermittent timeouts

### ISSUE THREAD

**Issue by syst0m** [kubernetes-sigs/aws-load-balancer-controller#779]
I'm experiencing intermittent timeouts with the alb ingress resource.
I've configured an external http monitor, and am shipping alb access logs and k8s cluster logs to Sumo Logic.
When the timeouts occur, it looks like the request doesn't reach the nginx pod.
However, in the alb access logs I can't see anything wrong during the exact timestamp  during which there was a a timeout reported by the external http monitor.
I managed to reproduce the timeout manually from my terminal:
`curl -IL http://myhost.com curl: (52) Empty reply from server`

The http monitor states there was a connection timeout. 
I don't see any errors caught by AWS LB monitor as well, from the AWS console.

**Comment by syst0m** [comment]
@M00nF1sh 
The reason some of the requests to alb are failing is that one of the subnets being chosen via tags is in fact a private subnet, not a public subnet.
There's 3 availability zones, the two with the public subnets are working properly, the request fails when alb redirects it to the private subnet.
For my EKS cluster I have 3 public and 3 private subnets in 3 availability zones.
In my terraform config, I have setup tags for all of those subnets, because I wasn't sure if alb needs both private and public subnets. 
Should I just tag the public subnets? Documentation is a bit unclear about this.

**Comment by M00nF1sh** [comment]
Hi, you should tag public subnets with 'kubernetes.io/role/elb:1', 
and tag private subnets with `'kubernetes.io/role/internal-elb:1' 
😄
